构建设计系统和组建库
xitu/gold-miner pull request #7318
Opened 2020-08-20 13:18 UTC by Charlo-O

构建设计系统和组建库

译文翻译完成，resolve #id

2020-08-27 10:18 UTC, snow1991bloom commented
@lsvih 校对认领

2020-08-27 10:18 UTC, fanyijihua commented
@snow1991bloom 好的呢 :beer:

2020-08-29 03:49 UTC, Chorer commented
@fanyijihua 校对认领

2020-08-29 03:49 UTC, fanyijihua commented
@Chorer 妥妥哒 :beers:

2020-08-29 07:14 UTC, Chorer reviewed
@Charlo-O  @lsvih  校对完毕。文章很长，译者辛苦了，但是翻译存在大量问题，包括上下文衔接不当、语义不明、翻译风格不统一（同一个词出现三种不同译法）等，总体读起来比较生硬。建议译者在翻译完之后自己需要重新阅读一遍，例如标点符号等问题可以自查并修正，不然会给校对者留下大量工作。

2020-08-29 07:14 UTC, Chorer commented on article/2020/building-a-design-system-and-a-component-library.md
> +在我们看来，构建一个设计系统和一个组件库是值得的。它带来了我们从一开始就在寻找的一致性设计。这并不意味着我们会把它推荐给所有人。在开始之前，我们建议你确保这是你项目的正确解决方案。我们会说，只有当你知道或期望产品需要大量不同的页面，这些页面具有重用相同组件的复杂交互时，才需要这样做。当你还是一家初创公司或小公司，并希望在未来几年扩大规模时，这一点尤其重要。然而，如果你期望你的产品是一个简单的网站
```suggestion
在我们看来，构建一个设计系统和一个组件库是值得的。它带来了我们从一开始就在寻找的一致性设计。这并不是说我们会推荐所有人去做这件事，在决定开始构建之前，你必须确保这是你项目的正确解决方案。只有当你知道或期望产品需要大量不同的页面，并且这些页面具有重用相同组件的复杂交互时，才需要这样做。当你的公司还是一家初创公司或小公司，并希望在未来几年扩大规模时，这种评估尤其重要。然而，如果你期望中的产品只是一个简单的网站，在几年之内不会有太大的变化，那么就可能有些过犹不及了。
```

2020-08-29 12:02 UTC, snow1991bloom requested changes

2020-08-29 12:05 UTC, snow1991bloom commented
@Charlo-O @lsvih @Chorer 校对完毕。与Chorer在文中的修改意见基本相同，需要讨论的地方也都给出了翻译建议。

2020-08-29 14:08 UTC, Chorer commented on article/2020/building-a-design-system-and-a-component-library.md
> +为了记录我们的选择，我们在 Material UI 组件指南中为每个组件(不管它是原子、分子还是有机体)创建了指南。在组件指导方针的旁边，我们还有一些适用于所有组件的通用指导方针，因为有些指导方针是超越的，比如可访问性和声调。这些指导方针是我们唯一的真理来源。他们确保没有任何东西可以留给想象力。为了给人留下印象，这是一份简单的文件，包括以下部分：
> 在组件指导方针的旁边，我们还有一些适用于所有组件的通用指导方针，因为有些指导方针是超越的，比如可访问性和声调。
> =>
> 紧接着组件指导方针，我们还有一些适用于所有组件的通用指导方针，因为有些指导方针是非常重要的，比如可访问性和风格定位。
> 
> “tone of voice”在原文并未特指用于形容网站，品牌语调确实有点难理解，"风格定位"可能比较容易被读者识别？

1. 文章说的就是旧网站项目的重构，句子中的“可访问性”也说明了这一点，虽然原文这里没有说明，但不意味着翻译的时候不可以进行补充
2. “风格定位”的翻译也挺好的

2020-08-29 14:12 UTC, Chorer commented on article/2020/building-a-design-system-and-a-component-library.md
> +在我们的设计系统和组件库中，我们都按按钮、颜色、表单元素、布局、链接、排版等类别对组件进行分组。这有助于将不同的原子、分子和组织，同时也有助于设计师和开发人员之间的交流。
> 在我们的设计系统和组件库中，我们都按按钮、颜色、表单元素、布局、链接、排版等类别对组件进行分组。
> =>
> 在我们的设计系统和组件库中，我们都按照类别将组件进行分组，例如按钮、颜色、表单元素、布局、链接、排版等。
> 
> 分类不知这几种，还有插画，图标等，所以这里的"like"不建议丢掉，同时将例子后置，避免句子过长难以理解。

其实这里的“等”已经表达了“不止这几种分类”的意思，不过确实按照你的译法会更好。

2020-08-29 14:14 UTC, Chorer commented on article/2020/building-a-design-system-and-a-component-library.md
> +在我们看来，构建一个设计系统和一个组件库是值得的。它带来了我们从一开始就在寻找的一致性设计。这并不意味着我们会把它推荐给所有人。在开始之前，我们建议你确保这是你项目的正确解决方案。我们会说，只有当你知道或期望产品需要大量不同的页面，这些页面具有重用相同组件的复杂交互时，才需要这样做。当你还是一家初创公司或小公司，并希望在未来几年扩大规模时，这一点尤其重要。然而，如果你期望你的产品是一个简单的网站
> 在开始之前，我们建议你确保这是你项目的正确解决方案。
> =>
> 在开始之前，我们建议你确保这对于你的项目而言是的正确解决方案。

=> 在开始之前，我们建议你确保这对于你的项目而言是正确的解决方案。

2020-10-15 15:13 UTC, lsvih commented
@Charlo-O 麻烦您抽空看看这儿的校对意见吧 XD

2021-02-01 04:51 UTC, lsvih approved these changes

2021-02-01 04:51 UTC, merged

2021-02-01 04:54 UTC, lsvih commented
已发布：https://juejin.cn/post/6924152501805678606 

@Shirley-He-Maker @Chorer 感谢校对，本文部分翻译积分作为校对积分