自己写一个 redux
xitu/gold-miner pull request #7386
Opened 2020-09-07 08:30 UTC by tanglie1993

译文翻译完成，resolve #7279

2020-09-07 13:02 UTC, Inchill commented
@tanglie1993 @lsvih 校对认领

2020-09-10 10:22 UTC, nia3y commented
校对认领 @fanyijihua @lsvih

2020-09-10 10:47 UTC, lsvih commented
@nia3y 好的！

2020-09-12 11:50 UTC, nia3y reviewed
@tanglie1993 @lsvih 校对完成
希望译者注意下格式问题[wiki 百科](https://github.com/xitu/gold-miner/wiki)

2020-09-12 11:50 UTC, nia3y commented on article/2020/how-to-build-redux.md
> +没什么好看的。我们可以把 props 输入给这些组件，并且渲染它们。但是我们来看一下 `openNoteId` 属性以及这些 `onOpenNote` 和 `onCloseNote` 回调。我们需要决定状态和回调在哪里。我们可以使用组件状态，没问题。一旦你开始使用 Redux，就没有规定说 **所有** 的状态都需要放到 Redux store 中。如果你想知道什么时候使用 store 状态，只
```suggestion
没什么好看的。我们可以把 props 输入给这些组件，并且渲染它们。但是我们来看一下传入的 `openNoteId` 属性以及这些 `onOpenNote` 和 `onCloseNote` 回调。我们需要决定状态和回调在哪里。我们可以使用组件状态，没问题。一旦你开始使用 Redux，就没有规定说**所有**的状态都需要放到 Redux store 中。如果你想知道什么时候使用 store 状态，只要问自己：
```

2020-09-12 11:50 UTC, nia3y commented on article/2020/how-to-build-redux.md
> +有时候 Redux 很适用于易变的状态。特别是状态需要随着 store 的改变而改变时，把它存放在 store 中可能更容易一些。对于我们的应用而言，当我们创建一个笔记时，我们需要把 `openNoteId` 赋值给它的 id。在组件中做这件事很笨拙，因为我们需要在 `componentWillReceiveProps` 中监控 store 状态的变化。我并不是说这是错的，只是这样很笨拙。所以对
```suggestion
有时候 Redux 很适用于易变的状态。特别是状态需要随着 store 中状态的改变而改变时，把它存放在 store 中可能更容易一些。对于我们的应用而言，当我们创建一个笔记时，我们需要把 `openNoteId` 设置为新的笔记 id。在组件中做这件事很笨拙，因为我们需要在 `componentWillReceiveProps` 中监控 store 状态的变化。我并不是说这是错的，只是这样很笨拙。所以对于我们的应用，我们将把 `openNoteId` 保存在 store 状态中。(在真实的 app 中，我们可能需要路由。看一下[这个帖子的结尾](#routing)来了解一下。）
```

2020-09-12 11:50 UTC, nia3y commented on article/2020/how-to-build-redux.md
> +所以我们需要一种方式把S context 转化成 prop。这就是 `connect` 的作用。
```suggestion
所以我们需要一种方式把 context 转化成 props。这就是 `connect` 的作用。
```

2020-09-12 11:50 UTC, nia3y commented on article/2020/how-to-build-redux.md
> +这有一点点复杂。说实话，和真正的实现相比，我们偷懒了 **很多**。（我们将在 [结尾](#performance)讨论。）但这已经和大概的原理很接近了。 `connect` 是一个 [高阶组件](https://facebook.github.io/react/docs/higher-order-components.html)。实际上，它更像是高阶组件的工厂。它接收两个函数，并返回一个以组件
```suggestion
这有一点点复杂。说实话，和真正的实现相比，我们偷懒了**很多**。（我们将在[结尾](#performance)讨论。）但这已经和大概的原理很接近了。`connect` 是一个[高阶组件](https://facebook.github.io/react/docs/higher-order-components.html)。实际上，它更像是高阶函数。它接收两个函数，并返回一个以组件为输入，新的组件为输出的函数。这个组件订阅 store，并且在发生改变时更新你的组件的 props。开始使用它吧，它会变得更实用的。
```

2020-09-12 11:50 UTC, nia3y commented on article/2020/how-to-build-redux.md
> +传给 `connect` 的首个函数 (`mapStateToProps`) 从我们的 `store` 中获取当前的 `state` 并返回一些 prop。第二个传给 `connect` 的函数 (`mapDispatchToProps`) 获取我们 `store` 的 `dispatch` 方法，并返回一些 prop。这给了我们一个新的函数，并且我们的组件传给这个函数。我们把组件传给这个函数。
```suggestion
传给 `connect` 的首个函数 (`mapStateToProps`) 从我们的 `store` 中获取当前的 `state` 并返回一些 props。第二个传给 `connect` 的函数（`mapDispatchToProps`）获取我们 `store` 的 `dispatch` 方法，并返回一些 props。这给了我们一个新的函数，并且我们的组件传给这个函数。我们把组件传给这个函数。这给了我们一个新的组件，它将会自动获取所有这些 props（加上我们额外传入的部分）。
```

2020-09-12 11:50 UTC, nia3y commented on article/2020/how-to-build-redux.md
> +很好！我们的 `store` 被在顶部传入一次，然后 `connect` 把它接过来完成了所有的工作。声明式编程万岁！ [这是我们的应用](https://jsfiddle.net/justindeal/srnf5n20/10/)，他已经用 `Provider` 和 `connect` 清理过了。
```suggestion
很好！我们的 `store` 被在顶部传入一次，然后 `connect` 接收 `store` 来完成所有的工作。声明式编程万岁！[这是我们的应用](https://jsfiddle.net/justindeal/srnf5n20/10/)，他已经用 `Provider` 和 `connect` 整理好了。
```

2020-09-12 11:50 UTC, nia3y commented on article/2020/how-to-build-redux.md
> +现在我们已经写了一些很实用的东西。但是还缺了一块。在某些环节，我们需要和服务器交流。我们的 action 是同步的。我们如何发出 **异步** action呢？很好，我们可以在组件中获取数据，但是这有一些问题。
```suggestion
现在我们已经写了一些很实用的东西。但是还缺了一块。在某些环节，我们需要和服务器通信。我们的 action 是同步的。我们如何发出**异步** action 呢？很好，我们可以在组件中获取数据，但是这有一些问题。
```

2020-09-12 11:50 UTC, nia3y commented on article/2020/how-to-build-redux.md
> +Redux 是同步的，我们应该怎么做呢？把一些东西放在 dispatch 操作之间，并用来改变 store 状态。这些东西就是中间件。
```suggestion
Redux 是同步的，我们应该怎么做呢？把一些东西放在 dispatch 和改变 store 状态的操作之间。这就是中间件。
```

2020-09-12 11:50 UTC, nia3y commented on article/2020/how-to-build-redux.md
> +我们需要把中间件传给 store 的一种方式。所以我们开始干吧。
```suggestion
我们需要一种把中间件传给 store 的方式。所以我们开始干吧。
```

2020-09-12 11:50 UTC, nia3y commented on article/2020/how-to-build-redux.md
> +我们创建一个 "重新dispatch" 的函数。
```suggestion
我们创建一个“重新 dispatch ”的函数。
```

2020-09-12 11:50 UTC, nia3y commented on article/2020/how-to-build-redux.md
> +这是另一个修改对象的例子，它可以简化问题。Redux 可以破坏规则，只要它能够帮助开发者遵循规则。:-)
注：这三个是一段的，希望修改一下

2020-09-12 11:50 UTC, nia3y commented on article/2020/how-to-build-redux.md
> +这调用了中间件，传给它一个能访问 "重新dispatch" 函数和 `getState` 函数的对象。这个中间件应该返回一个新的函数，它接收调用下一个 dispatch 函数的函数（在这里就是原始的 dispatch 函数）。如果你读到这里觉得头晕了，不要担心。创建和使用中间件实际上是很容易的。
```suggestion
这调用了中间件，传给它一个能进行“re-dispatch ”的函数和 `getState` 的函数。这个中间件应该返回一个新的函数，拥有用来接收调用下一个 dispatch 函数的能力（在这里就是原始的 dispatch 函数）。如果你读到这里觉得头晕了，不要担心。创建和使用中间件实际上是很容易的。
```

2020-09-13 17:56 UTC, rachelcdev commented
@lsvih 校对认领

2020-09-13 18:25 UTC, lsvih commented
@rachelcdev 好的！

2020-10-14 14:57 UTC, JohnieXu commented
@lsvih 校对认领

2020-10-14 15:21 UTC, lsvih commented
@JohnieXu 好的~

2020-10-18 00:29 UTC, JohnieXu requested changes
通篇校对下来，发现整篇文章就是用翻译工具翻译的，这会给校对者增加非常多的工作量。建议下：即使采用翻译工具翻译的，也最好翻译者自己仔细阅读以下译文。

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +这调用了中间件，传给它一个能访问 "重新dispatch" 函数和 `getState` 函数的对象。这个中间件应该返回一个新的函数，它接收调用下一个 dispatch 函数的函数（在这里就是原始的 dispatch 函数）。如果你读到这里觉得头晕了，不要担心。创建和使用中间件实际上是很容易的。
```suggestion
这调用了中间件，传给它一个能重新派发 action 的函数和 `getState` 的函数。这个中间件应该返回一个新的函数，拥有用来接收调用下一个 dispatch 函数的能力（在这里就是原始的 dispatch 函数）。如果你读到这里觉得头晕了，不要担心。创建和使用中间件实际上是很容易的。
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +这不是个优雅的函数，但你应该可以跟得上。首先需要注意的是它接收一个中间件的列表，并返回一个中间件函数。这个新的中间件函数和早先的中间件有同样的签名。它接收一个 store (只是我们的重新 `dispatch` 和 `getState` 方法，不是整个 store） 并返回另一个函数。对于这个函数：
```suggestion
这不是个优雅的函数，但你应该可以跟得上。首先需要注意的是它接收一个中间件的列表，并返回一个中间件函数。这个新的中间件函数和之前的中间件有同样的签名。它接收一个 store（只包含新的派发 action 的 `dispatch` 和 `getState` 方法，不是整个 store）并返回另一个函数。对于这个函数：
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +1. 如果我们没有中间件，返回一个恒等函数。基本上只是一个什么都不做的中间件。很蠢，但我们只是防止人们搞破坏。
```suggestion
1. 如果我们没有中间件，返回和原来一样的函数。基本上只是一个什么都不做的中间件。很蠢，但我们只是防止人们搞破坏。
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +好了，现在我们可以使用所有想用的中间件了。
```suggestion
好了，现在我们可以按预期使用所有的中间件了。
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +我们来做些真的异步操作吧。在此介绍一种 "thunk" 中间件：
```suggestion
我们来做些真的异步操作吧。在此介绍一种“thunk”中间件：
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +"Thunk" 真的只是 "函数" 的另一个名称，但是它通常意味着 "封装了一些未来处理的工作的函数"。如果我们加入 `thunkMiddleware`：
```suggestion
“Thunk”真的只是“函数”的另一个名称，但是它通常意味着“封装了一些未来处理的工作的函数”。如果我们加入 `thunkMiddleware`：
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +  // 从 state 中获取东西
```suggestion
  // 从 state 中取数据
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +  // 根据获取到的东西从服务端拉取数据
```suggestion
  // 根据获取到的数据从服务端拉取数据
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +      // 任何时候都可以发出去
```suggestion
      // 任何时候都可以派发 action
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +Thunk 中间件是一柄大锤。我们可以把任何东西从 state 中拉出来，并在任何时候把任何 action 派发出去。很有弹性，但随着你的 app 变得越来越大，它 **可能** 变得危险。但从这里开始挺好的。我们用它来做一些异步操作吧。
```suggestion
Thunk 中间件是一柄大锤。我们可以把任何东西从 state 中拉出来，并在任何时候把任何 action 派发出去。这十分方便灵活，但随着你的 app 变得越来越大，它**可能**变得危险。但从这里开始挺好的。我们用它来做一些异步操作吧。
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +你自己写了一个 Redux！看起来我们写了很多代码，但是主要是我们的 reducer 和组件。我们实际的 Redux 实现还不到140 [140 行](https://gist.githubusercontent.com/jdeal/c224026df3bae5803fd9e58cbbd4a60b/raw/623150cb62a7076e78904881b61d4c948639abe8/mini
```suggestion
你自己写了一个 Redux！看起来我们写了很多代码，但是主要是我们的 reducer 和组件。我们实际的 Redux 实现还不到 [140 行代码](https://gist.githubusercontent.com/jdeal/c224026df3bae5803fd9e58cbbd4a60b/raw/623150cb62a7076e78904881b61d4c948639abe8/mini-redux.js)。这包括了我们的 thunk 和日志中间件，空行，和注释！
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +我们的实现所缺少的是，监听特定属性是否真的改变了的能力。对于我们的示例应用而言，这没关系，因为每个状态变化都造成了属性的改变。但对于有很多 `mapStateToProps` 函数的大型应用而言，我们只想要在组件真的接收新属性时更新。要扩展我们的 `connect` 函数来实现这一点是很容易的。我们只需要在调用 `setState` 时比较前后的数据即可。我们需要更聪明地使用 `mapDispa
```suggestion
我们的实现所缺少的是，监听特定属性是否真的改变了的能力。对于我们的示例应用而言，这没关系，因为每个状态变化都造成了属性的改变。但对于有很多 `mapStateToProps` 函数的大型应用而言，我们只想要在组件真的接收新属性时更新。要扩展我们的 `connect` 函数来实现这一点是很容易的。我们只需要在调用 `setState` 时比较前后的数据即可。我们需要更聪明地使用 `mapDispatchToProps`。注意，我们每次都在创建新的函数。真正的 React Redux 库会检查函数的参数，看看它是否依赖`属性`。这样，如果属性没有真的改变，就不需要再做一次映射。
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +如果你使用纯 JS 数据（不是像 Immutable.js 这样的东西），那么我遗漏的一个很重要的细节是在开发时冻结 reducer 状态。因为这是 JavaScript，没有什么阻止你在从 store 中获取状态之后改变它。你可以在 `render` 方法或者别的任何东西中改变它。这会造成非常糟糕的结果，并且毁坏一些正在通过 Redux 加入的可预见性。我是这样做的：
```suggestion
如果你使用原始 JS 数据（不是像 Immutable.js 这样的东西），那么我遗漏的一个很重要的细节是在开发时冻结 reducer 状态。因为这是 JavaScript，没有什么阻止你在从 store 中获取状态之后改变它。你可以在 `render` 方法或者别的任何东西中改变它。这会造成非常糟糕的结果，并且毁坏一些正在通过 Redux 加入的可预见性。我是这样做的：
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +这创建了一个冻结了结果的 reducer。这样，如果你想要改变组件中的 store状态，它将会在开发时抛出错误。过一段时间，你将能够避免这些错误。但如果你新接触不可变数据，这可能是最容易的练习方式了，对于你和你的团队来说都是如此。
```suggestion
这创建了一个冻结了结果的 reducer。这样，如果你想要改变组件中的 store状态，它将会在开发环境报错。过一段时间，你将能够避免这些错误。但如果你新接触不可变数据，这可能是最容易的练习方式了，对于你和你的团队来说都是如此。
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +就好像我们的高阶函数还是不够多一样，Redux 还有一个我们遗漏掉的。"store 增强器" 是一个高阶函数，接收一个 store 创建器并返回一个 "增强版" store 创建器。这不是一个常见的操作，但它可以被用来创造 Redux 开发者工具之类的东西。 `applyMidleware` [**真正的**实现](https://github.com/reactjs/redux/blob/4d
```suggestion
就好像我们的高阶函数还是不够多一样，Redux 还有一个我们遗漏掉的。“store 增强器”是一个高阶函数，接收一个 store 创建器并返回一个”增强版“store 创建器。这不是一个常见的操作，但它可以被用来创造 Redux 开发者工具之类的东西。 `applyMidleware` [**真正的**实现](https://github.com/reactjs/redux/blob/4d8700c9631b152f0dff384d528a6c7f74024418/src/applyMiddleware.js?utm_source=zapier.com&utm_medium=referral&utm_campaign=zapier) 就是一个 store 增强器。
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +我们在有数字键的对象中保存我们的笔记。这意味着每一个 JS 引擎都会按照创建的顺序来给它们排序。如果我们的服务器返回 GUID 或者其它未排序的键，我们将很难排序。我们不想把笔记存放在数组中，因为要通过 id 获取特定笔记就不容易了。所以对于真实应用而言，我们可能需要用数组存放排好序的 id。另外，我们也可能可以使用数组，如果用 `reselect` 来缓存 `find` 操作结果的话。
```suggestion
这款笔记应用目前是将数据保存在以数字作为 key 的对象中。这意味着每一个 JS 引擎都会按照创建的顺序来给它们排序。如果我们的服务器返回 GUID 或者其它未排序的键，我们将很难排序。我们不想把笔记存放在数组中，因为要通过 id 获取特定笔记就不容易了。所以对于真实应用而言，我们可能需要用数组存放排好序的 id。另外，我们也可能可以使用数组，如果用 `reselect` 来缓存 `find` 操作结果的话。
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +### 副作用和 Action 创建器
```suggestion
### Action 创建器的副作用
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +别这样做。一个返回了 promise 的函数已经开始做这个操作了(除非它是个不正常的懒 promise)。这意味着我们阻止了任何中间件来处理这个 action。比如，我们就不能使用节流中间件。另外我们也不能正常使用回放，因为这需要关闭 dispatch 函数。但是任何调用这个 `dispatch` 的代码都已经完成了工作，所以不能把它停掉。
```suggestion
别这样做。一个返回了 promise 的函数已经开始做这个操作了（除非它是个不正常的延迟 promise）。这意味着我们阻止了任何中间件来处理这个 action。比如，我们就不能使用节流中间件。另外我们也不能正常使用回放，因为这需要关闭 dispatch 函数。但是任何调用这个 `dispatch` 的代码都已经完成了工作，所以不能把它停掉。
```

2020-10-18 00:29 UTC, JohnieXu commented on article/2020/how-to-build-redux.md
> +### 路由
这里的行号错位了，请检查下

2020-10-18 00:30 UTC, JohnieXu commented
@lsvih @tanglie1993 校对完成，希望能修改一下

2020-10-21 14:08 UTC, tanglie1993 commented
@lsvih 修改完毕。

2020-10-24 15:00 UTC, lsvih commented
@tanglie1993 啊这篇文章中间还有几十个校对意见没有修改或者回应呢= =您是不是漏了

2021-01-17 09:43 UTC, lsvih commented on article/2020/how-to-build-redux.md
> +现在你可以看到，我们为什么使用常量而不是字符串。我们对于 action 的检测比 Redux 更宽松，但也足以保证我们不拼错 action 类型。如果我们传入字符串，action 将会直接进入 reducer 的默认分支，什么都不会发生，错误可能会被忽视。但如果我们使用常量，拼写错误将会成为 `undefined`，这将会抛出一个错误。所以我们会马上知道，并且修复它。
```suggestion
现在你可以看到，我们为什么使用常量而不是字符串。我们对于 action 的检测比 Redux 更宽松，但也足以保证我们不拼错 action 类型。如果我们传入字符串，action 将会直接进入 reducer 的默认分支，什么都不会发生，错误可能会被忽视。但如果我们使用常量，拼写错误将会导致返回 `undefined` 并会抛出错误，让我们立刻发现错误并修复它。
```

2021-01-31 13:55 UTC, lsvih approved these changes

2021-01-31 13:55 UTC, merged

2021-01-31 14:03 UTC, lsvih commented
已发布：https://juejin.cn/post/6923922875191656462