5个鲜为人知的 Chrome 开发工具的特性
xitu/gold-miner pull request #7418
Opened 2020-09-15 16:34 UTC by Amy-Designer

以后一条，即第5条的图片加载可能有点问题

译文翻译完成，resolve #7410

2020-09-16 01:56 UTC, lsvih commented
![0*bZm_fnZYh8CzTIe-](https://user-images.githubusercontent.com/5164225/93283292-d2e3f800-f802-11ea-85ee-6959bdea35ba.gif)

用这个链接替换一下第五个图吧：`![0*bZm_fnZYh8CzTIe-](https://user-images.githubusercontent.com/5164225/93283292-d2e3f800-f802-11ea-85ee-6959bdea35ba.gif)`

2020-09-16 04:08 UTC, Amy-Designer commented
> ![0*bZm_fnZYh8CzTIe-](https://user-images.githubusercontent.com/5164225/93283292-d2e3f800-f802-11ea-85ee-6959bdea35ba.gif)
> 
> 用这个链接替换一下第五个图吧：`![0*bZm_fnZYh8CzTIe-](https://user-images.githubusercontent.com/5164225/93283292-d2e3f800-f802-11ea-85ee-6959bdea35ba.gif)`

已修复～

2020-09-16 09:34 UTC, x1ny commented
@lsvih 校对认领

2020-09-17 02:59 UTC, lsvih commented
@x1ny 好的！

2020-09-17 15:10 UTC, x1ny reviewed
@lsvih @Shirley-He-Maker 校对完成

2020-09-17 15:10 UTC, x1ny commented on article/2020/5-lesser-known-features-of-chrome-devtools.md
> +打开设计模式，你可以直接编辑所有内容
[打开设计模式] => [开启设计模式]

2020-09-19 12:09 UTC, calali commented
@lsvih 校对认领

2020-09-19 16:31 UTC, lsvih commented
@calali 好的！

2020-09-21 01:10 UTC, calali requested changes

2020-09-21 01:10 UTC, calali commented on article/2020/5-lesser-known-features-of-chrome-devtools.md
> +打开设计模式，你可以直接编辑所有内容
designMode不应该翻译，因为这是js的API。因此这句话应该翻译为：使用designMode，你可以直接编辑所有内容。

2020-09-21 01:10 UTC, calali commented on article/2020/5-lesser-known-features-of-chrome-devtools.md
> +# 5个鲜为人知的 Chrome 开发工具的特性
Devtools通常翻译为开发者工具，参考信息：https://www.google.com/search?q=Devtools+%E4%B8%AD%E6%96%87&oq=Devtools+%E4%B8%AD%E6%96%87&aqs=chrome..69i57.3698j0j1&sourceid=chrome&ie=UTF-8

2020-09-21 01:10 UTC, calali commented on article/2020/5-lesser-known-features-of-chrome-devtools.md
> +## 1. 切换类
这一点里面的classes成为类名更好一些，因为指的是css的类名，看到类更容易理解为es6的Class。下面的classes翻译也是。

2020-09-21 16:03 UTC, Shirley-He-Maker commented on article/2020/5-lesser-known-features-of-chrome-devtools.md
> +## 1. 切换类
已全部修改～

2020-09-21 16:04 UTC, Shirley-He-Maker commented on article/2020/5-lesser-known-features-of-chrome-devtools.md
> +打开设计模式，你可以直接编辑所有内容
已修改，谢谢建议～

2020-09-21 16:05 UTC, Shirley-He-Maker commented
@lsvih @calali 修改完成，辛苦各位

2020-09-21 16:05 UTC, lsvih commented on article/2020/5-lesser-known-features-of-chrome-devtools.md
>  > * 校对者：
请增加校对者信息

2020-09-21 16:05 UTC, lsvih commented on article/2020/5-lesser-known-features-of-chrome-devtools.md
> +使用designMode，你可以直接编辑所有内容
```suggestion
使用 designMode，你可以直接编辑所有内容
```

2020-09-21 16:06 UTC, lsvih commented
@Shirley-He-Maker 麻烦您加上校对者信息哈~还有中间有个空格漏了我标出来了，没有别的问题了

2020-09-21 16:13 UTC, Shirley-He-Maker commented on article/2020/5-lesser-known-features-of-chrome-devtools.md
>  > * 校对者：
已增加～

2020-09-21 16:14 UTC, Shirley-He-Maker commented
> @Shirley-He-Maker 麻烦您加上校对者信息哈~还有中间有个空格漏了我标出来了，没有别的问题了

已添加校对者信息～已添加空格～

2020-09-22 01:09 UTC, lsvih approved these changes

2020-09-22 01:09 UTC, merged

2020-09-22 01:09 UTC, lsvih commented
@Shirley-He-Maker 已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2020-09-22 09:39 UTC, Shirley-He-Maker commented
@lsvih 已投稿～知乎专栏可能需要通过一下推荐申请～之前的那一篇也还没有通过

2020-09-22 12:49 UTC, lsvih commented
@Shirley-He-Maker 您把掘金的链接发一下吧= =  知乎专栏不是我管理的，在群里说一声应该会有用..

2020-09-23 02:20 UTC, Shirley-He-Maker commented
> @Shirley-He-Maker 您把掘金的链接发一下吧= = 知乎专栏不是我管理的，在群里说一声应该会有用..

掘金的链接：https://juejin.im/post/6875240551390642189