NextJS vs. NuxtJS vs. GatsbyJS
xitu/gold-miner pull request #7495
Opened 2020-10-09 13:24 UTC by z0gSh1u

译文翻译完成，resolve #7414

2020-10-10 12:44 UTC, JohnieXu commented
@lsvih 校对认领

2020-10-10 12:45 UTC, lsvih commented
@JohnieXu 好的！

2020-10-10 13:31 UTC, JohnieXu requested changes
整体翻译的比较通畅，提了几个建议修改的点

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +我们都想要让网站能快点加载 —— 服务端渲染就是能帮助你的网站渲染得快一点的工具。让我们花点时间聊聊你的网站第一次渲染时的关键路径。 关键路径是指传送网页内容的最重要的部分给浏览器的过程，这样它才能渲染你的页面。如果我们能很快地传送重要的素材，浏览器就能很快地完成它的工作，快速地把页面渲染给用户。
稍微做了一下意译

`我们都想提升网站的加载速度 —— 而服务端渲染技术就是这么一个可以加速页面渲染的工具。下面我们来看一看服务端渲染的关键步骤。 浏览器渲染页面的关键步骤是接受服务端发送的关键数据并渲染成可视化的页面，如果我们能更快地将这些关键资源分发到浏览器，那么页面就可以更快地渲染好并呈现给用户。`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +## 了解背后的原理
`服务端渲染的原理`这样应该更好

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +浏览器渲染你的应用的速度，取决于你如何构建它。浏览器收到的第一个东西是 HTML 文档。文档包括了指向各种资源的引用 —— 如图片、CSS 和 JavaScript 代码。在浏览器解析 HTML 文档时，它知道要去获取并下载这些资源。所以，即使浏览器得到了你的 HTML，在 CSS 解析结束前，它也没办法渲染你的网站。
`所以，即使浏览器得到了你的 HTML，在 CSS 解析结束前，它也没办法渲染你的网站。`
===>
`所以，即使浏览器已经下载好了 HTML，也还是会在 CSS 解析完成之后才会开始渲染页面。`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +现在，最后的部分是 JavaScript。HTML 文档解析结束后，浏览器会下载你的 JavaScript 文件。如果文件很大，或者网络状况很差，那下载时间会很长，而且浏览器还得解析 JavaScript。在硬件配置较差的设备上，这部分的时间消耗会很可观。并且，如果你的首次渲染依赖于 JavaScript，你还会多次地看到慢的加载过程。JavaScript 应被看作 HTML 和 CSS 的一个
`现在，最后的部分是 JavaScript。`
===>
`现在，最后的一步是 JavaScript。`

`JavaScript 应被看作 HTML 和 CSS 的一个增强，因为它的加载是可以延迟的。`
===>
`JavaScript 应被看作 HTML 和 CSS 的一个增强，因为它的加载过程是异步的。`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +## 服务端渲染来袭
`服务端渲染的过程`这样应该更贴切

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> -JavaScript frameworks can be fast if you’re willing to put in the work. We can put this work in with server-side rendering — where we generate the HTML on the server and send that down to the browser
意译一下，关联一下上下文
`上面提到的 JavaScript 框架的渲染过程其实也是可以优化的，比如可以在服务端提前完成其渲染过程，再将生成好的 HTML 和 CSS 文件下发至浏览器。`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +所以，用户几乎能立刻看到你的应用的 HTML 版，同时 JavaScript 在后台启动执行。这不一定能让你的页面比非服务端渲染的版本加载的要快，但它确实能在 JavaScript 还在后台下载的过程中给用户一些能看到的内容 —— 这挺好的。
`所以，用户几乎能立刻看到你的应用的 HTML 版，`
===>
`所以，用户几乎能立刻看到你之前在服务端提前生成好的 HTML 页面，`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
>  ![Figure 01: [https://2019.stateofjs.com/back-end/](https://2019.stateofjs.com/back-end/)](https://cdn-images-1.medium.com/max/4244/1*-aPRuVhkDAfMp6chL8hjlQ.png)
需要翻译下
`![图 01: [https://2019.stateofjs.com/back-end/](https://2019.stateofjs.com/back-end/)](https://cdn-images-1.medium.com/max/4244/1*-aPRuVhkDAfMp6chL8hjlQ.png)`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
>  ![Figure 02: [https://2019.stateofjs.com/back-end/](https://2019.stateofjs.com/back-end/)](https://cdn-images-1.medium.com/max/4398/1*VTcI2ldavQoqePTHdyenhg.png)
需要翻译下
`![图 02: [https://2019.stateofjs.com/back-end/](https://2019.stateofjs.com/back-end/)](https://cdn-images-1.medium.com/max/4398/1*VTcI2ldavQoqePTHdyenhg.png)`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
>  ![Figure 03: [https://github.com/vercel/next.js/](https://github.com/vercel/next.js/)](https://cdn-images-1.medium.com/max/3562/1*TFDg_2S1N2e4RFtQ2muCwQ.png)
需要翻译下
`![图 03: [https://github.com/vercel/next.js/](https://github.com/vercel/next.js/)](https://cdn-images-1.medium.com/max/3562/1*TFDg_2S1N2e4RFtQ2muCwQ.png)`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
>  ![Figure 04: [https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)](https://cdn-images-1.medium.com/max/3564/1*F3CadZBwvdFjPpURd9u9Yg.png)
需要翻译下
`![图 04: [https://github.com/nuxt/nuxt.js](https://github.com/nuxt/nuxt.js)](https://cdn-images-1.medium.com/max/3564/1*F3CadZBwvdFjPpURd9u9Yg.png)`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
>  ![Figure 05: [https://github.com/gatsbyjs/gatsby](https://github.com/gatsbyjs/gatsby)](https://cdn-images-1.medium.com/max/3574/1*IfqEwUiWIPnxGdmU9YDj6A.png)
需要翻译下
`![图 05: [https://github.com/gatsbyjs/gatsby](https://github.com/gatsbyjs/gatsby)](https://cdn-images-1.medium.com/max/3574/1*IfqEwUiWIPnxGdmU9YDj6A.png)`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
>  ![Figure 06: [https://2019.stateofjs.com/back-end/nextjs/](https://2019.stateofjs.com/back-end/nextjs/)](https://cdn-images-1.medium.com/max/4398/1*1byrI3kvuO35-xQSdB5D5Q.png)
需要翻译下
`![图 06: [https://2019.stateofjs.com/back-end/nextjs/](https://2019.stateofjs.com/back-end/nextjs/)](https://cdn-images-1.medium.com/max/4398/1*1byrI3kvuO35-xQSdB5D5Q.png)`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +如果你打算把一个服务端的应用集成到 NextJS 应用中，我建议你不要一次性做完，因为实际上是做不到的 —— 工作量太大了。
`我建议你不要一次性做完`
==>
`我不建议你立即就开始这么做`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
>  ![Figure 07: [https://2019.stateofjs.com/back-end/nuxt/](https://2019.stateofjs.com/back-end/nuxt/)](https://cdn-images-1.medium.com/max/4404/1*nZe9YP8gl0d3FmZwoxaDsw.png)
需要翻译下
`![图 07: [https://2019.stateofjs.com/back-end/nuxt/](https://2019.stateofjs.com/back-end/nuxt/)](https://cdn-images-1.medium.com/max/4404/1*nZe9YP8gl0d3FmZwoxaDsw.png)`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +* 构建一个可用于生产环境的 Vue 应用是困难的。Nuxt 不仅预先配置好了 Vuex、Vue Router 和 Vue-meta，还聪明地使用基于充分的研究得来的最佳实践，来预设你的项目。 这些，Vue 并没有以开箱即用的方式提供给你。
`构建一个可用于生产环境的 Vue 应用是困难的。`
==>
`构建一个可用于生产环境的 Vue 应用是比较复杂的。`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +* Vue 的默认项目结构会把素材文件和组件文件放在你的源代码目录，而 Nuxt 把你的应用的页面、视图、路由和其他文件夹放在另外的、基于最佳实践的位置。
`素材文件`
==>
`资源文件`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +* Vue 应用并不是 SEO 友好的，而你会希望你的应用的某些页面能被搜索引擎恰当地索引，从而更容易被人找到。最好的解决方案之一是在服务器端预渲染你的页面，但靠自己来配置，可能需要很强的技巧性。而 Nuxt 已经被预设好了，能够借助路由配置在服务器端生成你的应用，并更容易添加 SEO 相关的 tag。
这样应该更通顺一些
`Vue 应用并不是 SEO 友好的`
==>
`Vue 应用对 SEO 并不友好`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +如果你新用 Nuxt，同时你的 Vue 应用的排期比较紧，你可能会遇到一些问题。
意义一下
`同时你的 Vue 应用的排期比较紧`
==>
`同时你的 Vue 应用的开发计划排期比较紧`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
>  ![Figure 08: [https://2019.stateofjs.com/back-end/gatsby/](https://2019.stateofjs.com/back-end/gatsby/)](https://cdn-images-1.medium.com/max/4472/1*Gih1W60mstqRA1lnPxQJjg.png)
需要翻译下
`![图 08: [https://2019.stateofjs.com/back-end/gatsby/](https://2019.stateofjs.com/back-end/gatsby/)](https://cdn-images-1.medium.com/max/4472/1*Gih1W60mstqRA1lnPxQJjg.png)`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
>  ![Photo by [Nathan Dumlao](https://unsplash.com/@nate_dumlao) on [Unsplash](https://unsplash.com/)](https://cdn-images-1.medium.com/max/2000/0*6GkumIALsOYIX3Tj)
需要翻译下
`![由 [Nathan Dumlao](https://unsplash.com/@nate_dumlao) 发布于 [Unsplash](https://unsplash.com/)](https://cdn-images-1.medium.com/max/2000/0*6GkumIALsOYIX3Tj)`

2020-10-10 13:31 UTC, JohnieXu commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +基于上面的优缺点和调查，我们可以得出结论：NextJS 是未来最好的服务端渲染框架。然而，如果我们看看前端开发的未来，我们可以看到，Vue 在工业界也做得不错。基于上面的各项因素，我建议你学习和使用 NextJS。
`Vue 在工业界也做得不错`
==>
`Vue 在实际项目开发中也表现得不错`

2020-10-11 06:24 UTC, nia3y commented
@lsvih 校对认领

2020-10-11 06:52 UTC, lsvih commented
@nia3y 好的！

2020-10-11 08:07 UTC, nia3y reviewed
@z0gSh1u @lsvih 校对完成

2020-10-11 08:07 UTC, nia3y commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +如果你要和 WordPress 一起使用 Gatsby，你需要换用很多 WordPress 内建的功能 —— 比如，你不能使用 Theme Hooks。
```suggestion
如果你要和 WordPress 一起使用 Gatsby，你需要换用很多 WordPress 内置的功能 —— 比如，你不能使用 主题 Hooks。
```

2020-10-11 08:07 UTC, nia3y commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +Next 是快速成长的 React 框架之一，尤其是在服务端渲染方面。作者把 NextJS 称作一个轻量级框架。我个人认为把它看作一个平台或者是起手模板，更合适些。
```suggestion
Next 是快速成长的 React 框架之一，尤其是在服务端渲染方面。作者把 NextJS 称作一个轻量级框架。我个人认为把它看作一个平台或者是起始模板更合适。
```

2020-10-13 02:35 UTC, z0gSh1u commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +现在，最后的部分是 JavaScript。HTML 文档解析结束后，浏览器会下载你的 JavaScript 文件。如果文件很大，或者网络状况很差，那下载时间会很长，而且浏览器还得解析 JavaScript。在硬件配置较差的设备上，这部分的时间消耗会很可观。并且，如果你的首次渲染依赖于 JavaScript，你还会多次地看到慢的加载过程。JavaScript 应被看作 HTML 和 CSS 的一个
JavaScript 的加载过程是默认同步的，在 HTML5 中可以利用 script 标签上的 async / defer 进行异步 / 延迟加载。

2020-10-13 02:37 UTC, z0gSh1u commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
>  ![Figure 01: [https://2019.stateofjs.com/back-end/](https://2019.stateofjs.com/back-end/)](https://cdn-images-1.medium.com/max/4244/1*-aPRuVhkDAfMp6chL8hjlQ.png)
已修改。此类可以不译。

2020-10-13 02:46 UTC, z0gSh1u commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +* Gatsby 使用 GraphQL 来从各个地方获取数据 —— 最激动人心的是我们可以从任何地方导入数据到 Gatsby 站点。
该处有语意重复，换译为：
`Gatsby 使用 GraphQL —— 我们可以从任何地方导入数据到 Gatsby 站点，这太激动人心了。`

2020-10-13 02:47 UTC, z0gSh1u commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +* 我们可以使用从数据库中获取到的 Markdown 文件，可以接入常见的 CMS，例如 WordPress 或者其他的 Headless CMS。然而，Gatsby 并不会为我们处理数据 —— 它只是获取拉取到 Gastby 中的数据，并从数据中生成站点。
Headless CMS 为常用术语，个人认为可不译。

2020-10-13 02:49 UTC, z0gSh1u commented on article/2020/nextjs-vs-nuxtjs-vs-gatsbyjs.md
> +如果你要和 WordPress 一起使用 Gatsby，你需要换用很多 WordPress 内建的功能 —— 比如，你不能使用 Theme Hooks。
Wordpress 的 Theme Hooks 指的是主题的自定义布局（ 见https://themeforwp.net/archives/astra-hooks/ ）。此处换译为
`比如，你不能使用主题的自定义布局。`

2020-10-13 02:52 UTC, z0gSh1u commented
根据校对修改完成。 @lsvih

2020-10-13 06:45 UTC, lsvih approved these changes

2020-10-13 06:46 UTC, merged

2020-10-13 06:46 UTC, lsvih commented
@z0gSh1u 已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2020-10-13 06:54 UTC, z0gSh1u commented
已发布掘金： https://juejin.im/post/6882994530149203981/