用 JavaScript 实现堆
xitu/gold-miner pull request #7518
Opened 2020-10-14 04:16 UTC by HurryOwen

译文翻译完成，resolve #7486

2020-10-15 13:50 UTC, z0gSh1u commented
校对认领  @lsvih

2020-10-15 14:57 UTC, lsvih commented
@z0gSh1u 好的！

2020-10-16 14:19 UTC, z0gSh1u reviewed
校对完成。

2020-10-16 14:19 UTC, z0gSh1u commented on article/2020/implementing-heaps-in-javascript.md
> +大部分编程语言都支持一些特定数据类型，例如 `int`, `string`, `boolean` 等等。我们可以自定义数据类型来存储一类数据，并且这个数据类型有一定的功能或作用。这些功能可以应用于数据点以获取有意义的结果。自定义数据结构的逻辑模型叫做**抽象数据结构（Abstract Data Type，简称 ADT）**，其物理实现是一种**数据结构**。数据结构是计算机科学中最基础的单元，为
functions/operations 应该指的是这些数据类型上面所带的方法。

2020-10-16 14:19 UTC, z0gSh1u commented on article/2020/implementing-heaps-in-javascript.md
> +大部分编程语言都支持一些特定数据类型，例如 `int`, `string`, `boolean` 等等。我们可以自定义数据类型来存储一类数据，并且这个数据类型有一定的功能或作用。这些功能可以应用于数据点以获取有意义的结果。自定义数据结构的逻辑模型叫做**抽象数据结构（Abstract Data Type，简称 ADT）**，其物理实现是一种**数据结构**。数据结构是计算机科学中最基础的单元，为
并没有绑定在  -->  并没有包含进

2020-10-16 14:19 UTC, z0gSh1u commented on article/2020/implementing-heaps-in-javascript.md
> +堆是一种基于树的数据结构，是一种满足堆属性的完全二叉树。
可以简化。

堆是一种满足堆属性的完全二叉树。

2020-10-16 14:19 UTC, z0gSh1u commented on article/2020/implementing-heaps-in-javascript.md
> +3. 其他运用包括，在数组中找到第 K 小或者第 K 大的元素这样的顺序统计，堆排序算法，Djiktra 这样的找到最短路径的图算法，以及 Prim 最小生成树。
`Djiktra` --> `Dijkstra`

2020-10-16 14:19 UTC, z0gSh1u commented on article/2020/implementing-heaps-in-javascript.md
> +我们将要实现 `MinHeap`，它将拥有在堆中获取最小元素和插入新元素，删除元素的方法。让我们从创建一个 `MinHeap` 的类开始：
它将拥有在堆中获取最小元素和插入新元素，删除元素的方法。
--->
它将拥有在堆中获取最小元素和插入新元素、删除元素的方法。

2020-10-16 14:19 UTC, z0gSh1u commented on article/2020/implementing-heaps-in-javascript.md
> +3. 其他运用包括，在数组中找到第 K 小或者第 K 大的元素这样的顺序统计，堆排序算法，Djiktra 这样的找到最短路径的图算法，以及 Prim 最小生成树。
换用顿号更合适。

2020-10-16 14:19 UTC, z0gSh1u commented on article/2020/implementing-heaps-in-javascript.md
> +        /* 初始化数组堆，并且在位置 0 加一个假元素 */
dummy可译为额外的、多余的。

2020-10-16 14:19 UTC, z0gSh1u commented on article/2020/implementing-heaps-in-javascript.md
> +现在我们开始检查当前元素及其父元素。如果当前节点比父母结点小，就交换他们的位置。请注意：当前节点的索引为 `current`，其父母节点的索引为` current/2`。我们用**ES6的数组结构语法**来交换着两个元素。插入或删除元素之后平衡堆的过程叫做**堆化（heapify）**。当我们遍历堆去给新结点找到合适的位置时，通常叫做**往上堆化（heapifyUp）**。
ES6 左右应添加空格。

2020-10-20 03:27 UTC, HurryOwen commented
@z0gSh1u  感谢校对，已修正。

2020-10-26 01:46 UTC, JohnieXu commented
@lsvih 还需要校对的话，校对认领

2020-10-26 02:22 UTC, lsvih commented
@JohnieXu 好的好的~

2020-11-06 02:41 UTC, kezhenxu94 commented
@JohnieXu hello, 还有在校对吗?

2020-11-06 11:11 UTC, kezhenxu94 commented on article/2020/implementing-heaps-in-javascript.md
> +堆是一种满足堆属性的完全二叉树。
这里和原文意思有出入, 和你“总结”里面的第一句也不一致.

2020-11-06 11:11 UTC, kezhenxu94 commented on article/2020/implementing-heaps-in-javascript.md
> +`**insert(36)**`：结点 `36` 作为结点 `10` 的右孩子被添加。我们不需要在这里转移任何结点，因为小顶堆的属性已经被处理了。
所有这种 \`\*\*xxxx\*\*\` 建议换成 \*\*\`xxx\`\*\*, 因为粗体在 \`\` 里面没效果, 原文估计在其他平台或者形式有误

2020-11-08 10:34 UTC, JohnieXu requested changes
整体翻译的还挺完整的，图片的备注信息没有翻译，还有几个格式问题

2020-11-08 10:34 UTC, JohnieXu commented on article/2020/implementing-heaps-in-javascript.md
>  ![Representation of a Binary Heap](https://cdn-images-1.medium.com/max/2000/1*ahBuj8eiKkIALwvlxJdzeQ.png)
```suggestion
![二叉堆示意图](https://cdn-images-1.medium.com/max/2000/1*ahBuj8eiKkIALwvlxJdzeQ.png)
```
需要翻译

2020-11-08 10:34 UTC, JohnieXu commented on article/2020/implementing-heaps-in-javascript.md
>  ![Representation of MinHeap & MaxHeap](https://cdn-images-1.medium.com/max/2000/1*5-_bPyIEw3-XtPVi3lCVzA.png)
```suggestion
![小顶堆、大顶堆示意图](https://cdn-images-1.medium.com/max/2000/1*5-_bPyIEw3-XtPVi3lCVzA.png)
```

2020-11-08 10:34 UTC, JohnieXu commented on article/2020/implementing-heaps-in-javascript.md
> +堆使得访问优先级元素的速度非常快。[优先队列](https://en.wikipedia.org/wiki/Priority_queue) 数据结构就是用堆来实现的。顾名思义，你可以使用优先队列在 `O(1)` 时间内按优先级访问元素。它通常用在[Dijkstra 算法](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm)，[Huffman
```suggestion
堆使得访问优先级元素的速度非常快。[优先队列](https://en.wikipedia.org/wiki/Priority_queue) 数据结构就是用堆来实现的。顾名思义，你可以使用优先队列在 `O(1)` 时间内按优先级访问元素。它通常用在[戴克斯特拉算法](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm)，[哈夫曼编码](https://en.wikipedia.org/wiki/Huffman_coding)中。如果你不知道这些算法也不用担心！接下来的文章中将会详细介绍它们。
```

2020-11-08 10:34 UTC, JohnieXu commented on article/2020/implementing-heaps-in-javascript.md
> +2. 生产者消费者模型可以用堆来实现，让消费者先访问高优先级的元素。在 [阻塞优先队列](https://www.geeksforgeeks.org/priorityblockingqueue-class-in-java/) 的实现中用到了。
```suggestion
2. 生产者消费者模型可以用堆来实现，让消费者先访问高优先级的元素。在[阻塞优先队列](https://www.geeksforgeeks.org/priorityblockingqueue-class-in-java/)的实现中用到了。
```

2020-11-08 10:34 UTC, JohnieXu commented on article/2020/implementing-heaps-in-javascript.md
> +3. 其他运用包括，在数组中找到第 K 小或者第 K 大的元素这样的顺序统计、堆排序算法、Dijkstra 这样的找到最短路径的图算法，以及 Prim 最小生成树。
```suggestion
3. 其他运用包括，在数组中找到第 K 小或者第 K 大的元素这样的顺序统计、堆排序算法和戴克斯特拉算法这样的找到最短路径的图算法，以及 Prim 最小生成树。
```

2020-11-08 10:34 UTC, JohnieXu commented on article/2020/implementing-heaps-in-javascript.md
>  ![Relationship of array indices of the parent and the child node in a Binary Heap](https://cdn-images-1.medium.com/max/2000/1*VzH_-Gq0LOMRLTktzflc5g.png)
```suggestion
![二进制堆中父节点和子节点的数组索引关系](https://cdn-images-1.medium.com/max/2000/1*VzH_-Gq0LOMRLTktzflc5g.png)
```

2020-11-08 10:34 UTC, JohnieXu commented on article/2020/implementing-heaps-in-javascript.md
> +往一个有 `n` 个元素二叉堆插入一个新元素的时间复杂度是 `O(log n)`。在每次迭代中要比较的元素减少一半，因此是 `log n` 。
```suggestion
往一个有 `n` 个元素二叉堆插入一个新元素的时间复杂度是 `O(log n)`。在每次迭代中要比较的元素减少一半，因此是 `log n`。
```

2020-11-08 10:34 UTC, JohnieXu commented on article/2020/implementing-heaps-in-javascript.md
>  ![Removing the minimum element from a binary heap](https://cdn-images-1.medium.com/max/2042/1*STrcM_P_ns8nxv0cktdRWw.png)
```suggestion
![从二进制堆中删除最小元素](https://cdn-images-1.medium.com/max/2042/1*STrcM_P_ns8nxv0cktdRWw.png)
```

2020-11-08 10:34 UTC, JohnieXu commented on article/2020/implementing-heaps-in-javascript.md
> +纠正上图：第四幅图的标题应该删除改为 —— **57比它的两个孩子结点32和38大，所以32和57交换**
```suggestion
纠正上图：第四幅图的标题应该删除改为 —— **57 比它的两个孩子结点 32 和 38 大，所以 32 和 57 交换**
```

2020-11-08 10:34 UTC, JohnieXu commented on article/2020/implementing-heaps-in-javascript.md
> +        /* 如果数组中只有两个元素，我们直接把第一个元素splice出去 */
```suggestion
        /* 如果数组中只有两个元素，我们直接把第一个元素 splice 出去 */
```

2020-11-08 10:34 UTC, JohnieXu commented on article/2020/implementing-heaps-in-javascript.md
>  ![Implementing Binary Heaps using Arrays](https://cdn-images-1.medium.com/max/2000/1*ZyMG4K50VjgBVkY_Bfcxaw.png)
```suggestion
![使用数组实现二进制堆](https://cdn-images-1.medium.com/max/2000/1*ZyMG4K50VjgBVkY_Bfcxaw.png)
```

2020-11-08 10:34 UTC, JohnieXu commented on article/2020/implementing-heaps-in-javascript.md
>  ![Insertion in Binary Heap](https://cdn-images-1.medium.com/max/2000/1*to65iKzq3VLUYPyOclk2lQ.png)
```suggestion
![二叉堆中插入元素](https://cdn-images-1.medium.com/max/2000/1*to65iKzq3VLUYPyOclk2lQ.png)
```

2020-11-09 06:03 UTC, HurryOwen commented
@lsvih @JohnieXu @kezhenxu94 已校对完毕

2020-11-09 07:00 UTC, lsvih commented on article/2020/implementing-heaps-in-javascript.md
> +    /* 堆数组中的最小元素在位置1 */
```suggestion
    /* 堆数组中的最小元素在位置 1 */
```

2020-11-09 07:00 UTC, lsvih commented on article/2020/implementing-heaps-in-javascript.md
> +    /* 如果数组中只有两个元素，我们直接把第一个元素splice出去 */
```suggestion
    /* 如果数组中只有两个元素，我们直接把第一个元素 splice 出去 */
```

2020-11-10 09:17 UTC, HurryOwen commented
@lsvih 已修改

2020-11-10 09:19 UTC, lsvih approved these changes

2020-11-10 09:19 UTC, merged

2020-11-10 09:20 UTC, lsvih commented
@HurryOwen 已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2020-12-16 08:08 UTC, kezhenxu94 commented
掘金文章发布地址 用 JavaScript 实现堆