The Do’s and Don’ts of Python List Comprehension
xitu/gold-miner pull request #7532
Opened 2020-10-16 07:06 UTC by samyu2000

resolve #7501

2020-10-18 12:25 UTC, luochen1992 commented
@lsvih 校对认领

2020-10-18 12:52 UTC, luochen1992 requested changes
建议译者再核对一遍

2020-10-18 12:52 UTC, luochen1992 commented on article/2020/the-dos-and-don-ts-of-python-list-comprehension.md
> +# Python List 使用注意事项
『Python List 使用注意事项』=>『Python 列表推导式使用注意事项』
整篇文章主题是列表推导式，并非列表本身。本文出现多次『List Comprehension』，应翻译为『列表推导式』，这里不再一一指出。

2020-10-18 12:52 UTC, luochen1992 commented on article/2020/the-dos-and-don-ts-of-python-list-comprehension.md
> +List 由于语法复杂，关于它的综合应用经常会难倒初学者，即便有的人使用过其他编程语言，要掌握 List 的使用也非易事。
『List 由于语法复杂，关于它的综合应用经常会难倒初学者，即便有的人使用过其他编程语言，要掌握 List 的使用也非易事。』=>『Python 列表推导式并不是给初学者用的，因为它非常反直觉，甚至对于有其他编程语言背景的人也是如此』

2020-10-18 12:52 UTC, luochen1992 commented on article/2020/the-dos-and-don-ts-of-python-list-comprehension.md
> +## Do’s使用建议
『Do’s使用建议』=>『使用建议』

2020-10-18 12:52 UTC, luochen1992 commented on article/2020/the-dos-and-don-ts-of-python-list-comprehension.md
> +使用 List 最基本的方式是以一个可迭代对象为基础，创建一个 List 对象，这个可迭代对象可以是任意可以迭代元素的Python对象。使用方法如下。
『使用 List 最基本的方式是以一个可迭代对象为基础，创建一个 List 对象，这个可迭代对象可以是任意可以迭代元素的Python对象。使用方法如下。』=>『列表推导式最基本的形式是利用一个可迭代对象创建列表，这个可迭代对象可以是任意的可迭代元素的Python对象。语法如下。』

2020-10-18 12:53 UTC, luochen1992 commented
@samyu2000 建议再核对一下。

2020-10-19 01:43 UTC, shixi-li commented
@lsvih 校对认领

2020-10-19 03:01 UTC, lsvih commented
@shixi-li 好的！

2020-10-19 13:24 UTC, shixi-li reviewed
有两个问题需要特别指出

1. 代码注释均需要译者补充翻译
2. 像另一位校对同学说的那样，本文主要是针对「列表推导式」，需要进行修改

2020-10-19 13:24 UTC, shixi-li commented on article/2020/the-dos-and-don-ts-of-python-list-comprehension.md
>  >>> # A list of integers
代码注释也请翻译

2020-10-19 13:24 UTC, shixi-li commented on article/2020/the-dos-and-don-ts-of-python-list-comprehension.md
> +The list comprehension can also work with conditional assignment, which has the following syntax.List 对象中还可以使用 if-else 形式的条件判断，语法如下。
请将英文原文移除

2020-10-19 13:24 UTC, shixi-li commented on article/2020/the-dos-and-don-ts-of-python-list-comprehension.md
> +跟使用 list 相比，使用 generator 内存开销小得多，只有 96 字节。原因很简单———— generator 不需要获取所有的元素。相反，它只需要获取各个元素在序列中的位置，并创建下一个元素并呈现它，而且不必保存在内存中。
并创建下一个元素并呈现它
=>
创建下一个元素并呈现它

2020-10-19 13:24 UTC, shixi-li commented on article/2020/the-dos-and-don-ts-of-python-list-comprehension.md
> +* **不要忘了生成器表达式** 它的语法与 list 中的语法相似。在处理大量的对象时，这是一种节省内存开销的办法。list 和 generator 不同的是，为了日后的索引和访问， list 必须提前创建，如果元素个数很多，就会消耗很大的内存。
为了日后的索引和访问， list
=>
为了日后的索引和访问，list

多了空格

2020-10-19 13:24 UTC, shixi-li commented on article/2020/the-dos-and-don-ts-of-python-list-comprehension.md
>  >>> # Use the range object
代码注释均需要翻译，下同

2020-10-23 12:42 UTC, samyu2000 commented
@lsvih 已发布到掘金网 https://juejin.im/post/6886633614717485070

2020-10-24 14:22 UTC, lsvih commented on article/2020/the-dos-and-don-ts-of-python-list-comprehension.md
>  > * 译者：
增加译者和校对者信息

2020-10-24 14:22 UTC, lsvih commented on article/2020/the-dos-and-don-ts-of-python-list-comprehension.md
> +使用 List 最基本的方式是以一个可迭代对象为基础，创建一个 List 对象，这个可迭代对象可以是任意可以迭代元素的Python对象。使用方法如下。
Python 左右要空格

2020-10-24 14:23 UTC, lsvih commented
得麻烦您在这个 pr 里也加上译者和校对者信息哈，然后有个格式上的小问题得改一下~

2020-11-01 07:56 UTC, merged