Update web-locks-api-cross-tab-resource-synchronization.md
xitu/gold-miner pull request #7564
Opened 2020-10-26 16:44 UTC by Raoul1996

译文翻译完成，resolve #7513

2020-10-28 23:32 UTC, JohnieXu commented
@lsvih 校对认领

2020-10-29 01:33 UTC, lsvih commented
@JohnieXu 好的~

2020-11-06 02:49 UTC, plusmultiply0 commented
校对认领@lsvih

2020-11-06 03:00 UTC, lsvih commented
@plusmultiply0 欢迎校对~

2020-11-07 14:30 UTC, plusmultiply0 reviewed
@lsvih @Raoul1996 校对完成

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +此外，可能存在用户打开了股票投资Web应用程序的两个 Tab 的情况。 如果用户使用其中一个打开的 Tab 购买了一定数量的股票，则两个 Tab 必须保持同步，以避免出现客户错误地再次进行交易的情况。 一个简单的选择是一次只允许应用程序的一个 Tab 或窗口。 但是请注意，可以通过使用私人浏览会话来绕过这个限制。
```suggestion
此外，可能存在用户打开了股票投资 Web 应用程序的两个 Tab 的情况。 如果用户使用其中一个打开的 Tab 购买了一定数量的股票，则两个 Tab 必须保持同步，以避免出现客户错误地再次进行交易的情况。一个简单的选择是一次只允许应用程序的一个 Tab 或窗口。 但是请注意，可以通过使用私人浏览会话来绕过这个限制。
```

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +这个 API 使用起来比较直接了当，但是你必须要确定浏览器支持该 API。`request()` 方法经常用来请求对资源的锁定。
```suggestion
这个 API 使用起来比较直接了当，但是你必须要确定浏览器支持该 API。`request()` 方法经常用来请求资源的锁。
```

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +方法接收三个参数。
```suggestion
该方法接收三个参数。
```

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +* 回调（必须传入的最后一个参数）—— 当请求成功时候会被调用的一个回调。建议传递 `async` 回调，这样它会返回一个 Promise。及时你没有传入异步回调，它也会包进一个 Promise 中。
```suggestion
* 回调函数（必须传入的最后一个参数）—— 当请求锁成功时候会调用回调函数。建议传递 `async` 回调函数，这样它会返回一个 Promise。即使你没有传入异步回调，它也会被包进一个 Promise 中。
```

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +* 选项（回调之前传递的可选第二个参数）—— 具有特定属性的对象，我们将在稍后讨论。
```suggestion
* 选项（回调之前传递的可选第二个参数）—— 一个具有特定属性的对象，我们将在稍后讨论。
```

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +这个方法返回的 promise 会在资源被获得后 resolve 掉， 你可以使用 `then..catch ..` 方法，或者选择 `await` 方法来用同步的方式写异步代码。
```suggestion
这个方法返回的 promise 会在资源被获得后 resolve 掉，你可以使用 `then..catch ..` 方法，或者选择 `await` 方法来用同步的方式写异步代码。
```

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +信号属性传入一个 [中止信号](https://dom.spec.whatwg.org/#interface-AbortSignal)。这允许一个在队列中的锁请求被中止。如果在特定时间段内未批准锁定请求，则可以使用超时来中止锁定请求。
```suggestion
信号属性传入一个[中止信号](https://dom.spec.whatwg.org/#interface-AbortSignal)。这允许一个在队列中的锁请求被中止。如果在特定时间段内未批准锁定请求，则可以使用超时来中止锁定请求。
```

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +#### 如果可用
```suggestion
#### 如果可用（ifAvailable）
```

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +## 用锁的风险
```suggestion
## 使用锁的风险
```

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +死锁的概念与并发关联。当进程由于每个部分都在因请求无法满足而等待导致的无法继续执行时，就会发生死锁。
```suggestion
死锁的概念与并发关联。当进程由于每个部分都在因请求无法满足，而等待导致无法继续执行时，就会发生死锁。
```

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +为了避免死锁，在获取锁时我们必须遵循严格的模式。可以使用很多种技术，例如避免嵌套锁定，确保锁定顺序正确，甚至使用 signal 可选参数来使锁定请求超时。说一千道一万，精心设计的 API 将是避免死锁的最佳解决方案。你可以在[此处](https://en.wikipedia.org/wiki/Deadlock_prevention_algorithms)上阅读有关死锁预防的更多信息。
```suggestion
为了避免死锁，在获取锁时我们必须遵循严格的模式。可以使用很多种技术，例如避免嵌套锁，确保锁的顺序正确，甚至使用 signal 可选参数来使锁定请求超时。说一千道一万，精心设计的 API 将是避免死锁的最佳解决方案。你可以在[此处](https://en.wikipedia.org/wiki/Deadlock_prevention_algorithms)上阅读有关死锁预防的更多信息。
```

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +在某些情况下，您会发现其中一个 Tab 变得无响应。如果在选项卡持有锁的状态下发生这种情况，则可能会非常棘手。 可以引入一个 `steal` 布尔值（参数），就是我们之前谈到的可选参数的一部分。尽管默认情况下取值为`false`，但如果将其传递为 `true`，则无论资源队列中锁请求有多少，任何资源上的锁都会被立即释放，并且将立即授予此新锁请求。
```suggestion
在某些情况下，您会发现其中一个 Tab 变得无响应。如果在选项卡持有锁的状态下发生这种情况，则可能会非常棘手。可以引入一个 `steal` 布尔值（参数），就是我们之前谈到的可选参数的一部分。尽管默认情况下取值为`false`，但如果将其传递为 `true`，则无论资源队列中锁请求有多少，任何资源上的锁都会被立即释放，并且将立即授予此新锁请求。
```

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +由于可能存在隐藏状态，因此可能存在与调试有关的问题。为了解决这个问题，引入了一种 `query` 方法。此方法在该特定时刻返回锁管理器的状态。结果中将包含未决和当前持有的锁的详细信息。它还将包含锁类型，持有/请求到锁的资源以及请求的 clientId 详细信息。
```suggestion
由于可能存在隐藏状态，因此可能存在与调试有关的问题。为了解决这个问题，引入了 `query` 方法。此方法在该特定时刻返回锁管理器的状态。结果中将包含等待和当前被持有的锁的详细信息。它还包含锁类型，持有/请求到锁的资源以及请求的 clientId 详细信息。 
```

2020-11-07 14:30 UTC, plusmultiply0 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +`clientId` 仅仅只是请求锁定的唯一上下文（框架/ worker ）的对应值。这是在 Service Workers 中使用相同的值。
```suggestion
`clientId` 仅仅只是请求锁定的唯一上下文（框架/ worker）的对应值。相同的值可用在 Service Workers 中。
```

2020-11-07 15:42 UTC, JohnieXu requested changes
辛苦译者了☕☕，提了一些小的建议

2020-11-07 15:42 UTC, JohnieXu commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +Web Locks API 将锁整体应用于 web 应用。这个 API 允许一个脚本异步持有对资源的锁定，直到其处理完成之后再释放。当持有锁时，除一种特殊情况外，其他在同域下的脚本无法获得相同资源的锁。接下来我们就说说这个特殊情况。
```suggestion
Web Locks API 将上面提到的锁（Locks）的相同功能应用到了 web 应用。这个 API 允许一个脚本异步持有对资源的锁定，直到其处理完成之后再释放。当持有锁时，除一种特殊情况外，其他在同域下的脚本无法获得相同资源的锁。接下来我们就说说这个特殊情况。
```

2020-11-07 15:42 UTC, JohnieXu commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
>  The scopes on how the Web Locks API can be quite confusing. Hence here is a summary for you to understand it better.
这里把后面的 diff 都打乱了，不好对比😢

2020-11-07 15:42 UTC, JohnieXu commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +* 根据文档，锁的作用域限制在同源。
```suggestion
* 根据官方文档说明，锁的作用域同样存在同源限制。
```

2020-11-07 15:42 UTC, JohnieXu commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +假设如果 `脚本 A` 属于 `锁管理器 A`，`脚本 B` 属于 `锁管理器 B`。`脚本 A` 尝试获得 `资源 X` 的锁，成功获得锁并执行异步任务。同时，`脚本 B` 也尝试获得 `资源X` 的锁，它将会成功，因为两个脚本属于不同的锁管理器。但是如果他们属于同一个锁管理器，那么将会有一个队列来获取对 `资源 X` 的锁。希望这个点我已经说明白了。
```suggestion
假设如果 `脚本 A` 属于 `锁管理器 A`，`脚本 B` 属于 `锁管理器 B`。`脚本 A` 尝试获得 `资源 X` 的锁，成功获得锁并执行异步任务。同时，`脚本 B` 也尝试获得 `资源 X` 的锁，它将会成功，因为两个脚本属于不同的锁管理器。但是如果他们属于同一个锁管理器，那么将会有一个队列来获取对 `资源 X` 的锁。希望这个点我已经说明白了。
```

2020-11-07 15:42 UTC, JohnieXu commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +#### 这些资源是什么？
```suggestion
#### 上面说到的这些资源是什么？
```

2020-11-07 15:42 UTC, JohnieXu commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +在简单的Web应用程序中很少需要进行资源协调。但是，更复杂，使用大量 JavaScript 的 Web 应用程序可能需要进行资源协调。
```suggestion
在简单的 Web 应用程序中很少需要进行资源协调，但是，那些大量使用 JavaScript 的复杂 Web 应用程序可能需要进行资源协调。
```

2020-11-07 15:42 UTC, JohnieXu commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +此外，可能存在用户打开了股票投资Web应用程序的两个 Tab 的情况。 如果用户使用其中一个打开的 Tab 购买了一定数量的股票，则两个 Tab 必须保持同步，以避免出现客户错误地再次进行交易的情况。 一个简单的选择是一次只允许应用程序的一个 Tab 或窗口。 但是请注意，可以通过使用私人浏览会话来绕过这个限制。
```suggestion
此外，可能存在用户打开了股票投资 Web 应用程序的两个 Tab 的情况。 如果用户使用其中一个打开的 Tab 购买了一定数量的股票，这样两个 Tab 就必须要保持同步，以避免出现客户根据错误的持有股票数进行误交易的情况。一个简单的选择是一次只允许应用程序的一个 Tab 或窗口。 但是请注意，用户可以通过使用隐身模式来绕过这个限制。
```

2020-11-07 15:42 UTC, JohnieXu commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +尽管可以使用诸如 SharedWorker，BroadcastChannel，localStorage，sessionStorage，postMessage，卸载 handler 之类的 API 来管理选项卡通信和同步，但它们各自都有缺点，并且需要变通办法，这降低了代码的可维护性。 Web Locks API 试图通过引入更标准化的解决方案来简化此过程。
```suggestion
尽管可以使用诸如 SharedWorker，BroadcastChannel，localStorage，sessionStorage，postMessage，unload handler 之类的 API 来管理选项卡通信和同步，但它们各自都有缺点，并且需要变通办法，这降低了代码的可维护性。 Web Locks API 试图通过引入更标准化的解决方案来简化此过程。
```

2020-11-07 15:42 UTC, JohnieXu commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
>  ![Source: [Shun Yan Cheung](http://www.mathcs.emory.edu/~cheung/Courses/554/Syllabus/7-serializability/compat-mat.html)](https://cdn-images-1.medium.com/max/2000/0*6-VW3zuoya_NHYsP.gif)
```suggestion
![源自：[Shun Yan Cheung](http://www.mathcs.emory.edu/~cheung/Courses/554/Syllabus/7-serializability/compat-mat.html)](https://cdn-images-1.medium.com/max/2000/0*6-VW3zuoya_NHYsP.gif)
```

2020-11-07 15:42 UTC, JohnieXu commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +但是请注意，当返回 `null` 时，该函数将不同步。而是回调将接收值 `null`，值可以由开发者进行处理。
```suggestion
但是请注意，当返回 `null` 时，该函数将不会同步执行。而是由回调函数返回 `null`，值可以由开发者进行处理。
```

2020-11-07 15:42 UTC, JohnieXu commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +与应用锁相关的风险有很多。这些或多或少是由于锁本身的概念，而不是由于 API 中的任何错误。
```suggestion
与应用锁相关的风险有很多，这些或多或少是由于锁本身的功能定义导致，而并非是 Web Locks API 中的任何错误导致。
```

2020-11-07 15:42 UTC, JohnieXu commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
>  ![Illustration by Author](https://cdn-images-1.medium.com/max/2840/1*DQI5-XUHL9L8e-32d_ufxg.png)
```suggestion
![图由原作者提供](https://cdn-images-1.medium.com/max/2840/1*DQI5-XUHL9L8e-32d_ufxg.png)
```

2020-11-07 15:42 UTC, JohnieXu commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +`clientId` 仅仅只是请求锁定的唯一上下文（框架/ worker ）的对应值。这是在 Service Workers 中使用相同的值。
这里的 frame 应该是指的是浏览器的主进程，主要为了区别主进程与 worker 进程
```suggestion
`clientId` 仅仅只是请求锁定的唯一上下文（frame/ worker ）的对应值。相同的值可用在 Service Workers 中。
```

2020-11-10 02:32 UTC, Raoul1996 commented
感谢~今天晚上完成修改

2020-11-15 16:27 UTC, Raoul1996 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +# Web Locks API: 跨 Tab 资源同步
浏览器标签我倾向不翻译

2020-11-15 16:30 UTC, Raoul1996 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +如果你对线程熟悉的话，那么你自然会知晓锁的概念。锁是一种同步方法，，可强制对线程执行访问限制，防止多个线程同时访问单个资源。还有一种锁的变体，允许多个线程同时访问单个资源，不过仍将访问限制为只读。我强烈建议你去阅读一些材料，理解操作系统中锁的概念。
still 我倾向于保留

2020-11-15 16:33 UTC, Raoul1996 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
>  The scopes on how the Web Locks API can be quite confusing. Hence here is a summary for you to understand it better.
抱歉

2020-11-15 16:34 UTC, Raoul1996 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +* 浏览器中单独用户配置被视为单独的用户代理，视为在作用域之外。因此，即使他们的同源，也不会共享锁管理器。
considered？

2020-11-15 16:35 UTC, Raoul1996 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +* 私有模式的浏览会话（隐身模式）被视为单独的用户代理，视为在作用域之外。因此，及时他们的同源，也不会共享锁管理器。
considered？

2020-11-15 16:41 UTC, Raoul1996 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +* 回调（必须传入的最后一个参数）—— 当请求成功时候会被调用的一个回调。建议传递 `async` 回调，这样它会返回一个 Promise。及时你没有传入异步回调，它也会包进一个 Promise 中。
callback 是回调函数还是回调。。。

翻译的时候比较疑惑。

callback function 呢？

2020-11-15 16:44 UTC, Raoul1996 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +死锁的概念与并发关联。当进程由于每个部分都在因请求无法满足而等待导致的无法继续执行时，就会发生死锁。
死锁的概念与并发关联。当进程由于每个部分都在因请求无法满足而等待，导致的无法继续执行时，就会发生死锁。

2020-11-15 16:52 UTC, Raoul1996 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +* 根据文档，锁的作用域限制在同源。
docs 没有添加明确的 offical 修饰。。

2020-11-15 16:57 UTC, Raoul1996 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +此外，可能存在用户打开了股票投资Web应用程序的两个 Tab 的情况。 如果用户使用其中一个打开的 Tab 购买了一定数量的股票，则两个 Tab 必须保持同步，以避免出现客户错误地再次进行交易的情况。 一个简单的选择是一次只允许应用程序的一个 Tab 或窗口。 但是请注意，可以通过使用私人浏览会话来绕过这个限制。
`根据错误的持有股票数` 貌似没有明确提到

2020-11-15 16:59 UTC, Raoul1996 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +与应用锁相关的风险有很多。这些或多或少是由于锁本身的概念，而不是由于 API 中的任何错误。
Web Locks API 并无提及。

2020-11-15 17:00 UTC, Raoul1996 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
>  ![Illustration by Author](https://cdn-images-1.medium.com/max/2840/1*DQI5-XUHL9L8e-32d_ufxg.png)
图由作者提供

2020-11-15 17:05 UTC, Raoul1996 commented on article/2020/web-locks-api-cross-tab-resource-synchronization.md
> +如果你使用跨多个 Tab 的应用程序并且可以执行 CRUD 操作，你将必须保持选项卡同步以避免问题。如果用户在一个 Tab 上打开了文本编辑的 Web 应用程序，而忘记了另一个 Tab 打开同一应用程序。现在，他具有正在运行的同一应用程序的两个 Tab。如果他在一个 Tab 上执行一项操作，并尝试在另一 Tab 上执行完全不同的操作，则当同一资源上被两个不同的进程操作时，服务器上可能会发生冲突。
忘记删除了应该是。。

2020-11-15 17:06 UTC, Raoul1996 commented
@JohnieXu @plusmultiply0 辛苦再看下

2020-11-16 01:20 UTC, lsvih approved these changes

2020-11-16 01:20 UTC, merged

2020-11-16 01:21 UTC, lsvih commented
@Raoul1996 已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2020-11-16 18:40 UTC, Raoul1996 commented
https://juejin.im/post/6895792867080405005/