四个优秀 Vue.js 静态站点生成器
xitu/gold-miner pull request #7724
Opened 2020-12-04 14:22 UTC by zenblo

译文翻译完成，resolve #7692

2020-12-05 13:58 UTC, NieZhuZhu commented
校对认领 @lsvih

2020-12-05 14:20 UTC, NieZhuZhu reviewed
@lsvih @zenblo 校对完成

2020-12-05 14:20 UTC, NieZhuZhu commented on article/2020/best-static-site-generators-for-vue-js.md
> +类似 React.js 静态网页生成器 Gatsby 和 NextJS，你可以找到几个支持生成静态网页的 Vue.js 框架。然而，考虑到它们的功能特性，选择一个合适的并不容易。
```suggestion
像  Gatsby 和 NextJS 等这类 React.js 的静态网页生成器，你可以找到几个支持生成静态网页的 Vue.js 框架。然而，考虑到它们的功能特性，选择一个合适的并不容易。
```

2020-12-05 14:20 UTC, NieZhuZhu commented on article/2020/best-static-site-generators-for-vue-js.md
> +Nuxt.js 遵循健壮的模块化架构来设计，有 50 多个不同的模块可供使用。这些模块将提供内置支持，将 PWA 功能和标准功能（如谷歌分析）引入应用程序。
```suggestion
Nuxt.js 遵循健壮的模块化架构设计，有 50 多个不同的模块可供使用。这些模块将提供内置支持，用以将 PWA 功能和标准功能（如谷歌分析）引入应用程序。
```

2020-12-05 14:20 UTC, NieZhuZhu commented on article/2020/best-static-site-generators-for-vue-js.md
> +Nuxt.js 最大的优点之一是带有 `nuxt generate` 命令。
```suggestion
Nuxt.js 最大的优点之一是具有 `nuxt generate` 命令。
```

2020-12-05 14:20 UTC, NieZhuZhu commented on article/2020/best-static-site-generators-for-vue-js.md
> +> 有了这个命令，你可以用很少的精力完成一个纯静态的网站版本。
```suggestion
> 有了这个命令，你可以只话费很少的精力就能完成一个纯静态的网站版本。
```

2020-12-05 14:20 UTC, NieZhuZhu commented on article/2020/best-static-site-generators-for-vue-js.md
> +查看 Nuxt.js 的统计数据，你会发现它有 32k star 和 280+ 贡献者。例如 GitLab、NESPRESSO 和 UBISOFT 这些公司已经开始使用 Nuxt.js。
```suggestion
通过查看 Nuxt.js 的统计数据，你会发现它有 32k stars 和 280+ 贡献者。例如 GitLab、NESPRESSO 和 UBISOFT 这些公司已经开始使用 Nuxt.js。
```

2020-12-05 14:20 UTC, NieZhuZhu commented on article/2020/best-static-site-generators-for-vue-js.md
> +VuePress 是 Vue.js 的另一个静态站点生成器，这是作为一个文档生成系统开发的。然而，1.x 版本发布后，VuePress 被认为是一个静态文件生成器。
```suggestion
VuePress 是作为一个文档生成系统开发的另一个 Vue.js 静态站点生成器。然而，1.x 版本发布后，VuePress 被认为是一个静态文件生成器。
```

2020-12-05 14:20 UTC, NieZhuZhu commented on article/2020/best-static-site-generators-for-vue-js.md
> +> **然而，VuePress 更适合以内容为中心的静态网站创建，而 Nuxt.js 更侧重于网络应用程序开发。**
```suggestion
> **然而，VuePress 更适合用来创建以内容为中心的静态网站，而 Nuxt.js 更侧重于网络应用程序开发。**
```

2020-12-05 14:20 UTC, NieZhuZhu commented on article/2020/best-static-site-generators-for-vue-js.md
> +* 相比之下是新技术，还没有像 Nuxt.js 那样发布。
这句话啥意思 🤔

2020-12-05 14:20 UTC, NieZhuZhu commented on article/2020/best-static-site-generators-for-vue-js.md
> +接下来要介绍的是 Gridsome，它以建立快速轻量静态网站而闻名。类似于 React 中的 Gatsby，Gridsome 是一个数据驱动的框架。Gridsome 使用一个 GraphQL 数据层从数据源中获取内容，然后动态生成页面。
```suggestion
接下来要介绍的是 Gridsome，它以建立快速轻量静态网站而闻名。跟 React 中的 Gatsby 类似，Gridsome 是一个数据驱动的框架。Gridsome 使用一个 GraphQL 的数据层从数据源中获取内容，然后动态生成页面。
```

2020-12-05 14:20 UTC, NieZhuZhu commented on article/2020/best-static-site-generators-for-vue-js.md
> +查看 Gridsome 的 GitHub 统计，它只有 7k stars 和 100+ 贡献者。此外，Gridsome 还有一些独特的功能来与其它项目进行竞争。
```suggestion
查看 Gridsome 的 GitHub 统计，它只有 7k stars 和 100+ 贡献者。此外，Gridsome 还有一些独特的具有竞争力的功能特性。
```

2020-12-05 14:20 UTC, NieZhuZhu commented on article/2020/best-static-site-generators-for-vue-js.md
> +然而，当比较上述四个框架时，基于 GitHub 和 [npmtrends.com](https://www.npmtrends.com/) 统计数据，看到 Nuxt.js 和 VuePress 是位于顶部。
```suggestion
然而，当比较上述四个框架时，从 GitHub 和 [npmtrends.com](https://www.npmtrends.com/) 统计数据来看，其中 Nuxt.js 和 VuePress 是佼佼者。
```

2020-12-06 04:25 UTC, zenblo commented
@NieZhuZhu 感谢校对！
@lsvih 完成修改

2020-12-06 07:45 UTC, wynn-w commented
校对认领 @lsvih

2020-12-06 08:30 UTC, wynn-w commented on article/2020/best-static-site-generators-for-vue-js.md
> +在过去几年里，Vue.js 已经成为 web 应用程序开发的热门选择。随着它的流行，该框架已经扩展到静态网页生成器，这是一个曾经由 React 主导的领域。
在过去几年里，Vue.js 已经成为 web 应用程序开发的热门选择。随着它的流行，该框架已经扩展到以 React 主导的静态网页生成器领域。

2020-12-06 08:33 UTC, wynn-w requested changes

2020-12-06 08:33 UTC, wynn-w commented on article/2020/best-static-site-generators-for-vue-js.md
> +> 有了这个命令，你可以只话费很少的精力就能完成一个纯静态的网站版本。
通过这个命令，你只要花费很少的精力就能开发一个纯静态的网站。

2020-12-06 09:00 UTC, wynn-w requested changes

2020-12-06 09:01 UTC, wynn-w requested changes

2020-12-06 09:01 UTC, wynn-w commented on article/2020/best-static-site-generators-for-vue-js.md
> +> **然而，更适合用来创建以内容为中心的静态网站，而 Nuxt.js 更侧重于网络应用程序开发。**
**然而，VuePress 更适合用来创建以内容为中心的静态网站，而 Nuxt.js 更侧重于网络应用程序开发。**

2020-12-06 09:25 UTC, wynn-w requested changes

2020-12-06 09:25 UTC, wynn-w commented on article/2020/best-static-site-generators-for-vue-js.md
> +* 相比之下是新技术，还没有像 Nuxt.js 那样成熟。
功能上不如Nuxt.js完备

2020-12-06 10:03 UTC, wynn-w requested changes
此外，Gridsome 还有一些独特的具有竞争力的功能特性。 =>  但这并不妨碍Gridsome 拥有一些独特且竞争力强的功能特性。

2020-12-06 10:03 UTC, wynn-w commented on article/2020/best-static-site-generators-for-vue-js.md
> +查看 Gridsome 的 GitHub 统计，它只有 7k stars 和 100+ 贡献者。此外，Gridsome 还有一些独特的具有竞争力的功能特性。
查看 Gridsome 的 GitHub 统计，它仅有 7k stars 和 100+ 贡献者。但这并不妨碍Gridsome 拥有一些独特且竞争力强的功能特性。

2020-12-06 11:07 UTC, zenblo commented
@wynn-w 感谢校对！
@lsvih 已完成两次校对，帮忙再看一下

2020-12-06 13:53 UTC, wynn-w requested changes

2020-12-06 14:21 UTC, lsvih commented
@wynn-w 感谢校对，下会儿您可以用“批量 review”功能哈，现在一条一条地添加校对意见，邮箱会被轰炸的 🤦

2020-12-06 14:25 UTC, zenblo commented on article/2020/best-static-site-generators-for-vue-js.md
> +* 相比之下是新技术，还没有像 Nuxt.js、VuePress 那样成熟。
好的，我又修改了：觉得译为“受认可”好些

2020-12-06 14:27 UTC, lsvih approved these changes

2020-12-06 14:27 UTC, merged

2020-12-06 14:27 UTC, lsvih commented
@zenblo 已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2020-12-06 14:28 UTC, wynn-w requested changes

2020-12-06 14:28 UTC, wynn-w commented on article/2020/best-static-site-generators-for-vue-js.md
> +> 大概浏览一下 Saber.js，感觉更像是 Gatsby、Gridsome 和 Nuxt.js 的结合。
经过一段时间的使用，我感觉Saber.js更像是 Gatsby、Gridsome 和 Nuxt.js 的结合。

2020-12-06 14:43 UTC, wynn-w requested changes

2020-12-06 14:43 UTC, wynn-w commented on article/2020/best-static-site-generators-for-vue-js.md
> +类似于 Gatsby 和 Gridsome，Saber 允许你用想要的数据创建静态网站。你可以从不同的文件系统中提取数据。使用 Saber，你就不用担心不会用 GraphQL。
与Gatsby 和Gridsome 一样，Saber 允许你用想要的数据创建静态网站。你可以从不同的文件系统中提取数据。在Saber项目中，你不需要担心GraphQL 的问题。

2020-12-06 14:59 UTC, wynn-w requested changes

2020-12-06 14:59 UTC, wynn-w commented on article/2020/best-static-site-generators-for-vue-js.md
> +由于 Saber 对这项业务来说仍然是新技术，它的 GitHub 项目也只有2k stars。我相信 Saber 框架只要稳定下来，它的 star 数量肯定会增加。
虽然Saber 在静态站点生成器中仍然是新技术，它的 GitHub 项目也只有2k stars，但是我相信 Saber 框架只要稳定下来，它的 star 数量肯定会增加。

2020-12-07 01:03 UTC, zenblo commented
掘金文章发布地址  https://juejin.cn/post/6903309715309068295