揭开 0-1 背包问题的神秘面纱
xitu/gold-miner pull request #7725
Opened 2020-12-05 09:24 UTC by Usualminds

译文翻译完成，resolve #7556

2020-12-06 06:46 UTC, Lokfar commented
@lsvih 校对认领

2020-12-06 08:47 UTC, luochen1992 commented
@lsvih 校对认领

2020-12-06 09:00 UTC, Lokfar requested changes
在校对近三个小时后，我提前结束了校对，并请求关闭该文章的翻译。原因是该篇文章质量较差，关于0-1背包问题的文章已经非常多了。该文章远不如某些中文博客通俗易懂，某些知识点也不够全面，如背包问题的变种。通篇下来看不到亮点，因此申请关闭该文章的翻译。
其次，对于翻译者的提议。译者明显对于算法领域不熟悉，许多专业术语翻译错误，比如动态规划翻译成动态编程。因为相关知识的缺乏，少数几处甚至出现了谬误，如optimized solution翻译成优化的解决方案。最严重的问题是，多处采取直译，甚至无视语句是否通顺，意思是否明确，如：并且可以通过改变维度，让面试者失去题目重心；从而深入了解到你是否为优化的解决方案而工作。翻译不一定要强求与原文完全一致，有时候，为了文章的通顺，应该采取意译，有时也可以省略或增加部分文字。
综上，希望译者在面对不熟悉领域的文章时，能够先了解一下相应的知识。通过查看译者主页估计译者应该是新加入掘金计划的成员，熟悉领域为前端。以上内容只是建议，并非责备，其中也大有译者对算法不够熟悉的原因。希望译者能够再接再励，加油。

2020-12-06 09:04 UTC, Lokfar commented
@lsvih @Usualminds 校对结束，请求关闭此篇文章。

2020-12-06 14:16 UTC, lsvih commented
@Lokfar 收到意见


请另一位校对者 @luochen1992 确认一下

2020-12-08 02:00 UTC, Usualminds commented
@Lokfar 感谢您的校对和意见，翻译之前有了解过一些 背包算法 的相关原理，但确实比较浅显。您提出的几点翻译问题后续我会逐步改进和提高

@lsvih 这篇文章在翻译过程中也有存疑，比如结尾部分图文不符，原文的图片和其下面代码说明文字部分所提及的行数似乎不符，**line 124 ~ line 142**  ，请帮忙确认

2020-12-11 15:11 UTC, closed without merging