Applications of some of the famous algorithms翻译完成
xitu/gold-miner pull request #7726
Opened 2020-12-06 04:02 UTC by samyu2000

译文翻译完成，resolve #7675

2020-12-11 05:25 UTC, zhuzilin commented
@lsvih 申请校对。

2020-12-11 06:26 UTC, lsvih commented
@zhuzilin 好的

2020-12-12 14:17 UTC, zhuzilin reviewed
@samyu2000 @lsvih 翻译辛苦了~ 提了一些建议哈~

2020-12-12 14:17 UTC, zhuzilin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +这是一篇讨论阿姆斯特朗数在无线传感器网络中的应用的[论文](https://www.ijitee.org/download/volume-1-issue-1/)。该论文使用基于阿姆斯特朗数的安全算法，其中阿姆斯特朗数用于生成128位密钥，并在 [AES algorithm](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard) 用
并在 [AES algorithm] 用于加密和解密。 => 并在 [AES 算法]中使用这个密钥进行加密和解密。
不是很了解这个领域...看了一下AES的wiki，128bit的秘钥好像是这个东西的输入。

2020-12-12 14:17 UTC, zhuzilin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +## 合并排序算法
合并排序算法 => 归并排序算法
下面的都需要改一下，就不再标出来了。

2020-12-12 14:17 UTC, zhuzilin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +合并排序是一种基于**分而治之**思想的排序法。它的两个基本原理是：
```suggestion
归并排序是一种基于**分治法**的排序算法。它的两个基本原理是：
```

2020-12-12 14:17 UTC, zhuzilin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +* 两个已排序数组的合并比未排序的要快。
```suggestion
* 合并两个有序数组比合并无序的要快。
```

2020-12-12 14:17 UTC, zhuzilin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +合并排序一般用于小于某个值的约束。
```suggestion
在使用归并排序时，一般会有数组大小上的约束条件。
```
感觉这里原文应该是要说under size constraints，就是说在一定长度之上才使用归并排序（一般更小的就用快排了）。

2020-12-12 14:17 UTC, zhuzilin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +电子商务网站通常有一个叫做**你可能喜欢**的版块。这里为每个用户保存一个列表。任何我们选择过的列表中浏览后回退次数最少的商品，都会进行推荐。
列表 => 数组
inversion应该是逆序对的意思，例如[这篇文章](https://medium.com/@ssbothwell/counting-inversions-with-merge-sort-4d9910dc95f0)中就提到推荐系统用归并排序数逆序对（counting inversion）的方式来做推荐。

2020-12-14 03:38 UTC, samyu2000 commented
@lsvih 已发布 https://juejin.cn/post/6905933346807742478

2020-12-16 07:48 UTC, samyu2000 commented
@lsvih  已发布 https://juejin.cn/post/6905933346807742478

2021-02-08 16:47 UTC, PassionPenguin requested changes
ψ(｀∇´)ψ

2021-02-08 16:47 UTC, PassionPenguin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +#### 你了解这些算法的实际应用案例吗？
```suggestion
#### 你了解那些知名算法的实际应用案例吗？
```

上文那张图木有啥算法诶，这个these应该是指代标题，直接引用回标题可能更恰当

2021-02-08 16:47 UTC, PassionPenguin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +在读大学期间，我练习过一些知名算法，开启了学习编程的道路。我从未试图了解这些算法在实际工作中的应用。不过，一定有外因驱使我们学习这些内容的，不是吗？
```suggestion
在我就读大学的时候，我曾经通过实践学习过大多数知名的算法，开启了学习编程的道路，但我从未试图了解这些算法在实际工作中的应用。不过，一定有外因驱使我们学习这些内容的，不是吗？
```

2021-02-08 16:47 UTC, PassionPenguin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +如今作为一名软件开发人员，我常常在项目中使用这些算法。曾经为了得到一份工作而学习的算法，在后来的实际工作中也有用武之地，这真是一件有趣的事。
```suggestion
如今作为一名软件开发人员，我常常在项目中使用这些算法。那些我曾经为了得到一份工作而学习的算法，在后来的实际工作中也有用武之地，这可真是一件有趣的事。
```

2021-02-08 16:47 UTC, PassionPenguin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +在本文中，我会分享这些算法的一些实际应用场景。初学者可以感受到学以致用的乐趣，有经验的开发者也可以借此加深印象。
```suggestion
在本文中，我会分享这些算法的一些实际应用场景。初学者们可以从中感受到学以致用的乐趣，而那些经验十足但开发者也可以借此加深印象。
```

2021-02-08 16:47 UTC, PassionPenguin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +几乎所有的开发者都了解过 Fibonacci 数列相关的算法。[Fibonacci 数列](https://en.wikipedia.org/wiki/Fibonacci_number) 是这样的一组序列：0, 1, 1, 2, 3, 5, 8, 13, 21, 34......
```suggestion
几乎所有的开发者都了解过 Fibonacci 数列相关的算法。[Fibonacci 数列](https://en.wikipedia.org/wiki/Fibonacci_number) 是这样的一组序列：0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55 一直到无穷大。
```

2021-02-08 16:47 UTC, PassionPenguin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +很多人认为，除了考查逻辑能力外，这种算法还能有什么其他实际应用价值呢。其实它的价值不止于此。例如，它可以用于 [DNA 序列的处理](https://pubmed.ncbi.nlm.nih.gov/11700586/)。
```suggestion
很多人认为，除了考查逻辑能力外，这种算法没有任何其他实际应用价值。但其实，它的价值远不止于此。例如，它可以用于 [DNA 序列的处理](https://pubmed.ncbi.nlm.nih.gov/11700586/)。
```

2021-02-08 16:47 UTC, PassionPenguin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +程序员都了解，二分查找是一种又快又好的、在已排序列表中进行查找的方法。很多教材上都有使用二分查找的例子，但是在实际开发中，它有用武之地吗？
```suggestion
程序员都了解，二分查找是一种又快又好的，在已排序列表中进行查找的方法。很多教材上都有使用二分查找的例子，但是在实际开发中，它有用武之地吗？
```

2021-02-08 16:47 UTC, PassionPenguin commented on article/2020/applications-of-some-of-the-famous-algorithms.md
> +二分查找到处都会用到。任何语言（Java、.NET、C++ 等）都可以创建已排序的集合，它们都可以使用（或选择使用）二分查找法来搜索相应元素。
```suggestion
二分查找到处都会用到。任何语言（如 Java、.NET、C++ 等）都可以创建已排序的集合，它们都可以使用（或选择使用）二分查找法来搜索相应元素。
```

2021-02-25 11:35 UTC, lsvih commented
@samyu2000 哈罗，有空来看看校对意见哈-。-

2022-01-15 10:07 UTC, Liang2028 commented
@lsvih 校对认领

2022-01-15 11:58 UTC, lsvih commented
@Liang2028 这篇现在没有必要校对哈

2022-05-05 13:54 UTC, jaredliw commented
接手
这作者不久前不是还在翻译文章吗。。。

2022-05-09 13:50 UTC, closed without merging