Python 中的运算符重载
xitu/gold-miner pull request #7750
Opened 2020-12-10 03:28 UTC by samyu2000

译文翻译完成，resolve #7695

2020-12-10 03:31 UTC, samyu2000 commented
@lsvih 翻译完成

2020-12-10 06:09 UTC, lsvih commented
为啥又是 3 个 Files change 🤦

2020-12-11 05:24 UTC, zhuzilin commented
@lsvih 申请校对。

2020-12-11 06:26 UTC, lsvih commented
@zhuzilin 好的~

2020-12-12 13:01 UTC, zhuzilin reviewed
@samyu2000 校对完成。翻译辛苦了~提了几个点，有些可能只是我个人说话方式导致的不同意见，所以只是作为参考~

2020-12-16 07:45 UTC, samyu2000 commented
@lsvih 已发布 https://juejin.cn/post/6906699052566462477

2020-12-16 08:55 UTC, zhuzilin commented
@samyu2000 是不是应该要等有2个校对矫正之后，然后这个issue变成翻译完成之后再发布......

2020-12-16 08:56 UTC, lsvih commented
@zhuzilin 是的→_→

2021-01-09 05:18 UTC, PassionPenguin requested changes
申请校对 @lsvih

2021-01-09 05:18 UTC, PassionPenguin commented on article/2020/operator-overloading-in-python.md
> +一种运算符对于不同类型的对象，有不同的使用方式。例如， `+` 用于整型对象，表示两个数相加；用于字符串，表示连接这两个字符串。
一种 -> 每一种

> 对于每一种运算符对于不同类型的对象，都有不同的使用方式。

2021-01-09 05:18 UTC, PassionPenguin commented on article/2020/operator-overloading-in-python.md
> +`**+**`运算符因操作对象的类型的不同而执行不同的操作，这种特性称为重载。
运算符后面或许可以加个空格
> `**+**` 运算符因操作对象的类型的不同而执行不同的操作，这种特性称为重载。

2021-01-09 05:18 UTC, PassionPenguin commented on article/2020/operator-overloading-in-python.md
> +在 Python 语言中，我们可以使用特殊方法来实现运算符重载。
使用与否的确无关紧要

2021-01-09 05:18 UTC, PassionPenguin commented on article/2020/operator-overloading-in-python.md
> +现在我们进行编码，使 Vector 对象支持 `+` 运算符。
（面对对象语言，基本一切都是对象）

2021-01-09 05:18 UTC, PassionPenguin commented on article/2020/operator-overloading-in-python.md
> +在 Python 中，使用特殊方法可以轻松实现运算符重载。关键在于理解数据模型和特殊方法。
同意

2021-01-09 05:18 UTC, PassionPenguin commented on article/2020/operator-overloading-in-python.md
> +这些方法能让你从 Python 的惯用特性中受益，并且能利用强大的标准库。
同意

2021-01-09 05:18 UTC, PassionPenguin commented on article/2020/operator-overloading-in-python.md
> +我们从理解什么是运算符重载开始，接着讨论了 Python 中运算符重载的一些限制条件、数据模型和特殊方法，然后在 Vector 类中实现了运算符重载。
为什么这一一个翻译对象一个翻译类

2021-08-11 08:18 UTC, jaredliw commented
@lsvih 发现问题，想认领校对，麻烦通过 #8996 ，谢谢。

2021-08-11 08:25 UTC, lsvih commented
@jaredliw  您好，这个 PR 处于 stale 状态，您可以在刚才您认领的另一个 PR 里进行校对

2021-08-11 13:15 UTC, jaredliw commented
> @jaredliw 您好，这个 PR 处于 stale 状态，您可以在刚才您认领的另一个 PR 里进行校对

发错地方了，抱歉抱歉

2022-04-21 15:17 UTC, jaredliw commented
@lsvih 接手

2022-04-24 06:05 UTC, closed without merging