Update flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multip…
xitu/gold-miner pull request #7784
Opened 2020-12-17 15:23 UTC by keepmovingljzy

…latform-is-here-to-stay.md

提交翻译内容

译文翻译完成，resolve #7688

2020-12-17 15:28 UTC, keepmovingljzy commented
@lsvih 翻译完成

2020-12-28 02:21 UTC, zhuzilin commented
@lsvih  申请校对

2020-12-29 01:31 UTC, lsvih commented
@zhuzilin 欢迎校对~

2020-12-30 02:21 UTC, zhuzilin reviewed
@lsvih 校对完成。
@keepmovingljzy 翻译辛苦了！我这里提了一些表述上的建议，很多我自己也不是很确定，欢迎来讨论~

2020-12-30 02:21 UTC, zhuzilin commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +所以为了完全控制其软件生态系统，Google 引入了 Flutter 框架和 Fuschia OS。 Dart 是一种可编译为机器码的语言，因此不需要依赖 Oracle 的 Java 虚拟机。
这里感觉 Java Virtual Machine 是不是就写成 JVM 就行，和上面比较统一

2020-12-30 02:21 UTC, zhuzilin commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +但是这并不能使 Kotlin / Native 暂时取代 Flutter，但可以确保构建 100％ 的原生应用程序 - 这是任何一个跨平台方案都没有做到的。
```suggestion
虽然上述这些并不能让 Kotlin / Native 在现在替代 Flutter，但它可以确保构建 100％ 的原生应用程序 - 这是任何一个跨平台方案都没有做到的。
```

2020-12-30 02:21 UTC, zhuzilin commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +不过Kotlin 通过支持多个运行时目标（类似于 Dart）确保了 JetBrains 的语言不会消失，并将继续成为 Android 开发人员的重要支撑。
这里的“不过”感觉应该是“无论如何，”会比较通，感觉他这个转折应该是想说“虽然Kotlin不能替代flutter”？主要是前面每一段最后都落到了Kotlin的好处...所以这里转折就让人有点看不懂...

Kotlin两侧空格。

2020-12-30 02:21 UTC, zhuzilin commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +实际上，Jetpack Compose（Android 的声明式 UI 框架）的推出强烈表明了对平台无关性的支持，这使 Kotlin Multiplatforms 成为跨平台应用程序开发的有力选择方案。
有力选择方案 => 有力竞争方案

2020-12-30 10:23 UTC, keepmovingljzy commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +不过Kotlin 通过支持多个运行时目标（类似于 Dart）确保了 JetBrains 的语言不会消失，并将继续成为 Android 开发人员的重要支撑。
无论如何也有点尴尬

2020-12-30 10:29 UTC, keepmovingljzy commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +Flutter 的迅速崛起无疑让 Android 开发人员的心里担忧，因为没有人在关心 Kotlin 的未来。
我也是看原文没有it seems like，就按原文吧，感觉这里为了更强的语气

2020-12-30 10:32 UTC, keepmovingljzy commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +对于不了解它的人来说，Flutter 是 Google 的跨平台框架，用于构建可在 Android，iOS，Web 和 Desktop 上运行的应用。它使用 Google 的 Dart 语言，与 Java 虚拟机（JVM）不兼容。
因为前面几个都是直接用英文了，这里就直接照着原文吧

2020-12-30 10:34 UTC, keepmovingljzy commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +对于那些不熟悉的人来说，因为 Android 设备中使用了某些Java API 和 JVM ，所以 Oracle 和 Google 多年来一直处于法律纠纷。
前面是了解，我觉得这里可以用熟悉，层层递进

2020-12-30 10:35 UTC, keepmovingljzy commented
@zhuzilin 感谢校对

2021-01-09 05:10 UTC, PassionPenguin requested changes

2021-01-09 05:10 UTC, PassionPenguin commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +# Flutter 可能是下一个大事件，但 Kotlin Multiplatform 一直都是大事件
一直都是，或许改为 一定是**当下的大事件** 会更好？

2021-01-09 05:10 UTC, PassionPenguin commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +Google 的 Flutter 框架在过去的一年中取得了巨大的进展。它已经成为人们茶余饭后常谈的话题，有的人称它为下一个大事件，而另一些人则只是将其作为一项闪亮的新技术进行推广而已。
将其作为 => 将其看作

2021-01-09 05:10 UTC, PassionPenguin commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +由 JetBrains 推出的 Kotlin 以及之后 Google 宣布它为 Android 开发的首选语言并没有让 Google 不再担忧，这是因为 Kotlin（与 Java 一样）仍然需要 JVM 才能运行（当时，Kotlin / Native 尚处于萌芽状态） ）。
这个句子有点奇怪，或许可以调整下语序

另外括号多了一个

> 而 JetBrains 推出了 Kotlin 以及之后 Google 宣布它为 Android 开发的首选语言，并没有让 Google 停下担忧 —— 这是因为 Kotlin（与 Java 一样）仍然需要 JVM 才能运行（当时，Kotlin / Native 尚处于萌芽状态）。

2021-01-09 05:10 UTC, PassionPenguin commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +该项目的其他内容包括 Kotlin / JS（会转换 Kotlin 代码），Kotlin 标准库以及任何与 JavaScript 兼容的依赖项。
> 会自动转换 Kotlin 代码为 Javascript 代码、Kotlin 标准库以及任何与 JavaScript 兼容的依赖。

https://kotlinlang.org/docs/reference/js-overview.html

2021-01-09 05:10 UTC, PassionPenguin commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +无论如何 Kotlin 通过支持多个运行时目标（类似于 Dart）确保了 JetBrains 的语言不会消失，并将继续成为 Android 开发人员的重要支撑。
这里应该是 JetBrains 开发的语言

或者译成 Kotlin 更好？

2021-01-09 05:10 UTC, PassionPenguin commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +无论如何 Kotlin 通过支持多个运行时目标（类似于 Dart）确保了 JetBrains 的语言不会消失，并将继续成为 Android 开发人员的重要支撑。
JetBrains的语言 —— 捷克语（

2021-01-09 05:10 UTC, PassionPenguin commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +------
？

2021-01-09 05:11 UTC, PassionPenguin commented
申请校对 @lsvih

2021-01-09 05:13 UTC, lsvih commented
@PassionPenguin 感谢校对~

2021-01-11 02:11 UTC, keepmovingljzy commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +# Flutter 可能是下一个大事件，但 Kotlin Multiplatform 一直都是大事件
我感觉这句话的意思是Flutter可能是下一个很重要的事情，但是Kotlin Mutiplatform（跨平台）已经在那里了，已经是一个很重要的事情了，从文字意思感觉也会一直是一个很重要的事情，因为它后面可能会支持其他系统，比如Kotlin-to-Dart的转译器支持等。

2021-01-11 02:27 UTC, keepmovingljzy commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +无论如何 Kotlin 通过支持多个运行时目标（类似于 Dart）确保了 JetBrains 的语言不会消失，并将继续成为 Android 开发人员的重要支撑。
JetBrains是一家捷克的软件开发公司，这里就按照JetBrains开发的语言来翻译吧。

2021-01-11 02:29 UTC, keepmovingljzy commented
@PassionPenguin 感谢校对~

2021-01-11 02:29 UTC, keepmovingljzy commented
@lsvih

2021-01-11 02:31 UTC, lsvih commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +> - 校对者：
增加校对者信息

2021-01-11 03:37 UTC, keepmovingljzy commented on article/2020/flutter-may-or-may-not-be-the-next-big-thing-but-kotlin-multiplatform-is-here-to-stay.md
> +> - 校对者：
@lsvih 添加完毕

2021-01-11 03:40 UTC, keepmovingljzy commented
@lsvih 翻译完成

2021-01-11 06:17 UTC, lsvih approved these changes

2021-01-11 06:17 UTC, merged

2021-01-11 06:17 UTC, lsvih commented
@keepmovingljzy  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-01-11 08:39 UTC, keepmovingljzy commented
@lsvih 文章发布完成，地址是：https://juejin.cn/post/6916418157641105421/

2021-01-11 10:24 UTC, PassionPenguin commented
@keepmovingljzy 找了些小小的问题，请您查收一下～