Web 应用缓存的基础知识
xitu/gold-miner pull request #7789
Opened 2020-12-21 09:48 UTC by regon-cao

译文翻译完成，resolve #7779

2020-12-24 06:24 UTC, ZavierTang commented
校对认领

2020-12-25 07:59 UTC, lsvih commented
@ZavierTang 好的~

2020-12-26 04:38 UTC, Usualminds commented
@lsvih 校对认领

2020-12-26 05:28 UTC, lsvih commented
@Usualminds 好滴

2020-12-27 09:32 UTC, Usualminds commented
@lsvih @regon-cao 校对完成，提了几个小建议

2020-12-27 09:36 UTC, Usualminds requested changes
@lsvih @regon-cao 校对完成，提了几个小建议

2020-12-27 09:36 UTC, Usualminds commented on article/2020/fundamentals-of-caching-web-applications.md
> +简单地说，在接收到类似性质的 HTTP 请求时，web 缓存能够重用存储在缓存中的 HTTP 响应。让我们思考一个简单的例子，用户从服务器请求某种类型的产品(书籍)。假设整个过程大约需要 670 毫秒。如果这个用户在当天晚些时候执行相同的查询，不会再次执行相同的计算并花费 670 毫秒，而是将存储在缓存中的 HTTP 响应直接返回给用户。这将大大减少响应时间。在现实场景中，这个响应时间不到 50
web 缓存能够重用存储在缓存中的 HTTP 响应 => web 缓存能够**复**用存储在缓存中的 HTTP 响应

2020-12-27 09:36 UTC, Usualminds commented on article/2020/fundamentals-of-caching-web-applications.md
> +由于缓存维护在离用户更近的地方，因此不需要往返于服务器之间。缓存越近，响应就越快。这将直接对用户体验产生积极的影响。
这将直接对用户体验产生积极的影响 => 这对提升用户体验有显著的效果

这里意译一下比较好理解？

2020-12-27 09:36 UTC, Usualminds commented on article/2020/fundamentals-of-caching-web-applications.md
> +## 哪里可以缓存?
哪里可以缓存? => 缓存应用在哪里? or 缓存的应用场景

2020-12-27 09:36 UTC, Usualminds commented on article/2020/fundamentals-of-caching-web-applications.md
> +Web 浏览器自身保留了一个小型缓存。通常，浏览器会设置策略来确定要被缓存的最重要的东西。这可能是特定于用户的内容，或者下载成本较高且很可能被重新使用的内容。若要禁用资源的缓存，可以如下所示设置响应头。
浏览器会设置策略来确定要被缓存的最重要的东西 => 浏览器会通过设置策略来缓存最重要的内容

2020-12-27 09:36 UTC, Usualminds commented on article/2020/fundamentals-of-caching-web-applications.md
> +Web 浏览器自身保留了一个小型缓存。通常，浏览器会设置策略来确定要被缓存的最重要的东西。这可能是特定于用户的内容，或者下载成本较高且很可能被重新使用的内容。若要禁用资源的缓存，可以如下所示设置响应头。
可以如下所示设置响应头 => 可以设置如下的响应头

2020-12-27 09:36 UTC, Usualminds commented on article/2020/fundamentals-of-caching-web-applications.md
> +位于消费设备和服务器基础设施之间的任何服务器都可以根据需要缓存内容。这些缓存可能由 ISPs 或其他独立机构维护。
消费设备 => 用户设备

2020-12-27 09:36 UTC, Usualminds commented on article/2020/fundamentals-of-caching-web-applications.md
> +你可以在后端服务中实现自己的缓存基础设施。在这种方法中，可以从外部连接点提供内容，而不需要经过后端服务器。你可以使用 Redis，Memcache 这样的服务来实现。
在这种方法中 => 使用这种方法

2020-12-27 09:36 UTC, Usualminds commented on article/2020/fundamentals-of-caching-web-applications.md
> +在实际情况中，你不能实现主动缓存，因为大多数时候它可能会返回陈旧的数据。这就是为什么应该有一个定制的缓存策略来平衡实现长期缓存和通过实现合适的缓存回收算法来响应更改站点的需求之间的关系。由于每个系统都是独特的，并且有自己的一系列需求，因此应该花充足的时间来创建缓存策略。
因为大多数时候它可能会返回陈旧的数据 => 因为大多数时候它可能会返回未更新的数据

2020-12-27 09:36 UTC, Usualminds commented on article/2020/fundamentals-of-caching-web-applications.md
> +在实际情况中，你不能实现主动缓存，因为大多数时候它可能会返回陈旧的数据。这就是为什么应该有一个定制的缓存策略来平衡实现长期缓存和通过实现合适的缓存回收算法来响应更改站点的需求之间的关系。由于每个系统都是独特的，并且有自己的一系列需求，因此应该花充足的时间来创建缓存策略。
这就是为什么应该有一个定制的缓存策略来平衡实现长期缓存和通过实现合适的缓存回收算法来响应更改站点的需求之间的关系

=>

这就是为什么应该需要一个定制的缓存策略来平衡和实现长期缓存，并且通过实现与之匹配的缓存回收算法来响应站点的内容更新

2020-12-27 09:36 UTC, Usualminds commented on article/2020/fundamentals-of-caching-web-applications.md
> +实现一个完美的缓存策略的关键是尽可能地促进积极的缓存，同时留出余地，在将来发生更改时使条目失效。
积极的 => 积极有效的
在将来发生更改时使条目失效 => 在将来站点内容更新时使缓存失效

2020-12-27 12:44 UTC, regon-cao commented
@Usualminds thank you。

2020-12-29 03:46 UTC, ZavierTang reviewed
校对完成 @lsvih ，@regon-cao 翻译很棒

2020-12-29 03:46 UTC, ZavierTang commented on article/2020/fundamentals-of-caching-web-applications.md
> +web 缓存只是一个能够临时存储 HTTP 响应的组件，只要满足某些条件，就可以将其用于后续的 HTTP 请求。
```suggestion
web 缓存只是一个能够临时存储 HTTP 响应的机制，只要满足某些条件，就可以将其用于后续的 HTTP 请求。
```

2020-12-29 03:46 UTC, ZavierTang commented on article/2020/fundamentals-of-caching-web-applications.md
> +Web 缓存是 HTTP 协议的一个关键设计特性，目的是减少网络流量，同时增强整个系统的预期响应能力。缓存存在于从服务器到浏览器的每一个阶段。
```suggestion
Web 缓存是 HTTP 协议的一个关键设计特性，目的是减少网络流量，同时提升整个系统的预期响应速度。缓存存在于从服务器到浏览器的每一个阶段。
```

2020-12-29 03:46 UTC, ZavierTang commented on article/2020/fundamentals-of-caching-web-applications.md
> +简单地说，在接收到类似性质的 HTTP 请求时，web 缓存能够复用存储在缓存中的 HTTP 响应。让我们思考一个简单的例子，用户从服务器请求某种类型的产品(书籍)。假设整个过程大约需要 670 毫秒。如果这个用户在当天晚些时候执行相同的查询，不会再次执行相同的计算并花费 670 毫秒，而是将存储在缓存中的 HTTP 响应直接返回给用户。这将大大减少响应时间。在现实场景中，这个响应时间不到 50
```suggestion
简单地说，在接收到类似性质的 HTTP 请求时，web 缓存能够复用存储在缓存中的 HTTP 响应。让我们思考一个简单的例子，用户从服务器请求某种类型的产品(书籍)。假设整个过程大约需要 670 毫秒。如果这个用户在当天晚些时候执行相同的查询，不会再次执行相同的计算并花费 670 毫秒，而是将存储在缓存中的 HTTP 响应直接返回给用户。这将大大减少响应时间。在现实场景中，这个响应时间可能不到 50 毫秒。
```

2020-12-29 03:46 UTC, ZavierTang commented on article/2020/fundamentals-of-caching-web-applications.md
> +#### 提升响应能力
```suggestion
#### 提升响应速度
```

2020-12-29 03:46 UTC, ZavierTang commented on article/2020/fundamentals-of-caching-web-applications.md
> +你可以在后端服务中实现自己的缓存基础设施。使用这种方法可以从外部连接点提供内容，而不需要经过后端服务器。你可以使用 Redis，Memcache 这样的服务来实现。
```suggestion
你可以在后端服务中实现自己的缓存基础设施。使用这种方法可以从外部连接点提供内容，而不需要经过后端服务器。你可以使用 Redis、Memcache 这样的服务来实现。
```

2020-12-29 03:46 UTC, ZavierTang commented on article/2020/fundamentals-of-caching-web-applications.md
> +## 能缓存什么?
```suggestion
## 能缓存什么？
```

2020-12-29 03:46 UTC, ZavierTang commented on article/2020/fundamentals-of-caching-web-applications.md
> +## 哪里可以缓存?
```suggestion
## 哪里可以缓存？
```

2020-12-29 03:46 UTC, ZavierTang commented on article/2020/fundamentals-of-caching-web-applications.md
> +- 图片，Logo，图标
```suggestion
- 图片、Logo、图标
```

2020-12-29 03:46 UTC, ZavierTang commented on article/2020/fundamentals-of-caching-web-applications.md
> +- 特定于用户的通常不应该被缓存，因为它是经常更新的.
```suggestion
- 特定于用户的通常不应该被缓存，因为它是经常更新的。
```

2020-12-29 03:46 UTC, ZavierTang commented on article/2020/fundamentals-of-caching-web-applications.md
> +## 为什么需要缓存策略？
```suggestion
## 为什么需要缓存策略？
```

2020-12-29 05:31 UTC, regon-cao commented
@ZavierTang thank you

2020-12-29 05:32 UTC, regon-cao commented
@lsvih 已校对修改完毕

2020-12-29 05:33 UTC, lsvih approved these changes

2020-12-29 05:34 UTC, merged

2020-12-29 05:34 UTC, lsvih commented
@regon-cao 已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-01-06 03:06 UTC, regon-cao commented
@lsvih 已发布咯 https://juejin.cn/post/6913898149740281870