iOS 中的 widget
xitu/gold-miner pull request #7790
Opened 2020-12-23 11:17 UTC by zhuzilin

译文翻译完成，resolve #7721

2020-12-24 07:16 UTC, zhuzilin commented
@lsvih 有空的时候给这个PR也加一下label呗~

2021-01-07 12:05 UTC, PassionPenguin requested changes
p2部分，应用代理是否应当按照原文以及下文的注释，对两个复数处理

翻译：

> 因此它不使用应用代理（app delegate）或导航栈（navigation stacks）

原文

>  it does not make use of **app delegates** or **navigation stacks**.

2021-01-07 12:07 UTC, PassionPenguin requested changes
[另外，p2有一处可改善阅读的语句](https://github.com/xitu/gold-miner/pull/7790/files/d50b4681ccd7db7621887d6f45abb597eb90c68c#diff-a0b30438f21e9667d771a8ac772a9e1df1179486a07b27bedcc6e0240567eb58R15)

> 此外，widget 不能独立存在，而是需要一个父应用程序

建议在 **需要一个父应用程序** 改为 **需要依赖于一个父应用程序** ，消除 组建需要程序 这个不恰当的词语搭配

2021-01-07 12:09 UTC, PassionPenguin requested changes
另外，基本配置-p1

>  我们现在需要添加一个 widget 扩展，widget 的代码就将放在这个扩展里。

[建议按照原文，将后文用定语从句合并两个长句，便于阅读](https://github.com/xitu/gold-miner/pull/7790/files/d50b4681ccd7db7621887d6f45abb597eb90c68c#diff-a0b30438f21e9667d771a8ac772a9e1df1179486a07b27bedcc6e0240567eb58R29)

>  我们现在需要添加一个 widget 扩展 以存放 widget 的代码。

2021-01-07 12:53 UTC, PassionPenguin requested changes
修改建议，麻烦查看一下，幸苦了译者，最高敬意。

2021-01-07 12:53 UTC, PassionPenguin commented on article/2020/widgets-on-ios.md
> +注意，WidgetConfiguration 会返回一个 StaticConfiguration 实例。实际上存在两类 widget 配置，静态配置和 intent 配置。intent 配置让用户可以在运行时设置 widget。在我们现在的配置（也就是静态配置）中，widget 显示的是静态数据，也就是说，用户无法在运行时更改 widget 上显示的数据。
intent配置 是否可以翻译以减少中英文交错？
参考翻译： 自定义配置、目标配置？

[参考：](https://developer.apple.com/documentation/widgetkit/intentconfiguration)
An object describing the content of a widget that uses a **custom intent** definition to provide user-configurable options.

2021-01-07 12:53 UTC, PassionPenguin commented on article/2020/widgets-on-ios.md
> +在本次演示中，我们将实现一个让用户可以从一系列城市中进行选择的 widget。
这里翻译后与英文语境有较大的脱离，或者说变得有些许难以理解与不通畅，英文语境下能够容易理解

> 控件能让用户从一个有关城市的列表中选择选项

翻译后列表、选项关键词消失了，令人惑而无解

> 让用户可以从一系列城市中进行选择的 widget

2021-01-07 12:53 UTC, PassionPenguin commented on article/2020/widgets-on-ios.md
> +在 **Static_Widget** 的定义部分中，添加一个新的 IntentConfiguration。它需要一个 intent 实例，把 **CityNameIntent** 传给它。对于 Provider，请使用我们创建的 **ConfigurableProvider**。其余的保持不变。
这里翻译有误，参考一下代码。

理应翻译为：

> 在 **Static_Widget** 的定义部分中，将代码中的 StaticConfiguration 修改为 IntentConfiguration。它需要一个 intent 实例，把 **CityNameIntent** 传给它。对于 Provider，请使用我们创建的 **ConfigurableProvider**。其余的保持不变。

我自己在Xcode 12.3 上跑了一遍步骤，前文所提及的复选框，如果勾选，得到的控件 `a`

```swift
@main
struct a: Widget {
    let kind: String = "a"

    var body: some WidgetConfiguration {
        IntentConfiguration(kind: kind, intent: ConfigurationIntent.self, provider: Provider()) { entry in
            aEntryView(entry: entry)
        }
        .configurationDisplayName("My Widget")
        .description("This is an example widget.")
    }
}
```


以及不勾选后的控件 `b`


```swift
@main
struct b: Widget {
    let kind: String = "b"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: Provider()) { entry in
            bEntryView(entry: entry)
        }
        .configurationDisplayName("My Widget")
        .description("This is an example widget.")
    }
}
```

可见本身就有一个 StaticConfiguration 定义，作者本意应该是替换而非添加定义，可以理解为作者原文即有不恰当的用词，建议将翻译中的 **【添加】** 更改为 **【修改】**

2021-01-07 12:53 UTC, PassionPenguin commented on article/2020/widgets-on-ios.md
> +到这里，用户就可以配置我们的 widget 了。运行应用，长按 widget 并选择 “Edit Widget”，你将看到一个我们提供的城市名称列表。
这里完全翻译错了，用户这个词语哪来的？！

> 到这里，用户就可以配置我们的 widget 了。

应该是

> 到这里，我们的 widget 就配置完了。

2021-01-07 13:02 UTC, lsvih commented
@PassionPenguin 感谢您的校对！

2021-01-08 01:43 UTC, zhuzilin commented on article/2020/widgets-on-ios.md
> +到这里，用户就可以配置我们的 widget 了。运行应用，长按 widget 并选择 “Edit Widget”，你将看到一个我们提供的城市名称列表。
@PassionPenguin 
这里反对您的意思，并不存在错译。
"With that, our widget is now **configurable**" 的直译应该是 "通过上面的代码调整，我们的 widget 就变得**可配置**了"。
原文这一节的目的就是将 widget 从静态变为用户可配置的状态。调整为“用户可以配置”是因为我认为” widget 为可配置状态“不符合中文表述习惯。而您给的翻译修改“我们的 widget 就配置完了”，明显是错译了 "configurable"，而是理解为了 "our widget is now configured"。

2021-01-08 01:49 UTC, zhuzilin commented on article/2020/widgets-on-ios.md
> +注意，WidgetConfiguration 会返回一个 StaticConfiguration 实例。实际上存在两类 widget 配置，静态配置和 intent 配置。intent 配置让用户可以在运行时设置 widget。在我们现在的配置（也就是静态配置）中，widget 显示的是静态数据，也就是说，用户无法在运行时更改 widget 上显示的数据。
这里保留 intent 的原因主要是为了让读者能够比较方便地和后文的源码中以及 Xcode 选项中的 intent 对应起来，以及不确定该词是否有比较统一的术语翻译。

2021-01-08 01:54 UTC, zhuzilin commented
@PassionPenguin 对您给出的校对意见有一些不同看法，欢迎来讨论。

2021-01-08 08:58 UTC, PassionPenguin commented on article/2020/widgets-on-ios.md
> +注意，WidgetConfiguration 会返回一个 StaticConfiguration 实例。实际上存在两类 widget 配置，静态配置和 intent 配置。intent 配置让用户可以在运行时设置 widget。在我们现在的配置（也就是静态配置）中，widget 显示的是静态数据，也就是说，用户无法在运行时更改 widget 上显示的数据。
no prob，这个词也属于专有名词～

2021-01-08 08:59 UTC, PassionPenguin commented on article/2020/widgets-on-ios.md
> +到这里，用户就可以配置我们的 widget 了。运行应用，长按 widget 并选择 “Edit Widget”，你将看到一个我们提供的城市名称列表。
呐，configurable总感觉应当适用于代码逻辑中哇

然后如果是用户可配置的状态，我觉得更应该翻译为交互，interact～

2021-01-08 09:01 UTC, PassionPenguin commented on article/2020/widgets-on-ios.md
> +到这里，用户就可以配置我们的 widget 了。运行应用，长按 widget 并选择 “Edit Widget”，你将看到一个我们提供的城市名称列表。
但如果是按照这一个类名就是IntentConfiguration，倒更像是已经配置了，换个角度理解，当然也可以是可配置的——可以自定义修改Configuration的内容

2021-01-19 15:01 UTC, zenblo commented
@lsvih 校对认领

2021-01-19 15:04 UTC, PassionPenguin commented
> @PassionPenguin 对您给出的校对意见有一些不同看法，欢迎来讨论。

呐？没有回复了呐

记得看看校对意见嗷，幸苦译者大大啦：）

2021-01-19 15:20 UTC, zenblo commented on article/2020/widgets-on-ios.md
>  > * 校对者：
添加校对者信息

2021-01-19 15:20 UTC, zenblo commented on article/2020/widgets-on-ios.md
> +苹果最近在 iOS 中支持了 widget。它们可以让用户在不访问应用程序的情况下获取有限但有用的信息。
苹果最近在 iOS 中支持了 widget（应用小插件）。
我建议补上解释说明，方便没有背景知识的读者理解

2021-01-19 15:20 UTC, zenblo commented on article/2020/widgets-on-ios.md
> +本文需要你已经熟悉 SwiftUI，因为构建 widget 的过程中会大量使用它。由于 widget 自身并不是一个完整的应用程序，因此它不使用应用代理（app delegate）或导航栈（navigation stacks）。此外，widget 不能独立存在，而是需要一个父应用程序。
而是需要一个父应用程序。
=>而是需要依赖一个父应用程序。

2021-01-19 15:20 UTC, zenblo commented on article/2020/widgets-on-ios.md
> +总而言之，小部件为用户提供了应用信息的快照。操作系统会在你设置的时刻快速触发 widget 以刷新其视图。
小部件为用户提供了应用信息的快照
=>widget 为用户提供了应用信息的快照

2021-01-19 15:20 UTC, zenblo commented on article/2020/widgets-on-ios.md
> +2. Xcode 12 或更高版本，Xcode  12 的[链接](https://developer.apple.com/download/more/)（如果不能从应用商店更新的话可以使用这个链接，不能直接更新的原因一般是磁盘空间不足）
Xcode  12 的
=>Xcode 12 的
多了一个空格

2021-01-19 15:20 UTC, zenblo commented on article/2020/widgets-on-ios.md
> +WidgetKit支持小、中、大三种尺寸。
WidgetKit支持小、中、大三种尺寸
=>WidgetKit 支持小、中、大三种尺寸

2021-01-19 15:20 UTC, zenblo commented on article/2020/widgets-on-ios.md
> +**getTimeline函数**用于告诉 widget 在不同时间需要显示什么内容。**时间线** 基本上是遵从 **TimelineEntry** 协议的对象的数组。例如，如果你想做一个显示特定事件的倒计时天数的 widget，你就需要创建从现在到那个事件发生日的一系列视图。
**getTimeline函数**
=>**getTimeline 函数**

2021-01-19 15:22 UTC, zenblo commented
@lsvih @zhuzilin 校对完成。文章很棒，提了一点格式问题。
@PassionPenguin 我看了前面的讨论，我觉得文章整体很棒，至于一些意译地方也很贴切，并没有错译。

2021-01-20 01:24 UTC, lsvih commented
@zenblo 感谢校对

2021-01-20 01:57 UTC, zhuzilin commented
> > @PassionPenguin 对您给出的校对意见有一些不同看法，欢迎来讨论。
> 
> 嗨！
> 
> 记得看看校对意见嗷，幸苦译者大大啦：）

抱歉，这两天有点忙...争取今天改过来~

2021-01-20 13:34 UTC, zhuzilin commented
@PassionPenguin @zenblo 感谢两位的校对~ @lsvih 已经根据校对进行了修改。

2021-01-20 17:31 UTC, lsvih approved these changes

2021-01-20 17:31 UTC, lsvih commented on article/2020/widgets-on-ios.md
> +接下来，让我们谈谈 **‘SimpleEntry’**。它的类型是 **‘TimelineEntry’** ，主要负责 widget 的数据模型。在我们的样例中，只用了一个日期参数，你可以根据需要添加其他值。例如，如果需要依照一些条件向用户显示文本，则可以在此处添加文本参数。在这个结构体中，你需要实现日期参数，用于为 OS 提供不同的数据时间戳（译者注：让 OS 知道什么时间使用这条数据）。
```suggestion
接下来，让我们谈谈 **‘SimpleEntry’**。它的类型是 **‘TimelineEntry’**，主要负责 widget 的数据模型。在我们的样例中，只用了一个日期参数，你可以根据需要添加其他值。例如，如果需要依照一些条件向用户显示文本，则可以在此处添加文本参数。在这个结构体中，你需要实现日期参数，用于为 OS 提供不同的数据时间戳（译者注：让 OS 知道什么时间使用这条数据）。
```

2021-01-20 17:32 UTC, merged

2021-01-20 17:32 UTC, lsvih commented
@zhuzilin  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-01-21 01:48 UTC, lsvih commented
收到