GitHub Package Registry 值得尝试吗
xitu/gold-miner pull request #7807
Opened 2021-01-02 04:33 UTC by zenblo

译文翻译完成，resolve #7719

2021-01-07 14:51 UTC, PassionPenguin commented
申领校对
@lsvih

2021-01-07 14:58 UTC, PassionPenguin requested changes
大体上没有问题

2021-01-07 14:58 UTC, PassionPenguin commented on article/2020/github-package-registry-is-it-worth-trying-out.md
> +然而，你可能想知道 GitHub 包管理器是否会作为一个核心特性脱颖而出？到目前为止，GitHub 已经巧妙地将它放在其核心产品组合中。此外，GitHub 已经实现了一套具有较高影响力的功能体系让我们启用。
启用一词不太适合语境，可参考修改为 

> 实现了一套具有较高影响力的功能体系【供我们入门】。

2021-01-07 14:58 UTC, PassionPenguin commented on article/2020/github-package-registry-is-it-worth-trying-out.md
> +在即将到来的版本更新中，我们可以期待支持更多的开发工具和客户端。
期待后面跟上个宾语和虚拟预期如何

> 在即将到来的版本更新中，我们可以期待**它会**支持更多的开发工具和客户端。

2021-01-07 14:58 UTC, PassionPenguin commented on article/2020/github-package-registry-is-it-worth-trying-out.md
> +与其他包管理器类似，GitHub 包注册表允许在下载之前查看包内容、下载统计数据和历史版本，以便在下载前有更好地了解。
包注册表与上文翻译不同，建议保留名词 Github Package Registry

2021-01-07 14:58 UTC, PassionPenguin commented on article/2020/github-package-registry-is-it-worth-trying-out.md
> +> 因为我们可以通过查看 GitHub 项目的 stars 和 forks 来理解它的活跃度，所以有助于找到合适的包以便我们在代码中使用。
【理解】建议改为【了解】

2021-01-07 14:58 UTC, PassionPenguin commented on article/2020/github-package-registry-is-it-worth-trying-out.md
> +**然而，如果我已经在其他地方托管包，我应该从哪里开始呢？**
为什么标题改成了加粗

2021-01-07 14:58 UTC, PassionPenguin commented on article/2020/github-package-registry-is-it-worth-trying-out.md
> +然后初始化一个新的 NPM 项目，打开 VSCode 并使用 `npm init` 命令。
使用 改为 运行

2021-01-07 14:58 UTC, PassionPenguin commented on article/2020/github-package-registry-is-it-worth-trying-out.md
> +创建主要 JavaScript 文件并编写一个简单函数。在这里，我在根目录中创建了一个名为 index.js 的文件来测试该软件包。
这里的【主要 Javascript】是否与main.js的含义不太吻合？

可参考将主要移到JS后，变为

> 创建 JavaScript (主脚本/主程序)文件

2021-01-08 02:39 UTC, zenblo commented
@PassionPenguin 感谢校对
@lsvih 完成 1 次校对

2021-01-08 03:24 UTC, lsvih approved these changes

2021-01-08 03:24 UTC, lsvih commented
一次校对后已经足够顺畅了~

2021-01-08 03:24 UTC, merged

2021-01-08 03:25 UTC, lsvih commented
@zenblo  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-01-08 05:31 UTC, zenblo commented
@PassionPenguin @lsvih 掘金文章发布地址  https://juejin.cn/post/6915255280959750152

2021-01-08 08:57 UTC, PassionPenguin commented
非常感谢译者大大的翻译！