不同类型的浏览器存储
xitu/gold-miner pull request #7823
Opened 2021-01-07 11:32 UTC by flashhu

译文翻译完成，resolve #7809

2021-01-07 13:31 UTC, PassionPenguin requested changes

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +* 允许和第三方共享数据（如第三方 cookie）
若是局限性，就应该翻译为

> 会导致被第三方读取数据

而译文的理解上是cookie的作用

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +Cookie 导致多种安全问题，因此现在建议尽可能使用现代存储 API。
将原句应改为，将一般现在的事件改为可能性事件

> ... Cookie 会导致 ...

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +Web Storage API 允许 Web 应用在用户浏览器中本地存储数据。 这些 API 已作为 HTML5 标准的一部分。
这些 改为 这个

<img width="250" alt="Screen Shot 2021-01-07 at 9 04 36 PM" src="https://user-images.githubusercontent.com/41184947/103895875-0c32d180-512c-11eb-8a2d-316c491d58fc.png">

这应当属于一类，用单数。

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +Web Storage API 以键/值对形式存储数据。所有数据都存储为字符串，所有被添加到存储空间中的数据会被隐式转换为字符串类型。在查询数据时，它将类型显式转换为所需类型。`JSON.parse()` 和 `JSON.stringify()` 方法可用于序列化和反序列化对象数据。
专有名词 类型显式 -> 显式类型

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +Web Storage API 调用是同步的，因此它们可能会影响 UI 渲染。使用 Web Storage API 用于存储和查询少量数据。Web Storage API 易于在用户浏览器上存储及查询数据 —— 所有现代浏览器都支持 Web Storage API。
1. 加个助词 **的**

> Web Storage API **的**调用是同步的

2. 可以提升翻译更大程度翻译外文：

> 也因为如此，我们仅应该使用 Web Storage API 存储和查询少量数据。

3. 并将文章划断，添加新段落，写它的好处（这个段落写的是WS API在渲染上的不利影响）

> Web Storage API 易于在用户浏览器上存储及查询数据 —— 所有现代浏览器都支持 Web Storage API。

4. 最后再将语言整理变得流畅一些：

>  在用户浏览器上使用 Web Storage API 存储及查询数据是便捷的 —— 所有现代浏览器都支持 Web Storage API。

归总：

> Web Storage API 的调用是同步的，因此它们可能会影响 UI 渲染。也因为如此，我们仅应该使用 Web Storage API 存储和查询少量数据。

> 在用户浏览器上使用 Web Storage API 存储及查询数据是便捷的 —— 所有现代浏览器都支持 Web Storage API。

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +IndexedDB 是一个基于 JavaScript的面向对象数据库。IndexedDB 允许你存储和查询键（主键，如 SSN）索引的对象。任何结构化克隆算法支持的对象（如，视频，图片）都可以被存储。IndexedDB 的使用比 Web Storage API 复杂得多。
请注意英语后的空格以及标点符号的适当修改

> IndexedDB 是一个基于 **JavaScript** 的面向对象数据库。IndexedDB 允许你存储和查询键（主键，如 **SSN** ）索引的对象。任何结构化克隆算法支持的对象（如**：**视频，图片）都可以被存储。IndexedDB 的使用比 Web Storage API 复杂得多。

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +IndexedDB 是一种在用户浏览器中持久化存储大量数据的方法。IndexedDB 允许你创建具有高级功能的 Web 应用，而不用关心网络可用性。这些应用在线，离线都可以工作。IndexedDB 对需要存储大量数据的应用及工作时不要求网络持续连通的应用而言非常有用。
**持久化存储** 应该修改为 **长时间地存储**

高级功能修饰 【不用关心网络可用性】，应当修改为：

> IndexedDB 允许你创建具有不用关心网络可用性这一高级功能的 Web 应用。

另，下文应当注意顿号使用：

> 这些应用在线【， => 、】离线都可以工作。

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +IndexDB API 是异步的，不会阻塞 UI 渲染。这个 API 使用索引以支持对数据的高性能搜索。
这里原文专有名词有问题，应该修改为：

【IndexedDB】是异步的，不会阻塞 UI 渲染。这个 API 使用索引以支持对数据的高性能搜索。

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +创建数据库模式及对象，打开数据库连接，然后在一系列事务中查询和更新数据。IndexDB 允许存储大量结构化数据。具体大小取决于浏览器。
此处并没有必要划段，两者语境上是连续的。

另外，翻译【事务】完全不准确，看来是谷歌翻译的

最后，同上段，IndexDB => IndexedDB

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +数据库对源（域/协议/端口）是私有的，因此任何网站不能访问其他网站的 IndexDB 存储。
这里就是译者的翻译错误了，IndexDB => IndexedDB

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +					// 设置键生成器（autoIncrement: true），默认不开启
默认不开启应当是修饰autoIncrement的吧，为什么在括号外面？

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +					// 查询特定对象的事务，指定模式 - 只读，读写和版本变更
【事务】翻译不妥当吧

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +该规范基于 SQLite。Web SQL 数据库未被所有浏览器支持 —— 该标准已被 W3C 否决，IndexDB 应该会成为替代品。
IndexDB => IndexedDB

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +					// 事务
总感觉transaction翻译为事务不太妥当，或许可以参考翻译为 执行的任务

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +> —— [Chidume Nnamdi](undefined) 的 [点点滴滴](https://blog.bitsrc.io/introduction-to-the-cache-storage-a-new-browser-cache-pwa-api-a5d7426a2456)
bits and pieces是个medium专栏，可以在后面加 专栏 两字

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +CacheStorage API 可以在 Windows 上下文（DOM 上下文）中使用，也可以和 Service Worker API 一起使用以实现离线访问。在本教程中，我们将更多地讨论 DOM 上下文。
原文错误，Windows上下文应该是Window上下文，参考：
<img width="254" alt="Screen Shot 2021-01-07 at 9 28 05 PM" src="https://user-images.githubusercontent.com/41184947/103897987-3df96780-512f-11eb-88f7-dafdf48b42b0.png">

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +相关演示参见[浏览器存储演示](https://github.com/techforum-repo/youttubedata/tree/master/browser-storage-demos)（这个演示是在 Node.js 上构建的，使用 Express.js）。
合并定语

> 这个演示是在 Node.js 上使用 Express.js 构建的

2021-01-07 13:31 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +对于存储大量应用或用户生成的数据，IndexedDB 是更好的选择。
合并段落及翻译错误： 

> 你可以选择使用 CacheStorage API 存储供离线访问的数据，而在存储大量应用或用户生成的数据的情况下，IndexedDB 是更好的选择。当然，Cookie 仍可以用于存储用于服务器识别的小型数据。

> 本地存储（localStorage）和会话存储（sessionStorage）则可用于存储少量数据。本地存储和会话存储的 API 是同步的，因此它们会影响 UI 渲染，但与此同时，它们这两个 API 易于在项目中使用。

2021-01-07 14:06 UTC, k8scat commented
认领校对

2021-01-07 14:08 UTC, PassionPenguin commented
认领下上面的校对♪:)

2021-01-07 14:14 UTC, PassionPenguin commented
> 认领下上面的校对♪:)

@lsvih

2021-01-07 14:19 UTC, k8scat commented
@Glowin 认领校对

2021-01-07 14:43 UTC, flashhu commented on article/2021/the-different-types-of-browser-storage.md
> +Web Storage API 以键/值对形式存储数据。所有数据都存储为字符串，所有被添加到存储空间中的数据会被隐式转换为字符串类型。在查询数据时，它将类型显式转换为所需类型。`JSON.parse()` 和 `JSON.stringify()` 方法可用于序列化和反序列化对象数据。
这里应该是 显式转换 吧？类型 显式转换为 所需类型

2021-01-07 14:59 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +Web Storage API 以键/值对形式存储数据。所有数据都存储为字符串，所有被添加到存储空间中的数据会被隐式转换为字符串类型。在查询数据时，它将类型显式转换为所需类型。`JSON.parse()` 和 `JSON.stringify()` 方法可用于序列化和反序列化对象数据。
嗷，我看走眼了，抱歉啊！（

2021-01-07 15:00 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +Web Storage API 以键/值对形式存储数据。所有数据都存储为字符串，所有被添加到存储空间中的数据会被隐式转换为字符串类型。在查询数据时，它将类型显式转换为所需类型。`JSON.parse()` 和 `JSON.stringify()` 方法可用于序列化和反序列化对象数据。
非常抱歉！

2021-01-07 15:06 UTC, flashhu commented on article/2021/the-different-types-of-browser-storage.md
> +创建数据库模式及对象，打开数据库连接，然后在一系列事务中查询和更新数据。IndexDB 允许存储大量结构化数据。具体大小取决于浏览器。
如果觉得原文有改进空间，请提出具体建议哦。光一个不准确，确实不太明白咋样算准确。
https://zh.wikipedia.org/wiki/%E6%95%B0%E6%8D%AE%E5%BA%93%E4%BA%8B%E5%8A%A1

2021-01-07 15:09 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +创建数据库模式及对象，打开数据库连接，然后在一系列事务中查询和更新数据。IndexDB 允许存储大量结构化数据。具体大小取决于浏览器。
有专有名词啊，谢谢您的提醒，已修改

2021-01-07 15:11 UTC, flashhu commented on article/2021/the-different-types-of-browser-storage.md
> +					// 设置键生成器（autoIncrement: true），默认不开启
该选项默认不开启，如果想设为开启，需要设置为 true，故翻译时将默认不开启放在逗号后面
https://developer.mozilla.org/zh-CN/docs/Web/API/IndexedDB_API/Using_IndexedDB#%E4%BD%BF%E7%94%A8%E9%94%AE%E7%94%9F%E6%88%90%E5%99%A8

2021-01-07 15:21 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +					// 设置键生成器（autoIncrement: true），默认不开启
理解，我的意思是，默认不开启应当修饰键生成器，加了逗号是割裂了句子，应该取消定语的独立性，或在定语前加该选项，个人意见时，如果要按照译者的意思翻译，可以是

> 这里默认不开启键生成器（autoIncrement: true）

2021-01-07 15:21 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +					// 设置键生成器（autoIncrement: true），默认不开启
-- 的确，该处翻译没有大碍，但是阅读有些不通畅吧，而且似乎原文并没有设置键生成器，而是给了一条注释，提示读者可以去自己变更设置。

2021-01-07 15:25 UTC, flashhu commented
@PassionPenguin 感谢校对，非常棒~

2021-01-07 15:28 UTC, PassionPenguin submitted a review, later dismissed
非常感谢！幸苦译者了～

2021-01-07 15:30 UTC, flashhu commented on article/2021/the-different-types-of-browser-storage.md
> +					// 设置键生成器（autoIncrement: true），默认不开启
是的。翻译的时候感觉不注一些的话，单这条注释出现的有点突然，故改成了那样

2021-01-07 15:31 UTC, flashhu commented on article/2021/the-different-types-of-browser-storage.md
> +					// 设置键生成器（autoIncrement: true），默认不开启
如不注任何东西，可能存在误解，认为默认设置键生成器

2021-01-07 15:34 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +					// 设置键生成器（autoIncrement: true），默认不开启
是的，这个我感觉原作者，应该是...开发过程中曾经用到了，或者希望这样做，然后忘记删除或加TODO，发代码的时候忘掉了这个遗漏的注释，也没有及时检查

2021-01-07 15:34 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +					// 设置键生成器（autoIncrement: true），默认不开启
（这样一看，我的proj似乎也有很多这样的代码，doge（

2021-01-07 17:48 UTC, PassionPenguin reviewed
部分关于语句通顺的建议

2021-01-07 17:48 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +* 持久化站点活动
持久化或许改为

> 长期的网站活动

会更易通顺

2021-01-07 17:48 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +Cookie 可以通过 JavaScript 中的 `document.cookie` 被创建，更新或读取。`HTTPOnly` cookie 标志可在 JavaScript 中被用于限制 cookie 访问，从而减少一些安全隐患，如跨站脚本（cookie 仅用于服务器访问）。
注，中间的 【`HTTPOnly` cookie 标志可在 JavaScript 中被用于限制 cookie 访问】 翻译无误

2021-01-07 17:48 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +Cookie 可以通过 JavaScript 中的 `document.cookie` 被创建，更新或读取。`HTTPOnly` cookie 标志可在 JavaScript 中被用于限制 cookie 访问，从而减少一些安全隐患，如跨站脚本（cookie 仅用于服务器访问）。
不一定是攻击，但这里翻译可以改善，如：

> 从而减少一些安全隐患，如被跨站脚本读取（cookies 理应仅供于服务器端访问）。

2021-01-07 17:48 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +Cookie 可分为两类：会话期 cookie 和持久性 cookie。
参考 https://en.wikipedia.org/wiki/HTTP_cookie#Persistent_cookie

而且这里的Cookie也可以单指一个Cookie的类型

2021-01-07 17:48 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +* 一个域下的 cookie 数量有限制，具体取决于浏览器（如 20 个）
k8scat的【实现方式】翻译不太妥当，而应该是浏览器的限制

实现方式是被代码与逻辑与语言所限制，而浏览器的限制则是对单个页面存储最大容量的规定限制

2021-01-07 17:48 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +* 跨域 cookie 的总数有限制，具体取决于浏览器（如 300 个）。一旦达到限制数量，为存储新的 cookie，最老的 cookie 将被移除。
这里没有必要修改，原文已经足以。

同时，实现方式见上文

为了和为，都是现代汉语中的常见使用，没有必要修改

2021-01-07 17:48 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +Cookie 导致多种安全问题，因此现在建议尽可能使用现代存储 API。
这里的翻译歧义，原文的modern，作者应该是指向whatwg、w3c的新的存储接口标准，如果是modern browser，那照样有大把modern browser不支持最新的接口，例如万年拖更Safari

2021-01-07 17:48 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +Cookie 导致多种安全问题，因此现在建议尽可能使用现代存储 API。
API这一专有名词要是看不懂那还是别学编程了吧，至少，这是个在编程中出现的，极度常见的英文单词了

2021-01-07 17:48 UTC, PassionPenguin commented on article/2021/the-different-types-of-browser-storage.md
> +Web Storage API 允许 Web 应用在用户浏览器中本地存储数据。 这些 API 已作为 HTML5 标准的一部分。
参考whatwg的原文，以及谷歌翻译的例句，这里的api不是指单一的存储类型，而是对所有存储方法的一个统称。

<img width="433" alt="Screen Shot 2021-01-08 at 1 45 42 AM" src="https://user-images.githubusercontent.com/41184947/103925960-3f3c8b80-5153-11eb-9d0d-4b8909cbc3f2.png">

2021-01-08 02:22 UTC, k8scat commented on article/2021/the-different-types-of-browser-storage.md
> +* 一个域下的 cookie 数量有限制，具体取决于浏览器（如 20 个）
这里的考虑是为了保持与译者上面的翻译一致，译者在上一句的翻译中用到了实现方式。

2021-01-08 03:42 UTC, flashhu commented on article/2021/the-different-types-of-browser-storage.md
> +Cookie 保存客户端的数据，为网站访问者提供个性化的体验。Cookie 在服务端生成，随响应发到客户端，每次请求都会与服务器交换数据。服务器可以根据 cookie 中的数据向用户发送个性化的内容。
个人还是倾向均使用单数形式，翻译时的大小写参照现代 JavaScript 教程中的形式 https://zh.javascript.info/cookie

2021-01-08 03:49 UTC, k8scat commented on article/2021/the-different-types-of-browser-storage.md
> +Cookie 保存客户端的数据，为网站访问者提供个性化的体验。Cookie 在服务端生成，随响应发到客户端，每次请求都会与服务器交换数据。服务器可以根据 cookie 中的数据向用户发送个性化的内容。
这部分没什么问题了

2021-01-08 03:58 UTC, flashhu commented on article/2021/the-different-types-of-browser-storage.md
> +Cookie 可以通过 JavaScript 中的 `document.cookie` 被创建，更新或读取。`HTTPOnly` cookie 标志可在 JavaScript 中被用于限制 cookie 访问，从而减少一些安全隐患，如跨站脚本（cookie 仅用于服务器访问）。
cookies 理应仅供于服务器端访问 => 这类 cookie 仅供服务器端访问
参照该部分文档最后一段第一句 https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Cookies#%E9%99%90%E5%88%B6%E8%AE%BF%E9%97%AE_cookie

2021-01-08 04:07 UTC, k8scat submitted a review, later dismissed
辛苦译者了~

2021-01-08 04:07 UTC, flashhu commented on article/2021/the-different-types-of-browser-storage.md
> +* 持久化站点活动
持久化，应该也是一个专用词，如上文提到的某处参考文档中最后一段第二句
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Cookies#%E9%99%90%E5%88%B6%E8%AE%BF%E9%97%AE_cookie

2021-01-08 04:16 UTC, flashhu commented on article/2021/the-different-types-of-browser-storage.md
> +Cookie 可分为两类：会话期 cookie 和持久性 cookie。
翻译时，多参考『MDN』和『现代 Javascript 教程』中的翻译方式，确实没注意这部分的区分，除原标题中仍保留复数形式外，均在翻译时改成了单数形式，大小写为位于句首保持大写。

2021-01-08 04:32 UTC, flashhu commented on article/2021/the-different-types-of-browser-storage.md
> +* 一个域下的 cookie 数量有限制，具体取决于浏览器（如 20 个）
是的，这部分的翻译表述没有统一。参照原文直接翻译为『浏览器实现』，有点拗口，故第一次出现时翻成了『浏览器的实现方式』。统一改为『具体限制取决于浏览器』如何？

2021-01-08 04:35 UTC, flashhu commented on article/2021/the-different-types-of-browser-storage.md
> +* 一个域下的 cookie 数量有限制，具体取决于浏览器（如 20 个）
只能存储 4 KB 的数据 —— 此限制依据浏览器的实现方式会有所差异 => 只能存储 4 KB 的数据，具体限制取决于浏览器
之后两点，因前半句均以限制结尾，故保留原句『具体取决于浏览器』

2021-01-08 04:40 UTC, k8scat commented on article/2021/the-different-types-of-browser-storage.md
> +* 一个域下的 cookie 数量有限制，具体取决于浏览器（如 20 个）
可以的，不一定要完全按照原文翻译，能够理解就好

2021-01-08 05:05 UTC, flashhu commented
@k8scat @PassionPenguin 感谢两位的认真校对~
@lsvih 校对完成

2021-01-08 05:19 UTC, lsvih approved these changes

2021-01-08 05:19 UTC, merged

2021-01-08 05:19 UTC, lsvih commented
@flashhu  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-01-08 05:56 UTC, flashhu commented
@lsvih @PassionPenguin @k8scat 掘金文章发布地址：https://juejin.cn/post/6915263201882046472

2021-01-08 08:57 UTC, PassionPenguin commented
非常感谢译者大大的翻译～