如何成为谷歌开发专家（GDE）—实用指南
xitu/gold-miner pull request #7845
Opened 2021-01-09 07:55 UTC by Usualminds

译文翻译完成，resolve #7802

2021-01-09 07:55 UTC, Usualminds commented
@lsvih 翻译完成

2021-01-09 08:24 UTC, PassionPenguin requested changes
文章看起来是机器翻译的，遣词造句有着比较大的问题，虽说不影响阅读，但还是建议修改

2021-01-09 08:24 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +成为[谷歌开发专家](https://developers.google.com/programs/experts/)  (GDE) 并不是我当初想要实现的目标，而是 **它** 找到了我。以下指南是为那些从零开始的开发人员准备的，他们希望有一天能加入这个只接受邀请，而且会改变职业生涯的项目👇
1. > 而是 **它** 邀请了我 会不会更好
2. > 以下指南是为那些从零开始的开发人员，那些希望有一天能加入这个只接受邀请且会改变职业生涯的项目而准备的

2021-01-09 08:24 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +在成为 GDE 之前，你需要获得谷歌员工或谷歌合作伙伴的提名，因为他们已经注意到你在当前领域的卓越贡献。
> 你需要获得注意到你在当前领域的卓越贡献的谷歌员工或谷歌合作伙伴的提名。

2021-01-09 08:24 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +> 对于使用 Angular 和 Firebase 构建应用程序的开发人员而言，你是最佳的技术顾问，YouTuber，内容创建者和高级资源。
顿号？或许会更好

2021-01-09 08:24 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +如果你擅长于此，你脱颖而出的机会就会大得多。相对于谷歌 Pay、Assistant、Tensorflow 等小众产品领域，Web 和Android 等大型产品领域更难脱颖而出。
1. > 如果...那么...
2. > 而相较于...
3. > 【空格】Android

2021-01-09 08:24 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +但是演讲只占总听众的一小部分。你仍然可以成为 GDE，不用大规模的演讲。**启动 YouTube 频道，博客，书籍，课程，Twitch 流或播客** - 做到最好，力争在你所在的领域中做到卓越。它还有助于在已经具有影响力的领域发送邀请帖相关的内容，例如为什么不在 [fireship.io上发表帖子](https://fireship.io/contributors/) 😎。
启动..频道 => 开通..频道

2021-01-09 08:24 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +拥有一个跟踪记录平台 [开源贡献](https://github.com/codediodeio) 也是有帮助的。帮助 **维护一个 Github 上的开源项目** ，它可能和你所做的产品或者你的代码语言相关。 一个 **出色的 Stack Overflow 个人主页** 也是一个强有力的资源。
> 【你也可以】帮助维护一个，这里注意空格以及上下文语言流畅
> 【如果你拥有】一个出色的

2021-01-09 08:24 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +联系其他 GDEs 或谷歌开发团队的领导。告诉人们你从第一步开始的任务和你正在做很酷的事情。不要担心征求他人的意见，适当表达你对成为 GDE 的兴趣。
> 【你可以】联系，告诉【他们】你【】第一部的任务

2021-01-09 08:24 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +我的第一次面试是在和一个在凤凰城的 GDE 共进午餐时进行的。我们聊了聊科技，吃了墨西哥煎玉米卷——很有趣。我的第二次面试是通过视频聊天与来自 Firebase 的开发者进行的。同样，这也是一个轻松有趣的对话。
【空格】 —— 

是与 Firebase 的开发者使用视频聊天进行的

2021-01-09 08:24 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +欢迎加入我们的俱乐部🥂，GDE 课程的福利取决于你所看重的东西。你可以是一个被动的参与者，也可以是一个重度的参与者。
> 我们的团队
> 及其热衷的参与者

2021-01-09 08:24 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +在你的个人简介中使用 GDE 标记。作为一个内容创作者，它是非常有价值的，因为它表明了你的资质。把它写在你的简历上，这样你就能脱颖而出，获取更高的薪水。
作为一个内容创作者，你可以在你的个人简介中使用 GDE 标记，而这是非常有意义有价值的，因为它证明了你的能力。你也可以把它写在你的简历上，这样你就能脱颖而出，获取更高的薪水。

2021-01-09 08:24 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +#### 连接
访问权限？连接这个词翻译很奇怪

2021-01-09 08:24 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +谷歌每年都会举办一个针对 GDE 免费的峰会，这是一个与其他专家交流的好机会。去年在山景城和多伦多有峰会，但前年是在波兰。你可能还会得到到谷歌 I/O 的门票 (不保证)。
不保证很突兀

而前年是在

2021-01-09 08:24 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +也许没有人谈论的最大的好处是 **职业认证**。程序员患有 Impostor 综合症，虽然无法治愈，但被谷歌授予骑士称号是有帮助的。至少，你应该不会觉得有那么大的压力去证明自己是一名开发人员。
授予职业称号

2021-01-09 08:24 UTC, PassionPenguin commented
申请校对 @lsvih

2021-01-09 08:27 UTC, PassionPenguin commented
另外标题的破折号～是不是也要加个空格（

2021-01-09 09:31 UTC, Usualminds commented
> 文章看起来是机器翻译的，遣词造句有着比较大的问题，虽说不影响阅读，但还是建议修改

@PassionPenguin 感谢校对，这是我花了一上午的时间翻译的，文章不是机器翻译

2021-01-09 09:36 UTC, PassionPenguin commented
> > 文章看起来是机器翻译的，遣词造句有着比较大的问题，虽说不影响阅读，但还是建议修改
> 
> @PassionPenguin 感谢校对，这是我花了一上午的时间翻译的，文章不是机器翻译

幸苦了，早已看到您的commits，知道您不是随意翻译的。不过建议译者您以后多检查检查读一读嗷：）！～
-by 苏苏的 [PassionPenguin](https://github.com/PassionPenguin)

2021-01-09 09:44 UTC, Usualminds commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +成为[谷歌开发专家](https://developers.google.com/programs/experts/)  (GDE) 并不是我当初想要实现的目标，而是 **它** 找到了我。以下指南是为那些从零开始的开发人员准备的，他们希望有一天能加入这个只接受邀请，而且会改变职业生涯的项目👇
1. 这里不做修改，这里 **它** 指的是成为 GDE 这个目标而非 GDE 组织，可以理解为作者一开始没有成为 GDE 这个目标，是在逐渐的从事自己喜欢的事情中 **找到了** 这个目标
2.这个语序有点问题，两个 **那些**

2021-01-09 09:49 UTC, Usualminds commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +在成为 GDE 之前，你需要获得谷歌员工或谷歌合作伙伴的提名，因为他们已经注意到你在当前领域的卓越贡献。
> > 你需要获得注意到你在当前领域的卓越贡献的谷歌员工或谷歌合作伙伴的提名。

这里语序似乎不通顺，**需要获得注意到**

2021-01-09 09:51 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +成为[谷歌开发专家](https://developers.google.com/programs/experts/)  (GDE) 并不是我当初想要实现的目标，而是 **它** 找到了我。以下指南是为那些从零开始的开发人员准备的，他们希望有一天能加入这个只接受邀请，而且会改变职业生涯的项目👇
看后文吧，GDE邀请了作者，然后视频中，作者说 i dont expect  and i dont have any conn to Google

那些，那些，一个条件短语一个条件从句两个条件叠加，没有毛病嗷

2021-01-09 09:54 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +在成为 GDE 之前，你需要获得谷歌员工或谷歌合作伙伴的提名，因为他们已经注意到你在当前领域的卓越贡献。
你需要获得【（注意到你在当前领域的卓越贡献的）谷歌员工或谷歌合作伙伴】的提名

这个句子有点点繁琐（

> 你需要获得谷歌员工或谷歌合作伙伴的提名，而他们正是注意到你在当前领域的卓越贡献而提名了你。
？？会不会感觉有点长啊如果拆分定语

2021-01-09 10:00 UTC, Usualminds commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +在你的个人简介中使用 GDE 标记。作为一个内容创作者，它是非常有价值的，因为它表明了你的资质。把它写在你的简历上，这样你就能脱颖而出，获取更高的薪水。
这里暂不修改，和原翻译比较，没有更加流畅

2021-01-09 10:03 UTC, Usualminds commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +#### 连接
之所以翻译为 **连接** ，是因为参考上下文，这里想表明的是通过峰会，把 GDE 们组织连接了起来，让他们可以交流
翻译为 访问权限 更加不合适，没有上下文语境

2021-01-09 10:05 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +在你的个人简介中使用 GDE 标记。作为一个内容创作者，它是非常有价值的，因为它表明了你的资质。把它写在你的简历上，这样你就能脱颖而出，获取更高的薪水。
呐，在你的个人简介中使用 GDE 标记【。】作为一个内容创作者，【它】是非常有价值的，因为它表明了你的资质。把它写在你的简历上，这样你就能脱颖而出，获取更高的薪水。

这里建议前面半句改一改嗷，后面的没必要改

而且这里也只是改了一下语序：）您的原来的翻译的内容没有任何问题的嗷

> 作为一个内容创作者，你可以在你的个人简介中使用 GDE 标记，而这是非常有意义的，因为它证明了你的能力。

2021-01-09 10:05 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +在你的个人简介中使用 GDE 标记。作为一个内容创作者，它是非常有价值的，因为它表明了你的资质。把它写在你的简历上，这样你就能脱颖而出，获取更高的薪水。
表明了/证明了，可以改为 【可以证明】

2021-01-09 10:06 UTC, Usualminds commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +谷歌每年都会举办一个针对 GDE 免费的峰会，这是一个与其他专家交流的好机会。去年在山景城和多伦多有峰会，但前年是在波兰。你可能还会得到到谷歌 I/O 的门票 (不保证)。
- 这里遵循原文，扩充一下语义：不保证可以获取该门票
- 第二点不修改

2021-01-09 10:07 UTC, Usualminds commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +也许没有人谈论的最大的好处是 **职业认证**。程序员患有 Impostor 综合症，虽然无法治愈，但被谷歌授予骑士称号是有帮助的。至少，你应该不会觉得有那么大的压力去证明自己是一名开发人员。
这里保留原翻译，加上双引号

2021-01-09 10:11 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +谷歌每年都会举办一个针对 GDE 免费的峰会，这是一个与其他专家交流的好机会。去年在山景城和多伦多有峰会，但前年是在波兰。你可能还会得到到谷歌 I/O 的门票 (不保证)。
赞同：）

2021-01-09 10:12 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +#### 连接
that may provide access to private alpha programs for your product specialty.

2021-01-09 10:12 UTC, PassionPenguin commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +也许没有人谈论的最大的好处是 **职业认证**。程序员患有 Impostor 综合症，虽然无法治愈，但被谷歌授予骑士称号是有帮助的。至少，你应该不会觉得有那么大的压力去证明自己是一名开发人员。
也不错！

2021-01-09 10:20 UTC, Usualminds commented
@lsvih @PassionPenguin 校对意见已合入

2021-01-12 14:28 UTC, zenblo commented
@lsvih 校对认领

2021-01-12 14:35 UTC, PassionPenguin commented
> @lsvih @PassionPenguin 校对意见已合入

谢谢译者大大的merge：）

- by 苏苏的 [PassionPenguin](https://github.com/PassionPenguin)

2021-01-13 01:22 UTC, lsvih commented
@zenblo 好的

2021-01-16 08:36 UTC, zenblo commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +成为[谷歌开发专家](https://developers.google.com/programs/experts/)  (GDE) 并不是我当初想要实现的目标，而是 **它** 找到了我。以下指南是为那些从零开始，希望有一天能加入这个只接受邀请，而且会改变职业生涯的项目的开发人员准备的👇
而是 **它** 找到了我
=> 而是**它**找到了我

2021-01-16 08:36 UTC, zenblo commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +你 **不需要** 是一个极有天赋的黑客。
你 **不需要** 是一个极有天赋的黑客
=>你**不需要**是一个极有天赋的黑客
以下还有几处类似多余空格

2021-01-16 08:36 UTC, zenblo commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +尽管以上这些都是可以帮助你成为 GDE 的合理目标，但它们 **不是** 正确但目标。表面的这些数字也许对你有所帮助，但这并非长远之道。
但它们 **不是** 正确的指引目标

2021-01-16 08:36 UTC, zenblo commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +我遇到但每一个 GDE 都是热衷于创作技术内容并与社区分享，他们 **专注于工艺**。
我遇到但每一个 GDE 都是热衷于创作技术内容并与社区分享，他们 **专注于工艺**。
=>我遇到的每一个谷歌开发专家都是热衷于创作技术内容并与社区分享，他们**专注于技术探究**。

2021-01-16 08:36 UTC, zenblo commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +设立一个明确的任务。你热衷的事情。越专业化越好。我打算成为……
你热衷的事情。越专业化越好。我打算成为……
=>你热衷的事情，越专业化越好。例如我打算成为......

2021-01-16 08:36 UTC, zenblo commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +> 对于使用 Angular 和 Firebase 构建应用程序的开发人员而言，你是最佳的技术顾问、YouTuber、内容创建者和高级资源。
你是最佳的技术顾问、YouTuber、内容创建者和高级资源
=>你是优秀的技术顾问、YouTuber、内容创建者和高级资源提供者

2021-01-16 08:36 UTC, zenblo commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +但是演讲只占总听众的一小部分。你仍然可以成为 GDE，不用大规模的演讲。**开通 YouTube 频道，博客，书籍，课程，Twitch 流或播客** - 做到最好，力争在你所在的领域中做到卓越。它还有助于在已经具有影响力的领域发送邀请帖相关的内容，例如为什么不在 [fireship.io上发表帖子](https://fireship.io/contributors/) 😎。
例如为什么不在 [fireship.io上发表帖子]
=>例如可以尝试在 [fireship.io 上发表帖子]

2021-01-16 08:36 UTC, zenblo commented on article/2020/how-to-become-a-google-developer-expert-gde-a-practical-guide.md
> +在这一点上，Impostor 综合症将达到临界水平，因为你正在准备一次千载难逢的高压工作面试——你想太多了！如果你能走到这一步，做你自己就好。他们已经对你感兴趣了，不需要在白板上写问题或脑筋急转弯。
Impostor 综合症将达到临界水平
=>冒充者综合症（Impostor syndrome）将达到临界水平

2021-01-16 08:38 UTC, zenblo commented
@Usualminds 提了一些格式问题，文章还是有 **  多出空格问题，需要做小调整
@lsvih 校对完成

2021-01-17 08:02 UTC, Usualminds commented
@zenblo 感谢校对，已合入
@lsvih 所有校对意见已合入

2021-01-17 08:08 UTC, lsvih approved these changes

2021-01-17 08:09 UTC, merged

2021-01-17 08:09 UTC, lsvih commented
@Usualminds  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-01-17 08:20 UTC, Usualminds commented
@lsvih  https://juejin.cn/post/6918640631317266439/

2021-01-17 08:25 UTC, lsvih commented
收到~