Swiftui cheat sheet
xitu/gold-miner pull request #7863
Opened 2021-01-12 08:31 UTC by LoneyIsError

译文翻译完成，resolve #id

2021-01-17 12:00 UTC, zhuzilin commented
@lsvih 校对认领～

2021-01-17 12:14 UTC, lsvih commented
@zhuzilin 好的~

2021-01-19 14:27 UTC, zhuzilin reviewed
@lsvih @LoneyIsError 感觉文章里面有一些机翻直译的内容，我标出了一些....以及一些语序上可能不用完全遵从英文语法，可以更改让他们更适合中文阅读...

2021-01-19 14:27 UTC, zhuzilin commented on article/2020/swiftui-cheat-sheet.md
> +本文试图通过简单、可重复的术语来定义每个包装器合适的使用时机。在这里我可能有点过于规定性，但我从这些规则中已经得到了一些不错的收获。 此外，过度规范是一个由来已久的程序员编写博客的传统，因此尽管偶尔会令人讨厌，但我的处境还是不错的。
可重复的 => 可重复性的
得到了一些不错的收获 => 有了不错的收获
收获。_此外 => 收获。此外
但我的处境还是不错的 => 相信我的总结还是会有所帮助的 （这里应该是指本文的"处境"不错吧，直译感觉很难看懂）

2021-01-19 14:27 UTC, zhuzilin commented on article/2020/swiftui-cheat-sheet.md
> +2. 当你的视图需要更改祖先视图所拥有的属性或祖先引用的可观察对象所拥有的属性时，请使用 `@Binding` 。
祖先引用 => 祖先视图引用

2021-01-19 14:27 UTC, zhuzilin commented on article/2020/swiftui-cheat-sheet.md
> +4. 当通过视图所有祖先的初始化器传递一个可观察对象太麻烦时，请使用 `@EnvironmentObject`。
这句不通...应该是说一个对象需要从上一直传下来吧

2021-01-19 14:27 UTC, zhuzilin commented on article/2020/swiftui-cheat-sheet.md
> +5. 当视图所依赖的类型不符合 observeObject 时，请使用 `@Environment`。
observeObject => ObserveObject

2021-01-19 14:27 UTC, zhuzilin commented on article/2020/swiftui-cheat-sheet.md
> +### …当需要向子视图提供对其某个属性进行读/写访问。
向子视图提供对其某个属性进行读/写访问。 => 让子视图对某个属性进行读/写访问。

2021-01-19 14:27 UTC, zhuzilin commented on article/2020/swiftui-cheat-sheet.md
> +视图通过传递 @State-wrapped 属性的 `projectedValue`来实现这一点，该属性是该值的绑定  [1]。一个很好的例子是 SwiftUI.Alert。视图负责通过改变一些 @State 的值来显示 Alert 弹框，比如一个 `isPresentingAlert` 的布尔属性。但是视图不能隐藏 Alert 弹框本身，因为 Alert 弹框并不知道它所弹出的视图。通过绑定解
__[1] => _[1]
"视图负责通过改变一些 @State 的值来显示 Alert 弹框" 不通
“通过绑定解决了这个难题。通过使用编译器” 过于直译
“弹框的自动解散。” 建议修改

2021-01-19 14:27 UTC, zhuzilin commented on article/2020/swiftui-cheat-sheet.md
> +就像上述 Alert 弹框的反例一样。如果你的视图类似于 Alert 弹框，它依赖于祖先所拥有的值，并且关键的是，需要对该值的可变访问，那么视图需要一个 @Binding 到该值。
“就像上述 Alert 弹框的反例一样” 和原文不符

2021-01-19 14:27 UTC, zhuzilin commented on article/2020/swiftui-cheat-sheet.md
> +你的视图需要具有对该可观察对象的某些成员的读/写访问权限，但是你的视图没有（也不应）具有对该可观察对象的访问权限。然后，视图将为该值定义一个@Binding 属性，该属性将在视图初始化时由其祖先视图提供。这方面的一个很好的例子是任何可重用的输入视图，如选择器或文本框。 一个文本框需要能够对另一个对象上的一些字符串属性有读/写访问权，但是文本框不应该与那个特定的对象有紧密耦合。相反，文本框的 @B
但是你的视图没有 => 但是它
是任何可重用的输入视图 => 可复用的输入视图们
有紧密耦合 => 紧密耦合

2021-01-19 14:27 UTC, zhuzilin commented on article/2020/swiftui-cheat-sheet.md
> +假设你有一个视图，用来展示从网络服务获取的项目列表。SwiftUI 的视图是暂时的、可丢弃的值类型。它们很适合展示内容，但不适合进行网络服务请求。此外，你不应该将用户界面代码与其他任务混在一起，因为那样会违反[单一职责原则](https://en.wikipedia.org/wiki/Single-responsibility_principle)。取而代之的是，你可能会将这些责任转移给另一个对
暂时的 => 临时的

2021-01-19 14:27 UTC, zhuzilin commented on article/2020/swiftui-cheat-sheet.md
> +让我们回到上面 @ObservedObject 部分的第二个示例，其中需要一个可观察对象来代表你的视图执行某些任务，但是视图无法自己初始化该对象。但是现在让我们假设你的视图不是根视图，而是深深地嵌套在许多祖先视图中的后代视图。如果所有祖先视图都不需要该被观察对象，那么要求视图链中的每个视图都将被观察对象包含在它们的构造器参数中，只为了让一个后代视图能够访问它，这将非常尴尬的。相反，你可以通过将其
这将非常尴尬的 => 是非常尴尬的

2021-01-20 08:58 UTC, LoneyIsError commented on article/2020/swiftui-cheat-sheet.md
> +就像上述 Alert 弹框的反例一样。如果你的视图类似于 Alert 弹框，它依赖于祖先所拥有的值，并且关键的是，需要对该值的可变访问，那么视图需要一个 @Binding 到该值。
我觉得作者可能想的意思是，生成一个供给子视图使用的包装属性，并与子视图属性同时是有

2021-01-20 09:02 UTC, LoneyIsError commented
@zhuzilin 麻烦看一下。之前确实翻得有点着急了

2021-01-21 12:46 UTC, PassionPenguin requested changes
@lsvih 认领校对

怎么说吧，建议康康翻译文章再理顺一下下：）

幸苦译者了

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +SwiftUI 引入了一系列新的属性包装器，你的代码可以通过它们来架起程序状态和视图之间的桥梁:
连起来吧：）

> SwiftUI 引入了一系列新的属性包装器使得你的代码可以通过它们来架起程序状态和视图之间的桥梁:

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +这只是其中一部分。还有其他用于 Core Data 获取请求和用于识别手势的属性包装器。但本文与其他包装器无关。与上面的包装器不同，`@FetchRequest` 和`@GestureState` 的用例是明确的，然而，何时使用 `@State` 还是 `@Binding`，或 `@ObservedObject` 还是 `@EnvironmentObject` ，等等，会令人非常困惑。
> 但本文这些别的包装器无关

然而，什么时候使用 `@State` 什么时候使用 `@Binding`，或什么时候使用 `@ObservedObject` 什么时候使用 `@EnvironmentObject` 这些，着实令人非常困惑。

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +下面的所有代码示例代码都可以在 [GitHub repo](https://github.com/jaredsinclair/swiftui-property-wrappers) 中找到。
GitHub repo => GitHub 仓库

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +> **注意：本文是使用 Swift 5 和 iOS 13 编写的。**
注意：本文是针对 Swift 5 和 iOS 13 编写的。

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +2. 当你的视图需要更改祖先视图所拥有的属性或祖先视图所引用的可观察对象所拥有的属性时，请使用 `@Binding` 。
祖先视图...喵喵喵

虽说想不到能够怎么改但感觉很喜感

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +### …当需要对自己的一个属性进行读/写访问以供私有使用时。
当需要 => 它需要

让上下文更连续

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +就像是是 UIButton 上的 `isHighlighted` 属性。其他对象不需要知道按钮什么时候高亮显示，也不需要对该属性进行赋值操作。如果你要在 SwiftUI 中从头开始实现一个按钮，那么你的 `isHighlighted` 属性将是 @State 包装器的一个很好的候选。
是是

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
>      /// its own properties for private use
翻译下吧

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +### …当需要让子视图可以对某个属性进行读/写访问时。
同上

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +视图通过传递 @State-wrapped 属性的 `projectedValue` 来实现这一点，该属性是该值的绑定 [1]。一个很好的例子是 SwiftUI.Alert。视图负责通过改变一些 @State 修饰的属性的值来显示 Alert 弹框，比如一个 `isPresentingAlert` 的布尔属性。但是视图不能隐藏 Alert 弹框本身，因为 Alert 弹框并不知道它所弹出的视图。
可食用<sup>[1]</sup>以支持上标

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +视图通过传递 @State-wrapped 属性的 `projectedValue` 来实现这一点，该属性是该值的绑定 [1]。一个很好的例子是 SwiftUI.Alert。视图负责通过改变一些 @State 修饰的属性的值来显示 Alert 弹框，比如一个 `isPresentingAlert` 的布尔属性。但是视图不能隐藏 Alert 弹框本身，因为 Alert 弹框并不知道它所弹出的视图。
iftUI.Alert。视图负责通过

这里的视图负责通过和上下文不顺畅嗷

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +视图通过传递 @State-wrapped 属性的 `projectedValue` 来实现这一点，该属性是该值的绑定 [1]。一个很好的例子是 SwiftUI.Alert。视图负责通过改变一些 @State 修饰的属性的值来显示 Alert 弹框，比如一个 `isPresentingAlert` 的布尔属性。但是视图不能隐藏 Alert 弹框本身，因为 Alert 弹框并不知道它所弹出的视图。
通过使用 `@State` 属性解决了这个难题。

> 通过使用 `@State` 属性能解决这个难题。

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +3. **你的**视图是 #2 的后代。
总感觉好好笑

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +你的视图需要具有对该可观察对象的某些成员的读/写访问权限，但是它没（也不应）具有对该可观察对象的访问权限。然后，视图将为该值定义一个@Binding 属性，该属性将在视图初始化时由其祖先视图提供。这方面的一个很好的例子是任何可复用的输入视图们，如选择器或文本框。 一个文本框需要能够对另一个对象上的一些字符串属性有读/写访问权，但是文本框不应该与那个特定的对象紧密耦合。相反，文本框的 @Bindi
@Bingding记得空格

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +### …将观察到的对象传递给视图所有祖先的所有构造器，这样太麻烦了
将观察到的对象传递给视图所有祖先的所有构造器太过麻烦

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +让我们回到上面 @ObservedObject 部分的第二个示例，其中需要一个可观察对象来代表你的视图执行某些任务，但是视图无法自己初始化该对象。但是现在让我们假设你的视图不是根视图，而是深深地嵌套在许多祖先视图中的后代视图。如果所有祖先视图都不需要该被观察对象，那么要求视图链中的每个视图都将被观察对象包含在它们的构造器参数中，只为了让某一个后代视图能够访问它，这将非常尴尬。相反，你可以通过将其
SwiftUI空格多了

2021-01-21 12:46 UTC, PassionPenguin commented on article/2020/swiftui-cheat-sheet.md
> +#### 参考
这里参考翻译规范，上标建议给原文锚点这里提供定向嗷：）

2021-01-21 15:44 UTC, lsvih commented
@PassionPenguin 感谢校对！

2021-01-22 02:20 UTC, LoneyIsError commented on article/2020/swiftui-cheat-sheet.md
> +2. 当你的视图需要更改祖先视图所拥有的属性或祖先视图所引用的可观察对象所拥有的属性时，请使用 `@Binding` 。
我全部改成父视图吧，或者改成根视图。父视图局限性，根视图有点太，恩。。。

2021-01-22 02:22 UTC, LoneyIsError commented on article/2020/swiftui-cheat-sheet.md
> +> **注意：本文是使用 Swift 5 和 iOS 13 编写的。**
我改的更好理解吧。本文是基于 iOS 13 并使用 Swift 5 编写的。基于某版本使用某语言

2021-01-22 04:03 UTC, lsvih approved these changes

2021-01-22 04:04 UTC, merged

2021-01-22 04:04 UTC, lsvih commented
@LoneyIsError  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-01-23 09:16 UTC, LoneyIsError commented
https://juejin.cn/post/6920881116043968520/

2021-01-25 08:28 UTC, lsvih commented
收到