Translation/security best practices for nodejs
xitu/gold-miner pull request #7870
Opened 2021-01-13 15:50 UTC by Ashira97

译文翻译完成，resolve #7762

2021-01-13 17:38 UTC, PassionPenguin requested changes
翻译的不少语句不通顺，还有较多的句子没有揪出来，麻烦作者再次阅读修正一下，幸苦了～ 

@lsvih 校对申请

- by 苏苏的 [PassionPenguin](https://github.com/PassionPenguin)

2021-01-13 17:38 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +除去那些我们大部分人都不为之工作的娱乐巨头们的娱乐圈，在系统上实现安全措施不仅重要，而且被严重低估，甚至被许多开发者遗忘。
这个句子很奇怪。

2021-01-13 17:38 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +它的实现难以捉摸，取决于项目的业务场景或者是你的公司决定如何制定标准用法。
（看下文

2021-01-13 17:38 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +## （旧）XML外部实体注入
空格

2021-01-13 17:38 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +换句话说，当您的应用中有受限访问的部分，比如说管理员面板这种普通用户无权访问的页面，这样的应用中就会有访问漏洞。
这样的应用 => 您的应用

2021-01-14 01:26 UTC, lsvih commented
@PassionPenguin 感谢校对

2021-01-14 02:14 UTC, Ashira97 commented
@PassionPenguin 感谢校对~按照您的意见进行了修改~欢迎沟通~欢迎多提意见~

2021-01-14 10:48 UTC, PassionPenguin commented
> @PassionPenguin 感谢校对~ 按照您的意见进行了修改~ 欢迎沟通~ 欢迎多提意见~

谢谢译者大大～

2021-01-15 03:37 UTC, samyu2000 commented
@lsvih 校对认领

2021-01-15 03:45 UTC, lsvih commented
@samyu2000 欢迎校对！

2021-01-15 11:20 UTC, PassionPenguin requested changes

2021-01-15 11:20 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +我们大部分人都不为之工作的巨头们的光怪陆离的世界之外，在系统上实现安全措施不仅重要，而且被严重低估，甚至被许多开发者遗忘。
段首可以加 在，让这个状语更加明显是状语，不会让读者误认为世界为主语

实现措施？搭配不太妥当嗷

落实相关的安全措施

而且被严重低估，这里翻译怪怪的

可改为，但是人们往往忽略了这些。

> 在我们大部分人都并不为之工作的巨头们的光怪陆离的世界之外，在系统上落实相关的安全措施很是重要，但是人们却往往忘却了这些，甚至连许多开发者也遗忘了这件事情。

2021-01-15 11:20 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +这并不是危言耸听。如果您的工作是开源的，那么在 GitHub 的保护机制之下，您会看到一些有缺陷的依赖的[提示](https://docs.github.com/en/github/managing-security-vulnerabilities/about-alerts-for-vulnerable-dependencies)。GitHub 代码平台变得越来越擅长-也越来越令人担心-在许多不
译者大大记得破折前后加空格：）

> GitHub 代码平台变得越来越擅长 —— 也越来越令人担心 —— 在许多不同语言的数千个依赖库中进行漏洞的探测。

2021-01-15 11:20 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +有很多安全工具或者平台可以帮助开发者解决代码和应用程序中的漏洞。今天，对于中小企业来说，这样的工具甚至整个平台变得越来越触手可及。
这句话翻译得有些奇怪

这样的【工具】甚至整个【平台】【变得】越来越【触手可及】

另外afford的安全工具这个定语被前提但是被句号割裂了，读起来有点怪

> 现在有很多安全工具或者平台可以帮助开发者解决代码和应用程序中的漏洞，他们对于中小企业来说让安全措施的实施变得越来越可操作。

2021-01-15 11:20 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +然而，无论是否使用这些安全平台，帮助你理解并意识到应用可能遭受的安全威胁并且通过这些简单但强大的最佳实践来消除这些威胁是这篇文章的主要目的。
然而可以翻译为 不管怎样，无论你是否使用这些安全平台，...

2021-01-15 11:20 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +作为参考手册，[OWASP](https://owasp.org/) (**开放网络应用安全项目**)会通过其中的[前十个 Web 应用面临的最关键的安全威胁](https://owasp.org/www-project-top-ten/)来引导我们。这十大安全威胁来自于它的广大使用者经分析之后得出的共识。让我们以 Node 项目为例来看一看这些安全威胁。
引导我们 缺宾语吧

引导我们防范这些威胁

2021-01-15 11:20 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +Node 应用中像下面这样设置 HSTS ：
HSTS后面不必要加空格吧？

2021-01-15 11:20 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +您可以通过不同的定义仔细调试配置项，比如，可以配置是否包含子域名：
仔细调试 => 对配置项做出微调

2021-01-15 11:20 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
>  <script>alert(Uh la la, it's me! XSS!!)</script>
<img width="545" alt="Screen Shot 2021-01-15 at 7 18 00 PM" src="https://user-images.githubusercontent.com/41184947/104718791-694f0880-5766-11eb-8c07-9231e3adc411.png">

看半天没看懂这句代码是啥（

跪求解释（

2021-01-15 11:20 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +这份清单是为开发者，尤其是新人开发者准备的指南，让开发者能够更好的理解网络中的安全威胁以什么样的形式存在，以及它们如何能够影响应用，即使你不相信有人尝试攻破你的应用。
这份清单是指南，搭配嗷

让..这个定语翻译有点怪，或许可以改为 目的是让

即使这里前面可以加破折号表转折，更好连接上下文

2021-01-15 11:21 UTC, PassionPenguin commented
麻烦译者大大康康校对意见，上次半夜校对没校对完困死了。

谢谢啦～

- by 苏苏的 [PassionPenguin](https://github.com/PassionPenguin)

2021-01-15 11:33 UTC, Ashira97 commented on article/2020/security-best-practices-for-nodejs.md
> +我们大部分人都不为之工作的巨头们的光怪陆离的世界之外，在系统上实现安全措施不仅重要，而且被严重低估，甚至被许多开发者遗忘。
这样翻译可好～
在我们大部分人都并不为之工作的巨头们的光怪陆离的世界之外，在系统上采取相关的安全措施非常重要，但是这种重要性往往被忽视，甚至有些开发者都会忘记采取这些安全措施。

2021-01-15 11:36 UTC, Ashira97 commented on article/2020/security-best-practices-for-nodejs.md
> +有很多安全工具或者平台可以帮助开发者解决代码和应用程序中的漏洞。今天，对于中小企业来说，这样的工具甚至整个平台变得越来越触手可及。
在您的修改上稍作改动～您看可以不？
现在有很多安全工具或者平台可以帮助开发者解决代码和应用程序中的漏洞，他们让中小企业更容易在系统上采取安全措施。

2021-01-15 11:40 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +有很多安全工具或者平台可以帮助开发者解决代码和应用程序中的漏洞。今天，对于中小企业来说，这样的工具甚至整个平台变得越来越触手可及。
译者大大的这个修改太棒了～！

2021-01-15 11:40 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +我们大部分人都不为之工作的巨头们的光怪陆离的世界之外，在系统上实现安全措施不仅重要，而且被严重低估，甚至被许多开发者遗忘。
（总感觉两个在字很别扭，但又想不到什么办法...）

诶或许可以翻译成 

> 在我们大部分人都并不为之工作的巨头们的光怪陆离的世界之外的系统上采取相关的安全措施是非常重要的，但是这种重要性往往被忽视，甚至有些开发者都会忘记采取这些安全措施。

2021-01-15 11:42 UTC, Ashira97 commented on article/2020/security-best-practices-for-nodejs.md
>  <script>alert(Uh la la, it's me! XSS!!)</script>
![image](https://https://github.com/Ashira97/aboutV8/blob/master/show.png)

试试能看到不~

2021-01-15 11:43 UTC, Ashira97 commented on article/2020/security-best-practices-for-nodejs.md
> +这份清单是为开发者，尤其是新人开发者准备的指南，让开发者能够更好的理解网络中的安全威胁以什么样的形式存在，以及它们如何能够影响应用，即使你不相信有人尝试攻破你的应用。
这份清单是为开发者，尤其是新人开发者准备的入门读物，目的是让开发者能够更好的理解网络中的安全威胁以什么样的形式存在，以及它们如何能够影响应用－即使你不相信有人尝试攻破你的应用。

2021-01-15 11:44 UTC, Ashira97 commented
> 麻烦译者大大康康校对意见，上次半夜校对没校对完困死了。
> 
> 谢谢啦～
> 
> * by 苏苏的 [PassionPenguin](https://github.com/PassionPenguin)

2021-01-15 11:45 UTC, Ashira97 commented
不好意思我操作不慎关闭了...

2021-01-15 11:45 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
> +这份清单是为开发者，尤其是新人开发者准备的指南，让开发者能够更好的理解网络中的安全威胁以什么样的形式存在，以及它们如何能够影响应用，即使你不相信有人尝试攻破你的应用。
破折号是两段嗷 ——

2021-01-15 11:47 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
>  <script>alert(Uh la la, it's me! XSS!!)</script>
看不到诶...

2021-01-16 11:54 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
>  <script>alert(Uh la la, it's me! XSS!!)</script>
对啊，字符串不就应该加引号嘛
单独执行这个只会报错，而且这也不过是本地的代码嘛，怎么来的安全问题嗷

2021-01-16 14:23 UTC, samyu2000 reviewed
校对完成

2021-01-16 14:23 UTC, samyu2000 commented on article/2020/security-best-practices-for-nodejs.md
> +另一个例子是处理文件上传任务的时候。例如，如果您限制仅仅可以接收某些类型的文件，那么可以接收基于 XML 格式的文档，例如 DOCX 或者著名的 SVG 格式的图片，同样可以运行恶意代码。
如果您限制仅仅可以接收某些类型的文件 => 如果您只对接收的文件类型作了限制
那么可以接收基于 XML 格式的文档，例如 DOCX 或者著名的 SVG 格式的图片，同样可以运行恶意代码。 => 由于 DOCX 格式的文档或 SVG 格式的图片都是基于 XML 的，也可以被系统接收，因此也可以运行恶意代码

2021-01-16 14:23 UTC, samyu2000 commented on article/2020/security-best-practices-for-nodejs.md
> +阻止这种攻击最简单的方法就是禁用第三方库的解析特性。例如 [node-libxml](https://www.npmjs.com/package/node-libxml) 第三方库，就提供了一系列方法来确认文件类型定义来保护您的应用免于遭受这种攻击。
例如 [node-libxml](https://www.npmjs.com/package/node-libxml) 第三方库，就提供了一系列方法来确认文件类型定义来保护您的应用免于遭受这种攻击。=> 例如 [node-libxml](https://www.npmjs.com/package/node-libxml) 就提供了一系列方法来验证文件类型，保护您的应用免受这种攻击。

2021-01-16 16:34 UTC, Ashira97 commented on article/2020/security-best-practices-for-nodejs.md
> +OWASP 认为身份认证很关键。像 [OAuth](https://oauth.net/) 这样的标准（以第二版为准，[第三版](https://oauth.net/3/)正在筹备中）正在不断发展并尝试尽可能多地考虑网络世界中的不同情况。
好棒的翻译！

2021-01-17 07:45 UTC, lsvih commented on article/2020/security-best-practices-for-nodejs.md
>  > * 校对者：
增加校对者信息

2021-01-17 11:41 UTC, PassionPenguin submitted a review, later dismissed
感谢译者大大的幸苦翻译，记得添加校对者信息

2021-01-17 11:41 UTC, PassionPenguin commented on article/2020/security-best-practices-for-nodejs.md
>  > * 校对者：
这不是译者信息嘛

2021-01-17 11:57 UTC, Ashira97 commented on article/2020/security-best-practices-for-nodejs.md
> +有很多安全工具或者平台可以帮助开发者解决代码和应用程序中的漏洞。今天，对于中小企业来说，这样的工具甚至整个平台变得越来越触手可及。
已修改为：现在有很多安全工具或者平台可以帮助开发者解决代码和应用程序中的漏洞，他们让中小企业更容易在系统上采取安全措施。

2021-01-17 12:00 UTC, Ashira97 commented on article/2020/security-best-practices-for-nodejs.md
> +如果开发者没有对请求中携带的输入参数做校验，那么攻击者可以不仅仅只传一个整数 ID，还可以传一个能够获取敏感信息甚至删除它的 SQL 命令。（这里不是强调合理的备份策略的重要性）
您好~我理解“如果...”描述了前提，“如果...”之后应该描述可以发生的确定事实。这个时候似乎不太适合继续用假如~
BTW：您的其他修改真的太棒了！！！

2021-01-17 12:02 UTC, Ashira97 commented
> 感谢译者大大的幸苦翻译，记得添加校对者信息

2021-01-17 12:11 UTC, PassionPenguin approved these changes
幸苦啦～

2021-01-17 12:11 UTC, Ashira97 commented
翻译完成，感谢两位大大的校对 @samyu2000 @PassionPenguin 
@Glowin 请您检查啦~

2021-01-17 12:14 UTC, lsvih approved these changes

2021-01-17 12:15 UTC, merged

2021-01-17 12:15 UTC, lsvih commented
@Ashira97 已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-01-17 16:06 UTC, Ashira97 commented
您好~
&nbsp; &nbsp; &nbsp;译文已发布到掘金社区，链接如下：
&nbsp; &nbsp; &nbsp;https://juejin.cn/post/6918757099782537224/
祝好~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xitu/gold-miner"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月17日(星期天) 晚上8:15
收件人:&nbsp;"xitu/gold-miner"<gold-miner@noreply.github.com&gt;;
抄送:&nbsp;"是九月啊"<1403801822@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xitu/gold-miner] Node.js 安全编程的最佳实践 (#7870)





 
@Ashira97 已经 merge 啦~ 快快麻溜发布到掘金然后给我发下链接，方便及时添加积分哟。
 
掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个好用的插件。
 专栏地址：https://zhuanlan.zhihu.com/juejinfanyi
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



Best Regards.
Ashira

2021-01-17 16:15 UTC, PassionPenguin commented
maybe to fix?

> 猜猜当客户发送下面这段代码作为 id 参数会发生什么？
> <script>alert(Uh la la, it's me! XSS!!)</script> 
> 复制代码
> 现在这只是一段无关紧要的提示信息，但是我们都知道攻击者会在代码中注入更多的 JavaScript 代码。

总感觉这里怎么说吧，应该是原作者漏了双引号。看他的下一句话，【现在这只是一段无关紧要的提示信息】，即传参后执行的是提示。那应该还是一个正常的指令啊？那就应该加个双引号括起来做字符串。否则就是exception，不仅不能达到目的，反而还会被bugreport抓出来>->

2021-01-18 02:10 UTC, Ashira97 commented
@PassionPenguin 这段代码我试了一下 在html中直接拼接<script>alert(123)<script>是有弹框的 但是这样的话 看原文中的内容应该是说req.query.product参数被拼接到了html中 那应该对product参数进行xss才对 不知道为什么写的是对id参数注入:(