解构标志性的 Apple Watch Bubble UI
xitu/gold-miner pull request #7871
Opened 2021-01-13 16:45 UTC by NieZhuZhu

@lsvih 译文翻译完成，resolve #7820

2021-01-13 17:49 UTC, PassionPenguin requested changes
Marvelous Translation, AC, but have some minor suggestions:

- by 苏苏的 [PassionPenguin](https://github.com/PassionPenguin)

2021-01-13 17:49 UTC, PassionPenguin commented on article/2021/deconstructing-the-iconic-apple-watch-bubble-ui.md
> +当 2015 年推出第一款 [**Apple Watch**](https://en.wikipedia.org/wiki/Apple_Watch) 时，我对 [**WatchOS**](https://en.wikipedia.org/wiki/WatchOS) 的主屏幕设计感到震惊。它的布局不同于标准的网格式布局，而是提出了一种原始的视觉动态界面。
缺了主语，不太通顺，当 Apple 在 2015 年时

2021-01-13 17:49 UTC, PassionPenguin commented on article/2021/deconstructing-the-iconic-apple-watch-bubble-ui.md
> +当然，我喜欢使用 [**CSS Grid**](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) 以及 **[Flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Fle
以及以及，有点重复了

复杂性不适合模型，搭配不当

2021-01-13 17:49 UTC, PassionPenguin commented on article/2021/deconstructing-the-iconic-apple-watch-bubble-ui.md
> +![[Gifer]上的动画(https://gifer.com/en/XbVD)](https://cdn-images-1.medium.com/max/2000/1*23GQLo9bhAzjCWcbpzGuFA.gif)
空格

2021-01-13 17:49 UTC, PassionPenguin commented on article/2021/deconstructing-the-iconic-apple-watch-bubble-ui.md
> +边缘区域再次负责这**两个状态之间的过渡**。就像气泡的大小一样，气泡平移距离的多少由到中心区域的距离（范围(`边缘宽度`，0)到范围(`最大大小`，0)）插值（内插或称插值（英语：interpolation）是一种通过已知的、离散的数据点，在范围内推求新数据点的过程或方法。））得出。
interpolation 上文已经解释了嗷，这里可以删去啦

2021-01-13 17:49 UTC, PassionPenguin commented on article/2021/deconstructing-the-iconic-apple-watch-bubble-ui.md
>  translation_magnitude = distance_to_middle_region / fringe_width *     max_size
话说这里的空格..是否可以清理一下

2021-01-13 17:49 UTC, PassionPenguin commented on article/2021/deconstructing-the-iconic-apple-watch-bubble-ui.md
> +![取自 [**React-Bubble-UI**](https://bubbleui.blakesanie.com/) 的现场演示，精美的展示了 S&P 500 公司,](https://cdn-images-1.medium.com/max/2000/1*Hq0zEG3n8dsY-8hAhk-byQ.gif)
可改为 美国股市 500 强企业 

> The S&P 500, or simply the S&P, is a stock market index that measures the stock performance of 500 large companies listed on stock exchanges in the United States. It is one of the most commonly followed equity indices.

2021-01-15 11:04 UTC, PassionPenguin approved these changes

2021-01-15 11:04 UTC, PassionPenguin commented
感谢译者大大：）

2021-01-15 17:23 UTC, lsvih approved these changes

2021-01-15 17:23 UTC, lsvih commented
本文一位校对即可

2021-01-15 17:23 UTC, merged

2021-01-15 17:23 UTC, lsvih commented
@NieZhuZhu  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-01-20 00:20 UTC, NieZhuZhu commented
@lsvih https://juejin.cn/post/6919630087843217416/

2021-01-20 01:22 UTC, lsvih commented
收到