深入了解 JavaScript 模块
xitu/gold-miner pull request #7890
Opened 2021-01-18 08:28 UTC by regon-cao

译文翻译完成，resolve #7883

2021-01-18 12:54 UTC, PassionPenguin requested changes
呐呐呐呐：）幸苦译者了 🍻

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
>  ![Image by [HeungSoon](https://pixabay.com/users/heungsoon-4523762/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=3887440) from [Pixabay](https://pixabay.com/?utm_sou
图源：）

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +所有 JavaScript 开发人员都知道如何导入模块，如果你以前没有这么做过，那么你还没有通过基本的 “helloworld” 示例。模块是 JavaScript 生态系统的基石。
go past => past by or around

或许写 “看过” 更好？毕竟没通过helloworld例子的人也（

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +但是你知道 JavaScript 中有不同的模块系统吗？如果你一直使用 Node.js 开发, 你可能很熟练的使用 `require`，如果你一直和 React 打交道，你可能更多的是一个 `import` 开发者。事实上，它们都能完成任务，但是完成的方式并不相同。
> 你可能【能够】很熟练【地】使用 `require`【。】

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +如果你是一个 Node.js 开发者，你以前可能用过它。CommonJS 是 Node 采用的标准，采用 `require` 函数。
优化一下
> CommonJS 是 Node 采用的标准，而它使用的是 `require` 函数。

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +//你的模块.js
这个翻译就很魔幻了，文件名保留下吧

不过记得空格

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +//... 客户端 代码
客户端的代码

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +const { prop1, myFn } = require("./yourmodule.js");
上面与下面要一致嗷

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +你知道的，CommonJs 没有“默认”导出的概念，如果你像下面一样使用 `require`，那么 `exports` 上的所有属性都将被导出：
CommonJS

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +const myModule = require("yourmdoule.js");
记得文件名一致

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +结果，你将得到一个包含一系列属性和方法的对象（即导出的所有内容）。但是，ES6 定义了一种方法来区分默认导出的内容和单独导出的内容。所以你可以这样做：
【结果，】这个割裂的有点迷惑

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
>  //mymodule.js
记得文件名一致+空格

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +    //你的逻辑...
记得空格+【你的代码...】

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +这段代码告诉你正在导出 3 个东西：
> 这段代码会告诉你知道你当前正在导出 3 个东西：
原来的句子会有歧义，是计算机导出还是你导出

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +- 默认的导出了包含一个 `mainMethod` 方法的对象。
默认导出了 或 默认地导出了

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +这就是 ES6 和 CommonJS 提供的默认导出之间的主要区别。上面的代码不能直接转译成 CommonJS，因为它没有默认导出的概念。然而，诸如 Babel 之类的工具通过添加 “相互操作” 代码（比如 `__esModule` 属性）来解决这个问题。
加上个 会 字表做法，更通顺嗷

> 然而，诸如 Babel 【这样】的工具【会】通过添加 “相互操作” 代码（比如 `__esModule` 属性）来解决这个问题。

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +我知道这看起来有很多代码，但现在只关注最后两行。请注意，我们的 `mainMethod` 是默认导出，它位于名为 `default` 的新属性中。我们没有声明它，但是 Babel 添加它是为了增加与 CommonJS 的兼容性。还要注意 `dummyFunction` 方法不在 `default` 属性中，因为它是作为单独的实体导出的，实际上也是单独导入的。
【请注意，我们的 `mainMethod` 是默认导出】缺宾语

> mainthread 是 导出【的函数】

【我们没有声明它，但是 Babel 添加它是为了增加与 CommonJS 的兼容性】

> 这不是我们声明的，而是 Babel 出于维护与 CommonJS 的兼容性而添加的属性。

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +`__interopRequiredWilcard` 辅助函数只负责返回将要使用的具有正确形状的对象（换句话说，如果还没有 `default` 属性，它会添加该属性）。
正确形状？

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +一个主要区别是，`require` 在代码中的任何地方都能动态工作，但 `import` 不能。可以将 `require` 语句视为函数调用，因此，它需要运行才能执行。但是 `import` 语句是静态的，它在解析文件时执行。与 `require` 的工作方式相比，这是一个重大的性能改进。
动态工作 or 自动适应？感觉自适应更适合原文语境诶

【你】可以将 `require` 语句视为函数调用

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +但是，也有一个缺点：由于 `require` 在运行时工作，因此可以动态定义导入路由，例如：
由于，因此，句式杂糅

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +但是，也有一个缺点：由于 `require` 在运行时工作，因此可以动态定义导入路由，例如：
由于...，我们可以...
...，因此我们可以...

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +当然，假设 `pathToFile` 是一个字符串，这将毫无问题地工作。但是 `import` 不允许这么做，因为在解析它们时没有在运行时执行。
毫无问题地工作 => 正常地工作

> 但是 `import` 不允许这么做，因为并不是在运行时解析的它们。

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
>  ## AMD
AMD （异步模块定义）

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +它代表了[异步模块定义](https://en.wikipedia.org/wiki/Asynchronous_module_definition)，这是一种为前端项目加载模块的模式。过去，在浏览器中定义一系列代码依赖的唯一方法是添加一堆 `script` 标记，并确保它们的顺序正确。一旦文档及其所有资源被完全加载，你的代码就可以运行了。
这玩意竟然没有中文条目...

建议 follow 维基标题，后面加括号翻译

[Asynchronous Module Definition（异步模块定义）](https://en.wikipedia.org/wiki/Asynchronous_module_definition)

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +这确保了前端世界的两个主要问题：
确保 or 
<img width="516" alt="Screen Shot 2021-01-18 at 8 52 16 PM" src="https://user-images.githubusercontent.com/41184947/104917954-0f9d4700-59cf-11eb-8c75-760ac096e7e9.png">

建议完整翻译为【保证前端世界的两个主要问题不会发生】，确保问题搭配不当嗷

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
>  ## UMD
UMD（通用模块定义）

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +一个 UMD 的声明主要是由两个部分组成：
的 没什么必要写上去嗷

2021-01-18 12:54 UTC, PassionPenguin commented on article/2021/a-deep-dive-into-javascript-modules.md
> +我将在这里介绍的最后一个模块加载器是[SystemJS](https://github.com/systemjs/systemjs)。它提供了将 ES6 兼容的代码加载到运行时不兼容的另一种方法。换句话说，通过使用自定义的 `import` 函数，你可以直接加载 ES6 代码，而无需将其转换为任何内容。
空格

2021-01-19 08:54 UTC, regon-cao commented
@PassionPenguin 已修改，谢谢哟

2021-01-19 15:01 UTC, PassionPenguin commented
谢谢译者大大的修改：）

2021-01-19 17:08 UTC, Ashira97 commented
@Glowin 校对认领

2021-01-21 01:06 UTC, Ashira97 commented on article/2021/a-deep-dive-into-javascript-modules.md
> +但是你知道 JavaScript 中有不同的模块系统吗？如果你一直使用 Node.js 开发, 你能够很熟练地使用 `require`，如果你一直和 React 打交道，你可能更多的是一个 `import` 开发者。事实上，它们都能完成任务，但是完成的方式并不相同。
如果你一直使用 Node.js 开发, 你能够很熟练地使用 `require`，如果你一直和 React 打交道，你可能更多的是一个 `import` 开发者。
=>如果你一直使用 Node.js 开发, 那么你应该能够很熟练地使用 `require`导入模块，如果你一直开发 React 项目，那你可能更多使用 `import` 导入模块。

2021-01-21 01:10 UTC, Ashira97 commented on article/2021/a-deep-dive-into-javascript-modules.md
> +检查 JS 模块类型之间的各种差异的最佳方法是从大家熟悉的地方开始，在这里我们以这门语言的新标准 ES6 为例。因为不是所有的运行时都兼容 ES6，所以在需要时我会用 Babel 将代码转换成不同的风格。
检查 JS 模块类型之间的各种差异的最佳方法是从大家熟悉的地方开始，在这里我们以这门语言的新标准 ES6 为例。
=>了解 JS 模块类型之间的各种差异的最佳方法是从大家熟悉的地方开始，在这里，也就是从我们这门语言的新标准 ES6 开始。
所以在需要时我会用 Babel 将代码转换成不同的风格。
=>所以我会用 Babel 将代码转换成运行时环境所需的风格。

2021-01-21 01:13 UTC, Ashira97 commented on article/2021/a-deep-dive-into-javascript-modules.md
> +我们首先看到，它向 `exports` 对象添加了两个属性。这个对象将会包含“公共”代码。换句话说，任何不属于此对象的内容都无法从外部访问。考虑此对象可以作为 `require` 函数的返回值。如果向其中添加属性，在加载模块时可以直接访问它们：
考虑此对象可以作为 `require` 函数的返回值。
=>我们也可以把该对象理解为 `require` 函数的返回值

2021-01-21 01:16 UTC, Ashira97 commented on article/2021/a-deep-dive-into-javascript-modules.md
> +上面代码示例的第二个重点是，我们添加了 `__esModule` 属性（值为 `true`）。导入端的辅助函数可以在处理默认导出时利用此属性来确定如何访问所需的方法。
导入端的辅助函数可以在处理默认导出时利用此属性来确定如何访问所需的方法。
=>这一属性在该模块被导入时提供了帮助函数来帮助开发者了解如何通过默认的导出对象访问所需的方法。

2021-01-21 01:21 UTC, Ashira97 commented on article/2021/a-deep-dive-into-javascript-modules.md
> +我知道这看起来有很多代码，但现在只关注最后两行。请注意，我们的 `mainMethod` 是默认导出的函数，它位于名为 `default` 的新属性中。我们没有声明它，而是 Babel 为了维护与 CommonJS 的兼容性而添加的属性。还要注意 `dummyFunction` 方法不在 `default` 属性中，因为它是作为单独的实体导出的，实际上也是单独导入的。
我们没有声明它，而是 Babel 为了维护与 CommonJS 的兼容性而添加的属性。
=>我们没有声明这个属性，它是 Babel 为了实现与 CommonJS 兼容而添加的属性。

2021-01-21 01:28 UTC, Ashira97 commented on article/2021/a-deep-dive-into-javascript-modules.md
> +`__interopRequiredWilcard` 辅助函数只负责返回将要使用的具有正确格式的对象（换句话说，如果还没有 `default` 属性，它会添加该属性）。
`__interopRequiredWilcard` 辅助函数只负责返回将要使用的具有正确格式的对象
=>`__interopRequiredWilcard` 辅助函数负责将要使用的对象以正确格式返回

2021-01-21 01:54 UTC, Ashira97 commented on article/2021/a-deep-dive-into-javascript-modules.md
> +当然，假设 `pathToFile` 是一个字符串，这将正常地工作。但是 `import` 不允许这么做，因为并不是在运行时解析的它们。
当然，假设 `pathToFile` 是一个字符串，这将正常地工作。但是 `import` 不允许这么做，因为并不是在运行时解析的它们。
=>假设 `pathToFile` 是一个自定义的字符串，`require` 会正常工作，但是  `import` 不允许这么做，因为在解析  `import` 语句的时候还没有运行时执行环境。

2021-01-21 02:06 UTC, Ashira97 commented on article/2021/a-deep-dive-into-javascript-modules.md
> +这种模式可能需要添加更多的代码来包装你的模块，但它将确保可以与多个系统一起工作。如果你要分发一个供许多用户使用的库，那么这绝对是一个有趣的选择。另一方面，如果你只是为自己的系统创建一个模块，那么额外的工作和代码行可能不值得。
但它将确保可以与多个系统一起工作
=>但它将确保与多个系统兼容

2021-01-21 02:07 UTC, Ashira97 commented on article/2021/a-deep-dive-into-javascript-modules.md
> +我将在这里介绍的最后一个模块加载器是 [SystemJS](https://github.com/systemjs/systemjs)。它提供了将 ES6 兼容的代码加载到运行时不兼容的另一种方法。换句话说，通过使用自定义的 `import` 函数，你可以直接加载 ES6 代码，而无需将其转换为任何内容。
加载到运行时不兼容的另一种方法
=>加载到不兼容的运行时环境的另一种方法

2021-01-21 02:08 UTC, Ashira97 commented on article/2021/a-deep-dive-into-javascript-modules.md
> +`traceu` 依赖关系是 SystemJS 所必需的，因此我们需要它，但是代码的其余部分正在加载并使用我们在本文开头声明的模块（它只使用 ES6 类型的导出和导入）。
依赖关系 => 依赖包
这里或许改为依赖包更合适？

2021-01-21 02:08 UTC, Ashira97 commented on article/2021/a-deep-dive-into-javascript-modules.md
> +如果我们希望在一个还不兼容的运行时内重用所有与 ES6 兼容的代码，那么这绝对是一个不错的选择。
如果我们希望在一个还不兼容的运行时内重用所有与 ES6 兼容的代码
=>如果我们希望在一个不兼容的运行时环境重用所有与 ES6 兼容的代码

2021-01-21 02:10 UTC, Ashira97 commented on article/2021/a-deep-dive-into-javascript-modules.md
> +在编写和使用 JavaScript 模块时，有很多选择，这取决于你的需要和偏好，但说实话，在不久的将来，所有运行时都应该迁移到与 ES6 兼容的版本，因为这是语言正在走的道路。这反过来意味着，除非你是为过时的系统编写代码，否则最好选择原生支持的格式。
因为这是语言正在走的道路。
=>因为这是语言未来的发展方向。

2021-01-21 02:11 UTC, Ashira97 commented
@regon-cao  校对完毕，提了一点建议~烦请译者大大看看啦~

2021-01-21 02:41 UTC, regon-cao commented
@lsvih 校对完成
@Ashira97 感谢校对

2021-01-21 07:02 UTC, lsvih approved these changes

2021-01-21 07:02 UTC, merged

2021-01-21 07:02 UTC, lsvih commented
@regon-cao  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-01-21 10:10 UTC, regon-cao commented
@lsvih   已发布咯    https://juejin.cn/post/6920153306392166413/

2021-01-21 10:14 UTC, lsvih commented
收到！