为什么React Hooks是错误的抽象
xitu/gold-miner pull request #7893
Opened 2021-01-20 09:21 UTC by fltenwall

为什么React Hooks是错误的抽象

译文翻译完成，resolve #7855

2021-01-20 09:29 UTC, fltenwall commented
前端

2021-01-21 01:46 UTC, lsvih commented
感谢翻译，不过您这里面还是有不少的格式问题哈，得劳烦您根据[排版指南](https://github.com/xitu/gold-miner/wiki/译文排版规则指北)修正一下

2021-01-21 02:46 UTC, fltenwall commented
没太注意，我看一下哈

2021-01-21 02:46 UTC, fltenwall commented
没太注意，我看一下哈

2021-01-21 15:27 UTC, PassionPenguin requested changes
总感觉有些比较生硬的翻译，另外记得注意翻译的格式规范嗷：）

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +再开始之前, 我想表达我对 React 团队多年来所付出的努力的感激。他们创建了一个很棒的框架，从很多方面来说，它是我现代 web 的入门。他们为我铺平了道路，让我相信我即将提出的观点，如果没有他们的聪明才智，我不可能得出这些结论。
web => Web，突兀的单词

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +再开始之前, 我想表达我对 React 团队多年来所付出的努力的感激。他们创建了一个很棒的框架，从很多方面来说，它是我现代 web 的入门。他们为我铺平了道路，让我相信我即将提出的观点，如果没有他们的聪明才智，我不可能得出这些结论。
## believe in
> be of the opinion that something is right or acceptable.
> "I don't believe in censorship of the arts"

我相信我的观点，总感觉有些怪怪的，而且这里ideas应该还只是停留在想法上，相信了自己的想法，等到后面才提出opinion

或许可以写为 > 让我相信我的想法是正确的

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +在今天的文章中，我将提出我所观察到的 hooks 的缺点，并提出一种同样强大但不需要太多注意事项的替代 API 。我要说的是，这个 [alternative API](https://malerba118.github.io/elementos-docs/) 有点冗长，但它对计算的浪费较少，概念上更准确，而且与框架无关。
Hooks大写

alternative记得翻译

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +既然钩子在组件的生命周期内都是静态的，那么我们在组件构造时声明它们不是比在渲染阶段声明它们更有意义吗?如果我们在组件的构造过程中附加了 Hooks，我们就不再需要担心强制执行 Hooks 的规则，因为在组件的生命周期中，Hooks 不会再有机会改变位置或被移除。
钩子 和 Hooks，既然 Hooks ...

记得统一用法嗷

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +既然钩子在组件的生命周期内都是静态的，那么我们在组件构造时声明它们不是比在渲染阶段声明它们更有意义吗?如果我们在组件的构造过程中附加了 Hooks，我们就不再需要担心强制执行 Hooks 的规则，因为在组件的生命周期中，Hooks 不会再有机会改变位置或被移除。
问号记得全角

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +如果你在想，“你不能仅仅将Hooks移动到构造函数。他们需要在每次渲染时运行，以获取最新的值”在这一点上，那么你是完全正确的!
空格

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +我们不能只是将 Hooks 移出渲染函数，因为我们会破坏它们。所以我们要用别的东西来代替它们。但首先，Hooks 的第二个主要问题。
最后一句是个病句嗷，只有主语

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +这是一种浪费，因为 React 本质上是说“好吧，在渲染函数中重新计算所有这些值”，然后当它遇到 `useMemo` 或者 `useCallback` 时，它就会返回那个决定，并在碎片上退出。但是，如果 React 只运行它需要运行的内容，那就更有意义了。
本质上是说...这个翻译很魔幻

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +响应式编程已经存在很长一段时间了，但最近在UI框架中成为一种流行的编程范式。
空格

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +注意，当我们修改可观察的 `count$` 值时，传递给 `observe` 的回调函数是如何执行的。您可能想知道 `count$` 后面的 `$`。这就是所谓的 [Finnish Notation](https://medium.com/@benlesh/observables-and- finland - Notation -df8356ed1c9b)，它简单地指出变量包含一个可观察对象。
链接修改？

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +在响应式编程中，还有一个计算/派生的可观察对象的概念，它既可以观察也可以被观察。下面是一个派生的可观察对象的例子，它跟踪另一个可观察对象的值，并对它应用`转换”:
/ 左右空格：）

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +结合我们早期的想法，我们可以从 React 中提取状态职责，并在构造函数中将状态设置为可观察对象的图形。当 observable 发生变化时，它就会通知组件，这样组件就知道要重新渲染了:
observable  => `observable`

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +在上面的例子中，我们在构造函数中创建的可观察对象通过闭包在 render 函数中可用，闭包允许我们设置它们的值以响应单击事件。只有当 `countwo $ ` 的值改变时,`doubledCountTwo$` 观察 `countwo $` 并将其值加倍。注意，我们不是在渲染过程中而是在渲染之前获得重复计数。最后，当任何可观察对象发生变化时，我们使用 `observe` 函数重新渲染组件。
`countwo $ ` => `countwo $`

2021-01-21 15:27 UTC, PassionPenguin commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +这实际上与 Vue3 使用其组合API的方式非常相似。尽管命名不同，但是可以看到这个 Vue 代码片段惊人地相似:
Vue 3

2021-01-21 15:48 UTC, lsvih commented
@PassionPenguin 感谢校对

2021-01-22 01:08 UTC, fltenwall commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +结合我们早期的想法，我们可以从 React 中提取状态职责，并在构造函数中将状态设置为可观察对象的图形。当 observable 发生变化时，它就会通知组件，这样组件就知道要重新渲染了:
这个是原文就没有加标记的，不过加上可能更醒目

2021-01-22 01:16 UTC, fltenwall commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +我们不能只是将 Hooks 移出渲染函数，因为我们会破坏它们。所以我们要用别的东西来代替它们。但首先，Hooks 的第二个主要问题。
这个其实是引出下面的，所以将最后的句子改成冒号应该就可以了

2021-01-22 01:17 UTC, fltenwall commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +再开始之前, 我想表达我对 React 团队多年来所付出的努力的感激。他们创建了一个很棒的框架，从很多方面来说，它是我现代 web 的入门。他们为我铺平了道路，让我相信我即将提出的观点，如果没有他们的聪明才智，我不可能得出这些结论。
改成“确信”怎么样

2021-01-22 07:50 UTC, zenblo commented
@lsvih 校对认领

2021-01-22 13:37 UTC, zenblo commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
>  > * 校对者：
增加校对者

2021-01-22 13:37 UTC, zenblo commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +再开始之前, 我想表达我对 React 团队多年来所付出的努力的感激。他们创建了一个很棒的框架，从很多方面来说，它是我现代 Web 的入门。他们为我铺平了道路，让我确信我的想法是正确的，如果没有他们的聪明才智，我不可能得出这些结论。
再开始之前
=>在开始之前
它是我现代 Web 的入门
=>它是我对现代 Web 开发的引路人

2021-01-22 13:37 UTC, zenblo commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +在今天的文章中，我将提出我所观察到的 Hooks 的缺点，并提出一种同样强大但不需要太多注意事项的替代 API 。我要说的是，这个 [替代 API](https://malerba118.github.io/elementos-docs/) 有点冗长，但它对计算的浪费较少，概念上更准确，而且与框架无关。
这个 [替代 API]
=>这个[替代 API]
去掉中间空格

2021-01-22 13:37 UTC, zenblo commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +响应式编程已经存在很长一段时间了，但最近在UI框架中成为一种流行的编程范式。
但最近在UI框架中成为一种流行的编程范式
=>但最近在 UI 框架中成为一种流行的编程范式

2021-01-22 13:37 UTC, zenblo commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +在响应式编程中，还有一个计算 / 派生的可观察对象的概念，它既可以观察也可以被观察。下面是一个派生的可观察对象的例子，它跟踪另一个可观察对象的值，并对它应用`转换”:
还有一个计算 / 派生的可观察对象的概念
=>还有一个计算或派生的可观察对象的概念

并对它应用转换”
=>并对它应用 `transform`

2021-01-22 13:37 UTC, zenblo commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +在上面的例子中，我们在构造函数中创建的可观察对象通过闭包在 render 函数中可用，闭包允许我们设置它们的值以响应单击事件。只有当 `countwo $` 的值改变时,`doubledCountTwo$` 观察 `countwo $` 并将其值加倍。注意，我们不是在渲染过程中而是在渲染之前获得重复计数。最后，当任何可观察对象发生变化时，我们使用 `observe` 函数重新渲染组件。
统一为 `countTwo$`

2021-01-22 13:37 UTC, zenblo commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +通过对 React API进行一些修改，我们可以实现上面的代码。
通过对 React API进行一些修改
=>通过对 React API 进行一些修改

2021-01-22 13:37 UTC, zenblo commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +当然，我的 `observable`，`derived`，和 `observe` 的实现都有 bug，并没有形成一个完整的状态管理解决方案。更不用说这些精心设计的示例忽略了一些考虑因素，但不用担心:我在这个问题上花了很多心思，我的想法在名为 [Elementos](https://malerba118.github.io/elementos-docs/)的新响应式状态管理库中达到了顶峰!
但不用担心:
=>但不用担心：
中文冒号

2021-01-22 13:38 UTC, zenblo commented
@fltenwall @lsvih 校对完成，提了一些小建议

2021-01-25 02:58 UTC, fltenwall commented
@lsvih 已根据两位校验者的修改意见全部进行了修改

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +这是一个优雅的解决方案，有以下几个原因:
```suggestion
这是一个优雅的解决方案，有以下几个原因：
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +在上面的例子中，我们在构造函数中创建的可观察对象通过闭包在 render 函数中可用，闭包允许我们设置它们的值以响应单击事件。只有当 `countwo$` 的值改变时,`doubledCountTwo$` 观察 `countwo$` 并将其值加倍。注意，我们不是在渲染过程中而是在渲染之前获得重复计数。最后，当任何可观察对象发生变化时，我们使用 `observe` 函数重新渲染组件。
```suggestion
在上面的例子中，我们在构造函数中创建的可观察对象通过闭包在 render 函数中可用，闭包允许我们设置它们的值以响应单击事件。只有当 `countwo$` 的值改变时，`doubledCountTwo$` 观察 `countwo$` 并将其值加倍。注意，我们不是在渲染过程中而是在渲染之前获得重复计数。最后，当任何可观察对象发生变化时，我们使用 `observe` 函数重新渲染组件。
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +结合我们早期的想法，我们可以从 React 中提取状态职责，并在构造函数中将状态设置为可观察对象的图形。当 `observable` 发生变化时，它就会通知组件，这样组件就知道要重新渲染了:
```suggestion
结合我们早期的想法，我们可以从 React 中提取状态职责，并在构造函数中将状态设置为可观察对象的图形。当 `observable` 发生变化时，它就会通知组件，这样组件就知道要重新渲染了：
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +考虑一个应用程序有两个计数器和一个依赖于其中一个计数器的派生状态:
```suggestion
考虑一个应用程序有两个计数器和一个依赖于其中一个计数器的派生状态：
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +在响应式编程中，还有一个计算或派生的可观察对象的概念，它既可以观察也可以被观察。下面是一个派生的可观察对象的例子，它跟踪另一个可观察对象的值，并对它应用 `transform`:
```suggestion
在响应式编程中，还有一个计算或派生的可观察对象的概念，它既可以观察也可以被观察。下面是一个派生的可观察对象的例子，它跟踪另一个可观察对象的值，并对它应用 `transform`：
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +响应式编程的核心思想是，变量是可观察的，当一个可观察对象的值发生变化时，观察者会通过回调函数来通知这个变化:
```suggestion
响应式编程的核心思想是，变量是可观察的，当一个可观察对象的值发生变化时，观察者会通过回调函数来通知这个变化：
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +如果你在想，“你不能仅仅将 Hooks 移动到构造函数。他们**需要**在每次渲染时运行，以获取最新的值”在这一点上，那么你是完全正确的!
```suggestion
如果你在想，“你不能仅仅将 Hooks 移动到构造函数。他们**需要**在每次渲染时运行，以获取最新的值”在这一点上，那么你是完全正确的！
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +不幸的是，函数组件没有构造函数的概念，但是让我们假设它们是构造函数。我想它会像下面这样:
```suggestion
不幸的是，函数组件没有构造函数的概念，但是让我们假设它们是构造函数。我想它会像下面这样：
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +当计数器增加时，会在第二次渲染时产生一个错误，因为组件将删除第二个 `useState` Hooks:
```suggestion
当计数器增加时，会在第二次渲染时产生一个错误，因为组件将删除第二个 `useState` Hooks：
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +从这个意义上说，React 允许开发者犯错误，然后试图警告用户他们的错误。为了说明白我的意思，看下这个例子:
```suggestion
从这个意义上说，React 允许开发者犯错误，然后试图警告用户他们的错误。为了说明白我的意思，看下这个例子：
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +React 的行为与此非常相似。如果我们从概念上考虑 Hooks，它们在组件的整个生命周期内都是静态的。我的意思是说，一旦声明了，我们就不能从组件中移除它们，也不能改变它们相对于其他 Hooks 的位置。 React 使用 lint 规则并抛出错误，试图阻止开发人员违反这个 Hooks 的细节。
```suggestion
React 的行为与此非常相似。如果我们从概念上考虑 Hooks，它们在组件的整个生命周期内都是静态的。我的意思是说，一旦声明了，我们就不能从组件中移除它们，也不能改变它们相对于其他 Hooks 的位置。React 使用 lint 规则并抛出错误，试图阻止开发人员违反这个 Hooks 的细节。
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +这实际上与 Vue 3 使用其组合API的方式非常相似。尽管命名不同，但是可以看到这个 Vue 代码片段惊人地相似:
```suggestion
这实际上与 Vue 3 使用其组合API的方式非常相似。尽管命名不同，但是可以看到这个 Vue 代码片段惊人地相似：
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +3.通过选择仅在依赖项发生变化时重新派生值，我们避免了在不必要的时候重新运行派生逻辑。
```suggestion
3. 通过选择仅在依赖项发生变化时重新派生值，我们避免了在不必要的时候重新运行派生逻辑。
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +如果这还不够令人信服，看看当我们引入一个构造函数层来反应函数组件时，“引用”变得多么简单:
```suggestion
如果这还不够令人信服，看看当我们引入一个构造函数层来反应函数组件时，“引用”变得多么简单：
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +也许更酷的是，我们可以很容易地将 `refs` 变成可观察的:
```suggestion
也许更酷的是，我们可以很容易地将 `refs` 变成可观察的：
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +当然，我的 `observable`，`derived`，和 `observe` 的实现都有 bug，并没有形成一个完整的状态管理解决方案。更不用说这些精心设计的示例忽略了一些考虑因素，但不用担心：我在这个问题上花了很多心思，我的想法在名为 [Elementos](https://malerba118.github.io/elementos-docs/)的新响应式状态管理库中达到了顶峰!
```suggestion
当然，我的 `observable`，`derived`，和 `observe` 的实现都有 bug，并没有形成一个完整的状态管理解决方案。更不用说这些精心设计的示例忽略了一些考虑因素，但不用担心：我在这个问题上花了很多心思，我的想法在名为 [Elementos](https://malerba118.github.io/elementos-docs/)的新响应式状态管理库中达到了顶峰！
```

2021-01-25 08:35 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +Elementos 是一个与框架无关的响应式状态管理库，强调状态的可组合性和封装性。如果你喜欢这篇文章，我强烈建议你去看看!
```suggestion
Elementos 是一个与框架无关的响应式状态管理库，强调状态的可组合性和封装性。如果你喜欢这篇文章，我强烈建议你去看看！
```

2021-01-25 08:35 UTC, lsvih commented
@fltenwall 还有少许格式上的问题，麻烦您看看哈

2021-01-25 09:02 UTC, fltenwall commented
@lsvih 好的，我再仔细修改下格式问题

2021-01-25 09:10 UTC, fltenwall commented
@lsvih 格式问题已经修正，烦请查阅

2021-01-25 09:19 UTC, lsvih commented on article/2021/why-react-hooks-are-the-wrong-abstraction.md
> +> * 校对者：[zenblo](https://github.com/zenblo) [Hoarfroster](https://github.com/Hoarfroster)
```suggestion
> * 校对者：[zenblo](https://github.com/zenblo) [PassionPenguin](https://github.com/PassionPenguin)
```

2021-01-25 09:20 UTC, lsvih commented
@fltenwall 这个链接咋改了个失效的。。

2021-01-25 09:26 UTC, fltenwall commented
@lsvih 已修正

2021-01-25 10:10 UTC, lsvih approved these changes

2021-01-25 10:11 UTC, merged

2021-01-25 10:11 UTC, lsvih commented
@fltenwall  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi