翻译完成
xitu/gold-miner pull request #7894
Opened 2021-01-20 13:57 UTC by samyu2000

译文翻译完成，resolve #7886

2021-01-21 05:33 UTC, regon-cao commented
@lsvih 校对认领

2021-01-21 06:10 UTC, regon-cao commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +在这个例子中，你可以清楚地看到，无论何时都会取缓存的值。这使你能方便地跳过那些计算过程，因为在这之前结果已经计算出来，并被保存起来，而且耗费了大量资源。
并被保存起来，而且耗费了大量资源。  多余

2021-01-21 06:10 UTC, regon-cao commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +如果你仔细观察调用过程，你会发现，由于不涉及计算过程，就很快得到了 `factorial(50)` 的值。这是因为 `factorial(50)` 已经计算完毕，并且缓存在 `factorial(60)` 的内存空间。
并且缓存在 `factorial(60)` 的内存空间 -->
并且在 `factorial(60)` 时已缓存结果

2021-01-21 07:01 UTC, lsvih commented
@regon-cao 感谢校对

2021-01-21 09:39 UTC, Ashira97 commented
@lsvih 校对认领

2021-01-21 09:55 UTC, lsvih commented
@Ashira97 好的~

2021-01-21 09:58 UTC, Ashira97 commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +# Javascript Memoization 入门指南
Javascript=>JavaScript

2021-01-21 10:11 UTC, Ashira97 commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +在上面的例子中，每时每刻都在进行计算。第二次调用 `factorial(100)` 时，整个过程都会重复执行。如果我们在这里实施 memoization，由于我们已经把 `factorial(100)` 存在缓存里，就不需要再次计算了。
每时每刻都在进行计算。=>每次调用都进行一轮计算。

2021-01-21 10:31 UTC, Ashira97 commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +虽然 memoization 可以大大提高程序的性能，还是有一些你需要记住的事项。缓存**存储**了相关的值，这表明数据被存储了。如果函数的输入范围太大，你的缓存就会越来越大。通常 memoization 函数的空间复杂度为O(n)。但要改进 memoization 函数的空间复杂度，需要进行算法设计。
但要改进 memoization 函数的空间复杂度，需要进行算法设计。
=>但也可以使用一些算法来改进 memoization 函数的空间复杂度。

2021-01-21 10:32 UTC, Ashira97 commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +你需要理解，必须平衡两种资源——时间和空间，这很重要。虽然 memoization 可以减少函数的时间复杂度，但另一方面，空间复杂度却增大了。
资源——时间 =>资源 —— 时间
破折号前后加空格~

2021-01-21 10:38 UTC, Ashira97 commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +作为一名软件开发者，需要不断学习。永远存在需要学习的新事物，特别是 Javascript 相关技术。当我们的应用程序变得复杂起来，运行速度就显得尤为重要了。当应用程序代码量不断增加，就需要进行性能优化。Memoization 是一种概念，它能帮助你构建高效的应用，即使在应用程序变得越来越庞大的情况下也是如此。Memoization 概念跟 Javascript 中纯函数和函数式编程密切相关。
作为一名软件开发者，需要不断学习。
=>一名软件开发者需要不断学习。

2021-01-21 10:41 UTC, Ashira97 commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +* **输入数据相同** — 这是一种直白的说法。但它确立了 Memoization 和纯函数之间的联系。从基本概念上来说，如果一个函数的输入数据是相同的，执行这个函数得到的结果也相同，这样的函数就称为纯函数。
如果一个函数的输入数据是相同的，执行这个函数得到的结果也相同
=>如果一个函数对于相同的输入数据总能得到相同的结果

2021-01-21 10:45 UTC, Ashira97 commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +如果你仔细观察调用过程，你会发现，由于不涉及计算过程，就很快得到了 `factorial(50)` 的值。这是因为 `factorial(50)` 已经计算完毕，并且缓存在 `factorial(60)` 的内存空间。
并且缓存在 `factorial(60)` 的内存空间。
=>并且在计算 `factorial(60)` 的时候缓存了结果。

2021-01-21 10:46 UTC, Ashira97 commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +你可以清楚地看到，factorial 函数是一个**纯函数**，因为对于相同的输入，输出值永远是相同的。你也应当注意到，memoize 函数是一个**高阶函数**，这是因为它返回的是一个将来需要调用、也会把输入函数用作参数的函数。更进一步，我们也可以看到，由于正在使用高阶函数，会创建一个闭包，它允许内部嵌套函数访问缓存对象。
把输入函数用作参数=>把函数用作输入参数

2021-01-21 10:47 UTC, Ashira97 commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +你可能想知道 Caching 和 Memoization 的区别在哪里。实际上，caching 可以是各种方式的，例如 HTTP 缓存、图片缓存等。但 memoization 在大多数情况下是一种特定类型的缓存，**它缓存的是函数返回值**。
caching 可以是各种方式的=>caching 有很多含义

2021-01-21 10:48 UTC, Ashira97 commented
@samyu2000 校对完毕 提了一点小建议 翻译的太棒了~

2021-01-21 15:16 UTC, PassionPenguin requested changes
Excellent Translation!

建议全文统一一下Memoize以及Memoization以及Caching等词汇的大小写以及JavaScript的各种拼写方式：）

2021-01-21 15:16 UTC, PassionPenguin commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +作为一名软件开发者，需要不断学习。永远存在需要学习的新事物，特别是 Javascript 相关技术。当我们的应用程序变得复杂起来，运行速度就显得尤为重要了。当应用程序代码量不断增加，就需要进行性能优化。Memoization 是一种概念，它能帮助你构建高效的应用，即使在应用程序变得越来越庞大的情况下也是如此。Memoization 概念跟 Javascript 中纯函数和函数式编程密切相关。
注意全文统一下JavaScript的拼写嗷，可以用用RegExp

2021-01-21 15:16 UTC, PassionPenguin commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +把这个概念分解后，我们应该对 Memoization 有了基本的认识。如果你仍然不理解，没关系，我会深入讲解，让你明白的。
把这个概念拆分为各部分后，我们应该对 Memoization 有了基本的认识。如果你仍然不能够理解，不必担心，我会深入讲解，让你明白的。

2021-01-21 15:16 UTC, PassionPenguin commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +只有纯函数才可以进行 Memoize。如果函数的输入数据相同，却可能产生不同的结果，对这样的函数进行 memoize 是没有实际用途的。看一看下面的代码。
Memoize或许更好？毕竟是比较突兀的专有名词

2021-01-21 15:16 UTC, PassionPenguin commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +虽然输入的数据相同，但每次调用函数输出的结果却不同。对这样的函数进行 memoize 是没有实际意义的。
同上，参考L32的

2021-01-21 15:16 UTC, PassionPenguin commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +更进一步，在这些情况下，你可能需要对函数进行 memoize：
同上

2021-01-21 15:16 UTC, PassionPenguin commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +关于 memoization 的应用，常用的例子是阶乘的计算。我们来了解一下。
同上，建议统一大小写

2021-01-21 15:16 UTC, PassionPenguin commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +在上面的例子中，每时每刻都在进行计算。第二次调用 `factorial(100)` 时，整个过程都会重复执行。如果我们在这里实施 memoization，由于我们已经把 `factorial(100)` 存在缓存里，就不需要再次计算了。
同上，建议统一大小写

2021-01-21 15:16 UTC, PassionPenguin commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +我们来研究一下这个使用 memoization 的例子。
同上

2021-01-21 15:16 UTC, PassionPenguin commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> -If you closely look at the call, you can see that the calculation of `factorial(50)` is pretty quick as there is no computation involved. This is due to the value of `factorial(50)` already being com
原文有点问题

2021-01-21 15:16 UTC, PassionPenguin commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +你可以清楚地看到，factorial 函数是一个**纯函数**，因为对于相同的输入，输出值永远是相同的。你也应当注意到，memoize 函数是一个**高阶函数**，这是因为它返回的是一个将来需要调用、也会把输入函数用作参数的函数。更进一步，我们也可以看到，由于正在使用高阶函数，会创建一个闭包，它允许内部嵌套函数访问缓存对象。
`factorial` 函数
`memoize` 函数

2021-01-21 15:16 UTC, PassionPenguin commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +# Javascript Memoization 入门指南
建议全文统一一下Memoize以及Memoization以及Caching等词汇的大小写以及JavaScript的各种拼写方式：）

2021-01-22 03:34 UTC, samyu2000 commented on article/2021/a-beginners-guide-to-memoization-with-javascript.md
> +把这个概念分解后，我们应该对 Memoization 有了基本的认识。如果你仍然不理解，没关系，我会深入讲解，让你明白的。
你这种译法不符合中文表达习惯

2021-01-22 04:20 UTC, lsvih approved these changes

2021-01-22 04:22 UTC, merged

2021-01-22 04:22 UTC, lsvih commented
@samyu2000  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-01-22 07:27 UTC, samyu2000 commented
@lsvih 已发布 https://juejin.cn/post/6920460950424256526

2021-01-25 08:27 UTC, lsvih commented
收到~