2021 年 Web 应用开发常用的五个图标库
xitu/gold-miner pull request #7899
Opened 2021-01-23 08:56 UTC by zenblo

译文翻译完成，resolve #7840

2021-01-23 10:33 UTC, PassionPenguin requested changes
这个广告文...

Material Icons与SF Symbols它不香嘛

2021-01-23 10:33 UTC, PassionPenguin commented on article/2021/top-5-icon-packs-for-web-apps-in-2021.md
> +# 2021 年 Web 应用开发常用的五个图标库
top 与常用似乎意思有点点远诶会不会？

2021-01-23 10:33 UTC, PassionPenguin commented on article/2021/top-5-icon-packs-for-web-apps-in-2021.md
> +图标或许很小，但却能给用户提供强有力的信息，即便是没有一个单词文本的图标。说到图标，我们可以使用现成的图标库，或者独立构建图标。然而，鉴于以下原因，我建议使用图标库。
> 图标或许很小，但即便是没有一个单词文本的图标，也能给用户提供强有力的信息。

2021-01-23 10:33 UTC, PassionPenguin commented on article/2021/top-5-icon-packs-for-web-apps-in-2021.md
>  ![Screenshot by Auther: Customizing icons in Icons8](https://cdn-images-1.medium.com/max/3068/1*Mv5Z09kKyMafb0PlZLONLw.png)
翻译下呗

2021-01-23 10:33 UTC, PassionPenguin commented on article/2021/top-5-icon-packs-for-web-apps-in-2021.md
> +* CC 套件有一个 Adobe 扩展。
> 为 Adobe 的创意云套件（CC）提供了拓展（校对者注：目前并没有搜索到相关拓展，官网链接已失效，可能是该拓展已下架）

2021-01-23 10:33 UTC, PassionPenguin commented on article/2021/top-5-icon-packs-for-web-apps-in-2021.md
> +使用免费版，你只能下载所选择图标的完整版本，如果你希望使用常规、浅色或双色调等更多版本，则需要切换到专业版。
翻译有误嗷，https://fontawesome.com/icons/acorn?style=regular

Light和Regular是字体粗细
<img width="138" alt="Screen Shot 2021-01-23 at 6 31 43 PM" src="https://user-images.githubusercontent.com/41184947/105575804-43021c00-5da9-11eb-943e-b7c18794b07c.png">

2021-01-23 12:05 UTC, zenblo commented
@PassionPenguin 感谢校对！你提到的那两个图标库也是常用的。图片处的原文就不动吧，本身没有大的含义。

2021-01-23 12:54 UTC, PassionPenguin commented
> @PassionPenguin 感谢校对！你提到的那两个图标库也是常用的。图片处的原文就不动吧，本身没有大的含义。

哈哈哈只是很想吐槽这篇文章罢了。图片那些alt也没啥意义，但建议还是可以翻译一下，为屏幕阅读器/无图浏览服务：）

- by 苏苏的 [PassionPenguin](https://github.com/PassionPenguin)

2021-01-23 12:54 UTC, PassionPenguin approved these changes

2021-01-27 09:30 UTC, lsvih approved these changes

2021-01-27 09:30 UTC, merged

2021-01-27 09:30 UTC, lsvih commented
@zenblo  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-01-27 12:31 UTC, zenblo commented
@lsvih @PassionPenguin 掘金文章发布地址  https://juejin.cn/post/6922416136294252557/