如何让 JavaScript 中的循环慢下来
xitu/gold-miner pull request #7919
Opened 2021-01-25 15:37 UTC by PassionPenguin

译文翻译完成，resolve #7913 @lsvih 

- by 苏苏的 [霜羽 Hoarfroster](https://github.com/PassionPenguin)

2021-01-25 17:05 UTC, PassionPenguin reviewed
Minor changes

2021-01-25 17:05 UTC, PassionPenguin commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +造成这个结果的原因是我们思维上的一个误区。似乎 For 循环中程序并没有为每一个元素设置 `timeout`。
造成这个结果的原因是我们想法是一个小小的错误 —— 似乎 For 循环中程序并没有为每一个元素设置 `timeout`，但实际上，程序设置了。

2021-01-25 17:05 UTC, PassionPenguin commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +但如果以这个想法为出发点，其实它可以在其他一些编程语言中起作用 —— 循环创建 `timeout`，而只有在这些任务执行后，循环才继续执行 —— 至少在其他编程语言中才继续。但是，在 JavaScript 中，将创建 `timeout`，并且代码将继续执行下去不会停留。因此，JavaScript 创建了两个并行运行的任务。
但如果以这个想法为出发点，其实它可以在其他一些编程语言中起作用 —— 循环创建 `timeout`，而只有在这些任务执行后，循环才继续执行 —— 至少在其他编程语言中才继续。但是，在 JavaScript 中，JavaScript 不会停下来，而只会继续创建 `timeout`，代码将继续执行下去不会停留。因此，JavaScript 可以看作是创建了两个并行运行的进程。

2021-01-25 17:05 UTC, PassionPenguin commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +我们通过函数调用 `Promise`。它将获取 **setTimeout** 应该延迟的时间（以毫秒为单位）。在一定时间后，所有 `timeout` 都会执行 `resolve` 函数。这意味着 `Promise` 能够实现我们所需要的功能 —— 它是异步的。我们可以简化上面显示的代码：
我们通过函数调用 `Promise`。它将获取 **setTimeout** 应该被设置的时间（以毫秒为单位）。在一定时间后，所有 `timeout` 都会执行 `resolve` 函数。这意味着 `Promise`这下子就是执行的了，程序可以继续进行了。我们可以简化上面显示的代码：

2021-01-26 01:44 UTC, samyu2000 commented
@lsvih 校对认领

2021-01-26 01:45 UTC, lsvih commented
@samyu2000 欢迎校对~

2021-01-26 11:17 UTC, Usualminds commented
@lsvih 校对认领

2021-01-26 11:25 UTC, lsvih commented
@Usualminds 好的~

2021-01-26 12:28 UTC, Usualminds requested changes
@lsvih @PassionPenguin 校对完成，提了几个小建议

2021-01-26 12:28 UTC, Usualminds commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +For 循环在 JavaScript 中是必不可少的。使用 For 循环能够帮助我们排序列表。但是它们存在一个问题 —— For 循环是尽可能快地执行，如果我们只是用它来遍历数组，这当然是可取的。
使用 For 循环能够帮助我们排序列表 => 使用 For 循环能够帮助我们对列表进行排序

2021-01-26 12:28 UTC, Usualminds commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +For 循环在 JavaScript 中是必不可少的。使用 For 循环能够帮助我们排序列表。但是它们存在一个问题 —— For 循环是尽可能快地执行，如果我们只是用它来遍历数组，这当然是可取的。
但是它们存在一个问题  => 但是这里存在一个问题 
这当然是可取的 => 这已经足够了

2021-01-26 12:28 UTC, Usualminds commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +我将向您展示如何执行此操作 —— 为 For 循环定时。
我将向您展示如何执行此操作 —— 为 For 循环定时 => 我将向你展示如何为 For 循环定时。

2021-01-26 12:28 UTC, Usualminds commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +## 首先：不起作用的方法
不起作用的方法 => 无效的方法

2021-01-26 12:28 UTC, Usualminds commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +这并不是我们所希望的。
这并不是我们所希望的。 => 这并不是我们想要的结果。

2021-01-26 12:28 UTC, Usualminds commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +而一当设置的时间到了，所有的任务都会立即执行 —— 同时打印日志。
一当 => 一旦

2021-01-26 12:28 UTC, Usualminds commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +## 如何适当降缓 For 循环的速度
如何适当降缓 For 循环的速度 => 如何正确地降低 For 循环的执行速度

2021-01-26 12:28 UTC, Usualminds commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +因此，如果我们使用 **setTimeout**，它将无法达到我们的预期。
因此 => 既然

2021-01-26 12:28 UTC, Usualminds commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +我们通过函数调用 `Promise`。它将获取 **setTimeout** 应该被设置的时间（以毫秒为单位）。在一定时间后，所有 `timeout` 都会执行 `resolve` 函数。这意味着 `Promise`这下子就是执行的了，程序可以继续进行了。我们可以简化上面显示的代码：
这意味着 `Promise`这下子就是执行的了 => 这意味着 `Promise` 执行了

2021-01-27 01:30 UTC, samyu2000 reviewed
@PassionPenguin @lsvih 校对完成

2021-01-27 01:30 UTC, samyu2000 commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +也就是说，Promise 足以实现我们的预期。现在让我们将它添加到 For 循环中：
Promise 足以实现我们的预期 => 使用 Promise 可以实现我们需要的功能

2021-02-02 03:04 UTC, PassionPenguin commented
嗷没留意到，稍等 @samyu2000

2021-02-02 03:13 UTC, PassionPenguin commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +因此，如果我们使用 **setTimeout**，它将无法达到我们的预期。
这里还是因此比较好，既然的话就需要把下一句话合并上来，不然就没有转折是病句了

2021-02-02 03:16 UTC, PassionPenguin commented on article/2021/how-to-slow-down-a-for-loop-in-javascript.md
> +## 首先：不起作用的方法
不是吧，`how` it doesnt work 强调 how 嗷

2021-02-02 03:21 UTC, PassionPenguin commented
@samyu2000 @zenblo 校对完成啦，有部分内容没有更改，没有必要，然后部分内容合并了两个校对意见

2021-02-02 03:58 UTC, lsvih approved these changes

2021-02-02 03:58 UTC, merged

2021-02-02 03:58 UTC, lsvih commented
@PassionPenguin  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-02-02 04:12 UTC, PassionPenguin commented
@zenblo @samyu2000 @lsvih 译文已经发布啦～🍻

- [x] https://juejin.cn/post/6924512805135581197
- [x] https://zhuanlan.zhihu.com/p/348740838
- [x] https://www.bilibili.com/read/preview/9593693

- by [霜羽 Hoarfroster](https://github.com/PassionPenguin)

2021-02-02 06:16 UTC, Usualminds commented
@PassionPenguin 校对者加下我，你好像添加错人了，哈哈

2021-02-02 06:19 UTC, PassionPenguin commented
诶抱歉抱歉

2021-02-02 06:37 UTC, PassionPenguin commented
Fixed:)

2021-02-13 06:42 UTC, PassionPenguin commented
Fix #8029 

- [x] https://juejin.cn/post/6924512805135581197
- [x] https://zhuanlan.zhihu.com/p/348740838
- [x] https://www.bilibili.com/read/cv9593693