SwiftUI 2 应用生命周期的终极指导
xitu/gold-miner pull request #7939
Opened 2021-01-27 09:18 UTC by zhuzilin

译文翻译完成，resolve #7934

2021-01-27 15:41 UTC, PassionPenguin requested changes
Excellent Translation 不过有部分地方如 activity 的翻译就过头了

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +在很长一段时间里，`AppDelegate` 都是 iOS 开发者们的应用的入口。随着 SwiftUI2 在 WWDC 2020 上发布，苹果公司引入了一个新的应用生命周期。新的生命周期几乎（几乎）完全与 `AppDelegate` 无关，为类 DSL 的方法铺平了道路。
SwiftUI 2 + 类..名词不必要加助词吧：）

```suggestion
在很长一段时间里，`AppDelegate` 都是 iOS 开发者们的应用的入口。随着 SwiftUI 2 在 WWDC 2020 上发布，苹果公司引入了一个新的应用生命周期。新的生命周期几乎（几乎）完全与 `AppDelegate` 无关，为类 DSL 方法铺平了道路。
```

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +在本文中，我会讨论引入新的生命周期的原因，以及你该如何在新旧应用中使用它。
新旧应用刚看到还懵了一会 = =

```suggestion
在本文中，我会讨论引入新的生命周期的意义，以及你该如何在已有的应用或新的应用中使用它。
```

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +> Swift编译器将识别标注了 @main 属性的类型为程序的入口。标有 @main 的类型有一个隐式要求：类型内部需要声明一个静态 main() 方法。
```suggestion
> Swift编译器将识别标注了 `@main` 属性的类型为程序的入口。标有 `@main` 的类型有一个隐式要求：类型内部需要声明一个静态 `main()` 方法。
```

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +创建新的 SwiftUI 应用时，应用的 main class 如下所示：
main class 可以翻译啊，或者至少翻译 class 或者至少加代码标记嗷！
```suggestion
创建新的 SwiftUI 应用时，应用的 `main` class 如下所示：
```

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +如果上述这些听起来有点复杂，好消息是实际上在创建新的SwiftUI应用程序时你不必关心它：只需确保在 **Life Cycle** 下拉菜单中选择 **SwiftUI App** 来创建你的应用程序就行了：
```suggestion
如果上述这些听起来有点复杂，好消息是实际上在创建新的 SwiftUI 应用程序时你不必关心它：只需确保在 **Life Cycle** 下拉菜单中选择 **SwiftUI App** 来创建你的应用程序就行了：
```

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +让我们来看一些常见的情况。
空行丢啦

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +* 为你的 main class 实现一个构造函数（initializer）（详见[文档](https://docs.swift.org/swift-book/LanguageGuide/Initialization.html#ID205)）
意见同上

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +如果上述几种策略都无法满足你的需求，你可能还是需要一个 AppDelegate。后文会介绍如果能在应用中加入一个 AppDelegate。
```suggestion
如果上述几种策略都无法满足你的需求，你可能还是需要一个 `AppDelegate`。后文会介绍如果能在应用中加入一个 `AppDelegate`。
```

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +从 iOS 14.0 起，苹果提供了新的 API，该 API 允许以更优雅，更易维护的方式跟踪应用程序状态：`[ScenePhase](https://developer.apple.com/documentation/swiftui/scenephase)`。你的项目可以有多个场景（scene），不过有时只有一个场景，由 [WindowGroup](https://developer.appl
```suggestion
从 iOS 14.0 起，苹果提供了新的 API，该 API 允许以更优雅，更易维护的方式跟踪应用程序状态：`[ScenePhase](https://developer.apple.com/documentation/swiftui/scenephase)`。你的项目可以有多个场景（`scene`），不过有时只有一个场景。这些情景将由 `[WindowGroup](https://developer.apple.com/documentation/swiftui/windowgroup) 展示`。
```

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +## 继续用户活动
？

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +下面是一个展现如何公示活动的代码片段。在一个具体的视图里：
？

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +为了允许继续进行此活动，你可以在最顶层的导航视图中注册 `onContinueUserActivity` 闭包，如下所示：
这个活动没必要翻译吧，翻译过来反而感觉很别扭，总像是线下活动似的。

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +同样，新的应用生命周期模型通过提供两个 modifier 使你更容易实现这一点。这些 modifier 使你可以公示活动并随后继续进行。
？

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +如果你的应用使用 `NSUserActivity` 来[集成](https://developer.apple.com/documentation/foundation/nsuseractivity) Siri、Handoff 或 Spotlight，你需要处理用户继续进行的活动。
？

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +新的应用声明周期（截止当前）并非支持 `AppDelegate`的所有回调函数。如果上述这些都不满足你的需求，你可能还是需要一个 `AppDelegate`。
```suggestion
新的应用声明周期（截止当前）并非支持 `AppDelegate` 的所有回调函数。如果上述这些都不满足你的需求，你可能还是需要一个 `AppDelegate`。
```

2021-01-27 15:41 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +另一个需要 AppDelegate 的原因是你使用的第三方 SDK 会使用 [method swizzling](https://pspdfkit.com/blog/2019/swizzling-in-swift/) 来把它们注入应用生命周期。[Firebase](https://firebase.google.com/) 就是一个[著名的例子](https://stackoverflow.co
```suggestion
另一个需要 `AppDelegate` 的原因是你使用的第三方 SDK 会使用 [method swizzling](https://pspdfkit.com/blog/2019/swizzling-in-swift/) 来把它们注入应用生命周期。[Firebase](https://firebase.google.com/) 就是一个[典型的例子](https://stackoverflow.com/a/62633158/281221)。
```

2021-01-28 02:37 UTC, zhuzilin commented
@PassionPenguin 感谢校对~我会尽快改正过来的。

2021-01-28 08:02 UTC, zenblo commented
@lsvih 校对认领

2021-01-28 08:43 UTC, lsvih commented
@zenblo 好的

2021-01-29 06:25 UTC, zenblo commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
>  > * 校对者：
添加校对者信息

2021-01-29 06:25 UTC, zenblo commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +在很长一段时间里，`AppDelegate` 都是 iOS 开发者们的应用的入口。随着 SwiftUI2 在 WWDC 2020 上发布，苹果公司引入了一个新的应用生命周期。新的生命周期几乎（几乎）完全与 `AppDelegate` 无关，为类 DSL 的方法铺平了道路。
`AppDelegate` 都是 iOS 开发者们的应用的入口
=>iOS 开发者们都是使用 `AppDelegate` 作为应用的主要入口

2021-01-29 06:25 UTC, zenblo commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +我们的第一个问题是，该如何告诉编译器哪里是应用的入口呢？[SE-0281]（https://github.com/apple/swift-evolution/blob/master/proposals/0281-main-attribute.md）详述了**基于类型的程序入口（Type-Based Program Entry Points）**的工作方式：
[SE-0281]（https://github.com/apple/swift-evolution/blob/master/proposals/0281-main-attribute.md）
=>[SE-0281](https://github.com/apple/swift-evolution/blob/master/proposals/0281-main-attribute.md)

2021-01-29 06:25 UTC, zenblo commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +> Swift编译器将识别标注了 @main 属性的类型为程序的入口。标有 @main 的类型有一个隐式要求：类型内部需要声明一个静态 main() 方法。
Swift编译器
=>Swift 编译器
添加空格

2021-01-29 06:25 UTC, zenblo commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +如果上述这些听起来有点复杂，好消息是实际上在创建新的SwiftUI应用程序时你不必关心它：只需确保在 **Life Cycle** 下拉菜单中选择 **SwiftUI App** 来创建你的应用程序就行了：
好消息是实际上在创建新的SwiftUI应用程序时你不必关心它
=>好消息是实际上在创建新的 SwiftUI 应用程序时你不必关心它

2021-01-29 06:25 UTC, zenblo commented
@lsvih @zhuzilin 校对完成，提了一点小建议

2021-01-30 01:57 UTC, zhuzilin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +创建新的 SwiftUI 应用时，应用的 main class 如下所示：
我还是翻译成主类好了~

2021-01-30 02:02 UTC, zhuzilin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +为了允许继续进行此活动，你可以在最顶层的导航视图中注册 `onContinueUserActivity` 闭包，如下所示：
@PassionPenguin 嗯，的确是。我翻译的时候也觉得这个活动很怪...但是又觉得写成“用户 activity” 就太中英混杂了...我还是保留 activity 吧~

2021-01-30 02:04 UTC, zhuzilin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +下面是一个展现如何公示活动的代码片段。在一个具体的视图里：
@PassionPenguin 这里我把握不太好这个 advertise 怎么翻比较好...有什么建议吗？感觉结合上下文，是说在应用里面“广而告之”有这么个 activity 了....

2021-01-30 02:27 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +为了允许继续进行此活动，你可以在最顶层的导航视图中注册 `onContinueUserActivity` 闭包，如下所示：
话说，我感觉这个很类似于 Android 的 Activity，也是一个生命周期，例如

```kotlin
package io.hoarfroster.android

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }
}
```

2021-01-30 02:27 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +为了允许继续进行此活动，你可以在最顶层的导航视图中注册 `onContinueUserActivity` 闭包，如下所示：
感觉直接翻译
```suggestion
为了允许继续进行此 activity，你可以在最顶层的导航视图中注册 `onContinueUserActivity` 闭包，如下所示：
```

2021-01-30 02:33 UTC, PassionPenguin commented on article/2021/ultimate-guide-to-swiftui2-application-lifecycle.md
> +下面是一个展现如何公示活动的代码片段。在一个具体的视图里：
毕竟下文是 "showColor"，或许advertise是告诉编译器这里有个用户的 activity？

2021-02-01 01:37 UTC, zhuzilin commented
@PassionPenguin @zenblo 感谢两位的校对，已更新。
cc @lsvih

2021-02-01 02:37 UTC, lsvih approved these changes

2021-02-01 02:37 UTC, merged

2021-02-01 02:37 UTC, lsvih commented
@zhuzilin  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-02-01 02:43 UTC, zhuzilin commented
@lsvih 辛苦啦~已经发布在了 https://juejin.cn/post/6924119708832628749/