我拒绝了 MIT 的 Offer，依然是一个高价值的开发者
xitu/gold-miner pull request #7945
Opened 2021-01-27 15:11 UTC by keepmovingljzy

译文翻译完成，resolve #7907

2021-01-27 15:13 UTC, keepmovingljzy commented
@lsvih 翻译完成

2021-01-27 17:29 UTC, PassionPenguin requested changes
翻译真棒，但仍然有一些些小小的问题，或许译者可以粗读一遍揪一下一些翻译口吻：） @keepmovingljzy @lsvih 

- by 苏苏的 [霜羽 Hoarfroster](https://github.com/PassionPenguin)

2021-01-27 17:29 UTC, PassionPenguin commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +然而[我去了一所州立学校](https://medium.com/the-ascent/4-brutally-honest-reasons-why-i-declined-my-offer-to-the-worlds-best-university-for-a-state-school-6a70d8a452e7)，那地方虽然工程专业虽然算不上顶尖，但是也还行吧。现在我代表着我司 [最重要的编程资产
资产很那个感觉是死物，或许改为 宝藏 啊 财富 啊 更棒

这使我

```suggestion
然而[我去了一所州立学校](https://medium.com/the-ascent/4-brutally-honest-reasons-why-i-declined-my-offer-to-the-worlds-best-university-for-a-state-school-6a70d8a452e7)，那地方虽然工程专业虽然算不上顶尖，但是也还行吧。现在我代表着我司[最重要的编程财富之一](https://medium.com/better-programming/how-i-made-myself-a-more-valuable-programmer-in-6-months-and-how-you-can-too-97f3323f9035) ，这使我意识到并非昂贵的，最好的，甚至体面的正规教育才能成就一个有价值的程序员。
```

```suggestion
然而[我去了一所州立学校](https://medium.com/the-ascent/4-brutally-honest-reasons-why-i-declined-my-offer-to-the-worlds-best-university-for-a-state-school-6a70d8a452e7)，那地方虽然工程专业虽然算不上顶尖，但是也还行吧。现在我代表着我司[最重要的编程财产之一](https://medium.com/better-programming/how-i-made-myself-a-more-valuable-programmer-in-6-months-and-how-you-can-too-97f3323f9035) ，这使我意识到并非昂贵的，最好的，甚至体面的正规教育才能成就一个有价值的程序员。
```

```suggestion
然而[我去了一所州立学校](https://medium.com/the-ascent/4-brutally-honest-reasons-why-i-declined-my-offer-to-the-worlds-best-university-for-a-state-school-6a70d8a452e7)，那地方虽然工程专业虽然算不上顶尖，但是也还行吧。现在我代表着我司[最重要的编程宝藏之一](https://medium.com/better-programming/how-i-made-myself-a-more-valuable-programmer-in-6-months-and-how-you-can-too-97f3323f9035) ，这使我意识到并非昂贵的，最好的，甚至体面的正规教育才能成就一个有价值的程序员。
```

2021-01-27 17:29 UTC, PassionPenguin commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +你们可能在听到埃隆马斯克 [发推文](https://www.inc.com/jeff-haden/if-you-want-to-work-at-tesla-elon-musk-just-tweeted-he-doesnt-care-if-you-even-graduated-high-school-it-might-be-smartest-thing-hes-ever-said.html#:~
```suggestion
你们可能在听到埃隆马斯克[发推文](https://www.inc.com/jeff-haden/if-you-want-to-work-at-tesla-elon-musk-just-tweeted-he-doesnt-care-if-you-even-graduated-high-school-it-might-be-smartest-thing-hes-ever-said.html#:~:text=Musk%20doesn't%20care%20whether,will%20have%20to%20demonstrate%20knowledge.) 告诉你不需要学位，甚至不需要高中毕业就可以为他工作时也会有这种感受。你只需要知道你有什么。
```

2021-01-27 17:29 UTC, PassionPenguin commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +邻家的草分外青，人生没有回头路，你的内心充满了悔不当初。这真的只是一个借口。
excellent translation as well as the original story！

2021-01-27 17:29 UTC, PassionPenguin commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +也许我上的工程课不是最好的，但是我上的水球运动课全美排名第三。 虽然这与编程无关，但是请你再忍忍吧。 因为它仍然很有意义。
```suggestion
也许我上的工程课不是最好的，但是我上的水球运动课全美排名第三。虽然这与编程无关，但请允许我讨论一下这个课程。因为它仍然很有意义。
```

2021-01-27 17:29 UTC, PassionPenguin commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +尽管如此，我不会让我的环境阻止我。
```suggestion
尽管如此，我不会让我的环境阻挡我的步伐。
```

2021-01-27 17:29 UTC, PassionPenguin commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +最终，所有这些额外的辛苦让我连续两年创造了国内最多球的记录。我也不会等着招聘者来找我。而是我主动联系了他们，给他们发游戏视频，让他们来找我。我被招收到全国最好的水球项目之一，这些只是我自己的目标导向行动的结果。
```suggestion
最终，所有这些额外的辛苦让我连续两年创造了县内进球数最多的记录。我也不会等着招聘者来找我，而是我主动联系了他们，给他们发游戏视频，让他们来找我。我被招收到全国最好的水球项目之一，这些只是我自己的目标导向行动的结果。
```

2021-01-27 17:29 UTC, PassionPenguin commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +如果你想升职又不想被人注意，那么把你工作周报发给经理甚至 CEO/CTO。这样他们就不会忽视你的生产力和主动性。这是 John Sonmez 在他的书 **A Complete Software Developer Career Guide** 中提到的。
```suggestion
如果你想升职又不想被人注意，那么把你工作周报发给经理甚至 CEO / CTO。这样他们就不会忽视你的生产力和主动性。这是 John Sonmez 在他的书 **A Complete Software Developer Career Guide** 中提到的。
```

2021-01-28 02:51 UTC, keepmovingljzy commented
@PassionPenguin 校对辛苦了，很好的建议，感谢~

2021-01-28 02:51 UTC, keepmovingljzy commented
@lsvih

2021-02-01 07:56 UTC, regon-cao commented
@lsvih 校对认领

2021-02-01 08:27 UTC, PassionPenguin approved these changes
```zsh
$ lint-md data.md --config /Library/WebServer/Documents/lint-md/config.json
Lint total 1 files, 0 warnings 0 errors
```

2021-02-01 08:29 UTC, lsvih commented
@regon-cao 好的

2021-02-01 08:52 UTC, regon-cao reviewed
@keepmovingljzy 提了些建议

2021-02-01 08:52 UTC, regon-cao commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +你可以能觉得我在异想天开，MIT 不仅有着世界上 [最好](https://www.businessinsider.com/best-computer-science-schools-in-the-world-2018-3#1-massachusetts-institute-of-technology-mit-50) 的计算机科学专业而且还是**** [排名最好的大学](https://news
然后你猜怎么着，-->
然后你猜怎么着？

2021-02-01 08:52 UTC, regon-cao commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +然而 [我去了一所州立学校](https://medium.com/the-ascent/4-brutally-honest-reasons-why-i-declined-my-offer-to-the-worlds-best-university-for-a-state-school-6a70d8a452e7)，那地方虽然工程专业虽然算不上顶尖，但是也还行吧。现在我代表着我司 [最重要的编程宝
然而 [我去了一所州立学校]  -->
然而，[我去了一所州立学校]

2021-02-01 08:52 UTC, regon-cao commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +然而 [我去了一所州立学校](https://medium.com/the-ascent/4-brutally-honest-reasons-why-i-declined-my-offer-to-the-worlds-best-university-for-a-state-school-6a70d8a452e7)，那地方虽然工程专业虽然算不上顶尖，但是也还行吧。现在我代表着我司 [最重要的编程宝
现在我代表着我司 [最重要的编程宝藏之一]  -->
现在我作为当前公司 [最有价值的程序员之一]

2021-02-01 08:52 UTC, regon-cao commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +不过，我还是很少看到有人在真正探寻自己的学习之路，埃隆的说法并不意味着他就轻易放过了那些缺乏教育的人，恰恰相反，他希望寻找一个对 AI 有足够兴趣并且能够 **自我激励** 和 **自力更生** 的人，一起深入探讨这个话题。
埃隆的说法并不意味着他就轻易放过了那些缺乏教育的人  -->
埃隆的说法不完全排除那些缺乏教育的人

2021-02-01 08:52 UTC, regon-cao commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +不过，我还是很少看到有人在真正探寻自己的学习之路，埃隆的说法并不意味着他就轻易放过了那些缺乏教育的人，恰恰相反，他希望寻找一个对 AI 有足够兴趣并且能够 **自我激励** 和 **自力更生** 的人，一起深入探讨这个话题。
他希望寻找一个对 AI 有足够兴趣并且能够 **自我激励** 和 **自力更生** 的人，一起深入探讨这个话题。-->
他想要的是一个对 AI 有足够兴趣，自己可以深入地且全面地探索 AI，并且能够 **自我激励** 和 **自力更生** 的人。

2021-02-01 08:52 UTC, regon-cao commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +- “只有上了正确的大学，才能真正成为一名工程师。 相反，我觉得我的学业阻碍了我的天赋发展。”
多了一个空格

2021-02-01 08:52 UTC, regon-cao commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +- “经理没有注意到我，我一直在努力工作。 如果我继续努力的话，也许他们最终会注意到并提拔我。”
多了一个空格

2021-02-01 08:52 UTC, regon-cao commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +我本可以去 MIT，进入这样的精英大学基本上意味着我是个开发人员了。我本可以说在初创公司工作是浪费时间，我应该微软或者谷歌实习。我可能因为我花了多年时间学习游戏开发并开发这些附带项目成为一个 Salesforce 开发人员，现状本该让我非常不满。我本可以在生活中游刃有余，而不是自学成才，最终只能想想我还有什么潜力。
我应该微软或者谷歌实习。-->
我应该去微软或者谷歌实习。

2021-02-01 08:52 UTC, regon-cao commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +也许我上的工程课不是最好的，但是我上的水球运动课全美排名第三。 虽然这与编程无关，但是请允许我讨论一下这个课程。 因为它仍然很有意义。
多了空格

2021-02-01 08:52 UTC, regon-cao commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +他们为我提供了全额奖学金让我在那里打球，你肯定猜不到我之前在全州最不适合这项运动的高中之一。 在这七个赛区中，我的学校排名垫底，甚至连州冠军都没有进入。 所以它不可能受到关注或着重视。
你肯定猜不到我之前在全州最不适合这项运动的高中之一 -->
你肯定猜不到我去了全州玩这项运动最差的高中

2021-02-01 08:52 UTC, regon-cao commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +您只需要意识到自己必须做出决定并执行计划，将这些事情变为现实。而不是等待天生掉馅饼。
天生掉  -->  天上掉

2021-02-01 08:52 UTC, regon-cao commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +你需要学会时间管理，扪心自问什么对自己和自我成长是真正重要的。
扪心自问什么对自己和自我成长是真正重要的 -->
扪心自问什么才是对自己和自我成长真正重要的

2021-02-01 09:12 UTC, keepmovingljzy commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +你可以能觉得我在异想天开，MIT 不仅有着世界上 [最好](https://www.businessinsider.com/best-computer-science-schools-in-the-world-2018-3#1-massachusetts-institute-of-technology-mit-50) 的计算机科学专业而且还是**** [排名最好的大学](https://news
我觉得这里用异想天开更合适，疯了感觉有点翻译的太直白了

2021-02-01 09:17 UTC, keepmovingljzy commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +然而 [我去了一所州立学校](https://medium.com/the-ascent/4-brutally-honest-reasons-why-i-declined-my-offer-to-the-worlds-best-university-for-a-state-school-6a70d8a452e7)，那地方虽然工程专业虽然算不上顶尖，但是也还行吧。现在我代表着我司 [最重要的编程宝
most valuable programming assets 不仅仅是程序员，可能还包含公司的其他程序宝藏，比如公司代码设计原则，公司内部分享的资料等等。

2021-02-01 09:19 UTC, keepmovingljzy commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +不过，我还是很少看到有人在真正探寻自己的学习之路，埃隆的说法并不意味着他就轻易放过了那些缺乏教育的人，恰恰相反，他希望寻找一个对 AI 有足够兴趣并且能够 **自我激励** 和 **自力更生** 的人，一起深入探讨这个话题。
这里不是排除吧，埃隆强调他不是特别注重学历，但是他也不会轻易放过低学历/缺乏教育的人，而不是他把低学历的人排除了

2021-02-01 09:26 UTC, keepmovingljzy commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +他们为我提供了全额奖学金让我在那里打球，你肯定猜不到我之前在全州最不适合这项运动的高中之一。 在这七个赛区中，我的学校排名垫底，甚至连州冠军都没有进入。 所以它不可能受到关注或着重视。
最差可能有好几个

2021-02-01 09:33 UTC, keepmovingljzy commented
@regon-cao 校对辛苦了，很好的建议，感谢校对！

2021-02-01 09:33 UTC, keepmovingljzy commented
@lsvih

2021-02-01 09:41 UTC, lsvih commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +> - 校对者：[PassionPenguin](https://github.com/PassionPenguin)
增加校对者信息

2021-02-01 09:53 UTC, PassionPenguin commented
```zsh
lint-md data.md --config /Library/WebServer/Documents/lint-md/config.json
/Users/penguin/data.md
   20:99-20:104          no-space-in-emphasis          Emphasis content can not start / end with space. '自我激励 '

Lint total 1 files, 0 warnings 1 errors
```

2021-02-01 09:54 UTC, PassionPenguin requested changes

2021-02-01 09:54 UTC, PassionPenguin commented on article/2021/i-got-into-mit-refused-the-offer-and-still-became-a-highly-valued-developer.md
> +不过，我还是很少看到有人在真正探寻自己的学习之路，埃隆的说法并不意味着他就轻易放过了那些缺乏教育的人，恰恰相反，他想要的是一个对 AI 有足够兴趣，自己可以深入地且全面地探索 AI，并且能够 **自我激励 ** 和 **自力更生** 的人。
```suggestion
不过，我还是很少看到有人在真正探寻自己的学习之路，埃隆的说法并不意味着他就轻易放过了那些缺乏教育的人，恰恰相反，他想要的是一个对 AI 有足够兴趣，自己可以深入地且全面地探索 AI，并且能够 **自我激励** 和 **自力更生** 的人。
```

2021-02-02 02:01 UTC, keepmovingljzy commented
@PassionPenguin 感谢指出问题！

2021-02-02 02:02 UTC, keepmovingljzy commented
@lsvih 添加完成，翻译完成

2021-02-02 02:12 UTC, lsvih approved these changes

2021-02-02 02:12 UTC, merged

2021-02-02 02:12 UTC, lsvih commented
@keepmovingljzy  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-02-02 02:42 UTC, keepmovingljzy commented
@lsvih 发布完成 https://juejin.cn/post/6924489699641786375

2021-02-02 02:43 UTC, lsvih commented
收到