揭开图着色算法的神秘面纱
xitu/gold-miner pull request #7946
Opened 2021-01-28 12:21 UTC by zenblo

译文翻译完成，resolve #7915

2021-01-28 15:43 UTC, PassionPenguin requested changes
有一些翻译有小小问题，如边着色翻译为边缘着色，总感觉很奇怪，不过总体还是不错哒～！🍻

2021-01-28 15:43 UTC, PassionPenguin commented on article/2021/demystify-graph-coloring-algorithms.md
> +图着色是指将特定的颜色按照特定约束条件在图中分配的问题。例如，你必须为一个图形着色，无论是顶点还是边，而且不会有两个相同的颜色相邻——没有两个相邻的顶点或边会有相同的颜色。
```suggestion
图着色是指将特定的颜色按照约束条件（相邻任意两个部分的颜色不能相同）在图中分配的问题。要进行图着色算法，你必须先为一个图形着色，要么是上色顶点或是上色图的边，并且需要保证不存在两个相邻的部分有相同的颜色 —— 没有两个相邻的顶点或边会有相同的颜色。
```

2021-01-28 15:43 UTC, PassionPenguin commented on article/2021/demystify-graph-coloring-algorithms.md
> +我偶然发现了这个算法，我在想它的目的是什么。当我更深入地研究图着色问题以及实际使用时，我意识到它在我们使用的应用程序中有着广泛的应用。本文将简要介绍这种算法和图着色实例。
```suggestion
我是在偶然间发现了这个算法，我在想它的应用上的作用是什么。当我更深入地研究图着色问题以及实际使用时，我意识到它在我们使用的应用程序中有着广泛的应用。本文将简要介绍这种算法和图着色实例。
```

2021-01-28 15:43 UTC, PassionPenguin commented on article/2021/demystify-graph-coloring-algorithms.md
> +解决图着色问题的方法有很多。你可以做[顶点着色](https://mathworld.wolfram.com/VertexColoring.html#:~:text=A%20vertex%20coloring%20is%20an,colors%20for%20a%20given%20graph.)、边缘着色和[地图着色](https://en.wikipedia.org/wiki/Map_col
```suggestion
现实中存在许多与图着色问题相关的问题，你可以使用[顶点着色](https://mathworld.wolfram.com/VertexColoring.html#:~:text=A%20vertex%20coloring%20is%20an,colors%20for%20a%20given%20graph.)、边着色或[地图着色](https://en.wikipedia.org/wiki/Map_coloring#:~:text=Map%20coloring%20is%20the%20act,different%20features%20on%20a%20map.&text=The%20second%20is%20in%20mathematics,features%20have%20the%20same%20color.)解图着色问题。在这个算法中，你可以思考各种不同类型的问题。例如，我们可以解决不同时分配彼此依赖的相同资源的问题。我们也可以解决这样的问题：为这个图上色所需的最小颜色数是多少。此外，我们可以把它变成一个回溯问题，在这个问题中我们希望找到所有可能的着色方法可以着色这个图。
```

2021-01-28 15:43 UTC, PassionPenguin commented on article/2021/demystify-graph-coloring-algorithms.md
> +我们假设这是顶点着色，我想给图形着色，这样相邻的两个顶点就不会有相同的颜色。
```suggestion
我们假设这是顶点着色问题，那么如果我想给图形着色，相邻的两个顶点将不会有相同的颜色。
```

2021-01-28 15:43 UTC, PassionPenguin commented on article/2021/demystify-graph-coloring-algorithms.md
> +接下来，开始在一个空白图的第一个顶点上色。你可以随便选一个。
```suggestion
接下来，开始在一个空白图的任意一个顶点作为第一个顶点进行上色操作。
```

2021-01-28 15:43 UTC, PassionPenguin commented on article/2021/demystify-graph-coloring-algorithms.md
> +编译器是将源代码从高级（Java、Scala）转换成机器代码的程序。这通常是分步骤进行的，最后一步是将寄存器分配给程序中最常用的值，同时将其它值放入内存。我们可以将符号寄存器（变量）建模为顶点，如果同时需要两个变量，则形成一条边。如果该图可以用 K 色进行着色，那么变量可以存储在 k 寄存器中。
```suggestion
编译器是将源代码从高级语言（Java、Scala）转换成机器代码的程序。这通常是分步骤进行的，最后一步是将寄存器分配给程序中最常用的值，同时将其它值放入内存。我们可以将符号寄存器（变量）建模为顶点，如果同时需要两个变量，则形成一条边。如果该图可以用 K 色进行着色，那么变量可以存储在 k 寄存器中。
```

2021-01-29 02:36 UTC, zenblo commented
@PassionPenguin @lsvih 感谢校对，已完成修改！

2021-02-02 03:02 UTC, PassionPenguin commented
@lsvih label给错了吧（

2021-02-02 10:03 UTC, flashhu commented
@lsvih 校对认领

2021-02-02 10:05 UTC, lsvih commented
@flashhu 好的

2021-02-02 11:34 UTC, flashhu reviewed
@zenblo 提了一些小建议，辛苦啦~
@lsvih 校对完成

2021-02-02 11:34 UTC, flashhu commented on article/2021/demystify-graph-coloring-algorithms.md
> +2. 选择顺序最接近的第一个顶点，然后分配一种颜色给顶点——我们称其为顶点 A。
选择顺序最接近的第一个顶点，然后分配一种颜色给顶点 => 选择最多入边的顶点作为第一个顶点，并为其分配颜色

2021-02-02 11:34 UTC, flashhu commented on article/2021/demystify-graph-coloring-algorithms.md
> +另一个例子是制定日程表或时间表。你想做一个考试日程安排，每个科目都有一份学生名单，每个学生都要上多节课。你要确保安排的考试不会相互冲突。在这种情况下，顶点可以是课程，如果两个课程中都有相同的学生，则两个课程之间会有边。在这种情况下，图的颜色将是安排考试所需的时隙数。因此，顶点 A 和顶点 B 上的相同颜色意味着 A 和 B 将在同一时隙中进行。
在这种情况下，图的颜色将是安排考试所需的时隙数。因此，顶点 A 和顶点 B 上的相同颜色意味着 A 和 B 将在同一时隙中进行。 => 在这种情况下，图的颜色将是安排考试所需的时间段总数。因此，顶点 A 和顶点 B 上的相同颜色意味着 A 和 B 将在同一时间段中进行。

2021-02-02 11:34 UTC, flashhu commented on article/2021/demystify-graph-coloring-algorithms.md
> +另一个例子是制定日程表或时间表。你想做一个考试日程安排，每个科目都有一份学生名单，每个学生都要上多节课。你要确保安排的考试不会相互冲突。在这种情况下，顶点可以是课程，如果两个课程中都有相同的学生，则两个课程之间会有边。在这种情况下，图的颜色将是安排考试所需的时隙数。因此，顶点 A 和顶点 B 上的相同颜色意味着 A 和 B 将在同一时隙中进行。
此行将 time slot 翻为时隙，后一行将 time slot 翻为时间段，可能需要统一一下

2021-02-02 13:38 UTC, zenblo commented
@flashhu 感谢校对！
@lsvih 完成两次校对

2021-02-02 13:45 UTC, lsvih approved these changes

2021-02-02 13:46 UTC, merged

2021-02-02 13:47 UTC, lsvih commented
@zenblo  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-02-02 14:14 UTC, zenblo commented
@PassionPenguin @flashhu @lsvih 掘金文章发布地址  https://juejin.cn/post/6924668410416791566/

2021-02-02 14:32 UTC, lsvih commented
收到