为什么你应该使用 Picture 标签而不是 Img 标签
xitu/gold-miner pull request #7948
Opened 2021-01-30 06:15 UTC by plusmultiply0

译文翻译完成，resolve #7923

2021-01-30 08:42 UTC, Usualminds commented
@lsvih 校对认领

2021-01-30 08:44 UTC, lsvih commented
@Usualminds 好的

2021-01-31 00:47 UTC, PassionPenguin commented
校对认领：）

2021-01-31 01:48 UTC, PassionPenguin requested changes
Excellent Translation 🍻

2021-01-31 01:48 UTC, PassionPenguin commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +选择 `picture` 或者 `img` 标签就是这么一个小细节，但是如果你做出了正确的选择，那么就可以同时提升用户体验和应用性能。
这里上下文倒是没有转折（，如果承接上文的转折可能不需要加 但是 可能两个上下文都更通顺吧

```suggestion
选择 `picture` 或者 `img` 标签就是这么一个小细节，如果你做出了正确的选择，那么就可以同时提升用户体验和应用性能。
```

2021-01-31 01:48 UTC, PassionPenguin commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +2. 艺术指导（Art Direction）——如何为不同尺寸的屏幕显示不同的图片。
```suggestion
2. 艺术指导（Art Direction）—— 如何为不同尺寸的屏幕显示不同的图片。
```

话说这个艺术指导感觉好别扭（

2021-01-31 01:48 UTC, PassionPenguin commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +1. 分辨率切换（Resolution Switching）——如何为窄屏设备提供较小尺寸的图片。
```suggestion
1. 分辨率切换（Resolution Switching）—— 如何为窄屏设备提供较小尺寸的图片。
```

2021-01-31 01:48 UTC, PassionPenguin commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +> **当 Chrome 声明其浏览器开发者工具（DevTools）将会在渲染选项卡（Rendering）中提供两种新的模拟方式以模拟部分支持的图像类型时，有关 picture 标签的事情开始变得有趣起来了。**
```suggestion
> **当 Chrome 声明其浏览器开发者工具（DevTools）将会在渲染选项卡（Rendering）中提供两种新的模拟方式以模拟部分支持的图像类型时，有关 `picture` 标签的事情开始变得有趣起来了。**
```

2021-01-31 06:57 UTC, Usualminds reviewed
@lsvih 校对完成
@plusmultiply0 翻译的不错，提了几个建议，特别需要留意的是
**Art Direction** 为专有名词，应翻译为**美术设计**，全局多处使用了艺术指导，需要修改

2021-01-31 06:57 UTC, Usualminds commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +现代 web 应用程序中，在用户界面中使用大量图片和动画是一件很常见的事情。这些现代设计聚焦于提升应用的用户体验，但是如果没有做好设备对图片的响应式支持，则可能适得其反。
则可能适得其反 => 其效果可能适得其反

2021-01-31 06:57 UTC, Usualminds commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +作为开发者，我们需要完成所有的需求。但是，在大多数情况下，我们可能会错过一些能产生巨大改变的细节，因为我们以一个更高的视角来解决问题。
产生巨大改变 => 产生巨大影响

2021-01-31 06:57 UTC, Usualminds commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +作为开发者，我们需要完成所有的需求。但是，在大多数情况下，我们可能会错过一些能产生巨大改变的细节，因为我们以一个更高的视角来解决问题。
因为我们以一个更高的视角来解决问题 => 因为我们**需要**以一个更高的视角来解决问题
NOTE: 这里因果关系似乎不妥

2021-01-31 06:57 UTC, Usualminds commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +选择 `picture` 或者 `img` 标签就是这么一个小细节，但是如果你做出了正确的选择，那么就可以同时提升用户体验和应用性能。
或者 => 还是

2021-01-31 06:57 UTC, Usualminds commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +众所周知，`img` 标签在很长的一段的时期内都是 HTML 的核心标签之一，这毫无疑问是因为它的简单和易用性。
简单和易用性 => 简单和易用

2021-01-31 06:57 UTC, Usualminds commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +2. 艺术指导（Art Direction）——如何为不同尺寸的屏幕显示不同的图片。
艺术指导 => 美术设计
[Art Direction](https://baike.baidu.com/item/ART%20DIRECTION) 此处应该为专有名词

2021-01-31 06:57 UTC, Usualminds commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +现在，让我们来看看如何解决这些问题并了解下 `picture` 标签的额外功能。
让我们来看看如何解决这些问题并了解下 `picture` 标签的额外功能
=>
让我们来看看如何解决上述问题，顺便了解下 `picture` 标签的其他功能。

NOTE：额外功能建议修改为其他功能

2021-01-31 06:57 UTC, Usualminds commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +正如我先前提到的，现代的 web 设计师经常使用高分辨率的图像来吸引用户的注意力。但是作为开发者，我们必须谨慎的选择合适的 HTML 元素。
谨慎的 => 谨慎地

2021-01-31 06:57 UTC, Usualminds commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +> **假设你对高分辨率图片使用了 `img` 标签。在这种情况下，相同的图片会被使用在运行了该应用程序的每个设备上，并且会影响低分辨率设备（如：移动设备）的性能。**
相同的图片会被使用在运行了该应用程序的每个设备上
=>
相同的图片会在运行了该应用程序的每个设备上应用

2021-01-31 06:57 UTC, Usualminds commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +艺术指导背后的主要思想是，基于设备的屏幕尺寸显示不同的图片。在大多数情况下，一张在大屏设备上看起来极好的图，会在当你切换到移动设备时被裁剪或者看起来很小。
一张在大屏设备上看起来极好的图 =>
 一张在大屏设备上看起来**漂亮极了的图片**
or
 一张在大屏设备上看起来**很棒的图片**

2021-01-31 06:57 UTC, Usualminds commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +> **我们可以通过为不同的屏幕尺寸提供不同的图片来解决这个问题。这些不同的图片可以是横向的、纵向的、或者同一图像的任意自定义版本。**
我们可以通过为不同的屏幕尺寸提供不同的图片来解决这个问题
=> 
我们可以通过为不同的屏幕尺寸提供不同**版本**的图片来解决这个问题
versions 没有翻译

2021-01-31 06:57 UTC, Usualminds commented on article/2021/why-you-should-use-picture-tag-instead-of-img-tag.md
> +如果我们能明智的使用 `srcset` 和 `sizes` 等属性，我们就能最大限度的用好 `img` 标签。比如，我们能仅使用 `img` 标签来实现分辨率切换。
明智的 => 有效的 or 有选择性的

2021-01-31 07:58 UTC, plusmultiply0 commented
@Usualminds @PassionPenguin 感谢校对:smiley:，已根据校对意见初步修改
@PassionPenguin 中文里破折号前后应该不需要添加空格——[破折号](https://baike.baidu.com/item/%E7%A0%B4%E6%8A%98%E5%8F%B7)

2021-01-31 08:03 UTC, PassionPenguin commented
> @Usualminds @PassionPenguin 感谢校对😃，已根据校对意见初步修改
> @PassionPenguin 中文里破折号前后应该不需要添加空格——[破折号](https://baike.baidu.com/item/%E7%A0%B4%E6%8A%98%E5%8F%B7)

https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E7%A0%B4%E6%8A%98%E5%8F%B7%E5%89%8D%E5%90%8E%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E4%B8%80%E4%B8%AA%E7%A9%BA%E6%A0%BC

2021-01-31 08:07 UTC, PassionPenguin approved these changes

2021-01-31 08:07 UTC, plusmultiply0 commented
> > @Usualminds @PassionPenguin 感谢校对😃，已根据校对意见初步修改
> > @PassionPenguin 中文里破折号前后应该不需要添加空格——[破折号](https://baike.baidu.com/item/%E7%A0%B4%E6%8A%98%E5%8F%B7)
> 
> [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E7%A0%B4%E6%8A%98%E5%8F%B7%E5%89%8D%E5%90%8E%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E4%B8%80%E4%B8%AA%E7%A9%BA%E6%A0%BC) ：）🍻

已修改

2021-01-31 08:33 UTC, lsvih approved these changes

2021-01-31 08:33 UTC, merged

2021-01-31 08:33 UTC, lsvih commented
@plusmultiply0  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-01-31 08:49 UTC, plusmultiply0 commented
@lsvih 已发布 https://juejin.cn/post/6923840549170446343/