掌握这 5 个 TypeScript 高级技巧，成为更好的开发者
xitu/gold-miner pull request #7949
Opened 2021-01-30 08:39 UTC by Usualminds

译文翻译完成，resolve #7878

2021-01-31 00:48 UTC, PassionPenguin commented
校对认领：）

2021-01-31 02:42 UTC, PassionPenguin requested changes
注意一下格式嗷：）

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +Typescript 是一门神奇的语言———相比 JavaScript 可以实现的所有功能，它只用十分之一的调试时间就可以完成，主要包括以下几点：
```suggestion
Typescript 是一门神奇的语言 —— 相比 JavaScript 可以实现的所有功能，它只用十分之一的调试时间就可以完成，主要包括以下几点：
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +API 调用一般是 typescript 类型错误的入口——其结果通常会像下面这样被强制转换:
```suggestion
API 调用一般是 TypeScript 错误的出处 —— 我们通常会将 API 调用的返回结果像下面这样强制转换:
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
>  const myApiResult = await callApi("url.com/endpoint") as any
AnyScript哈哈哈哈哈

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +这两种方法都会导致编译器关闭，但是第一种方法明显比第二种方法的健壮性更高——事实上，第二种方法处理的返回结果和 JavaScript 没什么区别。
```suggestion
这两种方法都会导致编译器崩溃无语，但是第一种方法明显比第二种方法的更好 —— 事实上，第二种方法处理的返回结果和 JavaScript 没什么区别。
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +我们可以使用 TS 的类型保护来处理以上问题:
```suggestion
我们可以使用 TypeScript 的类型保护来处理以上问题:
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> + `is` 操作符的一般含义是: `value is type` 实际上是一个布尔值，当输入 true 时，意味着告知 typescript 返回值类型确实是我们期望的类型。
```suggestion
 `is` 操作符的一般含义是: `value is type` 实际上是一个布尔值，当输入 `true` 时，意味着告诉了 TypeScript 返回值的类型确实是我们期望的类型。
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +t.myProperty = "bye" //编译错误, myProperty 是只读属性.
```suggestion
t.myProperty = "bye" // 编译错误, myProperty 是只读属性.
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +Typescript 支持在类型声明后加上 `as const`，这样我们就相当于给每个属性添加 readonly。
```suggestion
TypeScript 支持在类型声明后加上 `as const`，这样我们就相当于给每个属性添加 `readonly`。
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +做一个小提示，如果你只想进行类型声明，而不想让其属性只读，你可以这样做: type MyTypeReadonly = Readonly\<MyType> 。我们将会在后面的第 5 点更深入地讨论这个问题。
```suggestion
做一个小提示，如果你只想进行类型声明，而不想让其属性只读，你可以这样做: `type MyTypeReadonly = Readonly<MyType> `。我们将会在后面的第 5 点更深入地讨论这个问题。
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +许多语言解决这个问题的方法是：必须有明确 switch 和 case 场景，或者显式声明一个的、 `default` 状态。Typescript 编译器不支持这种情况，但我们可以这样创建 switch case: 如果我们扩展了枚举（enum）或其他可能的值，我们的程序就不会编译，直到我们显式地处理了这种情况。
```suggestion
许多语言解决这个问题的方法是：必须有明确 Switch 和 Case 场景，或者显式声明一个的、 `default` 状态。TypeScript 编译器不支持这种情况，但我们可以这样创建 `switch case`: 如果我们扩展了枚举（enum）或其他可能的值，我们的程序就不会编译，直到我们显式地处理了这种情况。
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +扩展枚举（enum）通常是一件叫人头疼的事情，因为我们需要在所有使用枚举的地方都添加新的 case。如果我们忘记了其中某一个跳转条件，我们的程序就会跳转到默认情况 (如果有的话) 或者失败，这可能会导致出乎意料的问题。
```suggestion
扩展枚举（enum）通常是一件叫人头疼的事情，因为我们需要在所有使用枚举的地方都添加新的 Case。如果我们忘记了其中某一个跳转条件，我们的程序就会跳转到默认情况 (如果有的话) 或者失败，这可能会导致出乎意料的问题。
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +假设两年后，另一个开发人员决定添加一个新的方向: Forward 。现在，枚举（enum）看起来是这样的:
```suggestion
假设两年后，另一个开发人员决定添加一个新的方向：向前走。现在，枚举（enum）看起来是这样的:
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +程序里的 switch case 知道这一点，但它**不在乎**。它会很自然地尝试打开 `goingTowards` ，如果它遇到 forward，它也会很自然地出错。两年是很长的一段时间，开发者忘记了之前都在哪里使用了 switch case 代码。对此，我们可以添加一个针对默认值的异常处理，让其在编译时抛出异常，这样总比运行时错误好。
```suggestion
程序里的 `switch case` 知道这一点，但它**不在乎**。它会很自然地尝试打开 `goingTowards` ，如果它遇到向前走的这样一个数据，它也会很自然地出错。两年是很长的一段时间，开发者忘记了之前都在哪里使用了 `switch case` 代码。对此，我们可以添加一个针对默认值的异常处理，让其在编译时抛出异常，这样总比运行时错误好。
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +如果我们处理了 “Forward” 这个情况，那么一切都正常。如果我们不这样做，那么我们的程序将无法编译！( `throw` 这一行是可选的，我这样做只是为了关闭 eslint 对未使用变量的校验报错)
```suggestion
如果我们处理了 `Forward` 这个情况，那么一切都正常。如果我们不这样做，那么我们的程序将无法编译！( `throw` 这一行是可选的，我这样做只是为了关闭 eslint 对未使用变量的校验报错)
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +许多使用过其他语言的开发者都会认为 null === undefined，事实并非如此（不用担心，这个技巧会变得更好）
```suggestion
许多使用过其他语言的开发者都会认为 `null === undefined`，事实并非如此（不用担心，这个技巧会变得更好）
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +Undefined 是可以通过 JS 赋值的——例如，如果我们有一个文本框，它没有输入值，那它就是 Undefined。可以把 undefined 看作是 JS 的一个自动触发的空值。
```suggestion
`undefined` 是可以通过 JavaScript 赋值的——例如，如果我们有一个文本框，它没有输入值，那它就是 `undefined`。可以把 `undefined` 看作是 JavaScript 的一个自动触发的空值。
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +我们通常很难判断一个字段是设计里本来就没有，还是无意中留下的。如果我专门为一个字段设置默认值，我会用 null。这样，每个人都知道这个字段是专门置空的。
```suggestion
我们通常很难判断一个字段是设计里本来就没有，还是无意中留下的。如果我专门为一个字段设置默认值，我会用 `null`。这样，每个人都知道这个字段是专门置空的。
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +属性 bar 以问好结尾，意味着这个字段可能是 undefined，因此 `let baz: Foo = {}` 会通过编译（另外, `let baz: Foo = {bar: null} ` 也能通过编译）。然而开发者无法通过上述代码知道我是故意让 bar 取空值还是无意的。 一个更好表述我声明意图的示例如下:
```suggestion
属性 `bar` 以问号结尾，意味着这个字段可能是 `undefined`，因此 `let baz: Foo = {}` 会通过编译（另外, `let baz: Foo = {bar: null} ` 也能通过编译）。然而开发者无法通过上述代码知道我是故意让 `bar` 取空值还是无意的。 一个更好表述我声明意图的示例如下:
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +现在，我必须 **明确地声明 bar 的取值为 null。** 我的意图不会被混淆 — bar 没有明确的取值。
```suggestion
现在，我必须 **明确地声明 `bar` 的取值为 `null`。** 我的意图不会被混淆 —— `bar` 没有明确的取值。
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +如果真是这样的话，先不用惊慌。你正在按照预期使用 TS:那就是类型安全。但是，如果你没有利用 TS 的内置类型，那你可能写了太多的重复代码。下面是 [你至少应该知道存在的内建类型的链接](https://www.typescriptlang.org/docs/handbook/utility-types.html)，以便你可以在代码中使用。
```suggestion
如果真是这样的话，先不用惊慌。你正在按照预期使用 TypeScript：那就是类型安全。但是，如果你没有利用 TypeScript 的内置类型，那你可能写了太多的重复代码。下面是 [你至少应该知道存在的内建类型的链接](https://www.typescriptlang.org/docs/handbook/utility-types.html)，以便你可以在代码中使用。
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +从接口声明中移除具有 ? 属性的值。
```suggestion
从接口声明中移除具有 `?` 属性的值。
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +关于 TS，我要说的就这么多了！如果你在任何地方发现了错误，请告诉我，这样我可以在其他人学到错误知识之前修复它。如果你认为我遗漏了什么知识点，也请让告诉我！
```suggestion
关于 TypeScript，我要说的就这么多了！如果你在任何地方发现了错误，请告诉我，这样我可以在其他人学到错误知识之前修复它。如果你认为我遗漏了什么知识点，也请让告诉我！
```

2021-01-31 02:42 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +创建一个新类型，不包含 null / undefined 属性。如果我们正在增加或填写一些数据，这是很有用的，可以保证它是有值的。
```suggestion
创建一个新类型，不包含 `null` / `undefined` 属性。如果我们正在增加或填写一些数据，这是很有用的，可以保证它是有值的。
```

2021-01-31 02:59 UTC, zenblo commented
@lsvih 校对认领

2021-01-31 03:00 UTC, lsvih commented
@zenblo 好的

2021-01-31 07:21 UTC, Usualminds commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
>  const myApiResult = await callApi("url.com/endpoint") as any
typescript any = JavaScript，哈哈

2021-01-31 07:39 UTC, Usualminds commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +假设两年后，另一个开发人员决定添加一个新的方向: Forward 。现在，枚举（enum）看起来是这样的:
这里我专门保留了Forward 没有翻译，原因是上面的代码里已经存在，翻译会让读者无法对应上下文，通用方法也是保留英文字段

2021-01-31 07:42 UTC, Usualminds commented
> 注意一下格式嗷：）

@PassionPenguin 感谢校对，相关意见已合入，文章比较长，哈哈

2021-01-31 07:46 UTC, PassionPenguin commented
> > 注意一下格式嗷：）
> 
> @PassionPenguin 感谢校对，相关意见已合入，文章比较长，哈哈

话说你可以 Create batch from suggestions 然后一次性 submit 多条 suggestion：）

2021-01-31 08:10 UTC, PassionPenguin requested changes
Typo

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +API 调用一般是 TypeScript 错误的出处 —— 我们通常会将 API 调用的返回结果像下面这样强制转换:
```suggestion
API 调用一般是 TypeScript 错误的出处 —— 我们通常会将 API 调用的返回结果像下面这样强制转换：
```

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +我们可以使用 TS 的类型保护来处理以上问题:
```suggestion
我们可以使用 TS 的类型保护来处理以上问题：
```

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +`is` 操作符的一般含义是: `value is type` 实际上是一个布尔值，当输入 `true` 时，意味着告诉了 TypeScript 返回值的类型确实是我们所期望的类型。
```suggestion
`is` 操作符的一般含义是： `value is type` 实际上是一个布尔值，当输入 `true` 时，意味着告诉了 TypeScript 返回值的类型确实是我们所期望的类型。
```

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +我认为对我们最有帮助的场景与之前一样——不同的是，在这里我们不是返回一个接口，而是想通过代理的方法修改 API 对象中的部分属性，使其成为一个数据对象，所以，结合前面的技巧:
```suggestion
我认为对我们最有帮助的场景与之前一样 —— 不同的是，在这里我们不是返回一个接口，而是想通过代理的方法修改 API 对象中的部分属性，使其成为一个数据对象，所以，结合前面的技巧：
```

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +做一个小提示，如果你只想进行类型声明，而不想让其属性只读，你可以这样做: `type MyTypeReadonly = Readonly<MyType>` 。我们将会在后面的第 5 点更深入地讨论这个问题。
```suggestion
做一个小提示，如果你只想进行类型声明，而不想让其属性只读，你可以这样做：`type MyTypeReadonly = Readonly<MyType>` 。我们将会在后面的第 5 点更深入地讨论这个问题。
```

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +许多语言解决这个问题的方法是：必须有明确 Switch 和 Case 场景，或者显式声明一个的、 `default` 状态。Typescript 编译器不支持这种情况，但我们可以这样创建 `switch case`: 如果我们扩展了枚举（enum）或其他可能的值，我们的程序就不会编译，直到我们显式地处理了这种情况。
```suggestion
许多语言解决这个问题的方法是：必须有明确 Switch 和 Case 场景，或者显式声明一个的、 `default` 状态。Typescript 编译器不支持这种情况，但我们可以这样创建 `switch case`：如果我们扩展了枚举（enum）或其他可能的值，我们的程序就不会编译，直到我们显式地处理了这种情况。
```

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +假设两年后，另一个开发人员决定添加一个新的方向: Forward 。现在，枚举（enum）看起来是这样的:
```suggestion
假设两年后，另一个开发人员决定添加一个新的方向：Forward 。现在，枚举（enum）看起来是这样的：
```

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +所以我们可以添加默认情况如下:
```suggestion
所以我们可以添加默认情况如下：
```

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +属性 `bar` 以问号结尾，意味着这个字段可能是 `undefined`，因此 `let baz: Foo = {}` 会通过编译（另外, `let baz: Foo = {bar: null} ` 也能通过编译）。然而开发者无法通过上述代码知道我是故意让 `bar` 取空值还是无意的。 一个更好表述我声明意图的示例如下:
```suggestion
属性 `bar` 以问号结尾，意味着这个字段可能是 `undefined`，因此 `let baz: Foo = {}` 会通过编译（另外, `let baz: Foo = {bar: null} ` 也能通过编译）。然而开发者无法通过上述代码知道我是故意让 `bar` 取空值还是无意的。 一个更好表述我声明意图的示例如下：
```

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +这不仅适用于接口声明 —— 我还会在函数不返回任何内容时使用它。这在编译时很有帮助:
```suggestion
这不仅适用于接口声明 —— 我还会在函数不返回任何内容时使用它。这在编译时很有帮助：
```

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +如果真是这样的话，先不用惊慌。你正在按照预期使用 TS:那就是类型安全。但是，如果你没有利用 TS 的内置类型，那你可能写了太多的重复代码。下面是 [你至少应该知道存在的内建类型的链接](https://www.typescriptlang.org/docs/handbook/utility-types.html)，以便你可以在代码中使用。
```suggestion
如果真是这样的话，先不用惊慌。你正在按照预期使用 TS：那就是类型安全。但是，如果你没有利用 TS 的内置类型，那你可能写了太多的重复代码。下面是 [你至少应该知道存在的内建类型的链接](https://www.typescriptlang.org/docs/handbook/utility-types.html)，以便你可以在代码中使用。
```

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +Swagger 极大地帮助我们了解后端可以提供什么样的服务——但是，通常情况下，开发者往往会得到和约定不一致的 API，其中某些 API 属性可能存在，也可能不存在，或者是根据状态返回不同的对象。
```suggestion
Swagger 极大地帮助我们了解后端可以提供什么样的服务 —— 但是，通常情况下，开发者往往会得到和约定不一致的 API，其中某些 API 属性可能存在，也可能不存在，或者是根据状态返回不同的对象。
```

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +使用这个方法的开发者想必都会喜出望外———它不仅可以识别返回值类型（来自 `response ` 的类型变量），而且数据还是不可变的（immutable）。当我们调用 API 时，可以通过这个简单的方法验证返回值是否符合我们的期望。这对每个开发者而言都是一种进步！
```suggestion
使用这个方法的开发者想必都会喜出望外 —— 它不仅可以识别返回值类型（来自 `response` 的类型变量），而且数据还是不可变的（immutable）。当我们调用 API 时，可以通过这个简单的方法验证返回值是否符合我们的期望。这对每个开发者而言都是一种进步！
```

2021-01-31 08:10 UTC, PassionPenguin commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +`undefined` 是可以通过 JavaScript 赋值的——例如，如果我们有一个文本框，它没有输入值，那它就是 `undefined`。可以把 `undefined` 看作是 JavaScript 的一个自动触发的空值。
```suggestion
`undefined` 是可以通过 JavaScript 赋值的 —— 例如，如果我们有一个文本框，它没有输入值，那它就是 `undefined`。可以把 `undefined` 看作是 JavaScript 的一个自动触发的空值。
```

2021-01-31 08:46 UTC, PassionPenguin commented
Checklist：中文前后英文字符、中文前后数字字符、破折号前后空格，其他仍在摸索中

<table>
 <tr>
  <td>([a-z])([\u4100-\u9fa5](?![\uff00-\uffef]))</td>
  <td>No Matches</td>
 </tr>
 <tr>
  <td>([\u4100-\u9fa5](?![\uff00-\uffef]))([a-z])</td>
  <td>No Matches</td>
 </tr>
 <tr>
  <td>([\u4100-\u9fa5](?![\uff00-\uffef]))(\d)</td>
  <td>No matches</td>
 </tr>
 <tr>
  <td>(\d)([\u4100-\u9fa5](?![\uff00-\uffef]))</td>
  <td>No matches</td>
 </tr>
 <tr>
  <td rowspan="5">(?!\s)——(?!\s)</td>
  <td>4 Matches</td>
 </tr>
 <tr>
  <td>Line 1013-1015</td>
 </tr>
 <tr>
  <td>Line 2867-2869</td>
 </tr>
 <tr>
  <td>Line 3290-3292</td>
 </tr>
 <tr>
  <td>Line 4899-4901</td>
 </tr>
</table>

2021-01-31 10:06 UTC, Usualminds commented
> Checklist：中文前后英文字符、中文前后数字字符、破折号前后空格，其他仍在摸索中
> 
> ([a-z])([\u4100-\u9fa5](?![\uff00-\uffef]))	No Matches
> ([\u4100-\u9fa5](?![\uff00-\uffef]))([a-z])	No Matches
> ([\u4100-\u9fa5](?![\uff00-\uffef]))(\d)	No matches
> (\d)([\u4100-\u9fa5](?![\uff00-\uffef]))	No matches
> (?!\s)——(?!\s)	4 Matches
> Line 1013-1015
> Line 2867-2869
> Line 3290-3292
> Line 4899-4901

2021-01-31 10:07 UTC, Usualminds commented
> Checklist：中文前后英文字符、中文前后数字字符、破折号前后空格，其他仍在摸索中
> 
> ([a-z])([\u4100-\u9fa5](?![\uff00-\uffef]))	No Matches
> ([\u4100-\u9fa5](?![\uff00-\uffef]))([a-z])	No Matches
> ([\u4100-\u9fa5](?![\uff00-\uffef]))(\d)	No matches
> (\d)([\u4100-\u9fa5](?![\uff00-\uffef]))	No matches
> (?!\s)——(?!\s)	4 Matches
> Line 1013-1015
> Line 2867-2869
> Line 3290-3292
> Line 4899-4901

优秀啊，哈哈，这个用起来，我看看还有其他的正则不，然后写个脚本处理一下

2021-01-31 10:11 UTC, PassionPenguin commented
> > Checklist：中文前后英文字符、中文前后数字字符、破折号前后空格，其他仍在摸索中
> > ([a-z])([\u4100-\u9fa5](?!%5B%5Cuff00-%5Cuffef%5D))	No Matches
> > ([\u4100-\u9fa5](?!%5B%5Cuff00-%5Cuffef%5D))([a-z])	No Matches
> > ([\u4100-\u9fa5](?!%5B%5Cuff00-%5Cuffef%5D))(\d)	No matches
> > (\d)([\u4100-\u9fa5](?!%5B%5Cuff00-%5Cuffef%5D))	No matches
> > (?!\s)——(?!\s)	4 Matches
> > Line 1013-1015
> > Line 2867-2869
> > Line 3290-3292
> > Line 4899-4901
> 
> 优秀啊，哈哈，这个用起来，我看看还有其他的正则不，然后写个脚本处理一下

其实理论上可以判断更多内容的（，就是挺麻烦

你可以用一下这个lint：https://github.com/lint-md/lint-md

2021-01-31 10:19 UTC, lsvih commented
咋 close 了。。

2021-01-31 10:22 UTC, PassionPenguin commented
话说没必要Close啊，你可以 convert to draft 啊（

2021-01-31 10:22 UTC, Usualminds commented
误操作了，乌龙了

2021-01-31 10:53 UTC, PassionPenguin approved these changes

2021-01-31 11:55 UTC, Usualminds commented
> > > Checklist：中文前后英文字符、中文前后数字字符、破折号前后空格，其他仍在摸索中
> > > ([a-z])([\u4100-\u9fa5](?!%5B%5Cuff00-%5Cuffef%5D))	No Matches
> > > ([\u4100-\u9fa5](?!%5B%5Cuff00-%5Cuffef%5D))([a-z])	No Matches
> > > ([\u4100-\u9fa5](?!%5B%5Cuff00-%5Cuffef%5D))(\d)	No matches
> > > (\d)([\u4100-\u9fa5](?!%5B%5Cuff00-%5Cuffef%5D))	No matches
> > > (?!\s)——(?!\s)	4 Matches
> > > Line 1013-1015
> > > Line 2867-2869
> > > Line 3290-3292
> > > Line 4899-4901
> > 
> > 
> > 优秀啊，哈哈，这个用起来，我看看还有其他的正则不，然后写个脚本处理一下
> 
> 其实理论上可以判断更多内容的（，就是挺麻烦
> 
> 你可以用一下这个lint：https://github.com/lint-md/lint-md



> Checklist：中文前后英文字符、中文前后数字字符、破折号前后空格，其他仍在摸索中
> 
> ([a-z])([\u4100-\u9fa5](?![\uff00-\uffef]))	No Matches
> ([\u4100-\u9fa5](?![\uff00-\uffef]))([a-z])	No Matches
> ([\u4100-\u9fa5](?![\uff00-\uffef]))(\d)	No matches
> (\d)([\u4100-\u9fa5](?![\uff00-\uffef]))	No matches
> (?!\s)——(?!\s)	4 Matches
> Line 1013-1015
> Line 2867-2869
> Line 3290-3292
> Line 4899-4901



> > > Checklist：中文前后英文字符、中文前后数字字符、破折号前后空格，其他仍在摸索中
> > > ([a-z])([\u4100-\u9fa5](?!%5B%5Cuff00-%5Cuffef%5D))	No Matches
> > > ([\u4100-\u9fa5](?!%5B%5Cuff00-%5Cuffef%5D))([a-z])	No Matches
> > > ([\u4100-\u9fa5](?!%5B%5Cuff00-%5Cuffef%5D))(\d)	No matches
> > > (\d)([\u4100-\u9fa5](?!%5B%5Cuff00-%5Cuffef%5D))	No matches
> > > (?!\s)——(?!\s)	4 Matches
> > > Line 1013-1015
> > > Line 2867-2869
> > > Line 3290-3292
> > > Line 4899-4901
> > 
> > 
> > 优秀啊，哈哈，这个用起来，我看看还有其他的正则不，然后写个脚本处理一下
> 
> 其实理论上可以判断更多内容的（，就是挺麻烦
> 
> 你可以用一下这个lint：https://github.com/lint-md/lint-md

可以的，我用了一下，后面再结合排版指南扩展下规则，基本可以规避翻译里面的格式问题了
https://github.com/Usualminds/translation/blob/main/.lintmdrc

2021-01-31 12:01 UTC, zenblo commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +如果真是这样的话，先不用惊慌。你正在按照预期使用 TS：那就是类型安全。但是，如果你没有利用 TS 的内置类型，那你可能写了太多的重复代码。下面是 [你至少应该知道存在的内建类型的链接](https://www.typescriptlang.org/docs/handbook/utility-types.html)，以便你可以在代码中使用。
下面是 [你至少应该知道存在的内建类型的链接](https://www.typescriptlang.org/docs/handbook/utility-types.html)，以便你可以在代码中使用。
=>如下所示是[你至少应该知道存在的内建类型](https://www.typescriptlang.org/docs/handbook/utility-types.html)，以便你可以在代码中使用。

2021-01-31 12:02 UTC, zenblo commented
@Usualminds @lsvih 校对完成，提了一点小建议

2021-01-31 14:33 UTC, Usualminds commented on article/2021/5-advanced-typescript-tips-to-make-you-a-better-programmer.md
> +API 调用一般是 TypeScript 错误的出处 —— 我们通常会将 API 调用的返回结果像下面这样强制转换：
这个还是采用原翻译

2021-01-31 14:43 UTC, Usualminds commented
@zenblo 感谢校对，已合入
@lsvih 已完成合入相关校对意见

2021-02-01 02:39 UTC, lsvih approved these changes

2021-02-01 02:39 UTC, merged

2021-02-01 02:40 UTC, lsvih commented
@Usualminds  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-02-01 13:57 UTC, Usualminds commented
@lsvih https://juejin.cn/post/6924293152907984909

2021-02-02 01:17 UTC, lsvih commented
收到