如何在浏览器上使用 NoSQL 数据库 IndexedDB
xitu/gold-miner pull request #7982
Opened 2021-02-04 03:40 UTC by zenblo

译文翻译完成，resolve #id

2021-02-04 04:11 UTC, PassionPenguin requested changes
：）

2021-02-04 04:11 UTC, PassionPenguin commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +* 虽然现代浏览器支持 IndexedDB，但是 IE 等浏览器却没有完全支持。
```suggestion
* 虽然现代浏览器支持 IndexedDB，但是 IE 等浏览器却没有完全支持。
```

2021-02-04 04:11 UTC, PassionPenguin commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +* Firefox 在无痕浏览模式下完全禁用 IndexedDB —— 通过隐身窗口访问时，可能导致应用程序出现故障。
```suggestion
* IndexedDB 在 Firefox 的无痕浏览模式下是完全禁用的 —— 通过隐身窗口访问应用程序时，接口无法使用可能导致应用程序出现故障。
```

2021-02-04 04:12 UTC, PassionPenguin commented
### TODO：
- [ ] 后续给翻译一下图片

2021-02-04 04:39 UTC, zenblo commented
@PassionPenguin 感谢校对！
@lsvih 完成 1 次校对

2021-02-04 04:40 UTC, zenblo commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +> 来源：[developers.google.com](https://developers.google.com/web/ilt/pwa/working-with-indexeddb)
链接是 .com

2021-02-04 05:02 UTC, PassionPenguin commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +> 来源：[developers.google.com](https://developers.google.com/web/ilt/pwa/working-with-indexeddb)
是的没问题，但针对译文，加上这个也是 Google Developer 的网站，可以大陆访问的

2021-02-04 05:03 UTC, PassionPenguin commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +> 来源：[developers.google.com](https://developers.google.com/web/ilt/pwa/working-with-indexeddb)
在基于无法访问的网页有替代措施加上又是官方维护的页面的情况下当然可以选择给能访问的网页啦：）

就例如 flutter.dev => flutter.cn / flutter-io.cn

2021-02-04 05:04 UTC, PassionPenguin commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +> 来源：[developers.google.com](https://developers.google.com/web/ilt/pwa/working-with-indexeddb)
在基于无法访问的网页有替代措施加上又是官方维护的页面的情况下当然可以选择给能访问的网页啦：）

* flutter.dev => flutter.cn / flutter-io.cn
* developer.android.com => developer.android.google.cn

2021-02-04 05:04 UTC, PassionPenguin commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +> 来源：[developers.google.com](https://developers.google.com/web/ilt/pwa/working-with-indexeddb)
在基于无法访问的网页有替代措施加上又是官方维护的页面的情况下当然可以选择给能访问的网页啦：）

* flutter.dev => flutter.cn / flutter-io.cn
* developer.android.com => developer.android.google.cn

2021-02-18 16:18 UTC, Chorer commented
校对认领

2021-02-18 16:37 UTC, Chorer reviewed
校对完毕

2021-02-18 16:37 UTC, Chorer commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +在本文中，我们将重点介绍以下内容。
```suggestion
在本文中，我们将重点介绍以下内容：
```

2021-02-18 16:37 UTC, Chorer commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +IndexedDB 存储不同数据类型的灵活性更高。不仅是字符串类型，还包括二进制数据（`ArrayBuffer` 对象、`Blob` 对象等）。而 IndexedDB 在内部使用对象存储来保存数据。
```suggestion
IndexedDB 存储不同数据类型的灵活性更高。支持的数据类型不仅包括字符串类型，还包括二进制数据（`ArrayBuffer` 对象、`Blob` 对象等）。而 IndexedDB 在内部使用对象存储来保存数据。
```

缺少主语。

2021-02-18 16:37 UTC, Chorer commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +通过为频繁使用的用户存储应用程序状态，可以大幅提高应用程序的性能，让应用程序可以在后续与后端服务器同步，并通过延迟加载来更新应用程序。
```suggestion
通过为频繁使用的用户存储应用程序状态，可以大幅提高应用程序的性能，让应用程序可以在后续与后端服务器同步，并通过懒加载来更新应用程序。
```

2021-02-18 16:37 UTC, Chorer commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +只要开启数据库连接，就可以在 `onsuccess` 事件处理程序中管理数据。插入数据分 4 步进行。
```suggestion
只要开启数据库连接，就可以在 `onsuccess` 事件处理程序中管理数据。插入数据分四步进行。
```

2021-02-18 16:37 UTC, Chorer commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +    // 创建新的 transaction
```suggestion
    // 创建新的事务
```

2021-02-18 16:37 UTC, Chorer commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +可以在 IndexedDB 上执行很多操作。包括如下所示：
```suggestion
可以在 IndexedDB 上执行很多操作。包括下面这些：
```

2021-02-18 16:37 UTC, Chorer commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +如果你需要关于如何实现上述操作的资料，请在下方评论部分告诉我。你也可以参考[这里](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB)获得更多信息。
```suggestion
如果你需要关于如何实现上述操作的资料，请在下方评论区告诉我。你也可以参考[这里](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB)获得更多信息。
```

2021-02-18 16:37 UTC, Chorer commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +到目前为止，IndexedDB 似乎很有希望用于客户端存储。然而，值得注意的局限是很少的。
```suggestion
到目前为止，IndexedDB 似乎很有希望用于客户端存储。然而，有几个限制值得注意。
```

2021-02-18 16:37 UTC, Chorer commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
> +考虑到 IndexedDB 提供的诸多特性，这个价值百万的问题答案可能是 Yes！然而，在得出结论之前，先问自己以下几个问题。
```suggestion
考虑到 IndexedDB 提供的诸多特性，这个百万美元问题（译者注：指至关重要的问题）答案可能是 Yes！然而，在得出结论之前，先问自己以下几个问题。
```
million-dollar question  means a question that is very important and/or difficult to answer. million-dollar question 有个译名是百万美元问题，指的是很重要或者很难回答的问题，最好是括弧说明一下。

2021-02-18 16:59 UTC, PassionPenguin approved these changes
哈喽 @zenblo

2021-02-18 16:59 UTC, PassionPenguin commented on article/2021/how-to-use-indexeddb-a-nosql-db-on-the-browser.md
>  ![](https://cdn-images-1.medium.com/max/3544/1*ttpz7RUwKhTJYmfmE5VQ0g.png)
```suggestion
![](https://raw.githubusercontent.com/PassionPenguin/gold-miner-images/master/how-to-use-indexeddb-a-nosql-db-on-the-browser-summary.png)
```

2021-02-19 00:55 UTC, zenblo commented
@Chorer @PassionPenguin 感谢校对！已完成修改。
@lsvih 完成 2 次校对

2021-02-19 07:35 UTC, zenblo commented
@lsvih 帮忙看一下这篇~

2021-02-19 07:49 UTC, lsvih approved these changes

2021-02-19 07:50 UTC, merged

2021-02-19 07:50 UTC, lsvih commented
@zenblo  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-02-19 08:10 UTC, zenblo commented
@PassionPenguin @Chorer @lsvih 掘金文章发布地址  https://juejin.cn/post/6930883284456964109/