2021 年 JavaScript 的前景
xitu/gold-miner pull request #7984
Opened 2021-02-04 08:26 UTC by regon-cao

译文翻译完成，resolve #7935

2021-02-04 09:32 UTC, PassionPenguin commented
Hello，欢迎查看一下这篇 Gist 嗷：），这样你的主仓库就可以与稀土的主仓库保持一致啦，省去这么长一串 Merge Pull 啦：）

https://gist.github.com/glennblock/1974465

```zsh
git fetch upstream
git reset --hard upstream/master
```

2021-02-04 09:32 UTC, PassionPenguin commented
校对认领：）

2021-02-05 13:25 UTC, PassionPenguin requested changes
翻译的好奇怪，缺主缺宾缺状缺定，建议稍微口语化一下全文，现在有一股很浓烈的机器味 ψ(｀∇´)ψ

可以参考我们翻译的文章（本文的数据源）：https://github.com/xitu/Annual-Survey/pull/5

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +web 开发领域的变化很快，但我们能确定 2021 年 web 会带来什么。通过仔细研究 2020 年开发者调查的数据，我重点挑出了 JavaScript 的大变化。
```suggestion
Web 开发领域的迭代更新很快，但我们能确定 2021 年 Web 会带来什么新的变化。通过仔细研究 2020 年开发者调查的数据，我挑出了 JavaScript 的可能的巨大变化。
```

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +在深入讨论细节之前，先简要介绍一下 JavaScript 调查。遗憾的是，优秀的[前端工具调查](https://ashleynolan.co.uk/blog/frontend-tooling-survey-2019-results)的下一版在一段时间内不会发布，这使得寻找趋势变得有点困难。当我们在为寻找一个好的调查发愁时，新的调查[前端状态](https://tsh.io/state-of-f
```suggestion
在深入讨论细节之前，先简要介绍一下 JavaScript 调查。遗憾的是，这份优秀的[前端工具调查](https://ashleynolan.co.uk/blog/frontend-tooling-survey-2019-results)的下一版在一段时间内不会发布，这使得寻找趋势变得有点困难。当我们在为寻找一个好的调查发愁时，新的这份 [2020 年前端状态](https://github.com/xitu/Annual-Survey/blob/main/2020/frontend/State-of-Frontend-2020-by-TSH.pdf) 突然出现了。虽然没有之前的年度数据帮助我们了解趋势, 但是它是由来自世界各地的 4500 名开发者填写的，所以它绝对能够算上是一个有价值的参考资料。
```

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +让我们深入探索我从数据中获得的见解。
```suggestion
让我们深入了解我从数据中获得的一些看法。
```

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +[去年](https://medium.com/engineered-publicis-sapient/the-javascript-landscape-in-2020-b8e5898b847e) 我曾建议关注下 [PNPM](https://pnpm.js.org/) 的崛起， 它旨在避免版本冲突，并与 monorepos 一起搭配的很好。它拥有一批[热情的支持者](https://mediu
```suggestion
[去年](https://medium.com/engineered-publicis-sapient/the-javascript-landscape-in-2020-b8e5898b847e) 我曾建议关注下 [PNPM](https://pnpm.js.org/) 的崛起，一款旨在避免版本冲突并能够很好地与 monorepos 一起搭配使用的包管理器。它拥有一大群[热情的支持者](https://medium.com/better-programming/the-case-for-pnpm-over-npm-or-yarn-2b221607119)，去年它在 Github 上共获得了 9.5k 星，显然赢得了开发者的支持。但是，考虑到 [Yarn](https://yarnpkg.com/) 和 [NPM](https://www.npmjs.com/) 在实际项目中的集成程度和它们为发布新特性投入的精力，其中一些特性是直接针对 PNPM 开发的，尤其是 [Workspaces](https://classic.yarnpkg.com/en/docs/workspaces/)，我觉得 PNPM 不太可能在 2021 年[在使用数量上能与它们竞争](https://www.npmtrends.com/yarn-vs-pnpm-vs-npm)。这正好说明了竞争在推动开源软件向前发展是多么重要。
```

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +2019 年，[Cypress](https://www.cypress.io/) 和 [Puppeteer](https://github.com/puppeteer/puppeteer) 脱颖而出，成为了高质量的新作品，它们都在 2020 年继续获得了成功。然而，微软新的端到端测试工具 [Playwright](https://github.com/microsoft/playwright)
```suggestion
2019 年，[Cypress](https://www.cypress.io/) 和 [Puppeteer](https://github.com/puppeteer/puppeteer) 脱颖而出，成为了高质量的新，它们都在 2020 年继续获得了成功。然而，微软的新的端到端测试工具 [Playwright](https://github.com/microsoft/playwright) 横空出世，仅在 2020 年就获得了不到 2 万颗星。作为世界上最大的软件公司之一，他们有能力来大范围推广自己的产品，但这只是工具流行的部分原因。主要原因还是它的特征集以及能方便地从 [Puppeteer](https://pptr.dev/) 迁移过来的特性。
```

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
>  ![Playright tops the Rising Stars testing frameworks chart despite not having featured at all in 2019](https://cdn-images-1.medium.com/max/2000/1*uYLDgxsDdacIUtiOnAWTFw.png)
翻译 alt 嗷ψ(｀∇´)ψ

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +自从 [Nadella](https://en.wikipedia.org/wiki/Satya_Nadella) 担任首席执行官以来，微软就养成了生产流行且强大的开源工具的习惯。[VSCode 或者别的](https://2020.stateofjs.com/en-US/other-tools/#text_editors)？
```suggestion
自从 [Nadella](https://en.wikipedia.org/wiki/Satya_Nadella) 担任首席执行官以来，微软就养成了生产流行且强大的开源工具的习惯。例如 [VSCode 或者别的其他的开源项目](https://2020.stateofjs.com/en-US/other-tools/#text_editors)？
```

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +我去年说过 [TypeScript](https://www.typescriptlang.org/) 已经缓慢地接管了 JavaScript 世界，这一趋势正在加剧。无数的开源项目都急切地将其列为受支持的特性。[2020 年收获星星最多的 Github 项目](https://risingstars.js.org/2020/en#section-all) [Deno](https://deno
```suggestion
我去年说过 [TypeScript](https://www.typescriptlang.org/) 已经缓慢地接管了 JavaScript 世界，这一趋势正在加剧。无数的开源项目都急切地将其列为受支持的特性。[2020 年收获星星最多的 Github 项目](https://risingstars.js.org/2020/en#section-all) [Deno](https://deno.land/) 就内置了 Typescript 编译器。
```

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +去年我建议关注 [PureScript](http://www.purescript.org/)，它强制使用静态类型和函数式编程。但是，在 2020 年它的使用率并没有那么高，在 Github 上只新增了 641 颗星星，[感兴趣度减少了 3%](https://2020.stateofjs.com/en-US/technologies/javascript-flavors/)。看一下 Type
```suggestion
去年我曾建议大家去关注 [PureScript](http://www.purescript.org/) 项目，一款强制使用静态类型和函数式编程的语言。但是，在 2020 年它的使用率并没有那么高，在 Github 上只新增了 641 颗星星，[感兴趣度减少了 3%](https://2020.stateofjs.com/en-US/technologies/javascript-flavors/)。看一下 TypeScript 和它的竞争者之间 [在使用率方面的巨大差距](https://www.npmtrends.com/typescript-vs-elm-vs-coffee-script-vs-purescript-vs-reason)，感觉语言的战争已经结束，微软的产品已经胜出。在社区经过多年的深思熟虑和语言过多的氛围中，任何新的语言都很难引起我们的注意。
```

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
>  ![React downloads in the past year](https://cdn-images-1.medium.com/max/2332/1*PJFyaoF6Bz3AKmt9Npzx6w.png)
alt ：）

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +还有两个有用的指标：GitHub 上的标签和招聘广告。目前 Github 上超过了 80k 仓库标记了 React，而 Vue 只有 25k。纵观就业市场，去年 5 月 Career Karma 在 Indeed.com 上公布了 [10005](https://www.decise.com/q-React-Developer-jobs.html？vjk=2873485b3446c4bc）个 R
【React 无处不在，并且正在经受一些激烈的竞争。】好别扭

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +纵观全栈框架的激增，在这一领域正进行着一场非常重要的心灵之战，因为它们对体系结构、性能和工作方式有着巨大的影响。两个基于 React 的框架，[NextJS](https://nextjs.org/) 还有 [Gatsby](https://www.gatsbyjs.com/)，在使用方面仍然比 VueJS 的同类产品更受欢迎，但这只印证了我们早已对 UI 框架生态系统的了解。真正值得注意的是
【在这一领域正进行着一场非常重要的心灵之战】等内容好奇怪

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +> 这篇文章是由 George Adamson 和 Joanne Parkes 友善地审查。
```suggestion
> 这篇文章是由 George Adamson 和 Joanne Parkes 助力提供了校对。
```

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +在语言特性、浏览器支持、运行时的快速发展和不断扩大的数字化范围影响下，JavaScript 的前景越来越好。
```suggestion
在语言特性、浏览器支持、运行时的快速发展和不断扩大的数字化范围影响下，我坚信 JavaScript 的前景越来越好。
```

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +受到 [JAMStack](https://jamstack.org/) 模式和对速度需求的影响，静态站点生成器和 ESbuild 等工具迅速崛起。
```suggestion
受到 [JAMStack](https://jamstack.org/) 模式和对速度需求的影响，静态站点生成器和 ESbuild 等工具正在迅速崛起。
```

2021-02-05 13:25 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +从 2020 年的数据中得出的关键主题是，大型软件供应商正在决定 JavaScript 的生态。微软的 TypeScript 正在成为一个行业标准，基于它的项目有更好的成功机会，NestJS 和 NextJS（不要混淆）就是很好的例子。
```suggestion
从 2020 年的数据中我们可以得到的关键内容是，大型软件供应商正在决定 JavaScript 的生态。微软的 TypeScript 正在成为一个行业标准，基于它的项目有更好的成功机会，NestJS 和 NextJS（不要混淆）就是很好的例子。
```

2021-02-20 07:02 UTC, Chorer commented
校对认领

2021-02-20 09:23 UTC, Chorer reviewed
@lsvih 校对完毕
文章的翻译难度确实有点大，但总体来说翻译得不错。提几个建议：
1. 还是那个一直以来存在的问题，做翻译的时候缺乏考证，很多东西查找平行文本是可以找出答案的。以这一句为例： because they’re attracted to its opinionated approach，翻译成了“他们被它固执己见的方法所吸引”，虽然 opinionated 常见的意思确实是固执己见，但很显然这里不可能是这个意思。联想到作者可能在说 Next 框架的某个特点，可以以关键词 opinionated + Nextjs 进行搜索，结合一些文章看看就能理解这里的意思，指的其实是框架的规范性、约束性。
2. 适当代入读者视角。DX 这个词可能不像 UX UI 这些词那么常见，为了防止有读者不理解 DX 的意思，应该考虑做适当的译者批注。其实只要翻译成开发体验/开发者体验，大部分读者应该也都能明白是什么意思了，就无需点击链接跳转到相关文章。
3. 另外有一些地方的翻译我感觉可能要几个人一起讨论一下。比如 github 的 star 是否翻译为星星，可能大家更熟悉的是 star 这种叫法，这种情况下是否保留不翻译是更加合适的做法呢？包括另一位校对者指出的图片的 alt，这个是否进行翻译也是个老生常谈的问题。

2021-02-20 09:23 UTC, Chorer commented on article/2021/the-javascript-landscape-in-2021.md
> +没有状态管理，什么样的 UI 框架才算是完整的解决方案呢? 撇开关于复杂性和未来验证的争论不谈，这个领域特别有趣，因为 Redux 正受到来自 React 内部和外来者的双重挑战。
```suggestion
没有状态管理，UI 框架还能算是完整的解决方案吗？撇开关于复杂性和未来验证的争论不谈，这个领域特别有趣，因为 Redux 正受到来自 React 内部和外来者的双重挑战。
```

2021-02-20 09:23 UTC, Chorer commented on article/2021/the-javascript-landscape-in-2021.md
> +从个人经验来说 React 的钩子和上下文 API 的确很强大，但它们都有其局限性。不管怎样，他们肯定是 React 开发者的大热门，拥有[几乎一半的前端参与者](https://tsh.io/state of frontend/#frameworks/框架)都说了使用过它们。
```suggestion
从个人经验来说，React 的钩子和上下文 API 的确很强大，但它们都有其局限性。不管怎样，他们肯定在 React 开发者中广受青睐，毕竟[几乎一半的前端状态调查的参与者](https://tsh.io/state of frontend/#frameworks/)都声称使用过它们。
```
1. 这里的 hook 和 Context api 不翻译是否更好？
2. half the State of Front End participants，这里的 State of Front End 要翻译出来。并不是前端参与者的一半，而是前端状态调查的参与者的一半。

2021-02-20 09:23 UTC, Chorer commented on article/2021/the-javascript-landscape-in-2021.md
> +从 2020 年的数据中得出的关键主题是，大型软件供应商正在决定 JavaScript 的生态。微软的 TypeScript 正在成为一个行业标准，基于它的项目有更好的成功机会，NestJS 和 NextJS（不要混淆）就是很好的例子。
```suggestion
从 2020 年的数据中我们可以得到的关键内容是，大型软件供应商正在决定 JavaScript 的生态。微软的 TypeScript 正在成为一个行业标准，基于它的项目有更大的机会获得成功，NestJS 和 NextJS（不要混淆）就是很好的例子。
```

2021-02-20 09:23 UTC, Chorer commented on article/2021/the-javascript-landscape-in-2021.md
> +> 这篇文章是由 George Adamson 和 Joanne Parkes 友善地审查。
```suggestion
> 本文由 George Adamson 和 Joanne Parkes 助力提供校对。
```

2021-02-21 00:51 UTC, Ivocin commented on article/2021/the-javascript-landscape-in-2021.md
> +自从 [Nadella](https://en.wikipedia.org/wiki/Satya_Nadella) 担任首席执行官以来，微软就养成了生产流行且强大的开源工具的习惯。[VSCode 或者别的](https://2020.stateofjs.com/en-US/other-tools/#text_editors)？
> [VSCode 或者别的](https://2020.stateofjs.com/en-US/other-tools/#text_editors)？
> =>
> 有人用过 [VSCode](https://2020.stateofjs.com/en-US/other-tools/#text_editors) 吗？
> 
> 这里的 VSCode anyone 应该是表达类似于 Does anyone use VSCode? 的意思

看起来的意思是 VS Code 就在其中

2021-02-21 00:53 UTC, Ivocin commented on article/2021/the-javascript-landscape-in-2021.md
> +还有两个有用的指标：GitHub 上的标签和招聘广告。目前 Github 上超过了 80k 仓库标记了 React，而 Vue 只有 25k。纵观就业市场，去年 5 月 Career Karma 在 Indeed.com 上公布了 [10005](https://www.decise.com/q-React-Developer-jobs.html？vjk=2873485b3446c4bc）个 R
> 【React 无处不在，并且正在经受一些激烈的竞争。】好别扭

并且竞争激烈。

2021-02-21 01:00 UTC, Ivocin commented
> @regon-cao @lsvih 校对完毕
> 文章的翻译难度确实有点大，但总体来说翻译得不错。提几个建议：
> 
> 1. 还是那个一直以来存在的问题，做翻译的时候缺乏考证，很多东西查找平行文本是可以找出答案的。以这一句为例： because they’re attracted to its opinionated approach，翻译成了“他们被它固执己见的方法所吸引”，虽然 opinionated 常见的意思确实是固执己见，但很显然这里不可能是这个意思。联想到作者可能在说 Next 框架的某个特点，可以以关键词 opinionated + Nextjs 进行搜索，结合一些文章看看就能理解这里的意思，指的其实是框架的规范性、约束性。
> 2. 适当代入读者视角。DX 这个词可能不像 UX UI 这些词那么常见，为了防止有读者不理解 DX 的意思，应该考虑做适当的译者批注。其实只要翻译成开发体验/开发者体验，大部分读者应该也都能明白是什么意思了，就无需点击链接跳转到相关文章。
> 3. 另外有一些地方的翻译我感觉可能要几个人一起讨论一下。比如 github 的 star 是否翻译为星星，可能大家更熟悉的是 star 这种叫法，这种情况下是否保留不翻译是更加合适的做法呢？包括另一位校对者指出的图片的 alt，这个是否进行翻译也是个老生常谈的问题。

我最近也在纠结 opinionated 的译法，很多的工具都宣称自己是 opinionated 的，如 Prettier，Vitejs 等，意思确实是固执己见哪个意思，但又不是贬义的，译为“有主见的”好像有少了那味儿，有点纠结。

2021-02-21 03:30 UTC, Chorer commented on article/2021/the-javascript-landscape-in-2021.md
> +自从 [Nadella](https://en.wikipedia.org/wiki/Satya_Nadella) 担任首席执行官以来，微软就养成了生产流行且强大的开源工具的习惯。[VSCode 或者别的](https://2020.stateofjs.com/en-US/other-tools/#text_editors)？
> > [VSCode 或者别的](https://2020.stateofjs.com/en-US/other-tools/#text_editors)？
> > =>
> > 有人用过 [VSCode](https://2020.stateofjs.com/en-US/other-tools/#text_editors) 吗？
> > 这里的 VSCode anyone 应该是表达类似于 Does anyone use VSCode? 的意思
> 
> 看起来的意思是 VS Code 就在其中

这样的话你可以根据你理解的这个意思微调一下，因为单独的这句“VSCode 或者别的”听起来还是怪怪的

2021-02-21 03:36 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +web 开发领域的变化很快，但我们能确定 2021 年 web 会带来什么。通过仔细研究 2020 年开发者调查的数据，我重点挑出了 JavaScript 的大变化。
Web 还是该大写吧，毕竟中文里面出个英文，又是小写，有些突兀（

2021-02-21 03:36 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +自从 [Nadella](https://en.wikipedia.org/wiki/Satya_Nadella) 担任首席执行官以来，微软就养成了生产流行且强大的开源工具的习惯。[VSCode 或者别的](https://2020.stateofjs.com/en-US/other-tools/#text_editors)？
的确，vscode anyone 乍听起来就是，“嘿有木有人用过 VSCode 啊？？”，

如果理解为  “VSCode 或者别的软件” 那其实也能够说得过去不过

2021-02-21 03:36 UTC, PassionPenguin commented on article/2021/the-javascript-landscape-in-2021.md
> +还有两个有用的指标：GitHub 上的标签和招聘广告。目前 Github 上超过了 80k 仓库标记了 React，而 Vue 只有 25k。纵观就业市场，去年 5 月 Career Karma 在 Indeed.com 上公布了 [10005](https://www.decise.com/q-React-Developer-jobs.html？vjk=2873485b3446c4bc）个 R
```suggestion
还有两个有用的指标：GitHub 上的标签和招聘广告。目前 Github 上有超过 80k 个仓库带有 React 标签，而 Vue 只有 25k。纵观就业市场，去年 5 月 Career Karma 在 Indeed.com 上公布了 [10005](https://www.decise.com/q-React-Developer-jobs.html?vjk=2873485b3446c4bc）个在美 React 开发者职位，而 Vue 只有 [1025](https://www.decise.com/q-Vue-Js-Developer-jobs.html?vjk=9216260d28c3fda3）个。 React 无处不在，并且竞争激烈。
```

2021-02-21 03:37 UTC, PassionPenguin commented
> > @regon-cao @lsvih 校对完毕
> > 文章的翻译难度确实有点大，但总体来说翻译得不错。提几个建议：
> > 
> > 1. 还是那个一直以来存在的问题，做翻译的时候缺乏考证，很多东西查找平行文本是可以找出答案的。以这一句为例： because they’re attracted to its opinionated approach，翻译成了“他们被它固执己见的方法所吸引”，虽然 opinionated 常见的意思确实是固执己见，但很显然这里不可能是这个意思。联想到作者可能在说 Next 框架的某个特点，可以以关键词 opinionated + Nextjs 进行搜索，结合一些文章看看就能理解这里的意思，指的其实是框架的规范性、约束性。
> > 2. 适当代入读者视角。DX 这个词可能不像 UX UI 这些词那么常见，为了防止有读者不理解 DX 的意思，应该考虑做适当的译者批注。其实只要翻译成开发体验/开发者体验，大部分读者应该也都能明白是什么意思了，就无需点击链接跳转到相关文章。
> > 3. 另外有一些地方的翻译我感觉可能要几个人一起讨论一下。比如 github 的 star 是否翻译为星星，可能大家更熟悉的是 star 这种叫法，这种情况下是否保留不翻译是更加合适的做法呢？包括另一位校对者指出的图片的 alt，这个是否进行翻译也是个老生常谈的问题。
> 
> 我最近也在纠结 opinionated 的译法，很多的工具都宣称自己是 opinionated 的，如 Prettier，Vitejs 等，意思确实是固执己见哪个意思，但又不是贬义的，译为“有主见的”好像有少了那味儿，有点纠结。

独成一派 独树一帜（不对这个太偏了

2021-02-21 04:21 UTC, Chorer commented
> > @regon-cao @lsvih 校对完毕
> > 文章的翻译难度确实有点大，但总体来说翻译得不错。提几个建议：
> > 
> > 1. 还是那个一直以来存在的问题，做翻译的时候缺乏考证，很多东西查找平行文本是可以找出答案的。以这一句为例： because they’re attracted to its opinionated approach，翻译成了“他们被它固执己见的方法所吸引”，虽然 opinionated 常见的意思确实是固执己见，但很显然这里不可能是这个意思。联想到作者可能在说 Next 框架的某个特点，可以以关键词 opinionated + Nextjs 进行搜索，结合一些文章看看就能理解这里的意思，指的其实是框架的规范性、约束性。
> > 2. 适当代入读者视角。DX 这个词可能不像 UX UI 这些词那么常见，为了防止有读者不理解 DX 的意思，应该考虑做适当的译者批注。其实只要翻译成开发体验/开发者体验，大部分读者应该也都能明白是什么意思了，就无需点击链接跳转到相关文章。
> > 3. 另外有一些地方的翻译我感觉可能要几个人一起讨论一下。比如 github 的 star 是否翻译为星星，可能大家更熟悉的是 star 这种叫法，这种情况下是否保留不翻译是更加合适的做法呢？包括另一位校对者指出的图片的 alt，这个是否进行翻译也是个老生常谈的问题。
> 
> 我最近也在纠结 opinionated 的译法，很多的工具都宣称自己是 opinionated 的，如 Prettier，Vitejs 等，意思确实是固执己见哪个意思，但又不是贬义的，译为“有主见的”好像有少了那味儿，有点纠结。

我个人的看法是这样的：
**1. **抛开固执己见这个词本身，直接从 opinionated  的英文解释去理解它的意思。参考[https://www.collinsdictionary.com/dictionary/english/opinionated](opinionated)：If you describe someone as opinionated, you mean that they have very strong opinions and refuse to accept that they may be wrong. 也就是说，这个词用来形容这样的一种人：他们有非常强烈的自我的观点，并且不相信自己在这方面可能是错误的。按照这句话来理解，确实有自以为是和固执己见的意思，但同时还强调了对于自己观点的深信不疑。另外按照[这里](https://dictionary.cambridge.org/dictionary/english/opinionated)的解释，它还有一个意思是 having strong opinions that you feel free to express，对应的例句 She’s seven years old and she’s already pretty opinionated. 中文是，她虽然才七岁但已经很有主见了，这里翻译为固执己见就不合适。
**2. **如果是人的话，我们是不是可以理解为有一层“他有自己坚守的行事准则，有自己坚持的看法”的意思呢？而如果是放在软件开发领域，就可以延伸理解为某个框架/软件是有自己的一套规范/约束的，不管你认不认可这套规范/约束，你必须默认它就是正确的，并且必须按照它的规范/约束来进行开发，即 do things their way。
**3.** 按照这个理解，以 opinionated + tools 作为关键词检索相关资料（Google），可以看到两个比较热门的相关问题，实际上，关于究竟什么才算是 opinionated software/framework，国外也有过比较热烈的讨论，那么我们就看他们普遍认为的 opinionated 的定义就好了。
第一个来自于[StackOverflow](https://stackoverflow.com/questions/802050/what-is-opinionated-software)：
"If a framework is opinionated, it lock or guides you into their way of doing things."
如果某个框架是 opinionated 的，那么它会要求或引导你按照它们的方式进行开发。后面也给出了相关例子，比如模板系统限制了对于用户自定义方法的访问权限，仅允许对于基本数据结构的访问，又比如苹果对自己的产品也有一套严格约束的标准；而对于 un-opinionated，回答者也举了 PERL 和 PHP 的例子，它们对开发者给予了充分的信任，并因此给了极大的开发自由度，简单地说就是“你放手去做就好了”，再比如 .NET 的公共语言运行时，这也是一种开放（与约束相对的）程度的体现。
第二个来自于[Quora]()的回答：
“All frameworks make some assumptions about best practices for application architecture to some degree. When these assumptions are strong (yes, that is as subjective as it looks), the framework is considered opinionated. Non-opinionated frameworks will usually not assume much beyond structure and conventions. Even then, they might not strongly enforce such rules, as often these rules are only used to enable opt-in framework features”
任何框架都会在某种程度（或大或小）上假定应用架构的最佳实践，当这种程度非常深的时候，则可以认为这个框架是 opinionated 的。而 un-opinionated 的框架通常不会在这方面进行过多的假定，甚至不会强迫开发者去遵循这些规定。其实这和上面说的还是差不多的意思，也就是 opinionated 的框架会假定一个自己认为的最佳实践，并在此基础上制定规则，让开发者去遵守，说到底还是**有规范的、有约束性的**。

经过这些解释，你应该能对 opinionated 有进一步的理解了，当然你还可以考证其它资料，将 opinionated 的意思更为精确地进行提炼，但个人认为在这篇文章中，翻译为“规范性/约束性的框架”是相对比较准确的。一定不要被“固执己见”这个词套进去了，要在软件开发的情境下去理解这个词的含义。

2021-02-21 04:28 UTC, Chorer commented
@lsvih = =另外问一下，现在是有三个校对者吗？机器人罢工后现在的 tag 似乎没有及时移除，issue 显示的还是认领校对的状态。

2021-02-21 04:57 UTC, lsvih commented
@Chorer 两位呀= = 我只改了 pr 的 label，issue 的校对 label 在机器人挂后一直都没有改了（懒）

2021-02-21 05:20 UTC, Chorer commented
> @Chorer 两位呀= = 我只改了 pr 的 label，issue 的校对 label 在机器人挂后一直都没有改了（懒）

噢噢，看错了 = =

2021-02-21 06:04 UTC, Ivocin commented
> > > @regon-cao @lsvih 校对完毕
> > > 文章的翻译难度确实有点大，但总体来说翻译得不错。提几个建议：
> > > 
> > > 1. 还是那个一直以来存在的问题，做翻译的时候缺乏考证，很多东西查找平行文本是可以找出答案的。以这一句为例： because they’re attracted to its opinionated approach，翻译成了“他们被它固执己见的方法所吸引”，虽然 opinionated 常见的意思确实是固执己见，但很显然这里不可能是这个意思。联想到作者可能在说 Next 框架的某个特点，可以以关键词 opinionated + Nextjs 进行搜索，结合一些文章看看就能理解这里的意思，指的其实是框架的规范性、约束性。
> > > 2. 适当代入读者视角。DX 这个词可能不像 UX UI 这些词那么常见，为了防止有读者不理解 DX 的意思，应该考虑做适当的译者批注。其实只要翻译成开发体验/开发者体验，大部分读者应该也都能明白是什么意思了，就无需点击链接跳转到相关文章。
> > > 3. 另外有一些地方的翻译我感觉可能要几个人一起讨论一下。比如 github 的 star 是否翻译为星星，可能大家更熟悉的是 star 这种叫法，这种情况下是否保留不翻译是更加合适的做法呢？包括另一位校对者指出的图片的 alt，这个是否进行翻译也是个老生常谈的问题。
> > 
> > 
> > 我最近也在纠结 opinionated 的译法，很多的工具都宣称自己是 opinionated 的，如 Prettier，Vitejs 等，意思确实是固执己见哪个意思，但又不是贬义的，译为“有主见的”好像有少了那味儿，有点纠结。
> 
> 光在这里猜是没有用的，还是要结合资料以及平行文本来理解。我个人的看法是这样的：
> **（1）** . 抛开固执己见这个词本身，直接从 opinionated 的英文解释去理解它的意思。参考[https://www.collinsdictionary.com/dictionary/english/opinionated](opinionated)：If you describe someone as opinionated, you mean that they have very strong opinions and refuse to accept that they may be wrong. 也就是说，这个词用来形容这样的一种人：他们有非常强烈的自我的观点，并且不相信自己在这方面可能是错误的。按照这句话来理解，确实有自以为是和固执己见的意思，但同时还强调了对于自己观点的深信不疑。另外按照[这里](https://dictionary.cambridge.org/dictionary/english/opinionated)的解释，它还有一个意思是 having strong opinions that you feel free to express，对应的例句 She’s seven years old and she’s already pretty opinionated. 中文是，她虽然才七岁但已经很有主见了，这里翻译为固执己见就不合适。
> **（2）** .如果是人的话，我们是不是可以理解为有一层“他有自己坚守的行事准则，有自己坚持的看法”的意思呢？而如果是放在软件开发领域，就可以延伸理解为某个框架/软件是有自己的一套规范/约束的，不管你认不认可这套规范/约束，你必须默认它就是正确的，并且必须按照它的规范/约束来进行开发，即 do things their way。
> **（3）** .按照这个理解，以 opinionated + tools 作为关键词检索相关资料（Google），可以看到两个比较热门的相关问题，实际上，关于究竟什么才算是 opinionated software/framework，国外也有过比较热烈的讨论，那么我们就看他们普遍认为的 opinionated 的定义就好了。
> 
> 第一个来自于[StackOverflow](https://stackoverflow.com/questions/802050/what-is-opinionated-software)：
> "If a framework is opinionated, it lock or guides you into their way of doing things."
> 如果某个框架是 opinionated 的，那么它会要求或引导你按照它们的方式进行开发。后面也给出了相关例子，比如模板系统限制了对于用户自定义方法的访问权限，仅允许对于基本数据结构的访问，又比如苹果对自己的产品也有一套严格约束的标准；而对于 un-opinionated，回答者也举了 PERL 和 PHP 的例子，它们对开发者给予了充分的信任，并因此给了极大的开发自由度，简单地说就是“你放手去做就好了”，再比如 .NET 的公共语言运行时，这也是一种开放（与约束相对的）程度的体现。
> 
> 第二个来自于Quora的回答：
> “All frameworks make some assumptions about best practices for application architecture to some degree. When these assumptions are strong (yes, that is as subjective as it looks), the framework is considered opinionated. Non-opinionated frameworks will usually not assume much beyond structure and conventions. Even then, they might not strongly enforce such rules, as often these rules are only used to enable opt-in framework features”
> 任何框架都会在某种程度（或大或小）上假定应用架构的最佳实践，当这种程度非常深的时候，则可以认为这个框架是 opinionated 的。而 un-opinionated 的框架通常不会在这方面进行过多的假定，甚至不会强迫开发者去遵循这些规定。其实这和上面说的还是差不多的意思，也就是 opinionated 的框架会假定一个自己认为的最佳实践，并在此基础上制定规则，让开发者去遵守，说到底还是**有规范的、有约束性的**。
> 
> 经过这些解释，你应该能对 opinionated 有进一步的理解了，当然你还可以考证其它资料，将 opinionated 的意思更为精确地进行提炼，但个人认为在这篇文章中，翻译为“规范性/约束性的框架”是相对比较准确的。一定不要被“固执己见”这个词套进去了，要在软件开发的情境下去理解这个词的含义。

很经常的分析，赞啊

2021-02-21 06:05 UTC, Ivocin commented
> @lsvih = =另外问一下，现在是有三个校对者吗？机器人罢工后现在的 tag 似乎没有及时移除，issue 显示的还是认领校对的状态。

哈哈，我只是路过，有一年多没来参与翻译计划了。

2021-02-21 06:06 UTC, Chorer commented
> > @lsvih = =另外问一下，现在是有三个校对者吗？机器人罢工后现在的 tag 似乎没有及时移除，issue 显示的还是认领校对的状态。
> 
> 哈哈，我只是路过，有一年多没来参与翻译计划了。

我看错了，以为是译者 hah

2022-05-05 13:50 UTC, jaredliw commented
@lsvih 这篇还有继续的必要吗？需要的话我接手了

2022-05-06 01:56 UTC, Chorer commented
这都2022年了，这篇文章还屯在这。。。所以译者接手这个翻译之后是干什么去了呢？

2022-05-08 15:08 UTC, jaredliw commented
> 这都2022年了，这篇文章还屯在这。。。所以译者接手这个翻译之后是干什么去了呢？

接着校对然后发出去呗

2022-05-09 03:10 UTC, Chorer commented
> > 这都2022年了，这篇文章还屯在这。。。所以译者接手这个翻译之后是干什么去了呢？
> 
> 接着校对然后发出去呗

校对早就结束了，译者没有修改而已

2022-06-16 13:07 UTC, closed without merging