How to Implement a GraphQL API on Top of an Existing REST API
xitu/gold-miner pull request #7988
Opened 2021-02-05 02:14 UTC by samyu2000

resolve #7972

2021-02-16 02:41 UTC, k8scat commented
校对认领

2021-02-17 05:56 UTC, k8scat reviewed
@samyu2000 @lsvih

2021-02-17 05:56 UTC, k8scat commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +虽然 dad joke 数据库是完全虚拟的项目，但几乎所有的在 2015 年 GraphQL 发布会之前成立的科技公司都发现：是时候转向 GraphQL 了，而且实际上它们也在做这些工作。另外，还有个好消息，Apollo Server 属于较灵活的产品，它也可以从包括 REST API 端点在内的各种数据源获取数据。
『虽然 dad joke 数据库是完全虚拟的项目，但几乎所有的在 2015 年 GraphQL 发布会之前成立的科技公司都发现：是时候转向 GraphQL 了，而且实际上它们也在做这些工作。另外，还有个好消息，Apollo Server 属于较灵活的产品，它也可以从包括 REST API 端点在内的各种数据源获取数据。』=>『虽然我们的 dad joke 数据库完全是虚构的，但几乎所有在 GraphQL 于2015年发布之前存在的技术公司都会发现，如果他们选择迁移到 GraphQL，他们也会发现自己处于同样的位置。好消息是，Apollo Server 足够灵活，可以从各种来源（包括现有的 REST API 端点）提取数据。』

2021-02-17 05:56 UTC, k8scat reviewed
@samyu2000 @lsvih

2021-02-17 07:01 UTC, lsvih commented
@k8scat 感谢校对！

2021-02-17 12:53 UTC, PassionPenguin requested changes
@lsvih @samyu2000  ψ(｀∇´)ψ

2021-02-17 12:53 UTC, PassionPenguin commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +最近你了解到一种新技术，它叫做 GraphQL，它具有一定的灵活性，可以精准获取你需要的数据，而且是使用单一的 API 结点。它很整洁，于是你打算在应用程序中使用这种技术。但是，你不希望对原有的 API 作过多的改动。能否让你的项目同时支持 REST API 和 GraphQL API？
```suggestion
最近你了解到一种新技术，叫做 GraphQL。它具有一定的灵活性，可以精准获取你需要的数据，而且只使用单一的 API 结点。听起来很不错，你打算在应用程序中使用这种技术。但是，你不希望对原有的 API 作过多的改动。能否让你的项目同时支持 REST API 和 GraphQL API呢？让我们一起找出答案吧！
```

2021-02-17 12:53 UTC, PassionPenguin commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +你的 dad jokes 放在哪儿？当然是在 **dadabase** 里。我们来想象一下，你是全世界最受欢迎的 dad jokes 数据库的管理员。项目的技术概况是：使用 REST API 与数据库通信，这种 REST API 具有搜索笑话和对笑话进行评分的功能；网站的访问者可以通过一个简单的界面对每条笑话进行评分。
意义差不多啦 ψ(｀∇´)ψ，平时我们一般也称为管理员啦

2021-02-17 12:53 UTC, PassionPenguin commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +你的 dad jokes 放在哪儿？当然是在 **dadabase** 里。我们来想象一下，你是全世界最受欢迎的 dad jokes 数据库的管理员。项目的技术概况是：使用 REST API 与数据库通信，这种 REST API 具有搜索笑话和对笑话进行评分的功能；网站的访问者可以通过一个简单的界面对每条笑话进行评分。
```suggestion
你的老爸一般存储在哪儿？当然是在 **dadabase** 里啦！让我们来想象一下，你是全世界最受欢迎的老爸笑话数据库的管理员。你的项目的技术概况是：使用 REST API 与数据库通信，这种 REST API 具有搜索笑话和对笑话进行评分的功能；网站的访问者可以通过一个简单的用户界面对每条笑话进行评分。
```

2021-02-17 12:53 UTC, PassionPenguin commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +最近你了解到一种新技术，它叫做 GraphQL，它具有一定的灵活性，可以精准获取你需要的数据，而且是使用单一的 API 结点。它很整洁，于是你打算在应用程序中使用这种技术。但是，你不希望对原有的 API 作过多的改动。能否让你的项目同时支持 REST API 和 GraphQL API？
Something you would say at times meaning "I'm sure that's cool but i don't really give a fuck right now"

哈哈哈哈这个 idiom

2021-02-17 12:53 UTC, PassionPenguin commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +在本文中，我们会讨论如何基于已有的 REST API 来实现 GraphQL API。你使用这种方法，不需要对基于原有的 REST API 框架进行调整，就可以在项目的未完成的模块中使用 GraphQL。
```suggestion
在本文中，我们会讨论如何基于已有的 REST API 来实现 GraphQL API。这个方法可以让你在应用程序的未完成部分使用 GraphQL 而不会破坏已有的任何功能性的，可能依赖于旧有 REST API 的功能。
```

2021-02-17 12:53 UTC, PassionPenguin commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +如果你想看到最终的结果，可以访问[REST API 代码](https://github.com/thawkin3/dad-joke-dadabase-rest-api) 和 [前端和 GraphQL API 代码](https://github.com/thawkin3/dad-joke-dadabase)。还要记得[浏览一下网站](https://dad-joke-dadabase.hero
```suggestion
如果你想看到最终的结果，可以访问[REST API 代码](https://github.com/thawkin3/dad-joke-dadabase-rest-api) 和 [前端和 GraphQL API 代码](https://github.com/thawkin3/dad-joke-dadabase)。别忘了要记得[浏览一下老爸笑话网](https://dad-joke-dadabase.herokuapp.com/)，毕竟那些笑话很值得看哦哈哈哈！
```

2021-02-17 12:53 UTC, PassionPenguin commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +我们做到了。我们以已有的 REST API 为基础，成功地实现了一个 GraphQL API 端点。因此，我们也能使用 GraphQL 来实现一些核心功能，而且不需要破坏已有的功能，也不需要修改原来的 REST API。如今 REST API 不是唯一选项了，将来可能被完全弃用。
```suggestion
我们做到了。我们以现有的 REST API 为基础，成功地实现了一个 GraphQL API 端点。现在我们也能使用 GraphQL 来实现一些核心功能，并且无需干扰任何已有的功能，也不需要修改原来的 REST API。如今 REST API 不是唯一选项了，我想 REST API 在将来可能被完全弃用。
```

2021-02-17 12:53 UTC, PassionPenguin commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
>  ![The Network tab shows a request is being made to the /graphql endpoint now](https://cdn-images-1.medium.com/max/2520/0*ketnaG9b4tR0O0O4.png)
记得翻译 alt

2021-02-17 12:53 UTC, PassionPenguin commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +现在，我们可以在本地运行应用程序了。实际上，从用户的角度来说，没有发生任何变化。但假如你在浏览器的开发者工具中查看网络请求，你会发现，现在获取笑话是通过访问 `/graphql` 端点来实现的了。
```suggestion
现在，我们可以在本地运行应用程序了。实际上，从用户的角度来说，没有发生任何变化。但假如你在浏览器的开发者工具中查看网络请求，你会发现，现在获取笑话是通过访问 `/graphql` 端点来实现的了，这可真棒！
```

2021-02-17 12:53 UTC, PassionPenguin commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
译者信息漏啦，以及标题

2021-02-18 03:45 UTC, samyu2000 commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +最近你了解到一种新技术，它叫做 GraphQL，它具有一定的灵活性，可以精准获取你需要的数据，而且是使用单一的 API 结点。它很整洁，于是你打算在应用程序中使用这种技术。但是，你不希望对原有的 API 作过多的改动。能否让你的项目同时支持 REST API 和 GraphQL API？
英译汉一般需要把长句分解为短句，这样符合汉语的表达

2021-02-18 05:13 UTC, k8scat commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +最近你了解到一种新技术，它叫做 GraphQL，它具有一定的灵活性，可以精准获取你需要的数据，而且是使用单一的 API 结点。它很整洁，于是你打算在应用程序中使用这种技术。但是，你不希望对原有的 API 作过多的改动。能否让你的项目同时支持 REST API 和 GraphQL API？
可能是我在精准这个词上的理解有偏差，我觉得『精准获取』可能没有体现原文的 only request the data you need，REST API 也可以精准获取数据，只是获取到的数据会含有使用者不需要的数据。

2021-02-18 06:58 UTC, lsvih commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
>  > * 校对者：
译者及校对者信息

2021-02-18 06:58 UTC, lsvih commented
@samyu2000 麻烦添加一下译者及校对者信息哈~

2021-02-18 12:44 UTC, samyu2000 commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +虽然 dad joke 数据库是完全虚拟的项目，但几乎所有的在 2015 年 GraphQL 发布会之前成立的科技公司都发现：是时候转向 GraphQL 了，而且实际上它们也在做这些工作。另外，还有个好消息，Apollo Server 属于较灵活的产品，它也可以从包括 REST API 端点在内的各种数据源获取数据。
你好！你这是直接把有道翻译的结果复制到这儿了？

2021-02-18 12:55 UTC, k8scat commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +虽然 dad joke 数据库是完全虚拟的项目，但几乎所有的在 2015 年 GraphQL 发布会之前成立的科技公司都发现：是时候转向 GraphQL 了，而且实际上它们也在做这些工作。另外，还有个好消息，Apollo Server 属于较灵活的产品，它也可以从包括 REST API 端点在内的各种数据源获取数据。
是有不通顺的地方吗？前面的翻译有严重的语法错误，可以了解下 if and when 的使用。

2021-02-18 14:07 UTC, lsvih commented
请另一位校对者 @PassionPenguin 看看 https://github.com/xitu/gold-miner/pull/7988/files#r577339755 中的讨论哈

2021-02-18 14:16 UTC, PassionPenguin commented on article/2021/how-to-implement-a-graphql-api-on-top-of-an-existing-rest-api.md
> +虽然 dad joke 数据库是完全虚拟的项目，但几乎所有的在 2015 年 GraphQL 发布会之前成立的科技公司都发现：是时候转向 GraphQL 了，而且实际上它们也在做这些工作。另外，还有个好消息，Apollo Server 属于较灵活的产品，它也可以从包括 REST API 端点在内的各种数据源获取数据。
我挺同意k8scat的（，if and when 表如果啊

> at a future time (should it arise).
> "most of these plans can be altered if and when the situation changes"

```suggestion
虽然 dad joke 数据库的转移这件事是虚构的，但几乎所有的在 2015 年 GraphQL 发布会之前成立的科技公司都在考虑转向 GraphQL 的时候发现自己也处于相同的位置。好消息是，Apollo Server 足够灵活，可以从包括 REST API 端点在内的各种数据源获取数据。
```

2021-02-18 14:17 UTC, PassionPenguin commented
> 请另一位校对者 @PassionPenguin 看看 https://github.com/xitu/gold-miner/pull/7988/files#r577339755 中的讨论哈

> at a future time (should it arise).
> "most of these plans can be altered if and when the situation changes"

（

2021-02-19 08:22 UTC, lsvih approved these changes

2021-02-19 08:22 UTC, merged

2021-02-19 08:22 UTC, lsvih commented
@samyu2000  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-02-20 06:57 UTC, samyu2000 commented
@lsvih 已发布 https://juejin.cn/post/6931145990599049223

2021-02-20 07:11 UTC, lsvih commented
收到