简述 HTTP 请求与跨域资源共享 CORS
xitu/gold-miner pull request #7989
Opened 2021-02-05 08:49 UTC by zenblo

@lsvih 译文翻译完成，resolve #7960

2021-02-05 13:08 UTC, PassionPenguin requested changes
主要还是一些不连贯以及括号英文（应该是，如果是关键内容例如表头的一些关键字就要注释，但如果是一些无关的例如脚本就可能可以删去：））

2021-02-05 13:08 UTC, PassionPenguin commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +## URL 格式
注意到其实这个部分 URL + Hostname + ... 全是 Request 的内容，这里加标题那下面也要加吧：）

2021-02-05 13:08 UTC, PassionPenguin commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +**查询参数：**
```suggestion
**Query 参数：**
```

2021-02-05 13:08 UTC, PassionPenguin commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +**路径：**
```suggestion
**路径（Path）：**
```

2021-02-05 13:08 UTC, PassionPenguin commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +**主机名：**
```suggestion
**主机名（Host）：**
```

2021-02-05 13:08 UTC, PassionPenguin commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +浏览器和服务器都需要获取对方的大量信息，才能识别对方，并最终发送请求或响应。比如 IP 地址、内容类型（Content-Type）、Cookie、[缓存控制](https://en.wikipedia.org/wiki/Cache-Control)等。你可以在这里找到[完整列表](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields)，
```suggestion
浏览器和服务器都需要获取对方的大量信息，才能识别对方，并最终发送请求或响应。比如 IP 地址、内容类型（Content-Type）、Cookie、[缓存控制（Cache-Control）](https://en.wikipedia.org/wiki/Cache-Control)等。你可以在这里找到[完整列表](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields)，它们带着**表头**数据也就是**键值对**。
```

2021-02-05 13:08 UTC, PassionPenguin commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +我想使用 JS 代码从浏览器发送另一个请求到另一个域（另一个服务器）。然而，这并不容易。出于安全原因，浏览器限制从脚本（script）发起的跨源 HTTP 请求。
```suggestion
例如我想使用 JS 代码从浏览器发送另一个请求到另一个域（另一个服务器），但你会发现这并不容易。出于安全原因，浏览器限制从脚本发起的跨源 HTTP 请求。
```

2021-02-05 13:08 UTC, PassionPenguin commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +[同源安全策略默](https://en.wikipedia.org/wiki/Same-origin_policy)默认禁止某些`跨域（cross-domain）`请求，尤其是 Ajax 请求，而始终允许`相同来源（Same-Origin）`请求。
```suggestion
[同源安全策略](https://en.wikipedia.org/wiki/Same-origin_policy)默认禁止某些`跨域（Cross-Domain）`请求，尤其是 Ajax 请求，而始终允许`相同来源（Same-Origin）`请求。
```

2021-02-05 13:08 UTC, PassionPenguin commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +> **跨域资源共享**（[CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS)）是基于 HTTP 表头的机制，它允许服务器指出浏览器应该允许加载资源的任何其他[来源](https://developer.mozilla.org/en-US/docs/Glossary/origin)（域、方案或端口）。
```suggestion
> **跨域资源共享**（[CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS)）是基于 HTTP 表头的机制，它允许服务器指出浏览器应该允许加载资源的任何其他[来源](https://developer.mozilla.org/en-US/docs/Glossary/origin)（域、协议或端口）。
```

2021-02-05 13:08 UTC, PassionPenguin commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +当浏览器发现域是不同的，它会向该服务器发送一个 **OPTIONS** 请求，检查请求是否被允许。尽管这与开发人员无关，浏览器会自动进行。然而开发人员可以在发送跨域请求之前，向请求添加一些表头，这可能有助于获得允许。
```suggestion
当浏览器发现域是不同的，它会向该服务器发送一个 **OPTIONS** 请求，检查请求是否被允许。这个行为与我们这些前端开发人员其实并没有什么关系，因为这是浏览器自动进行的行为。然而开发人员可以在发送跨域请求之前，向请求添加一些表头，这可能有助于获得允许。
```

2021-02-05 13:08 UTC, PassionPenguin commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +**Access-Control-Allow-Credentials** — 如果在响应头中为 true，则跨域请求将包含 cookie 表头。
```suggestion
**Access-Control-Allow-Credentials** — 如果在响应头中为 true，则跨域请求将包含 Cookie 表头。
```

2021-02-05 13:08 UTC, PassionPenguin commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +我试图简要说明这些重要概念，如果你有任何疑问或想在上述一个特定主题中了解更多信息，请告诉我。
```suggestion
在这篇文章中我尝试着以最简明的方法向你们介绍了这些重要的概念，而如果你有任何疑问或想在上述一个特定主题中了解更多信息，请记得告诉我喔。
```

2021-02-05 13:50 UTC, zenblo commented
@PassionPenguin 感谢校对！
@lsvih 完成 1 次校对

2021-02-05 15:33 UTC, PassionPenguin approved these changes

2021-02-05 15:33 UTC, PassionPenguin commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +**服务类型（Scheme）** 指明将被使用的协议（protocol）。**协议（Protocol）** 指定数据如何传输以及如何处理请求。当你查看协议时，你就能很好地理解这个 URL 的用途。（例如是带有 SMTP、POP3、IMAP 的电子邮件协议，还是获取和管理 git 仓库的 SSH 请求，或者是针对 Web 的 HTTP 请求。）
害，这里前面已经给了定义 Protocol 了，后面的就直接移到前面啦

并且前面那只给个首字母大写嘛

2021-02-09 01:51 UTC, regon-cao commented
@lsvih 校对认领

2021-02-09 02:32 UTC, lsvih commented
@regon-cao 好的

2021-02-09 06:40 UTC, regon-cao reviewed
@zenblo  翻译的棒棒

2021-02-09 06:40 UTC, regon-cao commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +3. **请求体**（可选）： 当你向服务器发出 POST、PUT、PATCH 请求时，你需要发送一个请求体报文，该报文告诉服务器你想要发送什么数据。示例：
可选）： 当你  -->可选）：当你  
多了个空格

2021-02-09 06:40 UTC, regon-cao commented on article/2021/quick-overview-of-http-requests-cross-origin-resource-sharing-cors.md
> +代码，当你在网页浏览这个的时候，它正在向我自己的网站服务器发送一个 POST 请求。这称为跨域请求（**Cross-Domain request**）。
这里为啥换行了

2021-02-09 08:56 UTC, zenblo commented
@regon-cao 感谢校对！
@lsvih 完成 2 次校对

2021-02-09 09:05 UTC, lsvih approved these changes

2021-02-09 09:05 UTC, merged

2021-02-09 09:05 UTC, lsvih commented
@zenblo  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-02-09 09:23 UTC, zenblo commented
@lsvih @PassionPenguin @regon-cao 掘金文章发布地址  https://juejin.cn/post/6927191095470194695/

2021-02-09 10:59 UTC, lsvih commented
收到