人人都能够理解的身份认证和授权访问
xitu/gold-miner pull request #8009
Opened 2021-02-08 01:36 UTC by Ashira97

译文翻译完成，请各位大佬校对~  resolve #7918

2021-02-08 02:00 UTC, lsvih commented
辛苦啦，这么长

2021-02-08 02:34 UTC, Ashira97 commented
My pleasure~

2021-02-08 14:42 UTC, PassionPenguin commented
校对认领：）

2021-02-08 14:43 UTC, lsvih commented
@PassionPenguin 好的

2021-02-08 17:25 UTC, PassionPenguin requested changes
除了翻译的一些遗留（翻译腔感觉）以及标点后不用空格之外挺棒哒 ψ(｀∇´)ψ

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +就算你已经做完了所有工作，但你一定不清楚一系列操作的背后发生了**什么**，或者是**为什么**能用特定的方式实现功能。如果你想要对 OAuth 2.0和 OpenID 连接规范有更深、更基础的理解，那么就请继续读下去吧~
```suggestion
就算你已经做完了所有工作，但你一定不清楚一系列操作的背后发生了**什么**，或者是**为什么**能用特定的方式实现功能。如果你想要对 OAuth 2.0 和 OpenID 连接规范有更深、更基础的理解，那么就请继续读下去吧～
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +然而，都不是。我之前为 [Auth0](https://auth0.com) 工作，这是一个管理**数字证书**的公司。我现在是 [Auth0 大使计划](https://auth0.com/ambassador-program)的一员，也是 SPPI (安全、隐私、支付、认证)方向的[谷歌开发专家](https://developers.google.com/)。
```suggestion
然而，都不是。我之前为 [Auth0](https://auth0.com) 工作，这是一个管理**数字证书**的公司。我现在是 [Auth0 大使计划](https://auth0.com/ambassador-program)的一员，也是 SPPI (安全、隐私、支付、认证)方向的[谷歌开发者专家](https://developers.google.com/)。
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +在一个系统能够实现身份认证后，我们就来到了下一个概念。
```suggestion
当一个系统能够实现身份认证后，我们就……
```

这里不仅仅是概念吧，应该是直接到下一动词

当一个系统能够实现身份认证后，我们就开启授权访问功能？

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +当我们谈论 web 规范的时候，[OAuth 2.0](https://tools.ietf.org/html/rfc6749)是最经常被提到的规范，也是**最容易被误解**的一个，为什么呢？
```suggestion
当我们谈论 Web 规范的时候，[OAuth 2.0](https://tools.ietf.org/html/rfc6749)是最经常被提到的规范，也是**最容易被误解**的一个，为什么呢？
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +为了理解 OAuth 的目的，我们需要看看它的发展历史。 OAuth 1.0在2007年12月出台。在此之前，如果我们需要**访问第三方资源**，就会发生如下过程：
```suggestion
为了理解 OAuth 的目的，我们需要看看它的发展历史。OAuth 1.0 在 2007 年 12 月出台。在此之前，如果我们需要**访问第三方资源**，就会发生如下过程：
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +好比说你正在使用一个叫做 HireMe123 的应用程序。 HireMe123 想代表你设定一个日历事件（例如面试约会）。但是HireMe123没有自己的日历，所以它要使用另一个叫做 MyCalApp 的服务去添加日历事件。
```suggestion
好比说你正在使用一个叫做 HireMe123 的应用程序。 HireMe123 想代表你设定一个日历事件（例如面试约会）。但是 HireMe123 没有自己的日历，所以它要使用另一个叫做 MyCalApp 的服务去添加日历事件。
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +从一个方面来考虑， HireMe123 承担的保护 MyCalApp 登录信息的责任要小的多。如果 HireMe123 没有给 MyCalApp 证书提供合适的保护，那它们就有可能被窃取，有的人可能就此窃取事件写一些很可恶的博客文章，但是 **HireMe123** 不会面临着 MyCalApp 那样的指责。
```suggestion
从一个方面来考虑，HireMe123 承担的保护 MyCalApp 登录信息的责任要小的多。如果 HireMe123 没有给 MyCalApp 的证书提供合适的保护，那它们就有可能被窃取，有的人可能就此窃取事件写一些很可恶的博客文章，但是 **HireMe123** 不会面临着 MyCalApp 那样的指责。
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +**OAuth 2.0**是一个开放的用于实现授权访问的标准。作为一个说明书，它能够指导我们如何在不用暴露个人证书的同时给第三方应用授权访问某些 API。
```suggestion
**OAuth 2.0** 是一个开放的用于实现授权访问的标准。作为一个说明书，它能够指导我们如何在不用暴露个人证书的同时给第三方应用授权访问某些 API。
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +使用 OAuth 协议，用户现在可以**授权** HireMe123 代表用户访问 MyCalApp。 MyCalApp 能够在避免共享登录信息或者提供**过多**访问权限的风险的同时控制第三方对于API的访问权限。它是像这样工作的：
```suggestion
使用 OAuth 协议，用户现在可以**授权** HireMe123 代表用户访问 MyCalApp。MyCalApp 能够在避免共享登录信息或者提供**过多**访问权限的风险的同时控制第三方对于API的访问权限。它是像这样工作的：
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +HireMe123 向 MyCalApp 的授权访问服务器发送一个授权访问请求。在响应中， MyCalApp 的授权访问服务器允许用户登录（如果你还没有登录过）。这个时候，你就拥有了能够访问 MyCalApp 的权限。
```suggestion
HireMe123 向 MyCalApp 的授权访问服务器发送一个授权访问请求。在响应中，MyCalApp 的授权访问服务器允许用户登录（如果你还没有登录过）。这个时候，你就拥有了能够访问 MyCalApp 的权限。
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +之后， MyCalApp 的授权服务器**提示请您同意**允许 HireMe123 代表你来访问 MyCalApp 的 API。这一提示在浏览器中弹出，然后请求您的同意允许 HireMe123 **添加日历事件** （但仅限于此了）。
```suggestion
之后，MyCalApp 的授权服务器**提示请您同意**允许 HireMe123 代表你来访问 MyCalApp 的 API。这一提示在浏览器中弹出，然后请求您的同意允许 HireMe123 **添加日历事件** （但仅限于此了）。
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +然后 MyCalApp 会给 HireMe123 发送一个**访问令牌**。 HireMe123 之后使用这个访问令牌在你同意过的权限许可的范围内调用 MyCalApp 的 API 并使用 API 来创建一个事件。
```suggestion
然后 MyCalApp 会给 HireMe123 发送一个**访问令牌**。HireMe123 之后使用这个访问令牌在你同意过的权限许可的范围内调用 MyCalApp 的 API 并使用 API 来创建一个事件。
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +**此处没有什么不可告人的事情发生！** **MyCalApp 正在要求用户登录 MyCalApp** 。 HireMe123 并**没有**请求用户的 MyCalApp 证书。共享证书和过多访问权限再也不是问题了。
```suggestion
**此处没有什么不可告人的事情发生！** **MyCalApp 正在要求用户登录 MyCalApp** 。HireMe123 并**没有**请求用户的 MyCalApp 证书。共享证书和过多访问权限再也不是问题了。
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +在这里，我希望 **OAuth 是一个授权访问协议**是一个足够清楚的事实，它不包含**身份认证**。在上述过程中的任一环节都不包含有身份认证，登录被 HireMe123 或是 MyCalApp 上不同的登录过程所控制。 OAuth 2.0在这里**并不规定**这个行为应该怎么做，它只是负责授权第三方访问 API。
```suggestion
在这里，我希望 **OAuth 是一个授权访问协议**是一个足够清楚的事实，它不包含**身份认证**。在上述过程中的任一环节都不包含有身份认证，登录被 HireMe123 或是 MyCalApp 上不同的登录过程所控制。OAuth 2.0在这里**并不规定**这个行为应该怎么做，它只是负责授权第三方访问 API。
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +这种问题叫做**困惑的副手问题**。 HireMe123 不知道这个令牌来自何处或者是这个令牌曾经发行给谁。如果我们还记得一开始的定义：**身份认证是关于确认这个用户是否是他自称的身份**，那么 HireMe123 无法从利用该访问令牌访问 API 的过程中得到这种信息。
```suggestion
这种问题叫做**不明的代理问题**。HireMe123 不知道这个令牌来自何处或者是这个令牌曾经发行给谁。如果我们还记得一开始的定义：**身份认证是关于确认这个用户是否是他自称的身份**，那么 HireMe123 无法从利用该访问令牌访问 API 的过程中得到这种信息。
```

2021-02-08 17:25 UTC, PassionPenguin commented on article/2021/authorization-and-authentication-for-everyone.md
> +接下来我们要了解的规范叫做 [OpenID 连接](https://openid.net/specs)，也被称作 OIDC。 OIDC 是一个**基于 OAuth 2.0**的规范，它规定了如何认证用户的身份。[OpenID 基金会 (OIDF)](https://openid.net/foundation/) 是 OIDC 标准的管理者。
```suggestion
接下来我们要了解的规范叫做 [OpenID 连接](https://openid.net/specs)，也被称作 OIDC。OIDC 是一个**基于 OAuth 2.0**的规范，它规定了如何认证用户的身份。[OpenID 基金会 (OIDF)](https://openid.net/foundation/) 是 OIDC 标准的管理者。
```

2021-02-08 17:32 UTC, PassionPenguin commented
一共 15 处出现符号后跟空格，可直接用 `。 ` 和 `， ` 正则检查 ψ(｀∇´)ψ

另外：

```zsh
penguin@Penguins-MBP ~ % markdown tmp.md
/Users/penguin/tmp.md
   12:77-12:78           space-round-number            No space between Chinese and number. 'uth 2.0和 Ope'
   66:91-66:92           space-round-number            No space between Chinese and number. 'uth 2.0代表用户给'
   70:39-70:40           space-round-number            No space between Chinese and number. 'uth 1.0在2007'
   70:40-70:41           space-round-number            No space between Chinese and number. 'th 1.0在2007年'
   70:44-70:45           space-round-number            No space between Chinese and number. '.0在2007年12月出'
   70:45-70:46           space-round-number            No space between Chinese and number. '0在2007年12月出台'
   70:47-70:48           space-round-number            No space between Chinese and number. '2007年12月出台。在'
   74:64-74:65           space-round-alphabet          No space between Chinese and alphabet. '试约会）。但是HireM'
   74:73-74:74           space-round-number            No space between Chinese and number. 'reMe123没有自己的'
   80:6-80:20            no-trailing-punctuation       Header content can not end with symbol. '证书共享是一件很糟糕的事情！'
   94:100-94:101         space-round-alphabet          No space between Chinese and alphabet. '控制第三方对于API的访'
   94:103-94:104         space-round-alphabet          No space between Chinese and alphabet. '三方对于API的访问权限'
   100:16-100:17         space-round-number            No space between Chinese and number. 'uth 2.0重新审视 '
   118:7-118:15          no-trailing-punctuation       Header content can not end with symbol. '什么是身份认证？'
   120:121-120:122       space-round-number            No space between Chinese and number. 'uth 2.0在这里'
   126:12-126:13         space-round-number            No space between Chinese and number. 'uth 2.0为第三方服'
   128:26-128:27         space-round-number            No space between Chinese and number. 'uth 2.0是负责授权'
   141:40-141:41         space-round-number            No space between Chinese and number. 'uth 2.0误用于身份'
   141:103-141:104       space-round-number            No space between Chinese and number. 'uth 2.0的基础上'
   151:32-151:33         space-round-alphabet          No space between Chinese and alphabet. '用户身份。ID令牌是供第'
   169:1-169:4           no-empty-code-lang            Language of code can not be empty. 
   185:1-185:4           no-empty-code-lang            Language of code can not be empty. 
   213:1-213:4           no-empty-code-lang            Language of code can not be empty. 
   238:1-238:4           no-empty-code-lang            Language of code can not be empty. 
   283:24-283:40         no-space-in-link              Link content can not start / end with space. ' OAuth 2.0和授权服务器'
   283:34-283:35         space-round-number            No space between Chinese and number. 'uth 2.0和授权服务'
   301:2-301:3           space-round-alphabet          No space between Chinese and alphabet. 'W我们在上面已经讲过了'
   307:1-307:4           no-empty-code-lang            Language of code can not be empty. 
   357:60-357:77         no-space-in-link              Link content can not start / end with space. '基于角色的访问控制 (RBAC) '
   361:4-361:14          no-trailing-punctuation       Header content can not end with symbol. '资源，接下来是什么？'
   373:12-373:13         space-round-number            No space between Chinese and number. 'uth 2.0和 Ope'
   373:88-373:102        no-space-in-link              Link content can not start / end with space. ' OAuth 2.0授权框架'
   373:98-373:99         space-round-number            No space between Chinese and number. 'uth 2.0授权框架'

Lint total 1 files, 0 warnings 33 errors
```

2021-02-20 10:35 UTC, stuchilde commented
认领校对

2021-02-20 10:38 UTC, lsvih commented
@stuchilde 欢迎校对~

2021-02-25 11:29 UTC, lsvih commented
@stuchilde 别忘了有空来完成校对哈

2021-02-26 03:07 UTC, stuchilde reviewed
> @stuchilde 别忘了有空来完成校对哈

周末就校对

2021-02-28 17:09 UTC, stuchilde approved these changes
校对完毕

2021-03-01 08:35 UTC, Ashira97 commented on article/2021/authorization-and-authentication-for-everyone.md
> +在一个系统能够实现身份认证后，我们就来到了下一个概念。
或者：当一个系统能够实现身份认证之后，我们就要考虑如何为它实现授权访问功能。

2021-03-01 09:18 UTC, Ashira97 commented on article/2021/authorization-and-authentication-for-everyone.md
> +在一个系统能够实现身份认证后，我们就来到了下一个概念。
或者：当一个系统能够实现身份认证之后，我们就要考虑如何为它实现授权访问功能。

2021-03-01 09:18 UTC, Ashira97 commented on article/2021/authorization-and-authentication-for-everyone.md
> +这种问题叫做**困惑的副手问题**。 HireMe123 不知道这个令牌来自何处或者是这个令牌曾经发行给谁。如果我们还记得一开始的定义：**身份认证是关于确认这个用户是否是他自称的身份**，那么 HireMe123 无法从利用该访问令牌访问 API 的过程中得到这种信息。
我记得翻译成“困惑的副手问题”是可以搜到结果的，“不明的代理问题”可能不利于读者继续定位问题或者探索。那我在这里把中英文都写上好啦~

2021-03-01 09:45 UTC, Ashira97 commented
@PassionPenguin @stuchilde 感谢两位老师的校对~  
@lsvih 修改完成~

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +* `sub` **(主题)**: 用户的独特标识符；必填
```suggestion
* `sub` **（主题）**：用户的独特标识符；必填
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +**访问令牌**用于**许可对某资源的访问**。用一个 MyCalApp 的授权服务器发行的访问令牌， HireMe123 就可以访问 MyCalApp 的 API。
```suggestion
**访问令牌**用于**许可对某资源的访问**。用一个 MyCalApp 的授权服务器发行的访问令牌，HireMe123 就可以访问 MyCalApp 的 API。
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +这一授权过的请求之后发给 API ，在 API 中使用第三方中间件来验证令牌。如果验证通过，API 就返回数据给浏览器中的应用程序。
```suggestion
这一授权过的请求之后发给 API，在 API 中使用第三方中间件来验证令牌。如果验证通过，API 就返回数据给浏览器中的应用程序。
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +我正在使用 HireMe123 并且 HireMe123 想要访问第三方程序 MyCalApp 的 API 来代表我创建一个事件。 HireMe123 已经向 MyCalApp 从授权服务器请求了访问令牌**访问令牌**。这个令牌中包含有一些重要信息，比如：
```suggestion
我正在使用 HireMe123 并且 HireMe123 想要访问第三方程序 MyCalApp 的 API 来代表我创建一个事件。HireMe123 已经向 MyCalApp 从授权服务器请求了访问令牌**访问令牌**。这个令牌中包含有一些重要信息，比如：
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +但是 MyCalApp 为**成百上千的用户**管理日历事件。除了查看令牌中的 `scope` ， MyCalApp 的 API 还需要检查 `sub` 字段标识符来确定这个来自 HireMe123 的请求仅仅能够使用**我**已有的权限来在**我的**账户上创建事件。
```suggestion
但是 MyCalApp 为**成百上千的用户**管理日历事件。除了查看令牌中的 `scope` ，MyCalApp 的 API 还需要检查 `sub` 字段标识符来确定这个来自 HireMe123 的请求仅仅能够使用**我**已有的权限来在**我的**账户上创建事件。
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +> **使用 RBAC** ，你能在授权服务器中给用户角色设置特定的权限。然后，当授权服务器发出访问令牌的时候，它就可以在作用域中包含一个特定的用户角色。
```suggestion
> **使用 RBAC**，你能在授权服务器中给用户角色设置特定的权限。然后，当授权服务器发出访问令牌的时候，它就可以在作用域中包含一个特定的用户角色。
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +* `sub`: (我的 MyCalApp 用户 ID)
```suggestion
* `sub`：（我的 MyCalApp 用户 ID）
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +* `aud`: `MyCalAppAPI` (受众字段说明这个令牌是用于访问 MyCalApp 的 API)
```suggestion
* `aud`：`MyCalAppAPI`（受众字段说明这个令牌是用于访问 MyCalApp 的 API）
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +* `scope`: `write:events` (作用域说明 HireMe123 有权限使用 API 来在日历中写事件)
```suggestion
* `scope`：`write:events`（作用域说明 HireMe123 有权限使用 API 来在日历中写事件）
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +* nonce (`nonce`): 这个令牌能否匹配到我们应用程序当初创建的授权请求？
```suggestion
* nonce (`nonce`)：这个令牌能否匹配到我们应用程序当初创建的授权请求？
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +* expiration (`exp`): 这个令牌是否在可用的时间段之内？
```suggestion
* expiration (`exp`)：这个令牌是否在可用的时间段之内？
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +* audience (`aud`): 我们的应用程序是这个令牌的指定接收者吗？
```suggestion
* audience (`aud`)：我们的应用程序是这个令牌的指定接收者吗？
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +* issuer (`iss`): 当前令牌是被特定授权服务器颁发的吗？
```suggestion
* issuer (`iss`)：当前令牌是被特定授权服务器颁发的吗？
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +字段也包含了 **[关于端用户的描述](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims)** 。如下是几个例子：
```suggestion
字段也包含了 **[关于端用户的描述](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims)**。如下是几个例子：
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +* `iat` **(发行时间)**: ID 令牌发行的时间。
```suggestion
* `iat` **（发行时间）**：ID 令牌发行的时间。
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +* `exp` **(过期时间)**: 过期时间; 在此时间之后 ID 令牌不再有效。
```suggestion
* `exp` **（过期时间）**：过期时间；在此时间之后 ID 令牌不再有效。
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +* `aud` **(接收者)**: JWT 的目标接收者; 对于 ID 令牌来说, 这个字段一定是接收令牌的应用的 ID。
```suggestion
* `aud` **（接收者）**：JWT 的目标接收者；对于 ID 令牌来说，这个字段一定是接收令牌的应用的 ID。
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +* `iss` **(发行人)**: JWT 的发行者, 例如授权访问服务器。
```suggestion
* `iss` **（发行人）**：JWT 的发行者，例如授权访问服务器。
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +这种问题叫做**困惑的副手问题（ Confused Deputy Problem ）**。HireMe123 不知道这个令牌来自何处或者是这个令牌曾经发行给谁。如果我们还记得一开始的定义：**身份认证是关于确认这个用户是否是他自称的身份**，那么 HireMe123 无法从利用该访问令牌访问 API 的过程中得到这种信息。
```suggestion
这种问题叫做**困惑的副手问题（Confused Deputy Problem）**。HireMe123 不知道这个令牌来自何处或者是这个令牌曾经发行给谁。如果我们还记得一开始的定义：**身份认证是关于确认这个用户是否是他自称的身份**，那么 HireMe123 无法从利用该访问令牌访问 API 的过程中得到这种信息。
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +**此处没有什么不可告人的事情发生！** **MyCalApp 正在要求用户登录 MyCalApp** 。HireMe123 并**没有**请求用户的 MyCalApp 证书。共享证书和过多访问权限再也不是问题了。
```suggestion
**此处没有什么不可告人的事情发生！** **MyCalApp 正在要求用户登录 MyCalApp**。HireMe123 并**没有**请求用户的 MyCalApp 证书。共享证书和过多访问权限再也不是问题了。
```
```suggestion
**此处没有什么不可告人的事情发生！** **MyCalApp 正在要求用户登录 MyCalApp** 。HireMe123 并**没有**请求用户的 MyCalApp 证书。共享证书和过多访问权限再也不是问题了。
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +好比说你正在使用一个叫做 HireMe123 的应用程序。 HireMe123 想代表你设定一个日历事件（例如面试约会）。但是 HireMe123 没有自己的日历，所以它要使用另一个叫做 MyCalApp 的服务去添加日历事件。
```suggestion
好比说你正在使用一个叫做 HireMe123 的应用程序。HireMe123 想代表你设定一个日历事件（例如面试约会）。但是 HireMe123 没有自己的日历，所以它要使用另一个叫做 MyCalApp 的服务去添加日历事件。
```

2021-03-01 11:10 UTC, lsvih commented on article/2021/authorization-and-authentication-for-everyone.md
> +有许多不同的标准和组织来管理互联网上的工作方式。在讨论身份认证和授权访问的时候，有两个组织是我们**尤其感兴趣的**，它们分别是互联网工程任务组 (IETF) 和 OpenID 基金会 (OIDF)。
```suggestion
有许多不同的标准和组织来管理互联网上的工作方式。在讨论身份认证和授权访问的时候，有两个组织是我们**尤其感兴趣的**，它们分别是互联网工程任务组（IETF）和 OpenID 基金会（OIDF）。
```

2021-03-01 11:10 UTC, lsvih commented
@Ashira97 您好，还有一点格式上的问题得麻烦您过一下哈

2021-03-02 00:41 UTC, Ashira97 commented
@lsvih 好的 抱歉 我在改一下~

2021-03-02 02:01 UTC, Ashira97 commented
@PassionPenguin @stuchilde 感谢两位老师的校对 格式错误太多 让二位老师费心了
@lsvih 已修改 麻烦您了~ 您看还有哪里需要改的不...我去把格式检查搞个脚本好了...

2021-03-02 06:10 UTC, lsvih commented
我稍晚点看哈

2021-03-02 07:56 UTC, lsvih approved these changes
LGTM

2021-03-02 07:57 UTC, merged

2021-03-02 07:57 UTC, lsvih commented
@Ashira97  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-03-03 01:21 UTC, Ashira97 commented
@lsvih 已发布~ https://juejin.cn/post/6935230984619032589/

2021-03-03 04:42 UTC, lsvih commented
收到