基于 50 万个浏览器指纹的新发现
xitu/gold-miner pull request #8014
Opened 2021-02-09 15:02 UTC by Usualminds

译文翻译完成，resolve #7977

2021-02-09 15:56 UTC, PassionPenguin requested changes
注意 syntax 以及 alt 的翻译嗷 ψ(｀∇´)ψ @lsvih

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +你还记得自己上一次在网上寻找想要的商品时，会弹出很多与之相关广告页面？这时候你很有可能正在被跟踪，因为你的屏幕分辨率、时区和表情符号集这些信息都暴露在了网上。
```suggestion
你还记得自己上一次在网上寻找想要的商品时，是不是会弹出很多与之相关的广告页面啊？这时候你很有可能正在被跟踪，因为你的屏幕分辨率、时区和表情符号集这些信息都暴露在了网上。
```

没看懂，这个 screen resolution emoji sets 和广告有啥关系，不应该是 keyword platform 和 ip 什么吗...

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +没错，这种方法甚至可以在你使用无痕浏览模式(也就是隐身模式)时跟踪你。
```suggestion
没错，这种方法甚至可以在你使用无痕浏览模式（又称为隐身模式）时跟踪你。
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
>  ![Example features and values of a browser fingerprint — check yours at [http://fp.virpo.sk](http://fp.virpo.sk)](https://cdn-images-1.medium.com/max/2000/1*PxgUnoZ92Gg75mpgczP2xQ.png)
```suggestion
![Example features and values of a browser fingerprint — check yours at [http://fp.virpo.sk](http://fp.virpo.sk)](https://cdn-images-1.medium.com/max/2000/1*PxgUnoZ92Gg75mpgczP2xQ.png)
```

记得翻译 alt 方便视障同学阅读嗷，无障碍化！

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +在 [Slido](https://slido.com) 上，我们进行了一次最大规模的浏览器指纹识别准确性的公开调查，并且是全球首次针对智能手机上的指纹信息表现进行的全面调查。
```suggestion
在 [Slido](https://slido.com) 上，我们进行了一次全网最大规模的浏览器指纹识别准确性的公开调查。这是全球首次针对智能手机上的指纹信息表现进行的全面调查！
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +每台相机都会在图片上留下独特的噪声模式，每台打字机都会以特定的方式在字母周围留下墨迹。
```suggestion
每台相机都会在图片上留下独特的噪声的样式，每台打字机也都会以特定的方式在字母周围留下墨迹。
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +通过观察两张照片并比较它们的噪声模式，我们可以准确地判定这是否是同一台相机所拍摄。
```suggestion
通过观察两张照片并比较它们的噪声样式，我们可以准确地判定这是否是同一台相机所拍摄。
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +可能是你的屏幕尺寸、表情符号、已安装的字体、语言、时区或显卡模型。所有这些都可以从你的浏览器获得，但是你也许从未注意过这一点。
已安装的字体..显卡...

能获取，但极度不方便，还不一定兼容，况且获取来干啥...

这作者也是硬黑

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +可能是你的屏幕尺寸、表情符号、已安装的字体、语言、时区或显卡模型。所有这些都可以从你的浏览器获得，但是你也许从未注意过这一点。
字体似乎唯一判断方法是利用字宽，但其实并不准确啊

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +就每个指纹信息本身而言，它们都是微不足道的。但通过组合使用，任何人都可以准确地通过它来识别特定的浏览器。
```suggestion
就每个指纹信息本身而言它们其实就是一堆垃圾。但通过信息间的组合使用，能让任何人都可以准确地通过它来识别特定的浏览器。
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
>  ![Even the appearance of emojis on your device can be used to identify you. Emojis can be extracted as a bitmap using HTML5 canvas.](https://cdn-images-1.medium.com/max/2264/1*EWjMItxMhNQCgseB4serOg.
ψ(｀∇´)ψ

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +以防诈骗为例。如果你的任何一种需要在线登录的账号，比如银行账户或者社交网络账户。 一般情况下只需要通过邮箱和密码就可以登录。
```suggestion
以防诈骗为例。如果你的任何一种需要在线登录的账号，比如银行账户或者社交网络账户。一般情况下只需要通过邮箱和密码就可以登录。
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +如果有一天你的证件被盗，小偷试图从他的设备上登录，但是浏览器指纹发生了变化，银行或社交网络将会检测到这种异常行为。为了防止诈骗，可能需要进一步的授权，比如短信验证码。
```suggestion
如果有一天你的证件被盗，小偷试图从他的设备上登录，但是浏览器指纹发生了变化，银行或社交网络将会检测到这种异常行为。为了避免诈骗的可能性，它们可能会要求你做出进一步的授权，比如短信验证码。
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +然而，迄今为止，浏览器指纹最广泛的应用是个性化的广告推送。“点赞”和“分享”按钮几乎出现在每个社交网站上，它们通常会包含一个 Javascript 脚本来收集你的浏览器指纹信息，从而进一步获取你的浏览记录。
```suggestion
然而，迄今为止，浏览器指纹最广泛的应用是个性化的广告推送。“点赞”和“分享”按钮几乎出现在每个社交网站上，它们通常会包含一个 JavaScript 脚本来收集你的浏览器指纹信息，从而进一步获取你的浏览记录。
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
>  ![Social share buttons are commonly used to collect your browser fingerprint](https://cdn-images-1.medium.com/max/2164/1*5Ux2MPqwS-XmNJrmSFw3uw.png)
ψ(｀∇´)ψ

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +但是因为与社交相关的按钮——也就是包含浏览器指纹的脚本——几乎无处不在，社交网络甚至知道你是怎么浏览网页的。
```suggestion
但是因为与社交相关的按钮——也就是包含浏览器指纹的脚本 —— 几乎无处不在，社交网络甚至知道你是怎么浏览网页的。
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +## 我的浏览器在任何地方和时间都能被识别出来吗?
```suggestion
## 我的浏览器在任何地方和时间都能被识别出来吗？
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +这些网站将你的指纹与他们的整个数据库进行比较，该数据库包含了 2-3 年(或 Panopticlick 45 天)收集的数据。
```suggestion
这些网站将你的指纹与他们的整个数据库进行比较，该数据库包含了 2 - 3 年（Panopticlick 则是 45 天）收集的数据。
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
>  ![Anonymity set sizes for the most occupied device types within our dataset. For example, only 33% of iPhones could be uniquely identified within our dataset.](https://cdn-images-1.medium.com/max/365
ψ(｀∇´)ψ

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
>  ![Distribution of device types within our dataset](https://cdn-images-1.medium.com/max/3842/1*6TGFW_Ta6xBGPtG3renu_g.png)
……

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
>  ![Rate of change of browser fingerprints.](https://cdn-images-1.medium.com/max/3842/1*girS-UYQ-GwEactOp8bgfg.png)
ψ(｀∇´)ψ

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
>  ![Rate of fingerprint change across different device types.](https://cdn-images-1.medium.com/max/4192/1*-kGLm0LGKQxjbtckW2gyZg.png)
ψ(｀∇´)ψ

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +这张图表显示，19% 的 iphone 手机在一周内更换了指纹，而同期只有 3% 的 Android 手机也更换了指纹。因此，我们的数据可以表明，iphone 比 android 更难进行长时间的跟踪。
```suggestion
这张图表显示，19% 的 iPhone 手机在一周内更换了指纹，而同期只有 3% 的 Android 手机也更换了指纹。因此，我们的数据可以说明，iPhone 比起 Android 来说更难进行长时间的跟踪。
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +如果我们用更难获得的特性(如 canvas、已安装字体列表等)扩展子集，就能够达到熵为 16.5 的目标。
```suggestion
如果我们用更难获得的特性（如 `Canvas`、已安装字体列表等）的扩展子集，就能够达到熵为 16.5 的目标。
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +* 智能手机(尤其是 iphone)比个人电脑更难追踪
```suggestion
* 智能手机（尤其是 iPhone）比个人电脑更难追踪
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +在 [Slido](https://slido.com)，我们试图使我们的 web 应用程序的用户体验尽可能简单。当你使用我们的应用程序时，你通常不需要注册，我们希望保持这种方式。
```suggestion
在 [Slido](https://slido.com) 上，我们试图使我们的 Web 应用程序的用户体验尽可能简单。当你使用我们的应用程序时，你通常不需要注册，我们希望保持这种方式。
```

2021-02-09 15:56 UTC, PassionPenguin commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +非常感谢我的主管, RNDr. Michal Forišek 博士, 他在本次研究中给了我很大的帮助。
```suggestion
非常感谢我的导师，RNDr. Michal Forišek 博士，在本次研究中为我提供了很大的帮助。
```

2021-02-09 15:57 UTC, PassionPenguin commented
（硕士学位论文 doge

2021-02-10 00:19 UTC, Usualminds commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +你还记得自己上一次在网上寻找想要的商品时，会弹出很多与之相关广告页面？这时候你很有可能正在被跟踪，因为你的屏幕分辨率、时区和表情符号集这些信息都暴露在了网上。
我理解的是这些都是指纹因子，通过综合指纹算法，可以像第三方cookie那样追踪个人信息，可以看下这个 [fingerprintjs](https://github.com/fingerprintjs/fingerprintjs)

2021-02-10 00:32 UTC, Usualminds commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +可能是你的屏幕尺寸、表情符号、已安装的字体、语言、时区或显卡模型。所有这些都可以从你的浏览器获得，但是你也许从未注意过这一点。
我觉得有一定实际意义，这里他只是举例这几个，事实上像 `canvas` 这些辨识度极高的指纹，在区分浏览器有很重要的作用，他举例的这些反而有点避重就轻，你可以看下文末第一个链接的论文，还有文中的那个两个科技论文，随着第三方cookie逐渐被禁用，像广告这种行业基本都走向了浏览器指纹方向，也是未来人机识别的一个方向，而通过这种手段用户很难感知到自己被追踪了，所以是一个双刃剑

2021-02-10 00:49 UTC, Usualminds commented
@PassionPenguin 感谢校对，哈哈
@lsvih 后面看是否将图片`alt ` 翻译纳入规范，个人感觉还是有必要的

2021-02-10 00:50 UTC, lsvih commented
@Usualminds 可以考虑哈，现在掘金的渲染样式还没有做 figure alt 的展示，我反馈一下

2021-02-10 00:55 UTC, Usualminds commented
> （捷克一名大佬的硕士学位论文 doge

看下这个 [fps](https://www.youtube.com/watch?v=jWX9P5_jZn8)，从结果看，他们已经实现了通过浏览器指纹来**唯一**识别用户了

2021-02-10 08:23 UTC, PassionPenguin commented
> @Usualminds 可以考虑哈，现在掘金的渲染样式还没有做 figure alt 的展示，我反馈一下

掘金似乎还是没有将别人的图片引入回来 - -

我现在回头看了一下，Bilibili 和 知乎都是自己的图床，唯有掘金是 medium 原链接 - -

以及那个孤零零的 `alt`

<img width="120" alt="Screen Shot 2021-02-10 at 4 22 20 PM" src="https://user-images.githubusercontent.com/41184947/107483628-4d4f5300-6bbc-11eb-8ad9-edbb15a72b4e.png">

2021-02-10 08:27 UTC, PassionPenguin submitted a review, later dismissed

2021-02-19 08:57 UTC, Chorer commented
校对认领

2021-02-19 09:48 UTC, lsvih commented
@Chorer 欢迎认领！

2021-02-19 09:54 UTC, Chorer reviewed
@lsvih 校对完毕。要改的地方可能有点多，但都是一些小问题（格式、语序的微调等），整体翻译的很棒，读起来相当流畅！

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +可能是你的屏幕尺寸、表情符号、已安装的字体、语言、时区或显卡模型。所有这些都可以从你的浏览器获得，但是你也许从未注意过这一点。
```suggestion
可能是你的屏幕尺寸、表情符号、已安装的字体、语言、时区或显卡型号。所有这些都可以从你的浏览器获得，但是你也许从未注意过这一点。
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +就每个指纹信息本身而言，它们都是微不足道的。但通过组合使用，任何人都可以准确地通过它来识别特定的浏览器。
```suggestion
就每个指纹信息本身而言，它们都是微不足道的。但通过信息间的组合使用，能让任何人都可以准确地通过它来识别特定的浏览器。
```
insignificant 是微不足道、无足轻重，不等于是毫无价值的垃圾。

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +![甚至你设备上的表情符号都可以用来识别你。表情符号可以使用HTML5画布提取为位图。](https://cdn-images-1.medium.com/max/2264/1*EWjMItxMhNQCgseB4serOg.jpeg)
```suggestion
![甚至你设备上的表情符号都可以用来识别你。我们可以使用 HTML5 的画布将表情符号提取为位图。](https://cdn-images-1.medium.com/max/2264/1*EWjMItxMhNQCgseB4serOg.jpeg)
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +## 浏览器指纹信息如何使用？
```suggestion
## 如何使用浏览器指纹信息？
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +有人可能会认为浏览器指纹天生就有不好的一面，但事实并非如此。
```suggestion
有人可能会认为浏览器指纹天生就是用来做一些非法勾当的，但事实并非如此。
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +以防诈骗为例。如果你的任何一种需要在线登录的账号，比如银行账户或者社交网络账户。一般情况下只需要通过邮箱和密码就可以登录。
```suggestion
以防诈骗为例。如果你有任何一种需要在线登录的账号，比如银行账户或者社交网络账户，一般情况下只需要通过邮箱和密码就可以登录。
```
“如果你的任何一种需要在线登录的账号，比如银行账户或者社交网络账户。”，这个不能单独成句。

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +如果有一天你的证件被盗，小偷试图从他的设备上登录，但是浏览器指纹发生了变化，银行或社交网络将会检测到这种异常行为。为了防止被诈骗，它们可能会要求你做出进一步的授权，比如短信验证码。
```suggestion
如果有一天，小偷盗取了你的登录凭证并试图从他的设备上登录，银行或社交网络是可以检测到这种异常行为的，因为浏览器指纹发生了变化。为了防止被诈骗，平台可能会要求你做出进一步的授权，比如短信验证码。
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +通过这种方式，那些科技巨头会向你提供你半小时前搜索的相关广告。
```suggestion
通过这种方式，那些科技巨头会向你推送你半小时前搜索内容的相关广告。
```
提供一般是服务，这里建议和你之前翻译的保持一致，即推送广告而不是提供广告。

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +这里有几个网站，比如 [AmIUnique](https://amiunique.org/) 和 [Panopticlick](https://panopticlick.eff.org/)，基于它们数据库大约 100 万个指纹信息，可以来确定你的浏览器指纹信息是否唯一。
```suggestion
这里有几个网站，比如 [AmIUnique](https://amiunique.org/) 和 [Panopticlick](https://panopticlick.eff.org/)，它们会基于数据库内大约 100 万个指纹信息，来确定你的浏览器指纹信息是否唯一。
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +你的浏览器指纹很可能会被标记为唯一的。这听起来很可怕，但请耐心听我说，当我们看到指纹标记原理时，可能就没那么担心了。
```suggestion
你的浏览器指纹很可能会被标记为唯一的。这听起来很可怕，但请耐心听我说，当我们了解指纹标记原理时，可能就没那么担心了。
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +这些网站将你的指纹与他们的整个数据库进行比较，该数据库包含了 2 - 3 年 (或 Panopticlick 则是 45 天) 收集的数据。
```suggestion
这些网站将你的指纹与他们的整个数据库进行比较，该数据库包含了至少两到三年 (或 Panopticlick 则是 45 天) 收集的数据。
```
注意这里的 over

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +我们看到了另一个有趣的现象，当观察单个设备的浏览器指纹发生变化的频率时。
```suggestion
当观察单个设备的浏览器指纹发生变化的频率时，我们看到了另一个有趣的现象。
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +这张图表显示，19% 的 iPhone 手机在一周内更换了指纹，而同期只有 3% 的 Android， iPhone 比 android 更难进行长时间的跟踪。
```suggestion
这张图表显示，19% 的 iPhone 手机在一周内更换了指纹，而同期只有 3% 的 Android。我们的数据表明，iPhone 比 Android 更难进行长时间的跟踪。
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +实验表明，通过提取 3 个基本的浏览器特征，即日期格式、用户代理字符集和屏幕可用大小(屏幕大小减去程序坞、窗口栏等的大小)，我们可以实现 14.2 的熵，在某些情况下，这已经足够识别浏览器(以及用户)。
```suggestion
实验表明，通过提取 3 个基本的浏览器特征，即日期格式、用户代理字符集和屏幕可用大小（屏幕大小减去程序坞、窗口栏等的大小），我们可以实现 14.2 的熵，在某些情况下，这已经足够识别浏览器（以及用户）。
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +如果我们用更难获得的特性 (如 `Canvas`、已安装字体列表等) 扩展子集，就能够达到熵为 16.5 的目标。
```suggestion
如果我们用更难获得的特性 (如画布指纹、已安装字体列表等) 扩展子集，就能够达到熵为 16.5 的目标。
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +那么从这里面能得到什么呢?
```suggestion
那么我们从中能得到什么结论呢？
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +* 那些科技巨头可以追踪到你的线上活动，但还不完全准确。
```suggestion
* 那些科技巨头可以追踪到你的线上活动，但目前还不完全准确。
```
注意这里的 yet

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +然而，如果你担心你的数据隐私，也有一些好消息。首先，[苹果宣布了一场针对浏览器指纹识别的保卫战](https://www.howtogeek.com/fyi/safari-battles-browser-fingerprinting-and-tracking-on-macos-mojave/)，它推出了最新的 Mac OS Mojave 版本。其次，GDPR 认为浏览器指纹是个人数据，必须进行相
```suggestion
然而，如果你担心你的数据隐私，我这里也可以告诉你一些好消息。首先，[苹果宣布了一场针对浏览器指纹识别的保卫战](https://www.howtogeek.com/fyi/safari-battles-browser-fingerprinting-and-tracking-on-macos-mojave/)，它推出了最新的 Mac OS Mojave 版本。其次，GDPR 认为浏览器指纹是个人数据，必须进行相应的处理。最后还有许多 [插件和浏览器扩展](https://amiunique.org/tools) 会混淆浏览器指纹脚本。
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +所以，我们的浏览器隐私在未来并不像看起来那么糟糕。诚然，有时你的浏览器可以被唯一地识别，但很多时候其他设备的浏览器指纹与你的完全相同，这使得你的浏览器更难被跟踪。
```suggestion
所以，我们的浏览器隐私在未来并不像它看起来的那么糟糕。诚然，有时你的浏览器可以被唯一地识别，但很多时候其他设备的浏览器指纹与你的完全相同，这使得你的浏览器更难被跟踪。
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +在 [Slido](https://slido.com) 上，我们试图使我们的 Web 应用程序的用户体验尽可能简单。当你使用我们的应用程序时，你通常不需要注册，我们希望保持这种方式。
```suggestion
在 [Slido](https://slido.com) 上，我们试图使我们的 Web 应用程序的用户体验尽可能简单。当你使用我们的应用程序时，你通常不需要登录，我们希望保持这种方式。
```

sign up VS sign in

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +而我们研究的结论是是**否定的**
```suggestion
而我们研究的结论是**否定的**
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +浏览器指纹本身不足以作为我们进行用户的身份验证的充分条件。然而，它们足够准确地把你放在一群有着类似兴趣的人当中(比如猫或汽车)。
```suggestion
浏览器指纹本身不足以作为我们进行用户身份验证的充分条件。然而，它们足够准确地把你放在一群有着类似兴趣（比如猫或汽车）的人当中。
```

这里的 cat 和 car 是 interest，建议放在“兴趣”后面

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +这就意味着使用浏览器指纹是个理想的场景，如个性化的广告，准确性并非其关键，或防止银行诈骗，通过浏览器指纹追踪，让诈骗者有所畏惧到底是一件好事。
```suggestion
这就意味着浏览器指纹的使用在个别场景中是理想的，比如个性化的广告，这种情况下准确性并非其关键，或者防止银行诈骗，通过浏览器指纹追踪，让诈骗者有所畏惧到底是一件好事。
```
“使用浏览器指纹是个理想的场景” 这句话有问题。并不是说使用浏览器指纹是个理想的场景，而是说使用浏览器指纹在如下这些场景中是较为理想的：个性化广告，防止诈骗等。注意原文的 xxx are ideal for use cases xxx，这个理想的场景是有限制的。

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +如果你想了解更多关于浏览器指纹识别的知识，我写了一篇关于我研究的 [60 多页长的论文](http://virpo.sk/browser-fingerprinting-hraska-diploma-thesis.pdf)，你可以读读看。
```suggestion
如果你想了解更多关于浏览器指纹识别的知识，我写了一篇关于和自己的研究相关的 [60 多页长的论文](http://virpo.sk/browser-fingerprinting-hraska-diploma-thesis.pdf)，你可以读读看。
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +* [http://fp.virpo.sk](http://fp.virpo.sk) — 了解浏览器指纹是什么
```suggestion
* [http://fp.virpo.sk](http://fp.virpo.sk) —— 了解浏览器指纹是什么
```

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +* [https://audiofingerprint.openwpm.com](https://audiofingerprint.openwpm.com/) — audio 特性在浏览器指纹中的应用
```suggestion
* [https://audiofingerprint.openwpm.com](https://audiofingerprint.openwpm.com/) —— audio api 在浏览器指纹中的应用
```
链接的介绍有这句话：This page tests browser-fingerprinting using the AudioContext and Canvas API. 使用的是相关的 audio api，这里翻译为 api 而不是特性，会不会更好一点？

2021-02-19 09:54 UTC, Chorer commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +* [https://www.nothingprivate.ml/](https://www.nothingprivate.ml/) — 无痕浏览不再是无痕
```suggestion
* [https://www.nothingprivate.ml/](https://www.nothingprivate.ml/) —— 无痕浏览并不是无痕的
```

这个“再”的翻译可能有问题。如果说“不再是”，意思就是以前是这样的，现在不是这样的，但作者想说的意思可能是：无痕浏览一直都不是无痕的（不存在以前和现在不同的区别），只是我们下意识会以为确实是无痕的，所以 is not as，就是说不像它的名字那样听起来是无痕的。建议这里的“再”字去掉。

2021-02-19 10:30 UTC, Usualminds commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +如果我们用更难获得的特性 (如 `Canvas`、已安装字体列表等) 扩展子集，就能够达到熵为 16.5 的目标。
这里不建议翻译，`Canvas ` 是前端术语，无需翻译

2021-02-19 10:42 UTC, Usualminds commented
> @lsvih @Usualminds 校对完毕。要改的地方可能有点多，但都是一些小问题（格式、语序的微调等），整体翻译的很棒，读起来相当流畅！

@Chorer 感谢您细致的校对，已合入相关校对建议

2021-02-19 10:43 UTC, Usualminds commented
@lsvih 两位校对者信息已合入完成

2021-02-19 11:01 UTC, lsvih commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +这些网站将你的指纹与他们的整个数据库进行比较，该数据库包含了至少两到三年 (或 Panopticlick 则是 45 天) 收集的数据。
```suggestion
这些网站将你的指纹与他们的整个数据库进行比较，该数据库包含了至少两到三年（或 Panopticlick 则是 45 天）收集的数据。
```

2021-02-19 11:01 UTC, lsvih commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +没错，这种方法甚至可以在你使用无痕浏览模式(也就是隐身模式)时跟踪你。
```suggestion
没错，这种方法甚至可以在你使用无痕浏览模式（也就是隐身模式）时跟踪你。
```

2021-02-19 11:01 UTC, lsvih commented on article/2021/we-collected-500-000-browser-fingerprints-here-is-what-we-found.md
> +* 智能手机 (尤其是 iPhone) 比个人电脑更难追踪
```suggestion
* 智能手机（尤其是 iPhone）比个人电脑更难追踪
```

2021-02-19 11:01 UTC, lsvih commented
@Usualminds 还有少许格式上的问题劳烦您修一下哈

2021-02-19 13:40 UTC, Usualminds commented
@lsvih 已修改

2021-02-19 13:48 UTC, lsvih approved these changes

2021-02-19 13:49 UTC, merged

2021-02-19 13:49 UTC, lsvih commented
@Usualminds  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-02-19 14:03 UTC, Usualminds commented
@lsvih https://juejin.cn/post/6930974348002590733/

2021-02-20 00:20 UTC, lsvih commented
收到