Translate/why i still lisp and you should too.md
xitu/gold-miner pull request #8016
Opened 2021-02-10 06:57 UTC by elliott-zhao

译文翻译完成，resolve #7966

2021-02-10 10:30 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +作为 Scheme/Common Lisp/Racket 的长期用户（和积极支持者），我有时会被问到为什么还坚持使用它们。幸运的是，我一直都在领导自己的工程师组织，所以我从来不需要为此向领导层解释。但是还有一个更重要的群体——我的工程是同事们——他们从未体会过使用这些语言的乐趣。就算他们不会让我解释，他们也会出于求知欲提问，而有时候也会想知道我为什么不会对 Python 或 Scala 即将加入
```suggestion
作为 Scheme / Common Lisp / Racket 的长期用户（和积极支持者），我有时会被人们问到，为什么我还在坚持使用它们。幸运的是，我一直都在领导着自己的程序员组织中工作，从来不需要为使用这些而向领导们解释。但是还有一个更幸运的群体 —— 我的程序员同事们 —— 他们从未体会过使用这些语言的乐趣。就算他们不会让我解释，他们也会出于求知欲提问，而有时候也会想知道为什么我不会对 Python 或 Scala 即将加入的很酷的新特性，或者是什么其他风靡一时的东西而神魂颠倒。
```

2021-02-10 10:30 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +虽然我真正使用的 Lisp 方言有很多种（Scheme, Common Lisp, Racket, Lisp-for-Erlang），核心总是保持一致的：一种基于 S-表达式的、动态类型的、主要是函数式的、值传递的基于 λ 演算的语言。
```suggestion
虽然我真正使用的 Lisp 的变种有很多（Scheme, Common Lisp, Racket, Lisp-for-Erlang），但核心总是保持一致的：一种基于 S 表达式的、动态类型的、主要是函数式的、值传递的基于 λ 演算的语言。
```

2021-02-10 10:30 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +我在十几岁的时候在 ZX Spectrum+上使用 BASIC 真正开始编程，虽然在此之前我就对（手）写Fortran程序略有涉猎。这对我来说是一个决定性的使其，因为它真正定义了我的职业路线。很快我就把语言推到了它的极限，并且尝试写超出这门语言和实现的有限能力的程序。我转到 Pascal 很短的一段时间（在 DOS box 上的 Turbo Pascal），这段时间很有趣，知道我发现了运行在 U
```suggestion
我在十几岁的时候在 ZX Spectrum+ 上使用 BASIC 开始了我的编程之旅。虽然我在此之前我就对（手）写Fortran程序略有涉猎，但这确实对我来说是一个决定性的起始，因为它真正定义了我的职业路线。很快我就把这些语言用到了它的极限，并且尝试写超出这门语言和实现的有限能力的程序。我转到 Pascal 很短的一段时间（DOS box 上的 Turbo Pascal）里都是非常快乐的，直到我发现了运行在 Unix（Santa Cruz Operation Xenix!）上的 C。它帮助我取得了计算机科学的学士学位，但它总是让我希望能够在程序中拥有更强的表现力。
```

2021-02-10 10:30 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +当我在 Miranda（丑陋的 Haskell 的漂亮妈妈）中发现函数式编程时（感谢 IISc！），它让我大开眼界，想要在程序中追寻**美**。我对编程语言中的表现力的概念的理解有了一个巨大的飞跃。我对程序应该长什么样的概念开始包含简洁，优雅和可读性。
```suggestion
当我在 Miranda（丑陋的 Haskell 的漂亮母亲）中发现函数式编程时（感谢 IISc！），它真的让我大开眼界，想要在程序中追寻**美**！而我对编程语言中的表现力的概念的理解也有了一个巨大的飞跃。我对程序应该长什么样的概念开始包含简洁，优雅和可读性。
```

2021-02-10 10:30 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +> 一种基于 S-表达式的、动态类型的、主要是函数式的、值传递的基于 λ 演算的语言。
```suggestion
> 一种基于 S 表达式的、动态类型的、主要是函数式的、值传递的基于 λ 演算的语言。
```

2021-02-10 10:30 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +我要开始解释这些——倒序。
```suggestion
我要开始解释这些 —— 倒过来讲。
```

2021-02-10 10:30 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +这种特性被称为**尾调用优化**（**或 TCO**），已经出现了几十年。在评价编程语言现状的时候发现没有现代语言支持它，这是很令人沮丧的。因为新的语言出现并试图把 JVM 作为运行架构，所以这对于 JVM 更是个问题。JVM 不支持这个特性，所以基于 JVM 构建的语言必须越过障碍来提供部分适用 TCO 的假象。因此，我总是非常疑虑地使用任何面向 JVM 的函数式语言。这也是我没有成为 Clo
```suggestion
这种特性被称为**尾调用优化**（**又称为 TCO**），已经出现了几十年。在评价编程语言现状的时候发现没有现代语言支持它，这是很令人沮丧的。因为新的语言出现并试图把 JVM 作为运行架构，所以这对于 JVM 更是个问题。JVM 不支持这个特性，所以基于 JVM 构建的语言必须越过障碍来提供部分适用 TCO 的假象。因此，我总是非常疑虑地使用任何面向 JVM 的函数式语言。这也是我没有成为 Clojure 的粉丝的原因。
```

2021-02-12 13:13 UTC, PassionPenguin requested changes
@lsvih @elliott-zhao @elliott-zhao-io

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +# 为什么我还在用Lisp（而且你也应该用）
```suggestion
# 为什么我还在用 Lisp（而且你也应该用）
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +所有程序中的基本实体都是**函数**。从软件设计过程之初函数就拥有了它们的意向性。你一直在考虑怎样对信息进行操作，它是怎样转换的，以及它是是怎样产生的。我还没有找到一个基本的框架，比 λ 演算更好的捕捉到这一固有意向。
```suggestion
所有程序中的基本实体都是**函数**，而函数从软件设计过程之初就拥有了它们自己的目的性。你早已考虑了怎样对信息进行操作，考虑了它是怎样转换的，以及它是怎样产生的。我还没有找到一个基本的框架，能够比 λ 演算更好的捕捉到这一固有意向。
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +**意向**这个词可能会让你失望。数学有两种方式来理解函数。首先，作为一组有序对：（**输入，输出**）。尽管这是一种证明函数定理的好方法，但在写代码的过程中完全没用。这也被称为函数的**扩展**视图。
```suggestion
**目的性**这个词可能会让你失望。数学有两种方式来理解函数。首先，作为一组有序对：（**输入，输出**）。尽管这是一种证明函数定理的好方法，但在编程领域是没有意义的。而这，也被称为函数的**扩展**视图。
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +第二种方式是把函数看做一个转换规则。例如，将输入和其本身相乘得到输出（这为我们提供了平方函数，每种编程语言都将其缩写为 **sqr**）。这是函数的**意向**视图，λ 演算可以很好地捕捉它，并提供简单的规则来帮助我们证明函数定理，而无需求助于扩展性。
```suggestion
第二种方式是把函数看做一个转换规则。例如，将输入和其本身相乘得到输出（这里就是平方函数了，基本上在各个编程语言中都缩写为 **sqr** 或 **sqrt**）。这是函数的**目的**的观点，而 λ 演算可以很好地捕捉它，并提供简单的规则来帮助我们证明函数定理，而无需求助于扩展性。
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +**等一下**，我确信你正在想。**我从未证明过我的函数的什么屎**。我敢打赌，事实上，你有过。而且你会**无时无刻**这么做。你总在说服自己，你的函数正在正常工作。你的代码可能不是正式的证明（可能会导致一些 BUG），但是对代码进行推理是软件开发人员一直在做的事情。他们通过在脑海中回放代码来查看其行为。
```suggestion
**等一下**，我确信你正在想。**我从未证明过我的函数的什么垃圾东西**。我敢打赌，事实上，你有过。而且你会**无时无刻**这么做。你总在说服自己，你的函数正在正常工作。你的代码可能不是正式的证明（可能会导致一些 BUG），但是对代码进行推理是软件开发人员一直在做的事情。他们通过在脑海中回放代码来查看其行为。
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +我确实知道，学习 Scheme/Lisp/Racket 比学习Python困难一点点（但是比学习 Java/JavaScript 容易得多）。但是，如果你这样做的话，你将成为一个更好的程序员，并且你将逐渐体会到这些语言的美，以至于再没有其他语言能满足你。
```suggestion
我当然知道，学习 Scheme / Lisp / Racket 比学习 Python 困难那么一点点（但是比学习 Java / JavaScript 要容易得多）。但是，如果真的学习了这些，我想，你将成为一个更好的程序员，并且你将逐渐体会到这些语言的美，以至于再没有其他语言能满足你。
```

php第一的感觉

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +最后，还有性能问题。首先，让我们解决常见的误解：Lisp**不**是解释语言。它**不**慢，并且所有实现都有很多杠杆来调整**大部分**程序的性能。在某些情况下，程序可能需要诸如 **C** 和 **C++** 之类的更快语言的帮助，因为它们更接近硬件，但是有了更快的硬件，即使这种区别也变得无关紧要了。这些语言是生产质量代码的完美选择，并且由于在此之上数十年的工作，它们可能比现有的大多数其他选
```suggestion
最后，还有性能问题。首先，让我们解决常见的误解：Lisp **不**是解释语言。它**不**慢，并且所有实现都有很多杠杆来调整**大部分**程序的性能。在某些情况下，程序可能需要诸如 **C** 和 **C++** 之类的更快语言的帮助，因为它们更接近硬件，但是有了更快的硬件，即使这种区别也变得无关紧要了。这些语言是生产质量代码的完美选择，并且由于在此之上数十年的工作，它们可能比现有的大多数其他选择更稳定。
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +另一个缺点是随着API的在互联网上的崛起，大多数厂商都在为互联网的常见语言（Java、Ruby、Python、JavaScript, and 最近的 Go 和 Rust）发布库，但是从来不会为 Scheme/Lisp/Racket 发布，除非是社区贡献的，在 C/C++ 中也很少。这通常使我不得不自己构建一个 API 层，这当然不是很实用。Racket (这是我目前的最爱)，有一个非常活跃的社区
```suggestion
另一个缺点是随着API的在互联网上的崛起，大多数厂商都在为互联网的常见语言（Java、Ruby、Python、JavaScript, 和最近的 Go 和 Rust）发布库，但是从来不会为 Scheme / Lisp / Racket 发布，除非是社区贡献的，在 C / C++ 中也很少。这通常使我不得不自己构建一个 API 层，这当然不是很实用。Racket (这是我目前的最爱)，有一个非常活跃的社区，确实做出了很多巨大的贡献，但是它通常微微落后于时代，在谈到最新和最棒的时候，我罕被人提及。这可能是我将来采用 Clojure 的主要原因，但这仍有待观察。
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +和每一种偏见一样，我的也有短板。在大约 15 年前，所有的第三方 SDK 都是完全使用 C/C++ 编写的，可以轻松与 Lisp 互操作。Java 的到来泼了一盆冷水，因为 JVM 不能很好地与 Scheme/Lisp/Racket 互操作。这使得在不做大量工作的情况下将第三方库合并到我的程序中变得越来越难。
```suggestion
和每一种偏见一样，我的也有短板。在大约 15 年前，所有的第三方 SDK 都是完全使用 C / C++ 编写的，可以轻松与 Lisp 互操作。Java 的到来泼了一盆冷水，因为 JVM 不能很好地与 Scheme / Lisp / Racket 互操作。这使得在不做大量工作的情况下将第三方库合并到我的程序中变得越来越难。
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +这就是为什么我仍然使用 Scheme/Racket/Lisp 并可能在我的余生中继续使用的原因。我会使用其他语言吗？当然——很多。他们中没有一个能和前面几位相比。**尤其是比较新的那几个。**看起来发明新的语言对于新一代的孤陋寡闻的软件工程师是一种锻炼当老的语言**远远**好于他们做梦能想到的任何东西(我向你介绍名义上也起源于 List 的 Ruby，但也引出了一个问题：**为什么你不直接用 L
```suggestion
这就是为什么我仍然使用 Scheme / Racket / Lisp 并可能在我的余生中继续使用的原因。我会使用其他语言吗？当然——很多。他们中没有一个能和前面几位相比。**尤其是比较新的那几个。**看起来发明新的语言对于新一代的孤陋寡闻的软件工程师是一种锻炼当老的语言**远远**好于他们做梦能想到的任何东西(我向你介绍名义上也起源于 List 的 Ruby，但也引出了一个问题：**为什么你不直接用 Lisp 本身**)。
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +没有中缀运算，没有运算符优先级，没有关联性，没有伪分隔符，没有悬空的 else，什么也没有。所有函数式应用都是前缀式的，因此你不会说“(a + b)”，而是说“(+ a b)”，这更进一步会允许你灵活地说出类似“(+ a b c)”这样的东西。“+”仅仅是一个你可以随意重新定义的函数的名字。
```suggestion
没有中缀运算，没有运算符优先级，没有关联性，没有伪分隔符，没有独立的 else，什么也没有。所有函数式应用都是前缀式的，因此你不会说“(a + b)”，而是说“(+ a b)”，这更进一步会允许你灵活地说出类似“(+ a b c)”这样的东西。“+”仅仅是一个你可以随意重新定义的函数的名字。
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +因此，再次的，Scheme/Lisp/Racket **当我需要它们时**给我类型的优点，但不会在所有地方强加约束两全其美。
```suggestion
因此，再次的，Scheme / Lisp / Racket **当我需要它们时**给我类型的优点，但不会在所有地方强加约束两全其美。
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +但是，像所有其他东西一样，有时你需要静态地理解类型。例如，我经常处理图像，如果知道他们是 `array[byte]` 会有帮助，而且我预焙了可以魔术般快速处理它们的操作。Scheme/Lisp/Racket 都提供了**在需要时**能够做到这一点的方式。在 Scheme 中，它取决于实现方式，但是 Racket 自带一个 `Typed Racket` 变体，可以与动态类型变体混合使用。Commo
```suggestion
但是，像所有其他东西一样，有时你需要静态地理解类型。例如，我经常处理图像，如果知道他们是 `array[byte]` 会有帮助，而且我预焙了可以魔术般快速处理它们的操作。Scheme / Lisp / Racket 都提供了**在需要时**能够做到这一点的方式。在 Scheme 中，它取决于实现方式，但是 Racket 自带一个 `Typed Racket` 变体，可以与动态类型变体混合使用。Common Lisp 允许在特定的上下文中声明类型，主要是为了让编译器在可能的情况下实现优化。
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +但是在最近的几十年中它具有了新的含义：静态类型是编译时错误检查的一种形式，因此它将帮助你产生质量更高的代码。就好像静态类型是神奇的定理证明，能够验证程序的某些深层属性一样。这就是我称之为**bullsh*t**的地方。我从未见过任何一种静态类型检查器（无论它有多复杂）能帮助我防止发生明显的错误（你还是应该在测试中捕获它）。
```suggestion
但是在最近的几十年中它具有了新的含义：静态类型是编译时错误检查的一种形式，因此它将帮助你产生质量更高的代码。就好像静态类型是神奇的定理证明，能够验证程序的某些深层属性一样。这就是我称之为**垃圾**的地方。我从未见过任何一种静态类型检查器（无论它有多复杂）能帮助我防止发生明显的错误（你还是应该在测试中捕获它）。
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +那些知道 λ 演算细节得人可能已经知道我为什么选择做这种区分。Remember my history: 我小试牛刀的 Miranda 是一种**惰性**函数式语言（和 Haskell 一样）。这意味着**只有**在需要表达式的值时才对它们进行求值。这也是 λ 演算最原始的定义。这意味着，函数的参数在使用时进行求值，而非在调用函数时。
```suggestion
那些知道 λ 演算细节得人可能已经知道我为什么选择做这种区分。请想想我的印迹，我小试牛刀的 Miranda 是一种**惰性**函数式语言（和 Haskell 一样）。这意味着**只有**在需要表达式的值时才对它们进行求值。这也是 λ 演算最原始的定义。这意味着，函数的参数在使用时进行求值，而非在调用函数时。
```

2021-02-12 13:13 UTC, PassionPenguin commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +这就是原因之一。Scheme/Racket 是基于 λ 演算的编程语言的合理实现。你可能已经注意到，我没有使用“函数式”一词来描述 Scheme。那是因为虽然它主要是函数式的，但并不会一直偏向不可变性。尽管不鼓励使用它，Scheme 意识到在某些真实环境下可能会需要变异（mutation），并且它允许在不需要辅助装置的情况下使用它。在这里，我不会与纯粹主义者争论为什么这是或者不是一个好主意，但这
```suggestion
这就是原因之一。Scheme / Racket 是基于 λ 演算的编程语言的合理实现。你可能已经注意到，我没有使用“函数式”一词来描述 Scheme。那是因为虽然它主要是函数式的，但并不会一直偏向不可变性。尽管不鼓励使用它，Scheme 意识到在某些真实环境下可能会需要变换（mutation），并且它允许在不需要辅助装置的情况下使用它。在这里，我不会与纯粹主义者争论为什么这是或者不是一个好主意，但这与我稍后将在本文中讨论的内容有关。
```

2021-02-22 12:47 UTC, JackEggie commented
校对认领 @lsvih

2021-02-22 14:08 UTC, lsvih commented
@JackEggie 欢迎校对！

2021-02-26 10:29 UTC, JackEggie requested changes
@lsvih @elliott-zhao 校对完成。整体翻译得不错。提供了一些小的改进意见，欢迎探讨。

2021-02-26 10:29 UTC, JackEggie commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +换句话说，静态类型是没有意义的它可能具有某些文档价值，但不能替代其他不变式的文档。例如，你的不变式可能是你想要有一个单调递增的数值数组，它的均值是多少多少，它的标准差是多少多少。任何一种静态类型检查能让你做得最好也也不过是让你定义一个  `array[float]`。其余的不变式必须用文字解释作为函数的文档。那么你为什么还要让自己忍受 `array[float]` 的痛苦呢?
```suggestion
换句话说，静态类型是没有意义的。它可能具有某些文档价值，但不能替代其他不变式的文档。例如，你的不变式可能是你想要有一个单调递增的数值数组，它的均值是某个值，它的标准差则是另一个值。任何一种静态类型检查能让你做得最好也也不过是让你定义一个  `array[float]`。其余的不变式必须用文字解释作为函数的文档。那么你为什么还要让自己忍受 `array[float]` 的痛苦呢？
```
用“多少多少”过于口语化了哈

2021-02-26 10:29 UTC, JackEggie commented on article/2021/why-i-still-lisp-and-you-should-too.md
>  ---
分割线位置错误，应该在 124 行和 126 行之间。见[原文](https://medium.com/better-programming/why-i-still-lisp-and-you-should-too-18a2ae36bd8).

2021-02-26 10:29 UTC, JackEggie commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +因此，再次的，Scheme / Lisp / Racket **当我需要它们时**给我类型的优点，但不会在所有地方强加约束两全其美。
```suggestion
因此，再次的，Scheme / Lisp / Racket **当我需要它们时**给我类型的优点，但不会在所有地方强加约束。两全其美。
```

2021-02-26 10:29 UTC, JackEggie commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +最后，我们来到了我使用 Lisp 的最重要原因之一。对于之前没有听说过 S 表达式的人来说，它代表 Lisp 和它的后代中的一种特殊语法选择。所有句法形式都是**原子**或**列表**。原子是诸如名称（符号），数字，字符串和布尔值之类的东西。而列表看起来像是“(...)”，列表里面的内容也是列表或者原子，而且很棒的事还有一个空列表“()”。就是这样。
```suggestion
最后，我们来到了我使用 Lisp 的最重要原因之一。对于之前没有听说过 S 表达式的人来说，它代表 Lisp 和它的后代中的一种特殊语法选择。所有句法形式都是**原子**或**列表**。原子是诸如名称（符号），数字，字符串和布尔值之类的东西。而列表看起来像是“(...)”，列表里面的内容也是列表或者原子，而且很棒的是还有一个空列表“()”。就是这样。
```

2021-02-26 10:29 UTC, JackEggie commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +这种语法形式的最大优点是极简主义——你不需要虚假的语法结构即可传达概念。概念通过函数的名称或者语法关键词传达。这产生了奇特而紧凑的代码。在字符数方面并不一定总是紧凑的，但是在阅读代码时需要记住的概念数量上却很紧凑。
```suggestion
这种语法形式的最大优点是极简主义 —— 你不需要虚假的语法结构即可传达概念。概念通过函数的名称或者语法关键词传达。这产生了奇特而紧凑的代码。在字符数方面并不一定总是紧凑的，但是在阅读代码时需要记住的概念数量上却很紧凑。
```
见[破折号前后需要增加一个空格](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E7%A0%B4%E6%8A%98%E5%8F%B7%E5%89%8D%E5%90%8E%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E4%B8%80%E4%B8%AA%E7%A9%BA%E6%A0%BC)

2021-02-26 10:29 UTC, JackEggie commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +甚至还不到一半。如果你的程序是树形的，那么你就可以编写程序来操作这些树。Lisper（还有 Schemer 和 Racketeer）称之为**宏**或者**语法扩展**。换句话来说，你可以扩展你的语言的语法来引入新的抽象。
```suggestion
它还有更多优点。如果你的程序是树形的，那么你就可以编写程序来操作这些树。Lisper（还有 Schemer 和 Racketeer）称之为**宏**或者**语法扩展**。换句话来说，你可以扩展你的语言的语法来引入新的抽象。
```

2021-02-26 10:29 UTC, JackEggie commented on article/2021/why-i-still-lisp-and-you-should-too.md
>  ---
分割线位置错误，应该在 142 行和 144 行之间。见[原文](https://medium.com/better-programming/why-i-still-lisp-and-you-should-too-18a2ae36bd8).

2021-02-26 10:29 UTC, JackEggie commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +这就是为什么我仍然使用 Scheme / Racket / Lisp 并可能在我的余生中继续使用的原因。我会使用其他语言吗？当然——很多。他们中没有一个能和前面几位相比。**尤其是比较新的那几个。**看起来发明新的语言对于新一代的孤陋寡闻的软件工程师是一种锻炼当老的语言**远远**好于他们做梦能想到的任何东西(我向你介绍名义上也起源于 Lisp 的 Ruby，但也引出了一个问题：**为什么你不直
```suggestion
这就是为什么我仍然使用 Scheme / Racket / Lisp 并可能在我的余生中继续使用的原因。我会使用其他语言吗？当然 —— 很多。他们中没有一个能和前面几位相比。**尤其是比较新的那几个。**看起来发明新的语言对于新一代的孤陋寡闻的软件工程师是一种锻炼，而老的语言**远远**好于他们做梦能想到的任何东西(我向你介绍名义上也起源于 Lisp 的 Ruby，但也引出了一个问题：**为什么你不直接用 Lisp 本身**)。
```
见[破折号前后需要增加一个空格](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E7%A0%B4%E6%8A%98%E5%8F%B7%E5%89%8D%E5%90%8E%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E4%B8%80%E4%B8%AA%E7%A9%BA%E6%A0%BC)

2021-02-26 10:29 UTC, JackEggie commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +另一个缺点是随着API的在互联网上的崛起，大多数厂商都在为互联网的常见语言（Java、Ruby、Python、JavaScript, and 最近的 Go 和 Rust）发布库，但是从来不会为 Scheme / Lisp / Racket 发布，除非是社区贡献的，在 C / C++ 中也很少。这通常使我不得不自己构建一个 API 层，这当然不是很实用。Racket (这是我目前的最爱)，有一个非
```suggestion
另一个缺点是随着 API 的在互联网上的崛起，大多数厂商都在为互联网的常见语言（Java、Ruby、Python、JavaScript，和最近的 Go 和 Rust）发布库，但是从来不会为 Scheme / Lisp / Racket 发布，除非是社区贡献的，在 C / C++ 中也很少。这通常使我不得不自己构建一个 API 层，这当然不是很实用。Racket (这是我目前的最爱)，有一个非常活跃的社区，确实做出了很多巨大的贡献，但是它通常微微落后于时代。而一旦涉及最新和最棒的代码库，我只能自己来收拾这个烂摊子。这可能是我将来采用 Clojure 的主要原因，但这仍有待观察。
```

2021-03-01 02:34 UTC, elliott-zhao commented on article/2021/why-i-still-lisp-and-you-should-too.md
>  ---
这个分割线，我看原始的md里面就是在此处，所以我没有移动它。前后文中也会有这样的分割线存在，也和原文的位置不同。我觉得，此处分割线的作用和原文中分割每个主题的作用可能不太一致。

2021-03-01 02:45 UTC, JackEggie commented on article/2021/why-i-still-lisp-and-you-should-too.md
>  ---
@lsvih 这个你来定夺吧 😅

2021-03-01 02:59 UTC, elliott-zhao commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +在本文中，我试图解释和探索，为什么会这样。是因为我是一个不会改变自己路径的老恐龙吗？是我对新想法太过傲慢和鄙夷吗？或者我只是累了？答案，我认为，不在这上面几点。我觉得它是完美的，而且还**没有**什么可以推翻这一点。
您的版本非常棒，但是全文都要适应新的风格，工作量似乎有点大（也是我中文水平有限）。所以，就先这样，只要能表达出原来的意思，也算差强人意了吧。

2021-03-01 02:59 UTC, lsvih commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +> * 校对者：[PassionPenguin](https://github.com/PassionPenguin)
增加另一位校对者信息

2021-03-01 02:59 UTC, lsvih commented on article/2021/why-i-still-lisp-and-you-should-too.md
> +虽然我真正使用的 Lisp 的变种有很多（Scheme, Common Lisp, Racket, Lisp-for-Erlang），但核心总是保持一致的：一种基于 S 表达式的、动态类型的、主要是函数式的、值传递的基于 λ 演算的语言。
```suggestion
虽然我真正使用的 Lisp 的变种有很多（Scheme、Common Lisp、Racket、Lisp-for-Erlang），但核心总是保持一致的：一种基于 S 表达式的、动态类型的、主要是函数式的、值传递的基于 λ 演算的语言。
```

2021-03-01 03:01 UTC, lsvih commented
@elliott-zhao 麻烦您加一下另一位校对者的信息哈，那个分割线得麻烦您全部删掉，是我录入 md 文件时候的疏忽

2021-03-01 05:10 UTC, elliott-zhao commented on article/2021/why-i-still-lisp-and-you-should-too.md
>  ---
和前文一样，很多分割线的位置都是在每一个主题上面一点，我觉得这个分割线是有特殊用意的……吧？

2021-03-01 05:13 UTC, elliott-zhao commented on article/2021/why-i-still-lisp-and-you-should-too.md
>  ---
额……刚刚看到老大说要删掉所有分割线。

2021-03-01 07:12 UTC, lsvih approved these changes

2021-03-01 07:13 UTC, lsvih commented
@JackEggie 还得麻烦您确认一下 review 状态哈，如果文章没有别的问题了可以把状态改成 approve

2021-03-01 07:24 UTC, JackEggie approved these changes

2021-03-01 07:29 UTC, merged

2021-03-01 07:29 UTC, lsvih commented
@elliott-zhao  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi