为什么 Service Mesh 应该淡出人们的视野
xitu/gold-miner pull request #8035
Opened 2021-02-14 12:35 UTC by nettee

译文翻译完成，resolve #7997

2021-02-17 13:05 UTC, PassionPenguin requested changes
ψ(｀∇´)ψ 翻译挺棒哒

@lsvih @nettee

2021-02-17 13:05 UTC, PassionPenguin commented on article/2021/why-the-service-mesh-should-fade-out-of-sight.md
> +随着 Service Mesh 越来越受关注，很多软件开发与交付的专家在初次接触到 Service Mesh 的时候，会搞不清楚它与 API 网关的区别。Service Mesh 是自成一类产品，还是属于广义的 API 管理的一部分？这些问题并没有抓住重点，因为 Service Mesh 需要淡出人们的视野，成为开发平台的后台部分。
```suggestion
Service Mesh 越来越受到人们的关注，而很多软件开发与交付的专家在初次接触到 Service Mesh 的时候，会搞不清楚它与 API 网关的区别。Service Mesh 究竟是自成一类产品，还是属于广义的 API 管理的一部分？这些问题并没有抓住重点，因为 Service Mesh 需要逐渐淡入成为后端开发平台的一部分。
```

2021-02-17 13:05 UTC, PassionPenguin commented on article/2021/why-the-service-mesh-should-fade-out-of-sight.md
> ++ 传统的操作系统管理计算机的资源，为程序员提供更高级别的抽象，使其可以与复杂的底层硬件进行交互。操作系统的出现是为了解决手工编码直接与硬件进行交互所遇到的挑战。
```suggestion
+ 传统的操作系统管理计算机的资源，为程序员提供更高级别的抽象，使其可以与复杂的底层硬件进行交互。操作系统的出现是为了解决人工编码直接与硬件进行交互所遇到的困难。
```

2021-02-17 13:05 UTC, PassionPenguin commented on article/2021/why-the-service-mesh-should-fade-out-of-sight.md
> ++ Kubernetes 管理计算机集群的资源，为程序员提供更高级别的抽象，使其可以与复杂的底层硬件以及不稳定、不安全的网络进行交互。Kubernetes 的出现是为了解决手工编码直接与硬件集群进行交互所遇到的挑战。虽然按操作系统的标准来看，Kubernetes 还很原始，但随着它逐渐成熟，会让传统的操作系统（如 Linux 和 Windows）越来越不相关。
```suggestion
+ Kubernetes 管理计算机集群的资源，为程序员提供更高级别的抽象，使其可以与复杂的底层硬件以及不稳定、不安全的网络进行交互。Kubernetes 的出现是为了解决人工编码直接与硬件集群进行交互所遇到的挑战。虽然按操作系统的标准来看，Kubernetes 还很原始，但随着它逐渐成熟，会与传统的操作系统（如 Linux 和 Windows）越来越不相关。
```

2021-02-17 13:05 UTC, PassionPenguin commented on article/2021/why-the-service-mesh-should-fade-out-of-sight.md
> +Service Mesh 是用于分布式计算的现在动态链接器。在传统的编程中，引入另一个模块需要在你的集成开发环境（IDE）中导入一个库。在部署时，操作系统的动态链接器会在运行时将你的程序与库进行连接。动态链接器还会负责发现库、验证调用库的安全性，以及建议与库的连接。在微服务架构中，你的“库”是到另一个微服务的网络跳转，而找到那个“库”并与之建立安全连接则是 Service Mesh 的工作。
```suggestion
Service Mesh 是用于分布式计算的现代动态链接器。在传统的编程中，引入另一个模块需要在你的集成开发环境（IDE）中导入一个库。在部署时，操作系统的动态链接器会在运行时将你的程序与库进行连接。动态链接器还会负责寻找调用库、验证调用库的安全性，以及建立与调用库的链接。在微服务架构中，你的“库”是到另一个微服务的网络跳转，而找到那个“库”并与之建立安全连接则是 Service Mesh 的工作。
```

2021-02-17 13:05 UTC, PassionPenguin commented on article/2021/why-the-service-mesh-should-fade-out-of-sight.md
> +正如开发和运维团队完全不必考虑动态链接器一样（它完全不怎么需要照看），现代的分布式团队也不应该去照看一个复杂的 Service Mesh。今天我们看到 Service Mesh 成为第一类的基础架构，这已经是很大的进步了。不过这存在一个问题：Service Mesh 太显眼了。
```suggestion
正如开发和运维团队完全不必考虑动态链接器一样（这几乎不怎么需要照看），现代的分布式团队也不应该去照看一个复杂的 Service Mesh。今天我们看到 Service Mesh 成为第一类的基础架构，这已经是很大的进步了。不过这存在一个问题：Service Mesh 还是太显眼了。
```

2021-02-21 05:42 UTC, nettee commented on article/2021/why-the-service-mesh-should-fade-out-of-sight.md
> +> * 校对者：[PassionPenguin](https://github.com/PassionPenguin)
@PassionPenguin 确认一下校对者信息

2021-02-21 05:42 UTC, nettee commented
根据校对修改完成 @PassionPenguin @lsvih

2021-02-24 15:09 UTC, PassionPenguin commented on article/2021/why-the-service-mesh-should-fade-out-of-sight.md
> +> * 校对者：[PassionPenguin](https://github.com/PassionPenguin)
没毛病的直接写用户名就好啦

2021-03-14 12:49 UTC, 1autodidact commented
@lsvih 认领校对

2021-03-14 12:56 UTC, lsvih commented
@1autodidact 欢迎校对~

2021-03-14 14:26 UTC, 1autodidact requested changes
@nettee @lsvih 校对完成(第一次校对哈哈)

2021-03-14 14:26 UTC, 1autodidact commented on article/2021/why-the-service-mesh-should-fade-out-of-sight.md
> +当然，这样的目标是几乎无法达成的。网络调用比内存中的库链接要复杂得多。不过，问题的关键在于，Service Mesh 应该尽可能地对开发运维团队不可见。它应该**尽力**达到这一黄金标准，即使它也许永远都不能 100% 实现这个目标。
```suggestion
当然，这样的目标是几乎无法达成的。网络调用比内存中的库链接要复杂得多。不过，问题的关键在于，Service Mesh 应该尽可能地对开发运维团队不可见。它应该**尽力**达到这一黄金标准，即使它永远不可能 100% 达到这个目标。
```

2021-03-14 14:26 UTC, 1autodidact commented on article/2021/why-the-service-mesh-should-fade-out-of-sight.md
> +对比一下链接到库的真实体验：你在你的 IDE 中引用了这个库，然后编译、运行。完成。这也应该成为 Service Mesh 的黄金标准。
```suggestion
对比一下链接到库的真实体验：你从你的IDE中引用库，构建，然后部署。这样就完成了。这也应该成为 Service Mesh 的黄金标准。
```

2021-03-14 14:26 UTC, 1autodidact commented on article/2021/why-the-service-mesh-should-fade-out-of-sight.md
> +想象一下，Service Mesh 的安装、配置、运维都需要导入一个 JAR 或者 DLL 库，这个过程中的开发者体验如何？如果在传统软件开发中，诊断线上问题必须理解操作系统的动态链接器的内部架构，那又会是怎样的情景？我想你一定会说：“那也太痛苦了！”
```suggestion
想象一下，在开发人员的体验中，导入一个 JAR 或 DLL 库需要一个服务网状结构所需的所有安装、配置和操作支持。如果还需要了解操作系统动态链接器的内部架构来诊断运行时的问题 ？我想你一定会说："那也太痛苦了！"
```

2021-03-14 14:26 UTC, 1autodidact commented on article/2021/why-the-service-mesh-should-fade-out-of-sight.md
> ++ Kubernetes 管理计算机集群的资源，为程序员提供更高级别的抽象，使其可以与复杂的底层硬件以及不稳定、不安全的网络进行交互。Kubernetes 的出现是为了解决人工编码直接与硬件集群进行交互所遇到的挑战。虽然按操作系统的标准来看，Kubernetes 还很原始，但随着它逐渐成熟，会与传统的操作系统（如 Linux 和 Windows）越来越不相关。
```suggestion
+ Kubernetes 管理计算机集群的资源，为程序员提供更高级别的抽象，使其可以与复杂的底层硬件以及不稳定、不安全的网络进行交互。Kubernetes 的出现是为了解决人工编码直接与硬件集群进行交互所遇到的挑战。虽然按操作系统的标准来看，Kubernetes 还很原始，但随着它逐渐成熟，它将会使传统的操作系统（如 Linux 和 Windows）越来越无关紧要。
```

2021-03-28 12:13 UTC, nettee reviewed
根据校对意见修改

2021-03-28 12:53 UTC, lsvih commented
@nettee 麻烦您添加一下另一位校对者的信息哈~

2021-03-29 08:41 UTC, nettee commented
> @nettee 麻烦您添加一下另一位校对者的信息哈~

已添加

2021-03-29 08:44 UTC, lsvih approved these changes

2021-03-29 08:44 UTC, merged

2021-03-29 08:44 UTC, lsvih commented
@nettee  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-04-06 03:58 UTC, 1autodidact commented
@lsvih 大佬为啥篇文章在掘金里面搜不到啊

2021-04-06 06:22 UTC, lsvih commented
@1autodidact 作者还没发。。

2021-04-08 16:57 UTC, 1autodidact commented
@nettee 记得发文章到掘金领积分哦

2021-04-09 08:56 UTC, husiyu commented
> @nettee 记得发文章到掘金领积分哦

发布了  https://juejin.cn/post/6949078735404400677/

2021-04-10 05:31 UTC, lsvih commented
收到