Translation/nginx concepts i wish i knew years ago
xitu/gold-miner pull request #8046
Opened 2021-02-17 07:37 UTC by joyking7

译文翻译完成，resolve #8011 
本文是 Nginx 入门内容，原文充满了许多语气词，这些翻译可能把控的不是很好，希望大家校对的时候能帮忙指正，谢谢~
另外原文标题级别有部分使用不是很恰当，因此修改了部分标题的级别

2021-02-17 11:48 UTC, PassionPenguin requested changes
代码下面有多行，以及加粗变成加斜，以及一些标题还是错的奥，记得翻译注释

@lsvih @joyking7

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
建议把头图 https://res.cloudinary.com/practicaldev/image/fetch/s--B8sTzGjW--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/jldvigb958mnww2rvcvx.jpeg 给添加了

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +### 代理 vs 反向代理
应该是 二级标题 吧

```suggestion
## 代理 vs 反向代理
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +#### 代理
```suggestion
### 代理
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +好的，我们有客户端（>= 1）、一个中间 Web 服务器（在这种情况下，我们称它为代理）和一个服务器。这其中最主要的就是服务器不知道哪个客户端在请求。是不是有点困惑？让我用一张示意图来解释一下。
```suggestion
好的，我们有多个客户端、一个中间 Web 服务器（在这种情况下，我们称它为代理）和一个服务器。这其中最主要的就是服务器不知道哪个客户端在请求。是不是有点困惑？让我用一张示意图来解释一下。
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
>  ![https://res.cloudinary.com/practicaldev/image/fetch/s--tPAqn11I--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/1moanfdnfnh5d0dqs4wd.png](https://res.
建议保留原图 alt

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +在这种情况下，client1 和 client2 通过代理服务器向服务器发送请求 request1 和 request2，现在后台服务器不会知道 request1 和 request2 是由 client1 还是 client2 发送的，而只是执行操作。
```suggestion
在这种情况下，客户端 client1 和 client2 通过代理服务器向服务器发送请求 request1 和 request2，现在后台服务器不会知道 request1 和 request2 是由 client1 还是 client2 发送的，只会执行操作。
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +最简单的解释，反向代理就是把代理的工作反过来。比方说有一个客户端、一个中间 Web 服务器和若干后台服务器（>= 1），我们也通过一张示意图解释吧！
```suggestion
最简单的解释，反向代理就是把代理的工作反过来。比方说有一个客户端、一个中间 Web 服务器和若干后台服务器。让我们继续通过一张示意图解释吧！
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
>  ![https://res.cloudinary.com/practicaldev/image/fetch/s--iUfM34yx--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/64jk21oeqlki2t3bx1kz.png](https://res.
建议保留并翻译 alt 嗷

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
>  ![https://res.cloudinary.com/practicaldev/image/fetch/s--Ng8XRfi_--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/bb9kkupl1z9dpacex8vt.png](https://res.
嗷嗷

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +### 负载均衡
```suggestion
## 负载均衡
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +### 有状态应用 vs 无状态应用
```suggestion
## 有状态应用 vs 无状态应用
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +#### 有状态应用
```suggestion
### 有状态应用
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +#### 无状态应用
```suggestion
### 无状态应用
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +### 什么是 Nginx？
```suggestion
## 什么是 Nginx？
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +如果我们要使用诸如*轮询调度*这样的算法，Nginx 会这样做：比如 client2 发送了一个请求到 `https://localhost`，那么 Nginx 服务器会先把请求传到 3001 端口，然后把响应返回给客户端。对于另一个请求，Nginx 会把请求传到 3002 端口，以此类推。
```suggestion
如果我们要使用诸如**轮询调度**这样的算法，Nginx 会这样做：比如 client2 发送了一个请求到 `https://localhost`，那么 Nginx 服务器会先把请求传到 3001 端口，然后把响应返回给客户端。对于另一个请求，Nginx 会把请求传到 3002 端口，以此类推。
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +太多信息啦！但到这里，你应该已经清楚地了解了什么是 Nginx 及其相关术语。现在，我们将继续了解 Nginx 的安装和配置。
```suggestion
阿这也太多概念了吧！不过我想到了现在，你应该已经清楚地了解了什么是 Nginx 及其相关术语。现在，我们将继续了解 Nginx 的安装和配置。
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +终于到这一步了！如果你能理解 Nginx 概念并看到了代码这部分，我为你感到灰常自豪。
噗

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +好的，让我告诉你，老实说，在任何操作系统上安装 Nginx 都只需要一行命令。我是 Mac OSX 用户，所以会基于它来写命令。但对于 [ubuntu](https://ubuntu.com/tutorials/install-and-configure-nginx#2-installing-nginx) 和 [windows](https://www.maketecheasier.com/in
```suggestion
好的，让我告诉你，老实说，在任何操作系统上安装 Nginx 都只需要一行命令。我是 Mac OSX 用户，所以会基于它来写命令。但对于 [Ubuntu](https://ubuntu.com/tutorials/install-and-configure-nginx#2-installing-nginx) 和 [Windows](https://www.maketecheasier.com/install-nginx-server-windows/) 以及其他 Linux 发行版，也有类似的操作。
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
>  ![https://res.cloudinary.com/practicaldev/image/fetch/s--7rgP-NQB--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/4mju73ad1f22gy1ni3gu.gif](https://res.cl
嗷嗷

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +### 安装过程
```suggestion
## 安装过程
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
多行啦

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +同时，在 *html* 和 *md* 文件中写上基本的上下文内容。
```suggestion
同时，在 **html** 和 **md** 文件中写上基本的上下文内容。
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +现在回到正规。我们可以通过修改位于 `usr/local/etc/nginx` 路径下的 `nginx.conf` 文件，实现对 Nginx 默认配置的任何改动。另外，我的系统中有 Vim，所以我使用 Vim 进行修改，你也可以自由使用所选的编辑器。
```suggestion
现在回到正规。我们可以通过修改位于 `/usr/local/etc/nginx` （译者注：默认安装路径）路径下的 `nginx.conf` 文件，实现对 Nginx 默认配置的任何改动。另外，我的系统中有 Vim，所以我将用 Vim 进行修改，你也可以自由使用所选的编辑器。
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
多了！

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
>  $ vim nginx.conf
哈哈哈vi就行了这个原作者也太不会省事（

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
多行啦

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +这将打开一个默认的 Nginx 配置文件，我真的不想使用它的默认配置。因此，我通常会复制这个配置文件，然后对原文件进行修改。在这里我们也这样做。
```suggestion
这将打开一个默认的 Nginx 配置文件，但我真的不想使用它的默认配置。因此，我通常会复制这个配置文件，然后对原文件进行修改。在这里我们也这样做。
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +1. 添加一个基本配置。添加 `events {}` 是必须的，因为对于 Nginx 架构来讲，它通常被用来表示 worker 的数量。我们在这里使用 `http` 来告诉 Nginx，我们将使用 [OSI 模型](https://bit.ly/2LGdbYB) 的第 7 层。
```suggestion
1. 添加一个基本配置。添加 `events {}` 是必须的，因为对于 Nginx 架构来讲，它通常被用来表示 Worker 的数量。我们在这里使用 `http` 来告诉 Nginx，我们将使用 [OSI 模型](https://bit.ly/2LGdbYB) 的第 7 层。
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +### 额外的 Nginx 命令！
```suggestion
## 额外的 Nginx 命令！
```

2021-02-17 11:48 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
> +要 kill 一个进程，你需要 PID，然后用下面的命令 kill 它：
```suggestion
要 kill 一个进程，你需要先知道它的 PID，然后用下面的命令 kill 它：
```

2021-02-18 16:49 UTC, joyking7 commented on article/2021/Nginx concepts I wish I knew years ago.md
为了不影响校对效率，头图和图片居中在内容review之后统一添加，感谢~

2021-02-18 16:50 UTC, joyking7 commented on article/2021/Nginx concepts I wish I knew years ago.md
> +终于到这一步了！如果你能理解 Nginx 概念并看到了代码这部分，我为你感到灰常自豪。
我也很无奈，改了一版卖萌的翻译

2021-02-18 17:04 UTC, PassionPenguin commented on article/2021/Nginx concepts I wish I knew years ago.md
>  在结束这篇文章之前，声明一下我所使用图片和视觉效果来自 Goole 图片和由 [Hussein Nasser](https://www.youtube.com/user/GISIGeometry) 提供的 Youtube 教程。
哦对了还有底部的那一段注释：）

https://github.com/xitu/gold-miner/blob/master/a-new-post-template.md

```markdown
> 如果发现译文存在错误或其他需要改进的地方，欢迎到 [掘金翻译计划](https://github.com/xitu/gold-miner) 对译文进行修改并 PR，也可获得相应奖励积分。文章开头的 **本文永久链接** 即为本文在 GitHub 上的 MarkDown 链接。

---

> [掘金翻译计划](https://github.com/xitu/gold-miner) 是一个翻译优质互联网技术文章的社区，文章来源为 [掘金](https://juejin.im) 上的英文分享文章。内容覆盖 [Android](https://github.com/xitu/gold-miner#android)、[iOS](https://github.com/xitu/gold-miner#ios)、[前端](https://github.com/xitu/gold-miner#前端)、[后端](https://github.com/xitu/gold-miner#后端)、[区块链](https://github.com/xitu/gold-miner#区块链)、[产品](https://github.com/xitu/gold-miner#产品)、[设计](https://github.com/xitu/gold-miner#设计)、[人工智能](https://github.com/xitu/gold-miner#人工智能)等领域，想要查看更多优质译文请持续关注 [掘金翻译计划](https://github.com/xitu/gold-miner)、[官方微博](http://weibo.com/juejinfanyi)、[知乎专栏](https://zhuanlan.zhihu.com/juejinfanyi)。
```

2021-02-19 12:17 UTC, joyking7 commented on article/2021/Nginx concepts I wish I knew years ago.md
>  在结束这篇文章之前，声明一下我所使用图片和视觉效果来自 Goole 图片和由 [Hussein Nasser](https://www.youtube.com/user/GISIGeometry) 提供的 Youtube 教程。
收到~

2021-02-20 19:02 UTC, ningzhy3 commented
校对认领@glowin

2021-02-21 00:06 UTC, lsvih commented
@ningzhy3 欢迎认领~

2021-02-21 22:04 UTC, ningzhy3 reviewed
@glowin @joyking7  校对完成

2021-02-24 00:46 UTC, ningzhy3 commented
@lsvih 完成校对

2021-02-28 18:35 UTC, joyking7 commented on article/2021/Nginx concepts I wish I knew years ago.md
> +如果我们要使用诸如**轮询调度**这样的算法，Nginx 会这样做：比如 client2 发送了一个请求到 `https://localhost`，那么 Nginx 服务器会先把请求传到 3001 端口，然后把响应返回给客户端。对于另一个请求，Nginx 会把请求传到 3002 端口，以此类推。
我认为只需要在第一次出现的时候备注一下即可，就像写论文那样

2021-02-28 18:53 UTC, joyking7 commented
@lsvih 修改完毕，同时增加了头图

2021-03-01 01:06 UTC, lsvih approved these changes

2021-03-01 01:07 UTC, lsvih commented
我改了文件名和两个链接，麻烦您更新一下本地的版本哈

2021-03-01 01:07 UTC, merged

2021-03-01 01:07 UTC, lsvih commented
@joyking7  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi