更新
xitu/gold-miner pull request #8078
Opened 2021-02-24 06:46 UTC by samyu2000

更新

2021-02-26 19:10 UTC, PassionPenguin requested changes
请修改代码，代码全是...坑
或者你别修改了，等到时候你push以后再去修改吧

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  function callMe(name) {
```js
function callMe(name) {
  console.log('Hello', name);
}

callMe = name => console.log('Hello', name);
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  // Longhand
```js
// Longhand
function test1() {
  console.log('test1');
};
function test2() {
  console.log('test2');
};
var test3 = 1;
if (test3 == 1) {
  test1();
} else {
  test2();
}
// Shorthand
(test3 === 1? test1:test2)();
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  Longhand:
显然是原作者写多了

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
```js
//longhand
function calculate(diameter) {
  return Math.PI * diameter
}
//shorthand
calculate = diameter => (
  Math.PI * diameter;
)
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  //Longhandfunction add(test1, test2) {
```js
//Longhand
function add(test1, test2) {
  if (test1 === undefined)
    test1 = 1;
  if (test2 === undefined)
    test2 = 2;
  return test1 + test2;
}
//shorthand
add = (test1 = 1, test2 = 2) => (test1 + test2);
add() //output: 3
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  //longhand// joining arrays using concat
```js
//longhand
// joining arrays using concat
const data = [1, 2, 3];
const test = [4 ,5 , 6].concat(data);
//shorthand
// joining arrays
const data = [1, 2, 3];
const test = [4 ,5 , 6, ...data];
console.log(test); // [ 4, 5, 6, 1, 2, 3]
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  //longhand
```js
//longhand

// cloning arrays
const test1 = [1, 2, 3];
const test2 = test1.slice()
//shorthand

// cloning arrays
const test1 = [1, 2, 3];
const test2 = [...test1];
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  //longhandconst welcome = 'Hi ' + test1 + ' ' + test2 + '.'//shorthandconst welcome = `Hi ${test1} ${test2}`;
```js
//longhand
const welcome = 'Hi ' + test1 + ' ' + test2 + '.'
//shorthand
const welcome = `Hi ${test1} ${test2}`;
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  Longhand:
同

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
漏了一个链接，请补上

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>           test test,test test test test`
```js
//longhand
const data = 'abc abc abc abc abc abc\n\t'
    + 'test test,test test test test\n\t'
//shorthand
const data = `abc abc abc abc abc abc
         test test,test test test test`
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  ```
```js
let test1 = 'a'; 
let test2 = 'b';
//Longhand 
let obj = {test1: test1, test2: test2}; 
//Shorthand 
let obj = {test1, test2};
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
漏了链接请补上

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  //longhandconst test1 = this.data.test1;
```js
//longhand
const test1 = this.data.test1;
const test2 = this.data.test2;
const test2 = this.data.test3;
//shorthand
const { test1, test2, test3 } = this.data;
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  const data = [{
```js
const data = [{
        type: 'test1',
        name: 'abc'
    },
    {
        type: 'test2',
        name: 'cde'
    },
    {
        type: 'test1',
        name: 'fgh'
    },
]
function findtest1(name) {
    for (let i = 0; i < data.length; ++i) {
        if (data[i].type === 'test1' && data[i].name === name) {
            return data[i];
        }
    }
}
//Shorthand
filteredData = data.find(data => data.type === 'test1' && data.name === 'fgh');
console.log(filteredData); // { type: 'test1', name: 'fgh' }
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
漏了链接请补上

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  // Longhand
```js
// Longhand
if (type === 'test1') {
  test1();
}
else if (type === 'test2') {
  test2();
}
else if (type === 'test3') {
  test3();
}
else if (type === 'test4') {
  test4();
} else {
  throw new Error('Invalid value ' + type);
}
// Shorthand
var types = {
  test1: test1,
  test2: test2,
  test3: test3,
  test4: test4
};
 
var func = types[type];
(!func) && throw new Error('Invalid value ' + type); func();
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  //longhandif(arr.indexOf(item) > -1) { // item found }if(arr.indexOf(item) === -1) { // item not found}//shorthandif(~arr.indexOf(item)) { // item found}if(!~arr.indexOf(item)) { // item not found}
```js
//longhand
if(arr.indexOf(item) > -1) { // item found 
}
if(arr.indexOf(item) === -1) { // item not found
}
//shorthand
if(~arr.indexOf(item)) { // item found
}
if(!~arr.indexOf(item)) { // item not found
}
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
漏了链接请补上

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  const data = { test1: 'abc', test2: 'cde', test3: 'efg' };
```js
const data = { test1: 'abc', test2: 'cde', test3: 'efg' };
const arr = Object.entries(data);
console.log(arr);
/** Output:
[ [ 'test1', 'abc' ],
  [ 'test2', 'cde' ],
  [ 'test3', 'efg' ]
]
**/
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  const data = { test1: 'abc', test2: 'cde' };
```js
const data = { test1: 'abc', test2: 'cde' };
const arr = Object.values(data);
console.log(arr);
/** Output:
[ 'abc', 'cde']
**/
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +注意：如果事先知道目标字符在字符串中的索引，我们可以直接使用该索引值。如果索引值不确定，运行时就有可能抛出 undefined。
```suggestion
// 注意：如果事先知道目标字符在字符串中的索引，我们可以直接使用该索引值。如果索引值不确定，运行时就有可能抛出 undefined。
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  str.charAt(2); // c//Shorthand
```suggestion
str.charAt(2); // c

//Shorthand 
```

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
>  //longhandMath.pow(2,3); // 8//shorthand2**3 // 8
...

2021-02-26 19:10 UTC, PassionPenguin commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +```
后文漏了5618字

2021-02-26 19:11 UTC, PassionPenguin commented
就是机译那篇文章也没有漏这么多啊... https://www.isolves.com/it/cxkf/yy/js/2021-01-11/35302.html = =

2021-03-05 07:02 UTC, Ashira97 commented
@lsvih 校对认领~

2021-03-05 07:03 UTC, lsvih commented
@Ashira97 好的~

2021-03-07 15:29 UTC, Ashira97 reviewed
@lsvih @samyu2000 校对完啦 ~

2021-03-07 15:29 UTC, Ashira97 commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +使用先进的速记技巧优化你的 JavaScript 代码
使用先进的速记技巧优化你的 JavaScript 代码
=> 使用现代语法中的缩写和语法糖优化你的 JavaScript 代码

2021-03-07 15:29 UTC, Ashira97 commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +在这里，我会介绍一些新的**速记方法**，它可以优化你的 JavaScript 代码，使代码更简洁。下面是一份 **JavaScript 偷懒法列表**，你需要了解一下。
速记方法 => 简写方法
下面是一份 **JavaScript 偷懒法列表**，你需要了解一下。 => 下面是一份你需要了解的 **JavaScript 偷懒法列表**。

2021-03-07 15:29 UTC, Ashira97 commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +# **2. If … else 的速记法**
建议在"速记"和“简写”中选择一种说法并保持全文统一~

2021-03-07 15:29 UTC, Ashira97 commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +当我们的 if-else 条件中的逻辑比较简单时，可以使用这种简洁的方式——三元条件运算符。
方式——三 => 方式 —— 三

2021-03-07 15:29 UTC, Ashira97 commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +Normal Value checks对正常值的检查
Normal Value checks对正常值的检查 => 对正常值的检查

2021-03-07 15:29 UTC, Ashira97 commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +我们在编码时可能需要处理很多算法，所以需要使用赋值运算符。以下是 JavaScript 中赋值运算符的应用。
我们在编码时可能需要处理很多算法，所以需要使用赋值运算符。
=>编程中使用算术运算符是很常见的情况。

2021-03-07 15:29 UTC, Ashira97 commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +注意：当 test1 为任何值时，程序都会执行 if(test1){ } 内的逻辑，这种写法在判断 NULL 或 undefined 值时普遍使用。
null 和 undefined 的大小写建议您统一一下 ~

2021-03-07 15:29 UTC, Ashira97 commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +More examples.再举个例子
原文好像没删除？

2021-03-07 15:29 UTC, Ashira97 commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +When we are dealing with a multi-line string in code we can go for this function:当我们在代码中处理多行文本时，可以使用这样的技巧
还是没删除原文哈...

2021-03-07 15:29 UTC, Ashira97 commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +当我们需要在一个对象数组中按属性值查找特定对象时，find 方法很有用。
`find`

2021-03-07 15:29 UTC, Ashira97 commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +# **31. 把一个字符串重复输出多次**
原文似乎没有提到输出...
=>把一个字符串重复多次

2021-03-07 15:29 UTC, Ashira97 commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +我们可以使用 for 循环把一个字符串反复输出多次，那这种功能有没有速记法呢？
我们可以使用 for 循环把一个字符串反复输出多次
=>我们可以使用 for 循环把一个字符串重复多次

2021-03-07 15:29 UTC, Ashira97 commented on article/2021/34-javascript-optimization-techniques-to-know-in-2021.md
> +```
结尾似乎缺了点什么？
> 如果发现译文存在错误或其他需要改进的地方，欢迎到 [掘金翻译计划](https://github.com/xitu/gold-miner) 对译文进行修改并 PR，也可获得相应奖励积分。文章开头的 **本文永久链接** 即为本文在 GitHub 上的 MarkDown 链接。

2021-03-10 06:38 UTC, lsvih approved these changes

2021-03-10 06:39 UTC, merged