重新审视 undefined 和 null
xitu/gold-miner pull request #8138
Opened 2021-03-04 11:58 UTC by PassionPenguin

译文翻译完成，resolve #8122

2021-03-04 16:40 UTC, MoonBall commented
认领翻译

2021-03-04 16:41 UTC, MoonBall commented
认领校对

2021-03-04 17:40 UTC, felixliao commented
认领校对

2021-03-05 01:29 UTC, lsvih commented
@MoonBall  @felixliao  欢迎校对~

2021-03-05 13:24 UTC, felixliao requested changes
校对完一遍，也许还需要一遍

2021-03-05 13:24 UTC, felixliao commented on article/2021/undefined-null-revisited.md
> +* 每个子类实现实例操作的不同模式。
```suggestion
* 每个子类的实例实现一种不同的模式。
```

2021-03-05 13:24 UTC, felixliao commented on article/2021/undefined-null-revisited.md
> +#### 可能的类型
```suggestion
#### “也许”类型
```

2021-03-05 13:24 UTC, felixliao commented on article/2021/undefined-null-revisited.md
> +Maybe 类型是一种函数编程技术：
```suggestion
“也许”类型是一种函数编程技术：
```

2021-03-05 13:24 UTC, felixliao commented on article/2021/undefined-null-revisited.md
> +我们本可以通过数组对 “有” 和 “无” 进行编码，好处是 TypeScript 很好地支持了这个方法（通过[歧视的联合](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminate-unions)）。
[可辨识联合](https://www.tslang.cn/docs/handbook/advanced-types.html)
```suggestion
我们本可以通过数组对 “有” 和 “无” 进行编码，好处是 TypeScript 很好地支持了这个方法（通过[可辨识联合](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminate-unions)）。
```

2021-03-05 13:24 UTC, felixliao commented on article/2021/undefined-null-revisited.md
> +* `undefined` 通常是在 JavaScript 中偶然出现的。
```suggestion
* `undefined` 通常是在 JavaScript 中意外出现的。
```

2021-03-05 13:24 UTC, felixliao commented on article/2021/undefined-null-revisited.md
> +### `undefined` 或 `null` 是一个忽略的值
```suggestion
### `undefined` 或 `null` 是一个被忽略的值
```

2021-03-05 13:24 UTC, felixliao commented on article/2021/undefined-null-revisited.md
> +例如，我们可能希望属性 `file.title` 是字符串或是忽略的值（即 `file` 没有标题），那么有几种方法可以实现此目的。
```suggestion
例如，我们可能希望属性 `file.title` 是字符串或是被忽略的值（即 `file` 没有标题），那么有几种方法可以实现此目的。
```

2021-03-05 13:24 UTC, felixliao commented on article/2021/undefined-null-revisited.md
> +#### `null` 是忽略值
```suggestion
#### `null` 是被忽略值
```

2021-03-05 13:24 UTC, felixliao commented on article/2021/undefined-null-revisited.md
> +### 其他处理忽略值的方法
```suggestion
### 其他处理被忽略值的方法
```

2021-03-05 14:54 UTC, felixliao reviewed
@PassionPenguin @lsvih 校对完毕

2021-03-05 14:54 UTC, felixliao commented on article/2021/undefined-null-revisited.md
> +在 JavaScript 中同时有两个表示非值的值现在被认为是一个设计错误（哪怕是 JS 之父 Brendan Eich 也这么认为）。
```suggestion
在 JavaScript 中同时有两个表示非值的值现在被认为是一个设计错误（哪怕是 JavaScript 之父 Brendan Eich 也这么认为）。
```

2021-03-05 14:54 UTC, felixliao commented on article/2021/undefined-null-revisited.md
> +在 Java（影响了 JS 很多方面的语言）中初始值依赖于一个变量的静态类型：
```suggestion
在 Java（影响了 JavaScript 很多方面的语言）中初始值依赖于一个变量的静态类型：
```

2021-03-05 14:54 UTC, felixliao commented on article/2021/undefined-null-revisited.md
> +如果一个属性 `.unknownProp` 缺失了，访问这个属性会赋予这个属性 `undefined` 值：
```suggestion
如果一个属性 `.unknownProp` 不存在，访问这个属性就会生成 `undefined` 值：
```

2021-03-05 14:54 UTC, felixliao commented on article/2021/undefined-null-revisited.md
> +如果一个函数没有指定任何内容的返回，那么默认就会返回 `undefined`：
```suggestion
如果一个函数没有明确返回任何内容，那么默认就会返回 `undefined`：
```

2021-03-06 01:20 UTC, MoonBall commented on article/2021/undefined-null-revisited.md
> +* 我们希望我们的代码结实而无声（？）地对待 `undefined` 和 `null`。
robustly 一般指鲁棒性~
silently 是指不报错

我们希望我们的代码足够鲁棒且不报错地对待 `undefined` 和 `null`。

2021-03-06 01:20 UTC, MoonBall commented on article/2021/undefined-null-revisited.md
> +* 我们需要一个非值，表示被忽略。
非值 => 空值

2021-03-06 03:03 UTC, PassionPenguin commented on article/2021/undefined-null-revisited.md
> +* `null` 表示任何有意而为的对象值的缺省缺失。<sup>[出处](https://tc39.es/ecma262/#sec-null-value)</sup>
```suggestion
* `null` 表示任何有意地缺省对象值。<sup>[出处](https://tc39.es/ecma262/#sec-null-value)</sup>
```

2021-03-06 03:03 UTC, PassionPenguin commented on article/2021/undefined-null-revisited.md
> +如果一个函数拥有一个 `return` 语句但没有任何附属语句，那么也是默认返回 `undefined`：
```suggestion
如果一个函数拥有一个 `return` 语句但没有指定任何返回值，那么也会默认返回 `undefined`：
```

2021-03-06 03:03 UTC, PassionPenguin commented on article/2021/undefined-null-revisited.md
> +一个对象的圆形是一个对象，或者是一系列原型的末尾 `null`，那么 `Object.prototype` 就没有一个原型：
```suggestion
一个对象的原型要么是另一个对象，要么是原型链末尾的 `null`。`Object.prototype` 没有原型：
```

2021-03-06 03:03 UTC, PassionPenguin commented on article/2021/undefined-null-revisited.md
> +### `undefined` 以及参数缺省值
好嘞

2021-03-06 03:03 UTC, PassionPenguin commented on article/2021/undefined-null-revisited.md
> +那个 `undefined` 还会触发参数默认值的条件，指向它的一个元值。
的确

2021-03-06 03:03 UTC, PassionPenguin commented on article/2021/undefined-null-revisited.md
> +### `undefined`、`null` 以及空合并
空合并就好了，没必要那么长，后面还有个赋值，

空安全，这些都这么翻译，能够理解了已经（

2021-03-06 03:12 UTC, PassionPenguin commented
@lsvih @felixliao @MoonBall 修改完啦～

2021-03-06 07:29 UTC, lsvih approved these changes

2021-03-06 07:30 UTC, merged

2021-03-06 07:30 UTC, lsvih commented
@PassionPenguin  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-03-06 07:30 UTC, lsvih commented
PS：代码缩进没问题可以不用改的

2021-03-06 13:00 UTC, PassionPenguin commented
> PS：代码缩进没问题可以不用改的

ide format markdown 自动化操作...

2021-03-06 15:15 UTC, PassionPenguin commented
https://juejin.cn/post/6936559478909665316/

2021-03-07 07:18 UTC, lsvih commented
收到