6 alternatives to classes in python
xitu/gold-miner pull request #8202
Opened 2021-03-12 05:50 UTC by Alfxjx

译文翻译完成，resolve #8144 
第一次尝试 python 文章，大大们帮偶狠狠挑挑刺

2021-03-12 12:43 UTC, PassionPenguin requested changes

2021-03-12 12:43 UTC, PassionPenguin commented on article/2021/6-alternatives-to-classes-in-python.md
>  > * 译者：
添加译者信息：）

2021-03-12 12:43 UTC, PassionPenguin commented on article/2021/6-alternatives-to-classes-in-python.md
> +作为开发者，我们每天会产出大量的数据。 如何表示这些数据很重要，因此我们需要能够跟踪哪些变量代表哪些属性。 配置化是针对复杂数据的一个最佳示例。
```suggestion
作为开发者，我们每天会产出大量的数据，而这些数据的表现尤为很重要，因此我们需要能够跟踪哪些变量代表哪些属性。 配置化是针对复杂数据的一个最佳示例。
```

2021-03-12 12:43 UTC, PassionPenguin commented on article/2021/6-alternatives-to-classes-in-python.md
> +在以下文章中，我将使用位置数据作为示例。它必须有一个经度，纬度，外加一个可选的地址。在 C 语言中，可以使用 `struct` 来表示。 在 Java 中，您只需创建一个类。在 Python，有六种选择。让我们来探索他们每一个的优点和缺点吧！
```suggestion
在以下文章中，我将使用位置数据作为示例。它必须有一个经度，纬度，外加一个可选的地址。在 C 语言中，可以使用 `struct` 来表示，而在 Java 中，我们只需创建一个类。在 Python，我们则有六种方法可供选择。让我们来探索他们每一个的优点和缺点吧！
```

2021-03-12 12:43 UTC, PassionPenguin commented on article/2021/6-alternatives-to-classes-in-python.md
> +你可以看到我们需要编写一个构造器方法 `__init__`。 构造器的代码不一定总是看起来那么简单，但在许多情况下，它是简单的。
```suggestion
你可以看到我们需要编写一个构造器方法 `__init__`。构造器的代码不一定总是看起来那么简单，但在许多情况下，它是简单的。
```

2021-03-12 12:43 UTC, PassionPenguin commented on article/2021/6-alternatives-to-classes-in-python.md
> +在实际中，注解确实很糟糕，字典的注解在多数情况下几乎总是 `Dict[str, Any]` 。通常，没有注解。
```suggestion
在实际中，注解确实很糟糕。通常来说几乎没有字典的注解，而一般来说，最佳的注解会是 `Dict[str, Any]` 。
```

2021-03-12 12:43 UTC, PassionPenguin commented on article/2021/6-alternatives-to-classes-in-python.md
> +[命名元组（ `NamedTuples` ）](https://docs.python.org/3/library/collections.html#collections.namedtuple) 在 Python 2.6 中被加入，索引此数据结构已经存在很久了。命名元组事实上也是元组，但是他们会有一个名称以及一个构造器，用来接受关键字参数：
```suggestion
[命名元组（`NamedTuples`）](https://docs.python.org/3/library/collections.html#collections.namedtuple) 在 Python 2.6 中被加入，索引此数据结构已经存在很久了。命名元组事实上也是元组，但是他们会有一个名称以及一个构造器，用来接受关键字参数：
```

2021-03-12 12:43 UTC, PassionPenguin commented on article/2021/6-alternatives-to-classes-in-python.md
> +与 attrs 不同的是， dataclass 使用类型注解而非 `attr.ib()` 这样的注解。我认为这样大大提高了可读性。另外，由于现在对属性有了注解，编辑器的支持效果也更好了。
```suggestion
与 attrs 不同的是，dataclass 使用类型注解而非 `attr.ib()` 这样的注解。我认为这样大大提高了可读性。另外，由于现在对属性有了注解，编辑器的支持效果也更好了。
```

2021-03-12 12:43 UTC, PassionPenguin commented on article/2021/6-alternatives-to-classes-in-python.md
> +但是，我不太喜欢。 它又是超级冗长的，并且消除了许多 dataclass 的魅力。 如果您需要类型未涵盖的验证，请使用Pydantic。
```suggestion
但是，我不太喜欢。它又是超级冗长的，并且消除了许多 dataclass 的魅力。如果您需要类型未涵盖的验证，请使用 Pydantic。
```

2021-03-12 12:43 UTC, PassionPenguin commented on article/2021/6-alternatives-to-classes-in-python.md
1. lint
```shell
   191:1-191:4           no-empty-code-lang            Language of code can not be empty. 
   275:60-275:61         space-round-alphabet          No space between Chinese and alphabet. '的验证，请使用Pydan'
   331:1-331:4           no-empty-code-lang            Language of code can not be empty. 
   358:1-358:4           no-empty-code-lang            Language of code can not be empty. 
   376:19-376:20         space-round-alphabet          No space between Chinese and alphabet. 'ydantic非常清楚地'
   412:1-412:4           no-empty-code-lang            Language of code can not be empty. 
   413:1-413:110         no-long-code                  Code Block cannot have too long line. line with 109 characters exceeds code max length 100
   416:135-416:136       space-round-alphabet          No space between Chinese and alphabet. '将字典序列化为JSON。'
   420:3-420:4           space-round-alphabet          No space between Chinese and alphabet. '使用JSON字符串对嵌套'
   420:7-420:8           space-round-alphabet          No space between Chinese and alphabet. '使用JSON字符串对嵌套'
   420:21-420:22         space-round-alphabet          No space between Chinese and alphabet. '进行用户化对于Pydan'
   420:29-420:30         space-round-alphabet          No space between Chinese and alphabet. 'ydantic来说是很容'
   432:1-432:4           no-empty-code-lang            Language of code can not be empty. 
   451:52-451:53         space-round-number            No space between Chinese and number. '对象？假设您有100个。'
   451:55-451:56         space-round-number            No space between Chinese and number. '假设您有100个。它们中'

Lint total 1 files, 0 warnings 15 errors
```
2. `您` => `我们` 和 `你`
3. 语言需要更通顺一些，很多地方都没有翻译到位，甚至，连句子的基本成分都有残缺
4. 注意译文格式建议

2021-03-12 18:56 UTC, flying-yogurt commented
@Alfxjx @lsvih 校对认领。

2021-03-13 02:54 UTC, lsvih commented
@flying-yogurt 欢迎校对

2021-03-14 11:31 UTC, flying-yogurt reviewed
@Alfxjx @lsvih 校对完成。

2021-03-14 11:31 UTC, flying-yogurt commented on article/2021/6-alternatives-to-classes-in-python.md
> +作为开发者，我们每天会产出大量的数据。 如何表示这些数据很重要，因此我们需要能够跟踪哪些变量代表哪些属性。 配置化是针对复杂数据的一个最佳示例。
在第一版校对的基础上修改语法。
```suggestion
作为开发者，我们每天会产出大量的数据。 而这些数据的表现尤为重要。因此，我们需要能够跟踪哪些变量代表哪些属性。 配置化是针对复杂数据的一个首要示例。
```

2021-03-14 11:31 UTC, flying-yogurt commented on article/2021/6-alternatives-to-classes-in-python.md
> +你可以看到我们需要编写一个构造器方法 `__init__`。 构造器的代码不一定总是看起来那么简单，但在许多情况下，它是简单的。
调整语序使其符合中文逻辑。
```suggestion
你可以看到我们需要编写一个构造器方法 `__init__`。构造器的代码在大部分情况下是简单的，尽管有一些例外。
```

2021-03-14 11:31 UTC, flying-yogurt commented on article/2021/6-alternatives-to-classes-in-python.md
> +你可以看出我们在代码中使用了位置参数和关键字参数。如果你在构造器中给某一变量定义了一个默认值，那么在创建类的实例的时候可以不给这个变量赋值。可以参考 `pos2`，其中的 `address` 变量并没有在构造的时候赋值。
```suggestion
你可以看到我们在代码中使用了位置参数或关键字参数。如果你在构造器中给某一变量定义了一个默认值，那么在创建类的实例的时候可以不给这个变量赋值。可以参考 `pos2`，其中的 `address` 变量并没有在构造的时候赋值。
```

2021-03-14 11:31 UTC, flying-yogurt commented on article/2021/6-alternatives-to-classes-in-python.md
> +`get_distance` 方法的注解看起来非常的杂乱。开发者需要知道的信息是 `p1` 表示的是地点，而非这个地点信息包含着两个浮点数以及一个可选的字符串。这是编辑器需要做的工作。
替换为破折号使逻辑更清晰。
```suggestion
`get_distance` 方法的注解看起来非常的杂乱。开发者需要知道的信息是 `p1` 表示的是地点，而非这个地点信息包含着两个浮点数以及一个可选的字符串——这是编辑器需要做的工作。
```

2021-03-14 11:31 UTC, flying-yogurt commented on article/2021/6-alternatives-to-classes-in-python.md
> +命名元组解决了类型声明注解难以阅读的问题。因此命名元组也解决了我上文中提到的编辑器支持不完全的问题。
```suggestion
命名元组解决了类型声明注解难以阅读的问题。因此，它也解决了我上文中提到的编辑器支持不完全的问题。
```

2021-03-14 11:31 UTC, flying-yogurt commented on article/2021/6-alternatives-to-classes-in-python.md
> +但是，我不太喜欢。 它又是超级冗长的，并且消除了许多 dataclass 的魅力。 如果您需要类型未涵盖的验证，请使用Pydantic。
```suggestion
但是，我不太喜欢这种超级冗长且丢失了许多 dataclass 独有魅力的手段。 如果您需要类型未涵盖的验证，请使用Pydantic。
```

2021-03-14 11:31 UTC, flying-yogurt commented on article/2021/6-alternatives-to-classes-in-python.md
> +您可以看到从普通类创建的对象的字符串表示形式是无用的。元组看起来更好，但是它们没有指出哪个索引代表哪个属性。其余所有表示形式都很棒。它们很容易理解，甚至可以用来重新创建对象！
```suggestion
可以看到从普通类创建的对象的字符串表示形式是无用的。元组看起来更好，但是它们没有指出哪个索引代表哪个属性。其余所有表示形式都很棒。它们很容易理解，甚至可以用来重新创建对象！
```

2021-03-14 11:31 UTC, flying-yogurt commented on article/2021/6-alternatives-to-classes-in-python.md
> +您已经了解了如何为普通类、attrs、dataclass 和 Pydantic 实现数据验证。您没有看到的是错误消息的样子。
```suggestion
现在我们已经了解了如何为普通类、attrs、dataclass 和 Pydantic 实现数据验证。但我们还并不清楚错误消息的样子。
```

2021-03-14 11:31 UTC, flying-yogurt commented on article/2021/6-alternatives-to-classes-in-python.md
> +对于 dataclasses 而言，`[dataclasses.asdict](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict)` 做了很多工作。然后，您可以直接将字典序列化为JSON。对于  `DateTime` 或者[小数](https://docs.python.org/3/library/deci
```suggestion
对于 dataclasses 而言，`[dataclasses.asdict](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict)` 做了很多工作。然后，字典可以被直接序列化为JSON。对于  `DateTime` 或者[小数](https://docs.python.org/3/library/decimal.html)对象的结果会很有趣。 attrs 的结果也是[相似的](https://www.attrs.org/en/stable/examples.html#converting-to-collections-types) 。
```

2021-03-15 01:27 UTC, lsvih commented
@Alfxjx 麻烦添加一下译者和校对者信息哈

2021-03-15 02:04 UTC, Alfxjx commented on article/2021/6-alternatives-to-classes-in-python.md
> +在实际中，注解确实很糟糕，字典的注解在多数情况下几乎总是 `Dict[str, Any]` 。通常，没有注解。
这里的 best [可以看看这个链接](https://www.merriam-webster.com/dictionary/best)，我觉得属于是第三个意思 绝大多数情况，因为  `Dict[str, Any]` 这个注解属于不好的注解，包含了所有的类型。
可以改成：
在实际中，注解确实很糟糕。通常来说几乎没有字典的注解，在大部分情况下的注解会是 `Dict[str, Any]` 。

2021-03-15 02:04 UTC, Alfxjx commented
@PassionPenguin @flying-yogurt 感谢校对 已经修改啦
@lsvih 译者和校对者信息也添加了

2021-03-15 02:18 UTC, lsvih approved these changes

2021-03-15 02:19 UTC, merged

2021-03-15 02:19 UTC, lsvih commented
@Alfxjx  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-03-15 03:23 UTC, Alfxjx commented
> @Alfxjx 已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。
> 
> 掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
> 专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

https://juejin.cn/post/6939715051779522591/  已经发布到掘金啦

2021-03-15 07:29 UTC, lsvih commented
@Alfxjx 收到