Translate/10 years of open source visualization
xitu/gold-miner pull request #8205
Opened 2021-03-12 09:59 UTC by momodiy

translate done  #8166

2021-03-12 12:46 UTC, PassionPenguin commented on article/2021/10-years-of-open-source-visualization.md
> +# [译]十年可视化开源历程 |技术点评
```suggestion
# 十年可视化开源历程
```

发文的时候你再改，而且按照校对的进度，你这文怕是参与不了活动了

2021-03-12 12:46 UTC, PassionPenguin commented on article/2021/10-years-of-open-source-visualization.md
> +> 看看我从D3.js中学到了什么...
```suggestion
> 看看我从 D3.js 中学到了什么……
```

2021-03-12 12:46 UTC, PassionPenguin commented on article/2021/10-years-of-open-source-visualization.md
> +为了纪念[D3 1.0版本](https://github.com/d3/d3/releases/tag/v1.0.0)发行10周年，我想我应该做一些反思总结。我不打算做的太全面或太认真，只是对未来十年的一点展望，但我仍然希望你能对其中一两点感兴趣。
```suggestion
为了纪念 [D3 1.0 版本](https://github.com/d3/d3/releases/tag/v1.0.0)发行 10 周年，我想我应该做一些反思总结。我不打算做的太全面或太认真，只是对未来十年的一点展望，但我仍然希望你能对其中一两点感兴趣。
```

2021-03-12 12:46 UTC, PassionPenguin commented on article/2021/10-years-of-open-source-visualization.md
空行导致后面的代码全错位了 = =

2021-03-12 12:46 UTC, PassionPenguin commented on article/2021/10-years-of-open-source-visualization.md
> +### 1.造轮子最重要的教会别人用
```suggestion
## 1. 造轮子最重要的教会别人用
```

2021-03-12 12:48 UTC, PassionPenguin commented
校对认领

---

@momodiy 

建议译者认真阅读一下格式规范 =_=

2021-03-12 12:54 UTC, PassionPenguin requested changes
先改 draft pr，等修改完再开吧，说几点：

1. 注意译文的格式，例如空格的添加
2. 翻译应该注意遣词造句，英文句和中文句的构成是不一样的，很多时候会有成分的残缺。
3. 翻译的时候应该注意上下文，并添加适量的注释，因为英文的阅读几乎是按段落阅读，但中文可能更多的是按句子都能够理解
4. 不要修改 Markdown Syntax 除非真的有错
5. 你看来也不懂 Markdown Syntax
6. 注意不要串行，开pr前先检查 `Files changed` 面板
7. 不要使用 Google Translate 后直接发文章，一堆病句
8. 翻译的时候，针对词语，遣词造句很重要，请搜索原文单词，查查字典，不要望文生义，看到这个单词，直接给出自己的一个想法而不看上下文的内容
9. 半角全角标点
10. 不想吐槽了

2021-03-12 12:54 UTC, PassionPenguin commented on article/2021/10-years-of-open-source-visualization.md
> +# [译]十年可视化开源历程 |技术点评
一部分的语法检查输出：

```shell
   11:7-11:8             space-round-alphabet          No space between Chinese and alphabet. '看看我从D3.js中学到'
   11:12-11:13           space-round-alphabet          No space between Chinese and alphabet. '我从D3.js中学到了什'
   14:12-14:13           space-round-number            No space between Chinese and number. 'D3 1.0版本'
   14:63-14:64           space-round-number            No space between Chinese and number. '发行10周年，我想我应该'
   14:65-14:66           space-round-number            No space between Chinese and number. '发行10周年，我想我应该'
   21:125-21:126         space-round-number            No space between Chinese and number. '行教学（参见第2小节）。'
   21:126-21:127         space-round-number            No space between Chinese and number. '教学（参见第2小节）。并'
   21:201-21:202         space-round-number            No space between Chinese and number. '室培训可以帮助100人，'
   21:204-21:205         space-round-number            No space between Chinese and number. '可以帮助100人，而一个'
   25:19-25:20           space-round-alphabet          No space between Chinese and alphabet. '可以补充难用的API，也'
   25:75-25:76           space-round-alphabet          No space between Chinese and alphabet. '。🤷虽然我是D3的作者'
   25:40-25:41           space-round-number            No space between Chinese and number. '贴的依赖。D3的成功不是'
   25:77-25:78           space-round-number            No space between Chinese and number. '�虽然我是D3的作者，但'
   33:122-33:123         space-round-alphabet          No space between Chinese and alphabet. '请别难过。我对GitHu'
   33:128-33:129         space-round-alphabet          No space between Chinese and alphabet. '对GitHub与其他平台'
   50:15-50:16           space-round-number            No space between Chinese and number. '常来说，可视化80%的工'
   52:249-52:250         space-round-alphabet          No space between Chinese and alphabet. '步骤。（请参阅Leigh'
   52:260-52:261         space-round-alphabet          No space between Chinese and alphabet. 'h Dodds关于该主题'
   52:426-52:427         space-round-alphabet          No space between Chinese and alphabet. '，我最常使用的D3模块是'
   52:412-52:413         space-round-number            No space between Chinese and number. '（假设你看过第3小节）。'
   52:413-52:414         space-round-number            No space between Chinese and number. '假设你看过第3小节）。因'
   52:428-52:429         space-round-number            No space between Chinese and number. '最常使用的D3模块是'
   52:432-52:442         no-space-in-link              Link content can not start / end with space. ' d3-array '
   52:477-52:485         no-space-in-link              Link content can not start / end with space. ' d3-dsv '
   52:530-52:531         space-round-alphabet          No space between Chinese and alphabet. '用于处理数据的javas'
   52:540-52:541         space-round-alphabet          No space between Chinese and alphabet. 'ascript工具，例如'
   52:546-52:555         no-space-in-link              Link content can not start / end with space. ' tidy.js '
   52:591-52:600         no-space-in-link              Link content can not start / end with space. ' Arquero '
   59:24-59:25           space-round-number            No space between Chinese and number. '的示例（查阅第1小节），'
   59:25-59:26           space-round-number            No space between Chinese and number. '示例（查阅第1小节），可'
   59:183-59:184         space-round-alphabet          No space between Chinese and alphabet. '第5条）。而且D3主要是'
   59:177-59:178         space-round-number            No space between Chinese and number. '的工具（参阅第5条）。而'
   59:178-59:179         space-round-number            No space between Chinese and number. '工具（参阅第5条）。而且'
   59:185-59:186         space-round-number            No space between Chinese and number. '条）。而且D3主要是为定'
   59:204-59:215         no-space-in-link              Link content can not start / end with space. ' Vega-Lite '
   59:379-59:380         space-round-alphabet          No space between Chinese and alphabet. '。我们正在简化Obser'
   59:389-59:390         space-round-alphabet          No space between Chinese and alphabet. 'ervable中绘制可视'
   61:20-61:21           space-round-alphabet          No space between Chinese and alphabet. '导致了90%的bug'
   61:16-61:17           space-round-number            No space between Chinese and number. '%的代码导致了90%的b'
   63:73-63:74           space-round-alphabet          No space between Chinese and alphabet. '确定的事情。在D3中交互'
   63:87-63:88           space-round-alphabet          No space between Chinese and alphabet. '为是最容易造成bug的地'
   63:90-63:91           space-round-alphabet          No space between Chinese and alphabet. '容易造成bug的地方，比'
   63:75-63:76           space-round-number            No space between Chinese and number. '的事情。在D3中交互式行'
   71:222-71:223         space-round-alphabet          No space between Chinese and alphabet. '？在我只想观看YouTu'
   71:229-71:230         space-round-alphabet          No space between Chinese and alphabet. 'YouTube时为何还要'
   78:20-78:21           space-round-number            No space between Chinese and number. '联网（请参阅第8小节），'
   78:21-78:22           space-round-number            No space between Chinese and number. '网（请参阅第8小节），你'

Lint total 1 files, 0 warnings 47 errors
```

2021-03-12 14:22 UTC, momodiy commented
> 先改 draft pr，等修改完再开吧，说几点：
> 
> 1. 注意译文的格式，例如空格的添加
> 2. 翻译应该注意遣词造句，英文句和中文句的构成是不一样的，很多时候会有成分的残缺。
> 3. 翻译的时候应该注意上下文，并添加适量的注释，因为英文的阅读几乎是按段落阅读，但中文可能更多的是按句子都能够理解
> 4. 不要修改 Markdown Syntax 除非真的有错
> 5. 你看来也不懂 Markdown Syntax
> 6. 注意不要串行，开pr前先检查 `Files changed` 面板
> 7. 不要使用 Google Translate 后直接发文章，一堆病句
> 8. 翻译的时候，针对词语，遣词造句很重要，请搜索原文单词，查查字典，不要望文生义，看到这个单词，直接给出自己的一个想法而不看上下文的内容
> 9. 半角全角标点
> 10. 不想吐槽了

okay 我先改一版吧，很多细节，感谢指出

2021-03-12 15:36 UTC, PassionPenguin commented
> > 先改 draft pr，等修改完再开吧，说几点：
> > 
> > 1. 注意译文的格式，例如空格的添加
> > 2. 翻译应该注意遣词造句，英文句和中文句的构成是不一样的，很多时候会有成分的残缺。
> > 3. 翻译的时候应该注意上下文，并添加适量的注释，因为英文的阅读几乎是按段落阅读，但中文可能更多的是按句子都能够理解
> > 4. 不要修改 Markdown Syntax 除非真的有错
> > 5. 你看来也不懂 Markdown Syntax
> > 6. 注意不要串行，开pr前先检查 `Files changed` 面板
> > 7. 不要使用 Google Translate 后直接发文章，一堆病句
> > 8. 翻译的时候，针对词语，遣词造句很重要，请搜索原文单词，查查字典，不要望文生义，看到这个单词，直接给出自己的一个想法而不看上下文的内容
> > 9. 半角全角标点
> > 10. 不想吐槽了
> 
> okay 我先改一版吧，很多细节，感谢指出

加油嗷 ψ(｀∇´)ψ

2021-03-12 15:43 UTC, momodiy commented
加油加油ヾ(◍°∇°◍)ﾉﾞ



在 2021-03-12 23:36:32，"Hoarfroster" ***@***.***> 写道：

先改 draft pr，等修改完再开吧，说几点：

注意译文的格式，例如空格的添加
翻译应该注意遣词造句，英文句和中文句的构成是不一样的，很多时候会有成分的残缺。
翻译的时候应该注意上下文，并添加适量的注释，因为英文的阅读几乎是按段落阅读，但中文可能更多的是按句子都能够理解
不要修改 Markdown Syntax 除非真的有错
你看来也不懂 Markdown Syntax
注意不要串行，开pr前先检查 Files changed 面板
不要使用 Google Translate 后直接发文章，一堆病句
翻译的时候，针对词语，遣词造句很重要，请搜索原文单词，查查字典，不要望文生义，看到这个单词，直接给出自己的一个想法而不看上下文的内容
半角全角标点
不想吐槽了

okay 我先改一版吧，很多细节，感谢指出

加油嗷 ψ(｀∇´)ψ

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-13 05:02 UTC, Chorer commented
校对认领

2021-03-13 10:30 UTC, Chorer commented
@momodiy 中文和英文行不对应，这样没法校对。你先改过来。

2021-03-13 11:42 UTC, momodiy commented
好的



在 2021-03-13 18:30:52，"Chor" ***@***.***> 写道：

@momodiy 中文和英文行不对应，这样没法校对。你先改过来。

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-13 14:06 UTC, momodiy commented
xdm，我重新提交了，麻烦看一下还有什么修改建议吗？

2021-03-14 06:59 UTC, Chorer reviewed
@lsvih @momodiy 校对完毕。这篇文章不是很好翻译，但还是翻译得不错，辛苦了。注意适当断句以及一些错别字。

2021-03-14 06:59 UTC, Chorer commented on article/2021/10-years-of-open-source-visualization.md
> +一个确定的视觉形式（比如柱状图或者是树形图）在绝对意义上并不意味着好或者坏，但是是否适合你的数据和你想回答的特定问题这一点值得商榷。只有一种方法能够知道你使用的图表是否准确：你必须将数据插入再观察，不要着手使用特定的展示形式，而是想想你的数据是要解决什么样的问题。
```suggestion
一个确定的视觉形式（比如柱状图或者是树形图）并没有完全意义上的好坏之分，但它是否适合你的数据以及你想回答的特定问题这一点则值得商榷。只有一种方法能够知道你使用的图表是否准确，那就是看它能够传达信息：你必须将数据与之结合之后再进行观察，不要着手使用特定的展示形式，而是想想你的数据是要解决什么样的问题。
```

2021-03-14 06:59 UTC, Chorer commented on article/2021/10-years-of-open-source-visualization.md
> +如果你的数据很难确定对应什么类型的示例（请看第 1 小节），可以先试试特定类型的图表再确定其有效性。绘制可视化图表所需的精力越少、你尝试的变化越多、最终效果就越好，这就是 `Observable` 帮你快速获取数据的原因，比如单击一下鼠标就能替换文件或者让你无需 fork 就能编辑代码。但是如果你的数据结构不兼容，可能仍然需要大量的工作（参阅第 5 条）。而且 D3 主要是为定制的解释性图形而设
```suggestion
如果你的数据很难确定对应什么类型的示例（请看第 1 小节），可以先试试特定类型的图表再确定其有效性。绘制可视化图表所需的精力越少，你可以尝试的变化就越多，最终效果也就越好，这就是 `Observable` 帮你快速获取数据的原因，比如单击一下鼠标就能替换文件或者让你无需 fork 就能编辑代码。但是如果你的数据结构不兼容，可能仍然需要大量的工作（参阅第 5 条）。而且 D3 主要是为定制的解释性图形而设计，例如 [Vega-Lite](https://vega.github.io/vega-lite/) 这类用于探索图形的东西需要更多的工作。如果你想降低特定[符号认知范围](https://en.wikipedia.org/wiki/Cognitive_dimensions_of_notations)的黏度，可以快速尝试多种形式并查看有效方法。我们正在降低从 Observable 中绘制可视化效果的难度，希望能尽快分享出来。敬请关注。
```

2021-03-14 06:59 UTC, Chorer commented on article/2021/10-years-of-open-source-visualization.md
> +这些数字是我编的但是感觉这结论没错，某些代码就是比其他代码更容易出错。不是因为这些代码的质量较低而是因为它试图做一些有困难或是不确定的事情。在 D3 中最容易造成 bug 的是交互式行为，比如 d3-zoom 、 d3-drag 和 d3-brush 。它很难通过控制变量的方法推理更不用说测试所有可能的异步事件。由于交互行为是不确定的，你是否点击、拖动、平移选择或双击？更困难的是浏览器会发生变化
```suggestion
这些数字是我编的，但我感觉这结论没错：某些代码就是比其它代码更容易出错。不是因为这些代码的质量较低，而是因为它们试图做一些本就很困难或是不确定的事情。在 D3 中最容易造成 bug 的是交互式行为，比如 d3-zoom、d3-drag 和 d3-brush 。它很难通过控制变量的方法进行推理，更不用说测试所有可能的异步事件。同时，其交互行为也是不确定的，你是在点击、拖动、平移选择，还是在双击？更困难的是浏览器会发生变化，就像[被动事件监听](https://developers.google.com/web/updates/2017/01/scrolling-intervention)一样单纯地破坏页面。
```

2021-03-14 06:59 UTC, Chorer commented on article/2021/10-years-of-open-source-visualization.md
> +以上表明你可以通过谨慎选择要解决的问题和没有解决的问题来减少一些麻烦。比如你可以使用 `Observable` 的 [输入](https://observablehq.com/@observablehq/inputs) 和 [数据流](https://observablehq.com/@observablehq/how-observable-runs) 代替低级的事件监听器来构建页面，你的顾虑就
```suggestion
以上表明你可以通过谨慎选择要解决的问题和不想解决的问题来减少一些麻烦。比如，如果你使用 `Observable` 的[输入](https://observablehq.com/@observablehq/inputs) 和[数据流](https://observablehq.com/@observablehq/how-observable-runs)代替低级的事件监听器来构建页面，你的顾虑就会减少很多。
```

2021-03-14 06:59 UTC, Chorer commented on article/2021/10-years-of-open-source-visualization.md
> +无论你工作多么出色，如果你把自己置于互联网这个平台就会有人说一些伤人的话并让你感觉难过。这通常不是故意的，但这并不重要。我因为 D3 感觉非常自豪但我也收集过一些分享出来的负面评价推文。这就是我的处理方式（收集负面推文），请不要批判我。（不，我可不会分享这个列表）。
```suggestion
无论你的工作多么出色，如果你把自己置于互联网这个平台，就会有人说一些伤人的话并让你感到难过。这通常不是故意的，但这并不重要。我为 D3 感到自豪，但我也收集过一些别人分享出来的负面评价推文。这就是我的处理方式（收集负面推文），请不要批判我。（对了，我可不会分享这个列表）。
```

2021-03-14 06:59 UTC, Chorer commented on article/2021/10-years-of-open-source-visualization.md
> +我对于那些使用工具受挫的人并无恶意，我完全理解一个工具可能给人带来的无助感，你只需要一个小表格如今却要学习数以百万计的其他内容。一个工具的设计可以如此的随意和滞后，这就是互联网的问题，过去你可能会向同事或者朋友抱怨 D3 有多糟糕，也许他们会帮你解决而且知道你正在发泄。因为互联网我也听到了这些抱怨，我并不认识你，然而这些抱怨让我很沮丧。如果我开发工具是为了看到成功使用工具的人分享快乐，然而我却看
```suggestion
我对于那些使用工具受挫的人并无恶意，我完全理解一个工具可能给人带来的无助感 —— 明明你只需要设计一个小表格，但却不得不学习数以百万计的其它内容。一个工具的设计可以如此地随意和滞后，这就是互联网的问题，过去你可能会向同事或者朋友抱怨 D3 有多糟糕，也许他们会帮你解决，而且知道你正在发泄。因为互联网我也听到了这些抱怨，我并不认识你，然而这些抱怨让我很沮丧。如果说我当初开发工具是为了看到成功使用工具的人分享快乐，如今的我却只感受到了痛苦和挫败，那我还为什么要继续开发？为何在我只想观看 YouTube 时还要遭受贬低和否定呢？
```

2021-03-14 06:59 UTC, Chorer commented on article/2021/10-years-of-open-source-visualization.md
> +因此如果你发现你在互联网上抱怨请考虑一下你这些话会造成的实际影响。是否这些话只会造成开发者的懈怠和受挫，甚至是开源项目停更？或是也可能是好的影响，比如你可以做一些贡献通过拉取请求或文档支持让这个工具变得更好。毕竟，这就是开源之美。
```suggestion
因此，如果你发现你在互联网上抱怨，请考虑一下你的言语会造成的实际影响。这些话是否只会造成开发者的懈怠和受挫？甚至更糟，导致开源项目停更呢？或者往更好的方向考虑一下，你可以做一些贡献来让这个工具变得更好，比如通过拉取请求或文档支持等。毕竟，这就是开源之美。
```

2021-03-14 06:59 UTC, Chorer commented on article/2021/10-years-of-open-source-visualization.md
> +为了避免将幸福感寄托于互联网（请参阅第 8 小节），你必须发展一个你尊重的小而稳定的组织，换句话说，找到一个可以提供验证、反馈、支持和指导的团队或组织。除我之外这对于每个人都是很容易的（我的朋友麦克就做的很好），距离遥远的朋友也需要多加联系。当使用 `Observable` 创建出一个远程共享的协作空间时我总是感觉很兴奋，这不是在炫耀（就像在 Twitter 上）而是为了与同伴实时合作时发表见解
```suggestion
为了避免将幸福感寄托于互联网（请参阅第 8 小节），你必须发展一个你尊重的小而稳定的组织，换句话说，找到一个可以提供验证、反馈、支持和指导的团队或组织。每个人都清楚这件事，除了我之外 —— **是的，麦克，有朋友真的会很棒**。尽管如此，我觉得还是有必要强调一下，毕竟如今人与人的交流大多都是在遥远的互联网上。当我使用 `Observable` 创建出一个远程共享的协作空间时，我觉得很高兴，这不是在炫耀（就像在 Twitter 上），而是因为可以与朋友们实时合作并发表见解、解决问题而真心感到高兴。
```
1. 这里的 Mike 指的是作者自己（Mike Bostock），应该是在调侃。
2. but I feel like it’s worth repeating today when so much human interaction happens at a distance。这句话要结合前面来理解，每个人都清楚抱团取暖的好处，但由于现在大家的交流很多都是在网上，作者觉得自己还是有必要强调这一点（it’s worth repeating today）

2021-03-14 06:59 UTC, Chorer commented on article/2021/10-years-of-open-source-visualization.md
> +起初我写的是`放松`,但是感觉有点假。我可能是最不会放松的人，我希望能够活的轻松。这是我的私事，我会尝试反思我工作生活中最喜欢的部分并且花更多的时间做这些事情。这听起来很老套实际做起来却不容易。如果你知道了你喜欢做的事当你失败时你也不会有太多遗憾（也是一种观点）。矛盾的是一个让你偏离实际目的的目标可能会帮助你成功，因为你更容易坚持。做自己喜欢的事情（工作）是更容易坚持的，比如我喜欢构建工具，我无
```suggestion
起初我写的是“放松”，但是感觉有点假。我可能是最不会放松的人，我**希望**能够活得轻松。这是我的私事，我会尝试反思自己工作生活中最喜欢的部分，并且花更多的时间做这些事情。这听起来很简单也很老套，但实际做起来却不容易。如果你知道自己喜欢做什么事情，那么（万一）当你失败（只是假设，未必真的会这样）时，你就不会有太多遗憾。矛盾的是，一个让你偏离实际目的的目标可能会帮助你成功，因为你更容易坚持下去。做自己喜欢的事情（工作）是更容易坚持的，比如我喜欢构建工具，虽然无法预测它是否能成功，但我热衷于解决难题并进行抽象，而且我也热衷于看到人们使用我的作品。另一方面，虽然我知道演讲的好处，也知道演讲之后会获得多棒的自我感觉，但我发现公开演讲会引起焦虑。因此，如果你对我较少发表公开演讲而略感失望，但愿这只是因为我正在埋头开发一些新的东西。😅
```

2021-03-14 07:27 UTC, PassionPenguin reviewed
Chor 大佬已经给出了很好的校对啦，我就顺带着修补一下几处格式叭

2021-03-14 07:27 UTC, PassionPenguin commented on article/2021/10-years-of-open-source-visualization.md
> +为了纪念[D3 1.0 版本](https://github.com/d3/d3/releases/tag/v1.0.0)发行 10 周年，我想我应该做一些反思总结。我不打算做的太全面或太认真，只是对未来十年的一点展望，但我仍然希望你能对其中一两点感兴趣。
```suggestion
为了纪念 [D3 1.0 版本](https://github.com/d3/d3/releases/tag/v1.0.0)发行 10 周年，我想我应该就所学的东西做一些反思总结。我不打算做得太全面或太认真，这只是对未来十年的一点展望，不过我仍然希望你能对其中一两点感兴趣。
```

2021-03-14 07:27 UTC, PassionPenguin commented on article/2021/10-years-of-open-source-visualization.md
> +在所有类型的文档中，示例似乎是最有效的。我一直崇尚[示例的优点](https://bost.ocks.org/mike/example/)， `Observable` 和它的前身 `bl.ocks.org` 都通过让人创建和使用示例来加快学习。示例能够通过展示可能的使用方式来激发灵感，能够展示特定的技巧，是帮助人们入门的基石。考虑到人们擅长模式匹配和从观察，示例自然而然地成为最好的学习材料。
```suggestion
在所有类型的文档中，示例似乎是最有效的。我一直崇尚[示例的优点](https://bost.ocks.org/mike/example/)，`Observable` 和它的前身 `bl.ocks.org` 都通过让人创建和使用示例来加快学习。示例能够通过展示可能的使用方式来激发灵感，能够展示特定的技巧，是帮助人们入门的基石。考虑到人们擅长模式匹配和从观察，示例自然而然地成为最好的学习材料。
```

2021-03-14 07:27 UTC, PassionPenguin commented on article/2021/10-years-of-open-source-visualization.md
> +可视化图表是分析的最终结果，也是数据的可视化表现，可供专业人士和非专业人士查看、共享与欣赏，因此可能会获得过多的赞誉。要想完成可视化效果，首先必须通过查找数据、清理数据、转换、链接、建模等等步骤，数据处理有时会被贬低为[清洁工](https://www.nytimes.com/2014/08/18/technology/for-big-data-scientists-hurdle-to-insi
```suggestion
可视化图表是分析的最终结果，也是数据的可视化表现，可供专业人士和非专业人士查看、共享与欣赏，因此可能会获得过多的赞誉。要想完成可视化效果，首先必须通过查找数据、清理数据、转换、链接、建模等等步骤，数据处理有时会被贬低为[清洁工](https://www.nytimes.com/2014/08/18/technology/for-big-data-scientists-hurdle-to-insights-is-janitor-work.html)，无论如何它代表了理解数据本质的关键步骤。（请参阅 Leigh Dodds 关于该主题的[文章](https://blog.ldodds.com/2020/01/31/do-data-scientists-spend-80-of-their-time-cleaning-data-turns-out-no/)）如果数据结构正确，那么应用视觉编码的过程可能会比较简单（假设你看过第 3 小节）。因此，我最常使用的 D3 模块是 [d3-array](https://github.com/d3/d3-array) 和 [d3-dsv](https://github.com/d3/d3-dsv)。我很高兴看到例如 [tidy.js](https://pbeshai.github.io/tidy/) 和 [Arquero](https://uwdata.github.io/arquero/) 这种用于处理数据的 javascript 工具。哈德利·威克姆（Hadley Wickham）的 [整理数据](https://vita.had.co.nz/papers/tidy-data.pdf) 相关示例是很有价值的。
```

2021-03-14 08:17 UTC, momodiy commented on article/2021/10-years-of-open-source-visualization.md
> +起初我写的是`放松`,但是感觉有点假。我可能是最不会放松的人，我希望能够活的轻松。这是我的私事，我会尝试反思我工作生活中最喜欢的部分并且花更多的时间做这些事情。这听起来很老套实际做起来却不容易。如果你知道了你喜欢做的事当你失败时你也不会有太多遗憾（也是一种观点）。矛盾的是一个让你偏离实际目的的目标可能会帮助你成功，因为你更容易坚持。做自己喜欢的事情（工作）是更容易坚持的，比如我喜欢构建工具，我无
厉害厉害，感觉非常专业👍，学到很多

2021-03-14 08:20 UTC, momodiy commented on article/2021/10-years-of-open-source-visualization.md
> +要想使你的影响力最大化，你的核心策略就应该是教学。这意味着包含文档、教程、示例、视频、推文等方面。一对一教学与工作室培训就是一种很好的方式，让你的知识浮出水面且与你的听众找到共同点。并且从他们的工作中得到启发，了解到如何更有效的进行教学（参见第 2 小节）。并且随着时间的推移，不断扩大规模的只是需要增加的教学资源而无需花费你的时间。如果需要，你的教程就是你的被动收入。一天的工作室培训可以帮助 1
学到了

2021-03-14 08:24 UTC, momodiy commented on article/2021/10-years-of-open-source-visualization.md
> +因此如果你发现你在互联网上抱怨请考虑一下你这些话会造成的实际影响。是否这些话只会造成开发者的懈怠和受挫，甚至是开源项目停更？或是也可能是好的影响，比如你可以做一些贡献通过拉取请求或文档支持让这个工具变得更好。毕竟，这就是开源之美。
> Chor 大佬已经给出了很好的校对啦，我就顺带着修补一下几处格式叭


> Chor 大佬已经给出了很好的校对啦，我就顺带着修补一下几处格式叭

感谢大佬的细心👍，学到了

2021-03-14 08:44 UTC, lsvih commented
@Chorer 感谢校对

2021-03-15 04:28 UTC, W-Qing requested changes
欢迎帮忙指正，其他的还是等重新翻译过再校验吧...

2021-03-15 07:21 UTC, momodiy commented on article/2021/10-years-of-open-source-visualization.md
> +为了纪念[D3 1.0 版本](https://github.com/d3/d3/releases/tag/v1.0.0)发行 10 周年，我想我应该做一些反思总结。我不打算做的太全面或太认真，只是对未来十年的一点展望，但我仍然希望你能对其中一两点感兴趣。
翻译的很棒

2021-03-15 07:33 UTC, momodiy commented on article/2021/10-years-of-open-source-visualization.md
> +要想使你的影响力最大化，你的核心策略就应该是教学。这意味着包含文档、教程、示例、视频、推文等方面。一对一教学与工作室培训就是一种很好的方式，让你的知识浮出水面且与你的听众找到共同点。并且从他们的工作中得到启发，了解到如何更有效的进行教学（参见第 2 小节）。并且随着时间的推移，不断扩大规模的只是需要增加的教学资源而无需花费你的时间。如果需要，你的教程就是你的被动收入。一天的工作室培训可以帮助 1
其他改动都很准确，但是这一句
> 但是随着你的听众增加，一系列教程才是你不需要花费时间就可以扩大规模的唯一方式
> 是否可以改成
> 但是随着你的听众增加，你无需花费额外的时间就可以扩大教学规模的唯一方式就是制作一系列教程

2021-03-15 11:39 UTC, lsvih commented
@momodiy 您好，我看到 File Change 里大多数校对者的意见都是 resolved 状态，但是没有对文章进行修改

2021-03-15 12:43 UTC, Chorer commented on article/2021/10-years-of-open-source-visualization.md
> +要想使你的影响力最大化，你的核心策略就应该是教学。这意味着包含文档、教程、示例、视频、推文等方面。一对一教学与工作室培训就是一种很好的方式，让你的知识浮出水面且与你的听众找到共同点。并且从他们的工作中得到启发，了解到如何更有效的进行教学（参见第 2 小节）。并且随着时间的推移，不断扩大规模的只是需要增加的教学资源而无需花费你的时间。如果需要，你的教程就是你的被动收入。一天的工作室培训可以帮助 1
> 其他改动都很准确，但是这一句
> 
> > 但是随着你的听众增加，一系列教程才是你不需要花费时间就可以扩大规模的唯一方式
> > 是否可以改成
> > 但是随着你的学员增加，你无需花费额外时间就可以扩大教学规模的唯一方式就是制作一系列教程

可以结合一下：但是随着你的学员增加，制作一系列教程才是你无需花费个人时间就可以扩大教学规模的唯一方式

2021-03-15 15:20 UTC, momodiy commented
> @momodiy 您好，我看到 File Change 里大多数校对者的意见都是 resolved 状态，但是没有对文章进行修改

okay，我重新commit一下

2021-03-15 16:23 UTC, momodiy commented
okay，已经重新commit



在 2021-03-15 20:44:00，"Chor" ***@***.***> 写道：

@Chorer commented on this pull request.

In article/2021/10-years-of-open-source-visualization.md:

>  
-## 2. Support is a powerful means of research.
+要想使你的影响力最大化，你的核心策略就应该是教学。这意味着包含文档、教程、示例、视频、推文等方面。一对一教学与工作室培训就是一种很好的方式，让你的知识浮出水面且与你的听众找到共同点。并且从他们的工作中得到启发，了解到如何更有效的进行教学（参见第 2 小节）。并且随着时间的推移，不断扩大规模的只是需要增加的教学资源而无需花费你的时间。如果需要，你的教程就是你的被动收入。一天的工作室培训可以帮助 100 人，而一个教程可以帮助数万人甚至更多。我也经常受到 [里奇·哈里斯](https://twitter.com/Rich_Harris) 和 [阿布拉莫夫](https://overreacted.io) 出色教学风格的启发(偶尔羡慕不已)。


其他改动都很准确，但是这一句

但是随着你的听众增加，一系列教程才是你不需要花费时间就可以扩大规模的唯一方式
是否可以改成
但是随着你的学员增加，你无需花费额外时间就可以扩大教学规模的唯一方式就是制作一系列教程

可以结合一下：但是随着你的学员增加，制作一系列教程才是你无需花费个人时间就可以扩大教学规模的唯一方式

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-15 16:24 UTC, PassionPenguin approved these changes

2021-03-15 16:24 UTC, PassionPenguin commented on article/2021/10-years-of-open-source-visualization.md
>  > * 校对者：
记得填写校对者嗷

2021-03-15 16:31 UTC, momodiy commented on article/2021/10-years-of-open-source-visualization.md
> +要想使你的影响力最大化，你的核心策略就应该是教学。这意味着包含文档、教程、示例、视频、推文等方面。一对一教学与工作室培训就是一种很好的方式，让你的知识浮出水面且与你的听众找到共同点。并且从他们的工作中得到启发，了解到如何更有效的进行教学（参见第 2 小节）。并且随着时间的推移，不断扩大规模的只是需要增加的教学资源而无需花费你的时间。如果需要，你的教程就是你的被动收入。一天的工作室培训可以帮助 1
已经修改，感谢宝贵的建议

2021-03-16 02:16 UTC, lsvih approved these changes

2021-03-16 02:17 UTC, merged

2021-03-16 02:17 UTC, lsvih commented
@momodiy  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-03-16 02:51 UTC, momodiy commented
掘金文章地址： https://juejin.cn/post/6940078120556822559/
感谢几位大佬的校对



在 2021-03-16 10:17:31，"lsvih" ***@***.***> 写道：

@momodiy 已经 merge 啦~ 快快麻溜发布到掘金然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个好用的插件。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-16 03:07 UTC, lsvih commented
收到