Raspberry Pi 九岁啦：你可能不知道的 9 件事
xitu/gold-miner pull request #8206
Opened 2021-03-12 11:28 UTC by PassionPenguin

译文翻译完成，resolve #8193

2021-03-12 16:40 UTC, husiyu requested changes
@PassionPenguin  Rest LGTM

2021-03-12 16:40 UTC, husiyu commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +* 快 40 倍的处理器（700 MHz 单核 <=> 1.5GHz 四核）
<=> 这个符号还是改回原文的 vs 吧。

2021-03-12 16:40 UTC, husiyu commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +为了纪念 Raspberry Pi 的九岁生日，让我们一起了解一下有关它的 9 项内容吧：
不如我们借此机会介绍有关树莓派的 9 个小故事，以此庆祝树莓派发布 9 周年吧！

2021-03-12 16:40 UTC, husiyu commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +树莓派最初是为解决一个非常局限的问题而开发的：剑桥大学申请计算机科学系的人数正在减少 —— 申请简历的数量从每年 600 个减少到每年 250 个。教学的负责人埃本·厄普顿（Eben Upton）担心太少孩子会对计算机产生兴趣。寄望于为英国的孩子们提供一种价格低廉且易于修改的计算机，厄普顿打算为他的计划吸引更多且更好的学生们。
教学的负责人埃本·厄普顿（Eben Upton）担心太少孩子会对计算机产生兴趣。寄望于为英国的孩子们提供一种价格低廉且易于修改的计算机，厄普顿打算为他的计划吸引更多且更好的学生们。
->>
负责教学及招生工作的埃本·厄普顿（Eben Upton）担心没有足够的对计算机感兴趣的孩子。于是，为了吸引更多、能力更好的学生，厄普顿为一小部分英国孩子提供了一个低成本、易修改的计算机（从而培养他们对计算机的兴趣）。

2021-03-12 16:40 UTC, husiyu commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +* **[Windows 10]**：是的！我们可以[在树莓派 4 上安装 Windows 10](https://www.tomshardware.com/how-to/install-windows-10-raspberry-pi)（需要一些技巧），但是它实在是太慢了，我觉得你可能不想继续让它运行 Windows 10。
`**[Windows 10]**` ->> ` **Windows 10**`

2021-03-12 16:40 UTC, husiyu commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +* **[Lakka]**：此操作系统专为复古游戏而设计，预装了一系列的模拟器。
`**[Lakka]**` ->>`**Lakka**`

2021-03-12 16:40 UTC, husiyu commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +国际空间站有两个 [Astro Pis](https://www.raspberrypi.org/education/programmes/astro-pi/)，一款经过特别改良的树莓派 B+ 型号。这两个机器已经“空间强化”过并配备了官方的树莓派 Sense HAT 传感器服加版。欧洲航天局举办定期竞赛，而孩子们可以提交代码并在这些设备上运行。
->>
国际空间站有两个 [Astro Pis](https://www.raspberrypi.org/education/programmes/astro-pi/)，一款经过特别改良的树莓派 B+ 型号。这两个机器已经“空间改造”（以适应太空环境），并配备了官方的 Raspberry Pi Sense HAT。欧洲航天局举办定期竞赛，孩子们可以提交代码并在这些设备上运行。

2021-03-12 16:40 UTC, husiyu commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +即使树莓派 B+，树莓派 2，树莓派 3B 和其他的一些型号已经过时了，树莓派基金会仍会继续积极制造和销售它们。该组织不愿接受报废（EOL，End-of-Life）产品，因为有些工业系统仍然会需要一些过时的及其。
该组织不愿接受报废（EOL，End-of-Life）产品，因为有些工业系统仍然会需要一些过时的及其。
->>
该组织不愿接受报废（EOL，End-of-Life）产品，因为有些工业客户仍会使用这些机器，并不在意它是否过时。

2021-03-12 16:40 UTC, husiyu commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +如果说 35 美元仍然是很多钱，那么有便宜些的树莓派型号。树莓派 Zero 仅售 5 美元，而树莓派 Pico 微控制器板仅售 4 美元。
如果说 35 美元仍然感到贵了一些，那么还有更便宜的树莓派型号供你选择。树莓派 Zero  仅售 5 美元，而树莓派 Pico 微控制器板仅售 4 美元。

2021-03-12 16:40 UTC, husiyu commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +如果说 35 美元仍然是很多钱，那么有便宜些的树莓派型号。树莓派 Zero 仅售 5 美元，而树莓派 Pico 微控制器板仅售 4 美元。
如果说 35 美元仍然显得贵了一些，那么便宜的树莓派型号供你选择。树莓派 Zero 仅售 5 美元，而树莓派 Pico 微控制器板仅售 4 美元。

2021-03-12 16:44 UTC, husiyu commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +# Raspberry Pi 九岁啦：你可能不知道的 9 件事
树莓派 9 岁啦！你不知道的 9 个树莓派冷知识

2021-03-12 17:26 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +为了纪念 Raspberry Pi 的九岁生日，让我们一起了解一下有关它的 9 项内容吧：
```suggestion
不如我们借此机会介绍有关树莓派的 9 个小知识，以庆祝树莓派的九岁生日把！
```

2021-03-12 17:26 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +树莓派最初是为解决一个非常局限的问题而开发的：剑桥大学申请计算机科学系的人数正在减少 —— 申请简历的数量从每年 600 个减少到每年 250 个。教学的负责人埃本·厄普顿（Eben Upton）担心太少孩子会对计算机产生兴趣。寄望于为英国的孩子们提供一种价格低廉且易于修改的计算机，厄普顿打算为他的计划吸引更多且更好的学生们。
```suggestion
树莓派最初是为解决一个非常局限的问题而开发的：剑桥大学申请计算机科学系的人数正在减少 —— 申请简历的数量从每年 600 个减少到每年 250 个。负责教学及招生工作的埃本·厄普顿（Eben Upton）担心没有足够的孩子对计算机感兴趣，于是，为了吸引更多能力更好的学生，厄普顿为一小部分英国孩子提供了一个低成本、易修改的计算机（从而培养他们对计算机的兴趣）。
```

2021-03-12 17:26 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +* **[Windows 10]**：是的！我们可以[在树莓派 4 上安装 Windows 10](https://www.tomshardware.com/how-to/install-windows-10-raspberry-pi)（需要一些技巧），但是它实在是太慢了，我觉得你可能不想继续让它运行 Windows 10。
```suggestion
* **Windows 10**：是的！我们可以[在树莓派 4 上安装 Windows 10](https://www.tomshardware.com/how-to/install-windows-10-raspberry-pi)（需要一些技巧），但是它实在是太慢了，我觉得你可能不想继续让它运行 Windows 10。
```

2021-03-12 17:26 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +* **[Lakka]**：此操作系统专为复古游戏而设计，预装了一系列的模拟器。
```suggestion
* **Lakka**：此操作系统专为复古游戏而设计，预装了一系列的模拟器。
```

2021-03-12 17:26 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +国际空间站有两个 [Astro Pis](https://www.raspberrypi.org/education/programmes/astro-pi/)，一款经过特别改良的树莓派 B+ 型号。这两个机器已经“空间强化”过并配备了官方的树莓派 Sense HAT 传感器服加版。欧洲航天局举办定期竞赛，而孩子们可以提交代码并在这些设备上运行。
```suggestion
国际空间站有两个 [Astro Pis](https://www.raspberrypi.org/education/programmes/astro-pi/)，一种经过特别改良的树莓派 B+ 型号。这两个机器经过了“空间改造”（以适应太空环境），并配备了官方的树莓派 Sense HAT 传感器附加板。欧洲航天局举办定期竞赛，孩子们可以提交代码并在这些设备上运行。
```

2021-03-12 17:26 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +即使树莓派 B+，树莓派 2，树莓派 3B 和其他的一些型号已经过时了，树莓派基金会仍会继续积极制造和销售它们。该组织不愿接受报废（EOL，End-of-Life）产品，因为有些工业系统仍然会需要一些过时的及其。
```suggestion
即使树莓派 B+，树莓派 2，树莓派 3B 和其他的一些型号已经过时了，树莓派基金会仍会继续积极制造和销售它们。该组织不愿接受报废（EOL，End-of-Life）产品，因为有些工业客户仍然会需要使用这些机器，而不在乎它是否过时。
```

2021-03-12 17:26 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +* 快 40 倍的处理器（700 MHz 单核 <=> 1.5GHz 四核）
```suggestion
* 快 40 倍的处理器（1.5GHz 四核 vs 700 MHz 单核 ）
```

2021-03-12 17:26 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +* 原来 RAM 容量的 8 次方倍（2GB <=> 256GB）
```suggestion
* 原来 RAM 容量的 8 次方倍（256GB vs 2GB）
```

2021-03-12 17:26 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +* 双监视器输出 <=> 单 HDMI 输出
```suggestion
* 双监视器输出 vs 单 HDMI 输出
```

2021-03-12 17:26 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +* USB 3.0 端口 <=> 只支持 USB 2
```suggestion
* USB 3.0 端口 vs 只支持 USB 2
```

2021-03-12 17:26 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +如果说 35 美元仍然是很多钱，那么有便宜些的树莓派型号。树莓派 Zero 仅售 5 美元，而树莓派 Pico 微控制器板仅售 4 美元。
```suggestion
如果说 35 美元仍然挺贵的，那么还有便宜些的树莓派型号供你选择。树莓派 Zero 仅售 5 美元，而树莓派 Pico 微控制器板仅售 4 美元。
```

2021-03-12 17:26 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +# Raspberry Pi 九岁啦：你可能不知道的 9 件事
```suggestion
# Raspberry Pi 九岁啦，让我们一起走进你可能不知道的有关它的 9 个小知识吧
```

2021-03-12 17:28 UTC, PassionPenguin commented
等待其他校对着校对

2021-03-13 05:01 UTC, Chorer commented
校对认领

2021-03-13 10:28 UTC, Chorer reviewed
@PassionPenguin 英文和中文行不对应，这样我没法校对。你先改过来吧，ok 了艾特我一下。

2021-03-13 11:28 UTC, PassionPenguin commented
> @PassionPenguin 英文和中文行不对应，这样我没法校对。你先改过来吧，ok 了艾特我一下。

改不了hh 源文件少了不少内容，要改就得reset

2021-03-13 12:26 UTC, Chorer reviewed
@PassionPenguin 校对完毕

2021-03-13 12:26 UTC, Chorer commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +# Raspberry Pi 九岁啦，让我们一起走进你可能不知道的有关它的 9 个小知识吧
```suggestion
# Raspberry Pi 九岁啦：你可能不知道的 9 件事 
```
太长了

2021-03-13 12:26 UTC, Chorer commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +Raspberry Pi 树莓派 是世界上最受欢迎和最具创新的计算机系列之一，于 2012 年 2 月 29 日正式推出。九年来，一共售出了 3,800 万太树莓派。它们为庞大的制造商、学生和企业群体提供了动力。这最初只是一个小项目，旨在增加剑桥大学的计算机科学计划的应用程序，但现在已经流行于全球。
```suggestion
Raspberry Pi（树莓派 ）是世界上最受欢迎和最具创新的计算机系列之一，于 2012 年 2 月 29 日正式推出。九年来，一共售出了 3,800 万台树莓派。它们为庞大的制造商、学生和企业群体提供了动力。这最初只是一个小项目，旨在促进剑桥大学的计算机科学教育，但现在已经流行于全球。
```

2021-03-13 12:26 UTC, Chorer commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +每个真正的技术爱好者都应该拥有至少一台的树莓派，或者，如果你像我一样，拥有 30 台树莓派。我们可以将其用作 轻型 PC、[复古街机](https://www.tomshardware.com/how-to/install-retropie-raspberry-pi-4)，或为各种项目提供动力，含括 [CCTV](https://www.tomshardware.com/how-to/raspb
```suggestion
每个真正的技术爱好者都应该拥有至少一台树莓派，或者，你也可以像我一样，拥有 30 台树莓派。我们可以将其用作轻型 PC、[复古街机](https://www.tomshardware.com/how-to/install-retropie-raspberry-pi-4)，或为各种项目提供动力，从 [家庭安全摄像头](https://www.tomshardware.com/how-to/raspberry-pi-security-camera) 到 [井字游戏机器人](https://www.tomshardware.com/news/this-raspberry-pi-robot-plays-tic-tac-toe-so-you-never-play-alone)、[自动运送垃圾的运输机器人](https://www.tomshardware.com/news/clean-your-room-with-this-raspberry-pi-trash-delivery-bot) 或是[流媒体服务器](https://www.tomshardware.com/how-to/raspberry-pi-plex-ubuntu)。
```

2021-03-13 12:26 UTC, Chorer commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +不如我们借此机会介绍有关树莓派的 9 个小知识，以庆祝树莓派的九岁生日把！
```suggestion
不如我们借此机会介绍有关树莓派的 9 个小知识，以庆祝树莓派的九岁生日吧！
```

2021-03-13 12:26 UTC, Chorer commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +他在 [2019 年的采访中](https://www.tomshardware.com/news/raspberry-pi-founder-interview,38585.html)告诉我们：“我们正在设计的东西，在商业领域围绕着这样的想法，即如果你可以生产 1000 台树莓派，并交付给合适的 1000 个孩子的手中，你就可以解决了问题。”
```suggestion
他在 [2019 年的采访中](https://www.tomshardware.com/news/raspberry-pi-founder-interview,38585.html)告诉我们：“我们正在设计的东西，在商业领域围绕着这样的想法，即如果你可以生产 1000 台树莓派，并交付到合适的 1000 个孩子的手中，你就可以解决问题。”
```

2021-03-13 12:26 UTC, Chorer commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +最初的树莓派 B 型只拥有 256MB 的 RAM 和一个单核 700 MHz 处理器，而当前的主流型号树莓派 4B 则具有高达 8GB 的 RAM，四核 1.5GHz 的 CPU 和 USB 3.0 的端口。
```suggestion
最初的树莓派 B 型只拥有 256MB 的 RAM 和一个单核 700MHz 处理器，而当前的主流型号树莓派 4B 则具有高达 8GB 的 RAM，四核 1.5GHz 的 CPU 和 USB 3.0 的端口。
```

2021-03-13 12:26 UTC, Chorer commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +[树莓派 400](https://www.tomshardware.com/news/raspberry-pi-400-review-faster-cpu-new-layout-better-thermals) 于 2020 年末推出，是树莓派发行的第一台独立计算机。尽管 CPU 是 1.8GHz 而不是 1.5GHz，但树莓派 400 取代了裸板，成了一个内部集成了一个与树莓派 4 一样的系
```suggestion
[树莓派 400](https://www.tomshardware.com/news/raspberry-pi-400-review-faster-cpu-new-layout-better-thermals) 于 2020 年末推出，是树莓派发行的第一台独立计算机。尽管 CPU 是 1.8GHz 而不是 1.5GHz，但树莓派 400 取代了裸板，成了一个内部集成了与树莓派 4 一样的系统的键盘。它可以单独被购买，也可以与鼠标、电源、电缆和官方指南配套使用。
```

2021-03-13 12:26 UTC, Chorer commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +[树莓派 Pico](https://www.tomshardware.com/news/raspberry-pi-pico-tutorials-pinout-everything-you-need-to-know) 于 2021 年 1 月发布，是该公司的首款微控制器，也标志着其首款定制芯片 RP2040 CPU 的首次亮相。以前的每个树莓派都是一台可以启动到通常为 Linux 的操作系统的功
```suggestion
[树莓派 Pico](https://www.tomshardware.com/news/raspberry-pi-pico-tutorials-pinout-everything-you-need-to-know) 于 2021 年 1 月发布，是该公司的首款微控制器，也标志着其首款定制芯片 RP2040 CPU 的首次亮相。以前的每个树莓派都是一台可以启动到通常为 Linux 的操作系统的功能齐全的计算机，而售价 4 美元的 Pico 则属于与 Arduino 相同的种类。Pico 非常适合用于控制电动机、灯光和传感器，并会在打开电源后立即运行程序，而无需等待启动，也无需担心在不安全关闭的情况下拔下插头会丢失数据的问题。
```

2021-03-13 12:26 UTC, Chorer commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +Pico 具有三个内置的 ADC（模数转换器），这是其他树莓派型号所不具备的。这些转换器让我们可以直接连接至模拟设备，例如操纵杆、电位计和距离传感器。请参阅我们有关[树莓派 Pico 与 Arduino](https://www.tomshardware.com/features/raspberry-pi-pico-vs-arduino) 的文章，以及[哪款树莓派最适合你](https://ww
```suggestion
Pico 具有三个内置的 ADC（模数转换器），这是其他树莓派型号所不具备的。这些转换器让我们可以直接连接至模拟设备，例如操纵杆、电位计和距离传感器。请参阅我们有关[树莓派 Pico 与 Arduino](https://www.tomshardware.com/features/raspberry-pi-pico-vs-arduino) 的文章，以及[哪款树莓派最适合你](https://www.tomshardware.com/how-to/raspberry-pi-buying-guide)，以获取 Pico、Arduino 和其他树莓派之间更详细的比较。
```

2021-03-13 12:26 UTC, Chorer commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +即使树莓派 B+，树莓派 2，树莓派 3B 和其他的一些型号已经过时了，树莓派基金会仍会继续积极制造和销售它们。该组织不愿接受报废（EOL，End-of-Life）产品，因为有些工业客户仍然会需要使用这些机器，而不在乎它是否过时。
```suggestion
即使树莓派 B+、树莓派 2、树莓派 3B 和其他的一些型号已经过时了，树莓派基金会仍会继续积极进行制造和销售。该组织不愿接受报废（EOL，End-of-Life）产品，因为有些工业客户仍然会需要使用这些机器，而不在乎它是否过时。
```

2021-03-13 12:26 UTC, Chorer commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +是的，我们可以参与树莓派竞赛。[树莓派竞赛（Pi Wars）](https://piwars.org/)是一年一度的机器人竞赛。在这个比赛中，我们必须使用树莓派来完成所有装备的构建。参与树莓派竞赛的团队需要在各种挑战中相互竞争，例如导航障碍物路线，弹出气球和导航迷宫。
```suggestion
是的，我们可以参与树莓派竞赛。[树莓派竞赛（Pi Wars）](https://piwars.org/)是一年一度的机器人竞赛。在这个比赛中，我们必须使用树莓派来完成所有装备的构建。参与树莓派竞赛的团队需要在各种挑战中相互竞争，例如导航障碍物路线、弹出气球和导航迷宫。
```

2021-03-13 12:30 UTC, Chorer commented
> > @PassionPenguin 英文和中文行不对应，这样我没法校对。你先改过来吧，ok 了艾特我一下。
> 
> 改不了hh 源文件少了不少内容，要改就得reset

确实少了不少东西，应该是转换格式的时候丢失了……话说这种情况还是修复源文件比较好吧。

2021-03-13 12:34 UTC, PassionPenguin commented
> > > @PassionPenguin 英文和中文行不对应，这样我没法校对。你先改过来吧，ok 了艾特我一下。
> > 
> > 改不了hh 源文件少了不少内容，要改就得reset
> 
> 确实少了不少东西，应该是转换格式的时候丢失了……话说这种情况还是修复源文件比较好吧。

的确，一边翻译一边查，就没像之前那样提pr了

抱歉哈，幸苦校对啦

2021-03-13 13:08 UTC, Chorer commented
> > > > @PassionPenguin 英文和中文行不对应，这样我没法校对。你先改过来吧，ok 了艾特我一下。
> > > 
> > > 
> > > 改不了hh 源文件少了不少内容，要改就得reset
> > 
> > 
> > 确实少了不少东西，应该是转换格式的时候丢失了……话说这种情况还是修复源文件比较好吧。
> 
> 的确，一边翻译一边查，就没像之前那样提pr了
> 
> 抱歉哈，幸苦校对啦

还好，没事。

2021-03-14 04:34 UTC, husiyu commented
校对认领

2021-03-14 04:40 UTC, itcodes commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +是的，我们可以参与树莓派竞赛。[树莓派竞赛（Pi Wars）](https://piwars.org/)是一年一度的机器人竞赛。在这个比赛中，我们必须使用树莓派来完成所有装备的构建。参与树莓派竞赛的团队需要在各种挑战中相互竞争，例如导航障碍物路线，弹出气球和导航迷宫。
哈哈哈。这个很形象。👍🏻le

2021-03-14 04:40 UTC, husiyu approved these changes
Rest LGTM

2021-03-14 04:40 UTC, husiyu commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> -# Raspberry Pi’s Ninth Birthday: 9 Things You Might Not Know
全文  Raspberry Pi  翻译可以统一成“树莓派”么？  有时候保留了 Raspberry Pi ，有时候又不保留，显得有点乱。

2021-03-14 07:21 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +## 7. Raspberry Pi 基金会希望产品永远存在
```suggestion
## 7. 树莓派基金会希望产品永远存在
```

2021-03-14 07:21 UTC, PassionPenguin commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
> +树莓派 OS 是 Debian 的定制版本，是 Raspberry Pi 板的官方操作系统，但到目前为止，它并不是唯一的选择。从适用于树莓派的 Ubuntu 和 FreeBSD Linux 版本到非官方的 Android 和 ChromeOS，我们可以使用大量不同的操作系统。最有趣的一些系统包括：
```suggestion
树莓派 OS 是 Debian 的定制版本，是树莓派的官方操作系统，但到目前为止，它并不是唯一的选择。从适用于树莓派的 Ubuntu 和 FreeBSD Linux 版本到非官方的 Android 和 ChromeOS，我们可以使用大量不同的操作系统。最有趣的一些系统包括：
```

2021-03-14 10:15 UTC, lsvih commented on article/2021/raspberry-pi’s-ninth-birthday-9-things-you-might-not-know.md
>  > * 校对者：
```suggestion
> * 校对者：[husiyu](https://github.com/husiyu)，[Chorer](https://github.com/Chorer)
```

2021-03-14 10:15 UTC, lsvih approved these changes

2021-03-14 10:15 UTC, lsvih commented
我加了校对者信息，记得同步一下哈@PassionPenguin

2021-03-14 10:15 UTC, merged

2021-03-14 10:16 UTC, lsvih commented
@PassionPenguin  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-03-14 10:19 UTC, PassionPenguin commented
https://juejin.cn/post/6939451780610654245/

2021-03-14 12:52 UTC, lsvih commented
收到