Google 的开源模糊测试工具 OSS-Fuzz 现在支持 Java 应用了
xitu/gold-miner pull request #8248
Opened 2021-03-16 18:37 UTC by PassionPenguin

译文翻译完成，resolve #8238

---

@lsvih

2021-03-21 07:11 UTC, huifrank commented
校对认领 @lsvih

2021-03-21 08:32 UTC, huifrank reviewed
完成校对

2021-03-21 08:32 UTC, huifrank commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +Google 通过将 OSS-Fuzz 与 Code Intelligence 的 [Jazzer](https://blog.code-intelligence.com/engineering-jazzer) 模糊器集成在一起，为 Java 和 JVM 启用了模糊处理功能。Jazzer 让我们可以通过 LLVM 项目的 libFuzzer 引擎（运行于进程内，指导覆盖率的模糊引擎）对基于 JV
```suggestion
Google 通过将 OSS-Fuzz 与 Code Intelligence 的 [Jazzer](https://blog.code-intelligence.com/engineering-jazzer) 混沌器集成在一起，为 Java 和 JVM 开启了混沌处理功能。Jazzer 让我们可以通过 LLVM 项目的 libFuzzer 引擎（运行于进程内，指导覆盖率的混沌引擎），类似于对 C / C++ 代码的处理那样，对基于 JVM 语言编写的代码进行混沌处理。Jazzer 支持的语言包括 Java、Clojure、Kotlin 和 Scala。代码覆盖反馈是由 Jazzer 支持的 libFuzzer 基于 JVM 字节码得出的，而 libFuzzer 功能包括：
```

2021-03-21 08:32 UTC, huifrank commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +* [FuzzedDataProvider](https://github.com/google/fuzzing/blob/master/docs/split-inputs.md#fuzzed-data-provider) 用于模糊处理不接受字节数组的代码。
```suggestion
* [FuzzedDataProvider](https://github.com/google/fuzzing/blob/master/docs/split-inputs.md#fuzzed-data-provider) 用于混沌测试中处理不接收字节数组的代码。
```

2021-03-21 08:32 UTC, huifrank commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +[Google 提供了](https://google.github.io/oss-fuzz/getting-started/new-project-guide/jvm-lang/)有关将 OSS-Fuzz 添加到以 JVM 语言编写的开源项目的文档。Jazzer 的开发计划最终要求 Jazzer 支持所有的 libFuzzer 功能。Jazzer 还可以提供通过 Java 原生接口执行的本机代
```suggestion
[Google 提供了](https://google.github.io/oss-fuzz/getting-started/new-project-guide/jvm-lang/)有关将 OSS-Fuzz 添加到以 JVM 语言编写的开源项目的文档。Jazzer 的开发计划要求 Jazzer 最终支持所有的 libFuzzer 功能。Jazzer 还可以提供 Java 通过使用 Native 接口执行的本地代码的覆盖率反馈。这样可以发现内存不安全的本地代码中的内存损坏漏洞。OSS-Fuzz 还同时支持了 Go、Python，C/C + 和 Rust 等语言。
```

2021-03-21 08:40 UTC, huifrank commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +# Google 的开源模糊测试工具 OSS-Fuzz 现在支持 Java 应用了
虽然 Fuzz 有模糊的意思，不过结合全文来看，OSS-Fuzz 是一个混沌工程工具，用于模拟外界异常，错误等。

2021-03-21 08:47 UTC, huifrank commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +* [FuzzedDataProvider](https://github.com/google/fuzzing/blob/master/docs/split-inputs.md#fuzzed-data-provider) 用于模糊处理不接受字节数组的代码。
这句话看了好久，细看了链接内容后 [FuzzedDataProvider](https://github.com/google/fuzzing/blob/master/docs/split-inputs.md#fuzzed-data-provider) ，FuzzedDataProvider应该是 OSS-Fuzz 提供的一个工具类，用于将给定的 byte 数组作为源数据，并将其转换为各种格式的结构数据。

所以，我想这里想表达的意思应该是：用来造各种类型的结构数据，以测试那种入参不是字节数组的方法。

2021-03-21 08:51 UTC, huifrank commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +[Google 提供了](https://google.github.io/oss-fuzz/getting-started/new-project-guide/jvm-lang/)有关将 OSS-Fuzz 添加到以 JVM 语言编写的开源项目的文档。Jazzer 的开发计划最终要求 Jazzer 支持所有的 libFuzzer 功能。Jazzer 还可以提供通过 Java 原生接口执行的本机代
java 是通过 Native 方法来执行本地代码的。
所以，
**Jazzer also can provide coverage feedback from native code executed through the Java Native Interface.** 
的意思应该是在统计代码覆盖率时，java 中的 Native 方法所执行的本地代码也可以一样统计上。(这个功能好犇，是怎么实现的)

2021-03-21 08:56 UTC, huifrank commented
@lsvih @PassionPenguin 完成校对
供参考哈 ，第一次校对 不合适的地方麻烦及时指出。

2021-03-21 09:27 UTC, huifrank commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +Google 的开源模糊测试服务 OSS-Fuzz 现在支持 Java 和 JVM-based 的应用程序了！这项功能于 3 月 10 日公布。
因为 java 也算是 JVM-based 的一种语言，他们严格意思上是包含关系。所以 这个地方改成了 **以及** 。

2021-03-21 09:32 UTC, huifrank commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +[OSS-Fuzz](https://github.com/google/oss-fuzz) 为开源软件提供连续的模糊测试。作为一种用于发现软件中的编程错误和安全漏洞的技术，模糊测试包括将半随机和无效的输入流发送到程序。用内存安全语言（例如 JVM 语言）编写的模糊代码能够帮助我们发现导致程序崩溃或行为不正确的错误。
**例如 JVM 语言 (as JVM languages)** 
这里指的应该是运行在 jvm 上的语言。但是，又没有想到什么好的说法。或者，直接翻译成 **JVM上的语言**？

2021-03-22 01:28 UTC, lsvih commented
@huifrank 感谢校对

2021-03-22 10:31 UTC, PassionPenguin commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +[OSS-Fuzz](https://github.com/google/oss-fuzz) 为开源软件提供连续的模糊测试。作为一种用于发现软件中的编程错误和安全漏洞的技术，模糊测试包括将半随机和无效的输入流发送到程序。用内存安全语言（例如 JVM 语言）编写的模糊代码能够帮助我们发现导致程序崩溃或行为不正确的错误。
基于 JVM 的语言？

2021-03-22 10:32 UTC, PassionPenguin commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +[OSS-Fuzz](https://github.com/google/oss-fuzz) 为开源软件提供连续的模糊测试。作为一种用于发现软件中的编程错误和安全漏洞的技术，模糊测试包括将半随机和无效的输入流发送到程序。用内存安全语言（例如 JVM 语言）编写的模糊代码能够帮助我们发现导致程序崩溃或行为不正确的错误。
```suggestion
[OSS-Fuzz](https://github.com/google/oss-fuzz) 为开源软件提供持续的混沌测试。混沌测试作为一种将半随机和非法的输入流发送到程序，用于发现软件中的编程错误和安全漏洞的技术。用内存安全语言（基于 JVM 的语言）编写的混沌代码能够帮助我们发现导致程序崩溃或行为异常的错误。
```

2021-03-22 10:32 UTC, PassionPenguin commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +[Google 提供了](https://google.github.io/oss-fuzz/getting-started/new-project-guide/jvm-lang/)有关将 OSS-Fuzz 添加到以 JVM 语言编写的开源项目的文档。Jazzer 的开发计划最终要求 Jazzer 支持所有的 libFuzzer 功能。Jazzer 还可以提供通过 Java 原生接口执行的本机代
类似firebase-ndk？

2021-03-22 14:50 UTC, 1autodidact commented
@lsvih 校对认领

2021-03-22 16:59 UTC, 1autodidact requested changes
@lsvih @PassionPenguin 校对完毕

2021-03-22 16:59 UTC, 1autodidact commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +Google 通过将 OSS-Fuzz 与 Code Intelligence 的 [Jazzer](https://blog.code-intelligence.com/engineering-jazzer) 混沌器集成在一起，为 Java 和 JVM 开启了混沌处理功能。Jazzer 让我们可以通过 LLVM 项目的 libFuzzer 引擎（运行于进程内，指导覆盖率的混沌引擎），类似于对
```suggestion
Google 通过将 OSS-Fuzz 与 Code Intelligence 的 [Jazzer](https://blog.code-intelligence.com/engineering-jazzer) 混沌器集成在一起，为 Java 和 JVM 开启了混沌处理功能。Jazzer 让我们可以通过 LLVM 项目的 libFuzzer 引擎（运行于进程内，覆盖引导的的混沌引擎），类似于对 C / C++ 的混沌处理，对基于 JVM 语言编写的代码进行混沌处理。Jazzer 支持的语言包括 Java、Clojure、Kotlin 和 Scala。代码覆盖率的反馈是基于JVM字节码提供给libFuzzer的，而 libFuzzer 功能包括：
```

2021-03-22 16:59 UTC, 1autodidact commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +[Google 提供了](https://google.github.io/oss-fuzz/getting-started/new-project-guide/jvm-lang/)有关将 OSS-Fuzz 添加到以 JVM 语言编写的开源项目的文档。Jazzer 的开发计划要求 Jazzer 最终支持所有的 libFuzzer 功能。Jazzer 还可以提供 Java 通过使用 Native
```suggestion
[Google 提供了](https://google.github.io/oss-fuzz/getting-started/new-project-guide/jvm-lang/)基于JVM语言编写的开源项目加入OSS-Fuzz的文档。Jazzer 的开发计划要求 Jazzer 最终支持所有的 libFuzzer 功能。Jazzer 还可以通过Java Native Interface 执行本地代码时提供覆盖率反馈。这样可以发现内存不安全的本地代码中的内存损坏漏洞。OSS-Fuzz 还同时支持了 Go、Python，C/C + 和 Rust 等语言。
```

2021-03-22 18:16 UTC, PassionPenguin commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +Google 通过将 OSS-Fuzz 与 Code Intelligence 的 [Jazzer](https://blog.code-intelligence.com/engineering-jazzer) 混沌器集成在一起，为 Java 和 JVM 开启了混沌处理功能。Jazzer 让我们可以通过 LLVM 项目的 libFuzzer 引擎（运行于进程内，指导覆盖率的混沌引擎），类似于对
```suggestion
Google 通过将 OSS-Fuzz 与 Code Intelligence 的 [Jazzer](https://blog.code-intelligence.com/engineering-jazzer) 混沌器集成在一起，为 Java 和 JVM 开启了混沌处理功能。Jazzer 让我们可以通过 LLVM 项目的 libFuzzer 引擎（运行于进程内，覆盖引导的的混沌引擎），类似于对 C / C++ 的混沌处理，对基于 JVM 语言编写的代码进行混沌处理。Jazzer 支持的语言包括 Java、Clojure、Kotlin 和 Scala。代码覆盖率的反馈是基于 JVM 字节码提供给 libFuzzer 的，而 libFuzzer 功能包括：
```

2021-03-22 18:17 UTC, PassionPenguin commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
> +[Google 提供了](https://google.github.io/oss-fuzz/getting-started/new-project-guide/jvm-lang/)有关将 OSS-Fuzz 添加到以 JVM 语言编写的开源项目的文档。Jazzer 的开发计划要求 Jazzer 最终支持所有的 libFuzzer 功能。Jazzer 还可以提供 Java 通过使用 Native
```suggestion
[Google 提供了](https://google.github.io/oss-fuzz/getting-started/new-project-guide/jvm-lang/)向基于 JVM 语言编写的开源项目加入 OSS-Fuzz 的文档。Jazzer 的开发计划要求 Jazzer 最终支持所有的 libFuzzer 功能。Jazzer 还可以通过 Java 原生接口执行本地代码时提供覆盖率反馈。这样可以发现内存不安全的本地代码中的内存损坏漏洞。OSS-Fuzz 还同时支持了 Go、Python，C/C + 和 Rust 等语言。
```

2021-03-23 01:40 UTC, lsvih commented
@1autodidact 感谢校对

2021-03-23 01:42 UTC, lsvih commented on article/2021/google-oss-fuzz-extends-fuzzing-to-java-apps.md
>  > * 校对者：
```suggestion
> * 校对者：[huifrank](https://github.com/huifrank)，[1autodidact](https://github.com/1autodidact)
```

2021-03-23 01:42 UTC, lsvih approved these changes

2021-03-23 01:42 UTC, merged