Go 语言全球开发者调查报告
xitu/gold-miner pull request #8262
Opened 2021-03-17 13:42 UTC by samyu2000

译文翻译完成，resolve #8182

2021-03-17 18:18 UTC, PassionPenguin requested changes
校对认领 @lsvih @samyu2000 @husiyu

2021-03-17 18:18 UTC, PassionPenguin commented on article/2021/Go-developer-survey-2020-results.md
>  > * 译者：
译者信息

2021-03-17 18:18 UTC, PassionPenguin commented on article/2021/Go-developer-survey-2020-results.md
？全删了？

2021-03-17 18:18 UTC, PassionPenguin commented on article/2021/Go-developer-survey-2020-results.md
> +大多数被调查者（63%）需要花费 10–30% 的时间用于重构代码，这说明重构是一项公共任务，我们应当采取措施去改善这种情况。这也解释了为何代码重构是编辑器优化中花费成本最高的事项之一。
公众任务 => 大家的共同任务

2021-03-17 18:18 UTC, PassionPenguin commented on article/2021/Go-developer-survey-2020-results.md
> +去年，我们就一些技术问题询问了开发人员，发现几乎 90% 的被调查者都用文本形式的 logging 进行程序调试，因此我们今年增加了一个问题，对该现象进行后续跟踪，以便发现他们为何这么做。结果是：43% 的被调查者认为这种方式方便了不同语言间的调试，42% 的被调查者一向偏爱这种调试方式。然而，也有 27% 不了解如何开启 Go 语言的调试工具，24% 从未使用调试工具，所以需要改进调试工具，使
一边发现

发现 动词不当

2021-03-17 18:18 UTC, PassionPenguin commented on article/2021/Go-developer-survey-2020-results.md
> +这也是我们第三次询问被调查者“你会推荐...吗”，然后统计[净推荐值（NPS）](https://en.wikipedia.org/wiki/Net_Promoter)。今年我们经统计得到的 NPS 是 61（推荐的 68% 减去不推荐的 6%），跟前两年持平。
…… instead of ...

2021-03-17 18:18 UTC, PassionPenguin commented on article/2021/Go-developer-survey-2020-results.md
> +
空行删去

2021-03-17 18:18 UTC, PassionPenguin commented on article/2021/Go-developer-survey-2020-results.md
> +今年我们在问卷中加入了一个新的问题，是跟主要工作职责有关的。我们发现，有 70% 被调查者的工作职责是开发软件系统和应用程序，但也有少数（10%）是负责 IT 系统和架构的设计。
工作职责 => 工作内容/岗位

2021-03-18 01:59 UTC, PingHGao commented
校对认领 @lsvih

2021-03-18 02:02 UTC, lsvih commented
@PingHGao 好的~

2021-03-18 10:18 UTC, PingHGao reviewed
校对完成 @samyu2000 @lsvih

2021-03-18 10:18 UTC, PingHGao commented on article/2021/Go-developer-survey-2020-results.md
> +总体而言，大多数受访者对在三大云服务平台上 Go 的使用感到满意，统计数字与去年相比没有变化。受访者对 AWS 和 GCP 的 Go 开发服务满意度相似，分别达到 82% 和 80%。Azure 的满意度较低(满意率为 58%)，free-text 用户反馈意见中经常提到需要对 Azure 的 Go SDK 进行改进，以及 Go 对 Azure 功能的支持。
```suggestion
总体而言，大多数受访者对在三大云服务平台上 Go 的使用感到满意，统计数字与去年相比没有变化。受访者对 AWS 和 GCP 的 Go 开发服务满意度相似，分别达到 82% 和 80%。Azure 的满意度较低(满意率为 58%)，用户自由反馈的意见中经常提到需要改进 Azure 的 Go SDK，以及提高 GO 对 Azure 函数的支持。
```

2021-03-18 10:18 UTC, PingHGao commented on article/2021/Go-developer-survey-2020-results.md
> +今年，我们推出了一个新的选项——“我可以在任何需要的场景下使用 Go 语言”，这样受访者就可以选择不做不妨碍他们使用 Go 的选择。这大大降低了所有其他选项的选择率，但没有改变它们的相对顺序。我们还为“Go 语言缺乏关键框架”引入了一个选项。
```suggestion
今年，我们推出了一个新的选项——“我已经可以在任何需要的场景下使用 Go 语言”，这样受访者就可以选择不做为什么不选择 Go 语言的相关问题。这大大降低了所有其他选项的选择率，但没有改变它们的相对顺序。我们还引入了 “Go 
 语言缺乏关键框架”的选项。
```

2021-03-18 10:18 UTC, PingHGao commented on article/2021/Go-developer-survey-2020-results.md
> +今年我们要求被调查者提供 5 个他们经常使用的问答网站。去年我们只要求提供 3 个，所以结果不能直接比较，然而，StackOverflow 仍然是最热门的，有 65% 的被调查者在使用。源代码仍然是热门的学习资源（占比 57%），而对于 godoc.org 网站的依赖已经明显下降（只占 39%）。查找包的网站 pkg.go.dev 是今年新加入的，已经成为了 32% 受调查者的首选。使用 pkg
```suggestion
今年我们要求被调查者提供 5 个他们经常使用的问答网站。去年我们只要求提供 3 个，所以结果不能直接比较。然而，StackOverflow 仍然是最热门的，有 65% 的被调查者在使用。源代码仍然是热门的学习资源（占比 57%），而对于 godoc.org 网站的依赖已经明显下降（只占 39%）。查找包的网站 pkg.go.dev 是今年新加入的，已经成为了 32% 受调查者的首选。使用 pkg.go.dev 的受调查者更多地认为：他们可以更快地找到需要的包。91% 选择使用 pkg.go.dev，82% 选择其他网站。
```

2021-03-18 10:18 UTC, PingHGao commented on article/2021/Go-developer-survey-2020-results.md
> +我们发现，有 12% 的受访者认同传统上代表性不足的群体(如族裔、性别认同等)，这一比例与 2019 年相同，有 2% 感受到自己是女性，低于 2019 年的 3%。认同被低估群体的受访者比不认同被低估群体的受访者更不认同“我在Go社区感到受欢迎”(10% vs. 4%)。这些问题让我们能够衡量社区的多样性，并突出拓展和增长的机会。
```suggestion
我们发现，有 12% 的受访者来自于传统上代表性不足的群体(如少数族裔、少数性别等)，这一比例与 2019 年相同。有 2% 的受访者是女性，低于 2019 年的 3%。来自代表性不足群体的受访者更不认同 “Go 社区比较欢迎我”这一陈述( 10% vs. 4%)。这些问题让我们能够衡量社区的多样性，并强调拓展和增长的机会。
```

2021-03-18 10:18 UTC, PingHGao commented on article/2021/Go-developer-survey-2020-results.md
> +今年我们额外增加了一个关于辅助技术使用的问题，发现 8% 的受访者正在使用某种形式的辅助技术。最常用的辅助技术是对比度或颜色设置(有 2% 受访者在使用)。这及时地提醒我们，有的用户对易访问性有一定的要求，这也能帮助驱动我们的设计去满足这些需求。
```suggestion
今年我们额外增加了一个关于辅助技术使用的问题，发现 8% 的受访者正在使用某种形式的辅助技术。最常用的辅助技术是对比度或颜色设置(有 2% 受访者在使用)。这及时地提醒我们，我们有很多有着典型需求的用户，这也能帮助我们的相关团队做出关于网站设计的一些决定。
```

2021-03-18 10:18 UTC, PingHGao commented on article/2021/Go-developer-survey-2020-results.md
> +Go 团队注重多样性和包容性，这不仅仅是正确的做法，而是因为不同的声音可以照亮我们的盲点，并最终使所有用户受益。根据数据隐私法规，我们询问敏感信息的方式，包括性别和传统上代表人数不足的群体，已经发生了变化，我们希望在未来让这些问题，特别是关于性别多样性的问题更具包容性。
```suggestion
Go 团队注重多样性和包容性，这不仅仅是正确的做法，更是因为不同的声音可以照亮我们的盲点，并最终使所有用户受益。根据数据隐私法规，我们询问敏感信息的方式，包括性别和传统上代表性不足的群体，已经发生了变化。我们希望在未来让这些问题，特别是关于性别多样性的问题更具包容性。
```

2021-03-18 10:20 UTC, PingHGao commented on article/2021/Go-developer-survey-2020-results.md
> +
有好多无用的空行，希望译者好好调整格式

2021-03-23 01:34 UTC, samyu2000 commented on article/2021/Go-developer-survey-2020-results.md
> +今年我们在问卷中加入了一个新的问题，是跟主要工作职责有关的。我们发现，有 70% 被调查者的工作职责是开发软件系统和应用程序，但也有少数（10%）是负责 IT 系统和架构的设计。
responsibilities的意思是：责任、职责

2021-03-23 02:48 UTC, lsvih commented
@samyu2000 中间还有不少 hidden conversations 没有处理哈，您可以在 [File Changes](https://github.com/xitu/gold-miner/pull/8262/files) 页面看到全部的校对意见

2021-03-24 16:14 UTC, lsvih commented on article/2021/Go-developer-survey-2020-results.md
> +尽管认同“我在Go社区感到受欢迎”这一说法的受访者比例与去年大致相同，但它似乎随着时间的推移呈下降趋势，或者至少不像其他领域那样保持上升趋势。
```suggestion
尽管认同“我在 Go 社区感到受欢迎”这一说法的受访者比例与去年大致相同，但它似乎随着时间的推移呈下降趋势，或者至少不像其他领域那样保持上升趋势。
```

2021-03-24 16:15 UTC, lsvih approved these changes

2021-03-24 16:15 UTC, merged

2021-03-24 16:16 UTC, lsvih commented
@samyu2000   已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-03-26 13:56 UTC, samyu2000 commented
@lsvih 已发布
https://juejin.cn/post/6943955783067385892

2021-03-27 01:12 UTC, lsvih commented
收到