SREs 和 DevOps 十大开源项目
xitu/gold-miner pull request #8312
Opened 2021-03-24 13:11 UTC by keepmovingljzy

译文翻译完成，resolve #8233

2021-03-24 13:12 UTC, keepmovingljzy commented
@lsvih 翻译完成

2021-03-25 05:10 UTC, kamly commented
@lsvih 校对认领

2021-03-25 08:29 UTC, lsvih commented
@kamly 欢迎校对

2021-03-28 13:49 UTC, kamly reviewed
@lsvih 已经校验完成 @keepmovingljzy 麻烦看看提的建议

2021-03-28 13:49 UTC, kamly commented on article/2021/top-open-source-projects-for-sres-and-devops.md
> +构建可扩展高可用的软件系统是每个 SRE 的最终目标。在我们最新的博客的帮助下，您可以沿着持续学习的道路前进，该博客概述了在监视，部署和维护领域最受追捧的开源项目。 成为成功的 SRE 的方式在于不断学习。 SRE / DevOps 有大量出色的开源项目，每个项目都有新颖而令人兴奋的实施方式，并且常常应对独特的挑战。 这些开源项目的工作量很大，因此您可以更轻松地完成工作。
```suggestion
构建可扩展高可用的软件系统是每个 SRE 的最终目标。在我们最新的博客的帮助下，您可以沿着持续学习的道路前进，其中概述了在监视，部署和维护领域最受追捧的开源项目。
成为一名成功的 SRE 的方式在于不断学习。对于 SRE / DevOps 来说，有大量出色的开源项目，每个项目都有新颖而令人兴奋的实现，并且经常能解决独特的挑战。 这些开源项目完成繁重的工作，因此你可以更轻松地完成你的工作。
```

2021-03-28 13:49 UTC, kamly commented on article/2021/top-open-source-projects-for-sres-and-devops.md
> +在该博客中，我们将在监控、部署和维护方面研究一些最受欢迎的开源项目。在我们所涵盖的项目中，有一些项目可以模拟网络流量，并允许您对不可预测的（混乱的）事件进行建模，以开发可靠的系统。
```suggestion
在该博客中，我们将在监控、部署和维护方面研究一些最受追捧的开源项目。在我们所涉及的项目中，有一些项目可以模拟网络流量，并允许你对不可预测的（混乱的）事件进行建模，以开发可靠的系统。
```

2021-03-28 13:49 UTC, kamly commented on article/2021/top-open-source-projects-for-sres-and-devops.md
> +[Cloudprober](https://github.com/google/cloudprober) 是一个活跃的跟踪和监控应用程序，可以在客户发现故障之前发现故障。它使用“active”监视模型来检查组件是否按预期运行。例如，它会主动运行探测，以确保前端能否访问后端。类似地，可以运行一个探测来验证本地系统是否能够真正到达云内虚拟机。这种跟踪方法使跟踪应用程序的配置变得简单（与实现无关），并
```suggestion
[Cloudprober](https://github.com/google/cloudprober) 是一个主动的跟踪和监控应用程序，可以在客户发现故障之前发现故障。它使用“active”监视模型来检查组件是否按预期运行。例如，它会主动运行探针，以确保前端能否访问后端。类似地，可以运行一个探针来验证你的内部系统是否能够真正访问云内虚拟机。这种跟踪方式可以轻松地，独立于实施之外地跟踪你的应用程序配置，并让你能够轻松地确定系统中故障所在。
```

2021-03-28 13:49 UTC, kamly commented on article/2021/top-open-source-projects-for-sres-and-devops.md
> +- 与 Prometheus and Grafana 的开源监视堆栈的本地集成。Cloudprober 也可以导出探测结果。
```suggestion
- 原生集成 Prometheus 和 Grafana 的开源监控。Cloudprober 也可以导出探测结果。
```

2021-03-28 13:49 UTC, kamly commented on article/2021/top-open-source-projects-for-sres-and-devops.md
> +- 对于云目标，自动发现目标。为 GCE and Kubernetes 提供了开箱即用的支持；其他云服务可以轻松配置。
```suggestion
- 对于云目标，自动发现目标。为 GCE 和 Kubernetes 提供了开箱即用的支持；其他云服务可以轻松配置。
```

2021-03-28 13:49 UTC, kamly commented on article/2021/top-open-source-projects-for-sres-and-devops.md
> +- 致力于简化部署。Cloudprober 已完全编写并编译为 Go 中的静态二进制文件。它可以通过 Docker 容器快速部署。 除了大多数更新之外，由于自动追踪目标，通常不需要重新部署或重新配置 Cloudprober。
```suggestion
- 致力于简化部署。Cloudprober 是完全用 Go 编写并编译成二进制静态文件。它可以通过 Docker 容器快速部署。 除了大多数更新之外，由于自动追踪目标，通常不需要重新部署或重新配置 Cloudprober。
```

2021-03-28 13:49 UTC, kamly commented on article/2021/top-open-source-projects-for-sres-and-devops.md
> +- Cloudprober Docker 的镜像占用很小，只包含一个静态编译的二进制文件，即使运行大量的探测，也只需要非常少的 CPU 和 RAM。
```suggestion
- Cloudprober Docker 的镜像占用很小，只包含一个静态编译的二进制文件，即使运行大量的探针，也只需要非常少的 CPU 和 RAM。
```

2021-03-28 13:49 UTC, kamly commented on article/2021/top-open-source-projects-for-sres-and-devops.md
> +[Kubernetes utility](https://github.com/jetstack/version-checker#:~:text=version%2Dchecker%20is%20a%20Kubernetes,This%20tool%20is%20currently%20experimental.) 允许您观察集群中运行的映像的现有版本。这个工具还允许您在 Grafana 仪表板
```suggestion
一个[Kubernetes 实用工具](https://github.com/jetstack/version-checker#:~:text=version%2Dchecker%20is%20a%20Kubernetes,This%20tool%20is%20currently%20experimental.) 允许你观察集群中运行的镜像的现有版本。这个工具还允许您在 Grafana 仪表板上以表格格式查看当前的镜像版本。
```

2021-03-28 13:49 UTC, kamly commented on article/2021/top-open-source-projects-for-sres-and-devops.md
> +[PowerfulSeal](https://github.com/powerfulseal/powerfulseal) 将故障注入 Kubernetes 集群，帮助您尽快识别问题。 它使创建描述完整混沌实验的方案成为可能。
```suggestion
[PowerfulSeal](https://github.com/powerfulseal/powerfulseal) 将故障注入 Kubernetes 集群，帮助您尽快识别问题。它让创建描述完整混沌实验的方案成为可能。
```

2021-03-29 06:45 UTC, keepmovingljzy commented
@kamly 感谢校对，建议很棒，校对辛苦了~

2021-03-29 13:47 UTC, keepmovingljzy commented
@lsvih

2021-04-05 16:28 UTC, 1autodidact commented
@lsvih 校对认领

2021-04-05 17:04 UTC, 1autodidact requested changes
@lsvih @kamly 校对完成

2021-04-05 17:04 UTC, 1autodidact commented on article/2021/top-open-source-projects-for-sres-and-devops.md
```suggestion
开源技术的一大优点是其可扩展的特性。如果需要，您可以向工具添加特性，以便更好地适应您的自定义架构。这些开源项目有广泛的支持文档和用户社区。由于微服务体系结构将主导云计算领域，用于监控和排除这些实例的可靠工具肯定会成为每个开发人员的工具库的一部分。

```

2021-04-06 01:26 UTC, keepmovingljzy commented
@1autodidact 校对辛苦了，很好的建议，感谢校对~

2021-04-06 01:27 UTC, keepmovingljzy commented
@lsvih 翻译，校对完成

2021-04-06 01:37 UTC, lsvih approved these changes

2021-04-06 01:37 UTC, merged

2021-04-06 01:37 UTC, lsvih commented
@keepmovingljzy  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-04-06 01:56 UTC, keepmovingljzy commented
@lsvih 发布完成 https://juejin.cn/post/6947856765589389326