React vs. Vue 谁是 2021 年最佳 JavaScript 框架
xitu/gold-miner pull request #8317
Opened 2021-03-25 07:22 UTC by keepmovingljzy

译文翻译完成，resolve #8309

2021-03-25 07:22 UTC, keepmovingljzy commented
@lsvih 翻译完成

2021-03-26 01:20 UTC, Chorer commented
@lsvih 校对认领

2021-03-26 01:25 UTC, lsvih commented
@Chorer 欢迎校对

2021-03-26 02:22 UTC, Chorer reviewed
@lsvih 校对完毕

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +在文档方面，Vue 显然是赢家。Vue 的网站以卓越的质量，高度详细的描述，提供多种语言，它的文档和 API 参考被广泛认为是业界最好的。你可以在文档中找到许多问题和问题的明确答案。但是，由于 Vue 社区不像 React 社区那么大，所以您可能很难正确回答文档中没有涉及的问题。
```suggestion
在文档方面，Vue 显然是赢家。Vue 的官网拥有上乘的质量、高度详细的描述、多语言的支持，它的文档和 API 引用普遍被认为是业界最好的。你可以在文档中找到许多问题和详细的答案。但是，由于 Vue 社区不像 React 社区那么大，所以您可能很难找到文档中未涉及问题的正确答案。
```
不要混用 你 和 您。自己检查一下全文吧，我就不一个个挑出来了。

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +React 的文档远远达不到 Vue 的水平，所以您将更多地求助于社区来解决挑战和问题。然而，React 拥有一个庞大而活跃的社区，拥有大量可供选择的学习材料。
```suggestion
React 的文档远远达不到 Vue 的水平，所以您需要更多地求助于社区去解决挑战和问题。好在 React 拥有一个庞大而活跃的社区，拥有大量可供选择的学习材料。
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +React 是由 Facebook 开发和维护的，Facebook 在自己的应用程序中使用它。因此，它拥有大量持续的支持和活跃的社区，不断地构建和维护新工具。
```suggestion
React 是由 Facebook 开发和维护的，Facebook 在自己的应用程序中使用它。因此，它拥有大量持续的支持和一个不断构建和维护新工具的活跃社区。
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +Vue 是由开发人员创建的，而不是一家公司，所以它没有像 React 那样迅速受到欢迎。事实上，当它第一次发布时，许多开发人员都觉得它不可靠，并犹豫是否要采用它。然而，由于用户社区的持续支持和贡献，Vue 已经有了实质性的增长并且越来越受欢迎。
```suggestion
Vue 是由单个开发人员而不是一家公司创建的，所以它没有像 React 那样迅速受到欢迎。事实上，当它第一次发布时，许多开发人员都觉得它不可靠，并犹豫是否要使用它。然而，由于用户社区的持续支持和贡献，Vue 已经有了实质性的增长并且越来越受欢迎。
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +Vue 和 React 都有自己的安全隐患，但是，Vue 应用程序比基于 React 的应用程序更容易获得安全保护。虽然无法针对XSS 漏洞启用自动保护功能，但 Vue 开发人员可以在实施之前对 HTML 代码进行清理或使用外部库来帮助防御攻击。 如果您知道 HTML 是安全的，则可以在渲染之前和之后明确渲染 HTML 内容并保护应用程序。
```suggestion
Vue 和 React 都有自己的安全隐患，但是，Vue 应用程序比基于 React 的应用程序更容易获得安全保护。虽然无法针对 XSS 漏洞等启用自动保护功能，但 Vue 开发人员可以在实施之前对 HTML 代码进行清理或使用外部库来帮助防御攻击。 只要您知道 HTML 是安全的，就可以明确地进行，并在渲染前后保护应用程序。
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +React 安全依靠开发人员使用安全最佳实践来防御XSS漏洞，服务器端渲染攻击，SQL 注入和其他威胁。这可能包括诸如使用 serialize-Javascript 模块，利用脚本注入漏洞以及使用安全的 React Native 应用程序之类的东西。因此，尽管 React 易于使用，但需要大量的专业知识和经验来确保 React 应用程序是安全的。
```suggestion
React 安全依赖于开发人员使用安全最佳实践来防御 XSS漏洞、服务器端渲染攻击、SQL 注入和其他威胁。这可能包括诸如使用 serialize-Javascript 模块，利用脚本注入漏洞以及使用安全的 React Native 应用程序之类的东西。因此，尽管 React 易于使用，但需要大量的专业知识和经验来确保 React 应用程序是安全的。
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +React 的受欢迎程度意味着有大量的经验丰富的开发人员可供雇用。根据 2019 年前端工具调查，超过 48％ 的开发人员对使用 React 感到自在，而只有 23％ 的开发人员声称可以在舒适的水平上使用 Vue。
```suggestion
React 的受欢迎程度意味着有大量的经验丰富的开发人员可供雇用。根据 2019 年前端工具调查，超过 48％ 的开发人员更喜欢使用 React，而只有 23％ 的开发人员声称可以使用 Vue 获得舒适的开发体验。
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +Vue 人气持续增加，并在 2020 年开发人员想要学习的技术排名中排名第四。这种受欢迎程度的增长，加上 Vue 出色的文档和易于学习的知识，很可能会导致合格的 Vue 开发人员增加。
```suggestion
Vue 人气持续增加，并在 2020 年开发人员想要学习的技术排名中位列第四。这种受欢迎程度的增长，加上 Vue 出色的文档和易于学习的知识，很可能会使得合格的 Vue 开发人员增加。
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +总而言之，React 获得了更多的企业支持，在开发人员中更受欢迎，并拥有一个庞大的社区，可以回答您可能有的任何问题。它也更容易扩展，通常是复杂的企业级应用程序的首选。
```suggestion
总而言之，React 获得了更多的企业支持，在开发人员中更受欢迎，并拥有一个可以为您解惑的庞大社区。它也更容易扩展，通常是复杂的企业级应用程序的首选。
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +另一方面，尽管 Vue 还没有得到广泛的支持和使用，但它的普及程度正在不断提高，这主要是因为它出色的文档化、易用性和增量采用功能。Vue 还提供了更多的核心支持和更广泛的内置工具和解决方案。当考虑 React 与 Vue 开发速度时，使用 Vue CLI 4，只需几周时间就可以建立并交付一个适合市场的产品。
```suggestion
另一方面，尽管 Vue 还没有得到广泛的支持和使用，但它的普及程度正在不断提高，这主要是因为它出色的文档、易用性和增量使用功能。Vue 还提供了更多的核心支持以及更广泛的内置工具和解决方案。当考虑 React 与 Vue 的开发速度时，使用 Vue CLI 4，只需几周时间就可以打造并交付一个符合市场需求的产品。
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +显然，这两种框架都是现代 web 应用程序的优秀框架，React 与 Vue 的优缺点根据用例而变化。正确的解决方案完全取决于您的项目目标和偏好。
```suggestion
显然，这两种框架都是现代 web 应用程序的优秀框架，React 与 Vue 的优缺点根据使用场景而有所不同。到底使用哪一个，完全取决于您的项目目标和偏好。
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +**React** 是更好的选择如果想要：
```suggestion
如果你追求的是下面这些，那么 **React** 是更好的选择：
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +- 拥有多种灵活的库，工具和生态系统。
```suggestion
- 拥有多种灵活的库、工具和生态系统。
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +- 轻松的和 TypeScript，Flow，ReasonML，BuckleScript 配合使用。
```suggestion
- 轻松地搭配 TypeScript、Flow、ReasonML、BuckleScript 使用。
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +- 开发一个易于测试和调试的高扩展性的应用程序。
```suggestion
- 开发一个易于测试和调试的高扩展性应用程序。
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +选择 **Vue** 当你想：
```suggestion
如果你追求的是下面这些，就选择 **Vue**：
```

2021-03-26 02:22 UTC, Chorer commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +我们希望这个指南能帮助你解决采用 React.js 还是 Vue.js（在你的下一个项目中）。如果你仍然有关于技术的问题，或者你需要一个有经验的开发团队来帮助创建你的项目，请使用下面的表格给我们发送消息！
```suggestion
我们希望这个指南能帮助你决定在下一个项目中使用 React.js 还是 Vue.js。如果你还有关于技术的问题，或者你需要一个有经验的开发团队来帮助创建你的项目，请使用下面的表单给我们发送消息！
```

2021-03-27 12:50 UTC, PassionPenguin commented
校对认领

2021-03-28 01:55 UTC, keepmovingljzy commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +React JavaScript 库通过使用 ‘组件’ 提供更多的灵活性，只需一小段独立的代码，开发就可以使用它来创建更复杂的逻辑和界面。React 通过 “虚拟 DOM” 与 HTML 文档交互，“虚拟 DOM” 是实际 DOM 的副本，但是所有元素都表示为 JavaScript 对象。这些元素，加上 React 的声明式编程风格和单向数据绑定，简化并加速了开发。
优秀

2021-03-28 02:59 UTC, keepmovingljzy commented
@Chorer 感谢校对，很好的建议，校对辛苦了~

2021-03-28 03:00 UTC, keepmovingljzy commented
@lsvih

2021-03-28 06:05 UTC, PassionPenguin reviewed
校对好啦 @keepmovingljzy 

---

@lsvih

2021-03-28 06:05 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +- 轻松地搭配 TypeScript、Flow、ReasonML、BuckleScript 使用。
```suggestion
- 轻松地搭配 TypeScript、Flow、ReasonML 和 BuckleScript 使用。
```

2021-03-28 06:05 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +React 是由 Facebook 开发和维护的，Facebook 在自己的应用程序中使用它。因此，它拥有大量持续的支持和一个不断构建和维护新工具的活跃社区。
```suggestion
React 是由 Facebook 开发和维护的，而且 Facebook 也在自己的应用程序中使用它。因此，它拥有大量持续的支持和一个不断构建和维护新工具的活跃社区。
```

2021-03-28 10:06 UTC, keepmovingljzy commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **相同点**
作者原本的格式，就不改了

2021-03-28 10:08 UTC, keepmovingljzy commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +- 轻松地搭配 TypeScript、Flow、ReasonML、BuckleScript 使用。
差不多

2021-03-28 10:10 UTC, keepmovingljzy commented
@PassionPenguin 感谢校对，很棒的建议，校对辛苦了~

2021-03-28 10:10 UTC, keepmovingljzy commented
@lsvih

2021-03-28 10:14 UTC, PassionPenguin requested changes

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **Vue.js vs. React —— 它们是什么？**
```suggestion
## Vue.js vs. React —— 它们是什么？
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **相同点**
格式都不对……

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **相同点**
```suggestion
## 相同点
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **不同点**
```suggestion
## 不同点
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **Vue vs. React 性能**
```suggestion
## Vue vs. React 性能
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **1. 应用架构**
```suggestion
### 1. 应用架构
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **2. 可扩展性**
```suggestion
### 2. 可扩展性
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **3. 文档**
```suggestion
### 3. 文档
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **4. 社区支持**
```suggestion
### 4. 社区支持
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **5. 人气**
```suggestion
### 5. 人气
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **5. 人气**
```suggestion
### 5. 人气
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **6. 安全性**
```suggestion
### 6. 安全性
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **7. React vs. Vue 就业市场**
```suggestion
### 7. React vs. Vue 就业市场
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **总结**
```suggestion
## 总结
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +- 构建一个渐进式 web app 或 SPA。
```suggestion
- 构建一个渐进式 Web 应用程序或一个单页应用程序。
```

2021-03-28 10:14 UTC, PassionPenguin commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +- 轻松地搭配 TypeScript、Flow、ReasonML、BuckleScript 使用。
差很多

2021-03-28 10:18 UTC, keepmovingljzy commented on article/2021/react-vs-vue-in-2021-best-javascript-framework.md
> +# **Vue.js vs. React —— 它们是什么？**
这个是作者的排版格式，我们就按照它的格式吧

2021-03-28 10:19 UTC, keepmovingljzy commented
@PassionPenguin 格式就按作者的，不改了

2021-03-28 10:20 UTC, keepmovingljzy commented
@lsvih 翻译校对完成

2021-03-28 10:48 UTC, PassionPenguin commented
> @PassionPenguin 格式就按作者的，不改了

还是请遵循正常的格式，原来的格式有问题就不应该依照着错误的格式

2021-03-28 11:56 UTC, lsvih approved these changes

2021-03-28 11:57 UTC, merged

2021-03-28 11:57 UTC, lsvih commented
@keepmovingljzy  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-03-28 12:22 UTC, keepmovingljzy commented
@lsvih 发布完成

2021-03-28 12:51 UTC, lsvih commented
收到