Postgres 和 MySQL 之间的性能差异
xitu/gold-miner pull request #8437
Opened 2021-04-13 12:14 UTC by greycodee

译文翻译完成，resolve #id

2021-04-14 13:23 UTC, 1autodidact commented
@lsvih 校对认领

2021-04-14 15:07 UTC, lsvih commented
@1autodidact 欢迎校对

2021-04-17 16:50 UTC, 1autodidact requested changes
@lsvih @greycodee 校对完成

2021-04-17 16:50 UTC, 1autodidact commented on article/2021/performance-differences-between-postgres-and-mysql.md
> +我们可以对数据库进行频繁的操作（读取、写入、更新）来了解其性能，然后选出最好的来用到你的项目上。通过上面的测试数据结果我们可以知道，尽管 MySQL 的速度比 PostgreSQL 要快，但也只是在某些特定条件下。
我们可以对数据库进行频繁的操作（读取、写入、更新）来了解其性能，然后选出最好的来用到你的项目上  =>
数据库中频繁执行的操作类型 (读取、写入、更新) 决定了哪个数据库适合你的个人或专业项目

2021-04-17 16:50 UTC, 1autodidact commented on article/2021/performance-differences-between-postgres-and-mysql.md
> +> “局部索引建立在由条件表达式定义的表中的行子集上（称为局部索引的谓词）。索引仅包含满足谓词的那些表行的条目。使用局部索引的主要原因是避免索引常见的值。由于查询通常会出现的值（占所有表行百分之几的查询）无论如何都会遍历大多数表，因此使用索引的好处是微不足道的。更好的策略是创建局部索引，其中这些行完全排除在外。局部索引减少了索引的大小，因此加快了使用索引的查询的速度。 这也将使许多写入操作速度更
占所有表行百分之几的查询 => 占所有表行的百分之几以上的值
因为在所有情况下都不需要更新索引  => 因为索引不需要在所有情况下都更新

2021-04-17 16:50 UTC, 1autodidact commented on article/2021/performance-differences-between-postgres-and-mysql.md
> +**MySQL：** :MySQL 大部分索引（PRIMARY KEY、UNIQUE、INDEX、FULLTEXT）在使用时都是使用B-Tree数据结构。特殊情况下也会使用 R-Tree 的数据结构。 MySQL 也支持 Hash 索引，而且在 InnoDB 引擎下使用 FULLTEXT 索引时是倒序排列的。
[[英文中文间加空格]()](使用B-Tree数据结构)

2021-04-17 16:50 UTC, 1autodidact commented on article/2021/performance-differences-between-postgres-and-mysql.md
> +PostgreSQL 和 MySQL 的另一个性能差异是**复制**。复制指的是将数据从一个数据库复制到另外一台服务器上的数据库。这样的话用户在另一台服务器上读取数据不会影响到当前服务器的数据读取。数据库复制最大的困难之一是协调整个分布式系统中的数据一致性。MySQL 和 PostgreSQL 为数据库复制提供了几个选项。除了一个主服务器，一个备用数据库和多个备用数据库之外，PostgreSQL
这样的话用户在另一台服务器上读取数据不会影响到当前服务器的数据读取 =>
这种数据的分布意味着用户现在可以访问数据而不直接影响其他用户

2021-04-17 16:50 UTC, 1autodidact commented on article/2021/performance-differences-between-postgres-and-mysql.md
> +MVCC 允许多个读取器和写入器同时与 Postgres 数据库进行交互，从而避免了每次有人与数据进行交互时都需要读写锁的情况。附带的好处是此过程可显着提高效率。**MySQL** 利用 InnoDB 存储引擎，支持对同一行的写入和读取而不会互相干扰。MySQL每次将数据写入一行时，也会将一个条目写入回滚段中。此数据结构存储用于将行恢复到其先前状态的**回滚日志**。之所以称为**回滚段**，是
附带的好处是此过程可显着提高效率  =>附带的好处是这个过程显著提高效率
是因为它是用于处理回滚交易的工具 => 因为它是用来处理回滚事务的工具

2021-04-20 02:35 UTC, greycodee commented
@lsvih 为什么这个文章不能用suggestion功能？

2021-04-20 02:38 UTC, lsvih commented
@greycodee 因为您把 fork 里的 branch 删了 = =

2021-04-20 02:47 UTC, greycodee commented
> @greycodee 因为您把 fork 里的 branch 删了 = =

尴尬😳  那这个是不是不能合并了

2021-04-20 02:51 UTC, lsvih commented
@greycodee  您完成第一位的校对修改之后重新建个 branch 提交 pr 吧，不然没法修改这个文件了

2021-04-20 03:05 UTC, greycodee commented
> @greycodee 您完成第一位的校对修改之后重新建个 branch 提交 pr 吧，不然没法修改这个文件了

好的

2021-04-20 10:23 UTC, greycodee commented
@lsvih 新pr：https://github.com/xitu/gold-miner/pull/8483

2021-04-20 15:05 UTC, lsvih commented
好嘞

2021-04-20 15:06 UTC, closed without merging