2021 年最值得使用的 Node.js 框架
xitu/gold-miner pull request #8472
Opened 2021-04-18 08:24 UTC by youngjuning

译文翻译完成，resolve #8301

2021-04-18 10:41 UTC, PassionPenguin requested changes
markdown syntax check

2021-04-18 10:41 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
>  ![Popularity of Hapi.js framework](https://cdn-images-1.medium.com/max/2316/1*bnq7cugj6hQYaLYlY2a53w.png)
alt

2021-04-18 10:41 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
>  ![Express.js popularity](https://cdn-images-1.medium.com/max/2080/1*oV-DuccRP7WvxgSabkTNqQ.png)
alt

2021-04-18 10:41 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
>  ![Nest.js popularity](https://cdn-images-1.medium.com/max/2000/1*uTZrckIaqRi2BolefxaVTg.png)
alt

2021-04-18 10:41 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
>  ![Popularity of Koa.js framework](https://cdn-images-1.medium.com/max/2078/1*lKpRVNszZ6gVbTF_blVJRQ.png)
alt

2021-04-18 10:41 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
>  ![Popularity of socket.io](https://cdn-images-1.medium.com/max/2046/1*5zUKf_Dt48W00aWfkAs84g.png)
alt

2021-04-18 10:41 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
>  ![Popularity of adoni.js](https://cdn-images-1.medium.com/max/2052/1*QVu2Z2wbudWv06tBwkJ8mQ.png)
alt

2021-04-18 10:41 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
>  ![Popularity of sails.js framework](https://cdn-images-1.medium.com/max/2000/1*nYu5aJOd4f933c6WZkX8eA.png)
alt

2021-04-18 10:41 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +5. 它基于最常用的编程语言--JavaScript。
```suggestion
5. 它基于最常用的编程语言 JavaScript。
```
```suggestion
5. 它基于最常用的编程语言 —— JavaScript。
```

2021-04-18 10:41 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +Express.js 是一个灵活而简约的 Node.js 应用框架。这个插件并不是围绕着特定的组件构建的，因此它并不限制你使用什么技术。这就给了开发者尝试的自由。他们还可以获得闪电般的配置和纯JavaScript 体验，这些特性使 Express.js 成为快速原型设计和敏捷开发市场的有力竞争者。
```suggestion
Express.js 是一个灵活而简约的 Node.js 应用框架。这个插件并不是围绕着特定的组件构建的，因此它并不限制你使用什么技术。这就给了开发者尝试的自由。他们还可以获得闪电般的配置和纯 JavaScript 体验，这些特性使 Express.js 成为快速原型设计和敏捷开发市场的有力竞争者。
```

2021-04-18 10:41 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +Sails.js是又一个实时 [Node.js](https://aglowiditsolutions.com/blog/hidden-cost-of-app-development/) MVC框架。它基于 Express 构建，其 MVC 架构与 Ruby on Rails 相似。它与 Ruby on Rails 的不同之处在于，它提供了对更现代的、以数据为中心的 API 和 Web 应用开发
```suggestion
Sails.js 是又一个实时 [Node.js](https://aglowiditsolutions.com/blog/hidden-cost-of-app-development/) MVC 框架。它基于 Express 构建，其 MVC 架构与 Ruby on Rails 相似。它与 Ruby on Rails 的不同之处在于，它提供了对更现代的、以数据为中心的 API 和 Web 应用开发风格的支持。
```

2021-04-18 10:41 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +任何想要一个模拟 MVC 模式的 [Node.js](https://aglowiditsolutions.com/blog/hidden-cost-of-app-development/) 框架（如Laravel和Ruby on Rails）、想要实现现代应用架构，并构建以数据为中心的 API 和实时应用的开发者都应该在他们的下一个项目中使用 Sails.js。
```suggestion
任何想要一个模拟 MVC 模式的 [Node.js](https://aglowiditsolutions.com/blog/hidden-cost-of-app-development/) 框架（如 Laravel 和 Ruby on Rails）、想要实现现代应用架构，并构建以数据为中心的 API 和实时应用的开发者都应该在他们的下一个项目中使用 Sails.js。
```

2021-04-18 11:14 UTC, PassionPenguin requested changes

2021-04-18 11:14 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +- **License**：BSD-3-Clause
missing translation

2021-04-18 11:14 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +- **License**：MIT
missing translation

2021-04-18 11:14 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +- **License**：MIT
missing translation

2021-04-18 11:14 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +- **License**：MIT
```suggestion
  - **Version**：2.13.1
  - **Contributors**：219
  - **Used by**：160k
- **NPM Weekly Download**：870,944
- **License**：MIT
```

2021-04-18 11:14 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +- **License**：MIT
```suggestion
  - **Version**：4.0.0
  - **Contributors**：189
  - **Used by**：2.2m
- **NPM Weekly Downloads**：3,617,636
- **License**：MIT
```

2021-04-18 11:14 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +- **License**：MIT
```suggestion
  - **Version**：4.0.0
  - **Contributors**：452
- NPM：不可用
- **License**：MIT
```

2021-04-18 11:14 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +- **License**：MIT
missing translation

2021-04-18 11:14 UTC, PassionPenguin commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +- **License**：MIT
missing translation

2021-04-22 14:30 UTC, xilihuasi commented
@lsvih 校对认领

2021-04-23 01:31 UTC, lsvih commented
@xilihuasi 欢迎校对

2021-04-23 03:10 UTC, youngjuning commented
@xilihuasi 感谢校对

2021-04-23 15:46 UTC, xilihuasi reviewed
@youngjuning @lsvih 校对完成
整体很好，只是有部分遗漏。还有些修改建议，仅供参考。

2021-04-23 15:46 UTC, xilihuasi commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +* 结合了函数式编程、面向对象编程和反应式编程的特点。
反应式编程 => 函数响应式编程

2021-04-23 15:46 UTC, xilihuasi commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +Koa.js 是一个开源的 Node 网络框架，由 Express.js 原班人马创建。通过 Koa，他们的目标是为 Web 应用和 API 创建一个更小、更有价值、更强大的平台。它提供了多种高效的方法，以让构建服务的过程更快速。
网络框架 => web 框架

2021-04-23 15:46 UTC, xilihuasi commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +要做到这一点，客户端需要在浏览器中安装 Socket.io，服务器也要集成 Socket.io 包。这使得数据可以在数百万种形式中共享。然而，最受欢迎的方法仍然是 JSON。
段落错位了

2021-04-23 15:46 UTC, xilihuasi commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +要做到这一点，客户端需要在浏览器中安装 Socket.io，服务器也要集成 Socket.io 包。这使得数据可以在数百万种形式中共享。然而，最受欢迎的方法仍然是 JSON。
可以在数百万种形式中共享 => 可以以各种形式共享

2021-04-23 15:46 UTC, xilihuasi commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> -* Internal
Internal 漏了

2021-04-23 15:46 UTC, xilihuasi commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +* 速度和可靠性突出
速度和可靠性突出 => 出色的速度和可靠性

2021-04-23 15:46 UTC, xilihuasi commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +Socket.io 是最好的基于事件的实时双向通信工具之一。任何想要在应用中添加实时分析功能的人都应该使用它。Socket.io 对于实时游戏应用也很有用。在实时游戏中使用基本的 HTTP 或 HTTPS 协议是不可行的，因为这些文件很大，建立通信需要时间。在这里，我们使用体积更小的 socket 包，几乎是实时地完成工作，以获得更流畅和更好的体验。
我们使用体积更小的 socket 包，几乎是实时地完成工作  => 我们使用体积更小的 socket 包来保证准“实时”

2021-04-23 15:46 UTC, xilihuasi commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +* 互操作性
互操作性 => 互通性

2021-04-23 15:46 UTC, xilihuasi commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +- **NPM Weekly Downloads**：3808
漏翻周下载数

2021-04-23 15:46 UTC, xilihuasi commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> -Adonis.js is a [Node.js ](https://aglowiditsolutions.com/blog/hidden-cost-of-app-development/)MVC framework that can run on all operating systems. It provides a stable ecosystem for writing server-si
漏翻
Adonis.js provides [Node.js](https://aglowiditsolutions.com/blog/hidden-cost-of-app-development/) with the same features and abilities that Laravel has naturally.

2021-04-23 15:46 UTC, xilihuasi commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +* 验证和给每一个用户的输入做卫生处理。
验证和给每一个用户的输入做卫生处理 => 验证和清理用户输入

2021-04-23 15:46 UTC, xilihuasi commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +- **NPM Weekly Downloads**：20,457
漏翻周下载数

2021-04-25 09:52 UTC, youngjuning commented on article/2021/top-node-js-frameworks-to-use-in-2021.md
> +- **License**：BSD-3-Clause
原文格式不方便阅读

2021-04-25 10:02 UTC, youngjuning commented
@xilihuasi 感谢校对，采纳了大部分建议

2021-04-26 01:36 UTC, lsvih reviewed
劳烦增加一下校对者信息哈

2021-04-26 09:35 UTC, youngjuning commented
@lsvih 已添加

2021-04-26 09:47 UTC, lsvih approved these changes

2021-04-26 09:47 UTC, merged

2021-04-26 09:48 UTC, lsvih commented
@youngjuning  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-04-27 03:25 UTC, youngjuning commented
@Isvih  已发布 https://juejin.cn/post/6955402195311263751

2021-04-27 04:41 UTC, lsvih commented
收到~