Chromium 隐私沙盒让用户隐私更安全
xitu/gold-miner pull request #8513
Opened 2021-04-27 03:54 UTC by Baddyo

Chromium 隐私沙盒让用户隐私更安全

译文翻译完成，resolve #8449

2021-04-27 05:50 UTC, CristoMonte commented
认领校对

2021-04-27 05:51 UTC, CristoMonte commented
认领校对 @lsvih

2021-04-27 06:23 UTC, lsvih commented
@CristoMonte 欢迎校对

2021-04-28 00:55 UTC, PingHGao commented
校对认领 @lsvih

2021-04-28 01:26 UTC, lsvih commented
@PingHGao 好嘞

2021-04-28 07:38 UTC, CristoMonte approved these changes
校对完成

2021-04-28 07:38 UTC, CristoMonte commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +浏览器指纹追踪是一种识别和追踪用户的技术，营销商通过轻松获取到的浏览器型号和版本、操作系统、所用插件、时区、语言、屏幕分辨率等其他这些简单的设置信息就能确定唯一用户。
```suggestion
浏览器指纹识别是一种识别和追踪用户的技术，营销商通过一些简单的信息，例如用户浏览器型号和版本、操作系统、插件、时区、语言、屏幕分辨率等其他设置信息就能确定唯一用户并对其进行跟踪。
```

2021-04-28 07:38 UTC, CristoMonte commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +为了使隐私沙盒能防御指纹追踪，Google 给出了一种反指纹追踪的方法。这种新方法叫做 [Gnatcatcher](https://github.com/bslassey/ip-blindness)，它会试图隐藏用户的 IP 地址，同时不干涉网站的正常行为。由于 Gnatcatcher 还处于开发中，所以它会根据社区反馈不断进行优化。
```suggestion
为了使隐私沙盒能防御指纹识别，Google 给出了一种反指纹识别的方法。这种新方法叫做 [Gnatcatcher](https://github.com/bslassey/ip-blindness)，它会试图隐藏用户的 IP 地址，同时不干涉网站的正常行为。由于 Gnatcatcher 还处于开发中，所以它会根据社区反馈不断进行优化。
```

2021-04-28 07:38 UTC, CristoMonte commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +为了改变网络生态环境，人们做出过许多大胆的尝试。但大多数尝试都以失败告终，主要原因在于抵触改变的利益相关者何止一二。但若是使用了隐私沙盒方案，Google 声称，与第三方 Cookie 方案相比，广告商和营销商每花费一美元的转化率最多只会下降 5%。另一方面，消费者总是会乐于看到他们的隐私信息在新的模型中更加安全。
```suggestion
为了改变网络生态环境，人们做出过许多大胆的尝试。但大多数尝试都以失败告终，主要原因在于抵触改变的利益相关者何止一二。但若是使用了隐私沙盒方案，Google 声称，与第三方 Cookie 方案相比，广告商和营销商每一美元的转化率最多只会下降 5%。另一方面，消费者总是会乐于看到他们的隐私信息在新的模型中更加安全。
```

2021-04-28 07:38 UTC, CristoMonte commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +但广告和营销领域的从业者自有他们的担忧。他们怀疑 Google 是否能对自家团队和外人做到一碗水端平。Google 自己有专门的广告团队。专家们想知道这些内部团队是否也和外部营销商、广告商及其他广告从业者一样，只能拿到同样的聚合数据。已经有[事实](http://digiday.com/uk/google-winner-googles-anti-tracking-moves-slow-amazo
```suggestion
但广告和营销领域的从业者自有他们的担忧。他们怀疑 Google 在对待对自家团队和外人时能否做到一碗水端平。Google 自己有专门的广告团队。专家们想知道这些内部团队是否也和外部营销商、广告商及其他广告从业者一样，只能拿到同样的聚合数据。已经有[事实](http://digiday.com/uk/google-winner-googles-anti-tracking-moves-slow-amazons-ad-growth/)能证明 Google 曾经耍花招来保护自己的广告收入份额。如果这次仍是故技重施，那就意味着 Google 的自家团队能获取到更多细粒度的用户数据，这对广告行业的其他从业者是不公平的。如果 Google 打算耍什么花招，等着瞧吧，绝对是一场大乱。
```

2021-04-29 02:07 UTC, Baddyo commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +[群组联合学习（Federated Learning of Cohorts，简称 FLoC）](https://github.com/jkarlin/floc)是旨在在定向广告投放中替换掉第三方 Cookie 的方案之一。该方案希望改变实现用户跟踪的方式，与其观察每个人的浏览行为，不如观察一组相似人群的行为。这种新的方式使企业能够把兴趣相似的用户进行分群，让定向广告匹配到适合的用户。这种新颖的方
> 

「改变实现用户跟踪的方式」直接改为「改变跟踪用户的方式」吧，

2021-04-30 07:16 UTC, PingHGao submitted a review, later dismissed
校对完成 @Baddyo

2021-04-30 07:16 UTC, PingHGao commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +Google 预计于今年 3 月开放试用，跟随下一版本的 Chrome 发布，该版本支持升级版的可信 Token API。详情[见此](https://web.dev/trust-tokens/)。
```suggestion
Google 预计于今年 3 月开放试用，跟随下一版本的 Chrome 发布，该版本支持升级版的可信 Token API，详情[见此](https://web.dev/trust-tokens/)。
```

2021-04-30 07:16 UTC, PingHGao commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +关于浏览器指纹识别及其危险性，我曾写过几篇文章。详情[见此]((https://blog.bitsrc.io/the-darker-side-of-pwas-you-might-not-be-aware-of-ffa7b1d08888))。
```suggestion
关于浏览器指纹识别及其危险性，我曾写过几篇文章，详情[见此]((https://blog.bitsrc.io/the-darker-side-of-pwas-you-might-not-be-aware-of-ffa7b1d08888))。
```

2021-04-30 07:20 UTC, PingHGao commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +Google 的广告团队已经将这套方案成功通过测试，并发现**与基于 Cookie 的广告方案相比，广告商可以预期每一美元达到至少 95% 的转化率**。这项发现足以证明，FLoC 就是隐私为重趋势下的未来之路。
这里的翻译应该改改的，文章后面不也说了新的方式相较于传统的方式收益只会降低5%。所以这里的95%是传统方式转化率的95%。而不是广告经费转化率95%，

2021-04-30 07:22 UTC, PingHGao commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +Google 的广告团队已经将这套方案成功通过测试，并发现**与基于 Cookie 的广告方案相比，广告商可以预期每一美元达到至少 95% 的转化率**。这项发现足以证明，FLoC 就是隐私为重趋势下的未来之路。
只有这里有要求译者要好好斟酌，其它都尊重译者的决定。

2021-04-30 10:31 UTC, Baddyo commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +下面就让我们来看看，隐私沙盒是如何做到改变我们的上网方式而不使用第三方 Cookie 的。
> 

这里的「Cookie」应该是首字母大写、单数形式吧？

2021-04-30 10:42 UTC, Baddyo commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +Google 的广告团队已经将这套方案成功通过测试，并发现**与基于 Cookie 的广告方案相比，广告商可以预期每一美元达到至少 95% 的转化率**。这项发现足以证明，FLoC 就是隐私为重趋势下的未来之路。
> 

是的是的，后半句也说了「compared to cookie-based advertising」，可见「95%」的比较对象确实是传统方案的转化率。

2021-04-30 12:45 UTC, PassionPenguin requested changes
```sh
   34:32-34:81           no-space-in-emphasis          Emphasis content can not start / end with space.
   
   '与基于 Cookie 的广告方案相比，广告商每花费一美元预计可以得到的转化率至少是前者的 95% '
```

2021-04-30 12:45 UTC, PassionPenguin commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +Google 的广告团队已经将这套方案成功通过测试，并发现**与基于 Cookie 的广告方案相比，广告商每花费一美元预计可以得到的转化率至少是前者的 95% **。这项发现足以证明，FLoC 就是隐私为重趋势下的未来之路。
```suggestion
Google 的广告团队已经将这套方案成功通过测试，并发现**与基于 Cookie 的广告方案相比，广告商每花费一美元预计可以得到的转化率至少是前者的 95%**。这项发现足以证明，FLoC 就是隐私为重趋势下的未来之路。
```

2021-05-01 07:05 UTC, Chorer commented
校对认领

2021-05-01 07:16 UTC, Chorer reviewed
校对完毕

2021-05-01 07:16 UTC, Chorer commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +近来关于隐私安全的讨论非常之多，尤其是浏览器相关的话题，更是炙手可热。不久前，WhatsApp 的一则声明引起了轩然大波，他们宣布将与其母公司 Facebook 共享用户数据。据 [Wired](https://www.wired.com/story/whatsapp-facebook-data-share-notification/) 爆料，WhatsApp 与 Facebook 共享用户数据
```suggestion
近来关于隐私安全的讨论非常热烈，尤其是浏览器相关的话题。不久前，WhatsApp 的一则声明引起了轩然大波，他们宣布将与其母公司 Facebook 共享用户数据。据 [Wired](https://www.wired.com/story/whatsapp-facebook-data-share-notification/) 爆料，WhatsApp 与 Facebook 共享用户数据已有数年之久。这场骚动引发了关于把用户数据用于广告服务的讨论。
```
炙手可热形容气焰嚣张，这里用错了。

2021-05-01 07:16 UTC, Chorer commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +Google 的广告团队已经将这套方案成功通过测试，并发现**与基于 Cookie 的广告方案相比，广告商每花费一美元预计可以得到的转化率至少是前者的 95% **。这项发现足以证明，FLoC 就是隐私为重趋势下的未来之路。
```suggestion
Google 广告团队的这套方案已经成功通过测试，并发现**与基于 Cookie 的广告方案相比，广告商每花费一美元预计可以得到的转化率至少是前者的 95%**。这项发现足以证明，FLoC 就是隐私为重趋势下的未来之路。
```

2021-05-01 07:16 UTC, Chorer commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +为了改变网络生态环境，人们做出过许多大胆的尝试。但大多数尝试都以失败告终，主要原因在于抵触改变的利益相关者何止一二。但若是使用了隐私沙盒方案，Google 声称，与第三方 Cookie 方案相比，广告商和营销商每花费一美元的转化率最多只会下降 5%。另一方面，消费者总是会乐于看到他们的隐私信息在新的模型中更加安全。
```suggestion
为了改变网络生态环境，人们做出过许多大胆的尝试，但大多数尝试都以失败告终，主要原因在于抵触改变的利益相关者何止一二。但 Google 声称，若是使用了隐私沙盒方案，与第三方 Cookie 方案相比，广告商和营销商每花费一美元的转化率最多只会下降 5%。另一方面，消费者总是会乐于看到他们的隐私信息在新的模型中更加安全。
```

2021-05-01 07:16 UTC, Chorer commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +但广告和营销领域的从业者自有他们的担忧。他们怀疑 Google 是否能对自家团队和外人做到一碗水端平。Google 自己有专门的广告团队。专家们想知道这些内部团队是否也和外部营销商、广告商及其他广告从业者一样，只能拿到同样的聚合数据。已经有[事实](http://digiday.com/uk/google-winner-googles-anti-tracking-moves-slow-amazo
```suggestion
但广告和营销领域的从业者自有他们的担忧。他们怀疑 Google 是否能对自家团队和外人做到一碗水端平。Google 自己有专门的广告团队，专家们想知道这些内部团队是否也和外部营销商、广告商及其他广告从业者一样，只能拿到同样的聚合数据。已经有[事实](http://digiday.com/uk/google-winner-googles-anti-tracking-moves-slow-amazons-ad-growth/)能证明 Google 曾经耍花招来保护自己的广告收入份额，如果这次仍是故技重施，那就意味着 Google 的自家团队能获取到更多细粒度的用户数据，这对广告行业的其他从业者是不公平的。如果 Google 打算耍什么花招，等着瞧吧，绝对是一场大乱。
```

2021-05-03 13:37 UTC, Baddyo commented
> ```shell
>    34:32-34:81           no-space-in-emphasis          Emphasis content can not start / end with space.
>    
>    '与基于 Cookie 的广告方案相比，广告商每花费一美元预计可以得到的转化率至少是前者的 95% '
> ```

咦？这是什么先进工具？

2021-05-03 13:45 UTC, Baddyo commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +近来关于隐私安全的讨论非常之多，尤其是浏览器相关的话题，更是炙手可热。不久前，WhatsApp 的一则声明引起了轩然大波，他们宣布将与其母公司 Facebook 共享用户数据。据 [Wired](https://www.wired.com/story/whatsapp-facebook-data-share-notification/) 爆料，WhatsApp 与 Facebook 共享用户数据
> 炙手可热形容气焰嚣张，这里用错了。

感谢指正。惭愧惭愧，掉书袋翻车了。

2021-05-03 14:01 UTC, Baddyo commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +为了改变网络生态环境，人们做出过许多大胆的尝试。但大多数尝试都以失败告终，主要原因在于抵触改变的利益相关者何止一二。但若是使用了隐私沙盒方案，Google 声称，与第三方 Cookie 方案相比，广告商和营销商每花费一美元的转化率最多只会下降 5%。另一方面，消费者总是会乐于看到他们的隐私信息在新的模型中更加安全。
> 

这里我觉得我的译法更符合原义，就不改了哈。

2021-05-03 14:03 UTC, Baddyo commented on article/2021/better-privacy-with-chromiums-privacy-sandbox.md
> +但广告和营销领域的从业者自有他们的担忧。他们怀疑 Google 是否能对自家团队和外人做到一碗水端平。Google 自己有专门的广告团队。专家们想知道这些内部团队是否也和外部营销商、广告商及其他广告从业者一样，只能拿到同样的聚合数据。已经有[事实](http://digiday.com/uk/google-winner-googles-anti-tracking-moves-slow-amazo
> 

我感觉这两处标点按原文来就行，维持原译法了哈。

2021-05-03 14:21 UTC, lsvih approved these changes

2021-05-03 14:21 UTC, merged

2021-05-03 14:21 UTC, lsvih commented
@Baddyo  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-05-03 14:41 UTC, Baddyo commented
> @Baddyo 已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。
> 
> 掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
> 专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

已发布到掘金：https://juejin.cn/post/6958070229956034591
感谢大家。

2021-05-03 15:28 UTC, lsvih commented
收到~