走向 kotlin 1.5
xitu/gold-miner pull request #8523
Opened 2021-04-29 02:26 UTC by samyu2000

译文翻译完成，resolve #8505
刚才操作失误，现在重新发起 pull request

2021-04-30 05:50 UTC, Kimhooo commented
@lsvih 校对认领

2021-04-30 06:19 UTC, Kimhooo reviewed
校对完成@lsvih  @samyu2000 
翻译的不错:)

2021-04-30 06:19 UTC, Kimhooo commented on article/2021/the-road-to-kotlin-1-5.md
> +> 后端逻辑中有很多功能是共享的，并且有统一的管道，可以实现大多数特性、优化和 BUG 修复工作一次性完成。
```suggestion
> 后端逻辑中有很多功能是共享的，并且有统一的管道，可以实现一次性完成大多数特性、优化和 BUG 修复工作。
```

2021-04-30 06:19 UTC, Kimhooo commented on article/2021/the-road-to-kotlin-1-5.md
> +> 统一的后端基础架构使编译器能跨平台使用。它有助于接通管道以及添加某些定制的处理和/或转换，并且是自动化、适用于一切需求的。
```suggestion
> 统一的后端基础架构使编译器能跨平台使用。它有助于接通管道以及添加某些定制的处理和转换，并且是自动化、适用于一切需求的。
```

//这里的and/or是英文中常见的连词，翻译成并列就好

2021-04-30 06:19 UTC, Kimhooo commented on article/2021/the-road-to-kotlin-1-5.md
> +为了提高构建效率，Kotlin Gradle 插件如今实现了跟 [Gradle configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) 的兼容，这是一个未普遍使用的 Gradle 特性，它的功能是通过缓存配置阶段的结果并在后续构建中重用它来加快构建速度。考虑下面的例子：
```suggestion
为了提高构建效率，Kotlin Gradle 插件如今实现了跟 [Gradle configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) 的兼容，这是一个未普遍使用的 Gradle 特性，它的功能是通过缓存配置阶段的结果并在后续构建中重用它来加快构建速度。考虑下面的例子：
```
```suggestion
为了提高构建效率，Kotlin Gradle 插件如今实现了跟 [Gradle configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) 的兼容，这是一个未普遍使用的 Gradle 特性，它的功能是通过缓存配置阶段的结果并在后续构建中重用它来加快构建速度。参考下面的例子：
```

2021-04-30 06:35 UTC, lsvih commented
@Kimhooo  感谢校对

2021-04-30 07:23 UTC, PingHGao commented
校对认领 @lsvih

2021-04-30 07:38 UTC, PingHGao approved these changes
校对完成 @samyu2000

2021-04-30 07:38 UTC, PingHGao commented on article/2021/the-road-to-kotlin-1-5.md
> +后端的变化包括：呈现于后端界面的一些 [BUG 修复工具](https://youtrack.jetbrains.com/issues/KT?q=%23fixed-in-jvm-ir%20sort%20by:%20votes&_ga=2.221556248.1626189385.1614553347-1788185777.1610805116)和用于改进性能的新特性。用于构建 Android U
```suggestion
后端的变化包括：呈现于后端界面的一些 [BUG 修复工具](https://youtrack.jetbrains.com/issues/KT?q=%23fixed-in-jvm-ir%20sort%20by:%20votes&_ga=2.221556248.1626189385.1614553347-1788185777.1610805116)和用于改进性能的新特性。用于构建 Android UI 的新工具箱 [Jetpack Compose](https://developer.android.com/jetpack/compose) 将只适用于新的后端编译器。
```

2021-04-30 07:38 UTC, PingHGao commented on article/2021/the-road-to-kotlin-1-5.md
> +JetBrains 的市场主管 [Alina Grebenkina](https://www.linkedin.com/in/alina-grebenkina-19756346/) 讲述了三个后端组件合并的[好处](https://blog.jetbrains.com/kotlin/2021/02/the-jvm-backend-is-in-beta-let-s-make-it-stable-t
```suggestion
JetBrains 的市场主管 [Alina Grebenkina](https://www.linkedin.com/in/alina-grebenkina-19756346/) 讲述了三个后端组件合并的[好处](https://blog.jetbrains.com/kotlin/2021/02/the-jvm-backend-is-in-beta-let-s-make-it-stable-together/)，他写道：
```

2021-04-30 07:38 UTC, PingHGao commented on article/2021/the-road-to-kotlin-1-5.md
> +[Java 16 发布](https://www.infoq.com/news/2021/03/java16-released/)的同时，Kotlin 也支持一种新数据类型————[**`record`**](https://cr.openjdk.java.net/~briangoetz/amber/datum.html)，因此 Kotlin 与 Java 可以互操作。Java 中的 **`re
```suggestion
随着 [Java 16 的发布](https://www.infoq.com/news/2021/03/java16-released/)，Kotlin 也支持一种新数据类型 ———— [**`record`**](https://cr.openjdk.java.net/~briangoetz/amber/datum.html)，因此 Kotlin 与 Java 可以互操作。Java 中的 **`record`** 类型在 Kotlin 中可以使用 **`@JvmRecord`** 注解来声明：
```
[破折号前后需要添加空格](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E7%A0%B4%E6%8A%98%E5%8F%B7%E5%89%8D%E5%90%8E%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E4%B8%80%E4%B8%AA%E7%A9%BA%E6%A0%BC)

2021-04-30 11:07 UTC, PassionPenguin requested changes
1. 语句标点符号使用不当，大量使用了逗号连接毫无关联的两个句子
2. 漏译
3. 将专有名词翻译
4. 部分词语翻译的有些跑
5. 把女生弄成男生
6. 强加因果

2021-04-30 11:07 UTC, PassionPenguin commented on article/2021/the-road-to-kotlin-1-5.md
> +JetBrains 的市场主管 [Alina Grebenkina](https://www.linkedin.com/in/alina-grebenkina-19756346/) 讲述了三个后端组件合并的[好处](https://blog.jetbrains.com/kotlin/2021/02/the-jvm-backend-is-in-beta-let-s-make-it-stable-t
```suggestion
JetBrains 的市场主管 [Alina Grebenkina](https://www.linkedin.com/in/alina-grebenkina-19756346/) 讲述了三个后端组件合并的[好处](https://blog.jetbrains.com/kotlin/2021/02/the-jvm-backend-is-in-beta-let-s-make-it-stable-together/)，写道：
```

另外她是个女生

2021-04-30 11:07 UTC, PassionPenguin commented on article/2021/the-road-to-kotlin-1-5.md
> +> 后端逻辑中有很多功能是共享的，并且有统一的管道，可以实现大多数特性、优化和 BUG 修复工作一次性完成。
```suggestion
> 后端逻辑中有很多功能是共享的，并且有统一的管道，可以实现一次性完成多目标的大多数特性、优化和 Bug 的修复工作。
```

2021-04-30 11:07 UTC, PassionPenguin commented on article/2021/the-road-to-kotlin-1-5.md
> +[Java 16 发布](https://www.infoq.com/news/2021/03/java16-released/)的同时，Kotlin 也支持一种新数据类型————[**`record`**](https://cr.openjdk.java.net/~briangoetz/amber/datum.html)，因此 Kotlin 与 Java 可以互操作。Java 中的 **`re
```suggestion
随着 [Java 16 的发布](https://www.infoq.com/news/2021/03/java16-released/)，Kotlin 也支持一种新数据类型 ———— [**`record`**](https://cr.openjdk.java.net/~briangoetz/amber/datum.html)，以维持 Kotlin 与 Java 的交互能力。Java 中的 **`record`** 类型在 Kotlin 中可以使用 **`@JvmRecord`** 注解来声明：
```

2021-04-30 11:07 UTC, PassionPenguin commented on article/2021/the-road-to-kotlin-1-5.md
> +编译器必须设置 **`-Xjvm-enable-preview`** 和 **`-language-version 1.5`**，用于测试这一新特性。
```suggestion
编译器必须设置 **`-Xjvm-enable-preview`** 和 **`-language-version 1.5`** 以用于测试这一新特性。
```

2021-04-30 11:07 UTC, PassionPenguin commented on article/2021/the-road-to-kotlin-1-5.md
> +Kotlin 中的密封接口是对密封类的补充，它可以创建更灵活的[密封类层次结构](https://kotlinlang.org/docs/whatsnew1430.html#package-wide-sealed-class-hierarchies)。这样，派生类可以继承多个密封接口：
```suggestion
Kotlin 中的 sealed 接口是对 sealed 类的补充，可以用于创建更灵活的 [sealed 类层次结构](https://kotlinlang.org/docs/whatsnew1430.html#package-wide-sealed-class-hierarchies)。这样，派生类可以继承多个 sealed 接口：
```

2021-04-30 11:07 UTC, PassionPenguin commented on article/2021/the-road-to-kotlin-1-5.md
> +为了提高构建效率，Kotlin Gradle 插件如今实现了跟 [Gradle configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) 的兼容，这是一个未普遍使用的 Gradle 特性，它的功能是通过缓存配置阶段的结果并在后续构建中重用它来加快构建速度。考虑下面的例子：
```suggestion
为了提高构建效率，Kotlin Gradle 插件如今实现了跟 [Gradle configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) 的兼容 —— 一个未被普遍使用的 Gradle 特性。它的功能是通过缓存配置阶段的结果，并在后续构建中重用它来加快构建速度。参考下面的例子：
```

2021-04-30 11:07 UTC, PassionPenguin commented on article/2021/the-road-to-kotlin-1-5.md
> +再次执行相同的命令，将输出:
```suggestion
再次执行相同的命令，将输出：
```

2021-04-30 11:07 UTC, PassionPenguin commented on article/2021/the-road-to-kotlin-1-5.md
> +注意两次构建分别花费的时间。使用的插件是比 5.4 高的版本，欲了解更多与配置缓存有关的信息，可以访问 [Gradle 官方文档](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:usage)。
```suggestion
注意两次构建分别花费的时间。该插件需要 Gradle 5.4 或更高的版本的支持。欲了解更多与配置缓存有关的信息，可以访问 [Gradle 官方文档](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:usage)。
```

2021-05-04 07:23 UTC, lsvih commented
@samyu2000 我看到还有许多校对意见没有 resolve，您要不再看看？

2021-05-06 13:26 UTC, samyu2000 commented
@lsvih 修改完成

2021-05-06 15:28 UTC, lsvih commented on article/2021/the-road-to-kotlin-1-5.md
> +后端的变化包括：呈现于后端界面的一些 [BUG 修复工具](https://youtrack.jetbrains.com/issues/KT?q=%23fixed-in-jvm-ir%20sort%20by:%20votes&_ga=2.221556248.1626189385.1614553347-1788185777.1610805116)和用于改进性能的新特性。用于构建 Android U
@ samyu2000 这里和校对的意思不一样，需要和校对者确认一下

2021-05-06 15:28 UTC, lsvih commented on article/2021/the-road-to-kotlin-1-5.md
> +> 后端逻辑中有很多功能是共享的，并且有统一的管道，可以实现大多数特性、优化和 BUG 修复工作一次性完成。
@samyu2000 这里和校对者意思有出入，需要确认一下

2021-05-06 15:30 UTC, lsvih commented
@samyu2000 前面有两处您和校对的意见出入较大，需要统一一下意见

2021-05-12 23:52 UTC, samyu2000 commented
@lsvih 修改完成

2021-05-13 01:32 UTC, lsvih approved these changes

2021-05-13 01:32 UTC, merged

2021-05-13 01:32 UTC, lsvih commented
@samyu2000  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-05-13 03:35 UTC, samyu2000 commented
@lsvih 已发布 https://juejin.cn/post/6961610009096486948/