Dagger, Hilt 以及 Koin 的本质区别是什么？
xitu/gold-miner pull request #8569
Opened 2021-05-14 06:29 UTC by keepmovingljzy

译文翻译完成，resolve #8537

2021-05-14 08:21 UTC, Kimhooo commented
校对认领 @lsvih

2021-05-14 08:46 UTC, Kimhooo reviewed
校对完成 @lsvih @keepmovingljzy

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +> - 译者：
```suggestion
> - 译者：[keepmovingljzy](https://github.com/keepmovingljzy)
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +> - 校对者：
```suggestion
> - 校对者：[Kimhooo](https://github.com/Kimhooo)
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +Dagger 和 Koin 无疑是 Android 中最流行的两个依赖注入框架。这两个库具有相同的目的，看起来非常相似，但它们在底层的工作方式却非常不同。
```suggestion
Dagger 和 Koin 无疑是 Android 中最流行的两个依赖注入框架。这两个库具有相同的用途，而且看起来非常相似，但它们在底层的工作方式却非常不同。
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +如果我们希望 Dagger 提供某个类的实例，我们要做的就是在构造函数中添加`@Inject`注解。
```suggestion
如果我们希望 Dagger 提供某个类的实例，我们要做的就是在构造函数中添加 `@Inject` 注解。
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +此类包含创建`CompositeAdapter`类的实例所需的所有信息。
```suggestion
此类包含创建 `CompositeAdapter` 类的实例所需的所有信息。
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +如你所看到该工厂类实现了`get()`并返回了一个新的`CompositeAdapter`实例。这实际上是此类实现的`Provider \ <T>`接口中指定的方法。其他类可以使用`Provider \ <T>`接口来获取一个类的实例。
```suggestion
如你所看到该工厂类实现了 `get()` 并返回了一个新的 `CompositeAdapter` 实例。这实际上是此类实现的 `Provider \ <T>` 接口中指定的方法。其他类可以使用 `Provider \ <T>` 接口来获取一个类的实例。
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +在这个例子中，没有任何区别。Hilt 是一个内部使用 Dagger 的库，我向你展示的类是由 Dagger 生成的。如果您使用 Hilt，它确实为我们生成了一些额外的类，这些类简化了 Dagger 的使用，并减少了我们需要编写的样板代码的数量。但核心部分保持不变。
```suggestion
在这个例子中，没有任何区别。Hilt 是一个内部使用 Dagger 的库，我向你展示的类是由 Dagger 生成的。如果您使用 Hilt，它确实为我们生成了一些额外的类，这些类简化了 Dagger 的使用，并减少了我们需要编写的样板代码的数量。但核心代码保持不变。
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +Koin 将这些工厂的引用添加到`InstancesRegistry`类中，该类包含对我们编写的所有工厂的引用。
```suggestion
Koin 将这些工厂类的引用添加到 `InstancesRegistry` 类中，该类包含对我们编写的所有工厂类的引用。
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +该 map 中的 key 是类的全名或使用命名参数时提供的名称。对应的值是我们编写的工厂，将用于创建类的实例。
```suggestion
该 map 中的 key 是类的全名或使用命名参数时提供的名称。对应的值是我们编写的将用于创建类的实例的工厂类。
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +要获得依赖关系，我们需要调用`get()` (比如在一个工厂类中) 或者通过在 activities 或 fragments 中调用 inject() 委托属性 ，从而懒加载`get()`。`get()`方法将查找为给定类型的类注册工厂，并将其注入其中。
```suggestion
要获得依赖关系，我们需要调用 `get()` (比如在一个工厂类中) 或者通过在 activities 或 fragments 中调用 inject() 委托属性 ，从而懒加载 `get()`。`get()` 方法将查找为给定类型的类注册工厂，并将其注入其中。
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +例如，如果我们忘记向构造函数的`CompositeAdapter`中添加`@Inject`注解，并尝试将其注入 fragment 中，则构建将失败，并显示适当的错误，确切地告诉我们出了什么问题。
```suggestion
例如，如果我们忘记向构造函数的 `CompositeAdapter` 中添加 `@Inject` 注解，并尝试将其注入 fragment 中，则构建将失败，并显示适当的错误，确切地告诉我们出了什么问题。
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +在 Koin 中的情况有所不同，因为它**不会生成任何代码**。如果我们忘记为`CompositeAdapter` 类添加工厂，**应用将会成功构建，但是会抛出`RuntimeException`一旦我们请求获取这个类的实例**。它可能会在应用启动时发生，因此我们可能会立即注意到它，但也可能稍后在其他屏幕上或当用户执行某些特定操作时发生。
```suggestion
在 Koin 中的情况有所不同，因为它**不会生成任何代码**。如果我们忘记为`CompositeAdapter` 类添加工厂，**应用将会成功构建，但是会抛出 `RuntimeException` 一旦我们请求获取这个类的实例**。它可能会在应用启动时发生，因此我们可能会立即注意到它，但也可能稍后在其他屏幕上或当用户执行某些特定操作时发生。
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +从另一方面来说，因为 Koin **在运行时解析依赖项**导致它稍差一些的**运行时性能**。
```suggestion
从另一方面来说，因为 Koin **在运行时解析依赖项**，所以它的**运行时性能**稍差一些。
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +**具体是多少呢？**要估算性能差异我们可以使用[该库](https://github.com/Sloy/android-dependency-injection-performance)，其中 Rafa Vázquez 测量并比较了这两个库位于不同的设备上。测试数据的编写方式可以模拟多个级别的传递依赖关系，因此它不仅仅是具有 4 个类的虚拟应用程序。
```suggestion
**具体是多少呢？**要估算性能差异我们可以使用[该库](https://github.com/Sloy/android-dependency-injection-performance)，其中 Rafa Vázquez 基于不同的设备上测量并比较了这两个库。测试数据的编写方式可以模拟多个级别的传递依赖关系，因此它不仅仅是具有 4 个类的虚拟应用程序。
```

2021-05-14 08:46 UTC, Kimhooo commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +正如我在本文开始时所说的，我这里的目标不是告诉您要使用哪个库。我在两个不同的大项目中使用了 Koin 和 Dagger。老实说，我认为选择 Dagger 还是 Koin 并不重要，**重要的是能够让你编写干净、简单且易于单元测试的代码**。我认为所有的库：Koin，Dagger 和 Hilt 都达到了这个目的。
```suggestion
正如我在本文开始时所说的，我这里的目标不是告诉您要使用哪个库。我在两个不同的大项目中都使用了 Koin 和 Dagger。老实说，我认为选择 Dagger 还是 Koin 并不重要，**重要的是能够让你编写干净、简单且易于单元测试的代码**。我认为所有的库：Koin，Dagger 和 Hilt 都达到了这个目的。
```

2021-05-14 09:04 UTC, keepmovingljzy commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +在这个例子中，没有任何区别。Hilt 是一个内部使用 Dagger 的库，我向你展示的类是由 Dagger 生成的。如果您使用 Hilt，它确实为我们生成了一些额外的类，这些类简化了 Dagger 的使用，并减少了我们需要编写的样板代码的数量。但核心部分保持不变。
两者都行~

2021-05-14 09:11 UTC, keepmovingljzy commented
@Kimhooo 校对辛苦了，已修正，感谢校对~

2021-05-14 09:11 UTC, keepmovingljzy commented
@lsvih

2021-05-14 10:29 UTC, lsvih commented
@Kimhooo 感谢校对

2021-05-22 02:12 UTC, 1autodidact commented
@lsvih 校对认领

2021-05-22 02:32 UTC, lsvih commented
@1autodidact 好的

2021-05-23 14:28 UTC, 1autodidact requested changes
@lsvih @keepmovingljzy 校对完成，翻译的很nice

2021-05-23 14:28 UTC, 1autodidact commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +添加这个注解将导致 Dagger 在构建时为这个类生成一个 Factory。在该用例下，由于它的类名是 `CompositeAdapter`, 它会生成一个名为 `CompositeAdapter**_**Factory`的类。
```suggestion
添加这个注解后，Dagger会在构建时为这个类生成一个工厂。在该用例下，由于它的类名是 `CompositeAdapter`, 它会生成一个名为 `CompositeAdapter**_**Factory`的类。
```

2021-05-23 14:28 UTC, 1autodidact commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +Koin 与 Dagger 以及 Hilt 相比，管理依赖项的方法完全不同。要在 Koin 中注册依赖项，我们不会使用任何注解，因为**Koin不会生成任何代码**。相反，我们必须提供带有工厂类的模块，这些模块将用于创建项目中所需的每个类的实例。
```suggestion
Koin 与 Dagger 以及 Hilt 相比，管理依赖项的方法完全不同。要在 Koin 中注册依赖项，我们不会使用任何注解，因为**Koin不会生成任何代码**。相反，我们必须为模块提供工厂，这些工厂将被用来创建我们项目中需要的每个类的实例。
```

2021-05-23 14:28 UTC, 1autodidact commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +**具体是多少呢？**要估算性能差异我们可以使用[该库](https://github.com/Sloy/android-dependency-injection-performance)，其中 Rafa Vázquez 基于不同的设备上测量并比较了这两个库。测试数据的编写方式可以模拟多个级别的传递依赖关系，因此它不仅仅是具有 4 个类的虚拟应用程序。
```suggestion
相差多少？为了估计性能差异我们可以使用[该库](https://github.com/Sloy/android-dependency-injection-performance)，其中 Rafa Vázquez 基于不同的设备上测量并比较了这两个库。测试数据的编写方式可以模拟多个级别的传递依赖关系，因此它不仅仅是具有 4 个类的虚拟应用程序。
```

2021-05-23 14:31 UTC, lsvih commented
@keepmovingljzy 记得来过一过校对意见哈~

2021-05-24 02:01 UTC, keepmovingljzy commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +添加这个注解将导致 Dagger 在构建时为这个类生成一个 Factory。在该用例下，由于它的类名是 `CompositeAdapter`, 它会生成一个名为 `CompositeAdapter**_**Factory`的类。
Factory 这里就不翻译了，因为后面 CompositeAdapter**_**Factory

2021-05-24 02:06 UTC, keepmovingljzy commented
@1autodidact 校对辛苦了，建议很棒，感谢~

2021-05-24 02:06 UTC, keepmovingljzy commented
@lsvih 翻译完成

2021-05-24 02:07 UTC, lsvih commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +> * 校对者：[Kimhooo](https://github.com/Kimhooo)
完善校对者信息

2021-05-24 02:12 UTC, keepmovingljzy commented on article/2021/how-dagger-hilt-and-koin-differ-under-the-hood.md
> +> * 校对者：[Kimhooo](https://github.com/Kimhooo)
@lsvih 已完善

2021-05-24 02:13 UTC, lsvih approved these changes

2021-05-24 02:13 UTC, merged

2021-05-24 02:14 UTC, lsvih commented
@keepmovingljzy  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-05-24 03:09 UTC, keepmovingljzy commented
@lsvih https://juejin.cn/post/6965687767011426317/

2021-05-24 03:15 UTC, lsvih commented
收到