TypeScript 中的依赖注入
xitu/gold-miner pull request #8652
Opened 2021-05-23 03:32 UTC by Usualminds

译文翻译完成，resolve #8517

2021-05-23 03:33 UTC, Usualminds commented
@lsvih 翻译完成

2021-05-23 08:43 UTC, PassionPenguin requested changes
翻译挺棒哒：）

2021-05-23 08:43 UTC, PassionPenguin commented on article/2021/dependency-injection-in-typescript.md
>  ![Photo by [Anthony DELANOIX](https://unsplash.com/@anthonydelanoix?utm_source=medium&utm_medium=referral) on [Unsplash](https://unsplash.com?utm_source=medium&utm_medium=referral)](https://cdn-image
```suggestion
![图源 [Anthony DELANOIX](https://unsplash.com/@anthonydelanoix?utm_source=medium&utm_medium=referral)，出自 [Unsplash](https://unsplash.com?utm_source=medium&utm_medium=referral)](https://cdn-images-1.medium.com/max/11174/0*EjOezZWFJ92qj8bt)
```

2021-05-23 08:43 UTC, PassionPenguin commented on article/2021/dependency-injection-in-typescript.md
> +每一个软件程序都有其最基础的构建模块。在面向对象的编程语言中， 我们使用类去构建复杂的体系架构。像建一幢大楼，我们把模块之间建立的联系称之为**依赖**。其他的类为了支持我们类的需求，提供复杂的封装操作。
```suggestion
每一个软件程序都有其最基础的构建模块。在面向对象的编程语言中，我们使用类去构建复杂的体系架构。类似于建一幢大楼，我们把模块之间建立的联系称之为**依赖**。其他的类为了支持我们类的需求，提供复杂的封装操作。
```

2021-05-23 08:43 UTC, PassionPenguin commented on article/2021/dependency-injection-in-typescript.md
> +一个类可能有引用其他类的字段。然后，我们不得不问及这些问题：这些引用是怎么被创建的？是**我们**去组合这些对象，还是**其他类**负责实例化它们？如果要实例化的类**太复杂**，并且我们想避免出现垃圾代码？所有这些问题都可以试图通过**依赖注入原则**来解决。
```suggestion
一个类可能有引用其他类的字段。也因此，我们不得不问及这些问题：这些引用是怎么被创建的？是**我们**去组合这些对象，还是**其他类**负责实例化它们？如果要实例化的类**太复杂**，并且我们想避免出现垃圾代码？所有这些问题都可以试图通过**依赖注入原则**来解决。
```

2021-05-23 08:43 UTC, PassionPenguin commented on article/2021/dependency-injection-in-typescript.md
>  * [1] [](https://www.tutorialsteacher.com/ioc/dependency-injection)[https://www.tutorialsteacher.com/ioc/dependency-injection](https://www.tutorialsteacher.com/ioc/dependency-injection)
```suggestion
* [1] [https://www.tutorialsteacher.com/ioc/dependency-injection](https://www.tutorialsteacher.com/ioc/dependency-injection)
```

2021-05-23 08:43 UTC, PassionPenguin commented on article/2021/dependency-injection-in-typescript.md
> +当你查看 `package.json` 文件时，你可以看到两个依赖项配置，让我简要介绍下它们：
```suggestion
当你查看 `package.json` 文件时，你可以看到这些依赖项配置，让我简要介绍下它们：
```

2021-05-23 13:15 UTC, lsvih commented
@PassionPenguin 感谢校对

2021-05-23 14:57 UTC, KimYangOfCat commented
@ 校对认领

2021-05-23 15:03 UTC, lsvih commented
@KimYangOfCat 好的

2021-05-24 09:46 UTC, KimYangOfCat reviewed
@lsvih 校对完毕
@Usualminds 翻译质量不错，赞，不过个别句子阅读起来还是有些生硬，建议加些语气词，提升阅读体验
最后，想要一份转载授权，用以将译文发布于我的个人博客上：https://kimyang.cn/ ，我会留下详细的授权信息以及翻译计划信息，希望得到你的允许～

2021-05-24 09:46 UTC, KimYangOfCat commented on article/2021/dependency-injection-in-typescript.md
> +一个类可能有引用其他类的字段。然后，我们不得不问及这些问题：这些引用是怎么被创建的？是**我们**去组合这些对象，还是**其他类**负责实例化它们？如果要实例化的类**太复杂**，并且我们想避免出现垃圾代码？所有这些问题都可以试图通过**依赖注入原则**来解决。
```suggestion
一个类可能有引用其他类的字段。然后，我们不得不问及这些问题：这些引用是怎么被创建的？是**我们**去组合这些对象，还是**其他类**负责实例化它们？如果要实例化的类**太复杂**，而且我们还想避免出现垃圾代码时，怎么办？所有这些问题都可以试图通过**依赖注入原则**来解决。
```

2021-05-24 09:46 UTC, KimYangOfCat commented on article/2021/dependency-injection-in-typescript.md
> +在开始示例之前，我们必须要去理解关于依赖注入的一些相关概念。依赖注入原则告诉我们，一个类应该去**接收**而非实例化它的依赖。通过委托方式来进行对象初始化，这可以处理较为复杂的操作，从而减少在类设计上的压力。你可以移除代码中复杂的模块，并通过其他方式重新引入依赖。如何处理**移除**和**重新引入依赖**，这是依赖管理的问题。你可以手动处理所有对象的初始化和注入，但是这将会使整个系统变得复杂，我
```suggestion
在开始示例之前，我们必须了解一些关于依赖注入的概念。依赖注入原则告诉我们，一个类应该去**接收**而非实例化它的依赖。通过委托方式来进行对象初始化，这可以处理较为复杂的操作，从而减少在类设计上的压力。你可以移除代码中复杂的模块，并通过其他方式重新引入依赖。如何处理**移除**和**重新引入依赖**，这是依赖管理的问题。你可以手动处理所有对象的初始化和注入，但是这将会使整个系统变得复杂，我们要尽量避免这种情况的发生。相反，你可以将构造的职责转移给 **IoC 容器**。
```

2021-05-24 09:46 UTC, KimYangOfCat commented on article/2021/dependency-injection-in-typescript.md
> +**反转控制**是通过反转整个程序的流程，以便容器对所有程序中涉及的依赖进行管理。你可以创建一个容器，整个容器负责构造对象。当一个类需要实例化对象时，IoC 容器可以提供它所需要的依赖。
```suggestion
**控制反转**是通过反转整个程序的流程，以便容器对所有程序中涉及的依赖进行管理。你可以创建一个容器，整个容器负责构造对象。当一个类需要实例化对象时，IoC 容器可以提供它所需要的依赖。
```
Inversion of Control 的正确翻译是 控制反转

2021-05-24 09:46 UTC, KimYangOfCat commented on article/2021/dependency-injection-in-typescript.md
> +* **Spring** 和 **Dagger**是 **Java** 的依赖注入框架
```suggestion
*  **Java** 有 **Spring** 和 **Dagger** 
```
这样的格式也许阅读体验更好，如果采纳的话，就将下面的都按这个格式来吧

2021-05-24 09:46 UTC, KimYangOfCat commented on article/2021/dependency-injection-in-typescript.md
> +初始化 Yarn 和添加 TypeScript 会花点时间。因为我不想使用没有足够说明信息的出名项目配置来让你感到无趣。所以我将给出初步的代码并做简要介绍。你可以从[这个 Github 仓库](https://github.com/mertturkmenoglu/typescript-dependency-injection)查看和下载代码。
```suggestion
初始化 Yarn 和添加 TypeScript 会花点时间。我不想使用著名但没有足够注释的项目配置，因为这会让你感到无趣。所以我将给出初步的代码并做简要介绍。你可以从[这个 Github 仓库](https://github.com/mertturkmenoglu/typescript-dependency-injection)查看和下载代码。
```

2021-05-24 09:46 UTC, KimYangOfCat commented on article/2021/dependency-injection-in-typescript.md
> +* 我们为 **reflect-metadata** 和 **node** 指定类型。
```suggestion
* 我们为 **reflect-metadata** 和 **node** 指定了类型。
```

2021-05-24 09:46 UTC, KimYangOfCat commented on article/2021/dependency-injection-in-typescript.md
> +* 我们必须将 **mitDecoratorMetadata** 和 **experimentalDecorators** 设置为 true。
```suggestion
* 我们还需将 **mitDecoratorMetadata** 和 **experimentalDecorators** 设置为 true。
```

2021-05-24 09:46 UTC, KimYangOfCat commented on article/2021/dependency-injection-in-typescript.md
> +这段代码是一个只有一个端口的小型 Express 服务器。当你向 **/users** 路由发送一个 **GET** 请求时，它会返回一个用户列表。**main** 函数的核心是 **Container.get** 方法。注意我们并没有使用 new 关键字或者实例化对象。我们只是调用 IoC 容器返回的一个 UserController 实例方法。然后绑定了路由和控制器方法。
```suggestion
这段代码是一个只有一个端口的小型 Express 服务器。当你向 **/users** 路由发送一个 **GET** 请求时，它会返回一个用户列表。**main** 函数的核心是 **Container.get** 方法。注意我们并没有使用 new 关键字或者实例化对象。我们只是调用 IoC 容器返回的一个 UserController 实例方法。然后我们将路由与控制器方法绑定在了一起。
```

2021-05-24 09:46 UTC, KimYangOfCat commented on article/2021/dependency-injection-in-typescript.md
> +UserService 和 UserController 很类似。我们向类添加一个 Service 装饰器，并在构造函数方法中指定它们想要到依赖项。
```suggestion
UserService 和 UserController 很类似。我们向类添加一个 Service 装饰器，并在构造函数方法中指定我们想要的依赖项。
```

2021-05-24 09:46 UTC, KimYangOfCat commented on article/2021/dependency-injection-in-typescript.md
> +UserRepository 是我们的最后一步。我们用 Service 来注解这个类，但是我们没有任何依赖关系。因为没有数据库连接，所以我只是将用户列表作为私有属性硬编码到类中。
```suggestion
UserRepository 是我们的最后一步。我们用 Service 来注解这个类，但是我们没有任何依赖关系。因为没有数据库连接，所以我只是将已硬编码过的用户列表作为私有属性添加到类中。
```

2021-05-24 09:48 UTC, KimYangOfCat reviewed
多谢！

2021-05-24 09:48 UTC, KimYangOfCat commented on article/2021/dependency-injection-in-typescript.md
>  > * 校对者：
```suggestion
> * 校对者：[Kim Yang](https://github.com/KimYangOfCat)
```

2021-05-24 11:44 UTC, Usualminds commented
@lsvih 校对意见已合入

2021-05-24 11:49 UTC, lsvih approved these changes

2021-05-24 11:49 UTC, merged

2021-05-24 11:49 UTC, lsvih commented
@Usualminds  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-05-24 14:09 UTC, Usualminds commented
@lsvih 已发布 https://juejin.cn/post/6965857170646630408/

2021-05-25 15:12 UTC, lsvih commented
收到