Android 静态分析工具
xitu/gold-miner pull request #8672
Opened 2021-05-25 08:17 UTC by Kimhooo

译文翻译完成，resolve #8649

2021-05-25 08:20 UTC, Kimhooo commented
文章的 automate code quality 不知道咋翻译...
还有一个 Anti-Bikeshedding，参考了网上用 Bikeshed 来代表一些无关紧要但会引起大量争论的问题,个人认为翻译成为反繁琐的或者易用的，如果有更好的意见欢迎讨论。
另外在不影响翻译和行数对齐的基础上对原文的一些格式做了调整，方便阅读和校对

2021-05-25 11:06 UTC, PassionPenguin requested changes
啊不说什么了

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +在类声明之后，我们创建定义 **Issue** 所需的所有信息。在这里，我们可以指定类别和严重性，以及在触发规则时将在编辑器 IDE 中显示的解释。
```suggestion
在类声明之后，我们创建定义 `Issue` 所需的所有信息。在这里，我们可以指定类别和严重性，以及在触发规则时将在编辑器 IDE 中显示的解释。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +然后我们需要指定要扫描的属性。我们可以返回一个特定的属性列表，如 **mutableListOf（“textColor”，“background”）** 或返回 **XmlScannerConstants.ALL** 来扫描每个布局上的所有属性。这将取决于您的用例。
```suggestion
然后我们需要指定要扫描的属性。我们可以返回一个特定的属性列表，如 `mutableListOf("textColor"，"background")` 或返回 `XmlScannerConstants.ALL` 来扫描每个布局上的所有属性。这将取决于您的用例。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +4. 创建一个名为 **DefaultIssuereRegistry** 的类，该类扩展了 **IssuereRegistry**。然后需要重写 **issues** 变量并列出所有这些变量。
```suggestion
4. 创建一个名为 `DefaultIssuereRegistry` 的扩展了 `IssuereRegistry` 的类。然后需要重写 `issues` 变量并列出所有这些变量。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +5. 为了检查规则是否正确执行了它们的工作，我们将实施一些测试。我们需要在 **build.gradle** 上有这两个依赖项作为 **testImplementation**:**com.android.tools.lint:lint-tests** 和 **com.android.tools.lint:lint**。这将允许我们在代码中定义一个 XML 文件，并扫描其内容，以查看规则是否正常
```suggestion
5. 为了检查规则是否正确执行了它们的工作，我们将实施一些测试。我们需要在 **build.gradle** 上有这两个依赖项作为 `testImplementation: com.android.tools.lint:lint-tests` 和 `com.android.tools.lint:lint`。这将允许我们在代码中定义一个 XML 文件，并扫描其内容，以查看规则是否正常工作。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +1. 如果使用自定义属性，第一个测试检查规则是否仍然有效。因此 TextView 将包含一个名为 **someCustomColor** 的属性，其颜色为 **#fff**。然后，我们可以添加几个问题来扫描模拟文件，在我们的示例中，我们只指定我们唯一编写的规则。最后我们说，预期结果应该是 1 个严重程度为错误的问题。
```suggestion
1. 如果使用自定义属性，第一个测试检查规则是否仍然有效。因此 TextView 将包含一个名为 `someCustomColor` 的属性，其颜色为 `#fff`。然后，我们可以添加几个问题来扫描模拟文件，在我们的示例中，我们只指定我们唯一编写的规则。最后我们说，预期结果应该是 1 个严重程度为错误的问题。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +3. 在上一个测试中，如果我们使用我们的资源指定颜色，我们检查规则是否没有引发任何错误。在这种情况下，我们使用 **@color/primaryColor** 设置文本颜色，预期的结果是干净利落的执行。
```suggestion
3. 在上一个测试中，如果我们使用我们的资源指定颜色，我们检查规则是否没有引发任何错误。在这种情况下，我们使用 `@color/primaryColor` 设置文本颜色，预期的结果是干净利落的执行。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +就这样！如果我们试图在任何布局中设置硬编码颜色，将提示错误🎉
```suggestion
就这样！如果我们试图在任何布局中设置硬编码颜色，就会立马提示错误 🎉
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +1. 创建自定义规则所在的新模块。我们将此模块称为 **ktlint rules**。
```suggestion
1. 创建自定义规则所在的新模块。我们将此模块称为 `ktlint-rules`。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +3. 编写一个规则，强制在以 **data.dto** 结尾的包名内的所有模型中使用前缀 （**Data**）**。
```suggestion
3. 编写一个规则，强制在以 **data.dto** 结尾的包名内的所有模型中使用前缀（`Data`）。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +首先，我们需要扩展 ktlint 为我们提供的 **Rule** 类，并为您的规则指定一个 id。
```suggestion
首先，我们需要扩展 ktlint 为我们提供的 `Rule` 类，并为您的规则指定一个 id。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +然后我们重写 **visit** 函数。这里我们将设置一些条件来检测包是否以 **data.dto** 结尾，并验证该文件中的类是否具有前缀 **data**。如果类没有这个前缀，那么我们将使用 emit lambda 来触发报告，我们还将提供一种解决问题的方法。
```suggestion
然后我们重写 `visit` 函数。这里我们将设置一些条件来检测包是否以 **data.dto** 结尾，并验证该文件中的类是否具有前缀 **data**。如果类没有这个前缀，那么我们将使用 emit lambda 来触发报告，我们还将提供一种解决问题的方法。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +4. 创建一个名为 **CustomRuleshiyongSetProvider** 的类，该类扩展 **RuleSetProvider**，然后需要重写 **get（）** 函数并在其中列出所有规则。
```suggestion
4. 创建一个名为 `CustomRuleshiyongSetProvider` 的类，该类扩展 `RuleSetProvider`，然后需要重写 `get()` 函数并在其中列出所有规则。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +我们将要实现的规则将强制为仓库实现使用特定的前缀。这只是为了说明我们可以在项目中创建自定义标准。在这种情况下，如果我们有一个 **ProductRepository** 接口，我们希望实现使用前缀 **Default** 而不是后缀 **Impl**。
```suggestion
我们将要实现的规则将强制为仓库实现使用特定的前缀。这只是为了说明我们可以在项目中创建自定义标准。在这种情况下，如果我们有一个 `ProductRepository` 接口，我们希望实现使用前缀 `Default` 而不是后缀 `Impl`。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +1. 创建自定义规则所在的新模块。我们将此模块称为 **detekt rules**。
```suggestion
1. 创建自定义规则所在的新模块。我们将此模块称为 `detekt-rules`。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +3. 编写规则以强制在所有仓库实现中使用前缀 （**Default**）。
```suggestion
3. 编写规则以强制在所有仓库实现中使用前缀（`Default`）。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +首先，我们需要扩展 detekt 为我们提供的 **Rule** 类。我们还需要重写 issue 类成员，并指定名称、问题类型、描述以及解决问题所需的时间。
```suggestion
首先，我们需要扩展 detekt 为我们提供的 `Rule` 类。我们还需要重写 issue 类成员，并指定名称、问题类型、描述以及解决问题所需的时间。
```
```suggestion
首先，我们需要扩展 detekt 为我们提供的 **Rule** 类。我们还需要重写 issue 类成员，并指定名称、问题类型、描述以及解决问题所需的时间。
```

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +然后重写 **visitClassOrObject** 函数。这里我们检查每个类的每个实现。如果其中一些以关键字 **Repository** 结尾，那么我们将验证类名是否以前缀开头。在这种情况下，我们将把问题称为**代码的坏味道**。
```suggestion
然后重写 `visitClassOrObject` 函数。这里我们检查每个类的每个实现。如果其中一些以关键字 **Repository** 结尾，那么我们将验证类名是否以前缀开头。在这种情况下，我们将把问题称为**代码的坏味道**。
```

???代码的坏味道？？？

2021-05-25 11:06 UTC, PassionPenguin commented on article/2021/static-analysis-tools-for-android.md
> +4. 创建一个名为 **CustomRuleSetProvider** 的类，该类扩展 **RuleSetProvider**。然后需要重写 **ruleSetId()** 和**实例（config:config）** 函数，并在其中列出所有规则。
```suggestion
4. 创建一个名为 `CustomRuleSetProvider` 扩展了 `RuleSetProvider` 的类。然后需要重写 `ruleSetId()` 和 `instance(config: config)` 函数，并在其中列出所有规则。
```

2021-05-25 12:31 UTC, PingHGao commented
校对认领 @lsvih

2021-05-26 01:24 UTC, PingHGao approved these changes
主要是讲原文中用强调符号 ** ** 表示的代码片段改为代码格式 ``

2021-05-26 01:24 UTC, PingHGao commented on article/2021/static-analysis-tools-for-android.md
> +在类声明之后，我们创建定义 **Issue** 所需的所有信息。在这里，我们可以指定类别和严重性，以及在触发规则时将在编辑器 IDE 中显示的解释。
```suggestion
在类声明之后，我们创建定义 `Issue` 所需的所有信息。在这里，我们可以指定类别和严重性，以及在触发规则时将在集成开发环境（IDE）中显示的解释。
```

2021-05-26 01:24 UTC, PingHGao commented on article/2021/static-analysis-tools-for-android.md
> +3. 在上一个测试中，如果我们使用我们的资源指定颜色，我们检查规则是否没有引发任何错误。在这种情况下，我们使用 **@color/primaryColor** 设置文本颜色，预期的结果是干净利落的执行。
```suggestion
3. 在上一个测试中，我们检测在使用我们的资源指定颜色时，检查规则是否能够不引发任何错误。在这种情况下，我们使用 `@color/primaryColor` 设置文本颜色，预期的结果是干净利落的执行。
```

2021-05-26 01:24 UTC, PingHGao commented on article/2021/static-analysis-tools-for-android.md
> +就这样！如果我们试图在任何布局中设置硬编码颜色，将提示错误🎉
```suggestion
就这样！如果我们试图在任何布局中设置硬编码颜色，将立即出现错误提示🎉
```

2021-05-26 01:24 UTC, PingHGao commented on article/2021/static-analysis-tools-for-android.md
> +3. 编写一个规则，强制在以 **data.dto** 结尾的包名内的所有模型中使用前缀 （**Data**）**。
```suggestion
3. 编写一个规则，强制在以 **data.dto** 结尾的包名内的所有模型中使用前缀 （**Data**）。
```
Data是一个字符，不应该用代码片方式呈现。

2021-05-26 01:24 UTC, PingHGao commented on article/2021/static-analysis-tools-for-android.md
> +然后我们重写 **visit** 函数。这里我们将设置一些条件来检测包是否以 **data.dto** 结尾，并验证该文件中的类是否具有前缀 **data**。如果类没有这个前缀，那么我们将使用 emit lambda 来触发报告，我们还将提供一种解决问题的方法。
```suggestion
然后我们重写 `visit` 函数。这里我们将设置一些条件来检测包是否以 **data.dto** 结尾，并验证该文件中的类是否具有前缀 **Data**。如果类没有这个前缀，那么我们将使用 emit lambda 来触发报告，我们还将提供一种解决问题的方法。
```

2021-05-26 01:24 UTC, PingHGao commented on article/2021/static-analysis-tools-for-android.md
> +detekt 是 **Kotlin** 编程语言的静态代码分析工具。它对 Kotlin 编译器提供的抽象语法树进行操作。它们的重点是查找代码的坏味道，尽管您也可以将其用作格式化工具。
```suggestion
detekt 是 **Kotlin** 编程语言的静态代码分析工具。它对 Kotlin 编译器提供的抽象语法树进行操作。它们的重点是查找代码异味，尽管您也可以将其用作格式化工具。
```

2021-05-26 01:24 UTC, PingHGao commented on article/2021/static-analysis-tools-for-android.md
> +3. 编写规则以强制在所有仓库实现中使用前缀 （**Default**）。
我觉得前缀就是字符串，不用使用代码片格式。

2021-05-26 01:24 UTC, PingHGao commented on article/2021/static-analysis-tools-for-android.md
> +首先，我们需要扩展 detekt 为我们提供的 **Rule** 类。我们还需要重写 issue 类成员，并指定名称、问题类型、描述以及解决问题所需的时间。
```suggestion
首先，我们需要扩展 detekt 为我们提供的 `Rule` 类。我们还需要重写 `issue` 类成员，并指定名称、问题类型、描述以及解决问题所需的时间。
```

2021-05-26 01:24 UTC, PingHGao commented on article/2021/static-analysis-tools-for-android.md
> +然后重写 **visitClassOrObject** 函数。这里我们检查每个类的每个实现。如果其中一些以关键字 **Repository** 结尾，那么我们将验证类名是否以前缀开头。在这种情况下，我们将把问题称为**代码的坏味道**。
```suggestion
然后重写 `visitClassOrObject` 函数。这里我们检查每个类的每个实现。如果其中一些以关键字 **Repository** 结尾，那么我们将验证类名是否以前缀开头。在这种情况下，我们将把问题称为**代码异味**。
```

2021-05-26 01:36 UTC, Kimhooo commented on article/2021/static-analysis-tools-for-android.md
> +然后重写 **visitClassOrObject** 函数。这里我们检查每个类的每个实现。如果其中一些以关键字 **Repository** 结尾，那么我们将验证类名是否以前缀开头。在这种情况下，我们将把问题称为**代码的坏味道**。
代码的坏味道是一些重构的书籍里经常提到的概念，泛指有问题的代码

2021-05-26 01:57 UTC, Kimhooo commented on article/2021/static-analysis-tools-for-android.md
> +3. 编写一个规则，强制在以 **data.dto** 结尾的包名内的所有模型中使用前缀 （**Data**）**。
个人认为前缀是指包名中的一部分，为表统一还是用代码片表示吧

2021-05-26 01:58 UTC, Kimhooo commented on article/2021/static-analysis-tools-for-android.md
> +然后重写 **visitClassOrObject** 函数。这里我们检查每个类的每个实现。如果其中一些以关键字 **Repository** 结尾，那么我们将验证类名是否以前缀开头。在这种情况下，我们将把问题称为**代码的坏味道**。
一个意思

2021-05-26 02:10 UTC, Kimhooo commented
@PingHGao @PassionPenguin 感谢校对，没有注意代码片格式问题非常抱歉:cry:
@lsvih 已根据校对意见调整

2021-05-26 02:11 UTC, lsvih commented on article/2021/static-analysis-tools-for-android.md
>  > * 校对者：
增加校对者信息

2021-05-28 02:09 UTC, Kimhooo commented on article/2021/static-analysis-tools-for-android.md
>  > * 校对者：
```suggestion
> * 校对者：[PassionPenguin](https://github.com/PassionPenguin)，[PingHGao](https://github.com/PingHGao)
```

2021-05-28 02:10 UTC, Kimhooo commented on article/2021/static-analysis-tools-for-android.md
>  > * 校对者：
@Isvih 已添加，我可以发布到掘金了吗

2021-05-28 05:05 UTC, lsvih approved these changes

2021-05-28 05:05 UTC, merged

2021-05-28 05:05 UTC, lsvih commented
@Kimhooo 已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-05-28 06:19 UTC, Kimhooo commented
@lsvih  已发布至：https://juejin.cn/post/6967219488341098510

2021-05-28 07:06 UTC, lsvih commented
收到~