阶段 3 提案评审
xitu/gold-miner pull request #8674
Opened 2021-05-26 04:48 UTC by Usualminds

译文翻译完成，resolve #8616

2021-05-26 04:49 UTC, Usualminds commented
@lsvih 翻译完成

2021-05-26 05:32 UTC, KimYangOfCat commented
@lsvih 校对认领

2021-05-26 06:15 UTC, KimYangOfCat reviewed
@lsvih 校对完毕
翻译质量很好，赞

2021-05-26 06:15 UTC, KimYangOfCat commented on article/ECMA-TC39/Stage-3-Proposal-Reviews.md
> +作为志愿者，阶段 3 的评审人员在 TC39 会议中讨论提案。如果提案准备就绪，提案的支持者可以在提案进入第二阶段的同一次会议上，要求委员会进行提案审查。规模较大的提案鼓励有多位评审人参与。因为不同的评审人员可以提供不同的视角。
```suggestion
作为志愿者，阶段 3 的评审人员在 TC39 会议中讨论提案。如果提案准备就绪，提案发起人可以在提案进入第二阶段的同一次会议上，要求委员会进行提案审查。规模较大的提案鼓励有多位评审人参与。因为不同的评审人员可以提供不同的视角。
```

2021-05-26 06:15 UTC, KimYangOfCat commented on article/ECMA-TC39/Stage-3-Proposal-Reviews.md
> +评审人员的反馈将会在 GitHub 议题（issue）的提案库中被追踪（[示例](https://github.com/tc39/proposal-regexp-unicode-property-escapes/issues/3)）。在会议开始之前，给评审人员发一封邮件也是有帮助的。
```suggestion
评审人员的反馈将会在提案库的 GitHub 议题（issue）中被追踪（[示例](https://github.com/tc39/proposal-regexp-unicode-property-escapes/issues/3)）。在会议开始之前，给评审人员发一封邮件也是有帮助的。 
```

2021-05-26 06:15 UTC, KimYangOfCat commented on article/ECMA-TC39/Stage-3-Proposal-Reviews.md
> +
```suggestion
```
这里多加了一行导致后面顺序错乱

2021-05-26 06:15 UTC, KimYangOfCat commented on article/ECMA-TC39/Stage-3-Proposal-Reviews.md
> +- 所有的提案细节和周边案例是不是都有合理的动机？
```suggestion
- 所有的提案细节和边界案例是不是都有合理的动机？
```

2021-05-26 06:24 UTC, lsvih commented
@KimYangOfCat 感谢校对

2021-05-26 10:58 UTC, PassionPenguin requested changes

2021-05-26 10:58 UTC, PassionPenguin commented on article/ECMA-TC39/Stage-3-Proposal-Reviews.md
> +向提案支持小组提供你的反馈、GitHub 中的议题文件或者提出修改意见的合并请求。
```suggestion
向提案支持小组提供你的反馈，在 GitHub 中提出议题或者提出修改意见的合并请求。
```

嘛，另外两个都是动宾就这个有些突兀，显然就有些问题啦！

这里的 file 应该指的是**提出**：）

> • submit (a legal document, application, or charge) to be placed on record by the appropriate authority: criminal charges were filed against the firm | [no object] : the company had filed for bankruptcy.

2021-05-26 10:58 UTC, PassionPenguin commented on article/ECMA-TC39/Stage-3-Proposal-Reviews.md
> +- 该提案和其他 JavaScript 语言特性（当前的特性和提案中的特性，即横切关注点）是否匹配？ 这两者之间的交互是否出人意料或者令人感觉陌生？
```suggestion
- 该提案和其他 JavaScript 语言特性（当前的特性和提案中的特性，即横切关注点）是否匹配？这两者之间的交互是否出人意料或者令人感觉陌生？
```

2021-05-26 10:58 UTC, PassionPenguin commented on article/ECMA-TC39/Stage-3-Proposal-Reviews.md
> +
其实没有……

是 GitHub 错位了罢了（

按照 Markdown Syntax，标题前后是需要空行的（

2021-05-26 10:58 UTC, PassionPenguin commented on article/ECMA-TC39/Stage-3-Proposal-Reviews.md
> +根据 [TC39 流程文档](https://tc39.es/process-document)，提案要从阶段 2 过渡到阶段 3，必须要评审人员和编辑小组在规范文档上签字。本文主要介绍阶段 3 的审核过程。
```suggestion
根据 [TC39 流程文档](https://tc39.es/process-document)，提案要从阶段 2 过渡到阶段 3，必须要评审人员和编辑小组同意这一份规范文档的提升。本文主要介绍阶段 3 的审核过程。
```

嗷：

> sign off on
> (sign off on something) US informal give one's approval to something: it was hard to get celebrities to sign off on those issues.

2021-05-26 10:58 UTC, PassionPenguin commented on article/ECMA-TC39/Stage-3-Proposal-Reviews.md
> +作为志愿者，阶段 3 的评审人员在 TC39 会议中讨论提案。如果提案准备就绪，提案的支持者可以在提案进入第二阶段的同一次会议上，要求委员会进行提案审查。规模较大的提案鼓励有多位评审人参与。因为不同的评审人员可以提供不同的视角。
```suggestion
阶段 3 的评审人员需要自愿提供评审，即在 TC39 会议中讨论提案。如果提案准备就绪，提案的支持者可以在提案进入阶段 2 的同一次会议上，要求委员会进行提案审查。规模较大的提案鼓励多位评审人一起参与，因为不同的评审人员可以提供不同的视角下的评审。
```

> as such
> [often with negative] in the exact sense of the word: it is possible to stay overnight here although there is no guest house as such.

另外统一下阶段的表述叭（

2021-05-26 10:58 UTC, PassionPenguin commented on article/ECMA-TC39/Stage-3-Proposal-Reviews.md
> +评审人员的反馈将会在 GitHub 议题（issue）的提案库中被追踪（[示例](https://github.com/tc39/proposal-regexp-unicode-property-escapes/issues/3)）。在会议开始之前，给评审人员发一封邮件也是有帮助的。
```suggestion
评审人员的反馈将会在提案库的 GitHub 议题（issue）中被追踪（[示例](https://github.com/tc39/proposal-regexp-unicode-property-escapes/issues/3)）。在会议开始之前，给评审人员发一封提醒邮件可能也是有帮助的。
```

2021-05-26 11:29 UTC, KimYangOfCat commented on article/ECMA-TC39/Stage-3-Proposal-Reviews.md
> +
那可能我看错了吧

2021-05-27 00:04 UTC, Usualminds commented
@lsvih 校对意见已合入

2021-05-27 01:44 UTC, lsvih approved these changes

2021-05-27 01:44 UTC, merged

2021-05-29 02:37 UTC, Usualminds commented
@lsvih 已发布 https://juejin.cn/post/6967535392484491301/