Jetpack Compose：样式和主题（第二部分）
xitu/gold-miner pull request #8724
Opened 2021-06-03 09:56 UTC by Kimhooo

译文翻译完成，resolve #8707

2021-06-06 02:51 UTC, PingHGao commented
校对认领 @lsvih @Kimhooo

2021-06-06 03:15 UTC, PingHGao submitted a review, later dismissed
校对完成 @Kimhooo @lsvih

2021-06-06 03:15 UTC, PingHGao commented on article/2021/jetpack-compose-styles-and-themes.md
> +正如你在最终成果页面上看到的，我们的应用程序看起来像是启用了暗黑模式。如果这是我们想要的最终外观（或者如果我们想要一个支持黑暗模式的应用程序），那么我们的项目最初是如何由 Android Studio 模板设置的就非常简单了。让我们再探讨一下，理解我们的意思。
```suggestion
正如你在最终成果页面上看到的，我们的应用程序看起来像是启用了暗黑模式。如果这是我们想要的最终外观（或者如果我们想要一个支持黑暗模式的应用程序），那么由 Android Studio 模板对我们的项目进行初始化就非常简单了。让我们再探讨一下，理解我们的意思。
```

2021-06-06 03:15 UTC, PingHGao commented on article/2021/jetpack-compose-styles-and-themes.md
> +正如你在最终成果页面上看到的，我们的应用程序看起来像是启用了暗黑模式。如果这是我们想要的最终外观（或者如果我们想要一个支持黑暗模式的应用程序），那么我们的项目最初是如何由 Android Studio 模板设置的就非常简单了。让我们再探讨一下，理解我们的意思。
```suggestion
正如你在最终成果页面上看到的，我们的应用程序看起来像是启用了暗黑模式。如果这是我们想要的最终外观（或者如果我们想要一个支持黑暗模式的应用程序），那么我们的项目最初是如何由 Android Studio 模板设置的就非常简单了。让我们再探讨一下我们的意思。
```

2021-06-06 03:15 UTC, PingHGao commented on article/2021/jetpack-compose-styles-and-themes.md
> +如果打开项目的目录，你可以看到项目中已经有了 `/ui/theme` 目录，在这个目录中，有几个 Kotlin 类，包括：Color、Shape、theme、Type。
```suggestion
如果打开项目的目录，你可以看到项目中已经有了 `/ui/theme` 目录。在这个目录中，有几个 Kotlin 类，包括：Color、Shape、theme、Type。
```

2021-06-06 03:15 UTC, PingHGao commented on article/2021/jetpack-compose-styles-and-themes.md
> +因此，在这一步，我们删除小狗卡片的硬编码颜色，以便卡显示我们刚刚设置的真正的 `surface` 的颜色。
```suggestion
因此，在这一步，我们删除小狗卡片的硬编码颜色，以便卡片显示我们刚刚设置的真正的 `surface` 的颜色。
```

2021-06-06 03:15 UTC, PingHGao commented on article/2021/jetpack-compose-styles-and-themes.md
> +> 注意：您可能注意到在 themes 目录中有两个`themes.xml` 文件。从现在开始，当你在做更改时，最好同时修改这两个文件中的值，因为这两个文件引用了应用程序的暗黑模式和光亮模式主题。
```suggestion
> 注意：您可能注意到在 themes 目录中有两个`themes.xml` 文件。从现在开始，当你在做更改时，最好同时修改这两个文件中的值，因为这两个文件与应用程序的暗黑模式和光亮模式主题相关。
```

2021-06-06 08:31 UTC, lsvih commented
@PingHGao  感谢校对~

2021-06-06 12:54 UTC, PassionPenguin commented
@lsvih label 错啦

2021-08-11 08:19 UTC, jaredliw commented
@lsvih 发现问题，想认领校对，麻烦通过 #8996 ，谢谢。

2021-08-11 08:24 UTC, lsvih commented
@jaredliw 欢迎校对，您直接在这个 PR 里校对就行啦

2021-08-11 14:40 UTC, jaredliw requested changes

2021-08-11 14:40 UTC, jaredliw commented on article/2021/jetpack-compose-styles-and-themes.md
> +正如你在最终成果页面上看到的，我们的应用程序看起来像是启用了暗黑模式。如果这是我们想要的最终外观（或者如果我们想要一个支持黑暗模式的应用程序），那么我们的项目最初是如何由 Android Studio 模板设置的就非常简单了。让我们再探讨一下，理解我们的意思。
```suggestion
正如你在最终成果页面上看到的，我们的应用程序看起来像是启用了暗黑模式。如果这是我们想要的最终外观（或者如果我们想要一个支持暗黑模式的应用程序），那么我们的项目最初是如何由 Android Studio 模板设置的就非常简单了。让我们再探讨一下我们的意思。
```
统一 dark mode 翻译

2021-08-11 14:40 UTC, jaredliw commented on article/2021/jetpack-compose-styles-and-themes.md
> +正如你在最终成果页面上看到的，我们的应用程序看起来像是启用了暗黑模式。如果这是我们想要的最终外观（或者如果我们想要一个支持黑暗模式的应用程序），那么我们的项目最初是如何由 Android Studio 模板设置的就非常简单了。让我们再探讨一下，理解我们的意思。
```suggestion
正如你在最终成果页面上看到的，我们的应用程序看起来像是启用了暗黑模式。如果这是我们想要的最终外观（或者如果我们想要一个支持暗黑模式的应用程序）。在项目最初时我们使用的 Android Studio 模板设置使得我们的工作变得非常简单。让我们在这个方面进一步的探索一下。
```

2021-08-11 14:40 UTC, jaredliw commented on article/2021/jetpack-compose-styles-and-themes.md
> +因为在我们的情况下，我们需要为应用程序启用暗模式，请执行以下操作：
```suggestion
因为在我们的情况下，我们需要为应用程序启用暗黑模式，请执行以下操作：
```
统一 dark mode 翻译

2021-08-11 14:40 UTC, jaredliw commented on article/2021/jetpack-compose-styles-and-themes.md
> +2. 在 `BarkTheme` composable 中，将 `isSystemInDarkTheme()` 的暗主题默认值设置为 `true`。
```suggestion
2. 在 `BarkTheme` Composable 中，将 `isSystemInDarkTheme()` 的暗主题默认值设置为 `true`。
```
[专有名词使用正确的大小写](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E4%B8%93%E6%9C%89%E5%90%8D%E8%AF%8D%E4%BD%BF%E7%94%A8%E6%AD%A3%E7%A1%AE%E7%9A%84%E5%A4%A7%E5%B0%8F%E5%86%99)，请参考[安卓文档](https://developer.android.com/reference/kotlin/androidx/compose/runtime/Composable)。

2021-08-11 14:40 UTC, jaredliw commented on article/2021/jetpack-compose-styles-and-themes.md
> +> 注：也许您还想知道 `surface` 是什么，它是由材质设计的颜色系统提供的颜色定义，影响组件的表面，如卡片、图纸和菜单：
```suggestion
> 注：也许您还想知道 `surface` 是什么，它是由 Material Design 的颜色系统所提供的颜色定义，影响组件的表面，如卡片、图纸和菜单：
```
Material Design 是 Google 的设计指南名称，不翻译。

2021-08-11 14:40 UTC, jaredliw commented on article/2021/jetpack-compose-styles-and-themes.md
> +2. 在 `PuppyListItem` composable函数中，从卡片 composable 中删除此参数：`backgroundColor value: backgroundColor = Color.White`
```suggestion
2. 在 `PuppyListItem` Composable 函数中，从卡片 composable 中删除此参数：`backgroundColor value: backgroundColor = Color.White`
```
[专有名词使用正确的大小写](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E4%B8%93%E6%9C%89%E5%90%8D%E8%AF%8D%E4%BD%BF%E7%94%A8%E6%AD%A3%E7%A1%AE%E7%9A%84%E5%A4%A7%E5%B0%8F%E5%86%99)、[中英文之间需要增加空格](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E4%B8%AD%E8%8B%B1%E6%96%87%E4%B9%8B%E9%97%B4%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC)

2021-08-11 14:40 UTC, jaredliw commented on article/2021/jetpack-compose-styles-and-themes.md
> +> 注意：您可能注意到在 themes 目录中有两个`themes.xml` 文件。从现在开始，当你在做更改时，最好同时修改这两个文件中的值，因为这两个文件引用了应用程序的暗黑模式和光亮模式主题。
```suggestion
> 注意：您可能注意到在 themes 目录中有两个 `themes.xml` 文件。从现在开始，当你在做更改时，最好同时修改这两个文件中的值，因为这两个文件与应用程序的暗黑模式和光亮模式主题相关。
```
[中英文之间需要增加空格](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E4%B8%AD%E8%8B%B1%E6%96%87%E4%B9%8B%E9%97%B4%E9%9C%80%E8%A6%81%E5%A2%9E%E5%8A%A0%E7%A9%BA%E6%A0%BC)

2021-08-11 14:40 UTC, jaredliw commented on article/2021/jetpack-compose-styles-and-themes.md
> +2. 为 `navigationBarColor` 添加另一项并将其值设置为 `?android:attr/windowBackground` 属性（是随系统首选项自动更改的颜色值）
```suggestion
2. 为 `navigationBarColor` 添加另一项并将其值设置为 `?android:attr/windowBackground` 属性（是随系统首选项自动更改的颜色值）。
```

2021-08-11 14:40 UTC, jaredliw commented on article/2021/jetpack-compose-styles-and-themes.md
> +表扬一下自己，因为你现在已经学会了如何在 Compose 中创建主题和设计风格。 👏
```suggestion
为你自己鼓掌，因为你现在已经学会了如何在 Compose 中创建主题和设计风格。 👏
```

2021-08-11 14:45 UTC, jaredliw commented
@Kimhooo @lsvih 校对完成，#8707 。

@lsvih 麻烦通过一下微信好友（不知道是哪位大佬的微信——`chnyifan`），谢谢啦~

2021-08-12 03:24 UTC, Kimhooo commented
@jaredliw @PingHGao 感谢两位的校对，校对的很认真，很多中英文标点的差异都找出来了:smiley:

@lsvih 校对完成，时隔两个月:open_mouth:

2021-08-12 04:23 UTC, lsvih approved these changes

2021-08-12 04:23 UTC, merged

2021-08-12 04:26 UTC, lsvih commented
@jaredliw 感谢您的校对哈，那位老哥最近特别忙，您可以加一下我微信- -  我微信号是这个 github id 后加一个下划线

2021-08-12 04:26 UTC, lsvih commented
@Kimhooo  下会儿如果还有这种拖了很长时间的情况，您可以直接 at 我来校对 -。-

2021-08-12 05:48 UTC, Kimhooo commented
> @Kimhooo 下会儿如果还有这种拖了很长时间的情况，您可以直接 at 我来校对 -。-

主要是我自己也忘了。。:dash:

2021-08-12 07:59 UTC, Kimhooo commented
@lsvih  文章掘金地址：https://juejin.cn/post/6995419287435345934

2021-08-12 11:03 UTC, lsvih commented
好嘞！