JetPack Compose for Desktop 初体验
xitu/gold-miner pull request #8753
Opened 2021-06-10 09:44 UTC by YueYongDev

译文翻译完成，resolve #8705

2021-06-14 08:36 UTC, PassionPenguin commented
@lsvih @YueYongDev nothing changed..

2021-06-14 08:36 UTC, PassionPenguin requested changes
## These merge commits were added into this branch cleanly.

There are no new changes to show.

2021-06-14 09:16 UTC, PassionPenguin requested changes

2021-06-14 09:16 UTC, PassionPenguin commented on article/2021/an-introduction-to-jetpack-compose-for-desktop.md
>  ![Photo by the author.](https://cdn-images-1.medium.com/max/2738/1*3wOqMMXsvUfkDTWXUri_EQ.png)
```suggestion
![图源作者](https://cdn-images-1.medium.com/max/2738/1*3wOqMMXsvUfkDTWXUri_EQ.png)
```

2021-06-14 09:16 UTC, PassionPenguin commented on article/2021/an-introduction-to-jetpack-compose-for-desktop.md
> +和往常一样，JetBrains 试图通过提供独家项目引导来简化开发者的开发流程。在 Compose for desktop 的早期版本中，他们为 IntelliJ 增加了一个桌面项目引导，可以在几秒内配置好项目。
试图是个贬义词……

```suggestion
和往常一样，JetBrains 在继续尝试通过提供独家项目引导来简化开发者的开发流程。在 Compose for desktop 的早期版本中，他们为 IntelliJ 增加了一个桌面项目引导，可以让我们在几秒内配置好项目。
```

2021-06-14 09:16 UTC, PassionPenguin commented on article/2021/an-introduction-to-jetpack-compose-for-desktop.md
> +在开始开发之前，你需要安装 [IntelliJ IDEA 2020.3](https://www.jetbrains.com/idea/whatsnew/#section=mac)。
```suggestion
在开始开发之前，你需要安装 [IntelliJ IDEA](https://www.jetbrains.com/idea/whatsnew) 2020.3 或更高版本。
```

链接在不断更新，现在发文，链接指向了 2021.1 啦

2021-06-14 09:16 UTC, PassionPenguin commented on article/2021/an-introduction-to-jetpack-compose-for-desktop.md
> +然后点击 "Next "按钮，这将会跳转至确认 Compose 模块的界面。现在点击 "Finish "按钮，IntelliJ 将通过自动下载适当的 gradle 为你配置整个项目。
```suggestion
然后点击 "Next" 按钮，这将会跳转至确认 Compose 模块的界面。现在点击 "Finish" 按钮，IntelliJ 将通过自动下载适当的 gradle 为你配置整个项目。
```

2021-06-14 09:16 UTC, PassionPenguin commented on article/2021/an-introduction-to-jetpack-compose-for-desktop.md
> +运行成功后，你会看到下面的输出结果，有一个包含 "Hello, World!"文字的按钮。如果你点击它，按钮里面的文字就会变成 "Hello, Desktop!“实际操作体验一下吧。
```suggestion
运行成功后，你会看到下面的输出结果，有一个包含 "Hello, World!"文字的按钮。如果你点击它，按钮里面的文字就会变成 "Hello, Desktop!"，快看看下面的效果吧：
```

2021-06-14 09:16 UTC, PassionPenguin commented on article/2021/an-introduction-to-jetpack-compose-for-desktop.md
> +正如你看到的，这是一个简单的 Hello World 程序——一点也不复杂。大部分的代码与 Android 里面的 Jetpack Compose UI 相似。
```suggestion
正如你看到的，这是一个简单的 Hello World 程序 —— 一点也不复杂。大部分的代码与 Android 里面的 Jetpack Compose UI 相似。
```

2021-06-14 09:16 UTC, PassionPenguin commented on article/2021/an-introduction-to-jetpack-compose-for-desktop.md
> +在一个声明式的 UI 系统中，代码本身就描述了 UI。我们需要描述任何时间点上的 UI——不仅仅是初始时间。在诸如按钮、文本字段等 UI 组件中，我们使用`remember`作为文本的状态，这样当我们在未来更新这个 `text` 变量时，与该变量相关的视图也会更新显示文本。
```suggestion
在一个声明式的 UI 系统中，代码本身就描述了 UI。我们需要描述任何时间点上的 UI —— 不仅仅是初始时间。在诸如按钮、文本字段等 UI 组件中，我们使用`remember`作为文本的状态，这样当我们在未来更新这个 `text` 变量时，与该变量相关的视图也会更新显示文本。
```

2021-06-14 09:16 UTC, PassionPenguin commented on article/2021/an-introduction-to-jetpack-compose-for-desktop.md
> +在这种情况下，我们只需要把值传给内容参数，其余的参数保留默认值即可。在接下来的代码中，我们声明了一个具有`remember`功能的`text`变量，其初始值为`Hello, World！`。如下所示：
```suggestion
在这种情况下，我们只需要把值传给内容参数，其余的参数保留默认值即可。在接下来的代码中，我们声明了一个具有 `remember` 功能的 `text` 变量，其初始值为`Hello, World！`。如下所示：
```

2021-06-14 09:42 UTC, YueYongDev commented
@lsvih 按照校对信息更新文章

2021-06-15 01:54 UTC, lsvih commented
@PassionPenguin 感谢校对

2021-07-02 16:35 UTC, YueYongDev commented
@lsvih  还有人校对吗

2021-07-02 18:59 UTC, lsvih commented
@YueYongDev 我明天白天过一遍吧

2021-07-25 06:08 UTC, YueYongDev commented
@lsvih  这一篇已经结束了吗？

2021-07-25 07:34 UTC, lsvih approved these changes

2021-07-25 07:35 UTC, lsvih commented
@YueYongDev 我的错。。漏了。。  我直接在您的 pr 上修改了一些格式上的小问题，您记得同步一下哈

2021-07-25 07:35 UTC, merged

2021-07-25 07:35 UTC, lsvih commented
@YueYongDev  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi