Translate/demystifying java lambda expressions
xitu/gold-miner pull request #8754
Opened 2021-06-11 00:59 UTC by samyu2000

resolve #8713

2021-06-12 13:23 UTC, z127 commented
@lsvih 校对认领

2021-06-21 06:16 UTC, Kimhooo commented
@lsvih 校对认领

2021-06-21 07:20 UTC, lsvih commented
@Kimhooo 好嘞

2021-06-21 13:02 UTC, 1autodidact commented
@lsvih 校对认领

2021-06-21 13:23 UTC, lsvih commented
@1autodidact  好嘞

2021-06-21 13:31 UTC, 1autodidact requested changes
@lsvih  @samyu2000 校对完成

2021-06-21 13:31 UTC, 1autodidact commented on article/2021/demystifying-java-lambda-expressions.md
> +这些 lambda 函数看起来像是我们无中生有捏造的。但在它们的背后，我们是在利用单一函数去实现接口，并提供单一函数的具体实现。
```suggestion
这些 lambda 函数看起来像是我们凭空创建的。但在它们的背后，我们是在利用单一函数去实现接口，并提供单一函数的具体实现。
```

2021-06-21 13:31 UTC, 1autodidact commented on article/2021/demystifying-java-lambda-expressions.md
> +我们来讨论另一个公共函数 `Consumer`。它把某个值作为输入参数，没有返回值，基本上是消费了这个值。如果你已经使用了列表或流对象的 `forEach` 方法，在这里你可以用 `Consumer`。我们会收集所有的宠物的叫声，存入一个列表，再逐个调用。如下所示：
```suggestion
我们来讨论另一个公共函数 `Consumer`。它把某个值作为输入参数，没有返回值，基本上是消费了这个值。如果你曾经使用过列表或流对象的 `forEach` 方法，在这里你已经用了 `Consumer`。我们会收集所有的宠物的叫声，存入一个列表，再逐个调用。如下所示：
```

2021-06-21 13:31 UTC, 1autodidact commented on article/2021/demystifying-java-lambda-expressions.md
> +OK，我展示的例子并不直观。我的目的是从多态函数入手，引入 lambda 表达式的相关内容。何时可以实际使用 lambda 表达式？有一些例子，它们具有通用性，应当反复研究。这些例子也被纳入了 Stream 类库中。
```suggestion
OK，我展示的例子并不直观。我的目的是从多态函数入手，引入 lambda 表达式的相关内容。何时可以实际使用 lambda 表达式？有一些很常见的例子，值得一看。这些例子也被纳入了 Stream 类库中。
```

2021-06-21 13:31 UTC, 1autodidact commented on article/2021/demystifying-java-lambda-expressions.md
> +作为一个例子，它直观了一些，在这个例子中，我会获取一系列的文件，删除那些不以点作为开头的文件，并获取文件名和文件大小。第一步比较繁琐，需要从当前目录获取文件列表对象，并将它转为 `Stream` 类型。我们可以使用 `File` 类实现：
```suggestion
作为一个直观的例子，在这个例子中，我会获取一系列的文件，删除那些不以点作为开头的文件，并获取文件名和文件大小。第一项工作是从当前目录中获取文件数组，并将它转为 `Stream` 类型。我们可以使用 `File` 类实现：
```

2021-06-21 13:31 UTC, 1autodidact commented on article/2021/demystifying-java-lambda-expressions.md
> +我希望本文能向读者揭示 lambda 函数的相关内幕。我想，当第一次引入这个话题，它本身就有些吓人。当然，它是从 Alonzo Church’s lambda calculus 借用过来的，但这又是另一回事了。现在，你应该了解：使用这种简单的语法，函数也可以凭空产生。
```suggestion
我希望本文能向读者揭开 lambda 函数的神秘面纱。我想，当第一次引入这个话题，它本身就有些吓人。当然，它是从 Alonzo Church’s lambda calculus 借用过来的，但这又是另一个故事了。现在，你应该了解：使用这种简单的语法，函数也可以凭空产生。
```

2021-06-22 08:03 UTC, Kimhooo reviewed
@lsvih @samyu2000 校对完成

2021-06-23 08:46 UTC, lsvih approved these changes

2021-06-23 08:46 UTC, merged

2021-06-23 08:46 UTC, lsvih commented
@samyu2000  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-06-25 02:13 UTC, samyu2000 commented
@lsvih 已发布
https://juejin.cn/post/6976973764277846023

2021-06-25 07:46 UTC, lsvih commented
收到~