探索 ANDROID 12：启动画面
xitu/gold-miner pull request #8804
Opened 2021-06-16 08:55 UTC by Kimhooo

译文翻译完成，resolve #8790

2021-06-16 08:57 UTC, Kimhooo commented
关于文章中的“JANKY”，参考了 http://ielts.zhan.com/tifen/18539.html 中的解释

2021-06-21 03:34 UTC, samyu2000 commented
@lsvih 校对认领

2021-06-21 03:55 UTC, lsvih commented
@samyu2000 好的！

2021-06-21 03:59 UTC, samyu2000 commented
@Kimhooo
https://github.com/xitu/gold-miner/pull/8754
帮我校对下好吗？
我已经认领了你的译文的校对。

2021-06-21 06:16 UTC, Kimhooo commented
> @Kimhooo
> #8754
> 帮我校对下好吗？
> 我已经认领了你的译文的校对。

哈哈哈好滴

2021-06-23 06:46 UTC, samyu2000 reviewed
@lsvih @Kimhooo 校对完成
原译文有部分段落明显不符合汉语表达习惯。
建议译者多多检查，即使是通过有道、百度机翻的，也应当多加润色。

2021-06-24 01:33 UTC, Kimhooo commented
@samyu2000 感谢校对，已根据校对意见修改

2021-07-04 17:09 UTC, PassionPenguin requested changes

2021-07-04 17:09 UTC, PassionPenguin commented on article/2021/exploring-android-12-splash-screen.md
> +随着 Android 12 测试版的发布，我们开始了解最新版 Android 提供的新功能。其中，我注意到此版本引入了 Splash Screen API —— 它不仅提供了一种应用程序呈现启动画面的标准化方式，而且还改善了启动应用程序时的用户体验。我正在准备发布 [Compose Academy](https://compose.academy/) 应用程序，同时确保一切功能在 Android
```suggestion
随着 Android 12 测试版的发布，我们现在可以了解最新版 Android 提供的新功能。在这些新功能中，我注意到此版本引入了 Splash Screen API —— 它不仅提供了一种应用程序呈现启动画面的标准化方式，而且还改善了启动应用程序时的用户体验。我正在准备发布 [Compose Academy](https://compose.academy/) 应用程序，同时确保一切功能在 Android 12 API 中正常运行 —— 所以这是了解启动画面相关 API 的绝佳机会。
```

2021-07-04 17:09 UTC, PassionPenguin commented on article/2021/exploring-android-12-splash-screen.md
> +您可能觉得我看过许多很棒的应用程序启动画面！尽管如此，但很多时候，开发人员仍然需要创建自己的启动画面类。这样的启动画面只能用于显示产品的品牌，或处理稍微复杂一些的功能，例如在用户进入应用程序之前执行应用程序初始化和获取数据。还有一些情况需要考虑，应用程序甚至没有设置某种形式的启动画面 —— 用户可能是通过冷启动或热启动方式开启应用程序的，因此用户体验就不太流畅。举个例子，让我们看看如果您不设置某
```suggestion
您可能觉得你已经看过许多很棒的应用程序启动画面！但尽管如此，很多时候，我们仍然需要创建自己的启动画面类。这样的启动画面只能用于显示产品的品牌，或处理稍微复杂一些的功能，例如在用户进入应用程序之前执行应用程序初始化和获取数据。还有一些情况需要考虑，应用程序甚至没有设置某种形式的启动画面 —— 用户可能是通过冷启动或热启动方式开启应用程序的，因此用户体验就不太流畅。举个例子，让我们看看如果您不设置某种启动画面，应用程序启动时候的样子：
```

2021-07-04 17:09 UTC, PassionPenguin commented on article/2021/exploring-android-12-splash-screen.md
> +在 Android API 26 中，我们看到了 **android:windowSplashScreenContent** 属性的引入。这可用于将某些内容设置为启动画面。虽然还是无法满足在这段时间内可能需要处理应用程序初始化的需求，但它提供了更流畅的启动画面显示和进入我们的应用程序的入口。
```suggestion
在 Android API 26 中，我们看到了 **android:windowSplashScreenContent** 属性的引入。这一属性可用于将某些内容设置为启动画面。虽然者还是无法满足在这段时间内可能需要处理应用程序初始化的需求，但无疑它提供了更流畅的启动画面显示和应用程序的入口。
```

2021-07-04 17:09 UTC, PassionPenguin commented on article/2021/exploring-android-12-splash-screen.md
> +虽然在以前的 API 版本中，我们需要提供某种形式的资源作为主题属性以用于我们的窗口内容或启动画面内容，但在 Android 12 中 **不再需要这样做**。因此，了解这一点很重要。**默认情况**下，您的启动器 Activity 将显示这个新的启动画面 —— 因此，如果您当前在应用程序中显示自定义启动画面，则需要适应 Android 12 中的这些更改。
```suggestion
虽然在以前的 API 版本中，我们需要提供某种形式的资源作为主题属性以用于我们的窗口内容或启动画面内容，但在 Android 12 中我们 **不再需要这样做**。因此，了解这一 API 很重要。**默认情况**下，您的启动器 Activity 将显示这个新的启动画面 —— 因此，如果您当前在应用程序中显示自定义启动画面，则需要适应 Android 12 中的这些更改。
```

2021-07-04 17:09 UTC, PassionPenguin commented on article/2021/exploring-android-12-splash-screen.md
> +在了解了启动画面 API 之后，我现在可以确保 [Compose Academy](https://compose.academy/) 应用程序能够正确处理事情。在大多数情况下，您可能不需要作过多修改，开箱即用，就可以令应用程序的启动变得流畅。
```suggestion
在了解了启动画面 API 之后，我现在就完全可以确保 [Compose Academy](https://compose.academy/) 应用程序能够正确工作了。在大多数情况下，您可能不需要作过多修改，开箱即用地就可以令应用程序的启动变得流畅。
```

2021-07-04 17:09 UTC, PassionPenguin commented on article/2021/exploring-android-12-splash-screen.md
> +未来可能会有更多应用程序可以为启动画面自定义——现在拥有这些 API 意味着有一个平台可以向开发人员开放这些东西。然而，创建一个通用的实现是不可能的，我觉得谷歌仍然希望为启动画面强制执行某种标准（而不是让开发人员自由发挥）。无论如何，我很期待看到开发人员会如何应用这些新的 API 😃
```suggestion
未来可能会有更多应用程序可以为启动画面自定义 —— 现在拥有这些 API 意味着有一个平台可以向开发人员开放这些东西。然而，创建一个通用的实现是不可能的，我觉得谷歌仍然希望为启动画面强制执行某种标准（而不是让开发人员自由发挥）。无论如何，我很期待看到开发人员会如何应用这些新的 API 😃
```

2021-07-05 03:02 UTC, lsvih commented
@PassionPenguin  感谢校对

2021-07-12 07:33 UTC, lsvih commented on article/2021/exploring-android-12-splash-screen.md
>  > * 校对者：
添加校对者信息

2021-07-12 07:36 UTC, lsvih approved these changes

2021-07-12 07:37 UTC, merged

2021-07-12 07:37 UTC, lsvih commented
@Kimhooo  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-07-12 07:46 UTC, Kimhooo commented
@lsvih 已发布到掘金： https://juejin.cn/post/6983942336824737822/
感谢校对@samyu2000 @PassionPenguin

2021-07-12 07:58 UTC, lsvih commented
收到