Translation/memory layout in swift
xitu/gold-miner pull request #8853
Opened 2021-06-30 11:15 UTC by LoneyIsError

译文翻译完成，resolve #id

2021-07-01 11:55 UTC, liyaxuanliyaxuan commented
@lsvih 校对认领

2021-07-01 13:33 UTC, lsvih commented
@liyaxuanliyaxuan  欢迎校对！~

2021-07-01 14:05 UTC, liyaxuanliyaxuan commented on article/2021/memory-layout-in-swift.md
> +有一件事很重要，我已经知道了，我想和大家分享。这就是关于各种架构上的[内存访问](https://cs.stackexchange.com/questions/45083/cpu-reading-cycles)。例如，如果 CPU 的总线宽度为 32 位，则意味着 CPU 只能在 1 个读取周期内从内存中读取 32 位字。现在，如果我们简单地将每个对象写入内存，而不进行适当的数据分离，可能会造成
有一件事很重要，我已经知道了，我想和大家分享 => 我想和大家分享一个我已知的关键点

2021-07-01 14:05 UTC, liyaxuanliyaxuan commented
@LoneyIsError @lsvih 校对完成

2021-07-04 17:14 UTC, PassionPenguin requested changes

2021-07-04 17:14 UTC, PassionPenguin commented on article/2021/memory-layout-in-swift.md
> +这里到底发生了什么事？为什么 **size** 会增加呢？ **size** 的增大变得有些棘手，因为如果填充位于存储的变量之间，那么它会增加我们类型的整体大小。你不能从 1 个字节开始，然后在它后面再加上 8 个字节，因为这样会使整数类型不对齐，所以你需要 1 个字节，然后是 7 个字节的填充，最后是 8个字节来存储整数值。
```suggestion
这里到底发生了什么事？为什么 **size** 会增加呢？ **size** 的增大变得有些棘手，因为如果填充位于存储的变量之间，那么它会增加我们类型的整体大小。你不能从 1 个字节开始，然后在它后面再加上 8 个字节，因为这样会使整数类型不对齐，所以你需要 1 个字节，然后是 7 个字节的填充，最后是 8 个字节来存储整数值。
```

2021-07-04 17:14 UTC, PassionPenguin commented on article/2021/memory-layout-in-swift.md
> +Swift 使用[自动引用计数 (ARC) ](https://docs.swift.org/swift-book/LanguageGuide/AutomaticReferenceCounting.html)来跟踪和管理您的应用程序的内存使用情况。多亏了 ARC，在大多数情况下，你不必操心于手动内存管理。你只需确保不会在类实例之间创建强引用循环。幸运的是，这些情况可以通过[弱引用或无主引用](h
```suggestion
Swift 使用[自动引用计数 (ARC)](https://docs.swift.org/swift-book/LanguageGuide/AutomaticReferenceCounting.html) 来跟踪和管理您的应用程序的内存使用情况。多亏了 ARC，在大多数情况下，你不必操心于手动内存管理。你只需确保不会在类实例之间创建强引用循环。幸运的是，这些情况可以通过[弱引用或无主引用](https://docs.swift.org/swift-book/LanguageGuide/AutomaticReferenceCounting.html#ID52)轻松解决。 🔄
```

2021-07-04 17:14 UTC, PassionPenguin commented on article/2021/memory-layout-in-swift.md
> +长话短说，循环引用很糟糕，但在大多数情况下，通过使用正确的关键字就可以避免它们。在幕后，ARC 做得很好，除了一些必须破坏引用循环的情况。Swift 被设计成[内存安全](https://docs.swift.org/swift-book/LanguageGuide/MemorySafety.html)的编程语言。该语言确保每个对象在可以使用它们之前都将被初始化，并且将自动释放不再被引用的内存中
```suggestion
长话短说，循环引用很糟糕，但在大多数情况下，通过使用正确的关键字就可以避免它们。在幕后，ARC 做得很好，除了一些必须破坏引用循环的情况。Swift 被设计成[内存安全](https://docs.swift.org/swift-book/LanguageGuide/MemorySafety.html)的编程语言。该语言确保每个对象在可以使用它们之前都将被初始化，并且将自动释放不再被引用的内存中的对象。 还会检查数组索引是否有越界错误。这为我们提供了额外的安全层，除非是编写不安全的 Swift 代码… 🤓
```

2021-07-04 17:14 UTC, PassionPenguin commented on article/2021/memory-layout-in-swift.md
> +* [Weak、strong、 unowned， 我的天呐！](https://krakendev.io/blog/weak-and-unowned-references-in-swift)
```suggestion
* [Weak、strong、unowned，我的天呐！](https://krakendev.io/blog/weak-and-unowned-references-in-swift)
```

2021-07-07 12:45 UTC, LoneyIsError commented
@liyaxuanliyaxuan @PassionPenguin @lsvih 更改完成，再看看呢

2021-07-08 01:29 UTC, lsvih approved these changes

2021-07-08 01:29 UTC, merged

2021-07-08 01:29 UTC, lsvih commented
@LoneyIsError   已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-07-19 06:32 UTC, LoneyIsError commented
@lsvih https://juejin.cn/post/6986520506002472973

2021-07-19 06:33 UTC, lsvih commented
收到