面向具有 React 开发经验的开发者介绍 Svelte
xitu/gold-miner pull request #8869
Opened 2021-07-02 03:49 UTC by Tong-H

resolve #8848 
打扰了.... 本来误删了分支，之前已经有两位校对者了 @liyaxuanliyaxuan @CarlosChenN

2021-07-02 05:03 UTC, lsvih commented
收到

2021-07-02 05:03 UTC, lsvih commented
@CarlosChenN 劳烦您来这个 PR 里校对哈~

2021-07-04 17:11 UTC, CarlosChenN reviewed
@lsvih 校对完毕

2021-07-04 17:11 UTC, CarlosChenN commented on article/2021/svelte-for-the-experienced-react-dev.md
> +对于 `React.Chidren`，Svelte 与之对应的是 slots，[Svelte 的文档很好的讲解了这个](https://svelte.dev/docs#slot)。我发现它们比 React’s Children API 更简单些。
[我发现它们比 React’s Children API 更简单些]=>[我发现它们去推理 React’s Children API 更简单]
个人建议：reason about翻译成推理更恰当

2021-07-04 17:31 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
>  > * 校对者：
写反了。。。

```suggestion
> * 校对者：[CarlosChenN](https://github.com/CarlosChenN)、[没事儿](https://github.com/Tong-H)、[霜羽 Hoarfroster](https://github.com/PassionPenguin)
```

2021-07-04 17:38 UTC, PassionPenguin requested changes
无力吐槽

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +> * 译者：没事儿[https://github.com/Tong-H]
```suggestion
> * 译者：[没事儿](https://github.com/Tong-H)
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +这篇文章将从富有 React 开发经验的开发者的角度快速的介绍 Sevlte。首先我会做一个概览，然后重点关注state管理和DOM交互能力。我打算把进度加快一点，这样就能覆盖更多的话题。总之，希望能引起你对 Svelte 的兴趣。
```suggestion
这篇文章将从富有 React 开发经验的开发者的角度快速的介绍 Sevlte。首先我会做一个概览，然后重点关注 state 管理和 DOM 交互能力。我打算把进度加快一点，这样就能覆盖更多的话题。总之，希望能引起你对 Svelte 的兴趣。
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +但是我们先谈论......
```suggestion
但是我们先谈论……
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +React 还有`useReducer` hook，让我们可以塑造更复杂的状态。我们提供一个reducer 函数，然后得到我们当前的值，以及一个 dispatch 函数让我们可以用一个给定的参数去调用 reducer，从而触发一个状态更新，不管 reducer 返回的是什么。我们上面的计数器例子可能看起来会是这样：
```suggestion
React 还有 `useReducer` hook，让我们可以塑造更复杂的状态。我们提供一个 reducer 函数，然后得到我们当前的值，以及一个 dispatch 函数让我们可以用一个给定的参数去调用 reducer，从而触发一个状态更新，不管 reducer 返回的是什么。我们上面的计数器例子可能看起来会是这样：
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +Svelte 没有类似的功能，但是它有一个称为**store**的模块。最简单的是 writable store，是持一个值的 object。想要设置一个新值，你可以调用 store 上的 `set` 方法并传递一个新值，或者调用 update，传入一个回调函数，这个函数接受当前值并且返回新值(和 React的 `useState`一样).
```suggestion
Svelte 没有类似的功能，但是它有一个称为 **store** 的模块。最简单的是 writable store，是持一个值的 object。想要设置一个新值，你可以调用 store 上的 `set` 方法并传递一个新值，或者调用 update，传入一个回调函数，这个函数接受当前值并且返回新值(和 React 的 `useState`一样).
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +### 那么`useState`呢?
```suggestion
### 那么`useState` 呢？
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +### 双向绑定**真的**糟糕吗?
```suggestion
### 双向绑定**真的**糟糕吗？
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +上面的例子创建一个带有`val` 属性的组件。在 Svelte中，`export` 关键字用于组件声明 props。通常，我们会把 props 传入到一个组件中，但这里有点不同。比如上面的例子，`val` prop 被子组件修改了。在 React 中，这是错误的，可能会引发 bug，但在 Svelte 中，渲染这个组件的组件可以做这个。
```suggestion
上面的例子创建一个带有 `val` 属性的组件。在 Svelte 中，`export` 关键字用于组件声明 props。通常，我们会把 props 传入到一个组件中，但这里有点不同。比如上面的例子，`val` prop 被子组件修改了。在 React 中，这是错误的，可能会引发 bug，但在 Svelte 中，渲染这个组件的组件可以做这个。
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +以上的一切都很好用，但 action 才是Svelte 的最大亮点。副作用频繁的捆绑 DOM 节点。我们可能想在一个 DOM 节点上集成一个老式的(但仍然很不错) jQuery 插件，然后在节点离开 DOM 的时候拆除它；或者我们想为一个节点设置一个 `ResizeObserver`，然后在节点离开 DOM 的时候分离它，等等。这是非常普通的需求，Svelte 将其内置在 [action](ht
```suggestion
以上的一切都很好用，但 action 才是 Svelte 的最大亮点。副作用频繁的捆绑 DOM 节点。我们可能想在一个 DOM 节点上集成一个老式的(但仍然很不错) jQuery 插件，然后在节点离开 DOM 的时候拆除它；或者我们想为一个节点设置一个 `ResizeObserver`，然后在节点离开 DOM 的时候分离它，等等。这是非常普通的需求，Svelte 将其内置在 [action](https://svelte.dev/docs#use_action) 中。让我们一起去看看。
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +只要`<div>` 进入DOM，就会调用这个 action，并且传递这个 DOM 节点给 action。这是一个时机可以去添加 jQuery 插件以及设置`ResizeObserver`等等。不只这样，我们还可以从中返回一个 cleanup 函数，比如这样：
```suggestion
只要 `<div>` 进入 DOM，就会调用这个 action，并且传递这个 DOM 节点给 action。这是一个时机可以去添加 jQuery 插件以及设置 `ResizeObserver` 等等。不只这样，我们还可以从中返回一个 cleanup 函数，比如这样：
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +来自 React 的开发者可能会惊喜，Svelte 开箱即用的动画。与其在 npm 里搜索然后希望能找到最好的，不如...内置。它甚至包含了[弹性动画，进入离开的动画](https://css-tricks.com/svelte-and-spring-animations/)，Svelte 称之为**transitions**。
```suggestion
来自 React 的开发者可能会惊喜，Svelte 开箱即用的动画。与其在 npm 里搜索然后希望能找到最好的，不如…内置。它甚至包含了[弹性动画，进入离开的动画](https://css-tricks.com/svelte-and-spring-animations/)，Svelte 称之为**transitions**。
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +最后，我最喜欢的功能之一，几乎算是隐藏的功能，通过[`svelte:options`](https://svelte.dev/docs#svelte_options)的属性`tagName`，Svelte 可以将自己的组件编译为真实的 web 组件。但一定要在 webpack 或 Rollup 配置中设置对应的属性。在 webpack 中是这样的：
```suggestion
最后，我最喜欢的功能之一，几乎算是隐藏的功能，通过 [`svelte:options`](https://svelte.dev/docs#svelte_options) 的属性`tagName`，Svelte 可以将自己的组件编译为真实的 web 组件。但一定要在 webpack 或 Rollup 配置中设置对应的属性。在 webpack 中是这样的：
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +这篇文章中的任何一个知识点都可以单独拧出来写一个 blog 了，比如 state 管理和 actions，而我们可能只了解到了一些皮毛，我们看到了 Svelte 的功能，不仅是与 React 相匹配，甚至可以模仿很多 React 的 API。然后之前我们简单的谈到了一些 Svelte 的便利，比如内置动画(或者过渡)以及将 Svelte 组件转化为真实的 web 组件。
```suggestion
这篇文章中的任何一个知识点都可以单独拧出来写一个 blog 了，比如 state 管理和 actions，而我们可能只了解到了一些皮毛，我们看到了 Svelte 的功能，不仅是与 React 相匹配，甚至可以模仿很多 React 的 API。然后之前我们简单的谈到了一些 Svelte 的便利，比如内置动画（或者过渡）以及将 Svelte 组件转化为真实的 web 组件。
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +Svelte 还有很多其他的，React 没有与之相对的功能。还有很多表单捆绑[教程有涵盖](https://svelte.dev/tutorial/text-inputs))，以及 CSS [辅助](https://svelte.dev/docs#class_name)。
```suggestion
Svelte 还有很多其他的，React 没有与之相对的功能。还有很多表单捆绑（[教程有涵盖](https://svelte.dev/tutorial/text-inputs)），以及 CSS [辅助](https://svelte.dev/docs#class_name)。
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +注意这个语法 `use:actionName`。这里我们将`<div>` 与一个称作`myAction`的 action 捆绑，这个 action 只是个函数。
```suggestion
注意这个语法 `use:actionName`。这里我们将 `<div>` 与一个称作 `myAction` 的 action 捆绑，这个 action 只是个函数。
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +在 React 中，我们使用`useEffect` hook 管理副作用。像这样：
```suggestion
在 React 中，我们使用 `useEffect` hook 管理副作用。像这样：
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +如果你真的喜欢 React 的`useState` hook，实现也很简单。实际上，我并没有觉得这是一个很有用的抽象，但这是个有趣的练习，可以展示 Svelte 的灵活性。
```suggestion
如果你真的喜欢 React 的 `useState` hook，实现也很简单。实际上，我并没有觉得这是一个很有用的抽象，但这是个有趣的练习，可以展示 Svelte 的灵活性。
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +Svelte 的用法和 React 几乎是一样的。唯一的区别是我们当前的值是一个 store，而不是一个原始值，所以我们需要加上一个 `$` 前缀来读取值(或者手动调用 store 上的`get` 或`subscribe` )。
```suggestion
Svelte 的用法和 React 几乎是一样的。唯一的区别是我们当前的值是一个 store，而不是一个原始值，所以我们需要加上一个 `$` 前缀来读取值(或者手动调用 store 上的 `get` 或 `subscribe` )。
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> + 另一个需要注意的是，Svelte 不需要 JSX 那样的单独的包裹元素，也没有 React 片段语法`<></>` 的等价物。
```suggestion
 另一个需要注意的是，Svelte 不需要 JSX 那样的单独的包裹元素，也没有 React 片段语法 `<></>` 的等价物。
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +在另一方面，Svelte 会分析你的模板，并且在相关的状态改变时创建目标 DOM 的更新代码。在上面的组件中，Svelte 将会看到 `number`  在哪里改变，然后在变更完成后添加代码去更新`<h1>`的内容，这表示你不需要担心函数或者对象的缓存。事实上，你甚至不需要担心副作用的依赖列表，我们稍后会讨论这个问题。
```suggestion
在另一方面，Svelte 会分析你的模板，并且在相关的状态改变时创建目标 DOM 的更新代码。在上面的组件中，Svelte 将会看到 `number`  在哪里改变，然后在变更完成后添加代码去更新 `<h1>`的内容，这表示你不需要担心函数或者对象的缓存。事实上，你甚至不需要担心副作用的依赖列表，我们稍后会讨论这个问题。
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +还有，Svelte 处理组件的方法和 React 完全不同。只要一个组件的状态或者父组件中的任何地方(除非你使用了 useMemo())发生了改变，React 会重新运行所有的组件。这可能会导致效率低下，这也是为什么 React 会使用`useCallback`和`useMemo`来防止额外的重新计算数据。
```suggestion
还有，Svelte 处理组件的方法和 React 完全不同。只要一个组件的状态或者父组件中的任何地方(除非你使用了 useMemo())发生了改变，React 会重新运行所有的组件。这可能会导致效率低下，这也是为什么 React 会使用 `useCallback` 和 `useMemo` 来防止额外的重新计算数据。
```

2021-07-04 17:38 UTC, PassionPenguin commented on article/2021/svelte-for-the-experienced-react-dev.md
> +接下来是一些 html 标记，类似`{#if}`, `{#each}`等 html 捆绑方法。相较于在 React 中，一切皆 JavaScript 的概念而言，这类特殊领域的语言功能可能看上去像是一个退步。但值得注意的是，Svelte 允许你在这些捆绑中放入任意的 JavaScript 代码。所以类似下面这类代码是完全有效的。
```suggestion
接下来是一些 html 标记，类似 `{#if}`、`{#each}` 等 html 捆绑方法。相较于在 React 中，一切皆 JavaScript 的概念而言，这类特殊领域的语言功能可能看上去像是一个退步。但值得注意的是，Svelte 允许你在这些捆绑中放入任意的 JavaScript 代码。所以类似下面这类代码是完全有效的。
```

2021-07-06 01:58 UTC, Tong-H commented on article/2021/svelte-for-the-experienced-react-dev.md
> +如果你之前是使用 Knockout 或者 Ember，但现在使用并且忠于 React，那么这可能会令你感到惊喜。
我的翻译：“如果你是从 Knockout 或者 Ember 转移到 React，并且从未回头”，另一位校对者的翻译：“ 如果你是从 Knockout 或者 Ember 过渡而来，且忠实于React的开发者”。  “忠实于React ”，这句话我觉得翻译得挺好的，然后我修改了一下意思是一样的

2021-07-06 02:01 UTC, Tong-H commented on article/2021/svelte-for-the-experienced-react-dev.md
> +### Reducer 和 store
我理解的加这个 s 是表示复数

2021-07-06 02:10 UTC, Tong-H commented on article/2021/svelte-for-the-experienced-react-dev.md
> +对于 `React.Chidren`，Svelte 与之对应的是 slots，[Svelte 的文档很好的讲解了这个](https://svelte.dev/docs#slot)。我发现它们比 React’s Children API 更简单些。
“我发现它们去推出 React’s Children API 更简单” ，这句话感觉好像有点奇怪

2021-07-06 02:13 UTC, Tong-H commented on article/2021/svelte-for-the-experienced-react-dev.md
> +### React API 与 Svelte
我理解的这部分章节并没有讲“在 Svelte  中使用 React APIs”，而是两者api的对比

2021-07-06 02:16 UTC, Tong-H commented
@PassionPenguin 空格这个问题是我疏忽了

2021-07-06 02:18 UTC, Tong-H commented on article/2021/svelte-for-the-experienced-react-dev.md
> +还有，Svelte 处理组件的方法和 React 完全不同。只要一个组件的状态或者父组件中的任何地方(除非你使用了 useMemo())发生了改变，React 会重新运行所有的组件。这可能会导致效率低下，这也是为什么 React 会使用`useCallback`和`useMemo`来防止额外的重新计算数据。
好的

2021-07-06 02:19 UTC, Tong-H commented on article/2021/svelte-for-the-experienced-react-dev.md
> +[文档](https://svelte.dev/docs#derived)深入的介绍了这个，但简单来说，`derived` store 让你可以使用和 writable store 一样的语法，让一个 store (或许多 store) 映射出一个新值。
好的

2021-07-06 02:19 UTC, Tong-H commented on article/2021/svelte-for-the-experienced-react-dev.md
> +我们的确是真的喜欢通过定义 reducer 函数来维护和更新 state。让我们看看使用 Svelte 的 store 去实现 React 的 `useReducer` 会有多难。我们想要调用我们自己的 `useReducer`，传入一个带有初始值的 reducer 函数，然后得到带有当前值的 store，这和 dispatch 函数调用 reducer 去更新 store 是一样的。
好的

2021-07-06 02:53 UTC, lsvih approved these changes

2021-07-06 02:55 UTC, merged

2021-07-06 02:55 UTC, lsvih commented
@Tong-H  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-07-06 06:18 UTC, Tong-H commented
> @Tong-H 已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。
> 
> 掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
> 专栏地址：https://zhuanlan.zhihu.com/juejinfanyi
地址：https://juejin.cn/post/6981693237484339207

2021-07-06 07:32 UTC, lsvih commented
收到~