Translate/v8 sparkplug compiler
xitu/gold-miner pull request #8870
Opened 2021-07-03 06:47 UTC by CarlosChenN

译文翻译完成，resolve #8817 @lsvih

2021-07-03 09:08 UTC, Chorer commented
校对认领

2021-07-03 10:07 UTC, Chorer reviewed
校对完毕。里面的 TuboFan、Ignition 以及 Sparkplug 不要去翻译了……一是你可以把这些理解为专有名词，没有翻译的必要；二是本来大家都知道是什么东西，但翻译效果不好的话，反而影响阅读。

2021-07-03 10:07 UTC, Chorer commented on article/2021/v8-sparkplug-compiler.md
> +> 编译时间和点火装置编译器大致相同（因为只是抽象语法树到字节码，不包括解析），大概比涡扇快二到三个量级。相对于解释器的性能，正如器注释指出，失控的变化是由于工作负荷，对于不完全由属性加载器控制来说，大概 4x 可能是个不错的近似值。
```suggestion
> 编译时间和 Ignition 编译器大致相同（因为只是抽象语法树到字节码，不包括解析），大概比 TurboFan 快两到三个量级。正如评论里所指出的，解释器的相对性能会由于工作量的不同而产生很大的差别，在不完全由属性负荷来控制的情况下，大概 4 倍就算是个不错的近似值了。
```

2021-07-03 17:41 UTC, CarlosChenN commented on article/2021/v8-sparkplug-compiler.md
> +> 编译时间和点火装置编译器大致相同（因为只是抽象语法树到字节码，不包括解析），大概比涡扇快二到三个量级。相对于解释器的性能，正如器注释指出，失控的变化是由于工作负荷，对于不完全由属性加载器控制来说，大概 4x 可能是个不错的近似值。
已经改正，感谢校对

2021-07-03 18:57 UTC, KimYangOfCat commented
@lsvih 校对认领

2021-07-04 00:29 UTC, Chorer reviewed
@CarlosChenN 请认真根据校对意见进行修改，不要增加校对者的额外工作。

虽然校对意见已经说得很详细了，但是我看了你的修改，很多明显错误的地方还是没改过来（包括格式错误、语序错误、句子成分残缺以及理解有误等问题）。如果对校对有异议，请及时指出并共同讨论更好的译法，我们是共同协作的关系，不要在没有通知校对者的情况下擅自否决某些校对意见。

2021-07-04 00:29 UTC, Chorer commented on article/2021/v8-sparkplug-compiler.md
> +>  在 Ignition 和 TurboFan 之间有一个巨大的性能差异；长时间驻留在解释器中，意味着我们无法获得优化的好处，而且太早调用 TurboFan 又意味着，我们在优化那些不属于热点代码的函数，甚至更糟，它意味着，我们在做些不必要的事。我们可以用一个简单且快速的非优化的编译器去缩小这个差距，这样可以通过线性遍历字节码并吐出机器码，快速的，低成本地从解释器中分层。我们叫这个编译器为 S
```suggestion
>  在 Ignition 和 TurboFan 之间有一个巨大的性能差异；长时间驻留在解释器中，意味着我们无法获得优化的好处，但是太早调用 TurboFan 又意味着，我们在优化那些不属于热点代码的函数，甚至更糟，它意味着我们在做些不必要的事。我们可以用一个简单且快速的非优化编译器去缩小这个差距，这样可以通过线性遍历字节码并吐出机器码，快速地、低成本地从解释器中分层。我们叫这个编译器为 Sparkplug 。
```
1. 我说明一下，这里“长时间驻留在解释器中”和“过早调用 TurboFan”是两件相反的事情，两件事情多多少少都有一点问题，这里应该用“但是”表示转折，而不是用“而且”表示顺承。
2. 是“快速地”，不是“快速的”

2021-07-04 00:29 UTC, Chorer commented on article/2021/v8-sparkplug-compiler.md
> +在引入 Ignition 和 TurboFan 之前， V8 曾经使用一个快速即时编译器，叫 Full-CodeGen （FCG） 。正如 Leszek [在黑客新闻中解释](https://news.ycombinator.com/item?id=27307862) 到，新的解释器架构 Ignition 抛弃了这种编译器，不再包含 FCG 。
```suggestion
在引入 Ignition 和 TurboFan 之前， V8 曾经使用一个快速即时编译器，叫 Full-CodeGen（FCG）。正如 Leszek [在黑客新闻中解释](https://news.ycombinator.com/item?id=27307862) 到，新的解释器架构 Ignition 抛弃了这种编译器，不再包含 FCG 。
```
不要增加多余的空格。仔细阅读 wiki 的排版规范，这里是不需要加空格的。

2021-07-04 00:29 UTC, Chorer commented on article/2021/v8-sparkplug-compiler.md
> +Leszek [提到](https://news.ycombinator.com/item?id=27312037) FCG 被抛弃而不是改进的原因是它巨大的技术负担，特别是与 Sparkplug 编译器和 FCG 不得不从源码编译，然后把输出提供给 TurboFan 有关，因为这导致了各种各样的复杂情况。这同样也[让他更难跟上 JavaScript 的新特性](https://v8projec
```suggestion
Leszek [提到](https://news.ycombinator.com/item?id=27312037) FCG 被抛弃而不是改进的原因是它巨大的技术负担，特别是与 Sparkplug 编译器和 FCG 不得不从源码编译，然后把输出提供给 TurboFan 有关，因为这导致了各种各样的复杂情况。这同样也[让 FCG 更难跟上 JavaScript 的新特性](https://v8project.blogspot.com/2017/05/launching-ignition-and-turbofan.html) 。
```

2021-07-04 00:29 UTC, Chorer commented on article/2021/v8-sparkplug-compiler.md
> +Swirski 称， Sparkplug 的速度来源于两个因素。首先，它依赖于 TurboFan 生成的字节码，这意味着大量的工作已经完成了，包括变量解析、判断圆括号是否是箭头函数、为解构声明语句进行脱糖等等。此外， Sparkplug 并不生成任何中间产物，而是输出机器码在一个单一的线性通道中。这种方式意味着 Sparkplug 不能做任何基于中间产物的高级优化，它必须全面移植到每个新的平台上
```suggestion
Swirski 称， Sparkplug 的速度来源于两个因素。首先，它依赖于 TurboFan 生成的字节码，这意味着大量的工作已经完成了，包括变量解析、判断圆括号是否是箭头函数、为解构声明语句进行脱糖等等。此外， Sparkplug 并不生成任何中间产物，而是在一个单一的线性通道中输出机器码。这种方式意味着 Sparkplug 不能做任何基于中间产物的高级优化，它必须全面移植到每个新的平台上。
```
“输出机器码在一个单一的线性通道中”，这个语序明显就是不符合中文语言习惯的，请注意修改。

2021-07-04 00:29 UTC, Chorer commented on article/2021/v8-sparkplug-compiler.md
> +在性能方面， Sparkplug 改进了 [Speedometer](https://browserbench.org/Speedometer2.0) 以及V8团队使用的一组现实的基准测试。根据测试机器和网站的不同，性能的提高范围在 5~15% 之间。谷歌尚未发布各种管道组件性能的官方低级基准。不过 Leszek [在这解释过](https://news.ycombinator.com/item
```suggestion
在性能方面， Sparkplug 改进了 [Speedometer](https://browserbench.org/Speedometer2.0) 以及 V8 团队使用的一组现实的基准测试。根据测试机器和网站的不同，性能的提高范围在 5~15% 之间。谷歌尚未发布各种管道组件性能的官方低级基准。不过 Leszek [在这解释过](https://news.ycombinator.com/item?id=27308038) ：
```

2021-07-04 00:29 UTC, Chorer commented on article/2021/v8-sparkplug-compiler.md
> +正如提及到的， Sparkplug 会在 [Chrome 91 中推出](https://developer.chrome.com/blog/new-in-chrome-91/) 所以，你很快就能自己体验一下。如果你对 Sparkplug 内核细节和它如何与 Ignition 和 TurboFan 的联系感兴趣。那么千万不要错过 Swirski 的文章。
```suggestion
正如提及到的， Sparkplug 会在 [Chrome 91 中推出](https://developer.chrome.com/blog/new-in-chrome-91/) 所以，你很快就能自己体验一下。如果你对 Sparkplug 的内核细节，以及它与 Ignition 和 TurboFan 的联系感兴趣。那么千万不要错过 Swirski 的文章。
```
“它如何与 Ignition 和 TurboFan 的联系”，如何与 XXX 的联系，这是什么意思？明显是病句。

2021-07-04 05:16 UTC, CarlosChenN commented on article/2021/v8-sparkplug-compiler.md
> +正如提及到的， Sparkplug 会在 [Chrome 91 中推出](https://developer.chrome.com/blog/new-in-chrome-91/) 所以，你很快就能自己体验一下。如果你对 Sparkplug 内核细节和它如何与 Ignition 和 TurboFan 的联系感兴趣。那么千万不要错过 Swirski 的文章。
我特别感谢，也特别重视您提出的意见，在您的宝贵意见中学到了很多，如果在此过程中出现的疏漏，造成不便，望请谅解，相关建议已经提交修改，后续会更加仔细校对。

2021-07-04 17:11 UTC, PassionPenguin requested changes
挺不错的：）

2021-07-04 17:11 UTC, PassionPenguin commented on article/2021/v8-sparkplug-compiler.md
> +最新版本的 JavaScript V8 引擎， V8 9.1 ，引入一个过渡编译阶段，叫[ Sparkplug ](https://v8.dev/blog/sparkplug) 。据 V8 开发者 [Leszek Swirski](https://twitter.com/leszekswirski) 介绍，它能在现实基准中提升 5~15% 的性能。它会在即将发布的 Chrome 91 中正式使用
```suggestion
最新版本的 JavaScript V8 引擎， V8 9.1 ，引入一个过渡编译阶段，叫 [Sparkplug ](https://v8.dev/blog/sparkplug) 。据 V8 开发者 [Leszek Swirski](https://twitter.com/leszekswirski) 介绍，它能在现实基准中提升 5~15% 的性能。它会在即将发布的 Chrome 91 中正式使用。
```

2021-07-04 17:11 UTC, PassionPenguin commented on article/2021/v8-sparkplug-compiler.md
> +旧的 V8 架构中包括了两个阶段： Ignition （一个 JavaScript 解释器），和 TurboFan （一个高度优化的编译器）， Ignition 使用 JavaScript 抽象语法树去生成 V8 字节码，而 TurboFan 使用这些字节码生成机器码。引入 Sparkplug 的原因，在 [ Sparkplug 设计](https://docs.google.com/docum
```suggestion
旧的 V8 架构中包括了两个阶段： Ignition （一个 JavaScript 解释器），和 TurboFan （一个高度优化的编译器）， Ignition 使用 JavaScript 抽象语法树去生成 V8 字节码，而 TurboFan 使用这些字节码生成机器码。引入 Sparkplug 的原因，在  [Sparkplug 设计](https://docs.google.com/document/d/1NeOsqjPPAcDWbuHxW5MobzVQgj9qZd6NqKUnz0h-fOw/edit) 的概述中有详细的解释。
```

2021-07-04 17:11 UTC, PassionPenguin commented on article/2021/v8-sparkplug-compiler.md
> +>  在 Ignition 和 TurboFan 之间有一个巨大的性能差异；长时间驻留在解释器中，意味着我们无法获得优化的好处，但是太早调用 TurboFan 又意味着，我们在优化那些不属于热点代码的函数，甚至更糟，它意味着我们在做些不必要的事。我们可以用一个简单且快速的非优化编译器去缩小这个差距，这样可以通过线性遍历字节码并吐出机器码，快速地、低成本地从解释器中分层。我们叫这个编译器为 Spa
```suggestion
> 在 Ignition 和 TurboFan 之间有一个巨大的性能差异；长时间驻留在解释器中，意味着我们无法获得优化的好处，但是太早调用 TurboFan 又意味着，我们在优化那些不属于热点代码的函数，甚至更糟，它意味着我们在做些不必要的事。我们可以用一个简单且快速的非优化编译器去缩小这个差距，这样可以通过线性遍历字节码并吐出机器码，快速地、低成本地从解释器中分层。我们叫这个编译器为 Sparkplug 。
```

2021-07-04 17:12 UTC, PassionPenguin requested changes

2021-07-04 17:12 UTC, PassionPenguin commented on article/2021/v8-sparkplug-compiler.md
> +在引入 Ignition 和 TurboFan 之前， V8 曾经使用一个快速即时编译器，叫 Full-CodeGen（FCG）。正如 Leszek [在黑客新闻中解释](https://news.ycombinator.com/item?id=27307862) 到，新的解释器架构 Ignition 抛弃了这种编译器，不再包含 FCG 。
```suggestion
在引入 Ignition 和 TurboFan 之前，V8 曾经使用一个快速即时编译器，叫 Full-CodeGen（FCG）。正如 Leszek [在黑客新闻中解释](https://news.ycombinator.com/item?id=27307862) 到，新的解释器架构 Ignition 抛弃了这种编译器，不再包含 FCG 。
```

2021-07-04 17:12 UTC, PassionPenguin commented on article/2021/v8-sparkplug-compiler.md
> +> 一个大的不同是， Sparkplug 是从字节码中编译的，而不是源码，因此，字节码才是程序的真实来源。回到 FCG 时代，做优化的编译器必须重解释源码成抽象语法树，然后从那里编译，甚至更糟，能反优化退化至 FCG ，它不得不有点像重复 FCG 编译去纠正错选的栈帧。
```suggestion
> 一个大的不同是，Sparkplug 是从字节码中编译的，而不是源码，因此，字节码才是程序的真实来源。回到 FCG 时代，做优化的编译器必须重解释源码成抽象语法树，然后从那里编译，甚至更糟，能反优化退化至 FCG ，它不得不有点像重复 FCG 编译去纠正错选的栈帧。
```

2021-07-04 17:12 UTC, PassionPenguin commented on article/2021/v8-sparkplug-compiler.md
> +Swirski 称， Sparkplug 的速度来源于两个因素。首先，它依赖于 TurboFan 生成的字节码，这意味着大量的工作已经完成了，包括变量解析、判断圆括号是否是箭头函数、为解构声明语句进行脱糖等等。此外， Sparkplug 并不生成任何中间产物，而是在一个单一的线性通道中输出机器码。这种方式意味着 Sparkplug 不能做任何基于中间产物的高级优化，它必须全面移植到每个新的平台上
```suggestion
Swirski 称，Sparkplug 的速度来源于两个因素。首先，它依赖于 TurboFan 生成的字节码，这意味着大量的工作已经完成了，包括变量解析、判断圆括号是否是箭头函数、为解构声明语句进行脱糖等等。此外，Sparkplug 并不生成任何中间产物，而是在一个单一的线性通道中输出机器码。这种方式意味着 Sparkplug 不能做任何基于中间产物的高级优化，它必须全面移植到每个新的平台上。
```

2021-07-04 17:12 UTC, PassionPenguin commented on article/2021/v8-sparkplug-compiler.md
> +在性能方面， Sparkplug 改进了 [Speedometer](https://browserbench.org/Speedometer2.0) 以及 V8 团队使用的一组现实的基准测试。根据测试机器和网站的不同，性能的提高范围在 5~15% 之间。谷歌尚未发布各种管道组件性能的官方低级基准。不过 Leszek [在这解释过](https://news.ycombinator.com/it
```suggestion
在性能方面，Sparkplug 改进了 [Speedometer](https://browserbench.org/Speedometer2.0) 以及 V8 团队使用的一组现实的基准测试。根据测试机器和网站的不同，性能的提高范围在 5~15% 之间。谷歌尚未发布各种管道组件性能的官方低级基准。不过 Leszek [在这解释过](https://news.ycombinator.com/item?id=27308038) ：
```

2021-07-04 17:12 UTC, PassionPenguin commented on article/2021/v8-sparkplug-compiler.md
> +正如提及到的， Sparkplug 会在 [Chrome 91 中推出](https://developer.chrome.com/blog/new-in-chrome-91/) 所以，你很快就能自己体验一下。如果你对 Sparkplug 的内核细节，以及它与 Ignition 和 TurboFan 的联系感兴趣。那么千万不要错过 Swirski 的文章。
```suggestion
正如提及到的，Sparkplug 会在 [Chrome 91 中推出](https://developer.chrome.com/blog/new-in-chrome-91/) 所以，你很快就能自己体验一下。如果你对 Sparkplug 的内核细节，以及它与 Ignition 和 TurboFan 的联系感兴趣。那么千万不要错过 Swirski 的文章。
```

2021-07-05 03:03 UTC, lsvih commented
@Chorer @PassionPenguin 感谢校对

2021-07-05 14:16 UTC, CarlosChenN commented
@PassionPenguin @lsvih 改正完毕

2021-07-06 02:51 UTC, lsvih commented
@CarlosChenN  劳烦您添加一下校对者信息哈~

2021-07-06 04:52 UTC, CarlosChenN commented
@Chorer @PassionPenguin @lsvih 改正完毕

2021-07-06 07:33 UTC, lsvih commented
@CarlosChenN  上一版修改是不是没提交上来呀= =

2021-07-06 14:33 UTC, CarlosChenN commented
@lsvih 提交了呀

2021-07-07 04:10 UTC, lsvih approved these changes

2021-07-07 04:10 UTC, lsvih commented
@CarlosChenN 我直接在您的 branch 上改了点东西，您记得同步一下哈

2021-07-07 04:11 UTC, merged

2021-07-07 04:11 UTC, lsvih commented
@CarlosChenN  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi