TC39 和知识产权
xitu/gold-miner pull request #8880
Opened 2021-07-03 16:35 UTC by finalwhy

译文翻译完成，resolve #8824

@lsvih 翻译完成

2021-07-03 18:56 UTC, KimYangOfCat commented
@lsvih 校对认领

2021-07-04 17:24 UTC, PassionPenguin commented
@finalwhy 麻烦 revert finalwhy/gold-miner [cd9569bd9c229da8e41ef93e54d0372046deddba](https://github.com/xitu/gold-miner/pull/8880/commits/cd9569bd9c229da8e41ef93e54d0372046deddba)

2021-07-04 17:29 UTC, PassionPenguin requested changes
另外，需要按照 [译文排版规则指北#排版](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E6%8E%92%E7%89%88) 脚注部分，修正文章中的 15 处脚注，需要注意，`[]` 需要改为 `\[\]` 以期正常显示

2021-07-04 17:29 UTC, PassionPenguin commented on article/ECMA-TC39/TC39-and-IP.md
> +# TC39 与知识产权（IP）
```suggestion

# TC39 与知识产权（IP）
```

2021-07-04 17:29 UTC, PassionPenguin commented on article/ECMA-TC39/TC39-and-IP.md
> +ECMA-404（JSON） 和 ECMA-415（ECMAScript 套件）也应用了相同的版权政策，这两个标准只会偶尔更新。
```suggestion
ECMA-404（JSON）和 ECMA-415（ECMAScript 套件）也应用了相同的版权政策，这两个标准只会偶尔更新。
```

2021-07-04 17:29 UTC, PassionPenguin commented on article/ECMA-TC39/TC39-and-IP.md
> +[16]: http://www.ecma-international.org/memento/codeofconduct.htm
```suggestion
```

2021-07-04 17:51 UTC, finalwhy commented
> 校对意见：
> 
> @finalwhy 麻烦 revert finalwhy/gold-miner [cd9569bd9c229da8e41ef93e54d0372046deddba](https://github.com/xitu/gold-miner/pull/8880/commits/cd9569bd9c229da8e41ef93e54d0372046deddba)

当时我误将 xitu/gold-miner 的 master 分支合并到该分支了，commit cd9569b 是为了撤销这次合并，这两个提交合并到仓库主分支会有影响吗？

2021-07-05 03:07 UTC, lsvih commented
@finalwhy 这个麻烦您重新开个分支提交一次哈。。您看现在的 Files Changed 改了很多文件

2021-07-05 03:07 UTC, closed without merging

2021-07-05 03:08 UTC, lsvih commented
@KimYangOfCat  @PassionPenguin  这篇文章的校对劳驾二位等作者提交正确分支的 PR 后进行哈~