使用 Husky 和 Hooks 保证 JavaScript 代码质量
xitu/gold-miner pull request #8885
Opened 2021-07-04 05:28 UTC by Usualminds

译文翻译完成，resolve #8717

2021-07-04 13:53 UTC, Usualminds commented
@lsvih 翻译完成

2021-07-04 13:55 UTC, Usualminds commented
@lsvih 翻译完成

2021-07-04 17:22 UTC, PassionPenguin requested changes
：）

2021-07-04 17:22 UTC, PassionPenguin commented on article/2021/ensure-javascript-code-quality-with-husky-and-hooks.md
> +* 由当下Git 的新特性 (`core.hooksPath`) 驱动
```suggestion
* 由当下 Git 的新特性 (`core.hooksPath`) 驱动
```

2021-07-05 03:05 UTC, lsvih commented
@PassionPenguin 这篇您要认领校对吗

2021-07-05 03:26 UTC, finalwhy commented
@lsvih 校对认领

2021-07-05 03:28 UTC, lsvih commented
@finalwhy  欢迎校对

2021-07-06 10:15 UTC, finalwhy reviewed
@Usualminds 校对完毕

2021-07-06 10:15 UTC, finalwhy commented on article/2021/ensure-javascript-code-quality-with-husky-and-hooks.md
> +1. Husky 能够运行任何命令，它可以和其他包进行组合（比如：Prettier、EsLint，检查 linting 是否使用 lint-staged 提交文件等）。
```suggestion
1. Husky 能够运行任何命令，它可以和其他包组合进行工作（例如：与 Prettier 组合进行格式化、与 EsLint 组合为准备提交的代码文件执行静态分析，等）。
```
对内容意译了一下，

2021-07-06 10:15 UTC, finalwhy commented on article/2021/ensure-javascript-code-quality-with-husky-and-hooks.md
> +* 进一步，它支持 Git GUIs、自定义目录和 Monorepos
```suggestion
* 此外，它还支持 Git GUI、自定义目录和 Monorepos
```

2021-07-06 10:15 UTC, finalwhy commented on article/2021/ensure-javascript-code-quality-with-husky-and-hooks.md
> +使用 Husky 和 Git Hooks 可以实现格式化、符合 lint 规则无错误的代码构建。这让执行编码规范变得非常简单和快速。
「…… lint error-free buildable code can be achieved ……」这句的翻译感觉有点问题，但我一时也没想到很合适的表达，建议再斟酌一下

2021-07-07 02:14 UTC, ROXZalwaysWithMe commented on article/2021/ensure-javascript-code-quality-with-husky-and-hooks.md
> +当你使用 Git (`git init` ) 初始化一个项目时，它会自动为你提供一个名为 Hooks 的钩子。你可以在 `[项目根目录]/.git/hooks` 下查看它。
Hooks 在这里应该是能直译成钩子的。

2021-07-10 01:11 UTC, Usualminds commented
@finalwhy @PassionPenguin 感谢两位细心的校对
@lsvih 校对意见已合入

2021-07-10 07:55 UTC, lsvih approved these changes

2021-07-10 07:55 UTC, merged

2021-07-10 07:55 UTC, lsvih commented
@Usualminds  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-07-11 01:00 UTC, Usualminds commented
@lsvih https://juejin.cn/post/6983443137041530887

2021-07-12 04:39 UTC, lsvih commented
收到！

2021-07-12 07:11 UTC, Usualminds commented
@lsvih 掘金翻译的积分兑换目前是 @itcodes 负责吗？想兑换下

2021-07-12 07:21 UTC, lsvih commented
@Usualminds 是的，您直接微信联系他就行~