用于 JavaScript 应用的前 5 大嵌入式数据库
xitu/gold-miner pull request #8923
Opened 2021-07-11 14:24 UTC by Tong-H

用于 JavaScript 应用的前 5 大嵌入式数据库

译文翻译完成，resolve #8852

2021-07-11 14:27 UTC, finalwhy commented
@lsvih 校对认领

2021-07-11 16:24 UTC, PassionPenguin requested changes

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
>  ![Image by [Pexels](https://pixabay.com/users/pexels-2286921/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=1836594) from [Pixabay](https://pixabay.com/?utm_source=li
alt

```suggestion
![图源 [Pexels](https://pixabay.com/users/pexels-2286921/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=1836594)，出自 [Pixabay](https://pixabay.com/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=1836594)](https://cdn-images-1.medium.com/max/3840/1*pbWGFLeMU5gfUc7jSLvoPA.jpeg)
```

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +当 RedShift, BigQuery, 甚至 MySQL 作为一种数据存储的方案用于小型数据需求时太重量型了怎么办？其实还有一类合适的应用。事实上，选项有很多，本文将覆盖适用于小型数据存储需求的前 5 个嵌入式数据库。
```suggestion
当 RedShift、BigQuery 甚至 MySQL 作为一种数据存储的方案用于小型数据需求时太重量型了怎么办？其实还有一类合适的应用。事实上，选项有很多，本文将覆盖适用于小型数据存储需求的前 5 个嵌入式数据库。
```

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +当读到“嵌入式”这个词时，90%的人都会联想到我在谈论 IOT 或者移动设备，但并不是的。
```suggestion
当读到“嵌入式”这个词时，90% 的人都会联想到我在谈论 IOT 或者移动设备，但并不是的。
```

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +LowDB 提供的 API 也很简单少量，也并不没有任何开箱即用的搜索功能。它仅限于将 JSON 文件的数据加载到一个数组变量中，然后让你自己(用户)去找你想要的数据。
```suggestion
LowDB 提供的 API 也很简单少量，也并不没有任何开箱即用的搜索功能。它仅限于将 JSON 文件的数据加载到一个数组变量中，然后让你自己（用户）去找你想要的数据。
```

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
>  db.read()  //Load the content of the file into memory
.

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +高度扩展性以及与 TypeScript 的兼容性，为了数据存储提供了一种类似模式的行为(不允许你添加违背预设置模式的数据)。
brackets

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +它只有三种基础的操作： Put, Get 以及 Delete，少量简洁的 api 这与 LowDB 有点相似。
comma

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +数据库的存储架构是围绕于 Log-structured Merge Tree (LSM)，这表示最优的使用方法是用于大型连续性而非小型随机的书写操作。
brackets

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +有趣的是，LevelDB 被 [Chrome’s IndexedDB](https://blog.openreplay.com/getting-started-with-indexeddb-for-big-data-storage) 作为后端数据库使用，显然 Minecraft Bedrock 版使用它作为某些块和实体数据存储(尽管它们使用的是 Google 实现的[轻微修改后的版本](http
missing link translation

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +我有提到过 IoT，是吗？ [Raima](https://raima.com/) 是最快的数据库管理者之一，对运行于资源受限的 IoT 设备而做了特别优化。
extra space

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +我说的资源受限的环境指的是什么？Raima 运行只需要 RAM 350kb，这样我可以最简化资源使用。
```suggestion
我说的资源受限的环境指的是什么？Raima 运行只需要 350kb 的 RAM，这样我可以最简化资源使用。
```

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +与 LevelDB 不同，它还能通过客户端-服务端的架构多进程访问数据库(相比其他的，它让你能离源代码稍微更远一点)。如果你决定做一个贴近源代码的嵌入式应用，你也可以使用多线程并发访问多个数据库。
brackets

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +Raima 的灵活性使你可以从传统的客户端-服务端模式转到最有效的(当然也是受限的)单个客户端使用单个内存数据库的用例。但这是嵌入式数据库非常有效的用例。
brackets

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +它集成了 JDBC 驱动器，所以不需要额外的依赖。它既能以嵌入式的模式在你的 JAVA 应用中工作，也可以作为一个独立的服务器与多个应用同时互动(与 Raima 做的类似，但是没有那么多的变量)，
brackets

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +* **高度可用模式** 这涉及到拥有重复数据的多个服务器。当然，这个模式并不太符合我们考虑的用例。
```suggestion
* **高度可用模式**。这涉及到拥有重复数据的多个服务器。当然，这个模式并不太符合我们考虑的用例。
```
see english ver

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +* **共享内存访问**。这个非常有趣，因为它并不只将数据存储在内存中(比如前面几个)还允许多个应用使用这个内存(**共享内存**部分)。当然，只有在相同节点内的应用才可以直接使用共享内存，但是，来自外部节点的基于 JDBC/ODBC 的也可以访问相同的数据。将共享内存转变为有外部访问权限的内存数据库。
brackets

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +多个大型公司，比如 Cisco, Alcatel, Nokia, 或者 Siemens 都声称在关键任务操作时使用这个数据库，因为其快如闪电般的数据访问速度。
comma

2021-07-11 16:24 UTC, PassionPenguin commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +> 如果发现译文存在错误或其它需要改进的地方，欢迎到 [掘金翻译计划](https://github.com/xitu/gold-miner) 对译文进行修改并 PR，也可获得相应奖励积分。文章开头的 **本文永久链接** 即为本文在 GitHub 上的 MarkDown 链接。
```suggestion
> 如果发现译文存在错误或其他需要改进的地方，欢迎到 [掘金翻译计划](https://github.com/xitu/gold-miner) 对译文进行修改并 PR，也可获得相应奖励积分。文章开头的 **本文永久链接** 即为本文在 GitHub 上的 MarkDown 链接。
```

2021-07-12 04:41 UTC, lsvih commented
@finalwhy  欢迎校对~

2021-07-13 06:12 UTC, finalwhy reviewed
@Tong-H @lsvih 校对完成

2021-07-13 06:12 UTC, finalwhy commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +如果你在寻找另一个小型的，类似 SQL 的数据库，[Apache Derby](http://db.apache.org/derby/) 非常可能是你要的。
```suggestion
如果你在寻找另一个小型的，类似 SQL 的数据库，[Apache Derby](http://db.apache.org/derby/) 很可能就是你想要的。
```

2021-07-13 06:12 UTC, finalwhy commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +最后一个，但绝对相当重要的一个，solidDB 覆盖一个非常有趣的案例，在提供一个内存关系型数据库的同时也可以提升模型的持续性。口气不小，声称自己可以保持两种数据存储选项的实时同步。
```suggestion
最后一个，但绝对相当重要的一个，solidDB 覆盖一个非常有趣的案例，在提供一个内存关系型数据库的同时也可以提升模型的持续性。口气不小，它声称自己可以保持两种数据存储选项的实时同步。
```

2021-07-13 07:15 UTC, Tong-H commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +LevelDB 主要的一个限制是，一旦存储开放它会锁定系统，这表示一次只有一个进程可以与其交互。当然，你可以在一个进程内部使用多线程同时操作。但这就是它的程度。
这句话修饰前面这句”Of course.....” 挺恰当的，但前面是句号如果看成是修饰这段，或者”但也只受限于此“

2021-07-13 07:32 UTC, Tong-H commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +如果你混合这两种选项，LowDB 开始展现一个有趣的选择，操作本地类似 JSON 的数据。
我感觉不太像 js 的 promise， 但我的也确实不太通顺

2021-07-13 07:46 UTC, Tong-H commented
文章已发布 @lsvih 

https://juejin.cn/post/6984313230214578213

2021-07-13 08:04 UTC, lsvih approved these changes

2021-07-13 08:04 UTC, merged

2021-07-13 08:04 UTC, lsvih commented
@Tong-H 好的

2021-07-13 15:01 UTC, finalwhy commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +如果你混合这两种选项，LowDB 开始展现一个有趣的选择，操作本地类似 JSON 的数据。
我看了下发到掘金的译文，这段也没有重译，那要不先修改成我这个版本吧，我去研究一下 LowDB 的文档后再看看怎末修改恰当

2021-07-14 01:01 UTC, Tong-H commented on article/2021/top-5-embedded-databases-for-javascript-applications.md
> +如果你混合这两种选项，LowDB 开始展现一个有趣的选择，操作本地类似 JSON 的数据。
ok