HTTP严格传输安全协议常见问题解答
xitu/gold-miner pull request #8929
Opened 2021-07-13 14:48 UTC by CarlosChenN

译文翻译完成，resolve #8916

2021-07-13 14:51 UTC, finalwhy commented
@lsvih 校对认领

2021-07-14 01:15 UTC, lsvih commented
@finalwhy  欢迎校对

2021-07-14 07:11 UTC, Chorer commented
校对认领

2021-07-14 08:08 UTC, lsvih commented
@Chorer  好的

2021-07-14 09:33 UTC, PassionPenguin requested changes

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
>  ![Photo by [Alessandro Sacchi](https://unsplash.com/@alle_sacchi) on [Unsplash](https://unsplash.com/photos/NUFnfYd09iI)](https://cdn-images-1.medium.com/max/2000/0*aQF5O9qqSppIwcdn)
```suggestion
![图片由 [Alessandro Sacchi](https://unsplash.com/@alle_sacchi) 上传至 [Unsplash](https://unsplash.com/photos/NUFnfYd09iI)](https://cdn-images-1.medium.com/max/2000/0*aQF5O9qqSppIwcdn)
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +在我学习 HSTS 的时候，我提出了下面的问题，和我对应的解答。
suggest:

```suggestion
本文是在我学习 HSTS 的时候，我提出的一些问题以及对应的回答。
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +它是一个网站返回的响应体，它让浏览器知道，浏览器从现在开始只能尝使用 HTTPS 协议访问网站。
```suggestion
它被包含在一个网站返回的响应的报头中，让浏览器知道从现在开始只能使用 HTTPS 协议去尝试访问这一个网站。
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +在你的浏览器接收 HSTS 报头之后，下一次你访问 [http://facebook.com](http://facebook.com)，你的浏览器不会真的发起这个请求，它会做一个”内部重定向“（ HTTP 307 ） 然后请求 [https://facebook.com](https://facebook.com) 来代替。
```suggestion
在你的浏览器接收 HSTS 报头之后，下一次你访问 [http://facebook.com](http://facebook.com) 时，你的浏览器不会真的发起这个请求，而会做一个”内部重定向“（HTTP 307）然后请求 [https://facebook.com](https://facebook.com) 来代替。
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
>  ![The browser knows to use HTTPS only, and redirects accordingly](https://cdn-images-1.medium.com/max/2000/1*T8VGnhGEkWqmVR6l0cQVdw.png)
alt

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +想象一下你在机场，一个黑客在他们的笔记本电脑，设置好一个公共的 Wi-Fi，然后虚拟一个假版本的 [http://facebook.com](http://facebook.com)。你就会访问 [http://facebook.com](http://facebook.com) ，这时，黑客就知道你的用户名和密码了。
```suggestion
想象一下你在机场，一个黑客在他们的笔记本电脑，设置好一个公共的 Wi-Fi，然后虚拟一个 [http://facebook.com](http://facebook.com) 盗版网站。当你访问 [http://facebook.com](http://facebook.com) 时，黑客就能获得你的用户名和密码了。
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +由于 HSTS，如果你已经访问过 [https://facebook.com](https://facebook.com)，你的浏览器已经接受了 HSTS 报头，并知道从那时开始使用 HTTPS 协议。
```suggestion
由于 HSTS，如果你已经访问过 [https://facebook.com](https://facebook.com)，你的浏览器已经接受了 HSTS 报头，并知道从那时开始访问该网站需要使用 HTTPS 协议。
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +这就是预加载解决的问题。 Google 维护一个域名列表，强制放在 Chrome 及其他浏览器中。当你第一次用 HTTP 访问列表里面的其中一个域名，浏览器帮你重定向到 HTTPS 协议，即使你的浏览器还未接收到 HSTS 报头。
```suggestion
这就是预加载解决的问题。Google 维护了一个域名列表，强制内置于 Chrome 及其他浏览器中。当你第一次用 HTTP 访问列表里面的其中一个域名，浏览器会自动帮你重定向到 HTTPS 协议 —— 即使你的浏览器还未接收到 HSTS 报头。
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +有一些你可以阅读的预加载的[要求](https://hstspreload.org/) 。一个预加载合法的 HSTS 报头例子像这样：
```suggestion
有一些你可以了解的预加载的[要求](https://hstspreload.org/)。一个合法的预加载 HSTS 报头的例子是这样的：
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
>  `Strict-Transport-Security:` max-age=63072000; includeSubDomains; preload
missing code block name `http request`

```suggestion
```http request
`Strict-Transport-Security:` max-age=63072000; includeSubDomains; preload
\`\`\` # 请直接修改此处
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +一个有趣的需要注意的事情是,你只能注册域名, ie. 不能注册子域名.
```suggestion
一个有趣的需要注意的事情是，你只能注册域名。我的意思是，你不能注册子域名。
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +为了保持列表尽可能地的小，保证列表上的每个条目为用户提供最广泛的价值，HSTS 预加载列表的策略是预加载 TLDs （top-level domains） 和注册域名，通常被称为 eTLD + 1（eTLDs是由[公共后缀列表](https://publicsuffix.org/) 确定的，+ 1 意味着符加额外的标签）。
```suggestion
为了保持列表尽可能地的小，保证列表上的每个条目为用户提供最广泛的价值，HSTS 预加载列表的策略是预加载 TLDs（顶级域名）和注册域名，通常被称为 eTLD + 1（eTLDs 是由[公共后缀列表](https://publicsuffix.org/) 确定的，+ 1 意味着添加额外的标签）。
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +如果 Google 让你预加载 [http://website1.com](http://website1.com/) ，那么，所有子域将会内部重定向到 HTTPS 协议，这会导致 [http://sub.website1.com](http://sub.website1.com)，不能再访问，因为用户将会重定向到 [https://sub.website1.com](http://sub.we
```suggestion
如果 Google 让你预加载 [http://website1.com](http://website1.com/)，那么，所有子域将会内部重定向到 HTTPS 协议，这会导致 [http://sub.website1.com](http://sub.website1.com)，不能再访问，因为用户将会重定向到 [https://sub.website1.com](http://sub.website1.com)。
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +回答这个之前，想一想如果你有另一个只用 HTTP 运行的子域名会发生什么 [http://sub.website1.com](http://sub.website1.com) 。
```suggestion
回答这个之前，想一想如果你有另一个只用 HTTP 运行的子域名会发生什么 [http://sub.website1.com](http://sub.website1.com)。
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +Google 先强制你找到这些问题（在开启半永久预加载功能你的网站之前），通过强制你让你的用户重定向到 [https://website1.com](https://website1.com/) ，这样，当 HSTS 报头返回时，浏览器就知道对顶级域名和所有子域名使用 HTTPS。
```suggestion
Google 先强制你找到这些问题（在开启半永久预加载功能你的网站之前），通过强制你让你的用户重定向到 [https://website1.com](https://website1.com/)。这样，当 HSTS 报头返回时，浏览器就知道要对顶级域名和所有子域名使用 HTTPS。
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +它的想法是你会找到 HTTP 子域名的问题，然后修复它们，在配置好预加载之前，因为它[一旦配置好就很难移除](https://bugs.chromium.org/p/chromium/issues/detail?id=527947) 。
```suggestion
它的想法是你会找到 HTTP 子域名的问题，然后修复它们，在配置好预加载之前，因为它[一旦配置好就很难移除](https://bugs.chromium.org/p/chromium/issues/detail?id=527947)。
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +HSTS 是一个很棒的安全特性，不过，你真的需要考虑预加载的含义，以及，以后是否不得不移除它的风险，这很困难，和为了特殊情况，添加额外的安全层值不值得的问题。
bad sentence connection

```suggestion
HSTS 是一个很棒的安全特性，不过，你真的需要考虑预加载的含义，也需要考虑以后是否需要移除它的风险。移除你的域名是很困难的，你需要考虑为了特殊情况添加额外的安全层究竟值不值得。
```

2021-07-14 09:33 UTC, PassionPenguin commented on article/2021/http-strict-transport-security-faqs.md
> +除非你经营一个知名度很高的网站，不然，你的其中一个用户第一次用公共 Wi-Fi去访问你网站，并且刚好有个黑客提供该 Wi-Fi 的几率，非常小。
```suggestion
除非你经营一个知名度很高的网站，不然，你的其中一个用户第一次用公共 Wi-Fi 去访问你网站，并且刚好这个 Wi-Fi 被一个黑客所运行的几率实在是太小了。
```

2021-07-14 14:42 UTC, zenblofe commented on article/2021/http-strict-transport-security-faqs.md
>  > * 校对者：
```suggestion
> * 校对者：[Z招锦](https://github.com/zenblofe)
```

2021-07-14 14:42 UTC, zenblofe commented on article/2021/http-strict-transport-security-faqs.md
> +## HSTS有什么作用呢？
```suggestion
## HSTS 的作用是什么呢？
```

2021-07-14 14:42 UTC, zenblofe commented on article/2021/http-strict-transport-security-faqs.md
> +HSTS 预加载列表以二进制的形式发送到全球数十亿客户的浏览器中，因此，需要高度重视控制这个列表的大小。
```suggestion
HSTS 预加载列表是以二进制形式发送到全球数十亿客户的浏览器中，因此，需要高度重视限制 HSTS 预加载列表的大小。
```

2021-07-14 14:42 UTC, zenblofe commented on article/2021/http-strict-transport-security-faqs.md
> +预加载子域名仍然允许其他子域名（或注册域名本身）在未来被预加载，它应该通过预加载可注册域名与 `includeSubDomains` 授予 HTTPS 强制执行其下面的域名进行处理。
```suggestion
预加载子域名仍然允许其他子域名（或注册域名本身）在未来被预加载，它应该通过预加载可注册域名，以及 `includeSubDomains` 授予 HTTPS 强制执行其下面的域名等进行处理。
```

2021-07-15 00:55 UTC, Chorer reviewed
校对完毕

2021-07-15 16:50 UTC, CarlosChenN commented
@Chorer @PassionPenguin @zenblo @lsvih

2021-07-16 01:41 UTC, lsvih approved these changes

2021-07-16 01:41 UTC, merged

2021-07-16 01:41 UTC, lsvih commented
@CarlosChenN  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-07-21 17:30 UTC, CarlosChenN commented
@lsvih 
https://juejin.cn/post/6987432172512608287/

2021-07-22 01:52 UTC, lsvih commented
收到