缓存踩踏事件是如何导致 Facebook 最大的宕机事件之一发生的
xitu/gold-miner pull request #8931
Opened 2021-07-13 17:05 UTC by PassionPenguin

resolve #7938

2021-07-15 01:39 UTC, kamly commented
@lsvih 认领校对

2021-07-15 01:43 UTC, lsvih commented
@kamly  欢迎校对

2021-07-17 06:52 UTC, kamly reviewed
@PassionPenguin 已校对完成，麻烦看看

lock 翻译 锁
断路器 翻译 熔断器

感觉会更合适

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +不知道你是否使用过 [spinlock](https://en.wikipedia.org/wiki/Spinlock) 模式并让线程不断轮询 Lock？这将创建一个[忙等待 Busy Waiting](https://en.wikipedia.org/wiki/Busy_waiting) 场景。
```suggestion
不知道你是否使用过 [自旋锁](https://en.wikipedia.org/wiki/Spinlock) 模式并让线程不断轮询锁？这将创建一个[忙等待](https://en.wikipedia.org/wiki/Busy_waiting) 场景。
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +在检查 Lock 是否空闲之前，你是否让线程休眠了任意时间？假设现在你手头上有 [惊群问题](https://en.wikipedia.org/wiki/Thundering_herd_problem)。
```suggestion
在检查锁是否空闲之前，你是否让线程休眠了任意时间？这样你就会遇到 [惊群效应问题](https://en.wikipedia.org/wiki/Thundering_herd_problem)。
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +你是否引入了 [backoff and jitter](https://www.baeldung.com/resilience4j-backoff-jitter) 以防止惊群问题？这可能有效，但还有一个更普遍的问题。拥有 Lock 的线程必须在释放 Lock 之前重新计算值并更新缓存键。
```suggestion
你是否引入了 [退避和抖动机制](https://www.baeldung.com/resilience4j-backoff-jitter) 以防止惊群效应问题？这可能有效，但还有一个更普遍的问题。拥有锁的线程必须在释放锁之前重新计算值并更新缓存键。
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +这个过程可能需要一段时间。特别是如果该值的计算成本很高或存在网络问题。如果缓存耗尽其可用连接池并且用户请求被丢弃，这仍然可能导致中断本身。
```suggestion
这个过程可能需要一段时间。特别是如果该值的计算成本很高或存在网络问题。如果缓存耗尽其可用连接池并且用户请求被丢弃，这仍然可能导致宕机。
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +#### Promise 如何防止自旋 Lock
```suggestion
#### Promise 如何防止自旋锁
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +引用 **[惊群问题与 Promise](https://instagram-engineering.com/thundering-herds-promises-82191c8af57d)** 来自 Instagram 的工程博客：
```suggestion
引用 **[惊群效应问题与 Promise](https://instagram-engineering.com/thundering-herds-promises-82191c8af57d)** 来自 Instagram 的工程博客：
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +幸运的是，一些顶级工程组织正在使用一种更简单的解决方案：**Promise**。
```suggestion
幸运的是，一些顶级公司正在使用一种更简单的解决方案：**Promise**。
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +通过缓存 Promise 而不是实际值，不需要自旋 Lock。获取缓存未命中的第一个线程将使用原子操作（例如 Java 的 [`computeIfAbsent`](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#computeIfAbsent-K-java.util.function.Function-)）。所有顺序获取请
```suggestion
通过缓存 Promise 而不是实际值，不需要自旋锁。获取缓存未命中的第一个线程将使用原子操作（例如 Java 的 [`computeIfAbsent`](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#computeIfAbsent-K-java.util.function.Function-)）。所有顺序获取请求将立即返回 Promise 。
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +我们仍然需要使用 Lock 来防止多个线程访问缓存键。但是假设创建一个 Promise 是一个近乎即时的操作，线程在自旋 Lock 中停留的时间长度可以忽略不计。
```suggestion
我们仍然需要使用锁来防止多个线程访问缓存键。但是假设创建一个 Promise 是一个近乎即时的操作，线程在自旋锁中停留的时间长度可以忽略不计。
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +早期重新计算的最简单实现是后台进程或 cron 作业。例如，假设有一个缓存键，其生存时间 (TTL) 在一小时内到期，计算该值需要两分钟。cron 作业可以在一个小时结束前运行五分钟，并在更新后将 TTL 再延长一个小时。
```suggestion
早期重新计算的最简单实现是后台进程或定时任务。例如，假设有一个缓存键，其过期时间在一小时内到期，计算该值需要两分钟。定时任务可以在一个小时结束前运行五分钟，并在更新后将过期时间再延长一个小时。
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +由于这些原因，我无法在生产环境中找到任何此类早期重新计算的示例。但是有一种**是**使用的。
```suggestion
由于这些原因，我无法在生产环境中找到任何此类早期重新计算的示例。但是也有例外。
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +然而，早期重新计算假设有重新计算的价值 —— 它不会单独阻止粉丝踩踏。为此，我们需要将它与 Lock 和 Promise 结合起来。
```suggestion
然而，早期重新计算假设有重新计算的价值 —— 它不会单独阻止追随者踩踏。为此，我们需要将它与锁和 Promise 结合起来。
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +#### 断路
```suggestion
#### 熔断器
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +在编程中使用断路器的想法并不新鲜。在 Michael Nygard 于 2007 年发表 [**Release It!**](https://www.amazon.com/gp/product/0978739213) 后，它开始流行。正如 Martin Fowler 在他的文章 **[CircuitBreaker](https://www.martinfowler.com/bliki/Circu
```suggestion
在编程中使用熔断器的想法并不新鲜。在 Michael Nygard 于 2007 年发表 [**Release It!**](https://www.amazon.com/gp/product/0978739213) 后，它开始流行。正如 Martin Fowler 在他的文章 **[CircuitBreaker](https://www.martinfowler.com/bliki/CircuitBreaker.html)** 所写的那样：
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +> 断路器背后的基本思想非常简单。您将受保护的函数调用包装在断路器对象中，该对象监视故障。一旦故障达到某个阈值，断路器就会跳闸，并且所有对断路器的进一步调用都会返回错误，而根本不会进行受保护的调用。
```suggestion
> 熔断器背后的基本思想非常简单。您将受保护的函数调用包装在熔断器对象中，该对象监视故障。一旦故障达到某个阈值，熔断器就会熔断，并且所有对熔断器的进一步调用都会返回错误，而不会调用到受到熔断器保护的地方。
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +断路器是被动的，这意味着它们不会阻止宕机，但它们将防止级联故障。当事情失控时，它提供了一个终止开关。如果 Facebook 使用断路器，他们本可以避免让整个网站脱机。
```suggestion
熔断器是被动的，这意味着它们不会阻止宕机，但它们将防止级联故障。当事情失控时，它提供了一个终止开关。如果 Facebook 使用熔断器，他们本可以避免让整个网站脱机。
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +诚然，断路器在 2010 年并不那么流行。如今，有几个带有断路器的库，例如 [Resilience4j](https://resilience4j.readme.io/)、[Istio](https://istio.io/) 和 [Envoy](https://www.envoyproxy.io/)。一些组织在生产中使用这些服务，例如 [Netflix](https://netflixtechb
```suggestion
诚然，熔断器在 2010 年并不那么流行。如今，有几个带有熔断器的库，例如 [Resilience4j](https://resilience4j.readme.io/)、[Istio](https://istio.io/) 和 [Envoy](https://www.envoyproxy.io/)。一些组织在生产中使用这些服务，例如 [Netflix](https://netflixtechblog.com/making-the-netflix-api-more-resilient-a8ec62159c2d) 和 [Lyft](https://www.getambassador.io /resources/mechanics-deploying-envoy-lyft-matt-klein/）。
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +他们从停电中吸取了哪些教训，他们采取了哪些保护措施来防止再次发生这种情况？
```suggestion
他们从故障中吸取了哪些教训，他们采取了哪些保护措施来防止再次发生这种情况？
```

2021-07-17 06:52 UTC, kamly commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +但是，当我们发现自己正在与惊群问题作斗争，那么了解缓存踩踏事件并了解可能的解决方案将使我们在未来受益。
```suggestion
但是，当我们发现自己正在与惊群效应问题作斗争，那么了解缓存踩踏事件并了解可能的解决方案将使我们在未来受益。
```

2021-07-19 02:19 UTC, JalanJiang commented
校对认领

2021-07-19 02:22 UTC, lsvih commented
@JalanJiang  欢迎校对

2021-07-19 06:44 UTC, PassionPenguin commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
>  > * 校对者：
```suggestion
> * 校对者：[kamly](https://github.com/kamly)
```

2021-07-19 06:46 UTC, PassionPenguin commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +## Lock 和 Promise
Promise 或许是 JavaScript 的那个朋友？

2021-07-26 10:33 UTC, JalanJiang requested changes
几个问题：

1. 译者部分句子机翻痕迹太重
2. 译者使用链接前后加空格的书写风格的话需要通篇对齐，我有找出一些链接前后未加空格的写法，请译者自己也检查一遍
3. 这篇文章已经有人翻译过了：https://www.infoq.cn/article/bb2yc0yhvsz4qvwdgzmo。希望管理员加强审核

谢谢！

2021-07-26 10:33 UTC, JalanJiang commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +他们的工程帖子，[**幕后：向数百万人广播直播视频**](https://engineering.fb.com/2015/12/03/ios/under-the-hood-broadcasting-live-video-to-millions/)，讨论他们对架构所做的改进。它讨论了我们已经讨论过的内容，例如缓存层次结构，但也包括一些新颖的方法，例如 HTTP 请求合并。这篇文章值得一读，但如果你
```suggestion
他们的工程帖子，[**幕后：向数百万人广播直播视频**](https://engineering.fb.com/2015/12/03/ios/under-the-hood-broadcasting-live-video-to-millions/)，讨论他们对架构所做的改进。它讨论了我们已经讨论过的内容，例如缓存层次结构，但也包括一些新颖的方法，例如 HTTP 请求合并。这篇文章值得一读，但如果你时间不够，这个 [视频提供了一个全面的概述](https://www.facebook.com/Engineering/videos/10153675295382200/?t=0)。
```

2021-07-26 10:33 UTC, JalanJiang commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +2015 年，一组研究人员发表了名为 「Optimal Probabilistic Cache Stampede Prevention」 的[白皮书](https://cseweb.ucsd.edu/~avattani/papers/cache_stampede.pdf)。在其中，他们描述了一种算法，用于优化预测何时在缓存过期之前重新计算缓存值。
```suggestion
2015 年，一组研究人员发表了名为 「Optimal Probabilistic Cache Stampede Prevention」 的 [白皮书](https://cseweb.ucsd.edu/~avattani/papers/cache_stampede.pdf)。在其中，他们描述了一种算法，用于优化预测何时在缓存过期之前重新计算缓存值。
```

2021-07-26 23:59 UTC, PassionPenguin commented
> 几个问题：
> 
> 1. 译者部分句子机翻痕迹太重
> 2. 译者使用链接前后加空格的书写风格的话需要通篇对齐，我有找出一些链接前后未加空格的写法，请译者自己也检查一遍
> 3. 这篇文章已经有人翻译过了，希望管理员加强审核。https://www.infoq.cn/article/bb2yc0yhvsz4qvwdgzmo
> 
> 谢谢！

infoq的文章倒是会有社区专门译

2021-07-27 08:53 UTC, PassionPenguin commented on article/2021/how-a-cache-stampede-caused-one-of-facebooks-biggest-outages.md
> +> * 校对者：[kamly](https://github.com/kamly)
```suggestion
> * 校对者：[kamly](https://github.com/kamly)、[JalanJiang](https://github.com/JalanJiang)
```

2021-07-28 01:52 UTC, lsvih approved these changes

2021-07-28 01:53 UTC, merged

2021-07-28 01:53 UTC, lsvih commented
@PassionPenguin  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi