translate/ffmpeg-webassembly.md
xitu/gold-miner pull request #8950
Opened 2021-07-20 13:10 UTC by finalwhy

译文翻译完成，resolve #8898

2021-07-20 13:10 UTC, finalwhy commented
@lsvih 翻译完成

2021-07-20 15:05 UTC, CarlosChenN commented
@lsvih 校对申请

2021-07-20 17:23 UTC, PassionPenguin requested changes
校对认领

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
> +Emscripten 是 WebAssembly 的一套编译工具链。我们会使用 [Docker](https://www.docker.com/) 和 [emscripten](https://emscripten.org/) 将 FFmpeg 的 `libav` 库和我们自定义的包装器编译为 Wasm。 让我们先从 FFmpeg 开始。
```suggestion
Emscripten 是 WebAssembly 的一套编译工具链。我们会使用 [Docker](https://www.docker.com/) 和 [emscripten](https://emscripten.org/) 将 FFmpeg 的 `libav` 库和我们自定义的包装器编译为 Wasm。让我们先从 FFmpeg 开始。
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
> +但 FFmpeg 不仅仅†是一个命令行工具。它是由被称为 libav 的一些 FFmpeg 库提供支持。这些库赋予了 FFmpeg 读取、写入和处理多媒体文件的能力。这些库为混流、编/解码、过滤、缩放、色域转换以及底层接口提供功能支持。如果你使用 C/C++ 开发应用，你可以直接调用这些库。很多常见的语言也集成了 libav 库。
```suggestion
但 FFmpeg 不仅仅只是一个命令行工具。它是由被称为 libav 的一些 FFmpeg 库提供支持。这些库赋予了 FFmpeg 读取、写入和处理多媒体文件的能力。这些库为混流、编/解码、过滤、缩放、色域转换以及底层接口提供功能支持。如果你使用 C/C++ 开发应用，你可以直接调用这些库。很多常见的语言也集成了 libav 库。
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
> +WebAssembly（或者叫 Wasm）近年来逐渐流行起来，原因是它能够让我们在浏览器中运行二进制指令。通过一套编译工具链，我们可以将 C/C++ 代码 构建为 Wasm。
```suggestion
WebAssembly（或者叫 Wasm）近年来逐渐流行起来，原因是它能够让我们在浏览器中运行二进制指令。通过一套编译工具链，我们可以将 C/C++ 代码构建为 Wasm。
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
> +这项工作目前已经有人实现了。你可以看一看 [ffmpeg.wasm](https://github.com/ffmpegwasm/ffmpeg.wasm) ，这个文件能够让你在浏览器环境中运行 FFmpeg CLI 工具。
```suggestion
这项工作目前已经有人实现了。你可以看一看 [ffmpeg.wasm](https://github.com/ffmpegwasm/ffmpeg.wasm)：这个文件能够让你在浏览器环境中运行 FFmpeg CLI 工具。
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
> +但是，本文的关注点是如何一步步将 FFmpeg 的 `libav` 库编译为 Webassembly 并在浏览器中使用，而非 FFmpeg CLI。
```suggestion
但是，本文的关注点是如何一步步将 FFmpeg 的 `libav` 库编译为 WebAssembly 并在浏览器中使用，而非 FFmpeg CLI。
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
> +让我们来编译并运行这个程序：
```suggestion
让我们来编译并运行这个程序：

```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
> +**构建时需要使用 `gcc`, `ffmpeg` 和 `ffmpeg-dev`**
```suggestion
**构建时需要使用 `gcc`、`ffmpeg` 和 `ffmpeg-dev`。**
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
> +_`gcc`, `ffmpeg` and `ffmpeg-dev` are required to build._
```suggestion
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
> +// 从 E Emscripten 构建工具生成的代码中引入 Wasm 装载器
```suggestion
// 从 Emscripten 构建工具生成的代码中引入 Wasm 装载器
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
> +  // 监听从 worker 中返回的消息，并渲染到 Dom
```suggestion
  // 监听从 worker 中返回的消息，并渲染到 DOM
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
> +在浏览器载入 `index.html` 之前，我们的 Wasm 模块会使用 [PTHREADS](https://emscripten.org/docs/porting/pthreads.html)，但在一些浏览器中会导致一个安全问题。在 Emscripten 文档中：
```suggestion
在浏览器载入 `index.html` 之前，我们的 Wasm 模块会使用 [PTHREADS](https://emscripten.org/docs/porting/pthreads.html)，但在一些浏览器中会导致一个安全问题。在 Emscripten 文档中有这样一段话：
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
> +  // CORS headers.
```suggestion
  // CORS 标头
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
>  [![Alt Text](https://res.cloudinary.com/practicaldev/image/fetch/s--7Ux4Erxc--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/nx1lp38jqe13
```suggestion
[![](https://res.cloudinary.com/practicaldev/image/fetch/s--7Ux4Erxc--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/nx1lp38jqe13cdu7a5k1.png)](https://res.cloudinary.com/practicaldev/image/fetch/s--7Ux4Erxc--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/nx1lp38jqe13cdu7a5k1.png)
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
> +**并且这就是你在浏览器中运行 FFmpeg 的 `libav` 库的结果!** ⚡
```suggestion
**这就是你在浏览器中运行 FFmpeg 的 `libav` 库的结果!** ⚡
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
>  `mp4info-wrapper.cpp`:
```suggestion
`mp4info-wrapper.cpp`：
```

2021-07-20 17:23 UTC, PassionPenguin commented on article/2021/ffmpeg-webassembly.md
>  }
L235、L242、L248没翻译

2021-07-21 01:35 UTC, finalwhy commented on article/2021/ffmpeg-webassembly.md
> +这项工作目前已经有人实现了。你可以看一看 [ffmpeg.wasm](https://github.com/ffmpegwasm/ffmpeg.wasm) ，这个文件能够让你在浏览器环境中运行 FFmpeg CLI 工具。
冒号也差点，想了想最好还是破折号

2021-07-21 01:45 UTC, finalwhy commented
@PassionPenguin 校对意见已合入

2021-07-21 01:47 UTC, lsvih commented
@CarlosChenN 欢迎校对

2021-07-21 07:54 UTC, Chorer commented
校对认领

2021-07-21 08:09 UTC, Chorer reviewed
校对完毕

2021-07-21 08:09 UTC, Chorer commented on article/2021/ffmpeg-webassembly.md
> +现在我们可以将 FFmpeg 的库文件构建为 Wasm 了，我们需要创建一个集成了 emsscripten 功能的包装器，这样方便我们在浏览器中通过 JavaScript 引入和使用。
```suggestion
现在我们可以将 FFmpeg 的库文件构建为 Wasm 了，我们需要创建一个集成了 emsscripten 功能的包装器，以方便在浏览器中通过 JavaScript 引入和使用。
```

2021-07-21 08:09 UTC, Chorer commented on article/2021/ffmpeg-webassembly.md
> +我们会使用 C++ 编写我们的自定义包装器，并利用 [Embind](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html)。
```suggestion
我们会使用 C++ 编写自定义包装器，并利用 [Embind](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html)。
```

2021-07-21 08:09 UTC, Chorer commented on article/2021/ffmpeg-webassembly.md
> +接下来我们将 `index.html`, `worker.js` 和 Wasm 相关的文件放到一个新目录 `www` 中：
```suggestion
接下来我们将 `index.html`、`worker.js` 和 Wasm 相关的文件放到一个新目录 `www` 中：
```

2021-07-21 08:09 UTC, Chorer commented on article/2021/ffmpeg-webassembly.md
> +> 浏览器会在跨源开放者政策（Cross Origin Resource Policy，COOP） 和 跨源嵌入程序政策（Cross Origin Embedder Policy，COEP）请求头通过验证后才会响应 SharedArrayBuffer。除非正确设置这些标头，否则 Pthreads 代码将无法在部署环境中工作。
```suggestion
> 浏览器会在跨源开放者策略（Cross Origin Opener Policy，COOP）和跨源嵌入程序策略（Cross Origin Embedder Policy，COEP）请求头通过验证后才会响应 SharedArrayBuffer。除非正确设置这些标头，否则 Pthreads 代码将无法在部署环境中工作。
```

2021-07-21 08:09 UTC, Chorer commented on article/2021/ffmpeg-webassembly.md
> +因此当服务器为我们的网页提供响应事需要提供正确的请求头：
```suggestion
因此当服务器为我们的网页提供响应时，需要提供正确的请求头：
```

2021-07-21 08:25 UTC, finalwhy commented on article/2021/ffmpeg-webassembly.md
> +现在我们可以将 FFmpeg 的库文件构建为 Wasm 了，我们需要创建一个集成了 emsscripten 功能的包装器，这样方便我们在浏览器中通过 JavaScript 引入和使用。
```suggestion
现在我们可以将 FFmpeg 的库文件构建为 Wasm 了，我们需要创建一个集成了 emscripten 功能的包装器，以方便我们在浏览器中通过 JavaScript 引入和使用。
```

2021-07-21 08:30 UTC, finalwhy commented
@Chorer 校对意见已合入

2021-07-21 08:30 UTC, finalwhy commented
@lsvih 翻译完成

2021-07-21 08:46 UTC, lsvih commented
@finalwhy 劳烦您添加一下译者信息和校对者信息哈~

2021-07-21 08:57 UTC, finalwhy commented
@lsvih 译者信息和校对者信息添加完毕

2021-07-21 11:18 UTC, lsvih approved these changes

2021-07-21 11:18 UTC, merged

2021-07-21 11:19 UTC, lsvih commented
@finalwhy   已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-07-21 11:27 UTC, finalwhy commented
@lsvih 已发布，文章地址：[FFmpeg + WebAssembly](https://juejin.cn/post/6987338848023871524/)

2021-07-21 11:33 UTC, lsvih commented
收到