JavaScript 实现图形数据结构
xitu/gold-miner pull request #8957
Opened 2021-07-22 15:34 UTC by CarlosChenN

@lsvih 
译文翻译完成，resolve #8918

2021-07-23 02:05 UTC, lsvih commented
这篇文章里的 graph 不是图像，是图哈（数据结构里的那个）

2021-07-23 03:19 UTC, PassionPenguin requested changes
bad syntax

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +# JavaScript 实现图形数据结构
```suggestion
# JavaScript 实现图形结构
```

没人说图形数据结构的吧……参照各大百科和原创文章

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +图形数据结构帮助我们创建许多强大的东西，你使用它实现非线性数据结构的可能性很高。它常用于许多数据节点之间的多重复杂连接，这也使他特别适合表现地图，网络和导航系统。
```suggestion
图形结构帮助我们创建许多强大的东西，你使用它实现非线性数据结构的可能性很高。它常用于许多数据节点之间的多重复杂连接，这也使他特别适合展示地图、网络和导航系统。
```

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +> 这篇文章是 Youtube 上[图形数据结构系列](https://www.youtube.com/watch?v=5Tx4A08TspQ&list=PLpWvGP6yhJUinXIN5wJQH7tVp3FU4dbAN&index=1)的详细的、改进文章版，如果你喜欢视频，你可以观看视频。
```suggestion
> 这篇文章是 Youtube 上[图形结构系列](https://www.youtube.com/watch?v=5Tx4A08TspQ&list=PLpWvGP6yhJUinXIN5wJQH7tVp3FU4dbAN&index=1)的详细的优化后的文章版本，如果你喜欢观看视频，你可以点击上面的 URL 观看原始视频。
```

原句倒数两句？

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +它由一组节点组成 — 也被称为由边（线）连接的顶点。如果这些顶点由方向，这个图就被称为有向图，如果两个节点的边间相互指向，那么我们就称这两个节点强连通。
```suggestion
它由一组节点组成 —— 也被称为由边（线）连接的顶点。如果这些顶点由方向，这个图就被称为有向图，如果两个节点的边间相互指向，那么我们就称这两个节点强连通。
```

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +## 什么时候使用图形数据结构？
```suggestion
## 什么时候使用图形结构？
```

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +在一个[列表数据结构中](https://javascript.plainenglish.io/array-data-structure-in-javascript-9554069c8823)，你有一个按顺序排列的元素集合，它需要你一个一个遍历，直到你找到你想要的那个元素。在像树一样的分层数据结构中，你有父子关系，可以让你去决定要导航到哪棵子树。在图形数据结构中，你有邻接点。
```suggestion
在一个[列表数据结构中](https://javascript.plainenglish.io/array-data-structure-in-javascript-9554069c8823)，你有一个按顺序排列的元素集合，它需要你一个一个遍历，直到你找到你想要的那个元素。在像树一样的分层数据结构中，你有父子关系，可以让你去决定要导航到哪棵子树。在图形结构中，你有邻接点。
```

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +# JavaScript 实现图形数据结构
change the following words

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +这要做的是首先保证两个顶点彼此不同，并且不为空。之后，我们添加他们到顶点列表中，该列表在添加他们之前已经检查这些顶点是否存在列表中。它通过将vertex2添加到vertex1邻接列表，这意味着vertex1连接到vertex2，如果它是定向的，它也使vertex2连接到vertex1的双向连接。
space

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +> **注意**: 无论何时提到 **check**，它只是表示正在读取节点值。当提到**访问**时，意味着我们正在检查它的邻接节点列表。
```suggestion
> **注意**: 无论何时提到 **check**，它只是表示正在读取节点值。当提到 **visit** 时，意味着我们正在检查它的邻接节点列表。
```

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +> **注意**: 无论何时提到 **check**，它只是表示正在读取节点值。当提到**访问**时，意味着我们正在检查它的邻接节点列表。
要不全部中文要不全部英文，下文同理

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
>  ```
no empty code lang

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
>  ```
no empty code lang

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
>  ```
no empty code lang

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +它从解构顶点和相邻列表开始，它将是一个数组和一个对象，因为这是我们在getter中定义的。如果没有顶点，它什么也不做就返回。然后，我们把所有节点都涂成绿色，这基本上是一个顶点到颜色的映射，所以我们可以很容易地查询节点的颜色
```suggestion
它从解构顶点和相邻列表开始，它将是一个数组和一个对象，因为这是我们在 getter 中定义的。如果没有顶点，它什么也不做就返回。然后，我们把所有节点都涂成绿色，这基本上是一个顶点到颜色的映射，所以我们可以很容易地查询节点的颜色
```

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +这里使用了相同的颜色概念，他的实现基于[递归函数](https://www.youtube.com/watch?v=7oLO9iAyYIM)，而不是宽度优先搜索算法中使用的while循环。它看起来像这样：
```suggestion
这里使用了相同的颜色概念，他的实现基于[递归函数](https://www.youtube.com/watch?v=7oLO9iAyYIM)，而不是宽度优先搜索算法中使用的 while 循环。它看起来像这样：
```

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +由于它们是私有的，我用 getter 去返回它们，我首先将它们转换为数组和JavaScript对象，因为它们更容易也更常用，并且它还能防止从外部更改这些私有值。
```suggestion
由于它们是私有的，我用 getter 去返回它们，我首先将它们转换为数组和 JavaScript 对象，因为它们更容易也更常用，并且它还能防止从外部更改这些私有值。
```

2021-07-23 03:19 UTC, PassionPenguin commented on article/2021/graph-data-structure-implementation-in-javascript.md
> +* **邻接矩阵**就像一个表，用1表示节点连接，用0表示节点不连接。这种方法很适合表示有限图。
```suggestion
* **邻接矩阵**就像一个表，用 1 表示节点连接，用 0 表示节点不连接。这种方法很适合表示有限图。
```

2021-07-24 06:58 UTC, CarlosChenN commented on article/2021/graph-data-structure-implementation-in-javascript.md
>  ```
不太明白你啥意思？

2021-07-24 07:00 UTC, CarlosChenN commented on article/2021/graph-data-structure-implementation-in-javascript.md
>  ```
不太明白你啥意思？

2021-07-24 07:01 UTC, CarlosChenN commented on article/2021/graph-data-structure-implementation-in-javascript.md
>  ```
不太明白你啥意思哈

2021-07-27 13:19 UTC, CarlosChenN commented on article/2021/graph-data-structure-implementation-in-javascript.md
>  ```
@lsvih 请问你知道这是指什么问题吗？

2021-08-08 06:59 UTC, CarlosChenN commented
@lsvih @PassionPenguin @zenblofe 校对完毕
有个no empty code lang问题，不太清楚是什么问题。

2021-08-09 01:58 UTC, lsvih approved these changes

2021-08-09 01:58 UTC, merged

2021-08-09 01:58 UTC, lsvih commented
@CarlosChenN   已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-08-09 02:00 UTC, lsvih commented
那个是指的代码块没有制定语言的问题= =  不过这里没加其实无伤大雅
类似于这样
```
```js
xxxxx
\```

```