通过 Redis 构建一个响应式架构
xitu/gold-miner pull request #8979
Opened 2021-08-03 17:05 UTC by YueYongDev

译文翻译完成，resolve #8940

2021-08-05 11:33 UTC, Usualminds commented
@lsvih 校对认领

2021-08-05 12:12 UTC, lsvih commented
@Usualminds  欢迎校对！

2021-08-12 04:18 UTC, lsvih commented
@jaredliw 欢迎校对~

2021-08-12 04:21 UTC, lsvih commented
@YueYongDev  您可以先微调一下格式哈，有些列表不需要换行的

2021-08-12 12:00 UTC, Usualminds commented on article/2021/building-a-reactive-architecture-around-redis.md
> +对于可以充当代理的东西，我们需要确保我们的代码知道他在哪里，以及他所需要的事件类型，以此来确保订阅到某些事件。
```suggestion
对于可以充当代理的东西，我们需要确保我们的代码知道它在哪里，以及他所需要的事件类型，以此来确保订阅到某些事件。
```

2021-08-12 12:07 UTC, Usualminds commented on article/2021/building-a-reactive-architecture-around-redis.md
> +所有这些特性都使得你可以以各种方式与你的业务逻辑进行沟通，根据你所期望的行为类型，你可能想解决其中的一个，或全部。
```suggestion
所有这些特性都使得你可以以各种方式与你的业务逻辑进行适配，根据你所期望的行为类型，你可能想解决其中的一个或全部。
```

2021-08-12 12:07 UTC, Usualminds commented on article/2021/building-a-reactive-architecture-around-redis.md
> +所有这些特性都使得你可以以各种方式与你的业务逻辑进行沟通，根据你所期望的行为类型，你可能想解决其中的一个，或全部。
communicate with 这里建议意译一下

2021-08-12 12:12 UTC, Usualminds commented on article/2021/building-a-reactive-architecture-around-redis.md
> +整个过程从 1 开始，由 “Client App” 提交请求，到 9 号也即由 ”Client App“ 得到响应通知结束。其余的呢？我不关心，客户端 App 也不需要关心。
```suggestion
整个过程从步骤 1 开始，由 `Client App` 提交请求，到步骤 9 由  `Client App`  得到响应通知结束。其余的呢？我不关心，客户端 App 也不需要关心。
```

2021-08-12 12:15 UTC, Usualminds commented on article/2021/building-a-reactive-architecture-around-redis.md
> +这就是这种模式的好处之一，使得架构对客户来说成为一个黑盒。一个请求可以触发数百个事件，也可能只触发一个，但是行为都是一样的：一旦准备好响应，它就会被传递给客户端。而不是让客户端知道需要多长时间或者需要多久检查一次是否准备好。这些在这里都不重要。
```suggestion
这种模式的好处之一就是使得架构对客户端来说成为一个黑盒。一个请求可以触发数百个事件，也可能只触发一个，但是行为都是一样的：一旦准备好响应，它就会被传递给客户端。而不是让客户端知道需要多长时间或者需要多久检查一次是否准备好。这些在这里都不重要。
```

2021-08-12 12:21 UTC, Usualminds commented on article/2021/building-a-reactive-architecture-around-redis.md
> +- 一条信息由其订阅者发布到一个 “频道”。如果你想发布不同类型的主题，建议你创建多个不同的频道。另外，如果你需要额外的粒度来区分哪个消费者必须负责处理某个特定的消息，那么这些细节就需要成为消息的一部分。这是因为一个通道的所有订阅者都会得到相同的消息，所以如果有多个进程侦听和获取相同的消息，那么最终可能会重新执行相同的操作。例如，在 Redis 中可以用消息的 ID 作为一个标志，以确保第一个创
```suggestion
- 一条信息由其订阅者发布到一个“频道”。如果你想发布不同类型的主题，建议你创建多个不同的频道。另外，如果你需要额外的粒度来区分哪个消费者必须负责处理某个特定的消息，那么这些细节就需要成为消息的一部分。这是因为一个通道的所有订阅者都会得到相同的消息，所以如果有多个进程侦听和获取相同的消息，那么最终可能会重新执行相同的操作。例如，在 Redis 中可以用消息的 ID 作为一个标志，以确保第一个创建它的进程将负责处理该事件，而其他进程则可以忽略它。这是一个可靠的方法，因为在 Redis 中设置一个键是一个原子过程，所以并发不会在其中起作用。
```

2021-08-12 15:47 UTC, jaredliw requested changes
@lsvih 完成啦~~
@YueYongDev @Usualminds 翻译/校对的是真滴好:thumbsup::thumbsup:

2021-08-12 15:47 UTC, jaredliw commented on article/2021/building-a-reactive-architecture-around-redis.md
> +- [发布/订阅](https://redis.io/topics/pubsub)。Redis 内部维护着一个消息队列，它允许我们发送消息，并将它们分发到每个订阅的进程。这是一种“发后即忘“类型的约定，这意味着如果没有在线的监听器，那么消息就会丢失。所以在使用时要考虑到这一点。
```suggestion
- [发布/订阅](https://redis.io/topics/pubsub)。Redis 内部维护着一个消息队列，它允许我们发送消息，并将它们分发到每个订阅的进程。这是一种“发后即忘”类型的约定，这意味着如果没有在线的监听器，那么消息就会丢失。所以在使用时要考虑到这一点。
```

2021-08-12 15:47 UTC, jaredliw commented on article/2021/building-a-reactive-architecture-around-redis.md
> +- Redis 流。这是 Redis 的数据类型的混合物，混合了键空间通知和发布/订阅，所有这些都放在一起，工作得很好。Streams 试图模仿 `tail -f` 命令在你的终端上的行为。如果你从来没有见过这个命令，说明这是一个\*nix 命令，它向你显示一个文件的最后一行，并保持监听该文件的变化，每新增一行时，终端会立即显示。Streams 也是同样的道理。如果使用得当，那么将会是一个强有力
```suggestion
- Redis 流。这是 Redis 的数据类型的混合物，混合了键空间通知和发布/订阅，所有这些都放在一起，工作得很好。Streams 试图模仿 `tail -f` 命令在你的终端上的行为。如果你从来没有见过这个命令，说明这是一个 *nix 命令，它向你显示一个文件的最后一行，并保持监听该文件的变化，每新增一行时，终端会立即显示。Streams 也是同样的道理。如果使用得当，那么将会是一个强有力的工具。[你可以阅读此处了解更多](https://blog.logrocket.com/why-are-we-getting-streams-in-redis-8c36498aaac5/)。
```
* 不必转义，it works fine。

2021-08-12 15:47 UTC, jaredliw commented on article/2021/building-a-reactive-architecture-around-redis.md
> +- 如果没有订阅者监听某个特定的频道，则发布的消息将丢失。如果你使用发布/订阅模式，就会出现这种情况，因为它是在“发后即忘”机制下工作的。如果你想确保你的信息在被处理之前一直在那里，你可以使用“阻塞队列”的方式。这种解决方案包括直接在 Redis 的键空间上创建一个列表(即一个正常的值列表)，并让进程订阅键空间通知。这样他们就可以决定如何处理插入的数据（比如忽略、处理、删除等）。
```suggestion
- 如果没有订阅者监听某个特定的频道，则发布的消息将丢失。如果你使用发布/订阅模式，就会出现这种情况，因为它是在“发后即忘”机制下工作的。如果你想确保你的信息在被处理之前一直在那里，你可以使用“阻塞队列”的方式。这种解决方案包括直接在 Redis 的键空间上创建一个列表（即一个正常的值列表），并让进程订阅键空间通知。这样他们就可以决定如何处理插入的数据（比如忽略、处理、删除等）。
```

2021-08-12 15:47 UTC, jaredliw commented on article/2021/building-a-reactive-architecture-around-redis.md
> +这些行为通常与现实世界的限制有关，需要一些时间来解决，或者甚至可以通过“等待一点时间”并重新启动倒计时来解决(就像物联网设备的连接不可靠)。
```suggestion
这些行为通常与现实世界的限制有关，需要一些时间来解决，或者甚至可以通过“等待一点时间”并重新启动倒计时来解决（就像物联网设备的连接不可靠）。
```

2021-08-12 15:47 UTC, jaredliw commented on article/2021/building-a-reactive-architecture-around-redis.md
> +2. 当你订阅一个键空间时（这也适用于 pub/sub，但我们在这里不使用），你可以使用一个模式进行订阅。换句话说，你可以订阅 "last_connection_time_of_device100002 "这个键的事件，而不是订阅 "last_connection_time_of_device"。然后，每一个创建的、符合该模式的键都会在它发生变化时通知你。
```suggestion
2. 当你订阅一个键空间时（这也适用于 pub/sub，但我们在这里不使用），你可以使用一个模式进行订阅。换句话说，你可以订阅 "last_connection_time_of_device100002" 这个键的事件，而不是订阅 "last_connection_time_of_device"。然后，每一个创建的、符合该模式的键都会在它发生变化时通知你。
```

2021-08-12 15:47 UTC, jaredliw commented on article/2021/building-a-reactive-architecture-around-redis.md
> +另一方面，如果你在该键中保存了一个复杂的结构（如果你需要这么做的话），你将不得不改变这种方法。这是因为当 TTL 过期时，键就会被删除，里面的数据也会被删除，所以你无法获取到它。这时，你可以使用一种叫做 "影子键 "的技术来代替。
```suggestion
另一方面，如果你在该键中保存了一个复杂的结构（如果你需要这么做的话），你将不得不改变这种方法。这是因为当 TTL 过期时，键就会被删除，里面的数据也会被删除，所以你无法获取到它。这时，你可以使用一种叫做 "影子键" 的技术来代替。
```

2021-08-12 15:47 UTC, jaredliw commented on article/2021/building-a-reactive-architecture-around-redis.md
> +在这两个 key 中，只有第一个有 TTL，第二个没有。因此，当你收到过期通知时，你将从过期的 key 中获取 ID（last_connection_time_of_device100002），并使用它来读取第二个 key 的内容。然后，如果你需要的话，你可以继续删除这个其他的密钥，或者把它留在那里，这取决于你的使用情况。
```suggestion
在这两个 key 中，只有第一个有 TTL，第二个没有。因此，当你收到过期通知时，你将从过期的 key 中获取 ID（last_connection_time_of_device100002），并使用它来读取第二个 key 的内容。然后，如果你需要的话，你可以删除这个密钥，或者把它留在那里，这取决于你的使用情况。
```

2021-08-12 15:47 UTC, jaredliw commented on article/2021/building-a-reactive-architecture-around-redis.md
> +这里唯一需要考虑的是，如果你把 Redis 配置为集群模式，键空间的通知不会在整个集群中广播。这意味着，你必须确保你的消费者连接到每个节点。这些通知中有一部分如果没有人接收就会丢失，这也是这项技术的唯一缺点，但是在你花费数天时间去调试你的异步逻辑前，了解这一点对你来说会有很大帮助（去过哪里，做过什么）。
```suggestion
这里唯一需要考虑的是，如果你把 Redis **配置为集群模式，键空间的通知不会在整个集群中广播。这意味着，你必须确保你的消费者连接到每个节点。通知如果没有人接收就会丢失，这也是这项技术的唯一缺点，但是在你花费数天时间去调试你的异步逻辑前，了解这一点对你来说会有很大帮助（我是过来人）。
```
“been there, done that” 是个口语表达，意思如上。

2021-08-12 15:47 UTC, jaredliw commented on article/2021/building-a-reactive-architecture-around-redis.md
> +正如你所看到的，这两种情况下的复杂性都被降低到只是确保你订阅了正确的事件或频道。如果你试图用一个普通的 SQL 数据库来做这件事，你必须通过代码实现非常复杂的逻辑，以便有效地确定何时有新的数据进入，或何时有一条信息被删除。
```suggestion
正如你所看到的，这两种情况下的复杂性都被降低了 —— 我们只需要确保已经订阅了正确的事件或频道。如果你试图用一个普通的 SQL 数据库来做这件事，你必须通过代码实现非常复杂的逻辑，以便有效地确定何时有新的数据进入，或何时有一条信息被删除。
```

2021-08-12 15:55 UTC, jaredliw requested changes
忘留名啦~

2021-08-12 15:55 UTC, jaredliw commented on article/2021/building-a-reactive-architecture-around-redis.md
> +> - 校对者：
```suggestion
> - 校对者：[Usualminds](https://github.com/Usualminds)、[jaredliw](https://github.com/jaredliw)
```

2021-08-12 16:43 UTC, YueYongDev commented
@lsvih  已更新

2021-08-13 03:17 UTC, lsvih approved these changes

2021-08-13 03:17 UTC, merged

2021-08-13 03:18 UTC, lsvih commented
@YueYongDev  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-08-15 14:40 UTC, YueYongDev commented
@lsvih 已经发布到掘金了，辛苦同步一下了，另外想问一下有哪些奖品可以兑换？积分兑换页面的东西已经好久没有更新了

2021-08-16 05:24 UTC, lsvih commented
@YueYongDev 下会儿您得把地址附上哈。。奖品目前就是那些勒，上半年更新过一次的。如果您有啥奖品想建议的，可以在群里找一下优弧- -