使用 RabbitMQ 和 SpringBoot 实现实时消息
xitu/gold-miner pull request #8998
Opened 2021-08-12 13:25 UTC by samyu2000

译文翻译完成，resolve #8976

2021-08-13 03:14 UTC, lsvih commented
@jaredliw 欢迎校对~

2021-08-13 04:55 UTC, Usualminds commented
@lsvih 校对认领

2021-08-13 08:32 UTC, jaredliw requested changes
@lsvih @samyu2000 校对完成~

2021-08-13 08:32 UTC, jaredliw commented on article/2021/RabbitMQ-and-SpringBoot-for-Real-Time-Messaging.md
> +在过去的几个月里，我一直在看《无垠苍穹》。这部剧中有太空战、战舰、外星人和许多其他很酷的科幻部队。其中有一些先进的软件，可以让空间站监视并与所有的宇宙飞船和火箭进行通信。这令我思考：今天是否有工具来为这样的东西建立一个后端。我首先想到的是 RabbitMQ 和 SpringBoot。
```suggestion
在过去的几个月里，我一直在看《苍穹浩瀚》。这部剧中有太空战、战舰、外星人和许多其他很酷的科幻部队。其中有一些先进的软件，可以让空间站监视并与所有的宇宙飞船和火箭进行通信。这令我思考：今天是否有工具来为这样的东西建立一个后端。我首先想到的是 RabbitMQ 和 SpringBoot。
```
没找到《无垠苍穹》这个翻译，维基百科上的是《苍穹浩瀚》。

2021-08-13 08:32 UTC, jaredliw commented on article/2021/RabbitMQ-and-SpringBoot-for-Real-Time-Messaging.md
> +基于上述场景，我们需要实现三个主要的用例。我们应当关注通信功能，而不是由消息触发的事件（希望在其他项目中可以讲述）。
```suggestion
基于上述场景，我们需要实现三个主要的用例。我们应当关注通信功能，而不是由消息触发的事件（希望我会在其他项目中讲述这个问题）。
```

2021-08-13 08:32 UTC, jaredliw commented on article/2021/RabbitMQ-and-SpringBoot-for-Real-Time-Messaging.md
> +2. 每艘飞船和对接站之间都将实时、一对一地进行通信。
```suggestion
2. 每艘飞船和对接站之间都将实时、一对一地进行通信。（即社交网络中的“即时消息”）
```

2021-08-13 08:32 UTC, jaredliw commented on article/2021/RabbitMQ-and-SpringBoot-for-Real-Time-Messaging.md
>  ## have to change property values for each ship
```suggestion
## 必须更改每艘船的属性值
```

2021-08-13 08:32 UTC, jaredliw commented on article/2021/RabbitMQ-and-SpringBoot-for-Real-Time-Messaging.md
> +每艘飞船都可以使用公共的路由键发送更新消息。@EnableScheduling 和 @Scheduled 注解用于设置定时任务。简单的来说，我们需要发送参数和用冒号加标点的飞船名称。在 ParameterFactory 类中，需要创建具有随机双精度值的虚拟参数。举例如下：
```suggestion
每艘飞船都可以使用公共的路由键发送更新消息。@EnableScheduling 和 @Scheduled 注解用于设置定时任务。简单的来说，我们需要发送用冒号分割隔的参数和飞船名称。在 ParameterFactory 类中，需要创建具有随机双精度值的虚拟参数。举例如下：
```

2021-08-13 08:32 UTC, jaredliw commented on article/2021/RabbitMQ-and-SpringBoot-for-Real-Time-Messaging.md
>  > * 译者：
```suggestion
> * 译者：[samyu2000](https://github.com/samyu2000)
```

2021-08-13 08:32 UTC, jaredliw commented on article/2021/RabbitMQ-and-SpringBoot-for-Real-Time-Messaging.md
>  > * 校对者：
```suggestion
> * 校对者：[jaredliw](https://github.com/jaredliw)
```

2021-08-13 08:32 UTC, jaredliw commented on article/2021/RabbitMQ-and-SpringBoot-for-Real-Time-Messaging.md
> +>  Fanout交换机忽略路由键，向所有绑定的队列发送消息。
```suggestion
>  Fanout 交换机忽略路由键，向所有绑定的队列发送消息。
```

2021-08-13 09:37 UTC, lsvih commented
@Usualminds 欢迎校对~

2021-09-02 01:36 UTC, jaredliw commented
@Usualminds 校对完成了吗？ 0.0

2021-09-02 01:40 UTC, jaredliw commented
谢谢 (u‿ฺu✿)

2021-09-02 11:06 UTC, Usualminds reviewed
@samyu2000 校对完成，久等了

2021-09-02 11:06 UTC, Usualminds commented on article/2021/RabbitMQ-and-SpringBoot-for-Real-Time-Messaging.md
> +在我的 [GitHub 仓库](https://github.com/iamtanbirahmed/real-time-comm)有相应的代码。在这里我只展示讲解相关概念所必要的代码。在开始讲解前，我先展示空间站和飞船的属性配置文件。
```suggestion
在我的 [GitHub 仓库](https://github.com/iamtanbirahmed/real-time-comm)有相应的代码。在这里我只展示与讲解相关概念所必要的代码。在开始讲解前，我先展示空间站和飞船的属性的配置文件。
```

2021-09-02 11:06 UTC, Usualminds commented on article/2021/RabbitMQ-and-SpringBoot-for-Real-Time-Messaging.md
> +在本应用程序中，每艘飞船和空间站都同时扮演生产者和消费者。所以，它们都需要自己的队列来保存消息。空间站只需要一个直接交换机和一个队列，用于接收实时消息和定时发送的消息。另一方面，由于飞船接收的消息存在两种类型———单一的和公共的，就需要两个交换机。然而它们只能跟一个队列绑定，队列再跟直接交换机和 Fanout 交换机进行绑定。本项目的实现代码：[**GitHub - iamtanbirahmed
```suggestion
在本应用程序中，每艘飞船和空间站都同时扮演生产者和消费者。所以，它们都需要自己的队列来保存消息。空间站只需要一个直接交换机和一个队列，用于接收实时消息和定时发送消息。另一方面，由于飞船接收的消息存在两种类型———单一的和公共的，就需要两个交换机。然而它们只能跟一个队列绑定，队列再跟直接交换机和 Fanout 交换机进行绑定。本项目的实现代码：[**GitHub - iamtanbirahmed/real-time-comm**](https://github.com/iamtanbirahmed/real-time-comm)。
```

2021-09-07 07:55 UTC, jaredliw commented
@samyu2000 轻轻敲醒沉睡的心灵~~

2021-09-14 02:22 UTC, Usualminds commented
@samyu2000 慢慢张开你的眼睛

2022-04-21 13:55 UTC, jaredliw commented
@lsvih 接手

2022-04-24 06:05 UTC, closed without merging