未经测试的 Python 代码已经损坏
xitu/gold-miner pull request #9000
Opened 2021-08-13 15:32 UTC by jaredliw

译文翻译完成，resolve #8549 

文章名翻译得有点僵硬，希望有更好的建议。这句话出自 Bruce Eckel （《Java 编程思想》的作者）的 “If it is not tested, it is broken.”，网上没有看到这句话的翻译。

2021-08-19 02:09 UTC, ItzMiracleOwO commented
校对认领

2021-08-19 02:15 UTC, ItzMiracleOwO commented
校对认领

2021-08-19 05:34 UTC, KimYangOfCat commented
@lsvih 校对认领

2021-08-19 07:24 UTC, lsvih commented
@ItzMiracleOwO @KimYangOfCat 欢迎校对~

2021-08-19 11:58 UTC, ItzMiracleOwO requested changes
@lsvih @jaredliw  校驗完成~

2021-08-19 11:58 UTC, ItzMiracleOwO commented on article/2021/untested-python-code-is-already-broken.md
> +我的第一位导师极其的令人难以置信。他向我展示了编码、日志记录、文档编制的最佳实践和其带来的收益。但有一件事他一直无法灌输给我，那就是测试。他的测试代码方式很复杂，包括说先写测试程序，然后编码实现！他的方式与我的编码风格对立，这让我觉得："**如果我在写函数前就写好了测试，那么我还不如不写测试。**”这样想让我感觉好多了。
我的第一位导师极其的令人难以置信。他向我展示了编码、日志记录、文档编制的最佳实践方法和其带来的收益。但有一件事他一直**无法**灌输给我，那就是测试。他的测试代码方式很复杂，包括先写测试程序，然后再用代碼实现！他的方式与我的编码风格对立，这让我觉得：**"如果我在写函数前就写好了测试，那么我还不如不写测试。”**... 这样想让我感觉好多了。

2021-08-19 11:58 UTC, ItzMiracleOwO commented on article/2021/untested-python-code-is-already-broken.md
> +* Mock 和 patch
* Mocking 和 patch

2021-08-19 11:58 UTC, ItzMiracleOwO commented on article/2021/untested-python-code-is-already-broken.md
> +* 什么时候编写测试？
* 什么时候進行测试？

2021-08-19 11:58 UTC, ItzMiracleOwO commented on article/2021/untested-python-code-is-already-broken.md
> +首先，我们 `import unittest`，它是一个用于测试代码的内置 Python 包，然后我们导入 `order_up.py` 文件（注意我们省略了 `.py` 扩展名）。
首先，我们使用了 `import unittest`，它是一个用于测试代码的 Python 内置包，然后我们导入 `order_up.py` 文件（注意我们省略了 `.py` 扩展名）。

2021-08-19 11:58 UTC, ItzMiracleOwO commented on article/2021/untested-python-code-is-already-broken.md
> +接下来，我们创建一个名为 `TestOrderUp` 的类，它只的名称和我们的文件名相匹配，这样一来我们能更容易找到失败的测试。哦，但是括号里有个东西，`unittest.TestCase`，这意味着我们的类继承了 `TestCase` 类。
接下来，我们要创建一个名为 `TestOrderUp` 的类，它只的名称和我们的文件名相匹配，这样一来我们能更容易找到失败的测试。哦，但是括号里有个东西，`unittest.TestCase`，这意味着我们的类继承了 `TestCase` 类。

2021-08-19 11:58 UTC, ItzMiracleOwO commented on article/2021/untested-python-code-is-already-broken.md
> +继承表示一个类从父类接收函数和变量。对于我们的这种情况来说，我们从 `TestCase` 继承了丰富的功能以便我们的测试工作更加的轻松。继承了什么函数和变量？我们之后会探讨这个问题。
继承表示一个类从父类接收函数和变量。对于我们的这种情况来说，我们从 `TestCase` 继承了丰富的功能以便我们的测试工作。继承了什么函数和变量？我们之后会探讨这个问题。

2021-08-19 11:58 UTC, ItzMiracleOwO commented on article/2021/untested-python-code-is-already-broken.md
> +在我们的类下面有个名为 `test_output_order_one_item` 的函数，它应该大致地解释我们在测试中所做的事情。我们将用其于测试 `get_order()` 函数并检查输出是否符合我们的预期。让我们运行它，看看会发生什么！你可以在终端中执行 `python -m unittest`，或者点击 PyCharm 中函数旁边的绿色箭头。你也可以选择执行 `make unit-test
在我们的类下面有个名为 `test_output_order_one_item` 的函数，它应该大致地解释我们在测试中所做的事情。我们将用其于测试 `get_order()` 函数并检查输出是否符合我们的预期。让我们运行它，看看会发生什么！你可以在终端中执行 `python -m unittest`，或者点击 PyCharm 中函数旁边的绿色箭头。你也可以选择执行 `make unit-test`，让代码在虚拟环境中运行 ( 我們將會在之後提到 `Makefile` ) 。看看结果：

2021-08-19 11:58 UTC, ItzMiracleOwO commented on article/2021/untested-python-code-is-already-broken.md
> +现在，`order_up` 的主要功能是获取订单，删除不在菜单上的项目，但允许重复项目。因此，让我们添加测试以确保我们在代码中保留这些功能。
现在，`order_up` 的主要功能是获取订单，删除不在菜单上的项目，以及允许重复项目。因此，让我们添加测试以确保我们在代码中保留这些功能。

2021-08-19 11:58 UTC, ItzMiracleOwO commented on article/2021/untested-python-code-is-already-broken.md
> +首先，在测试文件的开头添加 `from unittest.mock import patch`。一开始，我们正在补缀 `builtins.input()` 函数并告诉它返回 “yes”。然后，我们执行断言以检查从补丁中获得的参数是否与 `input` 的完全一致！注意到 `builtins.input` 没有括号了吗？我们可以引用函数的签名进行验证，而不是执行函数。之后，我们回到正常的测试协议：
首先，在测试文件的开头添加 `from unittest.mock import patch`。一开始，我们正在补缀 `builtins.input()` 函数并告诉它返回 “yes”。然后，我们执行断言以检查从补丁中获得的参数是否与 `input` 的完全一致！注意到 `builtins.input` 没有括号了吗？我们可以引用函数的签名进行验证，而不是执行函数。之后，我们回到正常的测试协议：运行函数，获取结果，并断言结果。在这种情况下，因为我们的 `input()` 返回值是 “yes”，我们預期 `is_order_complete()` 返回 `False`。将它添加到你的测试类中，单击运行，获得红色 OK 或绿色复选标记，让我们继续前进！

2021-08-19 11:58 UTC, ItzMiracleOwO commented on article/2021/untested-python-code-is-already-broken.md
> +为此，我们不分配 `return_value` 而是分配 `side_effect` 一个列表。
为此，我们不分配 `return_value` 而是為 `side_effect` 分配一个列表。

2021-08-19 12:21 UTC, jaredliw commented on article/2021/untested-python-code-is-already-broken.md
> +在我们的类下面有个名为 `test_output_order_one_item` 的函数，它应该大致地解释我们在测试中所做的事情。我们将用其于测试 `get_order()` 函数并检查输出是否符合我们的预期。让我们运行它，看看会发生什么！你可以在终端中执行 `python -m unittest`，或者点击 PyCharm 中函数旁边的绿色箭头。你也可以选择执行 `make unit-test
翻漏了~

2021-08-19 12:36 UTC, jaredliw reviewed
@ItzMiracleOwO 完成~
![image](https://user-images.githubusercontent.com/57293776/130069022-93bed385-6e3a-4bd9-8062-e520ff8e1f45.png)
这里提醒一下，下次校对记得用 Insert a suggestion，点击 Start a review，那么我就可以直接加进来，不用手动复制了。

2021-08-19 13:01 UTC, KimYangOfCat commented on article/2021/untested-python-code-is-already-broken.md
> +我带着一个想法离开那次会议：把你的哲学辩论从我的工作空间中**移开**。
```suggestion
我带着一个想法离开那次会议：让你的哲学辩论从我的工作中**消失**。
```

2021-08-19 13:07 UTC, KimYangOfCat commented on article/2021/untested-python-code-is-already-broken.md
> +* 什么时候進行测试？
```suggestion
* 什么时候进行测试？
```
保持简体中文

2021-08-19 13:18 UTC, jaredliw commented on article/2021/untested-python-code-is-already-broken.md
> +`side_effect` 将获取列表中的每个项目，并在每次调用 patch 函数时单独提供它。添加该代码并点击测试按钮/命令！最后一件事：在 “banana” 和 “cookie” 中没有是/否，因为`get_order()`不会询问“你想订购更多吗？”如果 `MENU` 中不存在该项目。 如果你想自己玩弄这个列表，请记住这件事情。
```suggestion
`side_effect` 将获取列表中的每个项目，并在每次调用 patch 函数时单独提供它。添加该代码并点击测试按钮/命令！最后一件事：在 “banana” 和 “cookie” 中没有是/否，因为如果 `MENU` 中不存在该项目，`get_order()`不会询问“你想订购更多吗？”。如果你想自己玩弄这个列表，请记住这件事情。
```

2021-08-19 13:18 UTC, jaredliw commented on article/2021/untested-python-code-is-already-broken.md
> +问题在于：你的代码需要测试。这是因为所有代码，即便是好的代码，都与 bug 只有一线之遥。对于新手的解释：bug 是代码中意外的功能或错误。你可能对自己的代码及其局限性非常了解，但是新队友呢？或者，在一年后，你想为一个你已经基本忘记的项目添加一个功能，该怎么办？测试就好比保龄球道上的保险杠，让你每次都可以对提交代码和性能评估充满信心。
👍🏼 👍🏼 👍🏼

2021-08-19 13:18 UTC, jaredliw commented on article/2021/untested-python-code-is-already-broken.md
> +# 未经测试的 Python 代码已经损坏
👍🏼 👍🏼 👍🏼

2021-08-19 13:19 UTC, jaredliw commented on article/2021/untested-python-code-is-already-broken.md
> +`side_effect` 将获取列表中的每个项目，并在每次调用 patch 函数时单独提供它。添加该代码并点击测试按钮/命令！最后一件事：在 “banana” 和 “cookie” 中没有是/否，因为`get_order()`不会询问“你想订购更多吗？”如果 `MENU` 中不存在该项目。 如果你想自己玩弄这个列表，请记住这件事情。
我多写了个空格

2021-08-19 13:20 UTC, jaredliw reviewed
@lsvih @ItzMiracleOwO @KimYangOfCat 完成啦~~~~~~ 谢谢大家 <3

2021-08-19 13:24 UTC, jaredliw commented
咦，我好像 commit 不上？

2021-08-19 13:46 UTC, ItzMiracleOwO commented
> @ItzMiracleOwO 完成~
> ![image](https://user-images.githubusercontent.com/57293776/130069022-93bed385-6e3a-4bd9-8062-e520ff8e1f45.png)
> 这里提醒一下，下次校对记得用 Insert a suggestion，点击 Start a review，那么我就可以直接加进来，不用手动复制了。

好的 谢谢提醒～

2021-08-19 14:14 UTC, lsvih commented
@jaredliw 劳驾添加一下另一位校对者的信息哈

2021-08-19 14:16 UTC, jaredliw commented on article/2021/untested-python-code-is-already-broken.md
> +> * 校对者：[ItzMiracleOwO](https://github.com/ItzMiracleOwO)
```suggestion
> * 校对者：[ItzMiracleOwO](https://github.com/ItzMiracleOwO)、[KimYangOfCat](https://github.com/KimYangOfCat)
```

2021-08-19 14:17 UTC, jaredliw commented
好嘞，完成 @lsvih

2021-08-19 14:18 UTC, lsvih approved these changes

2021-08-19 14:18 UTC, merged

2021-08-19 14:18 UTC, lsvih commented
@jaredliw   已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-08-19 14:18 UTC, lsvih commented
喜提第 9000 号 PR

2021-08-19 14:37 UTC, jaredliw commented
@lsvih 已发布：https://juejin.cn/post/6998149281576288292
我能转载吗？

2021-08-20 03:07 UTC, lsvih commented
收到

当然能转载啦，您自己的大作~ 不过请保留校对者的信息哈

2021-08-20 03:08 UTC, jaredliw commented
好勒，没问题