Reverse engineering the car file format
xitu/gold-miner pull request #9002
Opened 2021-08-15 00:46 UTC by LoneyIsError

译文翻译完成，resolve #id

2021-08-15 01:53 UTC, jaredliw commented
@lsvih 校对认领

2021-08-15 01:54 UTC, lsvih commented
@jaredliw 好嘞

2021-08-16 15:23 UTC, jaredliw requested changes
@LoneyIsError @lsvih 校对完成~
代码有些使用的是 Allman 风格，一些则是 K&R 风格，可考虑统一一下。
![image](https://user-images.githubusercontent.com/57293776/129587687-17c9a740-a047-40ce-be79-4b3af93c6a54.png)

这里想请教一下 @LoneyIsError ，`__attribute__` 和 `attribute` 有什么区别？我看到有几个被修改了但有些又没有。我不懂行哈哈，非常抱歉~

2021-08-16 15:23 UTC, jaredliw commented on article/2021/reverse-engineering-the-car-file-format.md
>  };
`=` 排歪了，建议校正一下，我这里改不了

2021-08-16 15:23 UTC, jaredliw commented on article/2021/reverse-engineering-the-car-file-format.md
> +在这些复杂的结构之后可以看到副本数据。它包含特定副本类型的报头，后跟压缩或未压缩的实际数据。长度设置在  `csibitmaplist` 结构的 `renditionLength` 字段中。
```suggestion
在这些复杂的结构之后可以看到副本数据。它包含特定副本类型的报头，后跟压缩或未压缩的实际数据。长度设置在 `csibitmaplist` 结构的 `renditionLength` 字段中。
```

2021-08-16 15:23 UTC, jaredliw commented on article/2021/reverse-engineering-the-car-file-format.md
> +`csiheader` 报头的 `pixelFormat` 和  `layout`  字段用于了解应使用哪种副本类型。在本文中，我将仅描述 4 种最常见的副本类型：
```suggestion
`csiheader` 报头的 `pixelFormat` 和 `layout` 字段用于了解应使用哪种副本类型。在本文中，我将仅描述 4 种最常见的副本类型：
```

2021-08-16 15:23 UTC, jaredliw commented on article/2021/reverse-engineering-the-car-file-format.md
> +- CUIThemePixelRendition：pixelFormat 设置为“ARGB”、“GA8”、“RGB5”、“RGBW”或“GA16”，而布局设置为图像子类型。
```suggestion
- CUIThemePixelRendition：pixelFormat 设置为 `ARGB`、`GA8`、`RGB5`、`RGBW` 或 `GA16`，而布局设置为图像子类型。
```

2021-08-16 15:23 UTC, jaredliw commented on article/2021/reverse-engineering-the-car-file-format.md
> +- CUIRawPixelRendition：pixelFormat 为 “JPEG“ 或 “HEIF“。布局设置为图像的子类型。
```suggestion
- CUIRawPixelRendition：pixelFormat 为 `JPEG` 或 `HEIF`。布局设置为图像的子类型。
```

2021-08-16 15:23 UTC, jaredliw commented on article/2021/reverse-engineering-the-car-file-format.md
> +- CUIRawDataRendition：pixelFormat 设置为“DATA”，布局设置为 kRenditionLayoutType_Data
```suggestion
- CUIRawDataRendition：pixelFormat 设置为 DATA，布局设置为 kRenditionLayoutType_Data
```

2021-08-16 15:23 UTC, jaredliw commented on article/2021/reverse-engineering-the-car-file-format.md
> +并不是所有的结构都这么简单，例如用于 PNG 图像的CUIThemePixelRendition 就稍微复杂一些。与其他类型的副本一样，CUIThemePixelRendition 具有特定的报头：
```suggestion
并不是所有的结构都这么简单，例如用于 PNG 图像的 CUIThemePixelRendition 就稍微复杂一些。与其他类型的副本一样，CUIThemePixelRendition 具有特定的报头：
```

2021-08-16 15:23 UTC, jaredliw commented on article/2021/reverse-engineering-the-car-file-format.md
> +- `version` 设为 0
```suggestion
- `version` 始终设为 0
```

2021-08-16 15:23 UTC, jaredliw commented on article/2021/reverse-engineering-the-car-file-format.md
> +* `rawDataLength` 包含  `rawData` 的大小。
```suggestion
* `rawDataLength` 包含 `rawData` 的大小。
```

2021-08-16 15:23 UTC, jaredliw commented on article/2021/reverse-engineering-the-car-file-format.md
> +* 最后 `rawData`  包含真实数据 - 未压缩或压缩。如果数据被压缩，你需要使用  `compressionType`  字段中指定的算法对其进行解压缩。
```suggestion
* 最后 `rawData` 包含真实数据 —— 未压缩或压缩。如果数据被压缩，你需要使用  `compressionType`  字段中指定的算法对其进行解压缩。
```

2021-08-16 15:23 UTC, jaredliw commented on article/2021/reverse-engineering-the-car-file-format.md
> +`.car` 文件可以存储许多不同类型的资产，这使得这种文件格式相当复杂。在本文中，我描述了最重要的结构以及如何转储它们。可以使用类似的方法来分析和理解其他结构。
```suggestion
`.car` 文件可以存储许多不同类型的资产，这使得这种文件格式相当复杂。在本文中，我描述了最重要的结构以及如何转储它们。类似的方法可应用于分析和理解其他结构。
```

2021-08-16 15:23 UTC, jaredliw commented on article/2021/reverse-engineering-the-car-file-format.md
>  };
`=` 排歪了，建议校正一下，我这里改不了

2021-08-16 15:24 UTC, jaredliw commented
@lsvih 没文章了，多放点呗，释放旧的也行~~

2021-08-17 06:06 UTC, LoneyIsError commented
@jaredliw 更改了一版，文章太大了

2021-08-28 02:44 UTC, lsvih commented
@LoneyIsError 好的

2021-08-28 02:51 UTC, lsvih commented
@LoneyIsError 校对者提的 comments 里还有大量没回应或修改的，我看了下主要是一些排版格式的问题和部分翻译问题，您再过一下哈，可能是有些 comment 被隐藏了。建议直接在 File Changes 里面看

2021-08-31 07:09 UTC, lsvih commented
@LoneyIsError 您先发吧~

2021-08-31 07:09 UTC, lsvih approved these changes

2021-08-31 07:09 UTC, merged