使用 PeerJS 轻松实现 P2P 通信
xitu/gold-miner pull request #9003
Opened 2021-08-15 08:19 UTC by Tong-H

使用 PeerJS 轻松实现 P2P 通信

译文翻译完成，resolve #8988

2021-08-15 08:54 UTC, jaredliw commented
@lsvih 校对认领

2021-08-15 09:39 UTC, lsvih commented
@jaredliw 欢迎校对

2021-08-15 14:56 UTC, CarlosChenN commented
@lsvih 校对认领

2021-08-15 15:47 UTC, jaredliw requested changes
@lsvih @Tong-H 完成~

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
>  > * 校对者：
```suggestion
> * 校对者：[jaredliw](https://github.com/jaredliw)
```

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +当在 web 应用中涉及到实时 P2P 通信时，WebRTC 是许多开发者使用的标准。但它包含一些复杂性：
```suggestion
当在 web 应用中涉及到实时 P2P 通信时，WebRTC 是许多开发者的使用标准。但它包含一些复杂性：
```

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +> 使用 PeerJs，我们不用担心 STUN，ICE 协议候选者，或者服务器的创建，而且我们甚至可以避免使用 WebSockets。
```suggestion
> 使用 PeerJS，我们不用担心 STUN，ICE 协议候选者，或者服务器的创建，而且我们甚至可以避免使用 WebSockets。
```

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +PeerJs 提供一个完整的、可配置的点对点连接的 API， 以及一个称之为 PeerServer 的服务能够轻松的在 PeerJs 的客户端之间建立连接。
```suggestion
PeerJS 提供一个完整的、可配置的点对点连接的 API， 以及一个称之为 PeerServer 的服务，使得我们能够轻松的在 PeerJS 的客户端之间建立连接。
```

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +那么就来看看我们如何使用 PeerJs 来创建一个简单的聊天应用。
```suggestion
那么就来看看我们如何使用 PeerJS 来创建一个简单的聊天应用。
```

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +### 步骤 1 - 安装 PeerJS
```suggestion
### 步骤 1 —— 安装 PeerJS
```

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +> **注意：** PeerJS 用于在本地启动 PeerServer，但你也可以使用 [PeerServer Cloud](https://peerjs.com/peerserver.html) 实例。
```suggestion
> **注意**：PeerJS 用于在本地启动 PeerServer，但你也可以使用 [PeerServer Cloud](https://peerjs.com/peerserver.html) 实例。
```

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +现在，让我们移至 React 应用，先初始化聊天组件的 state。
```suggestion
现在，让我们移至 React 应用，并通过初始化聊天组件的 state 来开始。
```

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +> **提示：**你可以使用你自己的 ID 作为第一个参数，或者不传参，让 PeerServer 生成一个随机 ID。如果你使用 `const peer = new Peer();`，你将连接到 PeerServer Cloud。
```suggestion
> **提示：**你可以使用你自己的 ID 作为第一个参数，或者不传参，让 PeerServer 生成一个随机 ID。如果你使用 `const peer = new Peer();`，你将连接到 PeerServer Cloud。
```
> **提示**：你可以使用你自己的 ID 作为第一个参数，或者不传参，让 PeerServer 生成一个随机 ID。如果你使用 `const peer = new Peer();`，你将连接到 PeerServer Cloud。

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +PeerJS 通过封装 WebRTC 简化了整个流程，并且为我们提供了更简单的事件和方法用于工作。
```suggestion
PeerJS 通过封装 WebRTC 简化了整个流程，为我们提供了更简单的事件和方法。
```

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +Web RTC 是允许 P2P 通信的浏览器标准。但是因为牵涉到 STUN Servers，ICE 协议候选者, SDPs, 以及 WebSockets，所以实现 WebRTC 会有一点复杂。
```suggestion
WebRTC 是支持 P2P 通信的浏览器标准。但是因为牵涉到 STUN 服务器，ICE 协议候选者，SDPs，以及 WebSockets，所以实现 WebRTC 会有一点复杂。
```

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +> **注意：** 在不是 HTTPS 的连接的情况下，一些浏览器（尤其是手机浏览器）可能不允许使用相机和麦克风。你可以参考这篇[文章](https://blog.bitsrc.io/using-https-for-local-development-for-react-angular-and-node-fdfaf69693cd)，通过几个步骤设置一个本地 HTTPS 连接。
```suggestion
> **注意**：在不是 HTTPS 连接的情况下，一些浏览器（尤其是手机浏览器）可能不允许使用相机和麦克风。你可以参考这篇[文章](https://blog.bitsrc.io/using-https-for-local-development-for-react-angular-and-node-fdfaf69693cd)，通过几个步骤设置一个本地 HTTPS 连接。
```

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +就是这样了！现在，一个快速视频聊天已经全部设置好了。最后的成果看起来像这样，你可以在我的 GitHub [仓库](https://github.com/Dulanka-K/video-chat)找到完整的代码。
```suggestion
就这样！现在，一个快速视频聊天已经全部设置好了。最后的成果看起来像这样，你可以在我的 GitHub [仓库](https://github.com/Dulanka-K/video-chat)找到完整的代码。
```

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +终于到时候添加一些 JSX 来渲染我们的聊天室了。让我们添加两个输入框用于输入节点 ID 以及聊天信息。我们将使用 `ref` 属性来操作 `video` 元素。
```suggestion
终于到时候添加一些 JSX 来渲染我们的聊天室了。让我们添加两个输入框用于输入节点 ID 以及聊天信息。我们将使用 `ref` 属性来操作 `video` 元素。
```

2021-08-15 15:47 UTC, jaredliw commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +现在，让我们修改聊天室用于发送视频消息。该功能的的实现与之前我们讨论过的步骤非常相似。我们可以通过 `peer.on` 方法监听 `call` 事件从而获知来自远程节点的来电。该监听事件提供一个携带 `MediaConnection` 对象的回调函数，而接受者的视频流和音频流将提供给 `MediaConnection` 对象的  `answer` 方法。
```suggestion
现在，让我们修改聊天室用于发送视频消息。该功能的的实现与之前我们讨论过的步骤非常相似。我们可以通过 `peer.on` 方法监听 `call` 事件从而获知来自远程节点的来电。该监听事件提供一个携带 `MediaConnection` 对象的回调函数，而接受者的视频流和音频流将提供给 `MediaConnection` 对象的 `answer` 方法。
```

2021-08-16 05:25 UTC, lsvih commented
@CarlosChenN 欢迎校对

2021-08-16 14:43 UTC, CarlosChenN reviewed
@lsvih @Tong-H 校对完毕

2021-08-16 14:43 UTC, CarlosChenN commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +即使你之前没有接触过 WebRTC，但我相信你已经感受到了实现它的复杂性。但别担心，PeerJS 来解救你了。
```suggestion
即使你之前没有接触过 WebRTC，我相信你也已经感受到了实现它的复杂性。但别担心，PeerJS 来解救你了。
```

2021-08-16 14:43 UTC, CarlosChenN commented on article/2021/simplified-peer-to-peer-communication-with-peerjs.md
> +> 使用 PeerJS，我们不用担心 STUN，ICE 协议候选者，或者服务器的创建，而且我们甚至可以避免使用 WebSockets。
```suggestion
> 有了 PeerJS，我们不用担心 STUN，ICE 协议候选者，或者服务器的创建，而且我们甚至可以避免使用 WebSockets。
```

2021-08-17 05:24 UTC, Tong-H commented
https://juejin.cn/post/6997264971415420942/
@lsvih 已发布

2021-08-17 09:07 UTC, lsvih approved these changes

2021-08-17 09:09 UTC, merged