在 Python 中用最快的速度发送 HTTP 请求
xitu/gold-miner pull request #9020
Opened 2021-08-20 00:25 UTC by ItzMiracleOwO

译文翻译完成，resolve #9018

2021-08-20 00:57 UTC, jaredliw commented
@lsvih 校对认领

2021-08-20 03:33 UTC, lsvih commented
@jaredliw 欢迎校对~

2021-08-20 03:52 UTC, jaredliw requested changes
@lsvih @ItzMiracleOwO 校对完成~
少数句子不是很通顺，像是 `your machine` => `你的机器`，`线程异步使用 100 个链接`，望周知。整体来说没问题。

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +最简单易懂的方式，但也是最慢的方式。我通过这个神奇的 Python 列表操作符为测试伪造了 100 个链接：
```suggestion
这是最简单易懂的方式，但也是最慢的方式。我通过这个神奇的 Python 列表操作符为测试伪造了 100 个链接：
```

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +他用了十秒钟来完成下载 100 个链接。
```suggestion
它用了十秒钟来完成下载 100 个链接。
```

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +作为一个同步解决方案，这个代码仍有改进的空间。我们可以利用 `Session` 对象来提高速度。 Session 对象将使用 urllib3 的连接池，这意味着对于对同一主机的重复请求，将重新使用 `Session` 对象的底层 TCP 连接，从而获得性能提升。
```suggestion
作为一个同步的解决方案，这个代码仍有改进的空间。我们可以利用 `Session` 对象来提高速度。`Session` 对象将使用 `urllib3` 的连接池，这意味着对于对同一主机的重复请求，将重新使用 `Session` 对象的底层 TCP 连接，从而获得性能提升。
```

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +使用 `requests` 包可以轻松发送单个 HTTP 请求。但如果我想要异步地发送上百个甚至上百万个 HTTP 请求呢？这篇文章是一篇探索笔记，旨在找到发送多个 HTTP 请求的最快方式。
```suggestion
使用 `requests` 包可以轻松地发送单个 HTTP 请求。但如果我想要异步地发送上百个甚至上百万个 HTTP 请求呢？这篇文章是一篇探索笔记，旨在找到发送多个 HTTP 请求的最快方式。
```

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +代码在云端的 Linux(Ubuntu) VM 主机中运行，使用 Python 3.7。 Gist 中的所有代码都可以复制和运行。
```suggestion
代码在云端的 Linux（Ubuntu）VM 主机中运行，使用 Python 3.7。Gist 中的所有代码都可以被复制和运行。
```

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +为了确保请求对象无论成功与否都退出，我将使用 `with` 语句作为包装器。 Python 中的 `with` 关键词只是替换 `try...finally...` 的一个干净的解决方案。
```suggestion
为了确保请求对象无论成功与否都退出，我将使用 `with` 语句作为上下文管理器。Python 中的 `with` 关键词只是替换 `try…… finally……` 的一个干净的解决方案。
```
包装器泛指装饰器（decorator），这里的 `with` 应叫作上下文管理器（context manager）。

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +（看起来 NodeJS 的 request 包已经 [被弃用](https://github.com/request/request/issues/3142) 了，但这个示例只是为了测试 NodeJs 的事件循环与 Python 的事件循环相比如何执行。）
```suggestion
（看起来 Node.js 的 request 包已经[被弃用](https://github.com/request/request/issues/3142)了，但这个示例只是为了测试 Node.js 的事件循环与 Python 的事件循环相比如何执行。）
```

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +Python 赢得了速度游戏!
```suggestion
Python 赢得了这场速度的游戏!
```

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +请注意，如果您在 JupyterNotebook 或 IPython 中运行代码。请安装 `nest-asyncio` 包。 (感谢 [这个 StackOverflow 链接](https://stackoverflow.com/questions/46827007/runtimeerror-this-event-loop-is-already-running-in-python)。感谢 [Di
```suggestion
请注意，如果您想在 Jupyter Notebook 或 IPython 中运行代码，请安装 `nest-asyncio` 包。 (感谢[这个 StackOverflow 链接](https://stackoverflow.com/questions/46827007/runtimeerror-this-event-loop-is-already-running-in-python)。感谢 [Diaf Badreddine](https://stackoverflow.com/users/12371243/diaf-badreddine)。)
```

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +使用 ThreadPoolExecutor 及其 map 函数，我们可以创建一个代码非常简洁的多线程版本，只需要从同步版本中进行很小的代码更改。
```suggestion
有了 ThreadPoolExecutor 及其 map 函数，我们可以创建一个代码非常简洁的多线程版本，只需要从同步版本中进行很小的代码更改。
```

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +要使用 Session 对象，为 10 个线程创建 10 个 Session 对像是一种浪费，我只想要创建一个 Session 对象并在所有下载工作中重用它。为了实现这一点，代码将利用 `threading` 包中的 `local` 对象，这样10个线程工作将共享一个 Session 对象。
```suggestion
要使用 Session 对象，为 10 个线程创建 10 个 Session 对象是一种浪费，我只想要创建一个 Session 对象并在所有下载工作中重用它。为了实现这一点，代码将利用 `threading` 包中的 `local` 对象，这样 10 个线程工作将共享一个 Session 对象。
```
对像 => 对象

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +在 Thread and Queue 版本中，HTTP 请求工作中有一个 `while True` 循环，这使得 worker 函数与 Queue 纠缠不清，从同步版本到异步版本需要额外的代码改动。
```suggestion
在 Thread + Queue 的版本中，HTTP 请求工作中有一个 `while True`  循环，这使得 `worker` 函数与 Queue 纠缠不清，从同步版本变更到异步版本的代码需要额外的改动。
```

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +无论如何，我仍然会使用 Python Thread 来完成 HTTP 请求工作。我将使用一个队列来保存 100 个链接并创建 10 个 HTTP 下载工作线程来异步使用 100 个链接。
```suggestion
无论如何，我仍然会使用 Python 线程来完成 HTTP 请求工作。我将使用一个队列来保存 100 个链接并创建 10 个 HTTP 下载工作线程来异步获取这 100 个链接。
```

2021-08-20 03:52 UTC, jaredliw commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +Python 线程是一个危险的话题，有时，多线程可能会更慢！戴维·比兹利 (David Beazley) 带来了一场精彩的、涵盖了这个危险的话题的演讲。 这里有 YouTube [链接](https://docs.python-requests.org/en/master/user/advanced/).
```suggestion
Python 线程是一个危险的话题，有时，多线程可能会更慢！戴维·比兹利（David Beazley）带来了一场精彩的、涵盖了这个危险的话题的演讲。YouTube 链接在[这里](https://docs.python-requests.org/en/master/user/advanced/)。
```

2021-08-20 07:56 UTC, KimYangOfCat commented
@lsvih 校对认领

2021-08-20 08:07 UTC, lsvih commented
@KimYangOfCat 好嘞

2021-08-20 11:20 UTC, ItzMiracleOwO commented
> @lsvih @ItzMiracleOwO 校对完成~
> 少数句子不是很通顺，像是 `your machine` => `你的机器`，`线程异步使用 100 个链接`，望周知。整体来说没问题。

好的  謝謝提醒～

2021-08-20 11:26 UTC, lsvih commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +这个代码非常简短:
```suggestion
这个代码非常简短：
```

2021-08-20 19:17 UTC, KimYangOfCat reviewed
@lsvih 校对完毕

2021-08-20 19:17 UTC, KimYangOfCat commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +但是这样还是很慢，我们试试多线程解决方案
原翻译更简洁，个人认为没有必要修改

2021-08-20 19:17 UTC, KimYangOfCat commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +## 解决方案#2：多线程
```suggestion
## 解决方案#2：多线程方法
```
和前面保持一致

2021-08-20 19:17 UTC, KimYangOfCat commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +Python 线程是一个危险的话题，有时，多线程可能会更慢！戴维·比兹利 (David Beazley) 带来了一场精彩的、涵盖了这个危险的话题的演讲。 这里有 YouTube [链接](https://docs.python-requests.org/en/master/user/advanced/).
```suggestion
Python 线程是一个危险的话题，有时，多线程可能会更慢！戴维·比兹利（David Beazley）发表过一场精彩的、涵盖了这个危险话题的演讲。YouTube 链接在[这里](https://docs.python-requests.org/en/master/user/advanced/)。
```

2021-08-20 19:17 UTC, KimYangOfCat commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +无论如何，我仍然会使用 Python Thread 来完成 HTTP 请求工作。我将使用一个队列来保存 100 个链接并创建 10 个 HTTP 下载工作线程来异步使用 100 个链接。
```suggestion
无论如何，我仍然会使用 Python 线程来完成 HTTP 请求工作。我将使用一个队列来保存 100 个链接并创建 10 个 HTTP 工作线程来异步下载这 100 个链接。
```

2021-08-20 19:17 UTC, KimYangOfCat commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +上面的代码在0.74秒内完成了100个链接的下载!
```suggestion
上面的代码在 0.74 秒内就完成了 100 个链接的下载！
```

2021-08-20 19:17 UTC, KimYangOfCat commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +这个代码需要 1.1 到 1.5 秒，您可以运行它在您的机器中查看结果
```suggestion
这个代码需要 1.1 到 1.5 秒，您可以在您的设备中运行它并查看结果。
```

2021-08-24 03:21 UTC, ItzMiracleOwO commented
@lsvih 完成啦～

2021-08-24 07:22 UTC, lsvih commented
@ItzMiracleOwO 您的修改还没有提交呢= =

2021-08-24 09:12 UTC, ItzMiracleOwO commented
尴尬了 要怎么提交 😓

2021-08-24 09:21 UTC, lsvih commented
最简单的方法是，您点击右上角的 File Changes：

![image](https://user-images.githubusercontent.com/5164225/130591691-83ba3af0-acc7-47ca-bb86-0eaa0d8547e2.png)

然后点击那个 Edit

![image](https://user-images.githubusercontent.com/5164225/130591660-fa53902d-3bad-487e-94fd-9f4060da3c8f.png)


把您修改后的文件粘贴进来，点 commit 就行了

2021-08-24 11:01 UTC, ItzMiracleOwO commented
@lsvih 好了~

2021-08-25 01:47 UTC, lsvih commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
>  > * 校对者：
增加校对者信息

2021-08-25 01:47 UTC, lsvih commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +## 方法 #1 : 使用同步
```suggestion
## 方法 #1：使用同步
```

2021-08-25 01:47 UTC, lsvih commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +代码:
```suggestion
代码：
```

2021-08-25 01:47 UTC, lsvih commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +代码 :
```suggestion
代码：
```

2021-08-25 01:47 UTC, lsvih commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +结果 :
```suggestion
结果：
```

2021-08-25 01:47 UTC, lsvih commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +代码 :
```suggestion
代码：
```

2021-08-25 01:47 UTC, lsvih commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +最后的输出和线程队列版本一样快:
```suggestion
最后的输出和线程队列版本一样快：
```

2021-08-25 01:47 UTC, lsvih commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +这个代码非常简短 :
```suggestion
这个代码非常简短：
```

2021-08-25 01:47 UTC, lsvih commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +并在代码开头添加以下两行代码 :
```suggestion
并在代码开头添加以下两行代码：
```

2021-08-25 01:47 UTC, lsvih commented on article/2021/send-http-requests-as-fast-as-possible-in-python.md
> +## 解决方案#5 ：如果是 Node.js 呢？
```suggestion
## 解决方案#5：如果是 Node.js 呢？
```

2021-08-25 01:48 UTC, lsvih commented
@ItzMiracleOwO 您好，还得劳烦您添加一下校对者信息哈，以及还有部分格式上的小问题附在前面了

2021-08-25 02:02 UTC, ItzMiracleOwO commented
> @ItzMiracleOwO 您好，还得劳烦您添加一下校对者信息哈，以及还有部分格式上的小问题附在前面了

好的，已經完成啦～

2021-08-25 02:03 UTC, lsvih approved these changes

2021-08-25 02:04 UTC, merged

2021-08-25 02:04 UTC, lsvih commented
@ItzMiracleOwO  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-08-25 10:39 UTC, ItzMiracleOwO commented
好的 已經發佈啦~ 
[點我點我 <3](https://juejin.cn/post/7000315185411915807/)