Update and rename distributed-tracing-matters.md to 分佈式追踪事項.md
xitu/gold-miner pull request #9048
Opened 2021-08-28 13:56 UTC by ItzMiracleOwO

译文翻译完成，resolve #9010  @lsvih 

第23行，原文是 * Key Takeaways 翻译的感觉有点奇怪 如果有任何意见请尽管提出

2021-08-28 14:00 UTC, lsvih commented
@ItzMiracleOwO 您好，文件名不需要修改哈，不然链接和 diff 对不上了

2021-08-28 14:02 UTC, lsvih commented on article/2021/分佈式追踪事項.md
> +单片的问题大多是易于调查的。您可以查找执行迹线，并详细调查错误和瓶颈。有时它可以快速查看堆叠追踪，以了解您业务流程中的问题是什么。
monolith 在本文语境中翻译成“单体式应用”或者“单体式系统”会比较合适一些

2021-08-28 14:17 UTC, jaredliw commented
@lsvih 校对认领

2021-08-28 14:21 UTC, lsvih commented
@jaredliw 好的

2021-08-28 14:21 UTC, lsvih commented
@jaredliw 您等译者把文件名改回去再校对哈

2021-08-28 14:21 UTC, ItzMiracleOwO commented
> @ItzMiracleOwO 您好，文件名不需要修改哈，不然链接和 diff 对不上了

好的呀 謝謝提醒～
（我滴媽 這效率 我刷了會微信就開始校對了

2021-08-28 14:23 UTC, ItzMiracleOwO commented
> @jaredliw 您等译者把文件名改回去再校对哈

已經改好啦～

2021-08-29 03:32 UTC, jaredliw requested changes
@lsvih @ItzMiracleOwO 校对大致完成（待会儿我会再过几遍，肝了5个小时，心力交瘁了。。）
这里提一下，
distributed tracing 中的 tracing 翻成 追踪 会不会比 跟踪 来得好？

2021-08-29 03:32 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +我们的根跨度仅用于跟踪我们的跟踪标识符。 最重要的是，我们将跟踪我们打开的所有跨度，并在操作或流程完成时删除每个跨度。
```suggestion
我们的根跨度仅用于跟踪我们的跟踪标识符。最重要的是，我们将跟踪我们打开的所有跨度，并在操作或流程完成时删除每个跨度。
```

2021-08-29 03:32 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +这使我们的示例很小，我们必须采取的基本步骤相当简单 :
```suggestion
这使我们的示例很小，我们必须采取的基本步骤相当简单：
```

2021-08-29 03:32 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +这意味着，参与的请求在我们的生态系统中的每个组件应有助于至少一个跨度。由于跨度可以引用其他跨度，我们可以建立一个完整的堆栈跟踪信息的多个时间段的覆盖在单个请求中的所有操作。跨度的大小没有限制。这基本上可以在任何地方被使用，从覆盖整个复杂的过程到单个功能甚至操作的跨度。
```suggestion
这意味着，我们生态系统中涉及请求的每个组件都应至少贡献一个跨度。由于跨度可以引用其他跨度，我们可以利用这些跨度来建立一个完整的栈追踪，以覆盖单个请求中的所有操作。跨度的精细程度不限。这基本上可以在任何地方使用，从覆盖整个复杂的过程到单个功能甚至操作的跨度。
```
多个时间段？

2021-08-29 03:32 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +看看应用程序中的专用线程，它一次只能有一个活动跨度，称为 `ActiveSpan`。 这并不意味着不能有多个跨度，而是其他需要被阻塞或等待。
```suggestion
看看应用程序中的专用线程，它一次只能有一个 active 的跨度，称为 `ActiveSpan`。 这并不意味着我们不能有多个跨度，而是其他跨度会被阻塞。
```

2021-08-29 03:32 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +如果生成了一个新的跨度而没有另外指定，当前活动的跨度会自动成为其父跨度。
```suggestion
当生成了一个新的跨度时，如果没有另外指定，当前 active 的跨度会自动成为其父跨度。
```

2021-08-29 03:32 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
>  ![Example traceparent HTTP header](https://cdn-images-1.medium.com/max/2000/1*qBXxYI9Qo_8RcohWoRegUQ.png)
```suggestion
![`traceparent` HTTP 表头示例](https://cdn-images-1.medium.com/max/2000/1*qBXxYI9Qo_8RcohWoRegUQ.png)
```

2021-08-29 03:32 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +我更喜欢使用我有两个专用对象的请求上下文
：
```suggestion
我更喜欢使用我有两个专用对象的请求上下文：
```

2021-08-29 03:32 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +总而言之：分布式跟踪有很多理由。
```suggestion
总而言之：种种原因都促使你需要使用分布式追踪。
```
分布式追踪有很多理由？什么理由？

2021-08-29 03:32 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +标头 `traceparent` 携带四种不同类型的信息：版本、跟踪标识符、父标识符和标志。
```suggestion
`traceparent` 标头携带四种不同类型的信息：版本、追踪标识符、父标识符和 flag。
```

2021-08-29 03:32 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
>  We can identify the parent, the timestamp of the span as well as our vendor. There are no fixed rules on which information the trace state header can carry or how it has to look, so it can hugely var
请译者翻译一下这段

2021-08-29 03:32 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +现在我们已经介绍了这些概念。 让我们通过了解如何利用这个概念来初始化跟踪以及如何通过自己打开和关闭跨度来扩展它们来将其付诸实践。
```suggestion
现在我们已经介绍了这些概念。让我们通过了解如何利用这个概念来初始化跟踪以及如何通过自己打开和关闭跨度来扩展它们来将其付诸实践。
```

2021-08-29 03:32 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +让我们看一个基本场景，其中我们想要添加到分布式跟踪中的系统仅通过调用另一个外部调用来执行次要业务逻辑。
```suggestion
让我们看一个基本场景，其中我们想要添加到分布式追踪中的系统仅通过调用另一个外部调用来执行次要业务逻辑。
```

2021-08-29 07:09 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +* **OpenTracing API**— 一个独立于供应商的框架
vendor 指的是什么？attention needed

2021-08-29 07:12 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +* **概念** — 跨度，范围和线程
```suggestion
* **概念** — span，scope 和线程
```
网上看到的大多都没有翻译，我就暂时先不翻译了，看看下一个校对者怎么说吧

2021-08-29 07:44 UTC, jaredliw requested changes

2021-08-29 07:44 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +> OpenTracing 由 API 规范、实现规范的框架和库以及项目文档组成。 OpenTracing 允许开发人员使用 API 将检测添加到他们的应用程序代码中，而这些 API 不会将他们锁定在任何特定产品或供应商中。
```suggestion
> OpenTracing 由 API 规范、实现规范的框架和库以及项目文档组成。OpenTracing 允许开发人员使用 API 将检测添加到他们的应用程序代码中，而这些 API 不限定于任何特定产品或供应商。
```

2021-08-29 07:44 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +看看应用程序中的专用线程，它一次只能有一个活动跨度，称为 `ActiveSpan`。 这并不意味着不能有多个跨度，而是其他需要被阻塞或等待。
不确定 dedicated 是否翻译准确

2021-08-29 07:44 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +### 跟踪父级
这有问题

2021-08-29 07:44 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +### 状态跟踪
```suggestion
### 追踪的状态
```

2021-08-29 07:44 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
>  ![Example tracestate HTTP header sent by NewRelic](https://cdn-images-1.medium.com/max/2000/1*V5wa57TXTNpOEkE_fKkczw.png)
```suggestion
![由 NewRelic 发送的 `tracestate` HTTP 标头示例](https://cdn-images-1.medium.com/max/2000/1*V5wa57TXTNpOEkE_fKkczw.png)
```

2021-08-29 07:44 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +标头 `tracestate` 是伴随 Trace Parent 的，添加特定于供应者的跟踪信息。
```suggestion
标头 `tracestate` 是伴随 Trace Parent 的，添加特定于供应者的追踪信息。
```

2021-08-29 07:44 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +* 一个保存 span 必要细节的对象：打开它的时间戳和跨度的标识符
```suggestion
* 一个保存跨度必要细节的对象：打开它时的时间戳和跨度的标识符
```

2021-08-29 07:44 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +* 一个跟踪跨度名称的列表，按照跨度打开的顺序
```suggestion
* 一个跟踪跨度名称的列表，按照跨度打开时间顺序排列。
```
意译

2021-08-29 07:44 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +### 设置我们的跟踪
```suggestion
### 设置我们的追踪
```

2021-08-29 07:44 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +我们可以在单个系统中根据需要打开任意数量的跨度。 我们只需要确保我们正确嵌套它们并分别关闭它们。 因此，手动实现需要跟踪跨度堆栈。
```suggestion
我们可以在单个系统中根据需要打开任意数量的跨度。我们只需要确保我们正确嵌套它们并分别关闭它们。因此，我们需要手动实现来跟踪跨度堆栈。
```

2021-08-29 07:44 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +* 我们将跨度详细信息提交给我们的跟踪收集器系统
```suggestion
* 我们将跨度详细信息提交给我们的追踪收集器系统
```

2021-08-29 07:44 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +现在我们已经介绍了这些概念。 让我们通过了解如何利用这个概念来初始化跟踪以及如何通过自己打开和关闭跨度来扩展它们来将其付诸实践。
这句不通顺，得重构

2021-08-29 09:00 UTC, KimYangOfCat commented
@lsvih 校对认领

2021-08-29 09:45 UTC, lsvih commented
@KimYangOfCat  欢迎校对

2021-08-29 11:07 UTC, ItzMiracleOwO commented
@lsvih `vendor` 這個字不確定要如何翻譯

2021-08-29 11:49 UTC, ItzMiracleOwO commented
Line 95: `Trace Parent` 翻譯爲 `跟踪父级` 好像有點怪怪的 
@lsvih

2021-08-29 13:08 UTC, lsvih commented
`vendor` 这里翻成供应商我觉得没问题哈~

2021-08-29 23:13 UTC, KimYangOfCat reviewed
@ItzMiracleOwO 额。。。，怎么说呢？目前的翻译问题还蛮大的，我只检查了四句话，但其中三句话都有语法级的翻译错误，导致最后翻译出来的句子结构都不太正确，造成歧义。
所以希望你能再检查一次翻译，重点查看句式结构吧。

校对尚未完成，后面还会继续校对

2021-08-29 23:13 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +在本文中，我想向您介绍 OpenTracing API，W3C 的 trace context，以及如何构建您自己的自定义集成。您可以将其用于创建和扩展您选择的追踪工具的 trace context。
```suggestion
在本文中，我想向你介绍 OpenTracing API，W3C 的 Trace Context 规范，以及如何构建你自己的自定义集成，你可以将其用来为你选择的追踪工具创建和扩展追踪上下文。
```
Trace Context specification ：这里漏掉了 specification；
 Trace Context  作为一个专业名词，可不翻译，但需保持大小；但是后文 extend trace context ，我个人认为应该翻译
integration which you can use ：是 which 引导的一个宾语从句，那么此处不太适合分裂成两句话。

2021-08-30 04:19 UTC, ItzMiracleOwO commented
刚刚再过了一遍 希望有解决一些问题

2021-08-30 05:45 UTC, lsvih commented
@KimYangOfCat

2021-08-30 07:37 UTC, jaredliw requested changes
我 ok 了，就是 trace parent 看看 @KimYangOfCat 怎么翻吧

2021-08-30 07:37 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +* 一个保存跨度必要细节的对象：打开它时的时间戳和跨度的标识符
```suggestion
* 一个保存跨度必要细节的对象：打开它时的时间戳和跨度的标识符。
```

2021-08-30 07:37 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +如果没有跟踪状态头进入我们的系统，我们可以很容易地通过自己生成一个新的。如果已经有一个，我们将通过打开新的跨度来扩展跟踪。
```suggestion
如果状态头没传入我们的系统，我们可以很容易地手动生成一个新的。如果已经有了一个，我们将通过打开新的跨度来扩展追踪。
```

2021-08-30 07:37 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +我们可以识别父级、跨度的时间戳以及我们的供应者。 跟踪状态标头可以携带哪些信息或它的外观没有固定的规则，因此它可能会因你使用的跟踪工具而有很大差异。
```suggestion
我们可以识别父级、跨度的时间戳以及我们的供应商。没有固定的规则规定追踪的状态标头需携带哪些信息，因此它可能会因你使用的追踪工具而有很大差异。
```

2021-08-30 08:24 UTC, KimYangOfCat reviewed
@lsvih 校对完毕

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +这使我们的示例变得很小，因此我们必须采取的基本步骤相当简单：
```suggestion
我们的示例非常简单，因此我们必须采取的基本步骤也相当简单：
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +* 如果还没有跟踪，我们将初始化一个新的（根跨度）
```suggestion
* 如果还没有跟踪，我们将初始化一个新的（根 span）
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +* 我们可以在处理该请求或操作的每个系统上为每个进程边界（例如外部调用）打开一个新的跨度
```suggestion
* 我们可以在处理该请求或操作的每个系统上为每个进程边界（例如外部调用）创建一个新的 span
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +* 我们将在完成后关闭我们打开的跨度
```suggestion
* 我们将在完成后关闭我们打开的 span
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +* 我们将跨度详细信息提交给我们的追踪收集器系统
```suggestion
* 我们将 span 详细信息提交给我们的追踪收集器系统
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +我们可以在单个系统中根据需要打开任意数量的跨度。我们只需要确保我们正确嵌套它们并分别关闭它们。因此，我们需要手动实现来跟踪跨度堆栈。
```suggestion
我们可以在单个系统中根据需要打开任意数量的 span。我们只需要确保我们正确嵌套它们并分别关闭它们。因此我们需要手动执行追踪 span 堆栈。
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +如果我们想以手动方式执行此操作，我们首先需要什么？我们需要一堆我们系统已经打开并因此需要关闭的跨度。
```suggestion
如果我们想以手动方式执行此操作，我们首先需要什么？我们需要一堆我们系统已经打开并因此需要关闭的 span。
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +### 设置我们的追踪
```suggestion
### 设置我们的追踪器
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +如果没有跟踪状态头进入我们的系统，我们可以很容易地通过自己生成一个新的。如果已经有一个，我们将通过打开新的跨度来扩展跟踪。
```suggestion
如果没有跟踪状态头进入我们的系统，我们可以自行通过生成它来轻松地创建一个新的。如果已经有一个，我们将通过打开新的 span 来扩展跟踪。
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +现在我们有了根跨度，我们可以继续操作或流程打开跨度。
```suggestion
现在我们有了根 span，我们可以继续在自定义的粒度上为操作或流程创建 span。
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +### 产生新的跨度
```suggestion
### 产生新的 span
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +为了在单个系统中跟踪我们的跨度，我们需要一个堆栈来保存我们已经打开的跨度，如前所述。
```suggestion
如前所述，为了在单个系统中跟踪我们的 span，我们需要一个堆栈来保存我们已经打开的 span。
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +我更喜欢使用我有两个专用对象的请求上下文：
```suggestion
我更喜欢使用有两个专用对象的请求上下文：
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +* 一个跟踪跨度名称的列表，按照跨度打开时间顺序排列。
```suggestion
* 一个追踪 span 名称的列表，按照 span 打开时间顺序排列。
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +* 一个保存跨度必要细节的对象：打开它时的时间戳和跨度的标识符
```suggestion
* 一个保存 span 必要细节的对象：打开它时的时间戳和 span 的标识符
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +我们的根跨度仅用于跟踪我们的跟追标识符。最重要的是，我们将跟踪我们打开的所有跨度，并在操作或流程完成时删除每个跨度。
```suggestion
我们的根 span 仅用于追踪我们的追踪器标识符。最重要的是，我们将追踪我们打开的所有 span，并在操作或流程完成时删除每个 span。
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +### 关闭跨度并提交追踪信息
```suggestion
### 关闭 span 并提交追踪信息
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +当我们需要关闭操作或进程结束的跨度时，我们可以从堆栈顶部弹出跨度。我们还可以根据我们在跨度中保存的信息或堆栈中剩余的信息来计算所需的信息。
```suggestion
当我们需要关闭操作或进程结束的 span 时，我们可以从堆栈顶部弹出 span。我们还可以根据我们在 span 中保存的信息或堆栈中剩余的信息来计算所需的信息。
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +* 我们父级的跨度标识符 —— 这是现在在堆栈顶部的跨度。
```suggestion
* 我们父级 span 标识符 —— 这是现在在堆栈顶部的 span。
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +* 操作的持续时间 —— 现在和我们在跨度保存的时间戳之间的差异。
```suggestion
* 操作的持续时间 —— 现在和我们在 span 保存的时间戳之间的差异。
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +* 追踪标识符 —— 保存在我们的根跨度中，它始终在堆栈的底部。
```suggestion
* 追踪标识符 —— 保存在我们的根 span 中，它始终在堆栈的底部。
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +在这个例子中，我们将跨度信息以他们自己的格式提交给 NewRelic。根据你使用的跟踪工具，这可能会有所不同。
```suggestion
在这个例子中，我们将 span 信息以他们自己的格式提交给 NewRelic。根据你使用的跟踪工具，这可能会有所不同。
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +## 关键要点
```suggestion
## 主要收获
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +就是这样。 你现在只需要在所有地方调用 `openNewSpan` 和 `closeSpan` 函数。将其放入某个注释中是有意义的，这样你只需注释要跟踪的方法或进程，并且自动调用打开和关闭操作。
```suggestion
就是这样。 你现在只需要在所有地方调用 `openNewSpan` 和 `closeSpan` 函数。把这一点放到一些注释中是有意义的，这样你只需注释要追踪的方法或进程，并且自动调用打开和关闭操作。
```

2021-08-30 08:24 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +> * 校对者：[jaredliw](https://github.com/jaredliw)
```suggestion
> * 校对者：[jaredliw](https://github.com/jaredliw)、[KimYangOfCat](https://github.com/KimYangOfCat)
```

2021-08-30 08:56 UTC, jaredliw requested changes

2021-08-30 08:56 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +* 如果还没有跟踪，我们将初始化一个新的（根跨度）
```suggestion
* 如果还没有追踪器，我们将初始化一个新的（根 span）
```
KimYangOfCat 的意见

2021-08-30 08:56 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +* **概念** —— 跨度，范围和线程
```suggestion
* **概念** —— spans，范围和线程
```
KimYangOfCat 的意见

2021-08-30 08:56 UTC, jaredliw commented on article/2021/distributed-tracing-matters.md
> +* 操作的持续时间 —— 现在和我们在跨度保存的时间戳之间的差异。
![image](https://user-images.githubusercontent.com/57293776/131313646-8d54ec20-9b04-4a3f-857b-8b62a9207f68.png)
@KimYangOfCat 不是吗？

2021-08-30 09:00 UTC, KimYangOfCat commented
@ItzMiracleOwO @lsvih 
总结一下吧，这篇文章是我校对时长最长的一篇文章了，其一是因文章本身的难度，其二便是文章原本的翻译质量问题。

客观上说，本文难度确实比较大，文章中所述内容属于更多是从一个架构师的角度来谈论，涉及的内容比较深。我在校对过程中也查阅了一些关于分布式追踪系统的文章，此前我也没有了解过分布式追踪系统，所以其中一些校对意见可能也不一定准确，仅供参考。

关于翻译质量的问题，在本文的译文中有一些非常基础的错误，现列举如下：
1. 全文翻译不统一，存在部分翻译，部分未翻译的情况。
2. 译句语法理解错误，导致译文歧义。
3. 部分句子逻辑不通，语句不顺。
翻译三境界，信、达、雅，其中最基本的信之境要求译文要准确，不偏离，不遗漏，本译文的质量.......其实能信之一境要求就已经算蛮高了，但不可否认本文译文与之差距甚大。所以希望译者继续加油！

由于译者是新加入掘金翻译计划的同学，还是希望译者认领翻译时认真考虑自己当前的知识储备和文章内容的关联程度，如果差距较大，请慎重认领翻译。建议先选择一些内容简单或知识相对集中的文章进行翻译。

以上所言，仅供参考

2021-08-30 09:05 UTC, KimYangOfCat commented on article/2021/distributed-tracing-matters.md
> +* 操作的持续时间 —— 现在和我们在跨度保存的时间戳之间的差异。
@jaredliw 这里确实应该理解为 差值，我都忽略，没看仔细

2021-08-30 09:59 UTC, jaredliw commented
呃呃。。我也来说一两句吧

这里我先总结一下我 review 里提出的问题：
- 繁体和简体混用
- 文章中有一些令人摸不着头脑的翻译，像是 `深潜`，`单片`，`分布式追踪有很多理由` 等等
- 格式上的问题，像是句号后有空格等等
会出现最后两个问题的原因相信大家都知道，我就不说太多，点到为止了。

这篇文章也是我搞过最久的校对，没有之一。花了不下六七个小时，文章读了不下 十遍，提了 60-70 个 commit。老实说，我也没搞过分布式追踪，也就凭借着谷歌一步步摸爬滚打地建立起这个知识体系。在 review 中可以看到，有些术语我也是不懂怎么翻译，也得依赖他人的指点。

虽然说我的翻译也没见得有多好，也常常犯错，但还是希望能给译者一个小小的建议。撇开知识储备、翻译质量什么的不说，心态正确足矣。我不知道你花了多少时间在这篇文章上，但还是希望你能对笔下的文章负责，多查查资料，多分析分析句型，更积极地参与到翻译/校对这整个过程中。（别喷我`(*>﹏<*)′，我译的每篇文章花的时间也很长，自己明白自己在写什么）

共勉之。

2021-08-30 10:00 UTC, lsvih commented
辛苦二位校对和译者了，本文翻译校对积分各增加 1 分

2021-08-31 11:54 UTC, ItzMiracleOwO commented
@lsvih 應該沒問題了

關於翻譯質量的問題，以後我會注意的。為各位前輩添麻煩了，實在抱歉

2021-09-01 06:19 UTC, lsvih approved these changes

2021-09-01 06:20 UTC, lsvih commented
辛苦了

2021-09-01 06:20 UTC, merged

2021-09-01 06:20 UTC, lsvih commented
@ItzMiracleOwO  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-09-01 11:02 UTC, ItzMiracleOwO commented
發佈了 
https://juejin.cn/post/7002917628326969381/

2021-09-01 11:07 UTC, lsvih commented
好嘞