React Native 开发者的流行存储方案
xitu/gold-miner pull request #9085
Opened 2021-09-05 07:56 UTC by KimYangOfCat

译文翻译完成，resolve #9055

2021-09-06 05:03 UTC, jaredliw commented
@lsvih 校对认领

2021-09-06 08:25 UTC, lsvih commented
@jaredliw 好的

2021-09-07 12:32 UTC, jaredliw requested changes
@KimYangOfCat 校对完成
和谷歌翻译有点过度相似，一小部分句子结构有些奇怪，词汇翻译记得统一，整体来说还能接受，就。。。下次注意一下 ❤️

2021-09-07 12:32 UTC, jaredliw commented on article/2021/trending-storage-options-for-react-native-developers.md
MongDB，PouchDB 没有空格 这里更新一下，我改不了

2021-09-07 12:32 UTC, jaredliw commented on article/2021/trending-storage-options-for-react-native-developers.md
> +[**GitHub - ospfranco/react-native-quick-sqlite：⚡️ 为 react-native提供最快的 SQLite 实现。**](https://github.com/ospfranco/react-native-quick-sqlite)
```suggestion
[**GitHub - ospfranco/react-native-quick-sqlite：⚡️ 为 React Native 提供最快的 SQLite 实现。**](https://github.com/ospfranco/react-native-quick-sqlite)
```

2021-09-07 12:32 UTC, jaredliw commented on article/2021/trending-storage-options-for-react-native-developers.md
> +此方案适合存储用户、应用程序逻辑和其他人的公共数据。它可以替代 **Async Storage**。
```suggestion
此方案适合存储常见的用户数据、应用程序逻辑等等。它可以替代 **Async Storage**。
```
这有点离谱哈，注意一下

2021-09-07 12:32 UTC, jaredliw commented on article/2021/trending-storage-options-for-react-native-developers.md
> +[**GitHub - ammarahm-ed/react-native-mmkv-storage: 可用于 React Native 的一个超快（0.0002s读/写）、小型、加密的移动键值存储框架，其使用了 JSI 并由 C++ 编写。**](https://github.com/ammarahm-ed/react-native-mmkv-storage)
```suggestion
[**GitHub - ammarahm-ed/react-native-mmkv-storage: 可用于 React Native 的一个超快（0.0002s 读/写）、小型、加密的移动键值存储框架，其使用了 JSI 并由 C++ 编写。**](https://github.com/ammarahm-ed/react-native-mmkv-storage)
```

2021-09-07 12:32 UTC, jaredliw commented on article/2021/trending-storage-options-for-react-native-developers.md
> +[**GitHub - mrousavy/react-native-mmkv: ⚡️ 一个用于 React Native 的极快的键/值存储库。~比 AsyncStorage 快 30 倍!**](https://github.com/mrousavy/react-native-mmkv)
```suggestion
[**GitHub - mrousavy/react-native-mmkv: ⚡️ 一个用于 React Native 的极快的键/值存储库。比 AsyncStorage 快大约 30 倍!**](https://github.com/mrousavy/react-native-mmkv)
```
这也离谱哈

2021-09-07 12:32 UTC, jaredliw commented on article/2021/trending-storage-options-for-react-native-developers.md
> +[**GitHub - oblador/react-native-keychain: React Native 的钥匙链存取**](https://github.com/oblador/react-native-keychain)
```suggestion
[**GitHub - oblador/react-native-keychain: React Native 的钥匙串存取**](https://github.com/oblador/react-native-keychain)
```
主流的翻译
注：上方没翻译 keychain 哈，自己统一下

2021-09-07 12:32 UTC, jaredliw commented on article/2021/trending-storage-options-for-react-native-developers.md
> +![Picture from iOS developer documentation](https://cdn-images-1.medium.com/max/2000/1*rQu7_2pJ0VwNqOMe92rbCA.png)
```suggestion
![图片来自 iOS 开发者文档](https://cdn-images-1.medium.com/max/2000/1*rQu7_2pJ0VwNqOMe92rbCA.png)
```

2021-09-07 12:32 UTC, jaredliw commented on article/2021/trending-storage-options-for-react-native-developers.md
> +在 iOS 上， [Keychain Services](https://developer.apple.com/documentation/security/keychain_services) 允许安全地存储应用程序的小块敏感信息。在 Android 上， [Shared Preference](https://developer.android.com/reference/android/
```suggestion
在 iOS 上， [Keychain Services](https://developer.apple.com/documentation/security/keychain_services) 允许安全地存储应用程序的小块敏感信息。在 Android 上， [Shared Preference](https://developer.android.com/reference/android/content/SharedPreferences) 相当于持久键值数据存储，可被用于安全存储。Shared Preference 中的数据默认不加密，但 [Encrypted Shared Preferences](https://developer.android.com/topic/security/data) 包装了 Android 的 Shared Preferences 类，并自动加密键和值。
```

2021-09-07 12:32 UTC, jaredliw commented on article/2021/trending-storage-options-for-react-native-developers.md
> +安全存储有助于存储**加密数据**。 React Native 没有捆绑任何存储敏感数据的方式。但是，已有适用于 Android 和 iOS 平台的解决方案。
```suggestion
安全存储有助于存储**加密数据**。React Native 没有附带任何存储敏感数据的方式。然而，在 Android 和 iOS 平台中这个问题已有解决方案。
```

2021-09-07 12:32 UTC, jaredliw commented on article/2021/trending-storage-options-for-react-native-developers.md
> +在 iOS 上，由 native 代码实现的 AsyncStorage 将小值存储在序列化字典中，并将较大值存储在单独的文件中。在 Android 上，AsyncStorage 将根据可用性使用 [RocksDB](http://rocksdb.org/) 或 SQLite。 AsyncStorage **在 Android 上仅支持 6 MB，**在 iOS 上支持无限量的数据。如果你的目标是
安卓？Android？
统一下

2021-09-07 12:32 UTC, jaredliw commented on article/2021/trending-storage-options-for-react-native-developers.md
> +有不同类型的数据库服务可用于通过遵循不同的方法来执行移动应用程序数据层的各种功能。全部列出如下：
```suggestion
在移动应用程序中，我们可以使用不同的方法、不同类型的数据库服务来执行数据层的各种功能。数据库列出如下：
```
适当拆分一下句子

2021-09-07 12:32 UTC, jaredliw commented on article/2021/trending-storage-options-for-react-native-developers.md
> +SQLite 是一个 C 语言库，它实现了一个**小型、快速、自包含、高可靠性、功能齐全的 SQL 数据库引擎**。它是最常用的数据库引擎。它**内置于所有手机**和大多数计算机中，并捆绑在人们每天使用的无数其他应用程序中。开发人员承诺其文件格式稳定、跨平台且向后兼容。
```suggestion
SQLite 是一个 C 语言库，它实现了一个**小型、快速、独立、高可靠性、功能齐全的 SQL 数据库引擎**。它是最常用的数据库引擎。它**内置于所有手机**和大多数计算机中，并夹带于人们每天使用的无数其他应用程序中。开发人员承诺其文件格式稳定、跨平台且向后兼容。
```

2021-09-07 12:54 UTC, KimYangOfCat commented on article/2021/trending-storage-options-for-react-native-developers.md
> +此方案适合存储用户、应用程序逻辑和其他人的公共数据。它可以替代 **Async Storage**。
🥵

2021-09-07 12:54 UTC, KimYangOfCat commented on article/2021/trending-storage-options-for-react-native-developers.md
> +SQLite 是一个 C 语言库，它实现了一个**小型、快速、自包含、高可靠性、功能齐全的 SQL 数据库引擎**。它是最常用的数据库引擎。它**内置于所有手机**和大多数计算机中，并捆绑在人们每天使用的无数其他应用程序中。开发人员承诺其文件格式稳定、跨平台且向后兼容。
感觉这里翻译为 夹带 似乎也不太合适，捆绑是个贬义，不如翻译为 打包 怎么样？

2021-09-07 12:54 UTC, KimYangOfCat commented on article/2021/trending-storage-options-for-react-native-developers.md
> +[**GitHub - mrousavy/react-native-mmkv: ⚡️ 一个用于 React Native 的极快的键/值存储库。~比 AsyncStorage 快 30 倍!**](https://github.com/mrousavy/react-native-mmkv)
这，我以为~是一个分隔符，没想起来它表达的是一个大约的意思🥵

2021-09-07 12:54 UTC, KimYangOfCat commented on article/2021/trending-storage-options-for-react-native-developers.md
> +有不同类型的数据库服务可用于通过遵循不同的方法来执行移动应用程序数据层的各种功能。全部列出如下：
👍🏻 这断句我想了很久也没想到好的

2021-09-07 12:54 UTC, KimYangOfCat commented on article/2021/trending-storage-options-for-react-native-developers.md
原文问题，我统一改一下吧

2021-09-07 12:54 UTC, KimYangOfCat commented on article/2021/trending-storage-options-for-react-native-developers.md
> +PouchDB 是一个袖珍型数据库，使应用程序可以**在离线时**将数据存储在本地，然后在应用程序重新上线时将其与 CouchDB 和兼容服务器同步，无论用户下次登录何处，都可以保持用户的数据同步。 实际上，PouchDB 是专为网络设计。但是现在开发者社区已经创建了第三方库来支持 React Native。
感觉 只为网络设计 没有 专为网络设计 好唉

2021-09-07 13:22 UTC, KimYangOfCat commented
@jaredliw 感谢校对，非常惭愧，校对了很多文章，但这却是第一次真正动手翻译，出现了很多自己以前和别人提的基础问题，汗颜！不过从中也确实体验到了翻译和校对的不同之处，很多校对中明显能看出来的问题，而在翻译时却真的很难注意到，比如名词翻译不同，目前我的翻译都是一句一句翻译地，脑子里面存储的内容只有当前这一段内容，就很难做到纵观全文地审视！🥵  幸好PR 之前，我自己校对了两遍，才勉强够看，哈哈哈！ 
 非常感谢 @jaredliw 提出的问题，下次会注意哒

2021-09-07 13:28 UTC, jaredliw commented
@KimYangOfCat 没事啦，谁都犯错😄 大家一起努力，一起进步💪🏻
挺暖心的 哈哈😜

2021-09-14 06:34 UTC, greycodee reviewed
@KimYangOfCat 校对完成

2021-09-14 06:34 UTC, greycodee commented on article/2021/trending-storage-options-for-react-native-developers.md
> +数据是任何移动应用程序的关键部分。它赋予朴素的用户界面以意义。但是存储、检索和维护数据才是真正的难题。使用不同方式的存储机制（加密存储、离线存储、面向服务的存储、自动同步存储）对于存储各种数据至关重要，并且可以加速移动应用程序开发全过程。因为应用程序的每个用户界面和功能都需要不同的数据存储机制来使该应用程序更自然。我列出了所有现有的可用于提升应用程序可用性的数据存储方法。
```suggestion
数据是任何移动应用程序的关键部分。它让简单的用户界面变得有意义。但是存储、检索和维护数据才是真正的难题。使用不同方式的存储机制（加密存储、离线存储、面向服务的存储、自动同步存储）对于存储各种数据至关重要，并且可以加速移动应用程序开发全过程。因为应用程序的每个用户界面和功能都需要不同的数据存储机制来使该应用程序更自然。我列出了所有现有的可用于提升应用程序可用性的数据存储方法。
```

2021-09-14 06:34 UTC, greycodee commented on article/2021/trending-storage-options-for-react-native-developers.md
> +AsyncStorage 是一个**未加密的、异步的、持久的键值**存储系统，可以在应用程序上全局访问。
```suggestion
异步存储是一个**未加密的、异步的、持久的键值**存储系统，可以在应用程序上全局访问。
```

2021-09-14 06:34 UTC, greycodee commented on article/2021/trending-storage-options-for-react-native-developers.md
> +在 iOS 上，由原生代码实现的 AsyncStorage 将小值存储在序列化字典中，并将较大值存储在单独的文件中。在安卓上，AsyncStorage 将根据可用性使用 [RocksDB](http://rocksdb.org/) 或 SQLite。 AsyncStorage **在安卓上仅支持 6 MB**，在 iOS 上支持无限量的数据。如果你的目标是构建跨平台应用程序，6MB 是极限。
```suggestion
在 iOS 上，由原生代码实现的异步存储将较小的值存储在序列化字典中，并将较大值存储在单独的文件中。在安卓上，异步存储将根据可用性使用 [RocksDB](http://rocksdb.org/) 或 SQLite。 异步存储**在安卓上仅支持 6 MB 大小的数据**，在 iOS 上支持无限量的数据。如果你的目标是构建跨平台应用程序，请把数据控制在 6MB 以内。
```

2021-09-14 06:34 UTC, greycodee commented on article/2021/trending-storage-options-for-react-native-developers.md
> +除了 Shared Preferences，安卓有另一个可用于安全存储的名为[安卓 Keystore](https://developer.android.com/training/articles/keystore)的系统，用于将加密密钥存储在容器中，使其更难以从设备中提取。并且， [react-native-sensitive-info](https://github.com/mCodex/
```suggestion
除了 Shared Preferences，安卓有另一个可用于安全存储的名为[安卓密钥库](https://developer.android.com/training/articles/keystore)的系统，用于将加密密钥存储在容器中，使其更难以从设备中提取。并且， [react-native-sensitive-info](https://github.com/mCodex/react-native-sensitive-info) 的[一个分支](https://github.com/mCodex/react-native-sensitive-info/tree/keystore)使用的就是安卓密钥库。
```

2021-09-14 06:34 UTC, greycodee commented on article/2021/trending-storage-options-for-react-native-developers.md
> +[MMKV](https://github.com/Tencent/MMKV) 是腾讯开发的一个**高效、小型的移动键值**存储框架，应用于微信。
```suggestion
[MMKV](https://github.com/Tencent/MMKV) 是腾讯开发用在微信上的一个**高效、小型的移动键值**存储框架
```

2021-09-14 06:34 UTC, greycodee commented on article/2021/trending-storage-options-for-react-native-developers.md
> +此方案适合存储常见的用户数据、应用程序逻辑等等。它可以替代 **Async Storage**。
```suggestion
此方案适合存储常见的用户数据、应用程序逻辑等等。它可以替代**异步存储**。
```

2021-09-14 06:34 UTC, greycodee commented on article/2021/trending-storage-options-for-react-native-developers.md
> +此方案适合存储比异步、安全和 MMKV 存储更多的数据，支持离线应用程序开发。
```suggestion
此方案可以比异步存储、安全存储和 MMKV 存储更多的数据，而且支持离线应用程序开发。
```

2021-09-14 06:34 UTC, greycodee commented on article/2021/trending-storage-options-for-react-native-developers.md
> +> - 校对者：[jaredliw](https://github.com/jaredliw)
```suggestion
> - 校对者：[jaredliw](https://github.com/jaredliw)、[greycodee](https://github.com/greycodee)
```

2021-09-14 11:02 UTC, KimYangOfCat commented on article/2021/trending-storage-options-for-react-native-developers.md
> +AsyncStorage 是一个**未加密的、异步的、持久的键值**存储系统，可以在应用程序上全局访问。
我在这里没有翻译的原因是，AsyncStorage 是 native 实现的一个特殊对象，这里可以理解为一个 API，它的官方中文文档中并没对其进行翻译，所以这里最好遵循官方文档来，参考下面的链接：
https://reactnative.cn/docs/asyncstorage

2021-09-14 11:03 UTC, KimYangOfCat commented on article/2021/trending-storage-options-for-react-native-developers.md
> +此方案适合存储比异步、安全和 MMKV 存储更多的数据，支持离线应用程序开发。
>此方案可以比异步存储、安全存储和 MMKV 存储更多的数据，

这句话似乎没有谓语动词

2021-09-14 11:03 UTC, KimYangOfCat commented on article/2021/trending-storage-options-for-react-native-developers.md
> +在 iOS 上，由原生代码实现的 AsyncStorage 将小值存储在序列化字典中，并将较大值存储在单独的文件中。在安卓上，AsyncStorage 将根据可用性使用 [RocksDB](http://rocksdb.org/) 或 SQLite。 AsyncStorage **在安卓上仅支持 6 MB**，在 iOS 上支持无限量的数据。如果你的目标是构建跨平台应用程序，6MB 是极限。
理由同上

2021-09-14 15:53 UTC, lsvih approved these changes

2021-09-14 15:54 UTC, merged

2021-09-14 15:54 UTC, lsvih commented
@KimYangOfCat  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-09-15 05:03 UTC, KimYangOfCat commented
https://juejin.cn/post/7008020729832669191

2021-09-15 05:17 UTC, lsvih commented
get~