简述 JavaScript 的事件捕获和事件冒泡
xitu/gold-miner pull request #9086
Opened 2021-09-05 12:39 UTC by zenblofe

@lsvih 译文翻译完成，resolve #9014

2021-09-05 13:41 UTC, KimYangOfCat commented
@lsvih 校对认领

2021-09-05 14:41 UTC, lsvih commented
@KimYangOfCat 欢迎校对

2021-09-06 05:22 UTC, jaredliw commented
@lsvih 校对认领

2021-09-06 08:25 UTC, lsvih commented
@jaredliw  好的

2021-09-06 13:44 UTC, jaredliw requested changes
@zenblofe 完成
👍🏼 👍🏼 👍🏼

2021-09-06 13:44 UTC, jaredliw commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +> 通常，一个事件从它的父元素开始向目标元素传播，然后它将向它的父元素传播回来。
```suggestion
> 通常，一个事件从它的父元素开始向目标元素传播，然后它将传播回其父元素。
```

2021-09-06 13:44 UTC, jaredliw commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +* **捕获阶段：** 事件从父元素开始向目标元素传播，从 `Window` 对象开始传播。
```suggestion
* **捕获阶段**：事件从父元素开始向目标元素传播，从 `Window` 对象开始传播。
```

2021-09-06 13:44 UTC, jaredliw commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +* **目标阶段：** 该事件到达目标元素或开始该事件的元素。
```suggestion
* **目标阶段**：该事件到达目标元素或开始该事件的元素。
```

2021-09-06 13:44 UTC, jaredliw commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +* **冒泡阶段：** 这时与捕获阶段相反，事件向父元素传播，直到 `Window` 对象。
```suggestion
* **冒泡阶段**：这时与捕获阶段相反，事件向父元素传播，直到 `Window` 对象。
```

2021-09-06 13:44 UTC, jaredliw commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +![DOM 事件](https://cdn-images-1.medium.com/max/2000/1*B0k6-J5ZwfmsxZDXAOCT2Q.jpeg)
```suggestion
![DOM 事件流](https://cdn-images-1.medium.com/max/2000/1*B0k6-J5ZwfmsxZDXAOCT2Q.jpeg)
```

2021-09-06 13:44 UTC, jaredliw commented on article/2021/event-bubbling-and-capturing-in-javascript.md
>  ![Event capturing sample](https://cdn-images-1.medium.com/max/2000/1*bwNxfZVJ28WSAQ5s1MCc3A.gif)
```suggestion
![事件捕获示例](https://cdn-images-1.medium.com/max/2000/1*bwNxfZVJ28WSAQ5s1MCc3A.gif)
```

2021-09-06 13:44 UTC, jaredliw commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +连接到 `Window`、`DIV 1` 和 `button` 的点击事件将在捕获过程中分别触发，而 `DIV 2` 和 `Document`监听器则在冒泡阶段依次触发。
```suggestion
连接到 `Window`、`DIV 1` 和 `button` 的点击事件将在捕获过程中分别触发，而 `DIV 2` 和 `Document` 监听器则在冒泡阶段依次触发。
```

2021-09-06 13:44 UTC, jaredliw commented on article/2021/event-bubbling-and-capturing-in-javascript.md
>  ![](https://cdn-images-1.medium.com/max/2000/1*ZAgwPqbTDtk8TROAUe-tdw.gif)
```suggestion
![演示](https://cdn-images-1.medium.com/max/2000/1*ZAgwPqbTDtk8TROAUe-tdw.gif)
```

2021-09-06 13:44 UTC, jaredliw commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +> 有时，如果事件冒泡和捕捉开始不受我们控制地传播事件，就会让人感到厌烦。
```suggestion
> 有时，如果事件冒泡和捕捉开始不受我们控制地传播时，就会让人感到厌烦。
```

2021-09-07 10:44 UTC, zenblofe commented
@jaredliw 感谢校对
@lsvih 完成 1 次校对

2021-09-07 13:52 UTC, KimYangOfCat reviewed
@lsvih 校对完毕

2021-09-07 13:52 UTC, KimYangOfCat commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +在这篇文章中，我将用相关的示例讨论关于这个主题的全部情况。
```suggestion
在这篇文章中，我将用相关的示例来讨论关于这个主题你所需要了解的全部情况。
```

2021-09-07 13:52 UTC, KimYangOfCat commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +## 事件传播的阶段
```suggestion
## 事件传播
```

2021-09-07 13:52 UTC, KimYangOfCat commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +如果我们有几个嵌套的元素处理同一个事件，我们会对哪个事件处理程序会先触发感到困惑。这时，理解事件的顺序就变得很有必要。
```suggestion
如果我们有几个嵌套的元素处理同一个事件，我们会对哪个事件处理程序会先触发的问题感到困惑。这时，理解事件传播顺序就变得很有必要。
```

2021-09-07 13:52 UTC, KimYangOfCat commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +> 通常，一个事件从它的父元素开始向目标元素传播，然后它将传播回其父元素。
```suggestion
> 通常，一个事件会从父元素开始向目标元素传播，然后它将被传播回父元素。
```

2021-09-07 13:52 UTC, KimYangOfCat commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +现在大概了解 DOM 内部的事件流程，让我们看下事件捕获和冒泡是如何出现的。
```suggestion
现在你大概了解了 DOM 内部的事件流程，让我们再来看下事件捕获和冒泡是如何出现的。
```

2021-09-07 13:52 UTC, KimYangOfCat commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +我们可以使用 `addEventListener()` 方法的 `useCapture` 参数来注册事件的捕捉阶段。
```suggestion
我们可以使用 `addEventListener()` 方法的 `useCapture` 参数来注册捕捉阶段的事件。
```

2021-09-07 13:52 UTC, KimYangOfCat commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +在 `addEventListener()` 中省略或将 `useCapture` 参数设置为 `false`，使事件进入冒泡阶段。所以，事件监听器的默认行为是冒泡事件。
```suggestion
在 `addEventListener()` 中省略或将 `useCapture` 参数设置为 `false`，将注册冒泡阶段的事件。所以，事件监听器默认监听冒泡事件。
```

2021-09-07 13:52 UTC, KimYangOfCat commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +作为一个解决方案，我们可以使用一个单一的事件监听器，并利用事件冒泡和捕获来处理这些事件。
```suggestion
作为一个解决方案，我们可以使用一个单独的事件监听器，并利用事件冒泡和捕获来处理这些事件。
```

2021-09-07 13:52 UTC, KimYangOfCat commented on article/2021/event-bubbling-and-capturing-in-javascript.md
> +因此，我为 `table` 创建了一个单一的事件监听器，它将被用来改变单元格的样式。
```suggestion
因此，我为 `table` 创建了一个单独的事件监听器，它将被用来改变单元格的样式。
```

2021-09-08 04:47 UTC, zenblofe commented
@KimYangOfCat 感谢校对
@lsvih 完成 2 次校对，帮忙再看一下

2021-09-08 05:39 UTC, lsvih approved these changes

2021-09-08 05:39 UTC, merged

2021-09-08 05:39 UTC, lsvih commented
@zenblofe  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-09-08 13:48 UTC, zenblofe commented
@lsvih 掘金文章地址  https://juejin.cn/post/7005558885947965454/