Update the-future-of-the-web.md
xitu/gold-miner pull request #9087
Opened 2021-09-08 00:39 UTC by Gesj-yean

Web 的未来

译文翻译完成，resolve #8970

2021-09-08 01:00 UTC, KimYangOfCat commented
@lsvih 校对认领

2021-09-08 02:25 UTC, jaredliw commented
@lsvih 校对认领

2021-09-08 03:45 UTC, lsvih commented
@KimYangOfCat @jaredliw 欢迎校对

2021-09-08 13:19 UTC, KimYangOfCat reviewed
校对了一部分，翻译的句子不太通顺唉😥  结构有些奇怪

2021-09-08 13:19 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +网络是静态的，单人游戏，好像印刷时代的一部分被带到了网络上。虽然我不得不说这有点[古怪和有趣](https://www.spacejam.com/1996/)。
```suggestion
网络是静态的，私人的，就好像是印刷时代的一部分被带到了网络上。然而我不得不说这既有点[古怪又十分有趣](https://www.spacejam.com/1996/)。
```

2021-09-08 13:19 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +随着网络应用程序、社交媒体、视频流媒体和移动设备的兴​​起，网络从一种实用工具转变为一种生活方式。
```suggestion
随着网络应用程序、社交媒体、视频流媒体和移动设备的兴​​起，网络从一种实用工具转变为一种生活方式。
```
web 不翻译的话，就统一一下吧，别一会儿翻译为 网络，一会儿网页的

2021-09-08 13:19 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +黄金之泉已经喷发，科技公司开始涌入数十亿美元的资金。当有这么多钱在流动时，乐趣、最终用户隐私、最大利益的强调不会真正成为他们优先考虑的事项。
```suggestion
黄金之泉已经喷发，科技公司开始投入数十亿美元的资金。当有这么多钱在流动时，增强乐趣、终端用户隐私以及最佳兴趣就不会真正成为他们优先考虑的事项。
```
best interest 的翻译还是有些不太确定，但是感觉翻译为 利益 ，有些不适合这句话本身的意思

2021-09-08 13:19 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +## 旧时 Web
```suggestion
## Web 的远古时代
```

2021-09-08 13:19 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +## 商业 Web
```suggestion
## Web 的商业时代
```

2021-09-08 13:19 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +所以网站变得更容易上瘾。公司开始创建自己的网站。就像每家公司和他们的狗都有一个登陆页面，如果你眯起眼睛，他们似乎都在使用相同的模板，标题相同，都是“自动化组织协作工作场所远程通信交付的多合一解决方案”，“用少于 100 倍的时间提高 10 倍的生产力！！！”，或“厕所......重新发明！”。除了这里和那里的一些文本、样式和图像之外，很难发现差异。这就像有人拿走了整个互联网，并从中消灭了所有的创
```suggestion
因此网站变得更加迷人。所有公司都开始创建自己的网站。最终每家公司甚至他们的狗都有一个登陆页面，如果你仔细观察，他们似乎都在使用相同的模板，甚至标题都相同，都是“自动化组织协作工作场所远程通信交付的多合一解决方案”，“用少于 100 倍的时间提高 10 倍的生产力！！！”，或“厕所......重新发明！”等等。它们之间除了一些文本、样式和图像之外，很难发现差异。这就像有人占领了整个互联网，同时消灭了所有的创造力和乐趣。
```

2021-09-08 15:48 UTC, KimYangOfCat reviewed
@lsvih 校对完毕

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +亲爱的读者，如果您还没有注意到，传统的桌面应用程序已经走向数字墓地。
```suggestion
亲爱的读者，如果您还没有注意到，传统的桌面应用程序已经在走向数字墓地的路上了。
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +移动应用具有“本机”的感觉，它们可以在您的主屏幕上显示、发送通知、访问相机、联系人、文件系统等。具有流畅的动画和手势。您在普通的 clicky 和 ​​tappy 网站上看不到的东西。
```suggestion
移动应用更具有“本机”的感觉，它们可以在您的主屏幕上显示、发送通知、访问相机、联系人、文件系统等。也具有流畅的动画和手势，以及你在普通的 clicky 和 ​​tappy 网站上看不到的东西。
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +当一家公司想要支持移动设备时，他们不会创建适合移动设备的 Web 应用程序，而是创建本机移动应用程序。为什么？因为 Web 无法访问与本机应用程序相同的 API 和功能，并且通常认为它的性能不佳，并且您将很难尝试实现跨浏览器工作且不适用的手势和动画不干扰设备默认手势，显然你不能向应用商店提交网站（或者你可以👀？）
```suggestion
当一家公司想要支持移动设备时，他们不会创建适合移动设备的 Web 应用程序，而是创建本机移动应用程序。为什么？因为 Web 无法访问与本机应用程序相同的 API 和功能，并且其通常被认为性能不好，同时你也很难实现能跨浏览器工作且不干扰设备默认手势的手势和动画，显然你也不能向应用商店提交一个网站（或者你可以试试👀 ？）
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +一些框架使您能够使用 [React Native](https://reactnative.dev/)等 Web 技术编写跨平台应用程序，它们主要允许您访问与本机应用程序相同的 API 和功能，尽管它们的性能较低。
```suggestion
 类似[React Native](https://reactnative.dev/) 的一些 Web 技术框架能够让你编写跨平台应用程序，尽管它们的性能较低，但它们能允许你访问与原生应用程序相同的 API 和功能。
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +一些公司已经采用了 React Native，例如 Facebook、Instagram、Discord、Tesla、Skype、Pinterest 和 Uber Eats。
```suggestion
有一些公司已经采用了 React Native，例如 Facebook、Instagram、Discord、Tesla、Skype、Pinterest 和 Uber Eats 等等。
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +但我相信有更好的东西即将出现，有一种网络应用程序可以运行并且感觉就像一个本机应用程序，它们被称为“渐进式网络应用程序”。它们是可安装的，可以访问 [诸如存储、相机、通知等 API]((https://whatwebcando.today/))。可以立即更新（与需要在应用商店中构建的原生应用不同），不必提交到应用商店，易于访问（URL 的强大功能），并且使用 [use-gestures](http
```suggestion
但我相信会有更好的东西即将出现，有一种 web 应用程序可以像一个原生应用程序一样运行，它们被称为“渐进式 web 应用程序”。它们是可安装的，可以访问 [诸如存储、相机、通知等 API]((https://whatwebcando.today/))，并且可以立即更新（与需要在应用商店中构建的原生应用不同），不必提交到应用商店，易于访问（URL 的强大功能），并且使用 [use-gestures](https://use-gesture.netlify.app/)、[react-spring](https://react-spring.io/) 和 [framer motion](https://www.framer.com/motion/) 等库，你可以轻松实现流畅的动画和手势（试用 [Bottom Sheet](https://zuwji.csb.app/)、[Multi-Gestures](https://rkgzi.csb.app/)、[Slide Show](https://v364z.csb.app/) 和 [App Store Like Cards](https://ecgc2.csb.app/) 手机上的演示）。
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +让我们希望 Apple 能够尽快添加更多的支持并解除它对 iOS 上 PWA 的一些限制🤞。
```suggestion
让我们期待 Apple 能够尽快添加更多的支持并解除它对 iOS 上 PWA 的一些限制🤞。
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +Google Play 商店和 Microsoft 商店已经允许将 PWA 提交到他们的市场。
```suggestion
Google Play 商店和 Microsoft 商店已经允许将 PWA 提交到他们的应用商店。
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +随着时间的推移，我预测更多的公司将转向 PWA，我们将看到它们与原生应用程序并存，直到有一天 PWA 成为标准（希望😁）然后我们会想知道为什么我们要构建相同的应用程序每个平台多次😲！
```suggestion
随着时间的推移，我预测更多的公司将转向 PWA，等到 PWA 成为标准的那一天，我们将看到它们与原生应用程序并存（希望😁），然后我们就会怀疑为什么我们要为了每个平台多次构建相同的应用程序😲！
```
> 然后我们会想知道为什么我们要构建相同的应用程序每个平台多次😲！

这是正常中文的语序吗？🥵

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +你可能想知道？网络是不是很慢，chrome 占用了我所有的 CPU 和 RAM，实际上网络并不适用于繁重的应用程序，但有了 [Web Assembly](https://webassembly.org/)，情况就不必再这样了。
```suggestion
你可能想知道？即使chrome 占用了我所有的 CPU 和 RAM，为什么 web 依旧很慢？事实上 web 并不适用于大型的应用程序，但有了 [Web Assembly](https://webassembly.org/)，情况有所不同了。
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +Web Assembly 允许您以接近机器代码的速度在 Web 上运行来自 [多种语言](https://github.com/appcypher/awesome-wasm-langs)（如 C++、Rust、Go、Java 等）的编译代码。这将为网络上的新型应用程序打开大门，例如：
```suggestion
Web Assembly 允许你以接近机器代码的速度在 Web 上运行来自 [多种语言](https://github.com/appcypher/awesome-wasm-langs)（如 C++、Rust、Go、Java 等）的编译代码。这将为 web 的新型应用程序打开大门，例如：
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +但是 3D 已经潜伏在网络中一段时间​​了，这不仅仅是出于美学原因。
```suggestion
但是 3D 已经在 web 中存在了一段时间​​了，这不仅仅是出于美学原因。
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +电子游戏一直存在于游戏机和 PC 上。网络只剩下迷你 Flash 游戏，当时网络还没有真正为视频游戏行业做好准备。
```suggestion
电子游戏一直存在于游戏机和 PC 上。web 只剩下小型 Flash 游戏，但那时 web 还没有真正为视频游戏行业做好准备。
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +[Unity 宣布它将支持 Web Assembly](https://blog.unity.com/technology/webassembly-is-here), 并且借助 [Three.js](https://threejs.org/), [Babylon](https://www.babylonjs.com/), [Play Canvas](https://playcanvas.com/
```suggestion
Unity 宣布它将借助 [Three.js](https://threejs.org/), [Babylon](https://www.babylonjs.com/), [Play Canvas](https://playcanvas.com/#!), 和 [RogueEngine](https://rogueengine.io/) 等工具[支持 Web Assembly](https://blog.unity.com/technology/webassembly-is-here), 在 Web 上运行游戏看起来有了一丝曙光。
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +网络是唯一向后兼容的平台，想象一下创建一个可以运行到互联网末日的游戏！
```suggestion
网络是唯一向后兼容的平台，想象一下，创建一个可以运行到互联网末日的游戏！
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +您可以在技术上在任何设备上运行您的游戏，无需将您的游戏移植到不同的控制台和架构，PC 游戏不再是 Windows 独有的。
```suggestion
技术层面来讲，你可以在任何设备上运行您的游戏，而无需将你的游戏移植到不同的控制台和架构，PC 游戏不再是 Windows 独有的。
```

2021-09-08 15:48 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +您可以通过代码拆分和延迟加载资产来使用网络流功能，用户可以立即玩和测试您的游戏（理论上）。
```suggestion
你可以通过代码拆分和延迟加载资源来使用 web 流功能，用户可以立即玩和测试你的游戏（理论上）。
```

2021-09-09 15:21 UTC, jaredliw requested changes
@Gesj-yean @lsvih 
校对完成
我挺认同 KimYangOfCat 的看法的，一些地方问题挺大，鉴于这篇文章有些”英文化“，翻译难度有些许的高，我就不吹毛求疵了，但标点符号、名词统一什么的麻烦注意一下。人家网站的名称也能搞成什么 nb 克拉斯的译文我也是醉了。不管怎样，整体翻译还是不错的。

这篇文章中的很多链接都能让人惊掉下巴，我觉得如果能以截图的形式放到文章中会大大加分
这里举一些例子：
![image](https://user-images.githubusercontent.com/57293776/132706750-b7d3c491-0d0f-438d-b276-b7f7be089bc3.png)
![image](https://user-images.githubusercontent.com/57293776/132707285-57374dc6-08b7-4ca1-bcd9-6d98975e2ca1.png)
![image](https://user-images.githubusercontent.com/57293776/132708177-246ae69f-48a1-43fb-bf0c-8e651b5c4784.png)
还有一个 windows xp 模拟器忘截屏了

2021-09-09 15:21 UTC, jaredliw commented on article/2021/the-future-of-the-web.md
> +- [pmndrs - 赛车游戏](https://racing.pmnd.rs/#)
```suggestion
- [pmndrs —— 赛车游戏](https://racing.pmnd.rs/#)
```

2021-09-09 15:21 UTC, jaredliw commented on article/2021/the-future-of-the-web.md
> +对此我说想象一下你的数据真正属于你的网络，你可以将它从一个应用程序转移到另一个应用程序，你不需要向应用程序提供你的电子邮件、密码、电话号码、地址、社交身份或你的照片要注册，您只需要您的虚拟密钥。想象一下互联网不是由数据饥渴的巨头运营，而是由我们所有人运营。想象一下真正的匿名性，您可以选择公开的内容和保密的内容，不再有中间人。
```suggestion
对此我说想象一下你的数据真正属于你的网络，你可以将它从一个应用程序转移到另一个应用程序。注册时，你不需要向应用程序提供你的电子邮件、密码、电话号码、地址、社交身份或你的照片。虚拟密钥足矣。想象一下互联网不是由数据饥渴的巨头运营，而是由我们所有人运营。想象一下真正的匿名性，你可以选择哪些内容公开，哪些内容保密，不再有中间人。
```

2021-09-09 15:21 UTC, jaredliw commented on article/2021/the-future-of-the-web.md
> +网络将是最终的操作系统，所有的连接，永远发展。
```suggestion
网络将是最终的操作系统，所有设备都连接到一起，永远发展。
```

2021-09-09 16:18 UTC, KimYangOfCat commented
@jaredliw 佩服，你可真的是太细了！哈哈哈😄

2021-09-09 16:26 UTC, KimYangOfCat commented on article/2021/the-future-of-the-web.md
> +网络是静态的，私人的，就好像是印刷时代的一部分被带到了网络上。然而我不得不说这既有点[古怪又十分有趣](https://www.spacejam.com/1996/)。
私人的这个翻译是我后改的，最开始翻译的是单人游戏，我一直都在找个词符合这个语境，又能表达 single 这个意思，始终想不到，不得不说，你这个 单机的 真的是非常贴切！赞

2021-09-10 01:01 UTC, Gesj-yean commented on article/2021/the-future-of-the-web.md
> +网络变得太商业化、太平庸、太……乏味了。
这里省略号应该用三个点表示就可以了，不用加空格吧

2021-09-10 01:03 UTC, Gesj-yean commented on article/2021/the-future-of-the-web.md
> +大多数互联网被 4-5 家公司（即 FAANG）垄断（Facebook、亚马逊、苹果、Netflix 和谷歌）。
确实更加清晰了

2021-09-10 01:24 UTC, Gesj-yean commented on article/2021/the-future-of-the-web.md
> +因此网站变得更加迷人。所有公司都开始创建自己的网站。最终每家公司甚至他们的狗都有一个登陆页面，如果你仔细观察，他们似乎都在使用相同的模板，甚至标题都相同，都是“自动化组织协作工作场所远程通信交付的多合一解决方案”，“用少于 100 倍的时间提高 10 倍的生产力！！！”，或“厕所......重新发明！”等等。它们之间除了一些文本、样式和图像之外，很难发现差异。这就像有人占领了整个互联网，同时消灭
网站变得更容易让人上瘾也很奇怪。这里改成 「因此搭建网站使人上瘾」吧。
「用 100 倍更少的时间提高 10 倍的生产力！」 -> 「减少 100 倍的时间提高 10 倍的生产力」这样比较好。
引号还是要用中文引号，不用改成英文。

2021-09-10 01:43 UTC, Gesj-yean commented on article/2021/the-future-of-the-web.md
> +- [发声音频计算](https://soundation.com/station/soundation-is-the-first-online-music-production-software-to-implement-webassembly-threads-gains-over-70-performance-improvement/)
这里感觉还是翻译一下比较好

2021-09-10 01:44 UTC, Gesj-yean commented on article/2021/the-future-of-the-web.md
> +- [Google Sketchup 3D 建模](https://madewithwebassembly.com/showcase/sketchup/)
[3D 建模 —— 谷歌的 Sketchup] -> [3D 建模 —— 由谷歌开发的 Sketchup] 也和前面的保持一致

2021-09-10 01:58 UTC, Gesj-yean commented on article/2021/the-future-of-the-web.md
> +- [月亮骑士（击败军刀克隆人）](https://moonrider.xyz/)
这个游戏介绍是玩家可选择扮演人类抵抗团军人或者反叛机器人，这两个角色都相应地配有各自的武器，玩家可以使用这些武器去痛打那些凶猛的外星生物、危险的机器人以及其他敌人们。

2021-09-10 02:04 UTC, Gesj-yean commented
感谢 @KimYangOfCat 和 @jaredliw 的校对。已经根据校对意见修改完成了哈。

2021-09-10 07:02 UTC, KimYangOfCat commented
@Gesj-yean 可以目前看来，很多前面提到的问题还是存在！！！
1. 关于 web 的翻译还是没有统一成 Web
2. 关于 you 的翻译还是没有统一成 你
3. 一些校对既没有采纳，也没有 resolve，也没有给出反对的理由
 ![image](https://user-images.githubusercontent.com/32960305/132813413-e9f29e61-38ba-4a75-95dc-fdfcdd150482.png)
？？？？？

2021-09-10 07:18 UTC, Gesj-yean commented on article/2021/the-future-of-the-web.md
> +你可能想知道？网络是不是很慢，chrome 占用了我所有的 CPU 和 RAM，实际上网络并不适用于繁重的应用程序，但有了 [Web Assembly](https://webassembly.org/)，情况就不必再这样了。
第二个引号应该是中文

2021-09-10 07:27 UTC, Gesj-yean commented
@KimYangOfCat 太感谢了。不好意思遗漏了部分校对信息，已经补上。并且统一了“web”和“你”的用法。

2021-09-10 11:05 UTC, lsvih approved these changes

2021-09-10 11:06 UTC, merged

2021-09-10 11:06 UTC, lsvih commented
本文翻译及校对积分增加一分

2021-09-10 11:06 UTC, lsvih commented
@Gesj-yean   已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-09-11 02:14 UTC, Gesj-yean commented
@lsvih 已经发布： https://juejin.cn/post/7006492657379704846

2021-09-11 03:25 UTC, lsvih commented
get