first draft
xitu/gold-miner pull request #9093
Opened 2021-09-10 15:58 UTC by zaviertang

译文翻译完成，resolve #9032 @lsvih

2021-09-11 03:02 UTC, jaredliw commented
@lsvih 校对认领

2021-09-11 03:25 UTC, lsvih commented
@jaredliw 好嘞

2021-09-11 07:21 UTC, jaredliw requested changes
@zaviertang 校对完成
译得很棒，语句通顺 👍🏼 👍🏼

2021-09-11 07:21 UTC, jaredliw commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +* 在上面 `for..in` 迭代的所有属性中不会显示我的自定义 Symbol 属性。如果你尝试访问类中这些作为调试数据的属性，这会派上用场，因为你知道它不会影响代码的正常运行。
```suggestion
* 在上面 `for...in` 迭代的所有属性中不会显示我的自定义 Symbol 属性。如果你尝试访问类中这些作为调试数据的属性，这会派上用场，因为你知道它不会影响代码的正常运行。
```

2021-09-11 07:21 UTC, jaredliw commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +就像上面提到的，Symbol 不是 JavaScript 最方便的特性，但也不是最差的。Symbol 成为标准的一部分是有充分理由的，现在你知道了它们的一些有趣的用例，考虑花时间使用并利用它们吧。
```suggestion
就像上面提到的，Symbol 不是 JavaScript 最丰富的特性，但也不是最差的。Symbol 成为标准的一部分是有充分理由的，现在你知道了它们的一些有趣的用例，考虑花时间利用它们吧。
```
richest feature => 最丰富的功能 != 最方便的
个人建议尽量跟着原句逐字翻译

2021-09-11 07:21 UTC, jaredliw commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
>  function myconsol_log(obj) {
```suggestion
function myconsole_log(obj) {
```

2021-09-11 07:21 UTC, jaredliw commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +那么这样一个你永远无法真正匹配的值有什么用呢？
```suggestion
那么这样一个你永远无法真正匹配的值有什么用呢？我的意思是，我不能实现：
```
别抛弃这句呀

2021-09-11 07:21 UTC, jaredliw commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +直到你认识到全局 Symbol 缓存后！
```suggestion
当你认识到全局 Symbol 缓存后你就不会那么觉得了！
```

2021-09-11 07:21 UTC, jaredliw commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +Symbol 的最后一个有趣的用例是向你的类和对象中添加属性，这些属性实际上不属于其”形状“的一部分。
```suggestion
Symbol 的最后一个有趣的用例是向你的类和对象中添加属性，这些属性实际上不属于其”结构“的一部分。
```
作者的 shape 表达的是整个类的结构，整个外貌
对于 shape，我觉得 外貌、形态、结构等 都是比较好的翻译选择

2021-09-11 07:21 UTC, jaredliw commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +解释一下：一个对象的“形状”是由它的属性决定的。将数据添加到对象而不影响其形状（其原始属性集）的唯一方法是将它们添加为 Symbol。这是因为这些类型的属性不会作为 `for..in` 循环的一部分出现，也不会作为调用 `Object.keys` 的结果出现。
```suggestion
解释一下：一个对象的“结构”是由它的属性决定的。将数据添加到对象而不影响其“结构”（其原始属性集）的唯一方法是将它们添加为 Symbol。这是因为这些类型的属性不会作为 `for...in` 循环的一部分出现，也不会作为调用 `Object.keys` 的结果出现。
```

2021-09-12 08:30 UTC, nia3y commented
@lsvih 校对认领

2021-09-12 08:55 UTC, lsvih commented
@nia3y 好的~

2021-09-12 09:46 UTC, nia3y reviewed
@zaviertang @lsvih 校对完成

2021-09-12 09:46 UTC, nia3y commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +如果你向一个开发者问：**”Symbol 有什么独特的特性？”**，他也许会回答：**“嗯，他是独一无二的”**。
```suggestion
String 问开发者：“Symbol 中的哪个特性是我 String 没有的？”。“额，Symbol 是独一无二的。”
```

2021-09-12 09:46 UTC, nia3y commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +这里的原始值是指字符串 `"foo"` 而不是 `a`。后者只是一个被赋值为原始值的变量。为什么我要在这里进行这样的区分呢？因为一般你不会直接地使用一个原始值，而是将它赋值给变量并赋予它含义。换句话说，数值 `2` 本身没有任何含义，但 `let double = 2;` 是有含义的。
```suggestion
这里的原始值是指字符串 `foo` 而不是 `a`。后者只是一个被赋值为原始值的变量。为什么我要在这里进行这样的区分呢？因为一般你不会直接地使用一个原始值，而是将它赋值给变量并赋予它含义。换句话说，数值 `2` 本身没有任何含义，但 `let double = 2;` 是有含义的。
```

2021-09-12 09:46 UTC, nia3y commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +另一个有趣的点是，在 JavaScript 中原始值是不可变更的。这意味着你永远不能修改数值 `2`。但实际上，你可以为变量重新赋值为其他（不可变更的）原始值。
```suggestion
另一个有趣的点是，在 JavaScript 中原始值是不可变更的。这意味着你永远不能修改数值 `2`。但实际上，你可以为变量**重新赋值**为其他的（不可变更的）原始值。
```

2021-09-12 09:46 UTC, nia3y commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +它还有一个额外的特征：Symbol 在全局是唯一的。
```suggestion
它还有一个额外的特征：Symbol 在脚本执行过程中是独一无二的。
```

2021-09-12 09:46 UTC, nia3y commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
>  console.log(obj[Symbol()]);
```suggestion
console.log(obj[Symbol()]); // undefined
```

2021-09-12 09:46 UTC, nia3y commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +你可以通过 `Symbol.for` 方法来创建 Symbol 值，而不是直接调用 `Symbol` 函数。
```suggestion
你可以通过 `Symbol.for` 方法来创建 Symbol，来代替直接调用 `Symbol` 函数。
```

2021-09-12 09:46 UTC, nia3y commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +第一次调用 `Symbol.for` 将会创建一个新的 Symbol 值，然后在第二次调用时将会返回它。这里就是 Symbol 偏离字符串的地方。显然，字符串 `"hello"` 和另一个字符串 `"hello"` 是相等的，但他们是不同的字符串。比如当我们：
```suggestion
第一次调用 `Symbol.for` 将会创建一个新的 Symbol 值，然后在第二次调用时将会取回它。这里就是 Symbol 和 String 不同的地方。显然，字符串 `"hello"` 和另一个字符串 `"hello"` 是相等的，但他们是不同的字符串。比如当我们：
```

2021-09-12 10:07 UTC, zaviertang commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +# JavaScript 最被误解的变量类型 Symbol
嗯，你是对的。（我大多数翻译偏意译，保证语句通顺不失原意即可，不太多纠结）

2021-09-12 10:39 UTC, zaviertang commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +如果你向一个开发者问：**”Symbol 有什么独特的特性？”**，他也许会回答：**“嗯，他是独一无二的”**。
这里我理解错了🤣

2021-09-12 10:42 UTC, zaviertang commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +我知道，这是一个糟糕的回答，但请和我一起来看看，可以吗？Symbol 是 JavaScript 奇怪语法之一，因为很少有人真正理解它，也不去使用它。
Symbol 是语法的一部分，特性是对语法的总结吧。但这里都称为特性也更好

2021-09-12 10:48 UTC, zaviertang commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +长话短说，Symbol 是一种新的原始数据类型，现在你可以像访问字符串、数值、布尔值、`undefined` 和 `null` 一样去访问它。
意思倒没有偏差，只是觉得 ”相当新“ 这样的描述有些怪

2021-09-12 10:50 UTC, zaviertang commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +这里的原始值是指字符串 `"foo"` 而不是 `a`。后者只是一个被赋值为原始值的变量。为什么我要在这里进行这样的区分呢？因为一般你不会直接地使用一个原始值，而是将它赋值给变量并赋予它含义。换句话说，数值 `2` 本身没有任何含义，但 `let double = 2;` 是有含义的。
`“foo"` 是字符串原始值，所以个人加上了双引号，区别于作为变量的 `a`

2021-09-12 10:54 UTC, zaviertang commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +它还有一个额外的特征：Symbol 在全局是唯一的。
“在全局”也许更合适，可理解为“全局作用域”

2021-09-12 10:55 UTC, zaviertang commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +它还有一个额外的特征：Symbol 在全局是唯一的。
个人认为 ”全局唯一“ 这样的说法在中文技术社区中也比较常见。

2021-09-12 11:08 UTC, zaviertang commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +那么这样一个你永远无法真正匹配的值有什么用呢？
直接翻译出来奇怪，所以去掉。同上，这里选择意译

2021-09-12 11:12 UTC, zaviertang commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +结果不是我们预期的。当然，你可以将 `Symbol` 保存到变量中，然后使用变量去访问唯一的属性值。但是你必须保存每个 Symbol 到变量中。实在的说，它像是字符串的一个变种，不是吗？
Symbol 是对作为对象 key 的字符串类型的补充，也不能称为”弱化“，Symbol 甚至比 String 类型更加复杂，这里依旧选择意译

2021-09-12 11:26 UTC, zaviertang commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +或者，如果你遇到一些边缘情况，例如可能需要进行一些数据处理以生成大型内存字典，或者你可能在内存有限的设备上使用 JavaScript，那么 Symbol 可能是维持内存利用率的好方法。
哈哈很到位，但大部分人不能理解“边缘设备”是什么，这里省略“边缘”，不会有偏差。

2021-09-12 11:36 UTC, zaviertang commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +Symbol 的最后一个有趣的用例是向你的类和对象中添加属性，这些属性实际上不属于其”形状“的一部分。
一般翻译为“结构”，我改一下

2021-09-12 11:54 UTC, lsvih commented on article/2021/javascript-symbols-the-most-misunderstood-feature-of-the-language.md
> +## Symbol 是什么?
```suggestion
## Symbol 是什么？
```

2021-09-12 11:54 UTC, lsvih commented
劳驾您加一下另一位校对者的信息哈~

2021-09-12 12:09 UTC, zaviertang commented
@jaredliw @nia3y 校对的非常严谨，感谢

2021-09-12 12:09 UTC, zaviertang commented
> 劳驾您加一下另一位校对者的信息哈~

已加

2021-09-13 01:00 UTC, lsvih approved these changes

2021-09-13 01:00 UTC, merged

2021-09-13 01:00 UTC, lsvih commented
@zaviertang  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2021-09-15 02:04 UTC, zaviertang commented
> @zaviertang 已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。
> 
> 掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
> 专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

https://juejin.cn/post/7007975053485113381/

2021-09-15 02:30 UTC, lsvih commented
get~