如何使用 Python 管道 Pipe 高效编码
xitu/gold-miner pull request #9180
Opened 2022-01-03 08:59 UTC by zenblofe

@lsvih 译文翻译完成，resolve #9165

2022-01-03 14:55 UTC, jaredliw commented
@lsvih 校对认领
（这篇文章和AI没关系。。）

2022-01-03 16:11 UTC, jaredliw reviewed
还没校对完 大致先这样吧 之后继续

2022-01-03 16:11 UTC, jaredliw commented on article/2021/pipe-operations-in-python.md
>  > * 原文作者：[Thuwarakesh Murallie](https://thuwarakesh.medium.com/)
## 文章中所有返回不可迭代对象的方法都已经deprecated了，建议修改
例子：
```python
result = [3, 4, 5, 3] | take_while(lambda x: x < 5) | as_list
```
建议修改成：
```python
result = list([3, 4, 5, 3] | take_while(lambda x: x < 5))
```

2022-01-03 16:11 UTC, jaredliw commented on article/2021/pipe-operations-in-python.md
> +作为一名有经验的数据科学家，我发现管道 Pipe 在大量日常任务中都非常有用。我们也可以用 Pandas 来完成大部分任务。然而，管道 Pipe 在提高代码可读性方面表现出色，即使是新手程序员也能理解这种转变。
```suggestion
作为一名执业数据科学家，我发现 Pipe 在大量日常任务中都非常有用。我们也可以用 Pandas 来完成大部分任务。然而，Pipe 在提高代码可读性方面表现出色，即使是新手程序员也能理解这种数据的转换操作。
```
对于practising，剑桥词典给的意思如下：
actively involved in a job

2022-01-04 03:07 UTC, zenblofe commented
@jaredliw 感谢校对！已做修改

2022-01-04 07:52 UTC, lsvih commented
@感谢校对

2022-01-04 08:19 UTC, jaredliw commented
@zenblofe 
我的代码修改建议和你改的是一回事吗 代码不熟悉的话还是建议别领了
算了 晚上我改吧 顺便补上剩余的校对

2022-01-05 12:25 UTC, Adolescent0 commented
@lsvih 认领校对

2022-01-05 13:30 UTC, lsvih commented
@Adolescent0  欢迎校对~

2022-01-07 09:19 UTC, Adolescent0 commented
@zenblofe @lsvih 校对完成

2022-01-07 09:36 UTC, zenblofe commented
@Adolescent0 直接在文章那里添加校对内容，我这没找到

2022-01-07 09:45 UTC, Adolescent0 commented
不好意思哦，我第一次搞这个。
麻烦问下，我是在那个Files changed 那个标签下面校对的 ，这样你没办法看到吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xitu/gold-miner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月7日(星期五) 下午5:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xitu/gold-miner] 如何使用 Python 管道 Pipe 高效编码 (PR #9180)





 
@Adolescent0 直接在文章那里添加校对内容，我这没找到
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2022-01-07 09:50 UTC, lsvih commented
@Adolescent0 完成后需要点右上角的 review changes，然后选择 comment 并提交，其他人才能看到~

2022-01-07 09:52 UTC, Adolescent0 reviewed
@zenblofe @lsvih 校对完成

2022-01-07 10:06 UTC, zenblofe commented
@Adolescent0 感谢校对
@lsvih 完成 2 次校对

2022-01-07 12:19 UTC, jaredliw commented on article/2021/pipe-operations-in-python.md
>  print(f"where: {result2}")
上方的代码改不了 就写这了
Line 212: `result = list([3, 4, 5, 3] | take_while(lambda x: x < 5))`
Line 216: `result2 = list([3, 4, 5, 3] | where(lambda x: x < 5))`

2022-01-07 14:15 UTC, zenblofe commented
@jaredliw 感谢校对！已做修改

2022-01-07 14:22 UTC, jaredliw requested changes

2022-01-07 14:22 UTC, jaredliw commented on article/2021/pipe-operations-in-python.md
> +result = [3, 4, 5, 3] | take_while(lambda x: x < 5)
```suggestion
result = list([3, 4, 5, 3] | take_while(lambda x: x < 5))
```
看走眼了吧

2022-01-07 14:22 UTC, jaredliw commented on article/2021/pipe-operations-in-python.md
> +result2 = [3, 4, 5, 3] | where(lambda x: x < 5)
```suggestion
result2 = list([3, 4, 5, 3] | where(lambda x: x < 5))
```
看走眼了吧

2022-01-07 14:38 UTC, zenblofe commented
@jaredliw 改好了

2022-01-08 09:46 UTC, lsvih approved these changes

2022-01-08 09:46 UTC, merged

2022-01-08 09:46 UTC, lsvih commented
@zenblofe  已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2022-01-09 04:07 UTC, zenblofe commented
@lsvih @jaredliw @Adolescent0 掘金文章地址 https://juejin.cn/post/7051051681357758494

2022-01-09 05:52 UTC, lsvih commented
好嘞