如何使用 Python 构建 GUI 程序
xitu/gold-miner pull request #9212
Opened 2022-01-14 17:21 UTC by YueYongDev

译文翻译完成，resolve #9203

2022-01-15 01:50 UTC, luochen1992 commented
校对认领

2022-01-15 02:42 UTC, luochen1992 requested changes
建议译者再仔细校对一下。

2022-01-15 02:42 UTC, luochen1992 commented on article/2022/how-to-build-gui-with-python.md
> +> 本教程使用一个名为 Tkinter 的 Python 库去构建一个应用程序，该应用可以基于最近的经期时间来推测即将到来的受孕期。
『受孕期』=>『预产期』

2022-01-15 02:42 UTC, luochen1992 commented on article/2022/how-to-build-gui-with-python.md
> +> 本教程使用一个名为 Tkinter 的 Python 库去构建一个应用程序，该应用可以基于最近的经期时间来推测即将到来的受孕期。
EDD 是预产期的意思，译者似乎以为是排卵期。

2022-01-15 02:42 UTC, luochen1992 commented on article/2022/how-to-build-gui-with-python.md
> +我最近在学习 GUI 编程，突然想到，如果可以将我所学内容实践到上述项目中会让整个过程变得有趣。该项目是要实现一个 GUI（图形用户界面）程序，当用户输入最近的经期时间（LMP）时计算出他们的易孕期（EDD）。我使用 Tkinter 模块构建了这个程序。
LMP 翻译成最近一次月经其实也可以，但是“末次月经”更准确一些。

2022-01-15 02:42 UTC, luochen1992 commented on article/2022/how-to-build-gui-with-python.md
> +本文，我将会采用持续开发的方式分阶段构建程序，不断地为应用添加代码，然后对其进行测试。这几个阶段分别是：
『持续开发的方式』=>『增量开发』

2022-01-15 05:48 UTC, Liang2028 commented
校对认领

2022-01-15 05:51 UTC, lsvih commented
@Liang2028 好的~

2022-01-15 09:54 UTC, Liang2028 reviewed
预产期（expected date of delivery）

2022-01-15 09:55 UTC, Liang2028 commented
@lsvih 校对完成

2022-01-16 12:48 UTC, YueYongDev commented
@lsvih 已根据校对意见更新内容

2022-01-18 04:24 UTC, lsvih approved these changes
LGTM

2022-01-18 04:24 UTC, merged

2022-01-18 04:24 UTC, lsvih commented
@YueYongDev   已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2022-01-21 14:15 UTC, YueYongDev commented
@lsvih  已经发布到掘金了
https://juejin.cn/post/7055662437315379231/

2022-01-24 11:08 UTC, lsvih commented
好嘞