Express vs. http - API 基准测试 v2
xitu/gold-miner pull request #9325
Opened 2022-05-03 16:58 UTC by finalwhy

译文翻译完成，resolve #7492
完成翻译精修 @lsvih

2022-05-26 05:26 UTC, lsvih commented
麻烦您加一下上一版#7534 中的校对名单哈，ghost 不用加~

2022-05-27 16:09 UTC, finalwhy commented
> 麻烦您加一下上一版#7534 中的校对名单哈，ghost 不用加~

已加

2022-06-10 09:07 UTC, jaredliw commented
@lsvih 校对认领

2022-06-10 09:16 UTC, lsvih commented
@jaredliw 好嘞

2022-06-15 08:16 UTC, jaredliw requested changes
@finalwhy 校对完成
不好意思 来迟了 最近忒忙

2022-06-15 08:16 UTC, jaredliw commented on article/2020/i-built-the-same-api-with-without-express-here-are-the-differences.md
> +我创建了两个相同的 API， 一个使用 Express，一个不使用。你可以在第一个提示处看到以下代码。
```suggestion
我创建了两个相同的 API，一个使用 Express，一个不使用，你可以在下面看到相关代码。但在此之前，我有一个小小的提示。
```
这里的tip指的是关闭 x-powered-by

2022-06-24 14:09 UTC, finalwhy commented on article/2020/i-built-the-same-api-with-without-express-here-are-the-differences.md
> +诚然，使用 Express.js 通常都会更愉快，当我学习 Node.js 的时候便直接使用 Express.js。在做这个实验之前，我写的任何东西都离不开 Express.js。
```suggestion
诚然，使用 Express.js 通常都会更愉快，当我开始学习 Node.js 的时候是从 Express.js 入手。（甚至于）在做这个实验之前，我写的任何东西都离不开 Express.js。
```

2022-06-24 14:28 UTC, finalwhy commented on article/2020/i-built-the-same-api-with-without-express-here-are-the-differences.md
> +在如此短的时间发送 10000 个请求给服务器是一个不实际的情况 — 当然，Express 的响应时间确实更高，但在正确情况下，这不会为任何人造成问题。
```suggestion
在如此短的时间发送 10000 个请求给服务器是一个不切实际的应用场景 — 当然，Express 的响应时间确实更高，但在正确情况下，这不会为任何人造成问题。
```

2022-06-24 14:31 UTC, finalwhy commented
@lsvih 校对意见已合并

2022-06-25 06:51 UTC, lsvih approved these changes

2022-06-25 06:51 UTC, merged

2022-06-25 06:51 UTC, lsvih commented
@finalwhy   已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2022-06-26 15:18 UTC, finalwhy commented
@lsvih [文章](https://juejin.cn/post/7113566528519274533)已发布

2022-06-27 02:29 UTC, lsvih commented
收到~