finish translating SwiftUI in 2021
xitu/gold-miner pull request #9392
Opened 2022-08-23 03:21 UTC by earthaYan

译文翻译完成，resolve #9065

2022-08-23 09:08 UTC, Lokfar commented
校对认领@lsvih

2022-08-23 10:42 UTC, Lokfar reviewed
整体翻译良好，译者的主要问题在于ios开发专业词汇的不熟悉导致了一些翻译上的错误。除此之外我也提供了一些更加偏向意译的译文，译者可以酌情采纳。

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +你可以把 SwiftUI 当作一个 UI 工具箱，这个工具箱提供了开发专业 app 需要的所有构建块。如果你熟悉 CSS 转场的话，　SwiftUI 也有它自己的版本，可以轻松创建优雅的交互。声明式语法的魅力在于 “just work”， 这看上去像魔法一样，但是也有不好的一面，我之后将会介绍。
关于“just work"的翻译有待商榷。我认为此处作者意在强调 swiftui声明式编程的特点，即让计算机明白目标而非流程

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +如果你熟悉 React的话，SwiftUI 也是一样的。当你监听整个 UI “react”，动画和所有一切的时候，你只需要修改 `@State` 和 `@Binding` 以及 `@Published` 属性，而不是使用回调地狱。充分利用 `Combine` 和`ObservableObject` 以及 `@StateObject` 的能力。这方面是和 UIKit 最酷的区别之一，强大到不可思议
```suggestion
如果你熟悉 React的话，SwiftUI 在这一点上完全类似。当你监听整个 UI 的”反应“，动画和所有一切的时候，你只需要修改 `@State` 和 `@Binding` 以及 `@Published` 属性，而不是使用多达几十层的嵌套回调函数。使用SwiftUI，你可以体会到 `Combine` 、`ObservableObject` 以及 `@StateObject` 的强大。这方面是SwiftUI和 UIKit 最酷的区别之一，强大到不可思议。
```

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +## 坏处
```suggestion
## 劣势
```

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +这些桥是弥补 SwiftUI 功能缺失的权宜之计，但并不是一直天衣无缝。而且，尽管 SwiftUI 的跨平台承诺很好，但是如果某些功能不可用的话，你仍然需要为 iOS 和 Mac 再次实现桥接代码。
```suggestion
这些协议是弥补 SwiftUI 功能缺失的权宜之计，但并不是一直天衣无缝。而且，尽管 SwiftUI 的跨平台承诺很好，但是如果某些功能不可用的话，你仍然需要为ios和Mac分别实现协议代码。
```

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +使用 `UIViewRepresentable` `UIViewControllerRepresentable` 和 `UIHostingController` 可以解决这一问题。前两个让你可以在 SwiftUI 视图层中嵌入 UIKit 视图和控制器。最后一个可以让你在 UIKit 中嵌入 SwiftUI 视图。在 Mac 开发中也存在这三者 (`NSViewRepresentable`等)。
`UIViewRepresentable` 等是swiftUI中的协议

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +使用 `UIViewRepresentable` `UIViewControllerRepresentable` 和 `UIHostingController` 可以解决这一问题。前两个让你可以在 SwiftUI 视图层中嵌入 UIKit 视图和控制器。最后一个可以让你在 UIKit 中嵌入 SwiftUI 视图。在 Mac 开发中也存在这三者 (`NSViewRepresentable`等)。
```suggestion
使用 `UIViewRepresentable` 、`UIViewControllerRepresentable` 和 `UIHostingController` 协议可以解决这一问题。前两个让你可以在 SwiftUI 视图层中嵌入 UIKit 视图和控制器。最后一个可以让你在 UIKit 中嵌入 SwiftUI 视图。在 Mac 开发中也存在类似的三种协议 (`NSViewRepresentable`等)。
```

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +如果你想在隐藏导航栏的同时仍然支持滑动手势，这是不可能的。我最终参考一些找到的代码创建了一个 [UINavigationController 包装器](https://gist.github.com/chrysb/d7d85e20d8c94fd3e0b753a4abd1c941)。尽管可以起作用，但这不是一个长远的解决方案。
wrapper应该可以作为一个专有名词不翻译

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +如果你想在隐藏导航栏的同时仍然支持滑动手势，这是不可能的。我最终参考一些找到的代码创建了一个 [UINavigationController 包装器](https://gist.github.com/chrysb/d7d85e20d8c94fd3e0b753a4abd1c941)。尽管可以起作用，但这不是一个长远的解决方案。
```suggestion
如果你想在隐藏导航栏的同时仍然支持滑动手势，这是不可能的。我最终参考一些找到的代码创建了一个 [UINavigationController wrapper](https://gist.github.com/chrysb/d7d85e20d8c94fd3e0b753a4abd1c941)。尽管可以起作用，但这不是一个长远的解决方案。
```

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +当你想使用编程式导航的时候，`NavigationLink` 是一种时髦的解决方案。这里有一个[有趣的讨论](https://forums.swift.org/t/implementing-complex-navigation-stack-in-swiftui-and-the-composable-architecture/39352)。
```suggestion
当你想使用编程式导航的时候，`NavigationLink` 是一种流行的解决方案。这里有一个[有趣的讨论](https://forums.swift.org/t/implementing-complex-navigation-stack-in-swiftui-and-the-composable-architecture/39352)。
```

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +`TextField` 和 `TextEditor` 现在都太简单了，最终你还是会退回到 UIKit。所以我不得不为 `UITextField` 和 `UITextView` 构建自己的 `UIViewRepresentable`(自动增长支持)。要点如下：
```suggestion
`TextField` 和 `TextEditor` 现在都太简单了，最终你还是会退回到 UIKit。所以我不得不为 `UITextField` 和 `UITextView` 构建自己的 `UIViewRepresentable`协议(以实现文本行数的自动增加)。要点如下：
```

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +`TextField` 和 `TextEditor` 现在都太简单了，最终你还是会退回到 UIKit。所以我不得不为 `UITextField` 和 `UITextView` 构建自己的 `UIViewRepresentable`(自动增长支持)。要点如下：
要点如下后是否缺少了文本

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +我可能错了，但是 Share Extensions 仍然使用 UIKit。我通过 `UIHostingController` 用 SwiftUI 构建了一个分享扩展，当分享扩展加载完毕后，有一个非常明显的延迟，用户体验较差。你可以尝试通过在视图中添加动画去掩饰，但是仍然有 500 ms 左右的延迟。
```suggestion
我可能错了，但是 我在构建Share Extensions 时仍然使用了 UIKit。我通过 `UIHostingController` 用 SwiftUI 构建了一个分享扩展，当分享扩展加载完毕后，有一个非常明显的延迟，用户体验较差。你可以尝试通过在视图中添加动画去掩饰，但是仍然有 500 ms 左右的延迟。
```

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +## 丑处
```suggestion
## 缺陷
```

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +## 定案
```suggestion
## 结论
```

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +SwiftUI 已经为简单的应用程序做好了准备，但是在写这篇文章的时候 (iOS 15, beta 4)，我不认为它已经适合复杂应用程序的生产环境，主要是由于`ScrollViews` 的问题和对 `UIViewRepresentable` 的严重依赖。我很遗憾。尤其是像即时通信产品，新闻订阅，以及严重依赖复杂视图或者想要创建手势驱动的定制体验产品，目前还不适合使用 SwiftUI。
```suggestion
SwiftUI 已经为简单的应用程序做好了准备，但是在写这篇文章的时候 (iOS 15, beta 4)，我不认为它已经适合复杂应用程序的生产环境，主要是由于`ScrollViews` 的问题和对 `UIViewRepresentable` 的严重依赖。我很遗憾，尤其是像即时通信产品，新闻订阅，以及严重依赖复杂视图或者想要创建手势驱动的定制体验产品，目前还不适合使用 SwiftUI。
```

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +SwiftUI 会兼容 UIKit 么？ 如果这样的话，我们可能需要 3-5 年的时间来移植所有必要的 UIKit api。如果不是，那么你总是能够下拉到　UIKit　并用SwiftUI包装它。
```suggestion
SwiftUI 会兼容 UIKit 么？ 如果这样的话，我们可能需要等待 SwiftUI 使用3-5 年的时间来移植所有必要的 UIKit api。如果SwiftUI不准备兼容UIkit，那你也能通过SwiftUI封装的方式使用UIKit。
```

2022-08-23 10:42 UTC, Lokfar commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +我好奇的是 Apple 会在 SwiftUI 上投入多少。他们是否有让所有的开发者采用 SwiftUI 的长期计划，或者是另一个界面构建器？ 我希望不是。希望他们能全心投入 SwiftUI，因为它的前景是非常令人惊讶的。
```suggestion
我好奇的是 Apple 会在 SwiftUI 上投入多少。他们是否有让所有的开发者采用 SwiftUI 的长期计划，或者说SwiftUI只是另一个界面构建器而已？ 我希望不是，我希望他们能全心投入 SwiftUI，因为它的前景是非常诱人的。
```

2022-08-23 10:43 UTC, Lokfar commented
校对完成@earthaYan@lsvih

2022-08-24 12:36 UTC, earthaYan commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +`TextField` 和 `TextEditor` 现在都太简单了，最终你还是会退回到 UIKit。所以我不得不为 `UITextField` 和 `UITextView` 构建自己的 `UIViewRepresentable`(自动增长支持)。要点如下：
缺失，medium上的原文下的评论中有提出，但是尚未补充

2022-09-01 04:14 UTC, earthaYan commented
@lsvih @Lokfar 已按照校对意见修改结束

2022-09-01 07:02 UTC, lsvih commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +你可以把 SwiftUI 当作一个 UI 工具箱，这个工具箱提供了开发专业 app 需要的所有构建块。另外，如果你熟悉 CSS 的Transition属性，你会发现SwiftUI也有一套类似的方法，可以轻松创建优雅的交互过程。声明式语法的魅力在于你只需要描述你需要什么样的效果，效果就实现了，这看上去像魔法一样，但是也有不好的一面，我之后将会介绍。
中英文间需要空格

2022-09-01 07:02 UTC, lsvih commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
>  > * 校对者：
请加上校对者的信息~

2022-09-01 09:17 UTC, earthaYan commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +你可以把 SwiftUI 当作一个 UI 工具箱，这个工具箱提供了开发专业 app 需要的所有构建块。另外，如果你熟悉 CSS 的Transition属性，你会发现SwiftUI也有一套类似的方法，可以轻松创建优雅的交互过程。声明式语法的魅力在于你只需要描述你需要什么样的效果，效果就实现了，这看上去像魔法一样，但是也有不好的一面，我之后将会介绍。
已修改

2022-09-01 09:17 UTC, earthaYan commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
>  > * 校对者：
已添加

2022-09-02 14:47 UTC, jaredliw requested changes

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +> 生产环境使用 SwiftUI？**仍然不可行。**
```suggestion
> 在生产环境使用 SwiftUI？**仍然不可行。**
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +![由 [Maxwell Nelson](https://unsplash.com/@maxcodes？utm_source=medium&utm_medium=referral) 在 [Unsplash](https://unsplash.com？utm_source=medium&utm_medium=referral) 发布](https://cdn-images-1.medium.com
```suggestion
![由 [Maxwell Nelson](https://unsplash.com/@maxcodes?utm_source=medium&utm_medium=referral) 在 [Unsplash](https://unsplash.com?utm_source=medium&utm_medium=referral) 发布](https://cdn-images-1.medium.com/max/12000/0*Wexfei50ZXms6ocU)
```
链接测试：
由 [Maxwell Nelson](https://unsplash.com/@maxcodes?utm_source=medium&utm_medium=referral) 在 [Unsplash](https://unsplash.com?utm_source=medium&utm_medium=referral) 发布

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +## SwfitUI的优势
```suggestion
## SwfitUI 的优势
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +使用 `addSubview` 和 `sizeForItemAtIndexPath` ，小心翼翼地计算控件的大小与位置，应对烦人的约束问题，手动构建视图层次结构，这样的日子已经一去不复返了。SwiftUI 的声明式和响应式设计模式使得创建响应式布局和 React 一样简单，同时它还背靠 Apple 强大的 UIKit。用它构建、启动并运行视图快到不可思议。
```suggestion
使用 `addSubview` 和 `sizeForItemAtIndexPath`，小心翼翼地计算控件的大小与位置，应对烦人的约束问题，手动构建视图层次结构，这样的日子已经一去不复返了。SwiftUI 的声明式和响应式设计模式使得创建响应式布局和 React 一样简单，同时它还背靠 Apple 强大的 UIKit。用它构建、启动并运行视图快到不可思议。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +我最兴奋的事情就是只需要编写一次 SwiftUI 代码，就可以在 iOS (iPhone 和 iPad)，WatchOS, 和 macOS 上使用。必须同时开发和维护 Android 和 Windows 各自的代码库已经很困难了，所以在减少不同代码库的数量这方面，每一个小的改变都很有帮助。当然还是有一些缺点，我将会在 “坏处”  章节分享。
```suggestion
我最兴奋的事情就是只需要编写一次 SwiftUI 代码，就可以在 iOS (iPhone 和 iPad)，WatchOS 和 macOS 上使用。同时开发和维护 Android 和 Windows 各自的代码库已经很困难了，所以在减少不同代码库的数量这方面，每一个小的改变都很有帮助。当然还是有一些缺点，我将会在 “劣势”  章节分享。
```
章节名称已经从 “坏处” 改成 “劣势” 了

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +你可以把 SwiftUI 当作一个 UI 工具箱，这个工具箱提供了开发专业 app 需要的所有构建块。另外，如果你熟悉 CSS 的Transition属性，你会发现 SwiftUI 也有一套类似的方法，可以轻松创建优雅的交互过程。声明式语法的魅力在于你只需要描述你需要什么样的效果，效果就实现了，这看上去像魔法一样，但是也有不好的一面，我之后将会介绍。
```suggestion
你可以把 SwiftUI 当作一个 UI 工具箱，这个工具箱提供了开发专业应用程序所需的所有构建块。另外，如果你熟悉 CSS 的 Transition 属性，你会发现 SwiftUI 也有一套类似的方法，可以轻松创建优雅的交互过程。声明式语法的魅力在于你只需要描述你需要什么样的效果，效果就实现了，这看上去像魔法一样，但是也有不好的一面，我之后将会介绍。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +如果你熟悉 React的话，SwiftUI 在这一点上完全类似。当你监听整个 UI 的”反应“，动画和所有一切的时候，你只需要修改 `@State` 和 `@Binding` 以及 `@Published` 属性，而不是使用多达几十层的嵌套回调函数。使用SwiftUI，你可以体会到 `Combine` 、`ObservableObject` 以及 `@StateObject` 的强大。这方面是S
```suggestion
如果你熟悉 React 的话，SwiftUI 在这一点上完全类似。当你监听整个 UI 的”反应“，动画和所有一切的时候，你只需要修改 `@State` 和 `@Binding` 以及 `@Published` 属性，而不是使用多达几十层的嵌套回调函数。使用 SwiftUI，你可以体会到 `Combine` 、`ObservableObject` 以及 `@StateObject` 的强大。这方面是 SwiftUI 和 UIKit 最酷的区别之一，强大到不可思议。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +SwiftUI 有许多组件缺失，不完整或者过于简单，我将在下面详细介绍其中一部分。
```suggestion
在 SwiftUI 中有许多缺失、不完整或者过于简单的组件，我将在下面详细介绍其中一部分。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +使用 `UIViewRepresentable` 、`UIViewControllerRepresentable` 和 `UIHostingController` 协议可以解决这一问题。前两个让你可以在 SwiftUI 视图层中嵌入 UIKit 视图和控制器。最后一个可以让你在 UIKit 中嵌入 SwiftUI 视图。在 Mac 开发中也存在类似的三种协议 (`NSViewRepresenta
```suggestion
使用 `UIViewRepresentable`、`UIViewControllerRepresentable` 和 `UIHostingController` 协议可以解决这一问题。前两个让你可以在 SwiftUI 视图层中嵌入 UIKit 视图和控制器。最后一个可以让你在 UIKit 中嵌入 SwiftUI 视图。在 Mac 开发中也存在类似的三种协议 (`NSViewRepresentable` 等)。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +如果你想在隐藏导航栏的同时仍然支持滑动手势，这是不可能的。我最终参考一些找到的代码创建了一个 [UINavigationController wrapper](https://gist.github.com/chrysb/d7d85e20d8c94fd3e0b753a4abd1c941)。尽管可以起作用，但这不是一个长远的解决方案。
```suggestion
如果你想在隐藏导航栏的同时仍然支持滑动手势，这是不可能的。我最终参考一些找到的代码创建了一个 [UINavigationController 的包装器](https://gist.github.com/chrysb/d7d85e20d8c94fd3e0b753a4abd1c941)。尽管它可以起到作用，但这不是一个长远的解决方案。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +如果你想要在 iPad 上拥有一个 SplitView，目前还不能以纵向模式同时展示主视图和详情视图。他们选择用一个简陋的按钮展示默认关闭的抽屉。显然，你可以通过添加 padding 来解决这个问题，它可以突出显示你在使用 SwiftUI 时必须做的事情。
```suggestion
如果你想要在 iPad 上拥有一个 SplitView，但目前你还不能以纵向模式同时展示主视图和详情视图。他们选择用一个简陋的按钮展示默认关闭的抽屉。显然，你可以通过添加 padding 来解决这个问题，它可以突出显示你在使用 SwiftUI 时必须做的事情。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +`TextField` 和 `TextEditor` 现在都太简单了，最终你还是会退回到 UIKit。所以我不得不为 `UITextField` 和 `UITextView` 构建自己的 `UIViewRepresentable` 协议(以实现文本行数的自动增加))。要点如下：
```suggestion
`TextField` 和 `TextEditor` 现在都太简单了，最终你还是会退回到 UIKit。所以我不得不为 `UITextField` 和 `UITextView` 构建自己的 `UIViewRepresentable` 协议（以实现文本行数的自动增加）。
```
Gist 链接作者，最后一句我删除了

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +> 编译器不能在合理时间内对表达式进行类型检查……
```suggestion
> The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions.
```
error 不必翻译
我贴了个完整版的error

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +这个问题已经多次拖慢进度。我已经很擅长注释代码并定位到引起问题的那一行，但是2021年了还在用这种方法调试代码感觉非常落后。
```suggestion
这个问题已经多次拖慢进度。由于这个问题，我已经很擅长注释代码定位到引起问题的那一行，但是 2021 年了还在用这种方法调试代码感觉非常落后。
```
强调下负面的“擅长”

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
>  ### 5. matchedGeometryEffect
```suggestion
### 5. `matchedGeometryEffect`
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +我一直想让它起作用。但最终还是放弃了，因为它并不完美并且当你在包含大量列表项的 `List` 或 `ScrollView` 中使用时会导致项目瘫痪。我只推荐在同一视图中使用这个做简单的转换过渡。当你在多个不同的视图中共享一个命名空间的时候，包括转场期间的视图剪裁在内的事情就会开始变得奇怪。
```suggestion
我一直想让它起作用。但最终还是放弃了，因为它并不完美。此外，在包含大量列表项的 `List` 或 `ScrollView` 中使用它会导致项目瘫痪。我只推荐在同一视图中使用这个做简单的转换过渡。当你在多个不同的视图中共享一个命名空间的时候（包括转场期间的视图剪裁在内），事情就会开始变得奇怪。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +### 6. 手势限制
```suggestion
### 6. 对手势的支持有限
```
啥玩意

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +SwiftUI 提供了一系列新的手势(即 `DragGesture`，`LongPressGesture`)，这些手势可以通过像 `tapGesture` 和 `longPressGesture` 这样的 `gesture` 修饰符被添加到视图中。他们都能正常工作，除非你想要做更复杂的交互。
```suggestion
SwiftUI 提供了一系列新的手势（即 `DragGesture` 和 `LongPressGesture`）。这些手势可以通过 `gesture` 修饰符（如 `tapGesture` 和 `longPressGesture`）添加到视图中。它们都能正常工作，除非你想要做更复杂的交互。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +### 7. 分享扩展中的SwiftUI
```suggestion
### 7. 分享扩展中的 SwiftUI
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +比如，`DragGesture` 和 `ScrollView` 交互就不是很好。即使有了 `simultaneousGesture` 修饰符，在 ScrollView 中放一个 `DragGesture` 还是会阻止滚动。在其他情况下，拖动手势可以在没有任何通知的情况下被取消，使得手势处于不完整状态。
```suggestion
比如，`DragGesture` 和 `ScrollView` 交互就不是很好。即使有了 `simultaneousGesture` 修饰符，在 `ScrollView` 中放一个 `DragGesture` 还是会阻止滚动。在其他情况下，拖动手势可以在没有任何通知的情况下被取消，使得手势处于不完整状态。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +* `UIVisualEffectsView` 会导致滚动延迟 (h/t @[AlanPegoli](https://twitter.com/alanpegoli？lang=en))
```suggestion
* `UIVisualEffectsView` 会导致滚动延迟（来源于推特：@[AlanPegoli](https://twitter.com/alanpegoli?lang=en)）
```
![image](https://user-images.githubusercontent.com/57293776/188170889-7885c106-2a98-439e-b868-5bd20cedd8f1.png)

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
>  ### 1. ScrollView
```suggestion
### 1. `ScrollView`
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +这是迄今为止最大的缺点之一。任何一个构建过定制化 iOS 应用的人都知道我们有多依赖 ScrollView 去支持交互。
```suggestion
这是迄今为止最大的缺点之一。任何一个构建过定制化 iOS 应用的人都知道我们有多依赖 `ScrollView` 去支持交互。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +* **主要的障碍:**  视图中的 `LazyVStack` 导致[卡顿、抖动和一些意外的行为](https://stackoverflow.com/questions/66523786/swiftui-putting-a-lazyvstack-or-lazyhstack-in-a-scrollview-causes-stuttering-a/67895804)。LazyVStacks 对于需
```suggestion
* **主要的障碍**：视图中的 `LazyVStack` 导致[卡顿、抖动和一些意外的行为](https://stackoverflow.com/questions/66523786/swiftui-putting-a-lazyvstack-or-lazyhstack-in-a-scrollview-causes-stuttering-a/67895804)。`LazyVStack` 对于需要滚动的混合内容（如新闻提要）的长列表至关重要。**仅凭这一点，SwiftUI 就还没准备好投入生产环境：** Apple 已经证实，这是 SwiftUI 自身的漏洞。尚未清楚他们什么时候会修复，但是一旦修复了，这将是一个巨大的胜利。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +* **滚动状态:** 原生不支持解析滚动的状态 (滚动视图是否正在被拖拽？ 滚动？ 偏移多少？)。尽管有一些解决方案，但是还是很繁琐且不稳定。
```suggestion
* **滚动状态**：原生不支持解析滚动的状态（滚动视图是否正在被拖拽？滚动？偏移多少？）。尽管有一些解决方案，但是还是很繁琐且不稳定。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +* **性能:** 使用 `List` 是性能最好的，并且避免了 `LazyVStack` 的卡顿问题，但由于转换的工作方式，它仍然不适合显示可变大小的内容。例如，在构建聊天视图时，其过渡很奇怪，会裁剪子视图，并且您无法控制插入动画样式。
```suggestion
* **性能**：使用 `List` 是性能最好的，并且避免了 `LazyVStack` 的卡顿问题，但由于工作方式的转换，它仍然不适合显示可变大小的内容。例如，在构建聊天视图时，其过渡很奇怪，会裁剪子视图，并且无法控制插入的动画样式。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +毫无疑问我觉得应该学习 SwiftUI ，自己去理解它，并享受乐趣。但是先别急着全盘接受。
```suggestion
毫无疑问我觉得应该学习 SwiftUI ，自己去理解它，并享受乐趣。但是先别急着全盘采用。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +SwiftUI 已经为简单的应用程序做好了准备，但是在写这篇文章的时候 (iOS 15, beta 4)，我不认为它已经适合复杂应用程序的生产环境，主要是由于`ScrollViews` 的问题和对 `UIViewRepresentable` 的严重依赖。我很遗憾，尤其是像即时通信产品，新闻订阅，以及严重依赖复杂视图或者想要创建手势驱动的定制体验产品，目前还不适合使用 SwiftUI。
```suggestion
SwiftUI 已经为简单的应用程序做好了准备，但是在写这篇文章的时候（iOS 15，beta 4 版本），我不认为它已经适合复杂应用程序的生产环境，主要是由于 `ScrollView` 的问题和对 `UIViewRepresentable` 的严重依赖。我很遗憾，尤其是像即时通信产品，新闻摘要，以及严重依赖复杂视图或者想要创建手势驱动的定制体验产品，目前还不适合使用 SwiftUI。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +如果你想要精细的控制和无限的可能性，我建议在可预见的未来坚持使用 UIKit。 你可以在一些视图（类似设置分页）里通过使用 `UIHostingController`包裹 SwiftUI 视图获得 SwiftUI 的好处。
```suggestion
如果你想要精细的控制和无限的可能性，我建议在可预见的未来坚持使用 UIKit。你可以在一些视图（如设置页）里通过使用 `UIHostingController` 包装 SwiftUI 视图以获得 SwiftUI 的好处。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +* [Is SwiftUI Ready？](https://www.jessesquires.com/blog/2021/07/01/is-swiftui-ready/)
```suggestion
* [SwiftUI 准备好了吗？](https://www.jessesquires.com/blog/2021/07/01/is-swiftui-ready/)
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
>  * [SwiftUI Drawbacks: Why SwiftUI Is Not Ready for Production Yet](https://www.iosapptemplates.com/blog/swiftui/swiftui-drawbacks)
```suggestion
* [SwiftUI 的缺点：为什么 SwiftUI 还没有准备好投入生产？](https://www.iosapptemplates.com/blog/swiftui/swiftui-drawbacks)
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
>  * [My takeaway from working with SwiftUI](https://link.medium.com/isXKLhaaCib)
```suggestion
* [使用 SwiftUI 的收获](https://link.medium.com/isXKLhaaCib)
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +SwiftUI 会兼容 UIKit 么？ 如果这样的话，我们可能需要等待 SwiftUI 使用 3-5 年的时间来移植所有必要的 UIKit api。如果 SwiftUI 不准备兼容  UIkit，那你也能通过 SwiftUI 封装的方式使用 UIKit。
```suggestion
SwiftUI 会兼容 UIKit 么？如果这样的话，我们可能需要等待 SwiftUI 使用 3-5 年的时间来移植所有必要的 UIKit API。如果 SwiftUI 不准备兼容 UIkit，那你也能通过 SwiftUI 封装的方式使用 UIKit。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +我好奇的是 Apple 会在 SwiftUI 上投入多少。他们是否有让所有的开发者采用 SwiftUI 的长期计划，或者说SwiftUI只是另一个界面构建器而已？ 我希望不是，我希望他们能全心投入 SwiftUI，因为它的前景是非常诱人的。
```suggestion
我好奇的是 Apple 会在 SwiftUI 上投入多少。他们是否有让所有的开发者采用 SwiftUI 的长期计划，或者说 SwiftUI 只是另一个界面构建器而已？我希望不是，也希望他们能全心投入 SwiftUI，因为它的前景是非常诱人的。
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +* **Paging:** 原生不支持分页滚动视图。所以忘记类似可滑动的媒体库吧（但是如果你想要关闭一些东西的时候，可以使用 `[SwiftUIPager](https://github.com/fermoya/SwiftUIPager)`）。在技术上你可以使用  `TabView` 加 `PageTabViewStyle`，但是我认为它更适合少部分的一些元素，而不是大的数据集。
```suggestion
* **分页**：原生不支持分页滚动视图。所以打消实现类似于可滑动的媒体库的念头吧（但是如果你想要关闭一些东西的时候，可以使用 [`SwiftUIPager`](https://github.com/fermoya/SwiftUIPager)）。在技术上你可以使用  `TabView` 加 `PageTabViewStyle`，但是我认为它更适合少部分的元素，而不是大的数据集。
```
我测试了一下，在掘金中只支持这样写：
```
[`SwiftUIPager`](https://github.com/fermoya/SwiftUIPager)
```

2022-09-02 14:47 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +我可能错了，但是 我在构建Share Extensions 时仍然使用了 UIKit。我通过 `UIHostingController` 用 SwiftUI 构建了一个分享扩展，当分享扩展加载完毕后，有一个非常明显的延迟，用户体验较差。你可以尝试通过在视图中添加动画去掩饰，但是仍然有 500 ms 左右的延迟。
```suggestion
我可能是错的，但是分享扩展还是使用 UIKit 吧。我通过 `UIHostingController` 用 SwiftUI 构建了一个分享扩展，当分享扩展加载完毕后，有一个非常明显的延迟，用户体验较差。你可以尝试通过在视图中添加动画去掩盖它，但是仍然有 500 毫秒左右的延迟。
```

2022-09-02 14:53 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +`TextField` 和 `TextEditor` 现在都太简单了，最终你还是会退回到 UIKit。所以我不得不为 `UITextField` 和 `UITextView` 构建自己的 `UIViewRepresentable`(自动增长支持)。要点如下：
补充：少了托管代码段的网站链接，我去找了原作者的Gist里也没有
我直接删了最后一句

2022-09-02 14:55 UTC, jaredliw commented
校对完成

语句略有不通顺的地方，还有就是标点的问题
感谢 @Lokfar 非常专业 应该下了不少心思
让我这个外行人只需要关注整体结构和中文内容就好了 xD

2022-09-06 03:13 UTC, jaredliw commented
@earthaYan 哈喽~

2022-09-06 07:29 UTC, earthaYan commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +如果你想在隐藏导航栏的同时仍然支持滑动手势，这是不可能的。我最终参考一些找到的代码创建了一个 [UINavigationController wrapper](https://gist.github.com/chrysb/d7d85e20d8c94fd3e0b753a4abd1c941)。尽管可以起作用，但这不是一个长远的解决方案。
此处赞同 @Lokfar 的校对意见：[wrapper为专业术语，无需翻译](https://github.com/xitu/gold-miner/pull/9392#discussion_r952426200)

2022-09-06 07:34 UTC, earthaYan commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
>  * [My takeaway from working with SwiftUI](https://link.medium.com/isXKLhaaCib)
此处参考文章标题是否应统一保持原文？

2022-09-06 07:35 UTC, earthaYan commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
>  ### 5. matchedGeometryEffect
这里需要添加``的原因是？

2022-09-06 07:40 UTC, earthaYan commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
>  * [SwiftUI Drawbacks: Why SwiftUI Is Not Ready for Production Yet](https://www.iosapptemplates.com/blog/swiftui/swiftui-drawbacks)
此处参考文章标题是否应统一保持原文？

2022-09-06 07:40 UTC, earthaYan commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +* [Is SwiftUI Ready？](https://www.jessesquires.com/blog/2021/07/01/is-swiftui-ready/)
此处参考文章标题是否应统一保持原文？

2022-09-06 07:46 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +如果你想在隐藏导航栏的同时仍然支持滑动手势，这是不可能的。我最终参考一些找到的代码创建了一个 [UINavigationController wrapper](https://gist.github.com/chrysb/d7d85e20d8c94fd3e0b753a4abd1c941)。尽管可以起作用，但这不是一个长远的解决方案。
有见过这一翻译
但问题不大 都能理解
译者自行定夺

2022-09-06 07:48 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
>  ### 5. matchedGeometryEffect
@earthaYan 
方法名/属性/类名/文件名……
我看下面部分有加部分没有（比如 ScrollView
统一就行

2022-09-06 07:53 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +* **主要的障碍:**  视图中的 `LazyVStack` 导致[卡顿、抖动和一些意外的行为](https://stackoverflow.com/questions/66523786/swiftui-putting-a-lazyvstack-or-lazyhstack-in-a-scrollview-causes-stuttering-a/67895804)。LazyVStacks 对于需
@earthaYan 
这是一个markdown的问题
星号在符号后面是不起作用的：

**主要的障碍：**视图中的 `LazyVStack`……

之前和lsvih商量过，星号加在冒号前即可

2022-09-06 07:58 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +* [Is SwiftUI Ready？](https://www.jessesquires.com/blog/2021/07/01/is-swiftui-ready/)
@earthaYan 
也行 我的习惯是翻译 所以就提了个POV 让译者看着办哈哈
但
[遇到完整的英文整句、特殊名词，其內容使用半角标点](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E9%81%87%E5%88%B0%E5%AE%8C%E6%95%B4%E7%9A%84%E8%8B%B1%E6%96%87%E6%95%B4%E5%8F%A5%E7%89%B9%E6%AE%8A%E5%90%8D%E8%AF%8D%E5%85%B6%E5%85%A7%E5%AE%B9%E4%BD%BF%E7%94%A8%E5%8D%8A%E8%A7%92%E6%A0%87%E7%82%B9)

2022-09-06 08:01 UTC, jaredliw commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
> +* **主要的障碍:**  视图中的 `LazyVStack` 导致[卡顿、抖动和一些意外的行为](https://stackoverflow.com/questions/66523786/swiftui-putting-a-lazyvstack-or-lazyhstack-in-a-scrollview-causes-stuttering-a/67895804)。LazyVStacks 对于需
还有就是这么改是因为 不希望在星号后加个空格：
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;↓
**主要的障碍：** 视图中的 LazyVStack……

[全角标点与其他字符之间不加空格](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E5%85%A8%E8%A7%92%E6%A0%87%E7%82%B9%E4%B8%8E%E5%85%B6%E4%BB%96%E5%AD%97%E7%AC%A6%E4%B9%8B%E9%97%B4%E4%B8%8D%E5%8A%A0%E7%A9%BA%E6%A0%BC)

2022-09-07 08:28 UTC, earthaYan commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
>  * [My takeaway from working with SwiftUI](https://link.medium.com/isXKLhaaCib)
统一保持原文不修改

2022-09-07 08:52 UTC, earthaYan commented on article/2021/swiftui-2021-the-good-the-bad-and-the-ugly.md
>  ### 5. matchedGeometryEffect
这部分的处理感觉还是与原文保持一致比较好？

2022-09-07 09:07 UTC, earthaYan commented
@jaredliw @Lokfar @lsvih 感谢校对，已根据校对意见修改，关于``使用问题，个人倾向于与原文保持一致，故选择不修改

2022-09-07 09:12 UTC, jaredliw commented
> @jaredliw @Lokfar @lsvih 感谢校对，已根据校对意见修改，关于``使用问题，个人倾向于与原文保持一致，故选择不修改

收到 没问题

2022-09-08 01:33 UTC, lsvih approved these changes

2022-09-08 01:33 UTC, merged

2022-09-08 02:14 UTC, earthaYan commented
@lsvih @Lokfar @jaredliw 已发布至掘金啦   https://juejin.cn/post/7140825514108780580/

2022-09-08 03:15 UTC, lsvih commented
收到