Update verifying-distributed-systems-isabelle
xitu/gold-miner pull request #9437
Opened 2022-11-04 10:37 UTC by wangxuanni

译文翻译完成，resolve #9428

2022-11-04 14:32 UTC, lsvih commented
标题里中英文也要空格哈~

2022-11-05 09:27 UTC, wangxuanni commented
> 标题里中英文也要空格哈~

好的嘞，已加

2022-11-05 09:28 UTC, wangxuanni commented
> 标题里中英文也要空格哈~

好的嘞

2022-11-07 02:02 UTC, lsvih commented
@Quincy-Ye 认领校对

2022-11-07 02:54 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +不幸的是，众所周知，分布式系统很难推理。因为无论消息到达的顺序，或者一些消息丢失，或者某些进程崩溃，它们都必须要确保其保证。许多算法非常微妙，非正式的推理不足以确保它们是正确的。此外，并发活动出现的排列和交错，这个可能性的数量很快就会变得太大，以至于模型检查器无法进行详尽的测试。出于这个原因，正式的正确性证明对于分布式算法很有价值。
```suggestion
不幸的是，众所周知，分布式系统很难推理。因为无论消息到达的顺序，或者一些消息丢失，或者某些进程崩溃，它们都必须要确保其保证。许多算法非常微妙，非正式的推理不足以确保它们是正确的。此外，并发活动出现的排列和交错，这个可能性的数量很快就会变得太大，以至于模型检查器无法进行详尽的测试。出于这个原因，正确性的正式证明对于分布式算法很有价值。
```

2022-11-07 02:54 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +在这篇博文里，我们将会探索怎么样使用 Isabelle/HOL 辅助证明，去正式的验证一些分布式算法。Isabelle/HOL 没有对分布式计算有任何内置的支持，不过幸运的是，可以十分简单的使用 Isabelle/HOL 提供的结构：方法，列表和集合，去建模一个分布式系统。
```suggestion
在这篇博文里，我们将会探索怎么样使用 Isabelle/HOL 辅助证明，去正式地验证一些分布式算法。Isabelle/HOL 没有对分布式计算有任何内置的支持，不过幸运的是，可以十分简单的使用 Isabelle/HOL 提供的结构：方法，列表和集合，去建模一个分布式系统。
```

2022-11-07 02:54 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +首先我们假设在系统里每一个进程（或**节点**）都有一个唯一的标识符，它可以简单的是一个整数或是一个字符串。根据算法，系统中一组进程 ID 可能是固定的和已知的，或者是未知的和不固定的（后者适用于进程们随时可以加入或离开的系统）。
```suggestion
首先，我们假设在系统里每一个进程（或**节点**）都有一个唯一的标识符，它可以简单的是一个整数或是一个字符串。根据算法，系统中一组进程 ID 可能是固定的和已知的，或者是未知的和不固定的（后者适用于进程们随时可以加入或离开的系统）。
```

2022-11-07 02:54 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +然后算法的执行以离散的时间步长进行。在每个时间步长中，一个事件发生在其中一个进程上。这个事件可能是这三件事中的之一：接收一个其他进程发送过来的消息，接收用户的输入或者是超时。
“的”和“之”，意思重复。
```suggestion
然后算法的执行以离散的时间步长进行。在每个时间步长中，一个事件发生在其中一个进程上。这个事件可能是这三件事中的一个：接收一个其他进程发送过来的消息，接收用户的输入或者是超时。
```

2022-11-07 02:54 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +## 为什么线性的时间步长序列就足够了
虽然原文没有，但是忍不住想补个问号
```suggestion
## 为什么线性的时间步长序列就足够了？
```

2022-11-07 02:54 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +进程在一个时间步骤的当前状态等于它在前一步骤之后的新状态（或者如果没有前一步骤，则为初始状态）。进程在一个时间步的当前状态等于同一进程在前一步之后的新状态（就是初始的状态）。假设 step 函数是确定性的，我们现在可以把系统里任何一个执行编码为（进程 ID ，事件）键值对的集合，表示发生的一系列事件，以及它们发生在哪个进程。系统的最终状态是通过一次调用一个事件的阶跃函数来获得的。
```suggestion
进程在一个时间步长的当前状态等于同一进程在前一步之后的新状态（如果没有前一步骤，则为初始状态）。假设 步长函数是确定性的，我们现在可以把系统里任何一个执行编码为（进程 ID ，事件）键值对的集合，表示发生的一系列事件，以及它们发生在哪个进程。系统的最终状态是通过一次调用一个事件的阶跃函数来获得的。
```

2022-11-07 02:54 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +## 去定义可能发生了什么
```suggestion
## 定义可能发生的事情
```

2022-11-07 02:54 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +为了证明分布式算法的正确性，我们需要证明它在每次可能的执行中产生正确的结果，也就是说对于每一个可能的（进程ID，事件）键值对集合。但哪一种执行是可能的？只有一件事是我们可以安全地假设的：如果一个进程接收到一条消息，那么该消息一定已经发送到该进程。换句话来说，我们假设网络不会凭空捏造消息，并且一个进程不能模拟另一个进程。（在攻击者可以注入虚假数据包的公共网络中，我们必须对消息进行加密验证以确保此属
```suggestion
为了证明分布式算法的正确性，我们需要展示在每个可能的执行中都产生的正确结果，即例举出所有可能的（processID, event） 键值对。但会执行哪一些呢？只有一件事是我们可以安全地假设的：如果一个进程接收到一条消息，那么该消息一定已经发送到该进程。换句话来说，我们假设网络不会凭空捏造消息，并且一个进程不能模拟另一个进程。（在攻击者可以注入虚假数据包的公共网络中，我们必须对消息进行加密验证以确保此属性，但现在让我们将其排除在范围之外。）
```

2022-11-07 02:54 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +首先，我们定义一个函数来告诉我们单个事件是否可能发生:如果事件 evt 被允许在系统中的进程 `proc` 中发生，`(valid_event evt proc msgs)` 会返回 true ，`msgs` `是迄今为止已发送的所有消息的集合`。 `msgs` 是（发件人、收件人、消息）的三元组。在整个系统里。我们定义一个接受事件是允许出现的，如果接收的消息是在 msgs 和 Request
```suggestion
首先，我们定义一个函数来告诉我们单个事件是否可能发生：如果事件 evt 被允许在系统中的进程 `proc` 中发生，`(valid_event evt proc msgs)` 会返回 true ，`msgs`  是迄今为止已发送的所有消息的集合。 `msgs` 是（发件人、收件人、消息）的三元组。在整个系统里。我们定义一个接受事件是允许出现的，如果接收的消息是在 msgs 和 Request 或者 Timeout 事件中，则允许事件发生，或者允许事件随时发生。
```

2022-11-07 02:54 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +这个定义的状态是，当系统处于初始状态且未发送任何消息时，空事件列表有效。此外，如果`events`是迄今为止有效的事件序列，并且event在当前状态下是允许的，那么我们可以调用 step 函数，添加它发送到`msgs`的任何消息，更新相应进程的状态，其返回值是另一个有效序列的事件。
states 在这里作为动词，that 引导后面的宾语从句。
```suggestion
该定义规定，当系统处于初始状态且未发送任何消息时，空事件列表有效。此外，如果 `events` 是迄今为止有效的事件序列，并且 `event` 在当前状态下是允许的，那么我们可以调用 step 函数，添加它发送到 `msgs` 的任何消息，更新相应进程的状态，其返回值是另一个有效序列的事件。
```

2022-11-07 02:54 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +这就是我们建模一个分布式系统所需要的全部！
```suggestion
这就是我们建模一个分布式系统所需要的全部内容！
```

2022-11-07 02:54 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +换句话说，我们证明 **P** 在整个系统所有可能的状态中是一个不变量。在Isabelle里，这证明看起来是粗糙的像这个 ( `step`, `init`, 和 `procs` 被适当的定义过):
```suggestion
换句话说，我们证明 **P** 在整个系统所有可能的状态中是一个不变量。在 Isabelle 里，这证明看起来是粗糙的像这个 ( `step`、 `init`、和  `procs`  被适当地定义过):
```

2022-11-07 02:54 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +有关如何在此模型中证明简单共识算法的正确性的更多详细信息，我录制了一个[2 小时的视频讲座](https://www.youtube.com/watch?v=Uav5jWHNghY) ，该讲座贯穿了第一原理的演示（无需之前有 Isabelle 的经验）。这个[演示的Isabelle 代码](https://gist.github.com/ept/b6872fc541a68a321a26198b5
```suggestion
有关如何在此模型中证明简单共识算法的正确性的更多详细信息，我录制了一个[2 小时的视频讲座](https://www.youtube.com/watch?v=Uav5jWHNghY) ，该讲座贯穿了第一原理的演示（无需之前有 Isabelle 的经验）。这个[演示的 Isabelle 代码](https://gist.github.com/ept/b6872fc541a68a321a26198b53b3896b)也是可用的。
```

2022-11-07 02:56 UTC, Quincy-Ye commented
@lsvih @wangxuanni 校对完毕。若有疑问，随机交流~

2022-11-09 11:05 UTC, wangxuanni commented
> @lsvih @wangxuanni 校对完毕。若有疑问，随机交流~

感谢校对，除了一个有疑，其他都修改啦

2022-11-09 11:09 UTC, Quincy-Ye commented on article/2022/verifying-distributed-systems-isabelle.md
> +这就是我们建模一个分布式系统所需要的全部！
因为我在读这句话的时候，读到“全部”，感觉好像没读完。所以加上“内容”，这样整句话读起来更加通顺一下。仅个人建议，尊重原译。

2022-11-11 09:21 UTC, vuuihc commented
@lsvih 请问还需校对吗，需要的话认领一下

2022-11-11 09:45 UTC, lsvih commented
@vuuihc 欢迎校对~

2022-11-13 11:17 UTC, wangxuanni commented on article/2022/verifying-distributed-systems-isabelle.md
> +这就是我们建模一个分布式系统所需要的全部！
感谢建议~  我想了一下，认为"所需要的全部"，已经能表达出意思了，语法上也是正确。因此，这条就恕不采纳啦。

2022-11-15 13:59 UTC, vuuihc requested changes

2022-11-15 13:59 UTC, vuuihc commented on article/2022/verifying-distributed-systems-isabelle.md
> +我们每天都以互联网服务的形式使用分布式系统。这些系统很有用，但实现起来也很有挑战性，因为网络是不可预料的。每当你发送一条网络消息时候，它有可能很快到达，也有可能延迟很久，或者永远不会达到，又或者多次到达。
> 网络消息时候 

网络消息的时候

2022-11-15 13:59 UTC, vuuihc commented on article/2022/verifying-distributed-systems-isabelle.md
> +当你向另一个进程发送请求但没有收到响应时，你完全不知道发生了什么，是这个请求丢失了，还是另一个进程崩溃了，或者是响应丢失了？或者可能没有任何东西丢失，消息只是延迟了，还没有到达。没有办法知道发生了什么，因为进程通信的唯一方式是不可靠的消息传递。
> 发生了什么，

发生了什么：

2022-11-15 13:59 UTC, vuuihc commented on article/2022/verifying-distributed-systems-isabelle.md
> +不幸的是，众所周知，分布式系统很难推理。因为无论消息到达的顺序，或者一些消息丢失，或者某些进程崩溃，它们都必须要确保其保证。许多算法非常微妙，非正式的推理不足以确保它们是正确的。此外，并发活动出现的排列和交错，这个可能性的数量很快就会变得太大，以至于模型检查器无法进行详尽的测试。出于这个原因，正确性的正式证明对于分布式算法很有价值。
> 因为无论消息到达的顺序，或者一些消息丢失，或者某些进程崩溃，它们都必须要确保其保证。

因为不论消息到达的顺序如何，他们都必须维护他们的保证，甚至是在一些消息丢失，或者一些进程奔溃的时候也如此。

2022-11-15 13:59 UTC, vuuihc commented on article/2022/verifying-distributed-systems-isabelle.md
> +不幸的是，众所周知，分布式系统很难推理。因为无论消息到达的顺序，或者一些消息丢失，或者某些进程崩溃，它们都必须要确保其保证。许多算法非常微妙，非正式的推理不足以确保它们是正确的。此外，并发活动出现的排列和交错，这个可能性的数量很快就会变得太大，以至于模型检查器无法进行详尽的测试。出于这个原因，正确性的正式证明对于分布式算法很有价值。
> 并发活动出现的排列和交错，这个可能性的数量很快就会变得太大

并发活动可能出现的排列和交织的数量，很快就变得太多

2022-11-15 13:59 UTC, vuuihc commented on article/2022/verifying-distributed-systems-isabelle.md
> +然后算法的执行以离散的时间步长进行。在每个时间步长中，一个事件发生在其中一个进程上。这个事件可能是这三件事中的一个：接收一个其他进程发送过来的消息，接收用户的输入或者是超时。
>  时间步长

建议直接叫 “时间步”？

2022-11-15 13:59 UTC, vuuihc commented on article/2022/verifying-distributed-systems-isabelle.md
> +2. 如果一些执行时，属性 **P** 的值为真，那么我们在执行结束时再添加一个时间步长，那么 **P** 在该时间步长之后仍然成立。
如果属性 **P** 对于某些执行为真

2022-11-15 14:24 UTC, vuuihc reviewed
校对完成，提了一些 suggestion

2022-11-15 14:24 UTC, vuuihc commented on article/2022/verifying-distributed-systems-isabelle.md
> +接下来，我们定义所有可能的事件序列集合。为此，我们在 Isabelle 中使用了一个判断断言：如果是算法属于执行中的有效事件集合，`(execute step init procs events msgs states)`则返回 true ，其中`step`是阶跃函数， `init` 是每个进程的初始状态，`proc`是系统中所有进程的集合（如果我们希望允许任意数量的进程，这可能是无限的）。最后
```suggestion
接下来，我们定义所有可能的事件序列集合。为此，我们在 Isabelle 中使用了一个归纳断言：如果 `events`是算法执行中的有效事件集合，`step`是阶跃函数， `init` 是每个进程的初始状态，`proc`是系统中所有进程的集合（如果我们希望允许任意数量的进程，这可能是无限的），那么 `(execute step init procs events msgs states)` 返回 true 。最后两个参数跟踪执行状态：`msgs` 是迄今为止发送的所有消息的集合，`states` 是从进程 ID 到该进程状态的映射。
```

2022-11-15 14:24 UTC, vuuihc commented on article/2022/verifying-distributed-systems-isabelle.md
> +该定义规定，当系统处于初始状态且未发送任何消息时，空事件列表有效。此外，如果 `events` 是迄今为止有效的事件序列，并且 `event` 在当前状态下是允许的，那么我们可以调用 step 函数，添加它发送到 `msgs` 的任何消息，更新相应进程的状态，其返回值是另一个有效序列的事件。
```suggestion
该定义规定，当系统处于初始状态且未发送任何消息时，空事件列表有效。此外，如果 `events` 是迄今为止有效的事件序列，并且 `event` 在当前状态下是允许的，那么我们可以调用 step 函数，添加它发送到 `msgs` 的任何消息，更新相应进程的状态，其返回值是另一个有效的事件序列。
```

2022-11-15 14:30 UTC, lsvih commented
@wangxuanni ~

2022-11-16 02:31 UTC, wangxuanni commented on article/2022/verifying-distributed-systems-isabelle.md
> +然后算法的执行以离散的时间步长进行。在每个时间步长中，一个事件发生在其中一个进程上。这个事件可能是这三件事中的一个：接收一个其他进程发送过来的消息，接收用户的输入或者是超时。
搜索了一下，大多都是翻译成时间步长，就按照这样翻译啦，比如 http://muchong.com/t-7324619-1

2022-11-16 02:33 UTC, wangxuanni commented
感谢校对，修改已提交~

2022-11-16 03:03 UTC, lsvih approved these changes

2022-11-16 03:03 UTC, merged

2022-11-16 03:03 UTC, lsvih commented
@wangxuanni   已经 merge 啦~ 快快麻溜发布到[掘金](https://juejin.im)然后给我发下链接，方便及时添加积分哟。

掘金翻译计划有自己的知乎专栏，你也可以投稿哈，推荐使用一个[好用的插件](https://chrome.google.com/webstore/detail/minimalist-markdown-edito/pghodfjepegmciihfhdipmimghiakcjf?hl=zh-CN)。
专栏地址：https://zhuanlan.zhihu.com/juejinfanyi

2022-11-16 03:33 UTC, wangxuanni commented
已发布掘金 https://juejin.cn/post/7166450887626326030
已发布知乎文章 https://zhuanlan.zhihu.com/p/583884597

2022-11-16 08:27 UTC, lsvih commented
收到~