translate: achieve-Next.js-mastery-build-a-sales-page-with-stripe-and…
xitu/gold-miner pull request #9554
Opened 2023-11-09 04:53 UTC by PassionPenguin

…-airtable

译文翻译完成，resolve #9527

2023-11-09 07:32 UTC, lsvih commented
还请赐个标题

2023-11-10 07:51 UTC, PassionPenguin commented on article/2023/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md
```suggestion
实现熟练使用 Next.js：使用 Stripe 和 Airtable 搭建一个销售页面

```

2023-11-10 07:51 UTC, PassionPenguin commented on article/2023/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md
> +实现熟练使用 Next.js：使用 Stripe 和 Airtable 搭建一个销售页面
```suggestion

# 实现熟练使用 Next.js：使用 Stripe 和 Airtable 搭建一个销售页面
```

2024-01-07 07:01 UTC, jeffery1995 commented
我可以参与校对

2024-01-07 07:04 UTC, jeffery1995 commented on article/2023/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md
> +> * 原文地址：[Achieve Next.js Mastery: Build a Sales Page with Stripe and Airtable](https://dev.to/triggerdotdev/achieve-Next.js-mastery-build-a-sales-page-with-stripe-and-airtable-1p5m)
`https://dev.to/triggerdotdev/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable-1p5m` 
应该是这个url

2024-01-07 07:06 UTC, jeffery1995 commented on article/2023/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md
> -> * 本文永久链接：[https://github.com/xitu/gold-miner/blob/master/article/2023/4achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md](https://github.com/xitu/gold-miner/blob/master/article/
同样的url问题

2024-01-07 07:10 UTC, jeffery1995 commented on article/2023/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md
> +[Trigger.dev](https://trigger.dev/) 是一个可以让你在 Next.js、Remix、Astro 等应用中创建和监视长时间运行的作业的开源库！
nit: 
`作业` ->`工作`

2024-01-18 11:47 UTC, PassionPenguin commented
> 您好，我可以参与校对

你好，感谢你的校对🙏，下次校对的时候可以开一个大的 Review 包含一大堆不同的 conversation 和 suggestion，这样方便我们沟通～

Thanks for your proofreading! Next time you proofread an article, or review any other code on GitHub, you may open a bigger Review that contains different conversation & suggestions, so that we can resolve it in a better way!

2024-01-18 11:51 UTC, PassionPenguin commented on article/2023/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md
> +> * 原文地址：[Achieve Next.js Mastery: Build a Sales Page with Stripe and Airtable](https://dev.to/triggerdotdev/achieve-Next.js-mastery-build-a-sales-page-with-stripe-and-airtable-1p5m)
> `https://dev.to/triggerdotdev/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable-1p5m` 应该是这个url

```suggestion
> * 原文地址：[Achieve Next.js Mastery: Build a Sales Page with Stripe and Airtable](https://dev.to/triggerdotdev/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable-1p5m)
```

2024-01-18 11:51 UTC, PassionPenguin commented on article/2023/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md
> +> * 本文永久链接：[https://github.com/xitu/gold-miner/blob/master/article/2023/4achieve-Next.js-mastery-build-a-sales-page-with-stripe-and-airtable.md](https://github.com/xitu/gold-miner/blob/master/article
```suggestion
> * 本文永久链接：[https://github.com/xitu/gold-miner/blob/master/article/2023/4achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md](https://github.com/xitu/gold-miner/blob/master/article/2023/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md)
```

2024-01-18 11:51 UTC, PassionPenguin commented on article/2023/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md
> +[Trigger.dev](https://trigger.dev/) 是一个可以让你在 Next.js、Remix、Astro 等应用中创建和监视长时间运行的作业的开源库！
> nit: `作业` ->`任务/工作`
```suggestion
[Trigger.dev](https://trigger.dev/) 是一个可以让你在 Next.js、Remix、Astro 等应用中创建和监视长时间运行任务的开源库！
```

2024-01-18 11:51 UTC, PassionPenguin commented on article/2023/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md
> +作为一名开源开发者，欢迎加入我们的[社区](https://discord.gg/nkqV9xBYWy)与维护人员一起贡献和交流。不要犹豫访问我们的 [GitHub Repo](https://github.com/triggerdotdev/trigger.dev) 以贡献并创建与 Trigger.dev 相关的问题。
```suggestion
作为一名开源开发者，欢迎加入我们的[社区](https://discord.gg/nkqV9xBYWy)与维护人员一起贡献和交流。不要犹豫访问我们的 [GitHub Repo](https://github.com/triggerdotdev/trigger.dev)，来一起为这个项目贡献自己力量，或者提出与 Trigger.dev 有关的 issue！
```

2024-01-18 11:53 UTC, PassionPenguin commented
> 您好，我可以参与校对

另，译者信息麻烦你自己提一个 suggestion 喔：）

btw, please make a suggestion to update the proofreader information~~

2024-01-22 09:25 UTC, jeffery1995 requested changes

2024-01-22 09:25 UTC, jeffery1995 commented on article/2023/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md
>  > * 校对者：
> * 校对者：[Jeffery](https://github.com/jeffery1995)

2024-01-23 11:16 UTC, jeffery1995 approved these changes

2024-04-17 09:44 UTC, PassionPenguin commented on article/2023/achieve-nextjs-mastery-build-a-sales-page-with-stripe-and-airtable.md
>  > * 校对者：
```suggestion
> * 校对者：[Jeffery](https://github.com/jeffery1995)
```

2024-04-17 09:46 UTC, yukui123 commented
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

2024-12-11 04:22 UTC, PassionPenguin commented
not to be maintained

2024-12-11 04:22 UTC, closed without merging

2024-12-11 04:23 UTC, yukui123 commented
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。