为什么命名是编写整洁代码的首要技能
xitu/gold-miner pull request #9566
Opened 2023-12-07 12:26 UTC by jaredliw

译文翻译完成，resolve #9530

2023-12-07 12:54 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +3.  `map` 中的匿名函数重复使用了名称 `a`, **遮蔽（shadowing）​**了作为函数参数的 `a`，使读者感到困惑，并可能导致我们在未来修改代码时引用错误的变量。
```suggestion
3.  `map` 中的匿名函数重复使用了名称 `a`，**遮蔽（shadowing）​**了作为函数参数的 `a`，使读者感到困惑，并可能导致我们在未来修改代码时引用错误的变量。
```

2023-12-07 12:54 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +最好的建议是，不要起名字，而是**找出**一个名字。你不应该像给宠物或孩子命名一样随意起一个自己的名字；相反，**你应寻找你所命名的事物的本质，并且名称应该基于它来呈现**。如果你不喜欢你找到的名称，则意味着你不喜欢你所命名的事物，并且你应该通过改进代码的设计来更改该名称（就像我们在例 #2 中所做的那样）。
```suggestion
最好的建议是，不要起名字，而是**找出**一个名字。你不应该像给宠物或孩子命名一样随意起一个自己的名字；相反，**你应寻找你所命名的事物的本质，并且名称应该基于此来呈现**。如果你不喜欢你找到的名称，则意味着你不喜欢你所命名的事物，并且你应该通过改进代码的设计来更改该名称（就像我们在例 #2 中所做的那样）。
```

2023-12-07 12:54 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +3.  **让名称与周围融合。​**它应该与其他名称有明确的关系，即，在同一个“世界”里。它应该与相似的事物相似，与相反的事物相反。它应该与周围的其他名称组成一个“故事”。它应该考虑所处的上下文。
```suggestion
3.  **让名称与周围融合。​**它应该与其他名称有明确的关系，即，在同一个“世界”里。它应该与相似的事物相似，与相反的事物相反。它应该与周围的其他名称组成一个“故事”，应考虑它所处的上下文。
```

2023-12-07 12:54 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +5.  **贯彻你在代码库中使用的术语。​**如果你一直以来使用的术语是 `server` 请不要混用 `backend`。此外，如果你使用了 `server` 一词，你或许不应该使用 `frontend`。`client` 这一术语与 `server` 更相关。
```suggestion
5.  **贯彻你在代码库中使用的术语。​**如果你一直以来使用的术语是 `server` 请不要混用 `backend`。此外，如果你使用了 `server` 一词，你或许不应该使用 `frontend`。`client` 与 `server` 更相关。
```

2023-12-07 12:54 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +不要过分坚持从一开始就找出完美的名称 → 你可以对代码进行多次迭代，每次迭代都会改进你的代码和名称。
```suggestion
不要过分执着于在一开始就找出完美的名称 → 你可以对代码进行多次迭代，每次迭代都会改进你的代码和名称。
```

2024-01-18 12:38 UTC, PassionPenguin requested changes
🥹 好久没看到翻译的这么出色的文章，让人校对都感觉很舒服（就像读母语者写的文章一样！）

一点点校对，辛苦啦：）

2024-01-18 12:38 UTC, PassionPenguin commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +我始终相信，写代码也亦是如此：只要我们能够为函数、变量和结构体找到好的名称，我们就能真正认识到问题的本质。**清晰之道不仅反映出好的名称，还有更整洁的代码和更稳健的架构。**
漏了 `we are solving`，=>我们就能真正认识到我们在解决的问题的本质

```suggestion
我始终相信，写代码也亦是如此：只要我们能够为函数、变量和结构体找到好的名称，我们就能真正认识到我们在解决的问题的本质。**清晰之道不仅反映出好的名称，还有更整洁的代码和更稳健的架构。**
```

2024-01-18 12:38 UTC, PassionPenguin commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +![取名在编程中的重要性](https://res.cloudinary.com/practicaldev/image/fetch/s--V94wO-D0--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_800/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/i9egdxs8uo4
取名or命名？译者可能要选择一个，然后全文统一一下下！

2024-01-18 12:38 UTC, PassionPenguin commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +我甚至可以说，**要想写好整洁的代码，仅仅是取好名称就已完成 90% 了。**
除非整一句话的格式，不然建议还是不要包含标点符号：）

```suggestion
我甚至可以说，**要想写好整洁的代码，仅仅是取好名称就已完成 90% 了**。
```

2024-01-18 12:38 UTC, PassionPenguin commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
>  ```
这里，辛苦译者加上代码格式，ts/js都行
dev.to的代码格式添加和其他网站不太一样，turndown的时候都会丢失

2024-01-18 12:38 UTC, PassionPenguin commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +这个代码有什么问题？
用“段”可能更合适？

```suggestion
这段代码有什么问题？
```

2024-01-18 12:38 UTC, PassionPenguin commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +5.  `.info` 字段这个名称也**不能告诉我们任何有关其内容的信息**。更糟糕的是，由于我们是通过下标访问元素，如果他们的顺序发生变化，我们的代码将会在毫无征兆下出错。
毫无征兆 <=> prone to 不太符合，prone to 表倾向（可能），原文应该是：

同样也隐藏了他们的信息，让我们的代码，如果元素的排序有所变更，倾向于不被人发现地错误运行。

2024-01-18 12:38 UTC, PassionPenguin commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +一旦您开始深入思索命名的问题，你将见识到它如何改变你的代码审查过程：焦点从查看实现细节转移到首先查看名称。
您/你混用了

2024-01-18 12:38 UTC, PassionPenguin commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +## 增广
似乎……很少用增广翻译further reading诶……？

2024-01-18 12:38 UTC, PassionPenguin commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +> * 校对者：
```suggestion
> * 校对者：[霜羽 Hoarfroster](https://github.com/PassionPenguin)
```

2024-01-19 01:14 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +![取名在编程中的重要性](https://res.cloudinary.com/practicaldev/image/fetch/s--V94wO-D0--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_800/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/i9egdxs8uo4
```suggestion
![命名在编程中的重要性](https://res.cloudinary.com/practicaldev/image/fetch/s--V94wO-D0--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_800/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/i9egdxs8uo4256ioir3x.png)
```

2024-01-19 01:14 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +### 取名的技巧
```suggestion
### 命名的技巧
```

2024-01-19 01:17 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +一旦您开始深入思索命名的问题，你将见识到它如何改变你的代码审查过程：焦点从查看实现细节转移到首先查看名称。
```suggestion
一旦你开始深入思索命名的问题，你将见识到它如何改变你的代码审查过程：焦点从查看实现细节转移到首先查看名称。
```

2024-01-19 01:19 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +## 增广
确实有点离谱 哈哈哈哈

```suggestion
## 延伸阅读
```

2024-01-19 01:26 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +5.  `.info` 字段这个名称也**不能告诉我们任何有关其内容的信息**。更糟糕的是，由于我们是通过下标访问元素，如果他们的顺序发生变化，我们的代码将会在毫无征兆下出错。
```suggestion
5.  `.info` 字段这个名称也**不能告诉我们任何有关其内容的信息**。更糟糕的是，由于我们是通过下标访问元素，如果它们的顺序有所变更，我们的代码将更倾向于在不被发现的情况下错误运行。
```

2024-01-19 01:29 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +![取名在编程中的重要性](https://res.cloudinary.com/practicaldev/image/fetch/s--V94wO-D0--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_800/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/i9egdxs8uo4
已统一，但像是“取一个好名字”这种句式的我就保留“取”了，“命一个好名字”有些奇怪？

2024-01-19 01:32 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +我始终相信，写代码也亦是如此：只要我们能够为函数、变量和结构体找到好的名称，我们就能真正认识到问题的本质。**清晰的结果不仅是好的名称，还有更整洁的代码和更稳健的架构。**
```suggestion
我始终相信，写代码也亦是如此：只要我们能够为函数、变量和结构体找到好的名称，我们就能真正认识到我们在解决的问题的本质。**清晰之道不仅反映出好的名称，还有更整洁的代码和更稳健的架构。**
```

2024-01-19 01:32 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
> +我始终相信，写代码也亦是如此：只要我们能够为函数、变量和结构体找到好的名称，我们就能真正认识到问题的本质。**清晰之道不仅反映出好的名称，还有更整洁的代码和更稳健的架构。**
已更改

2024-01-19 01:33 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
>  ```
```suggestion
```javascript
```

2024-01-19 01:35 UTC, jaredliw commented on article/2023/why-naming-is-1-skill-for-writing-clean-code.md
>  ```
全都加上了

2024-01-19 01:44 UTC, jaredliw commented
> 🥹 好久没看到翻译的这么出色的文章，让人校对都感觉很舒服（就像读母语者写的文章一样！）
> 
> 一点点校对，辛苦啦：）

@PassionPenguin 
谬赞了哈，但还是非常感谢你的肯定（翻译时确实用了点心思 xD
已根据校对意见修改完成，你可以过目一下~

2024-01-20 03:36 UTC, jaredliw commented
@lsvih 来看看呗

2024-01-21 07:29 UTC, lsvih approved these changes

2024-01-21 07:30 UTC, lsvih commented
俺认为没有什么需要修改的了，真流畅

2024-01-21 07:30 UTC, lsvih commented
俺认为没有什么需要修改的了，真流畅

2024-01-21 07:30 UTC, merged

2024-01-22 07:28 UTC, jaredliw commented
@lsvih 不计积分吗？

2024-01-22 08:17 UTC, lsvih commented
@jaredliw 记呀记呀，您把链接发一下哈

2024-01-22 13:00 UTC, jaredliw commented
> @jaredliw 记呀记呀，您把链接发一下哈

@lsvih 好的哈哈
https://juejin.cn/spost/7326759323064434723

2024-01-23 01:15 UTC, lsvih commented
收到~